### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by KaedieCat36** [anegostudios/VintageStory-Issues#3586] opened 2024-02-14 22:50 UTC
### Game Version

1.19.3

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Everytime I click on one of my worlds, the game crashes. I'm not sure why. Please help

### Screenshots

![Screenshot 2024-02-14 164711](https://github.com/anegostudios/VintageStory-Issues/assets/160078514/0b487810-d989-401e-a883-8a7ec183e536)

### Logs

```Log```
Running on 64 bit Windows 10.0.22621.0 with 8029 MB RAM
Game Version: v1.19.3 (Stable)
2/14/2024 4:40:39 PM: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Common.WorldConfig.loadWorldConfigValuesFromPlaystyle() in VintagestoryLib\Common\Config\WorldConfig.cs:line 107
   at Vintagestory.Common.WorldConfig.selectPlayStyle(String playstylecode) in VintagestoryLib\Common\Config\WorldConfig.cs:line 98
   at Vintagestory.Common.WorldConfig.loadFromSavegame(SaveGame savegame) in VintagestoryLib\Common\Config\WorldConfig.cs:line 56
   at Vintagestory.Client.GuiScreenSingleplayerModify.initGui(SaveGame savegame) in VintagestoryLib\Client\MainMenu\Screens\Singleplayer\GuiScreenSingleplayerModify.cs:line 44
   at Vintagestory.Client.GuiScreenSingleplayerModify.OnScreenLoaded() in VintagestoryLib\Client\MainMenu\Screens\Singleplayer\GuiScreenSingleplayerModify.cs:line 168
   at Vintagestory.Client.ScreenManager.LoadScreen(GuiScreen screen) in VintagestoryLib\Client\ScreenManager.cs:line 944
   at Vintagestory.Client.GuiScreenSingleplayer.OnClickCellRight(Int32 cellIndex) in VintagestoryLib\Client\MainMenu\Screens\Singleplayer\GuiScreenSingleplayer.cs:line 154
   at Vintagestory.API.Client.GuiElementMainMenuCell.OnMouseUpOnElement(MouseEvent args, Int32 elementIndex) in VintagestoryApi\Client\UI\Elements\Impl\Misc\GuiElementMainMenuCell.cs:line 319
   at Vintagestory.API.Client.GuiElementCellList`1.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementCellList.cs:line 240
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\GuiElement.cs:line 719
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 445
   at GuiScreen.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\MainMenu\Screens\Special\GuiScreen.cs:line 204
   at Vintagestory.Client.ScreenManager.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\ScreenManager.cs:line 889
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 211
   at OpenTK.Windowing.Desktop.NativeWindow.OnMouseUp(MouseButtonEventArgs e)
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.NativeWindow.ProcessWindowEvents(Boolean waitForEvents)
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2/14/2024 4:35:19 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.3.0, time stamp: 0x65310000
Faulting module name: coreclr.dll, version: 7.0.1624.6629, time stamp: 0x65a740d6
Exception code: 0xc00000fd
Fault offset: 0x00000000000d1de3
Faulting process id: 0x0x3bc8
Faulting application start time: 0x0x1da5f95d08825c9
Faulting application path: C:\Users\Mason\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.16\coreclr.dll
Report Id: fe8bc12f-a4be-474a-8903-e30fba838d5f
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 2/13/2024 9:36:25 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.3.0, time stamp: 0x65310000
Faulting module name: coreclr.dll, version: 7.0.1023.36312, time stamp: 0x64b06d6c
Exception code: 0xc00000fd
Fault offset: 0x00000000000df4b3
Faulting process id: 0x0x2f30
Faulting application start time: 0x0x1da5ef6f6bc998c
Faulting application path: C:\Users\Mason\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.10\coreclr.dll
Report Id: be685059-a4c3-4baa-87c6-f5115fbfeceb
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 2/13/2024 9:35:59 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.3.0, time stamp: 0x65310000
Faulting module name: coreclr.dll, version: 7.0.1023.36312, time stamp: 0x64b06d6c
Exception code: 0xc00000fd
Fault offset: 0x00000000001767e7
Faulting process id: 0x0x5c74
Faulting application start time: 0x0x1da5ef6aead436f
Faulting application path: C:\Users\Mason\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.10\coreclr.dll
Report Id: 231e55d8-5909-4148-aca1-33302c184b93
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment] 2024-02-15 08:10
Duplicate of #2692

**Closed by Craluminum2413** 2024-02-15 08:10 UTC
Labels: status: new
