### ISSUE TITLE
Game crashes within 1-2 mins of loading save, fruit tree related?

### ISSUE THREAD

**Issue by neue** [anegostudios/VintageStory-Issues#2510] opened 2023-03-24 16:49 UTC
### Game Version

v1.17.11 

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Game crashed as I was wandering around a large mountain formation, I reloaded then walked back in the same direction and saved. Now it crashes around the same place about one or two minutes after loading the save every time you load it.

I've included a link to the save here if that helps https://mega.nz/file/3okF3KjK#a1wswggA69q-76GzO21y40CRrRn7M0TWYbkHKUvMWd8

### How to reproduce

Open the save and stand still, something causes it to crash in that area from just standing still or walking to the right, If you run to the left you can leave the area before the what causes the crash to happen happens.

### Screenshots

![2023-03-24_16-41-01](https://user-images.githubusercontent.com/27670/227588391-0d5ff353-7da1-405c-b6f2-85d7e506d336.png)

### Logs

```Log```
Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.17.11 (Stable)
24/03/2023 4:23:50 PM: Critical error occurred
Loaded Mods: game@1.17.11, creative@1.17.11, survival@1.17.11
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityFruitTreePart.GenFoliageMesh(Boolean withSticks, MeshData& foliageMesh, MeshData& sticksMesh) in VSSurvivalMod\Systems\FruitTree\BEFruitTreePart.cs:line 212
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.GenMeshes() in VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:line 250
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.GenMesh() in VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:line 236
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldForResolving) in VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:line 386
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(Packet_BlockEntity p, ClientMain game) in VintagestoryLib\Client\Model\ClientChunk.cs:line 422
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 817
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 1138
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 123
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 678
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 622
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 124
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 23/03/2023 8:22:52 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1857557184126262820, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.11.0
P3: 63e108be
P4: KERNELBASE.dll
P5: 10.0.19041.2728
P6: e7e53a4e
P7: c0020001
P8: 000000000002cd29
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER169A.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_4f14cb37fe7b85e2ed7b3b85a54ece8c4d43adc2_1112ccc3_92030fbc-178e-4598-9437-da9c8ec2f908

Analysis symbol: 
Rechecking for solution: 0
Report Id: 818eefcc-9c9a-4b46-828e-a1d815815d68
Report Status: 268566528
Hashed bucket: e0279c219ddd09df69c75e6acdd21e24
Cab Guid: 0 }
--------------
{ TimeGenerated = 23/03/2023 8:22:51 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.11.0
P3: 63e108be
P4: KERNELBASE.dll
P5: 10.0.19041.2728
P6: e7e53a4e
P7: c0020001
P8: 000000000002cd29
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_4f14cb37fe7b85e2ed7b3b85a54ece8c4d43adc2_1112ccc3_92030fbc-178e-4598-9437-da9c8ec2f908

Analysis symbol: 
Rechecking for solution: 0
Report Id: 818eefcc-9c9a-4b46-828e-a1d815815d68
Report Status: 131076
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 23/03/2023 8:22:50 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.17.11.0, time stamp: 0x63e108be
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2728, time stamp: 0xe7e53a4e
Exception code: 0xc0020001
Fault offset: 0x000000000002cd29
Faulting process ID: 0x6850
Faulting application start time: 0x01d95dc4fa7ff9f2
Faulting application path: C:\Users\neue\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 818eefcc-9c9a-4b46-828e-a1d815815d68
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment] 2023-03-24 16:54
Duplicate of #2102

**Closed by Craluminum2413** 2023-03-24 16:54 UTC
Labels: status: new
