### ISSUE TITLE
this still in 1.18 rc 6

### ISSUE THREAD

**Issue by KeiMuriKoe** [anegostudios/VintageStory-Issues#2600] opened 2023-04-16 20:40 UTC
### Game Version

v1.18 rc 6

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

Any pie, after being cut, is divided into 3 + 1 parts that do not stack, while having identical characteristics.
There may be some logic to it, but I don't understand it.
https://youtu.be/7Fa_hguTVk4

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2023-04-16 20:43
Duplicate of #2316

**Closed by Craluminum2413** 2023-04-16 20:43 UTC
Labels: status: new
