### ISSUE TITLE
Crash when trying to open Mod manager

### ISSUE THREAD

**Issue by RaffiaD** [anegostudios/VintageStory-Issues#3269] opened 2023-12-02 18:46 UTC
### Game Version

v.1.19.0-pre7

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

When I try to open the Mod Manager, the game just crashes.

### How to reproduce

1. Have the mods that I have installed
2. Open Mod Manager
3. Crash

### Screenshots

![Screenshot_8](https://github.com/anegostudios/VintageStory-Issues/assets/31040060/85de429d-6c83-42f2-b8eb-576e1f14f058)

### Logs

Running on 64 bit Windows with 10238 MB RAM
Game Version: v1.19.0-pre.7 (Unstable)
02.12.2023 19:38:50: Critical error occurred
Loaded Mods: game@1.19.0-pre.7, wlts@1.0.0, carryon@1.7.0-pre.2, herbarium@1.0.0, hudclock@3.2.1, prospectorinfo@4.3.0, creative@1.19.0-pre.7, survival@1.19.0-pre.7, wildfarmingrevival@1.1.6, wildcraftfruit@1.0.1
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.GuiElementModCell..ctor(ICoreClientAPI capi, ModCellEntry cell, ElementBounds bounds, IAsset warningIcon) in VintagestoryLib\Client\MainMenu\Screens\GuiElementModCell.cs:line 74
   at Vintagestory.Client.GuiScreenMods.createCellElem(ModCellEntry cell, ElementBounds bounds) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenMods.cs:line 176
   at Vintagestory.API.Client.GuiElementCellList`1.AddCell(T cell, Int32 afterPosition) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementCellList.cs:line 204
   at Vintagestory.API.Client.GuiElementCellList`1.Initialize() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementCellList.cs:line 106
   at Vintagestory.API.Client.GuiElementCellList`1.BeforeCalcBounds() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementCellList.cs:line 140
   at Vintagestory.API.Client.GuiComposer.Compose(Boolean focusFirstElement) in VintagestoryApi\Client\UI\GuiComposer.cs:line 365
   at Vintagestory.Client.GuiScreenMods.InitGui() in VintagestoryLib\Client\MainMenu\Screens\GuiScreenMods.cs:line 139
   at Vintagestory.Client.GuiScreenMods..ctor(ScreenManager screenManager, GuiScreen parentScreen) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenMods.cs:line 24
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Vintagestory.Client.ScreenManager.LoadAndCacheScreen(Type screenType) in VintagestoryLib\Client\ScreenManager.cs:line 917
   at Vintagestory.Client.GuiCompositeMainMenuLeft.OnMods() in VintagestoryLib\Client\MainMenu\Composite\GuiCompositeMainMenuLeft.cs:line 303
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 304
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\GuiElement.cs:line 714
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 290
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 445
   at Vintagestory.Client.GuiCompositeMainMenuLeft.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\MainMenu\Composite\GuiCompositeMainMenuLeft.cs:line 362
   at GuiScreen.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\MainMenu\Screens\Special\GuiScreen.cs:line 198
   at Vintagestory.Client.ScreenManager.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\ScreenManager.cs:line 883
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 213
   at OpenTK.Windowing.Desktop.NativeWindow.OnMouseUp(MouseButtonEventArgs e)
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 322
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.GuiElementModCell..ctor(ICoreClientAPI capi, ModCellEntry cell, ElementBounds bounds, IAsset warningIcon) in VintagestoryLib\Client\MainMenu\Screens\GuiElementModCell.cs:line 74
   at Vintagestory.Client.GuiScreenMods.createCellElem(ModCellEntry cell, ElementBounds bounds) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenMods.cs:line 176
   at Vintagestory.API.Client.GuiElementCellList`1.AddCell(T cell, Int32 afterPosition) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementCellList.cs:line 204
   at Vintagestory.API.Client.GuiElementCellList`1.Initialize() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementCellList.cs:line 106
   at Vintagestory.API.Client.GuiElementCellList`1.BeforeCalcBounds() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementCellList.cs:line 140
   at Vintagestory.API.Client.GuiComposer.Compose(Boolean focusFirstElement) in VintagestoryApi\Client\UI\GuiComposer.cs:line 365
   at Vintagestory.Client.GuiScreenMods.InitGui() in VintagestoryLib\Client\MainMenu\Screens\GuiScreenMods.cs:line 139
   at Vintagestory.Client.GuiScreenMods..ctor(ScreenManager screenManager, GuiScreen parentScreen) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenMods.cs:line 24
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

**Comment by RaffiaD** [comment] 2023-12-02 18:47
I had an empty folder in there, got it fixed.

**Comment by Craluminum2413** [comment] 2023-12-04 20:42
Duplicate of #3239

**Closed by Craluminum2413** 2023-12-04 20:42 UTC
Labels: status: new
