### ISSUE TITLE
1.18.6 shield bug

### ISSUE THREAD

**Issue by Prinzip** [anegostudios/VintageStory-Issues#2866] opened 2023-06-29 16:07 UTC
### Game Version

1.18.6

### Platform

None

### Modded

None

### SP/MP

None

### Description

if placing a shield on wall, the shield is unvissible.

video: https://cdn.discordapp.com/attachments/334233095374897152/1124007835752202300/2023-06-29_18-05-08.mp4

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2023-06-29 16:12
Duplicate of #2859

**Closed by Craluminum2413** 2023-06-29 16:12 UTC
Labels: status: new
