### ISSUE TITLE
Render crash of pulverizer

### ISSUE THREAD

**Issue by Criperum** [anegostudios/VintageStory-Issues#1184] opened 2021-07-17 15:57 UTC
**Game Version:** 1.15.1 
**Platform:** Windows 
**Modded:** No 

### Description
Pulverizer crash.

### How to reproduce
Not sure about exact steps. I was filling pulv with parts. May be the reason is it was connected to moving axle at that moment.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.1 (Stable)17.07.2021 17:15:52: Critical error occurred
System.IndexOutOfRangeException: Индекс находился вне границ массива.
   в Vintagestory.GameContent.Mechanics.PulverizerRenderer.UpdateLightAndTransformMatrix(Int32 index, Vec3f distToCamera, Single rotation, IMechanicalPowerRenderable dev)
   в Vintagestory.GameContent.Mechanics.MechBlockRenderer.UpdateCustomFloatBuffer()
   в Vintagestory.GameContent.Mechanics.PulverizerRenderer.OnRenderFrame(Single deltaTime, IShaderProgram prog)
   в Vintagestory.GameContent.Mechanics.MechNetworkRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage)
   в Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   в Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   в Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   в Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   в _LpTdfLOAWwrFBtCzFbbeuEgj89qb._BdAGMFwyOn5tRjrJ2AiJBfbgDkH(Single )
   в _RWDpUP9pNIFCL1enbZzYqmh8eRe._rmjRcUg6ZZy8gFclAtdmfo8RemC(Single )
   в _RWDpUP9pNIFCL1enbZzYqmh8eRe._uf2x7pSJniCpFh7nbMvuI5iHIsh(Single )
   в Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   в System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   в OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   в OpenTK.GameWindow.DispatchRenderFrame()
   в OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   в _dWMiVfUAappivvjgQTrHbayLaP6._JCfAsRVSY5s6xyZG4pMiBR26lu(_mzzuiHzecediUg7OL4KPB2bLyPO , String[] )
   в _75U2lTywrsd0KIurOPIOvOxQoiH._JCfAsRVSY5s6xyZG4pMiBR26lu(ThreadStart )
```

**Comment by Craluminum2413** [comment] 2021-07-17 16:03
Duplicate of #1166

**Comment by copygirl** [comment] 2021-07-17 16:26
Indeed. Thanks for reporting, however!

**Closed by copygirl** 2021-07-17 16:26 UTC
Labels: status: duplicate
