### ISSUE TITLE
Glider works after being taken off

### ISSUE THREAD

**Issue by Zelger98** [anegostudios/VintageStory-Issues#2459] opened 2023-03-09 14:39 UTC
### Game Version

v1.18-pre5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

After taking off the glider it still works for as long as it is in your inventory it seems.

### Screenshots

https://user-images.githubusercontent.com/126715524/224058057-ec75d2e9-08fa-4155-9f59-08b987ba4e34.mp4

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2023-03-09 14:44
Have you tried to fly without having glider in your inventory?

**Comment by Zelger98** [comment] 2023-03-09 17:18
It has to be in my inventory. When I throw it away or have it in my hotbar
I stop being able to glide.

2023-03-09, kt, 16:44 Craluminum2413 ***@***.***> rašė:

**Comment by Craluminum2413** [comment] 2023-04-20 15:40
Fixed in 1.18.0 stable

**Comment by eugeneko** [comment] 2023-08-14 11:05
@Craluminum2413 I used this bug in 1.18.5, so consider reopening.

**Comment by korobya** [comment] 2024-01-17 10:54
cannot reproduce in 1.19.0-rc.8

**Closed** 2024-01-17 11:04 UTC
Labels: status: resolved, priority: medium, department: code, version: 1.18
