### ISSUE TITLE
Charcoal drawing may extend beyond the block boundaries

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#991] opened 2021-06-12 11:52 UTC
**Game Version:** 1.15.0-pre.3
**Platform:** Windows
**Modded:** No

### Description
Charcoal drawing may extend beyond the block boundaries, if placed close to boundary
 
### How to reproduce
1. Press RMB near the boundaries of the rock with charcoal / coke
2. Drawing goes beyond the boundaries of the block

### Screenshots
![2021-06-12_14-44-45](https://user-images.githubusercontent.com/69315569/121774811-bf48a080-cb8c-11eb-8169-88f18804cddd.png)

**Comment by Saricane** [comment] 2021-06-12 18:37
How do you select the pattern to draw ? I only have the "small hut", no list, no choice.

**Comment by Craluminum2413** [comment] 2021-06-12 18:41
@Saricane Press "F" holding charcoal/coke

**Comment by Saricane** [comment] 2021-06-12 18:47
Thank you. I have found another bug with cave art, I open another issue.

**Comment by Craluminum2413** [comment] 2021-06-16 13:12
I found a feature ![2021-06-16_16-09-50](https://user-images.githubusercontent.com/69315569/122225255-92162e00-cebd-11eb-83dc-fb077d1ae4d4.png)

**Comment by radfast** [comment] 2021-06-17 08:42
@Craluminum2413   The original issue will be fixed in `1.15-pre.4`

![image](https://user-images.githubusercontent.com/6842258/122362717-46609480-cf50-11eb-9186-cf1e4405ec3f.png)

@Saricane   You use the toolmode (F) key to select the shape.  This information will be added to the Handbook for `1.15-pre.4`

@Craluminum2413   Please can you tell me exact steps to reproduce this "feature"?  From the video it looks like you are just aiming charcoal at sandstone rock, but normally that should draw 1 piece of art

**Comment by Craluminum2413** [comment] 2021-06-17 08:49
@radfast The bottom two right voxels
![image](https://user-images.githubusercontent.com/69315569/122363904-00acc780-cf62-11eb-84bc-533e0f2651e8.png)

**Comment by Craluminum2413** [comment] 2021-06-21 10:08
Actually the whole voxel is causing this

**Comment by radfast** [comment] 2021-07-01 00:49
Thanks @Craluminum2413.   Found and fixed the issue for next build.   Unfortunately any existing cave art with this visual issue will still have the issue, but new art drawn on that specific bottom-right voxel should be shown OK.

**Closed by radfast** 2021-07-01 00:49 UTC
Labels: department: code, status: in-progress, target: survival
