### ISSUE TITLE
Rush matting reappearing/duplicating.

### ISSUE THREAD

**Issue by Rottyfoot** [anegostudios/VintageStory-Issues#1243] opened 2021-08-02 21:38 UTC
**Game Version:** 1.15.3
**Platform:** Windows 10
**Modded:** No

### Description
I placed two rush matting on the ground and broke the blocks to remove them. Upon leaving and returning they reappeared and were able to be destroyed and picked up again. I repeated this multiple times and they reappeared each time. It should also be noted that on one attempt, the blocks the mats were placed on were removed entirely. I left, returned, placed the blocks back, whereupon the mats appeared on the ground as if they had been destroyed.

### How to reproduce
1. Place Rush Matting on a block.
2. Remove the block the mat is placed on, and immediately place it back.
3. Move far enough away that the chunk the mat was in is unloaded.
4. Return to the location you placed the mat.
5. If done properly, the mat should reappear. I have been able to repeat this process indefinitely.

**Comment by Craluminum2413** [comment] 2021-08-02 21:40
Duplicate of #992

**Closed** 2021-08-03 05:05 UTC
Labels: status: duplicate
