### ISSUE TITLE
Cutting cattails or thule with a scythe causes a crash every few swings

### ISSUE THREAD

**Issue by ShnitzelKiller** [anegostudios/VintageStory-Issues#3791] opened 2024-04-08 07:48 UTC
### Game Version

1.19.7

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

When using a scythe to cut cattails in large quantities, or any other 2-high crops like thule, after a few swings I will be kicked from the server because "the client caused an unhandled exception". This will always happen without fail after around 5-10 swings of the scythe.

Most recently I crashed to desktop upon trying to rejoin the server (log attached). It now crashes reliably every time I try to join the server.

### How to reproduce

1. Cut cattails or thule in large groups
2. Repeat until crash (should be around  minute or less if you're doing it constantly)

### Logs
*CRASH 1*:
```Log
Running on 64 bit Windows 10.0.22631.0 with 31884 MB RAM
Game Version: v1.19.7 (Stable)
4/8/2024 12:41:33 AM: Critical error occurred
Loaded Mods: aculinaryartillery@1.1.4, betterdrifters@2.1.3, glowingarrows@1.2.0, HangingOilLamps@1.0.1, instanddrifterdrops@1.1.0, millwright@1.1.4, MoveLikeKaji@0.0.5, primitivesurvival@3.5.1, game@1.19.7, alchemy@1.6.31, animationmanagerlib@0.7.12, canjewelry@0.2.25, carryon@1.7.4, commonlib@2.3.7, expandedfoods@1.6.9, herbarium@1.1.0, sailboat@1.3.0, playerlist@1.8.0, rivers@2.7.0, sharablewaypoints@1.5.4, stonebakeoven@1.1.3, tieredsuperiority@1.1.1, trailmod@1.0.7, vhfp@1.1.0, creative@1.19.7, vsinstruments@1.2.7, vsquest@1.2.0, survival@1.19.7, vsvillage@1.0.0-pre.2, wildfarmingrevival@1.1.8, xlib119@0.7.4-dev.1191, bullseye-continued@2.5.8, doffanddonagain@4.0.0, playercorpse@1.9.0, simplewinddirection@1.0.2, stonequarry@3.2.1, wildcraftfruit@1.1.1, wildcraftherb@0.0.0, wildcrafttree@1.1.0, xskills119@0.7.5-dev.1191
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 49
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 815
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 731
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

```
*CRASH 2* (after trying to rejoin again)
```Log
Running on 64 bit Windows 10.0.22631.0 with 31884 MB RAM
Game Version: v1.19.7 (Stable)
4/8/2024 12:50:23 AM: Critical error occurred
Loaded Mods: aculinaryartillery@1.1.4, betterdrifters@2.1.3, glowingarrows@1.2.0, HangingOilLamps@1.0.1, instanddrifterdrops@1.1.0, millwright@1.1.4, MoveLikeKaji@0.0.5, primitivesurvival@3.5.1, game@1.19.7, alchemy@1.6.31, animationmanagerlib@0.7.12, canjewelry@0.2.25, carryon@1.7.4, commonlib@2.3.7, expandedfoods@1.6.9, herbarium@1.1.0, sailboat@1.3.0, playerlist@1.8.0, rivers@2.7.0, sharablewaypoints@1.5.4, stonebakeoven@1.1.3, tieredsuperiority@1.1.1, trailmod@1.0.7, vhfp@1.1.0, creative@1.19.7, vsinstruments@1.2.7, vsquest@1.2.0, survival@1.19.7, vsvillage@1.0.0-pre.2, wildfarmingrevival@1.1.8, xlib119@0.7.4-dev.1191, bullseye-continued@2.5.8, doffanddonagain@4.0.0, playercorpse@1.9.0, simplewinddirection@1.0.2, stonequarry@3.2.1, wildcraftfruit@1.1.1, wildcraftherb@0.0.0, wildcrafttree@1.1.0, xskills119@0.7.5-dev.1191
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.IOException: Cannot open worldmap database file C:\Users\James\AppData\Roaming\VintagestoryData\Maps\44d6c5a0-5633-472c-bebf-1425b5030ef2.db, it seems to be not writable!
   at Vintagestory.API.Common.SQLiteDBConnection.OpenOrCreate(String filename, String& errorMessage, Boolean requireWriteAccess, Boolean corruptionProtection, Boolean doIntegrityCheck) in VintagestoryApi\Common\IO\SQLiteDBConnection.cs:line 42
   at Vintagestory.GameContent.ChunkMapLayer..ctor(ICoreAPI api, IWorldMapManager mapSink) in VSEssentials\Systems\WorldMap\ChunkLayer\ChunkMapLayer.cs:line 109
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Vintagestory.GameContent.WorldMapManager.OnLvlFinalize() in VSEssentials\Systems\WorldMap\WorldMapManager.cs:line 193
   at Vintagestory.Client.NoObf.ClientEventAPI.TriggerLevelFinalize() in VintagestoryLib\Client\API\ClientEventAPI.cs:line 383
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleLevelFinalize(Packet_Server packet) in VintagestoryLib\Client\Systems\Startup.cs:line 1035
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 448
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 442
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 776
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 313
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
System.IO.IOException: Cannot open worldmap database file C:\Users\James\AppData\Roaming\VintagestoryData\Maps\44d6c5a0-5633-472c-bebf-1425b5030ef2.db, it seems to be not writable!
   at Vintagestory.API.Common.SQLiteDBConnection.OpenOrCreate(String filename, String& errorMessage, Boolean requireWriteAccess, Boolean corruptionProtection, Boolean doIntegrityCheck) in VintagestoryApi\Common\IO\SQLiteDBConnection.cs:line 42
   at Vintagestory.GameContent.ChunkMapLayer..ctor(ICoreAPI api, IWorldMapManager mapSink) in VSEssentials\Systems\WorldMap\ChunkLayer\ChunkMapLayer.cs:line 109
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by Craluminum2413** [comment] 2024-04-08 07:59
Does it happen without any mods?

**Comment by Craluminum2413** [comment] 2024-04-08 15:09
Duplicate of #3550

**Closed by Craluminum2413** 2024-04-08 15:09 UTC
Labels: status: incomplete
