### ISSUE TITLE
Game can't open any of its folders if you have a space in your windows username

### ISSUE THREAD

**Issue by jangofett890** [anegostudios/VintageStory-Issues#3052] opened 2023-08-27 21:03 UTC
### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

if you have your game installed into your app data directory and your username is your first and last name seperated by a space and you try to open any of the folders from within the game such as the mods folder or the logs folder an error popup window appears saying the path isnt available because it cuts it off at the space.

### How to reproduce

1. Make a new user on your pc with any name seperated by spaces.
2. install VS and play the game.
3. click the mods button the open mods folder. or any other button that opens a vs folder

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/2407092/231063fc-9b41-44e8-bb55-b06852ee08e5)

### Logs

NA

**Comment by Th3Dilli** [comment] 2023-09-13 16:09
Duplicate of #2949

will be fixed in 1.19

**Closed by Th3Dilli** 2023-09-13 16:09 UTC
Labels: status: resolved
