### ISSUE TITLE
Enhance handbook's search feature for russian language by supporting "е" and "ё" interchangeability

### ISSUE THREAD

**Issue by vulpeep** [anegostudios/VintageStory-Issues#3086] opened 2023-09-07 18:55 UTC
### Platform

None

### Modded

None

### SP/MP

None

### Description

I'm reaching out to discuss a minor issue with the game's "Handbook" search feature, specifically affecting Russian-language players. The search engine currently treats the Cyrillic letters "е" and "ё" as distinct characters. While technically accurate, this approach leads to complications when Russian-speaking players search for items within the Handbook.

For instance, if a player searches for "[берёза](https://ru.wikipedia.org/wiki/Берёза)" (birch) in the search bar, items with "береза" in their name won't appear in the search results. Despite these terms essentially being variations of the same word, they are treated as distinct due to different stress marks. This lack of interchangeable recognition between "е" and "ё" can lead to confusion or missed information.

I've also noted from the [Crowdin discussion](https://crowdin.com/project/vintage-story-game/discussions/6) that the translators of the game have an internal guideline to avoid using "ё", specifically due to this limitation in the search engine. However, there are mods for Vintage Story that do not follow this rule in their translations, making the implementation of this feature even more crucial.

To improve the user experience for Russian players, I kindly suggest updating the Handbook's search algorithm to treat "е" and "ё" as interchangeable characters. This minor adjustment could make the Handbook more user-friendly and inclusive for Russian-speaking players, thus enhancing their overall gaming experience.

### Screenshots

<img width="400" alt="image" src="https://github.com/anegostudios/VintageStory-Issues/assets/8516470/cba12e69-8292-4a18-8273-937618e87b4e">
<img width="400" alt="image" src="https://github.com/anegostudios/VintageStory-Issues/assets/8516470/b5c5bfb3-c6a9-4f84-8093-73865983a081">

**Comment by Craluminum2413** [comment] 2023-09-10 09:47
Duplicate of #2559

**Closed** 2023-09-10 09:47 UTC
Labels: status: new, target: localization
