### ISSUE TITLE
Scroll wheel crash?

### ISSUE THREAD

**Issue by xCinniBunny** [anegostudios/VintageStory-Issues#655] opened 2020-11-22 03:15 UTC
**Game Version:** 1.13.4
**Platform:** Windows
**Modded:** No

### Description
Everytime i use the scroll wheel with the map open the game crashes. i have gone in and made the same thing happen 3 different times cause i wasn't sure.
it also will crash if i'm just running around and use the scroll wheel, but not everytime, with the map open its every single time i use the scroll wheel.

### How to reproduce
1. press "m"
2. use scroll wheel on mouse to scroll in.
3. game crash.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.13.4 (Stable)11/21/2020 10:02:26 PM: Critical error occurred
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: dx/dz must be within [0,2]
   at Vintagestory.GameContent.MultiChunkMapComponent.unsetChunk(Int32 dx, Int32 dz)
   at Vintagestory.GameContent.ChunkMapLayer.OnViewChangedClient(List`1 nowVisible, List`1 nowHidden)
   at Vintagestory.GameContent.WorldMapManager.onViewChangedClient(List`1 nowVisible, List`1 nowHidden)
   at Vintagestory.GameContent.GuiElementMap.EnsureMapFullyLoaded()
   at Vintagestory.GameContent.GuiDialogWorldMap.<ComposeDialog>b__16_0(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _VtIDI6oYFpyEcQSZBFso9UVxS9aA._ZnYzeuHqveMMiEvOnpahncAMjfg(Single )
   at _LSAAgZhw31Rqs2is6nnojfZBbQC._4BykKOCicJqCBHpyWIgTmxWrTrg(Single )
   at _LSAAgZhw31Rqs2is6nnojfZBbQC._6XmOxKoTYrFLRCGd58p58XW43nD(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._EEzpApWBQHtHR4iMJabXK2wDvlA(_ex0VSgRAdtsvhANmJHZHaf9ATWt , String[] )
   at _IcGByoJhapvESnm6vaOawAHbkeU._EEzpApWBQHtHR4iMJabXK2wDvlA(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 11/21/2020 9:59:45 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException
   at Vintagestory.GameContent.MultiChunkMapComponent.unsetChunk(Int32, Int32)
   at Vintagestory.GameContent.ChunkMapLayer.OnViewChangedClient(System.Collections.Generic.List`1<Vintagestory.API.MathTools.Vec2i>, System.Collections.Generic.List`1<Vintagestory.API.MathTools.Vec2i>)
   at Vintagestory.GameContent.WorldMapManager.onViewChangedClient(System.Collections.Generic.List`1<Vintagestory.API.MathTools.Vec2i>, System.Collections.Generic.List`1<Vintagestory.API.MathTools.Vec2i>)
   at Vintagestory.GameContent.GuiElementMap.EnsureMapFullyLoaded()
   at Vintagestory.GameContent.GuiDialogWorldMap.<ComposeDialog>b__16_0(Single)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64, Vintagestory.API.Common.IWorldAccessor)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single)
   at _VtIDI6oYFpyEcQSZBFso9UVxS9aA._ZnYzeuHqveMMiEvOnpahncAMjfg(Single)
   at _LSAAgZhw31Rqs2is6nnojfZBbQC._4BykKOCicJqCBHpyWIgTmxWrTrg(Single)
   at _LSAAgZhw31Rqs2is6nnojfZBbQC._6XmOxKoTYrFLRCGd58p58XW43nD(Single)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(System.Object, OpenTK.FrameEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.GameWindow.RaiseRenderFrame(Double, Double ByRef)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double, Double)
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._EEzpApWBQHtHR4iMJabXK2wDvlA(_ex0VSgRAdtsvhANmJHZHaf9ATWt, System.String[])
   at _IcGByoJhapvESnm6vaOawAHbkeU._EEzpApWBQHtHR4iMJabXK2wDvlA(System.Threading.ThreadStart)

 }
```

**Comment by copygirl** [comment] 2020-11-22 07:09
Closing this as duplicate of #601 due to the same error, but your information is still useful. Do you by chance have any custom settings for your world such as smaller world size?

**Closed by copygirl** 2020-11-22 07:09 UTC
Labels: status: duplicate, type: crash
