### ISSUE TITLE
MP Windows Server - SQLite Error 11

### ISSUE THREAD

**Issue by DejFidOFF** [anegostudios/VintageStory-Issues#3883] opened 2024-05-18 05:37 UTC
### Game Version

1.19.7

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

After regular shutdown server Started and shutdown on fatal emediately.

18.5.2024 06:35:51 [Fatal] Caught unhandled exception in thread 'chunkdbthread'. Shutting down server.
18.5.2024 06:35:51 [Error] Exception: SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Vintagestory.Common.Database.SQLiteDbConnectionv2.GetChunk(UInt64 position, String tablename) in VintagestoryLib\Common\FileIO\Database\SQLiteDbConnectionv2.cs:line 223
   at Vintagestory.Server.ServerSystemSupplyChunks.TryLoadMapRegion(Int32 regionX, Int32 regionZ) in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 1320
   at Vintagestory.Server.ServerSystemSupplyChunks.GetOrCreateMapRegion(Int32 chunkX, Int32 chunkZ, ITreeAttribute chunkGenParams) in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 1054
   at Vintagestory.Server.ServerSystemSupplyChunks.GetOrCreateMapRegionEnsureNeighbours(Int32 chunkX, Int32 chunkZ, ITreeAttribute chunkGenParams) in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 1007
   at Vintagestory.Server.ServerSystemSupplyChunks.GetOrCreateMapChunk(ChunkColumnLoadRequest chunkRequest, Boolean forceCreate) in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 1119
   at Vintagestory.Server.ServerSystemSupplyChunks.loadOrGenerateChunkColumn_OnChunkThread(ChunkColumnLoadRequest chunkRequest, Int32 stage) in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 717
   at Vintagestory.Server.ServerSystemSupplyChunks.loadChunkAreaBlocking(Int32 chunkX1, Int32 chunkZ1, Int32 chunkX2, Int32 chunkZ2, Boolean isStartupLoad, ITreeAttribute chunkGenParams) in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 1673
   at Vintagestory.Server.ServerSystemSupplyChunks.OnSeparateThreadTick() in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 386
   at Vintagestory.Server.ServerThread.Update() in VintagestoryLib\Server\ServerThread.cs:line 123
   at Vintagestory.Server.ServerThread.Process() in VintagestoryLib\Server\ServerThread.cs:line 53

### Logs

After regular shutdown server Started and shutdown on fatal emediately.

**Comment by Craluminum2413** [comment] 2024-05-23 07:51
Duplicate of #3734

**Closed by Craluminum2413** 2024-05-23 07:51 UTC
Labels: status: new
