### ISSUE TITLE
11x11x11 Charcoal pit burning only top 6 layers.

### ISSUE THREAD

**Issue by KingDeDeDe11** [anegostudios/VintageStory-Issues#4247] opened 2024-10-07 02:09 UTC
### Game Version

V1.20.0-Pre.5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Charcoal pit 11x11x11 was created, lit on fire, and left. Distance was 200+. it may have unloaded.
After going back, only top 6 layers of firewood was charcoal. Bottom 5 layers are still firewood.

### How to reproduce

1. In multiplayer create 11x11x11 pit and fill with firewood.
2. Cover pit and light.
3. Leave area, (200+?) blocks
4. Wait 24 in game hours
5. Check charcoal pit.

### Screenshots

![2024-10-06_20-53-27](https://github.com/user-attachments/assets/1953fa69-32a6-452a-a818-387db6b785ee)

### Logs

```Log```

**Comment by KingDeDeDe11** [comment] 2024-10-07 03:20
I've been told there was a change to how the charcoal pit works and it now looks 6 blocks out from the firepit. I guess this just means that this issue is with the handbook and not the function of it, assuming what I was told is correct.

**Comment by RedramVS** [comment] 2024-10-08 02:09
To the best of my knowledge this is always how the firepit has worked.  It only converts in a 6 block radius around the firepit.  So in order to get the maximum charcoal pit, the firepit has to be in the dead-center of the entire thing, which requires putting it at the bottom of a deep shaft generally.  I'll see about adding some more text to the handbook entry, but am going to close this as 'not a bug'.

**Closed by RedramVS** 2024-10-08 02:09 UTC
Labels: status: wontfix, department: json

**Comment by pizza2004** [comment] 2024-12-24 22:00
The charcoal pit should now properly detect a full size 11x11x11 pit size no matter where in the pit the firepit is placed, as long as it is on top of any firewood pile, so it is no longer necessary to bury the firepit in the center to get 11x11x11 size pits to work.
