### ISSUE TITLE
Game Crash on Lighting Pit Kiln with Four Crock Pots

### ISSUE THREAD

**Issue by nskjellum** [anegostudios/VintageStory-Issues#1064] opened 2021-06-25 15:37 UTC
**Game Version:** Pre-release .7 (1.15)
**Platform:** Windows 
**Modded:** Yes (Prospector Info)

### Description
Game crash on attempting to light Pit Kiln.

### How to reproduce
Create Pit Kiln, using four Crock Pots
Light Kiln.

### Expected behavior
Pit Lights and begins to fire.

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.0-pre.7 (Unstable)6/25/2021 11:34:51 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityPitKiln.IsAreaLoaded()
   at Vintagestory.GameContent.BlockEntityPitKiln.<>c__DisplayClass14_0.<Initialize>b__2(BlockPos pos)
   at Vintagestory.GameContent.BEBehaviorBurning.canBurn(BlockPos pos)
   at Vintagestory.GameContent.BEBehaviorBurning.OnFirePlaced(BlockPos firePos, BlockPos fuelPos, String startedByPlayerUid)
   at Vintagestory.GameContent.BlockEntityPitKiln.TryIgnite(IPlayer byPlayer)
   at Vintagestory.GameContent.BlockBehaviorCanIgnite.OnHeldInteractStop(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, EnumHandling& handling)
   at Vintagestory.API.Common.CollectibleObject.OnHeldInteractStop(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _tWLW0byDLIhtS1wxxVHI5lzRZDE._pYOg3eHClIOT1FF5vsNdyXdGM03(Single )
   at _6pW3IzjvlkXCwvQdAjU2jMcqPPaA._7YovFWQpW8u7nZERbVYDJRoxy6p(Single )
   at _6pW3IzjvlkXCwvQdAjU2jMcqPPaA._LsdcISpmOPNjHJfC7tNPJt4urmy(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _NfEIYGetj5nHaIEe1bMOq5qPVVe._uAPnYXwEzdCJ8CQ2oCBe9aHMUxo(_DqmInuVm7RykCDabuWwjzEo51Se , String[] )
   at _aLUPv552XTtNubHVap8iu7zzoZB._uAPnYXwEzdCJ8CQ2oCBe9aHMUxo(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 6/25/2021 11:34:56 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1547252815793226177, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.0.0
P3: 60d5aa82
P4: KERNELBASE.dll
P5: 10.0.19041.1023
P6: 924f9cdb
P7: c0020001
P8: 0000000000034b89
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2A86.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER318C.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER31AC.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER31AA.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER31E9.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_a846974abe3961501bc89d24c8949c4d2ba53ee_b5f093ef_dc9c007d-fcef-4167-b732-4f39e3cf78a9

Analysis symbol: 
Rechecking for solution: 0
Report Id: 4eddb3c4-ca48-48d6-9f4b-c09add234c15
Report Status: 268435456
Hashed bucket: c789984255babbd0e578f23cff1401c1
Cab Guid: 0 }
--------------
{ TimeGenerated = 6/25/2021 11:34:53 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.15.0.0, time stamp: 0x60d5aa82
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1023, time stamp: 0x924f9cdb
Exception code: 0xc0020001
Fault offset: 0x0000000000034b89
Faulting process id: 0x4b14
Faulting application start time: 0x01d769d38fb36d69
Faulting application path: D:\Games\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 4eddb3c4-ca48-48d6-9f4b-c09add234c15
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 6/25/2021 11:34:52 AM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FFED8364B89
Stack:
 }
```

**Comment by Craluminum2413** [comment] 2021-06-25 15:38
Duplicate of #1062

**Comment by tyronx** [comment] 2021-06-25 16:20
indeed

**Closed by tyronx** 2021-06-25 16:20 UTC
Labels: status: new, type: bug
