### ISSUE TITLE
Looking at wooden bed recipe causes a client crash

### ISSUE THREAD

**Issue by richardhendricks** [anegostudios/VintageStory-Issues#3399] opened 2024-01-06 16:57 UTC
### Game Version

v1.19.0-rc5

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Trying to look at wooden bed recipe causes a client crash. Looking at hay bed or aged bed recipes works fine.

Crash occurred on modded multiplayer, but has been duplicated in vanilla singleplayer as well.

### How to reproduce

Start game, open help guide, search for wooden bed, click on it. Crash.

### Logs

```Running on 64 bit Windows 10.0.19045.0 with 16137 MB RAM
Game Version: v1.19.0-rc.5 (Unstable)
1/6/2024 10:50:27 AM: Critical error occurred
Loaded Mods: cairns11bigcairn@1.1.0, icemagic@0.1.0, moretreesmoreseeds@1.0.0, NoMoreDrifterThrowing@1.0.0, primitivesurvival@3.4.5, ragnamans-seeds-from-crops-recipes@1.0.0, richerthandirt@1.2.1, game@1.19.0-rc.5, BedRespawning@1.0.1, betterfirepit@1.1.2, carryon@1.7.0-pre.3, icecold@0.5.1, morepiles@1.5.0, stablesurface@0.0.2, creative@1.19.0-rc.5, survival@1.19.0-rc.5, burntreeseeds@1.0.1, stonepiles@1.1.2
System.DivideByZeroException: Attempted to divide by zero.
   at Vintagestory.API.Client.SlideshowGridRecipeTextComponent.RenderInteractiveElements(Single deltaTime, Double renderX, Double renderY, Double renderZ) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\SlideshowGridRecipeTextComponent.cs:line 265
   at Vintagestory.API.Client.GuiElementRichtext.RenderInteractiveElements(Single deltaTime) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementRichtext.cs:line 472
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime) in VintagestoryApi\Client\UI\GuiComposer.cs:line 716
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 384
   at Vintagestory.GameContent.GuiDialogHandbook.OnRenderGUI(Single deltaTime) in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 493
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 318
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1006
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 317
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by Craluminum2413** [comment] 2024-01-06 17:01
Duplicate of #3366

**Closed by Craluminum2413** 2024-01-06 17:01 UTC
Labels: status: new
