### ISSUE TITLE
Sealed crocks stay sealed after removing a meal

### ISSUE THREAD

**Issue by svanheulen** [anegostudios/VintageStory-Issues#1690] opened 2022-02-10 21:44 UTC
**Game Version:** 1.16.4-rc1
**Platform:** Linux
**Modded:** No
**SP/MP:** Singleplayer

### Description
If you use a bowl to remove a meal from a sealed crock, it will stay sealed.

**Comment by copygirl** [comment] 2022-02-11 07:03
Just to confirm: Does the sealed status persist after reloading the world? (Otherwise it could be a sync issue, instead.)

**Comment by svanheulen** [comment] 2022-02-11 14:08
Yes, after restarting the game, the crock is still sealed.

**Comment by JustForVS** [comment] 2022-10-02 16:26
Had the same right now in v 1.17.4, so it's still an issue.

**Comment by Craluminum2413** [comment] 2023-04-08 15:58
Duplicate of #852

**Closed by Craluminum2413** 2023-04-08 15:58 UTC
Labels: status: confirmed
