### ISSUE TITLE
Crash to Desktop accessing sails from Handbook

### ISSUE THREAD

**Issue by rhadamant** [anegostudios/VintageStory-Issues#3383] opened 2024-01-05 07:18 UTC
### Game Version

v1.19rc5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Basically identical to https://github.com/anegostudios/VintageStory-Issues/issues/3366, but this time when accessing sails rather than just cloth. When loaded back into the crashed game it rolled back a only a minute or so, but entire backpack inventory was erased.

### How to reproduce

Click on Sails in the handbook.

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2024-01-05 08:39
Duplicate of #3366

**Closed by Craluminum2413** 2024-01-05 08:39 UTC
Labels: status: new
