### ISSUE TITLE
Crash on World Load

### ISSUE THREAD

**Issue by Sushiy** [anegostudios/VintageStory-Issues#2197] opened 2022-09-16 10:53 UTC
So I've been having trouble with this crash since I updated to 1.17.3! It happens with mods and without mods, and sometimes it doesnt happen at all! :I Could it perhaps be a racing condition?

I played this world just yesterday, but today it won't load for me. The crash happens at the very last step of loading a world just after the "return again" message comes in.

16/09/2022 12:39:14: Critical error occurred
Loaded Mods: tonwexp@1.1.0, backpackpack@1.0.3, cellardoor@1.3.0, cottagewindows@1.0.8, primitivesurvival@3.0.5, rustandrails@1.0.3, game@1.17.3, zeekea@1.6.2, stepup@1.2.0, creative@1.17.3, survival@1.17.3
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.ClientMain.ProcessServerReady() in VintagestoryLib\Client\ClientMain.cs:line 1921
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 1138
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 381
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 709
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 613
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 125
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Craluminum2413** [comment] 2022-09-16 10:56
Does it happen in other worlds?

**Comment by Sushiy** [comment] 2022-09-16 23:18
Yes it happens for all my worlds! I think it's okay if the world is completely new, but anything i load will crash

**Comment by Craluminum2413** [comment] 2022-09-17 07:45
Have you tried to reinstall the game?

**Comment by ApacheTech** [comment] 2022-09-18 06:12
Duplicate of #2046

**Closed** 2022-09-18 08:52 UTC
Labels: status: incomplete
