### ISSUE TITLE
Unknown Crash

### ISSUE THREAD

**Issue by DruidBrandon** [anegostudios/VintageStory-Issues#4321] opened 2024-10-18 00:11 UTC
### Game Version

1.20.0-pre.6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Logs
```
Running on 64 bit Windows 10.0.19045.0 with 16299 MB RAM
Game Version: v1.20.0-pre.6 (Unstable)
10/17/2024 7:10:08 PM: Critical error occurred
Loaded Mods: game@1.20.0-pre.6, creative@1.20.0-pre.6, survival@1.20.0-pre.6
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.Entities.Entity.get_FrustumSphereRadius() in VintagestoryApi\Common\Entity\Entity.cs:line 1076
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 74
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 819
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 825
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 741
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 207
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 10/17/2024 5:04:40 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x6c94
Faulting application start time: 0x01db20dfd50203d3
Faulting application path: C:\Users\BNSMS\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\BNSMS\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: e3c27e28-82d1-4c72-b630-67ec27e14119
Faulting package full name: 
Faulting package-relative application ID:  }
```

**Comment by Craluminum2413** [comment] 2024-10-18 21:42
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4163

**Closed by Craluminum2413** 2024-10-18 21:42 UTC
Labels: status: new
