### ISSUE TITLE
Crashed when cutting grass

### ISSUE THREAD

**Issue by JoIamar** [anegostudios/VintageStory-Issues#1041] opened 2021-06-20 23:10 UTC
Running on 64 bit Windows with 8 GB RAM 
Version: v1.15.0-pre.5 (Unstable)6/20/2021 6:07:59 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Datastructures.JsonObject.ToString()
   at Vintagestory.API.Common.CollectibleObject.DamageItem(IWorldAccessor world, Entity byEntity, ItemSlot itemslot, Int32 amount)
   at Vintagestory.API.Common.CollectibleObject.OnBlockBrokenWith(IWorldAccessor world, Entity byEntity, ItemSlot itemslot, BlockSelection blockSel, Single dropQuantityMultiplier)
   at Vintagestory.Client.NoObf.ClientMain.OnPlayerTryDestroyBlock(BlockSelection blockSelection)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.ContinueBreakSurvival(BlockSelection blockSelection, Block block, Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _MOdxi5vG0bna4SXTrSTDPTj4rVg._4Yd80CSETSLq3ryQSQyu0CgTVkD(Single )
   at _ZTfxbGnrfFIByyznrlGTkx2vj9o._fa9CGlG0qMmF2Mdhb11gCvro90x(Single )
   at _ZTfxbGnrfFIByyznrlGTkx2vj9o._xGQguz838073AFF0xjLFxOuNFvd(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _d9njO8fhbi6B7GfzQuHDVcoAyY6._3LaTwazRKZVPcHgOIFRHUTG6ZpD(_4lAn4F3kZqtcY1FLfNdzOm0cnKI , String[] )
   at _QyjwcZJgpstl1btBhzlpbS2YOg0._3LaTwazRKZVPcHgOIFRHUTG6ZpD(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 6/20/2021 4:47:40 PM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.15.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 2e58

Start Time: 01d7661b7d8da3ae

Termination Time: 4294967295

Application Path: C:\Users\savag\AppData\Roaming\Vintagestory\Vintagestory.exe

Report Id: c5b41dd0-442e-4e5c-af52-b9fe41da8b1e

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Top level window is idle
 }
--------------
{ TimeGenerated = 6/19/2021 7:19:54 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1259147309639579605, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.0.0
P3: 10.0.19041.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\savag\AppData\Local\Temp\RDR3D8B.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3DAC.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3DCC.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3E63.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3EB2.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 4a242a70-58ba-4a38-8415-f439a8fed0cf
Report Status: 268435456
Hashed bucket: c9b9d3809ce1ec04417963ce8ef4b7d5
Cab Guid: 0 }

**Comment by Craluminum2413** [comment] 2021-06-20 23:12
Duplicate of #1037

**Closed** 2021-06-21 05:15 UTC
Labels: status: duplicate
