### ISSUE TITLE
Game crashed while writing a book in multiplayer

### ISSUE THREAD

**Issue by tolbachik** [anegostudios/VintageStory-Issues#3577] opened 2024-02-12 19:41 UTC
### Game Version

1.19.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

I was writing a book, and once I had reached the 8th page, the game crashed. I had noticed bad lag as I approached page 8 of writing.

### How to reproduce

The only other thing I was doing was smelting 2200 units of copper, writing to pass the time. I did very little formatting in the book, could it be a text limit? 

### Logs

Running on 64 bit Windows 10.0.19044.0 with 15731 MB RAM
Game Version: v1.19.1 (Stable)
2/12/2024 2:38:33 PM: Critical error occurred
Loaded Mods: game@1.19.1, creative@1.19.1, survival@1.19.1
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at Vintagestory.GameContent.GuiDialogEditableBook.onTryTextChange(List`1 lines) in VSSurvivalMod\Systems\WritingSystem\GuiDialogEditableBook.cs:line 78
   at Vintagestory.API.Client.GuiElementEditableTextBase.LoadValue(List`1 newLines) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 292
   at Vintagestory.API.Client.GuiElementEditableTextBase.SetValue(String text, Boolean setCaretPosToEnd) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 264
   at Vintagestory.GameContent.GuiDialogReadonlyBook.updatePage(Boolean setCaretPosToEnd) in VSSurvivalMod\Systems\WritingSystem\GuiDialogReadonlyBook.cs:line 170
   at Vintagestory.GameContent.GuiDialogEditableBook.onTextChanged(String text) in VSSurvivalMod\Systems\WritingSystem\GuiDialogEditableBook.cs:line 124
   at Vintagestory.API.Client.GuiElementEditableTextBase.TextChanged() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 329
   at Vintagestory.API.Client.GuiElementTextArea.TextChanged() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementTextArea.cs:line 31
   at Vintagestory.API.Client.GuiElementEditableTextBase.OnKeyBackSpace() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 560
   at Vintagestory.API.Client.GuiElementEditableTextBase.OnKeyDown(ICoreClientAPI api, KeyEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 423
   at Vintagestory.API.Client.GuiComposer.OnKeyDown(KeyEvent args, Boolean haveFocus) in VintagestoryApi\Client\UI\GuiComposer.cs:line 610
   at Vintagestory.API.Client.GuiDialog.OnKeyDown(KeyEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 440
   at Vintagestory.GameContent.GuiDialogReadonlyBook.OnKeyDown(KeyEvent args) in VSSurvivalMod\Systems\WritingSystem\GuiDialogReadonlyBook.cs:line 209
   at Vintagestory.GameContent.GuiDialogEditableBook.OnKeyDown(KeyEvent args) in VSSurvivalMod\Systems\WritingSystem\GuiDialogEditableBook.cs:line 213
   at Vintagestory.Client.NoObf.GuiManager.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 333
   at Vintagestory.Client.NoObf.ClientMain.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1714
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(KeyboardKeyEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 230
   at OpenTK.Windowing.Desktop.NativeWindow.KeyCallback(Window* window, Keys key, Int32 scancode, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Craluminum2413** [comment] 2024-02-12 19:49
Duplicate of #2740

**Closed** 2024-02-12 19:49 UTC
Labels: status: new
