### ISSUE TITLE
open log entry after getting book for "Return part 1" 

### ISSUE THREAD

**Issue by InvertedCow** [anegostudios/VintageStory-Issues#665] opened 2020-11-26 00:47 UTC
Running on 64 bit Windows with 32 GB RAM 
Version: v1.14.0-rc.3 (Unstable)25/11/2020 6:45:58 PM: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.GuiDialogJournal.onClickItem(Int32 i)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientMain.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _4BWchexiFigD9Q16Uzu1AHRcMkKA._F6I3lsgrc5VRUFEGnBoXsboBGFs(_zaqE2EDRPzgKzO45PKPCgTGhJk6 , String[] )
   at _ZkFtsNKa9prG34Jd8zC0yw7G6T4._F6I3lsgrc5VRUFEGnBoXsboBGFs(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 25/11/2020 6:45:07 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IndexOutOfRangeException
   at Vintagestory.GameContent.GuiDialogJournal.onClickItem(Int32)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(Vintagestory.API.Client.MouseEvent)
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(Vintagestory.API.Client.MouseEvent)
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(Vintagestory.API.Client.MouseEvent)
   at Vintagestory.Client.NoObf.ClientMain.OnMouseUp(Vintagestory.API.Client.MouseEvent)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(System.Object, OpenTK.Input.MouseButtonEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(OpenTK.Platform.Windows.MSG ByRef)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double, Double)
   at _4BWchexiFigD9Q16Uzu1AHRcMkKA._F6I3lsgrc5VRUFEGnBoXsboBGFs(_zaqE2EDRPzgKzO45PKPCgTGhJk6, System.String[])
   at _ZkFtsNKa9prG34Jd8zC0yw7G6T4._F6I3lsgrc5VRUFEGnBoXsboBGFs(System.Threading.ThreadStart)

 }

**Comment by copygirl** [comment] 2020-11-26 06:01
This is a duplicate of issue #661. Thank you for reporting, however!

**Closed by copygirl** 2020-11-26 06:01 UTC
Labels: status: duplicate
