### ISSUE TITLE
Game crash to desktop when pressing 'h' to open recipes with honeycomb

### ISSUE THREAD

**Issue by f33dback89** [anegostudios/VintageStory-Issues#1509] opened 2021-12-28 20:38 UTC
**Game Version:** 1.16.rc2  
**Platform:** Windows  
**Modded:** Yes 
**SP/MP:** Singleplayer

### Description
Game crashed to desktop when I pressed H to open handbook while hovering mouse over honeycomb.

### Logs
```
Running on 64 bit Windows with 24 GB RAM 
Version: v1.16.0-rc.3 (Unstable)2021-12-28 3:33:56 PM: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionStatesNative(IWorldAccessor world, ItemSlot inslot)
   at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionState(IWorldAccessor world, ItemSlot inslot, EnumTransitionType type)
   at Vintagestory.Client.NoObf.InventoryItemRenderer.GetItemStackRenderInfo(ClientMain game, ItemSlot inSlot, EnumItemRenderTarget target, Single dt)
   at Vintagestory.Client.NoObf.InventoryItemRenderer.RenderItemstackToGui(ItemSlot inSlot, Double posX, Double posY, Double posZ, Single size, Int32 color, Boolean shading, Boolean origRotate, Boolean showStackSize)
   at Vintagestory.API.Client.SlideshowItemstackTextComponent.RenderInteractiveElements(Single deltaTime, Double renderX, Double renderY)
   at Vintagestory.API.Client.GuiElementRichtext.RenderInteractiveElements(Single deltaTime)
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime)
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime)
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _x2sphGvaQHYRL58iBmwDrxU4JDn._YW8xM33zLilYIiYmPz3LwkRyZnf(Single )
   at _8d8bxAkSchxDthWdXGk9L7JzIAp._COZH04DCHcYdj7FJVekhdO7h2zW(Single )
   at _8d8bxAkSchxDthWdXGk9L7JzIAp._NGLt2tlj0Kdb71xAZX2ab8OUsaY(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 375
   at _Gqy4bfkYgCRmVM3rr5ctXVLZlMh._aoi1Mc6iTidbcOBRjahZfdoHVdN(_BNIaG9Y7PSPYLFpjzhV1OMF5mHh , String[] )
   at _0ynubLUTRXRju8HMEIDSQn5ni6F._aoi1Mc6iTidbcOBRjahZfdoHVdN(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2021-12-24 12:48:04 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2268545439001199446, type 5
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.0.0
P3: 61c3a923
P4: 86d0
P5: 134217728
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4E8E.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_Vintagestory.exe_9931513d86d47870a1e5811854a4d8102b714185_f062d20e_f4c902aa-69ba-467a-9bdf-59d9731029c5

Analysis symbol: 
Rechecking for solution: 0
Report Id: b8e44eca-f2ee-4a8e-b098-5743013818cc
Report Status: 268435462
Hashed bucket: 3e6d586a051789e7cf7b7e0eb87fc356
Cab Guid: 0 }
--------------
{ TimeGenerated = 2021-12-24 12:48:03 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2268545439001199446, type 5
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.0.0
P3: 61c3a923
P4: 86d0
P5: 134217728
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4A57.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_Vintagestory.exe_9931513d86d47870a1e5811854a4d8102b714185_f062d20e_5a7d8949-d493-43ca-bcad-e76fe1e0f25f

Analysis symbol: 
Rechecking for solution: 0
Report Id: 3bc3af2e-e492-419e-b0b5-41053ee02073
Report Status: 268435462
Hashed bucket: 3e6d586a051789e7cf7b7e0eb87fc356
Cab Guid: 0 }
--------------
{ TimeGenerated = 2021-12-24 12:39:40 PM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.16.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: e9c

Start Time: 01d7f8ed2dc6f824

Termination Time: 4

Application Path: C:\Program Files (x86)\Vintagestory\Vintagestory.exe

Report Id: b8e44eca-f2ee-4a8e-b098-5743013818cc

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
```

**Comment by Craluminum2413** [comment] 2021-12-28 20:41
Duplicate of #1430

**Comment by copygirl** [comment] 2021-12-28 21:04
Thanks for noticing this issue, still!

**Closed by copygirl** 2021-12-28 21:04 UTC
Labels: status: duplicate
