### ISSUE TITLE
Crash report 2023/09/02 [v1.18.8] (Linux)

### ISSUE THREAD

**Issue by silentiumNoxe** [anegostudios/VintageStory-Issues#3070] opened 2023-09-01 23:16 UTC
### Game Version

v1.18.8

### Platform

Linux

### Modded

Vanilla

### SP/MP

None

### Description

**Stacktrace**
```
Running on 64 bit Linux with 31562 MB RAM
Game Version: v1.18.8 (Stable)
02/09/2023 02:06:03: Critical error occurred
Loaded Mods: game@1.18.8, creative@1.18.8, survival@1.18.8
System.OverflowException: Arithmetic operation resulted in an overflow.
   at Vintagestory.Common.ArrayConvert.ByteToByte(Byte[] data, Int32 length) in VintagestoryLib\Common\Convert\ArrayConvert.cs:line 73
   at Vintagestory.Common.CompressionZSTD.Decompress(Byte[] fi) in VintagestoryLib\Common\Convert\Compression.cs:line 678
   at Vintagestory.Common.Compression.Decompress(Byte[] data) in VintagestoryLib\Common\Convert\Compression.cs:line 113
   at Vintagestory.Common.BlockTypeNet.UnpackBlockPositions(Byte[] setBlocks) in VintagestoryLib\Common\Network\BlockTypeNet.cs:line 899
   at Vintagestory.Client.NoObf.SystemHighlightBlocks.HandlePacket(Packet_Server packet) in VintagestoryLib\Client\Systems\Render\HighlightBlocks.cs:line 300
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 452
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 446
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 757
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 712
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 75
   at OpenTK.Windowing.Desktop.GameWindow.DispatchRenderFrame()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 312
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

### How to reproduce

Generate new world

### Logs

I take all logs because i'm not sure what needed
[Logs.zip](https://github.com/anegostudios/VintageStory-Issues/files/12501912/Logs.zip)

**Comment by Th3Dilli** [comment] 2023-09-21 09:04
Duplicate of #3009

And should be fixed with the latest version (as of 1.18.9)

So please make sure to update

**Closed by Th3Dilli** 2023-09-21 09:04 UTC
Labels: platform: linux, status: new
