### ISSUE TITLE
My game save is not opening

### ISSUE THREAD

**Issue by huseyn0087** [anegostudios/VintageStory-Issues#4706] opened 2024-12-15 20:42 UTC
### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

My game save is not opening

### How to reproduce

My game save is not opening

### Screenshots

![123](https://github.com/user-attachments/assets/0b938ccb-7a8b-4a73-8298-bdc439639197)

### Logs

```Log```Running on 64 bit Windows 10.0.19045.0 with 8080 MB RAM
Game Version: v1.20.0-pre.6 (Unstable)
15.12.2024 23:31:27: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockShapeFromAttributes.OnUnloaded(ICoreAPI api)
   at Vintagestory.Client.NoObf.ClientMain.Dispose()
   at Vintagestory.Client.NoObf.ClientMain.DestroyGameSession(Boolean gotDisconnected)
   at Vintagestory.Client.GuiScreenConnectingToServer.onCancel()
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 318
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\GuiElement.cs:line 719
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 308
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 447
   at GuiScreen.OnMouseUp(MouseEvent e)
   at Vintagestory.Client.ScreenManager.OnMouseUp(MouseEvent e)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(MouseButtonEventArgs e)
   at OpenTK.Windowing.Desktop.NativeWindow.OnMouseUp(MouseButtonEventArgs e)
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.NativeWindow.ProcessWindowEvents(Boolean waitForEvents)
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1()
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)

**Comment by Craluminum2413** [comment] 2024-12-15 20:56
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4095

**Closed by Craluminum2413** 2024-12-15 20:56 UTC
Labels: status: new

**Comment by Craluminum2413** [comment] 2024-12-15 20:58
it was fixed in rc.1

**Comment by huseyn0087** [comment] 2024-12-15 21:21
I am new to this platform. I don't know what to do. Did you solve my problem right now?

**Comment by Craluminum2413** [comment] 2024-12-15 21:23
@huseyn0087 No, it is just fixed in latest versions
