### ISSUE TITLE
Gui dissappears

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#1266] opened 2021-08-09 05:37 UTC
**Game Version:** 1.15.3
**Platform:** Mac  
**Modded:** No 

### Description
Whenever a block is close enough to be selected, the gui disappears.

### How to reproduce
1. Load game on mac
2. get close enough for block info to appear

### Screenshots
https://youtu.be/LrIH969ZSO8

**Comment by copygirl** [comment] 2021-08-09 06:47
Duplicate of #983.

**Closed by copygirl** 2021-08-09 06:47 UTC
Labels: target: survival, platform: osx, status: confirmed, priority: high, department: code
