### ISSUE TITLE
Clay forming, knapping - Net visibility worse on Linux

### ISSUE THREAD

**Issue by daretmavi** [anegostudios/VintageStory-Issues#2662] opened 2023-04-26 12:59 UTC
### Game Version

1.18.1

### Platform

Linux

### Modded

Vanilla

### SP/MP

None

### Description

Knapping and Clay forming Net visibility on Linux is much worse than on Windows. It is almost invisible, but on windows is brighter and better visible.

Windows:
<details><summary>Details</summary>
<p>
Windows 10

Nvidia Quadro P2000
Driver: 31.0.15.2727

</p>
</details> 

![2023-04-26_14-37-49 windows-form](https://user-images.githubusercontent.com/47914240/234580531-0c1cd9c3-caeb-4075-a304-203d3e1e1bb8.png)
![2023-04-26_14-46-16 windows-knap](https://user-images.githubusercontent.com/47914240/234580538-6aa17daa-5472-4a45-831f-ec7f69a4907d.png)

Linux:
<details><summary>Details</summary>
<p>
Distro: KDE neon 22.04 5.27

AMD RX 580
  OpenGL: renderer: AMD Radeon RX 580 Series (polaris10 LLVM 15.0.6 DRM
    3.47 5.19.0-38-generic)
    v: 4.6 Mesa 22.2.5

</p>
</details> 

![2023-04-26_14-42-01 linux-form](https://user-images.githubusercontent.com/47914240/234580729-8e6ad4ae-8d62-4a63-ab74-80b02d48e561.png)
![2023-04-26_14-47-14 linux-knap](https://user-images.githubusercontent.com/47914240/234580750-69dc78ba-a5b0-4da9-812f-f55d0b6d10c6.png)

**Comment by Craluminum2413** [comment] 2023-04-26 13:02
Duplicate of #2658

**Closed by Craluminum2413** 2023-04-26 13:02 UTC
Labels: status: new
