### ISSUE TITLE
Food in a basement on a shelf has unrealistic long storability

### ISSUE THREAD

**Issue by VS-hunson** [anegostudios/VintageStory-Issues#4645] opened 2024-12-09 16:00 UTC
### Game Version

v1.20.rc1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Food (sealed and unsealed) that was put in the basement on a shelf in last stable version (v1.19.8?) has now a unrealistic long storability.
When taken from the shelf in the hot bar, the time seems reasonable. When put back, the 'best before' time again is very long.

### How to reproduce

1. store food in a basement on a shelf.

### Screenshots

![2024-12-08_11-49-00_small](https://github.com/user-attachments/assets/beac169b-7d10-4775-8865-bd1d1092025d)

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2024-12-09 16:01
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4624

**Closed by Craluminum2413** 2024-12-09 16:01 UTC
Labels: status: new
