### ISSUE TITLE
Instant crash on modless private server join

### ISSUE THREAD

**Issue by TimPerdok** [anegostudios/VintageStory-Issues#3572] opened 2024-02-10 15:41 UTC
### Game Version

v1.19.3

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Hello, me and my friend both suddenly crashed on our private  server. We are not using any mods. We can't join the server anymore as it crashes instantly. The server still runs without issues. So this is clientsided. We were picking berries off a bush around when this happened.

### How to reproduce

1. Try to run this world file: https://we.tl/t-Bvf6q45tUh. Running in singleplayer or in repair mode does not matter.
2. I don't know if it occurs in every chunk. If it's related to a corrupted chunk, it should be around coordinates ( 511254.35485898436 112 512323.1545201172)

### Logs

```Running on 64 bit Windows 10.0.22631.0 with 32691 MB RAM
Game Version: v1.19.3 (Stable)
10/02/2024 16:41:26: Critical error occurred
Loaded Mods: game@1.19.3, creative@1.19.3, survival@1.19.3
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityItemRenderer.LoadModelMatrix(ItemRenderInfo renderInfo, Boolean isShadowPass, Single dt) in VSEssentials\EntityRenderer\EntityItemRenderer.cs:line 280
   at Vintagestory.GameContent.EntityItemRenderer.DoRender3DOpaque(Single dt, Boolean isShadowPass) in VSEssentials\EntityRenderer\EntityItemRenderer.cs:line 150
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderFrameShadows(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 177
   at Vintagestory.API.Client.DummyRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in VintagestoryApi\Client\API\IClientEventAPI.cs:line 83
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 191
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 799
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 862
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 723
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 675
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 650
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 10/02/2024 16:36:39, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.3.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x1eb4
Faulting application start time: 0x0x1da5c362b55557c
Faulting application path: C:\Users\tim-p\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\tim-p\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: c9df7978-b8c2-4c4d-b8a5-391aff25b0fb
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 10/02/2024 16:30:46, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.3.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x2840
Faulting application start time: 0x0x1da5c34615bc832
Faulting application path: C:\Users\tim-p\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\tim-p\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 7bfd8525-6ab9-4267-aebe-85bf78bd9379
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 10/02/2024 16:18:18, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.3.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x1684
Faulting application start time: 0x0x1da5c32738e0b38
Faulting application path: C:\Users\tim-p\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\tim-p\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 8edbc75f-83f5-4d79-bf6e-95cb09c764bd
Faulting package full name: 
Faulting package-relative application ID:  }```

**Comment by Craluminum2413** [comment] 2024-02-10 16:01
Duplicate of #3529

**Closed by Craluminum2413** 2024-02-10 16:01 UTC
Labels: status: new

**Comment by TimPerdok** [comment] 2024-02-10 16:13
@Craluminum2413 Not necessarily duplicate. As that issue is a third party issue. This one occurs even without any third party changes.

**Comment by Craluminum2413** [comment] 2024-02-10 16:22
@TimPerdok Crash log is the same

**Comment by TimPerdok** [comment] 2024-02-10 16:30
Workaround: Managed to repair the chunks by forceloading the area of the coordinates and removing all entities in the area.
