### ISSUE TITLE
leaning spear keeps standing when removing wall in specific order

### ISSUE THREAD

**Issue by JustForVS** [anegostudios/VintageStory-Issues#2228] opened 2022-10-03 20:43 UTC
Game Version: 1.17.4
Platform: Windows 10
Modded: Yes (hudclock-2.8.0, ProspectorInfo-4.1.1, singlepause-1.0.3, ZoomButton1.3.0)
SP/MP: Singleplayer

### Description
When leaning a spear agains the wall (needs a 2 blocks high wall) and remove at first the lower wall block and then the upper one, the spear keeps standing

### How to reproduce
See screen shots

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
![003](https://user-images.githubusercontent.com/87942616/193678654-b12b0db8-8a05-4d82-aaaa-05fbd4ca02ed.jpg)

### Logs
```
Paste crash between the triple backticks.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.
```

**Comment by Craluminum2413** [comment] 2022-10-03 20:45
Duplicate of #1938

**Closed by Craluminum2413** 2022-10-03 20:45 UTC
Labels: status: new
