### ISSUE TITLE
Save crash. I can't play again on this gamesave.

### ISSUE THREAD

**Issue by marek2001** [anegostudios/VintageStory-Issues#871] opened 2021-04-22 09:33 UTC
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.8 (Stable)22.04.2021 11:31:26: Critical error occurred
System.NullReferenceException: Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
   w Vintagestory.API.Common.EntityItem.FromBytes(BinaryReader reader, Boolean forClient)
   w Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntitySpawnPacket(_uQLFO3G34CNPass7LE9Zs5TcuUF serverpacket)
   w Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   w _jeEziyUSYl0BpbOxT46FYwj5VWL._t25VgrofhlXMw6hHEZh8JHhJz1A(Single )
   w _idIkJkIueHHf3Oz2WNlBdD0E1XR._DvzT6D0wN3fMakeuDyljJJ09hok(Single )
   w _idIkJkIueHHf3Oz2WNlBdD0E1XR._V5piYzG7beYPldE6UVxY58dqacE(Single )
   w Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   w System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   w OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   w OpenTK.GameWindow.DispatchRenderFrame()
   w OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   w _YrS2W1MoaeqC4xqH8ItdZB6vADN._8t1BmEWVlCT9mjx5M0vFIzU9tif(_7T00Rjby4si0wyEBez5dXNqLm7h , String[] )
   w _ejKuc6cg0k8V39o8jDIzquyczbO._8t1BmEWVlCT9mjx5M0vFIzU9tif(ThreadStart )
-------------------------------

**Comment by copygirl** [comment] 2021-04-22 09:34
Try opening the world in repair mode. In the world selection, click the pencil for the world, then there should be a "Run in Repair mode" button you can click.

**Comment by copygirl** [comment] 2021-04-24 06:18
Closing as duplicate of #472 for now. Repair mode should help.

**Closed by copygirl** 2021-04-24 06:18 UTC
Labels: status: duplicate, type: crash
