### ISSUE TITLE
Berry bushes prevent grass growth

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/VintageStory-Issues#111] opened 2018-05-25 15:42 UTC
Berry bushes placed on barren dirt blocks will prevent grass from growing underneath

**Comment by sirStroam** [comment] 2018-05-26 00:30
All leaves and bushes prevent grass from growing underneath.

**Comment by tyronx** [comment] 2018-06-08 11:06
I cannot reproduce this in singleplayer

**Comment by jchappelle** [comment] 2018-07-11 01:47
I'm unable to reproduce this.

The only blocks that smother grass are ones that have a solid and opaque bottom face. Leaves and berry bushes do not. 

If you're still having this issue please zip up your world and share it with me so I can debug it locally.

**Comment by jchappelle** [comment] 2018-07-14 00:34
This may just be this issue which I just committed code to fix: https://github.com/anegostudios/VintageStory-Issues/issues/144

You can try placing leaves and standing on the block underneath them and running this command:
`tickblock ~0 ~-1 ~0`
That will cause the block to try and tick immediately instead of waiting for the random tick. If it declines then attach your world and I'll try to recreate. 

Closing for now. Please reopen with the attached world zip if the problem persists.

**Closed by jchappelle** 2018-07-14 00:34 UTC
Labels: status: incomplete, target: survival, type: bug
