### ISSUE TITLE
Modded Multiplayer connection error crash.

### ISSUE THREAD

**Issue by AustSian** [anegostudios/VintageStory-Issues#3689] opened 2024-03-07 06:07 UTC
### Game Version

1.19.4

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

It's a modded server. 2 of the three people playing can join no issue. The third person tries to connect to the server and crashes before they see the downloading data screen.

All mods are of the correct version and matching.

### Logs

Running on 64 bit Windows 10.0.19045.0 with 16314 MB RAM
Game Version: v1.19.4 (Stable)
3/6/2024 11:28:41 PM: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.ShaderAPI.ReloadShaders() in VintagestoryLib\Client\API\ShaderAPI.cs:line 53
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerReady(Packet_Server packet) in VintagestoryLib\Client\Systems\Startup.cs:line 881
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 446
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 440
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 776
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 313
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>cDisplayClass9_0.<.ctor>b1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 2/28/2024 7:31:22 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.4.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x27f0
Faulting application start time: 0x01da6aaea76fea45
Faulting application path: C:\Program Files (x86)\Games\Vintagestory\Vintagestory.exe
Faulting module path: C:\Program Files (x86)\Games\Vintagestory\Lib\openal32.dll
Report Id: 03f08f36-ded1-4c02-99aa-ec8c8fd0b5e3
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment] 2024-03-07 09:33
What mods are installed?

**Comment by AustSian** [comment] 2024-03-08 01:12
The mods are;
- A Culinary Artiliery 1.1.3
- Animation Manager Lib 0.7.2
- config Lib 1.0.2
- Division of Labor
- Expanded Foors 1.6.8
- Fising 1.1.5
- Floating Landmasses
- FSMlib 0.3.0
- Malteiz Firearms 0.5.0
- Medieval Expansion 3.13.1
- Pet AI 2.2.3
- Pipeleaf 1.5.0
- Primitive Survival 3.4.8
- Rivers 2.7.0
- Shareable Waypoints 1.5.4
- VS IMgui 1.1.1
- Wolf Taming 2.1.0 _petai v2

They work perfectly fine for two of us, and our third can't even get into the part where the server asks for them to download the mods if they got the wrong ones. It's immediately crashing and sending them to the home screen. Both when they wipe the mods (To let the server download it) and pre put the mods on.

**Comment by Craluminum2413** [comment] 2024-03-08 08:26
Duplicate of #3648

**Closed by Craluminum2413** 2024-03-08 08:26 UTC
Labels: status: incomplete
