### ISSUE TITLE
Game crashing in -pre13 on help ui while holding wax (will test in rc2)

### ISSUE THREAD

**Issue by hlangeveld** [anegostudios/VintageStory-Issues#1492] opened 2021-12-23 15:51 UTC
---
name: Bug report
about: I found an issue with the game
title: ''
labels: 'status: new'
assignees: ''

---

**Game Version:** 1.16.0-pre13
**Platform:** Windows 
**Modded:** No
**SP/MP:** Singleplayer 

### Description
Game crashing in -pre13 on help ui while holding wax

I will try to reproduce in rc2.

### How to reproduce
1. Squeeze honeycomb
2. Hold wax, press 'h'
3. It crashes

### Expected behavior
No crash ;-)

### Screenshots
N/A

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.16.0-pre.13 (Unstable)23/12/2021 16:42:58: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionStatesNative(IWorldAccessor world, ItemSlot inslot)
   at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionState(IWorldAccessor world, ItemSlot inslot, EnumTransitionType type)
   at Vintagestory.Client.NoObf.InventoryItemRenderer.GetItemStackRenderInfo(ClientMain game, ItemSlot inSlot, EnumItemRenderTarget target, Single dt)
   at Vintagestory.Client.NoObf.InventoryItemRenderer.RenderItemstackToGui(ItemSlot inSlot, Double posX, Double posY, Double posZ, Single size, Int32 color, Boolean shading, Boolean origRotate, Boolean showStackSize)
   at Vintagestory.API.Client.SlideshowItemstackTextComponent.RenderInteractiveElements(Single deltaTime, Double renderX, Double renderY)
   at Vintagestory.API.Client.GuiElementRichtext.RenderInteractiveElements(Single deltaTime)
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime)
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime)
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _6pTt0YrkqDwwGWnREQxlCvqvggA._LinuZfvr6BDowcBGwXPTAS8FTLK(Single )
   at _mdvf5bEeWL56h6SFl4h8FigPo2s._Xo3D3EqAH7sRM3A1fC6QheeS3MJ(Single )
   at _mdvf5bEeWL56h6SFl4h8FigPo2s._KvFfRKRjGrTPsMo8Ao0w7EtHWIh(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 375
   at _UqcwV9GG4BrOgZROg4gh2pkpCwF._o88CILSXcIXZF55D7LyehQbY6UMA(_K4VhmQb3cdagrWrCnGTIiiauFxF , String[] )
   at _cktdlkc1KpfKxjSnOv5ASA84NFp._o88CILSXcIXZF55D7LyehQbY6UMA(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 07/12/2021 22:49:47, Site = , Source = Windows Error Reporting, Message = Fault bucket 2303487212832634002, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.0.0
P3: 10.0.19044.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Henk\AppData\Local\Temp\RDRA32D.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA32E.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA33F.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA347.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA367.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 5ae98720-8c91-414c-8e0e-e7e71b12f36a
Report Status: 268435456
Hashed bucket: 53cc9f6abf54db50bff7a16a698b3492
Cab Guid: 0 }
--------------
{ TimeGenerated = 07/11/2021 17:48:18, Site = , Source = Windows Error Reporting, Message = Fault bucket 1970256216346595652, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.8.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Henk\AppData\Local\Temp\RDRDA91.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDA92.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDAA3.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDAB1.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDAD1.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 986b24dd-2682-4eb2-bf1d-e77f91bee438
Report Status: 268435456
Hashed bucket: 6ae005b1ffe475076b57c19703d81144
Cab Guid: 0 }
--------------
{ TimeGenerated = 23/09/2021 02:14:10, Site = , Source = Windows Error Reporting, Message = Fault bucket 1298668709714251717, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.6.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Henk\AppData\Local\Temp\RDRF5C5.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF5D6.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF5E6.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF5EB.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF5FC.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: a9e2996f-ae2e-4a60-b41e-7168e9a73013
Report Status: 268435456
Hashed bucket: 8f39dc2e068300f29205cc4f936ecfc5
Cab Guid: 0 }
```

**Comment by Craluminum2413** [comment] 2021-12-23 15:57
Duplicate of #1430

**Closed** 2021-12-23 16:40 UTC
Labels: status: duplicate
