### ISSUE TITLE
Crash while Scything Grass

### ISSUE THREAD

**Issue by FlexibleGames** [anegostudios/VintageStory-Issues#3798] opened 2024-04-10 18:05 UTC
### Game Version

v1.19.5

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

While Scything grass, crash (NullRef Exception) from VintageStoryLib.dll RenderEntities.cs.

Library is not on GitHub so could not investigate exact reason further.  Unable to debug as I can't debug base code and see what is being passed in as null.

### How to reproduce

On a MP server, use a diamond Scythe and cut the grass. Had my magnet on and enabled at the time. Magnet does NOT touch rendering of entities, it only moves them from A to B. Scythe was in 9x9 and remove modes.

### Logs

Running on 64 bit Windows 10.0.19045.0 with 32509 MB RAM
Game Version: v1.19.5 (Stable)
4/10/2024 12:45:11 PM: Critical error occurred
Loaded Mods: angelbelt@1.5.0, backpackpackplus@1.1.0, bettercrates@1.7.0, BuggisRandomChanges@3.6.2, buildinggadgets@1.0.0, charcoalpitrebalance@1.0.1, chiseltools@1.11.1, craftingtable@0.6.0, extendedcrafts@1.1.1, extrachests@1.8.0, FarmSurvival@1.4.1, FlexibleTools@3.2.1, HoneyPress@1.1.2, moremolds@1.4.12, moretreesmoreseeds@1.0.0, nailsmold@1.0.1, nightwatcher@2.1.0, NoMoreDrifterThrowing@1.0.0, oildeposits@1.3.2, OresAPlenty@3.2.0, QuartzBlocks@1.1.0, RockBlocks@1.0.0, vintageengineering@0.0.11, game@1.19.5, animalcages@3.0.2, betterfirepit@1.1.4, betterruins@0.3.4, diamondcrate@1.0.2, justanarrowheadmold@1.0.1, knapster@2.9.2, norottinghides@1.0.0, scarecrow@1.4.3, storagecontroller@1.0.8, th3dungeon@0.2.1-rc.1, vmetp@1.1.1, creative@1.19.5, vsimgui@1.1.2, survival@1.19.5, metalrecovery@0.1.19-pre.1, configlib@1.0.2, em@2.5.1, bricklayers@2.5.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 49
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 815
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 731
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Craluminum2413** [comment] 2024-04-10 18:11
Duplicate of #3550

**Closed by Craluminum2413** 2024-04-10 18:11 UTC
Labels: status: new

**Comment by FlexibleGames** [comment] 2024-04-10 21:24
I looked for a dup report and didn't see one, oh well.
