### ISSUE TITLE
Game crash upon dedicated server entry (v1.16.0)

### ISSUE THREAD

**Issue by SirPlayFair** [anegostudios/VintageStory-Issues#1589] opened 2022-01-15 04:00 UTC
Running on 64 bit Windows with 32 GB RAM 
Version: v1.16.0 (Stable)1/14/2022 10:46:57 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.TextureSource..ctor(ClientMain game, Size2i atlasSize, Block block, Boolean forInventory)
   at Vintagestory.Client.NoObf.ShapeTesselatorManager.TesselateBlock(Block block, Nullable`1 quantityElements)
   at Vintagestory.Client.NoObf.ShapeTesselatorManager.TesselateBlocks(IList`1 blocks)
   at Vintagestory.Client.NoObf.ClientMain.OnServerBlocksItemsReceivedStep4(Action onCompleted, Int32 blockCount)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _0dbBCVS4kT4NsuDZA84yDu7r3AG._1NlBQQ8qS5idQptIBQaAbARuOfxA(Single )
   at _vFhcDU5n6Z0hUte90jdaxlrDjR5._HuDdfzha8ZKZvU2y0RbH58r7VzR(Single )
   at _vFhcDU5n6Z0hUte90jdaxlrDjR5._XZOFA2JA54yZjH15yys9W7vL9hj(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _FKpOpQGqqf3cJWdQyWh1ysxsDBb._pYad7oBcQ5qtzQkYGDu4NFHQxhK(_5x3PJgrln4IBXPDNSNN0fecxKFb , String[] )
   at _sejP0Tcz8wTg70ptIdRr3CwQmrE._pYad7oBcQ5qtzQkYGDu4NFHQxhK(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 1/14/2022 1:04:01 PM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.16.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 2708

Start Time: 01d80971087bc228

Termination Time: 2

Application Path: C:\Users\David\AppData\Roaming\Vintagestory\Vintagestory.exe

Report Id: 2e00011c-c474-44cb-97b0-7c6c0601709e

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
--------------
{ TimeGenerated = 1/14/2022 12:20:19 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2137399946764805085, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.0.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\David\AppData\Local\Temp\RDR8B06.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8B17.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8B18.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8B35.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8B55.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 9cf627b6-c536-497a-8591-ce8fbce64af0
Report Status: 268435456
Hashed bucket: 90206cb8882a62a92da991ed59dae3dd
Cab Guid: 0 }
--------------
{ TimeGenerated = 1/14/2022 12:11:40 AM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.16.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 48f0

Start Time: 01d80904d00732b6

Termination Time: 3

Application Path: C:\Users\David\AppData\Roaming\Vintagestory\Vintagestory.exe

Report Id: c0c10904-1b77-473b-8f2f-c1cc0bbab830

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }

**Comment by copygirl** [comment] 2022-01-15 05:40
Duplicate of #1587.

**Closed by copygirl** 2022-01-15 05:40 UTC
Labels: status: duplicate, status: new
