### ISSUE TITLE
Vanilla Game Crash on Joining Multiplayer Game

### ISSUE THREAD

**Issue by KenadeeM** [anegostudios/VintageStory-Issues#2441] opened 2023-03-07 03:43 UTC
### Game Version

v1.18.0-pre.5 (Unstable)

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

I try to load the server and it crashes the game. It worked once but not since.

### How to reproduce

1. run game 2. put in IP 3. load game 4. crash
My friend uses NGROK to host the server

### Logs

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.0-pre.5 (Unstable)
2023-03-06 11:33:12 PM: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.GuiScreenConnectingToServer.exitToDisconnectScreen() in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 427
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 313
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 715
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 618
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 119
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2023-02-24 5:09:49 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1431080498583360532, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.11.0
P3: 10.0.19045.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Kenadee\AppData\Local\Temp\RDRE266.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE296.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE2A7.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE300.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE36E.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 057c2f5a-90bf-4336-8d39-0b73c05cbc31
Report Status: 268435456
Hashed bucket: a386333e91cb17c6d3dc38219b0cd414
Cab Guid: 0 }
--------------
{ TimeGenerated = 2022-10-09 4:08:29 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1195683450976658661, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.6.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Kenadee\AppData\Local\Temp\RDR775D.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER776E.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER778E.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER77C2.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7811.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 161a885d-65be-44bc-8b38-393ae517a1f3
Report Status: 268435456
Hashed bucket: 5e98493e22bafc7aa097ebc37f46e4e5
Cab Guid: 0 }

**Comment by Craluminum2413** [comment] 2023-03-07 07:00
Duplicate of #2380

**Closed by Craluminum2413** 2023-03-07 07:00 UTC
Labels: status: new
