### ISSUE TITLE
Solid block above ladders sometimes ghosts and allows to pass

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#523] opened 2020-05-04 23:37 UTC
**Game Version:** 1.12.14 Stable
**Platform:** Windows 10, build from 2016 year
**Modded:** No

### Description
On behalf of player mihannnik
See the video: https://www.youtube.com/watch?v=eWM1bYkUIzo
The player who placed the solid block was able to pass. The only meaningful audio information was that he needed to get out from the ladder and enter back on it, then it sometimes worked.
Blocks if placed on both sides of the problematic block seems to remove the issue, can not pass.
Minimizing window or changing to windowed mode seems to pass this ability to go through the block to another player: initially the recording player was in the block, but after minimizing the game for starting video capture he could not pass but the other player got this ability. When another player minimized the game, he also lost this ability.
They played on a dedicated server located not on their PC.
Other user - DearFox - also knows about this bug and says Tyron also knows. But I failed to find it in the bug list and it is 2:30 am and I wanna sleep :D

### How to reproduce
They were unable to reproduce consistently.

### Expected behavior
Not be able to pass the solid block.

### Screenshots
https://www.youtube.com/watch?v=eWM1bYkUIzo

**Comment by copygirl** [comment] 2020-05-05 04:03
I found that this is much easier to reproduce if you sneak before getting on the ladder.

**Comment by Craluminum2413** [comment] 2021-06-02 12:40
> https://www.vintagestory.at/forums/topic/3726-wintery-stability-patch-v1146-rc1/
> "Fixed: Players on ladders sometimes clipping through a solid block above"

**Comment by Craluminum2413** [comment] 2021-06-14 21:28
I found this bug again

### How to reproduce
1. You know what to do
2. Sneak to ladder, staying on the ground
3. Holding Shift press Space and climb above

https://user-images.githubusercontent.com/69315569/121961424-165a9b00-cd70-11eb-8aad-3c9876e8ea18.mp4

**Comment by Craluminum2413** [comment] 2021-06-14 21:34
@copygirl Unfortunately this hasn't been fixed

**Comment by Craluminum2413** [comment] 2022-01-07 14:21
There was a tweak in some of 1.14 or 1.15 versions, I can't find it in changelogs, but there was something like "`shift` is now more preferable than `space bar`", but I sure it fixed this issue, because I can no longer reproduce it

**Comment by copygirl** [comment] 2022-01-07 14:30
Fair, I will close it until this can be reproduced again.

**Closed by copygirl** 2022-01-07 14:30 UTC
Labels: target: survival, status: resolved
