### ISSUE TITLE
crash when cutting reed

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1037] opened 2021-06-20 19:20 UTC
**Game Version:** 1.15.0-pre5
**Platform:** Windows
**Modded:** No

### Description
Beginning a new map on a pre5 generated standard world, and experienced crash cutting reed with flintstone knife.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.0-pre.5 (Unstable)20/06/2021 21:16:13: Critical error occurred
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à Vintagestory.API.Datastructures.JsonObject.ToString()
   à Vintagestory.API.Common.CollectibleObject.DamageItem(IWorldAccessor world, Entity byEntity, ItemSlot itemslot, Int32 amount)
   à Vintagestory.API.Common.CollectibleObject.OnBlockBrokenWith(IWorldAccessor world, Entity byEntity, ItemSlot itemslot, BlockSelection blockSel, Single dropQuantityMultiplier)
   à Vintagestory.Client.NoObf.ClientMain.OnPlayerTryDestroyBlock(BlockSelection blockSelection)
   à Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.ContinueBreakSurvival(BlockSelection blockSelection, Block block, Single dt)
   à Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   à Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   à Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   à Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   à Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   à _MOdxi5vG0bna4SXTrSTDPTj4rVg._4Yd80CSETSLq3ryQSQyu0CgTVkD(Single )
   à _ZTfxbGnrfFIByyznrlGTkx2vj9o._fa9CGlG0qMmF2Mdhb11gCvro90x(Single )
   à _ZTfxbGnrfFIByyznrlGTkx2vj9o._xGQguz838073AFF0xjLFxOuNFvd(Single )
   à Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   à System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   à OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   à OpenTK.GameWindow.DispatchRenderFrame()
   à OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   à _d9njO8fhbi6B7GfzQuHDVcoAyY6._3LaTwazRKZVPcHgOIFRHUTG6ZpD(_4lAn4F3kZqtcY1FLfNdzOm0cnKI , String[] )
   à _QyjwcZJgpstl1btBhzlpbS2YOg0._3LaTwazRKZVPcHgOIFRHUTG6ZpD(ThreadStart )
-------------------------------

```

**Comment by Craluminum2413** [comment] 2021-06-20 19:22
Can't reproduce in 1.15.0-pre.5

https://user-images.githubusercontent.com/69315569/122685745-f9154900-d215-11eb-8bb3-654b1d1f6d40.mp4

**Comment by Saricane** [comment] 2021-06-20 19:24
Because I did not say it was with every reed. I first cut enough to make 2 baskets, then crafted the baskets, and when I returned to make more, crash.

**Comment by Saricane** [comment] 2021-06-20 19:36
Crash when harvesting wild turnips. All those crashes seems to occur when a "harverstable" resource is extracted.

**Comment by Craluminum2413** [comment] 2021-06-20 19:40
Then it is related to #973 too

**Comment by Craluminum2413** [comment] 2021-06-20 19:44
Can you send a seed with coordinates of that reed block?

**Comment by Saricane** [comment] 2021-06-20 19:51
For the reed, I don't know (I'll try again after) , but for the wild turnips, I crashed again : seed 1287401365 go to -59,11,-219

**Comment by Craluminum2413** [comment] 2021-06-20 20:00
Specify the world size, please. I can't find turnips on those coordinates in `1.000.000x256x1.000.000` world

**Comment by Saricane** [comment] 2021-06-20 20:07
> 
> 
> Specify the world size, please. I can't find turnips on those coordinates in `1.000.000x256x1.000.000` world

You're right, I forget to mention I started in "warm climate". BUT I tried to generate this same world, landscape is the same, but no turnips. It will be the same for you. Too bad, I just managed to find reeds that make game crash.

**Comment by Saricane** [comment] 2021-06-20 20:27
Still experiencing crashes when harvesting things. After a reed and a turnips, now a wild flax. I could give you the coordinates, but you won't have the same wild crops.
This pre5 seems to be too much unstable to keep using it.

**Comment by Craluminum2413** [comment] 2021-06-20 20:30
That is why I suggest waiting about 5-10 more patches when the game will not crash from the first placed ladder

**Comment by copygirl** [comment] 2021-06-20 20:51
Also occurs with (acacia) tree and flint axe, see #1038.

**Comment by botenredwolf** [comment] 2021-06-21 03:28
Same experience, harvesting grass with granite knife. About 18-20 harvested and then a crash: 

Running on 64 bit Windows with 128 GB RAM 
Version: v1.15.0-pre.5 (Unstable)6/20/2021 22:22:02: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Datastructures.JsonObject.ToString()
   at Vintagestory.API.Common.CollectibleObject.DamageItem(IWorldAccessor world, Entity byEntity, ItemSlot itemslot, Int32 amount)
   at Vintagestory.API.Common.CollectibleObject.OnBlockBrokenWith(IWorldAccessor world, Entity byEntity, ItemSlot itemslot, BlockSelection blockSel, Single dropQuantityMultiplier)
   at Vintagestory.Client.NoObf.ClientMain.OnPlayerTryDestroyBlock(BlockSelection blockSelection)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.ContinueBreakSurvival(BlockSelection blockSelection, Block block, Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _MOdxi5vG0bna4SXTrSTDPTj4rVg._4Yd80CSETSLq3ryQSQyu0CgTVkD(Single )
   at _ZTfxbGnrfFIByyznrlGTkx2vj9o._fa9CGlG0qMmF2Mdhb11gCvro90x(Single )
   at _ZTfxbGnrfFIByyznrlGTkx2vj9o._xGQguz838073AFF0xjLFxOuNFvd(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _d9njO8fhbi6B7GfzQuHDVcoAyY6._3LaTwazRKZVPcHgOIFRHUTG6ZpD(_4lAn4F3kZqtcY1FLfNdzOm0cnKI , String[] )
   at _QyjwcZJgpstl1btBhzlpbS2YOg0._3LaTwazRKZVPcHgOIFRHUTG6ZpD(ThreadStart )

**Comment by Craluminum2413** [comment] 2021-06-21 09:49
@Saricane @Saphkey @JoIamar What was the durability of your tools? Were they nearly broken?

**Comment by Craluminum2413** [comment] 2021-06-21 09:51
If your tools were nearly broken (stone axes break easily from chopping big tree), then it was fixed in 1.15.0-pre.6
> Fixed: Game crashing when breaking blocks with a tool that has 1 durability left

**Comment by Saricane** [comment] 2021-06-21 10:36
For the crash I had harvesting turnips, I perfectly remember I was hitting it with a stick, so, not a tool.

**Comment by Craluminum2413** [comment] 2021-06-21 10:37
> Fixed: Game crashing when trying to harvest a wild crop

**Comment by Saphkey** [comment] 2021-06-21 13:09
> 
> 
> @Saricane @Saphkey @JoIamar What was the durability of your tools? Were they nearly broken?

The axe only had 12 durability left. and the tree had more than 12 blocks. The crash no longer happens in pre 6.

**Closed** 2021-06-21 13:37 UTC
Labels: status: resolved, target: survival, type: bug
