### ISSUE TITLE
Crash while smithing a scythe

### ISSUE THREAD

**Issue by Boesknecht** [anegostudios/VintageStory-Issues#467] opened 2020-03-12 17:52 UTC
**Game Version:** 1.12.5
**Platform:** Windows 10
**Modded:** No 
### Description
While smithing a Scythe and pushing a little block to the left out of the shape and then trying to push it back right one stroke.

### How to reproduce
1. Take a tin bronze ingot out of the forge and put it on the anvil, choose scythe shape
2. Smith it with a tin bronze hammer and push one "little block" out of the shape to the left
3. Now change the "hammer mode" to push to the right and use it on this "little block"
4. Game crash occurs

### Expected behavior
Expected the "little block" to return into the scythe shape

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.12.5 (Stable)12.03.2020 18:44:36: Critical error occurred
System.IndexOutOfRangeException: Der Index war außerhalb des Arraybereichs.
   bei Vintagestory.GameContent.BlockEntityAnvil.OnUpset(Vec3i voxelPos, BlockFacing towardsFace)
   bei Vintagestory.GameContent.BlockEntityAnvil.OnUseOver(IPlayer byPlayer, Vec3i voxelPos, BlockSelection blockSel)
   bei Vintagestory.GameContent.ItemHammer.OnHeldAttackStop(Single secondsPassed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   bei _RBWjLi9HnRqEtluCiqYBp4ujfaK._8Qtn8ES10YaYq51yN95EtEob7zB()
   bei Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   bei _cbodHKZNx5G5B0ajOJRiKOMUi6d._ykWNCOaup5AuVWVrjbcBvBqoivo(Single )
   bei _cbodHKZNx5G5B0ajOJRiKOMUi6d._mNh2oavQCEJVrb6jUHjJh1mToWE(Single )
   bei _2LdR0X5PHgIsH0Qq61AbDPLAlFo._jHkasPdfycueGbkSaxMFKzSMfh3(Single )
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._AjNkRnsn39TXAz2S4OVzXdXYu0h(Single )
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._NbPATb9BXlxRc4ZhH2GgyFCUInp(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _hCuHXesCXlp0LGSdrsPFpw4up5n._mOm8EuKIvHpaJoztxNWRpAoOpbM(_55ISULxdcpPfF8D2JP831aWhOBe , String[] )
   bei _iCfIbY24GyBXP5lAwqsSlD9COxC._mOm8EuKIvHpaJoztxNWRpAoOpbM(ThreadStart )
-------------------------------
```

**Comment by PeterBzz** [comment] 2020-03-15 15:18
I think, my crash is connected. It occurred during my first try at smiting. Goal - copper saw blade. Maybe, the problem is connected with the fact, that the copper piece began to cool down. And I was doing it with low HP (camera floating). Here is the report:

Running on 64 bit Windows with 16 GB RAM 
Version: v1.12.8 (Stable)15.03.2020 17:07:25: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.BlockEntityAnvil.OnUpset(Vec3i voxelPos, BlockFacing towardsFace)
   at Vintagestory.GameContent.BlockEntityAnvil.OnUseOver(IPlayer byPlayer, Vec3i voxelPos, BlockSelection blockSel)
   at Vintagestory.GameContent.ItemHammer.OnHeldAttackStop(Single secondsPassed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   at _z0BDthbM9TYCr36Cuqy4evNwAdI._HYhc9umDZmH8RDQyqMf4JtMn4Gp()
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at _DheU0S41ys8PmWwanVxliVufAfL._AKTgHF9r1SjkR8Qry41rzH1bshD(Single )
   at _DheU0S41ys8PmWwanVxliVufAfL._5nmBA4REW1c7YBzSjT1tTS3qNSp(Single )
   at _EBtxK36Ixmcei9M4cHb3yN0CdBY._SBmZIE5zeKBZLld4sDoBkph45oC(Single )
   at _TCuegFvuCG7xQqhWKljGWgaccAS._xnJNZgMqo5oGjGjHTS2kXgpC9eH(Single )
   at _TCuegFvuCG7xQqhWKljGWgaccAS._uw3xmExX4CRVc5TYKty6OJkT52C(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _BjgcNpIFkj1jqrVxzsqeX8AsdOJ._Sxh5j8nPFBKHENmnO5xs7MH8hze(_dWKuoESsZrjrNSOe8XL3edrjaTJ , String[] )
   at _OeweVW96y8iGyqsCmuTDn7vCxyG._Sxh5j8nPFBKHENmnO5xs7MH8hze(ThreadStart )
-------------------------------

**Comment by Bloodsaw** [comment] 2020-03-19 23:17
Are both of you able to reproduce your crash?
I tried everything that came into my mind to provoke this crash, but with no success.

I do have a feeling that this issue is maybe connected with #67 (tried to provoking it this way) and #459, it happens on different actions, but the stack traces are pretty similar.
First I thought this could be an desync issue, but maybe its more on the rendering site?

**Comment by PeterBzz** [comment] 2020-03-20 07:42
Bloodsaw, I did smiting just once after that and without problem. If it happens again, I'll add new info

**Comment by tyronx** [comment] 2020-03-26 07:53
This should be fixed already as well. I think we can safely close this issue.

**Closed** 2020-03-26 16:39 UTC
Labels: status: new, target: survival, type: crash
