### ISSUE TITLE
Open containers and creatures are invisible in 1.17.4

### ISSUE THREAD

**Issue by 8mittim8** [anegostudios/VintageStory-Issues#2217] opened 2022-09-26 12:07 UTC
**Game Version:** 1.17.4  
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer 

### Description
Opening an animated container (like vessel or chest) turns the container invisible. The container returns to being visible when closed.
Similarly the crank and screw on the fruitpress also turns invisible when not in released position.
All creatures (animals and drifters) are invisible as well.

I have reinstalled 1.17.4 but issues persist.
I have deinstalled 1.17.4 and installed 1.17.3 and issues disappear.

**Comment by tyronx** [comment] 2022-10-02 10:36
i'm not able to reproduce this in 1.17.4 in a super flat world, for either chests or vessels.

**Comment by Saricane** [comment] 2022-10-28 14:50
I add this post for another french player who had exactly the same bug. He downgraded version after version until the bug dissapeared with ... 1.17.3. So exactly the same problem as 8mittim8. May be a problem with graphic card / graphic driver ?

**Comment by tyronx** [comment] 2022-11-26 17:10
duplicate of #2277

**Closed by tyronx** 2022-11-26 17:10 UTC
Labels: status: can't reproduce
