### ISSUE TITLE
UI Overlapping

### ISSUE THREAD

**Issue by Yota77** [anegostudios/VintageStory-Issues#2208] opened 2022-09-21 20:51 UTC
**Game Version:** 1.17.4  
**Platform:** Windows   
**Modded:** No
**SP/MP:** Singleplayer

### Description
When moving the UI Character panel the items overlap another panel.

### How to reproduce
1. Move the UI Character Panel

![UI_overlap](https://user-images.githubusercontent.com/70011570/191607710-979aa1cd-17ae-43c9-9a8c-f796ae8a0a8b.png)

**Comment by Craluminum2413** [comment] 2022-09-24 09:53
Duplicate of #1152

**Closed by Craluminum2413** 2022-09-24 09:53 UTC
Labels: status: new
