### ISSUE TITLE
Crafted crates not expanded.

### ISSUE THREAD

**Issue by Empirehacker91** [anegostudios/VintageStory-Issues#3576] opened 2024-02-12 05:29 UTC
### Game Version

v1.19.3

### Platform

Windows

### Modded

None

### SP/MP

Multiplayer

### Description

Made a Crate out of Walnut says its 20 slots should hold 1280 only holds the same as ancient crates (1024).

### Screenshots

![Crate issue 1](https://github.com/anegostudios/VintageStory-Issues/assets/159750467/bf19497f-d8c1-4b7a-b321-56ed339a91fa)
![Crate issue 2](https://github.com/anegostudios/VintageStory-Issues/assets/159750467/a948924c-fe99-4fbf-9bcc-f14bb9c9c485)

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2024-02-12 10:10
Duplicate of #3562

**Closed by Craluminum2413** 2024-02-12 10:10 UTC
Labels: status: new
