### ISSUE TITLE
При создании мира вылетает игра

### ISSUE THREAD

**Issue by IDVfly** [anegostudios/VintageStory-Issues#4487] opened 2024-11-10 12:45 UTC
### Game Version

1.20.0 pre11

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

При создании мира вылетает игра, на также сервера подключиться не получается

### How to reproduce

1. Запустить игру
2. Попробовать создать мир (иногда даже не нужно создавать мир, игра может просто вылететь в меню с такой же ошибкой).

### Logs

Running on 64 bit Windows 10.0.19045.0 with 32670 MB RAM
Game Version: v1.20.0-pre.11 (Unstable) 
10.11.2024 15:14:46: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockShapeFromAttributes.OnUnloaded(ICoreAPI api) in VSSurvivalMod\Block\BlockShapeFromAttributes.cs:line 170
   at Vintagestory.Client.NoObf.ClientMain.Dispose() in VintagestoryLib\Client\ClientMain.cs:line 2711
   at Vintagestory.Client.NoObf.ClientMain.DestroyGameSession(Boolean gotDisconnected) in VintagestoryLib\Client\ClientMain.cs:line 2644
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleDisconnectPlayer(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 185
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in VintagestoryLib\Client\Systems\ProcessPacketTask.cs:line 16
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in VintagestoryLib\Client\Systems\ProcessPacketTask.cs:line 10
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 786
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 254
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 127
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Craluminum2413** [comment] 2024-11-10 13:01
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4095

**Closed by Craluminum2413** 2024-11-10 13:01 UTC
Labels: status: new
