### ISSUE TITLE
[v1.19.0-pre.7] Crash and save corruption while interacting with a coal pile

### ISSUE THREAD

**Issue by sk4r** [anegostudios/VintageStory-Issues#3261] opened 2023-11-29 06:05 UTC
### Game Version

v1.19.0-pre.7

### Platform

Linux

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Crash while interacting with a coal pile.

When I tried to load the game again, it crashed.

I tried out the save repair button, it loaded but shortly after crashed again. It now loads the save but once I hover over near the coal pile, crashes again.

### How to reproduce

Multiplayer game crashed while I interacted with a coal pile. There were 3 piles near each other, two of them placed 1 block lower, if that matters. Haven't tried to reproduce exact steps.

### Screenshots

Looks like now there's just a single visible pile that takes up a block and a layer above it, which causes a crash when mouse hovers over

![2023-11-28_22-28-10](https://github.com/anegostudios/VintageStory-Issues/assets/19878249/c1ed28f4-736c-4e87-896a-14ee791f5a62)

### Logs
From the server log
```
28.11.2023 21:55:40 [Server Fatal] Caught unhandled exception in thread 'ai-pathfinding'. Shutting down server.
28.11.2023 21:55:41 [Server Error] Exception: Index was outside the bounds of the array.
   at Vintagestory.GameContent.BlockCoalPile.GetCollisionBoxes(IBlockAccessor blockAccessor, BlockPos pos) in VSSurvivalMod\Block\BlockCoalPile.cs:line 119
   at Vintagestory.API.MathTools.CollisionTester.GetCollidingBlock(IBlockAccessor blockAccessor, Cuboidf entityBoxRel, Vec3d pos, Boolean alsoCheckTouch) in VintagestoryApi\Math\CollisionTester.cs:line 256
   at Vintagestory.Essentials.AStar.traversable(PathNode node, Single stepHeight, Int32 maxFallHeight, Cuboidf entityCollBox, Cardinal fromDir, Single& extraCost) in VSEssentials\Entity\Pathfinding\Astar\AStar.cs:line 257
   at Vintagestory.Essentials.AStar.FindPath(BlockPos start, BlockPos end, Int32 maxFallHeight, Single stepHeight, Cuboidf entityCollBox, Int32 searchDepth, Int32 mhdistanceTolerance) in VSEssentials\Entity\Pathfinding\Astar\AStar.cs:line 68
   at Vintagestory.Essentials.AStar.FindPathAsWaypoints(BlockPos start, BlockPos end, Int32 maxFallHeight, Single stepHeight, Cuboidf entityCollBox, Int32 searchDepth, Int32 mhdistanceTolerance) in VSEssentials\Entity\Pathfinding\Astar\AStar.cs:line 35
   at Vintagestory.Essentials.PathfindingAsync.ProcessQueue(AStar astar, Int32 maxCount) in VSEssentials\Entity\Pathfinding\PathfindingAsync.cs:line 90
   at Vintagestory.Server.ServerThread.Update() in VintagestoryLib\Server\ServerThread.cs:line 111
   at Vintagestory.Server.ServerThread.Process() in VintagestoryLib\Server\ServerThread.cs:line 92
```
From the crash reporter
```
Running on 64 bit Linux with 39446 MB RAM
Game Version: v1.19.0-pre.7 (Unstable)
11/28/2023 9:55:26PM: Critical error occurred
Loaded Mods: game@1.19.0-pre.7, creative@1.19.0-pre.7, survival@1.19.0-pre.7
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.BlockCoalPile.GetSelectionBoxes(IBlockAccessor blockAccessor, BlockPos pos) in VSSurvivalMod\Block\BlockCoalPile.cs:line 124
   at Vintagestory.Client.NoObf.ClientMain.GetBlockIntersectionBoxes(BlockPos pos) in VintagestoryLib\Client\ClientMain.cs:line 3044
   at Vintagestory.API.MathTools.AABBIntersectionTest.RayIntersectsBlockSelectionBox(BlockPos pos, BlockFilter filter) in VintagestoryApi\Math\AABBIntersectionTest.cs:line 117
   at Vintagestory.API.MathTools.AABBIntersectionTest.GetSelectedBlock(Single maxDistance, BlockFilter filter) in VintagestoryApi\Math\AABBIntersectionTest.cs:line 102
   at Vintagestory.Common.GameMain.RayTraceForSelection(IWorldIntersectionSupplier supplier, Ray ray, BlockSelection& blockSelection, EntitySelection& entitySelection, BlockFilter bfilter, EntityFilter efilter) in VintagestoryLib\Common\GameMain.cs:line 189
   at Vintagestory.Common.GameMain.RayTraceForSelection(IPlayer player, BlockSelection& blockSelection, EntitySelection& entitySelection, BlockFilter bfilter, EntityFilter efilter) in VintagestoryLib\Common\GameMain.cs:line 196
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.UpdateCurrentSelection() in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 385
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.UpdatePicking(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 237
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 101
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 796
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 989
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 322
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by sk4r** [comment] 2023-11-29 06:21
I tried out the save repair button, it loaded but shortly after crashed again. It now loads the save but once I hover over near the coal pile, crashes again.

**Comment by tyronx** [comment] 2024-01-01 13:52
Duplicate of #3261

**Closed by tyronx** 2024-01-01 13:52 UTC
Labels: status: new, version: 1.19
