### ISSUE TITLE
Crash on Startup(1.15.6 Stable)

### ISSUE THREAD

**Issue by TY-NiD50** [anegostudios/VintageStory-Issues#1349] opened 2021-10-09 04:51 UTC
Running on 64 bit Windows with 8 GB RAM 
Version: v1.15.5 (Stable)10/9/2021 12:41:47 AM: Critical error occurred
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at _q065sSmA3CNgGuKTGnlAjR4ljPw._WkSl7yfiyr5DwPiSMvTudNAhp6(_t3ILnyYBq5OoYhhBY3JeTWgFmJDA , String[] )
   at _DBu5wiQWRAHGS5G2jiCKymvQ9yE._WkSl7yfiyr5DwPiSMvTudNAhp6(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 6/11/2021 8:54:42 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 6079b344
P4: atio6axx.dll
P5: 6.14.10.13399
P6: 55c029a0
P7: c0000005
P8: 00000000003f3020
P9: 
P10: 

Attached files:

These files may be available here:
C:\Users\Joshua Mink\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_42355878747a9cddb6e48248dbec03fb3e788_0e17df7c

Analysis symbol: 
Rechecking for solution: 0
Report Id: c187c7a6-cb18-11eb-8db1-485b398e340b
Report Status: 2 }
--------------
{ TimeGenerated = 6/11/2021 8:54:36 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.14.10.0, time stamp: 0x6079b344
Faulting module name: atio6axx.dll, version: 6.14.10.13399, time stamp: 0x55c029a0
Exception code: 0xc0000005
Fault offset: 0x00000000003f3020
Faulting process id: 0x1630
Faulting application start time: 0x01d75f207892578e
Faulting application path: C:\Users\Joshua Mink\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\system32\atio6axx.dll
Report Id: c187c7a6-cb18-11eb-8db1-485b398e340b }
--------------
{ TimeGenerated = 6/11/2021 8:54:35 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
Stack:
   at Vintagestory.Client.NoObf.ClientPlatformWindows.RenderMesh(Vintagestory.API.Client.MeshRef)
   at Vintagestory.GameContent.AnvilWorkItemRenderer.OnRenderFrame(Single, Vintagestory.API.Client.EnumRenderStage)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(Vintagestory.API.Client.EnumRenderStage, Single)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(Vintagestory.API.Client.EnumRenderStage, Single)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single)
   at _vKnDSS3ZW5fZhqcIJSzL9xbAUttA._mhcyOBzdAWALla9FVcjc15WACGi(Single)
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._3HP2xkrryy8Ktr1q1yqHHv9s1kb(Single)
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._JbXJA0SA6LQOS6diuqtXAjMb8Fo(Single)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(System.Object, OpenTK.FrameEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.GameWindow.RaiseRenderFrame(Double, Double ByRef)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double, Double)
   at _ISiSTzGmXXpAqo3PzdxdVD1bClZ._ofvn0Tr1zNGCbNV3SxvKs2MXNP(_C7CLMRbe3BejVtaARYCgl7Bg1vl, System.String[])
   at _0Y0SN1uu1V65pRLxvnN2xsIjXAg._ofvn0Tr1zNGCbNV3SxvKs2MXNP(System.Threading.ThreadStart)
   at _ISiSTzGmXXpAqo3PzdxdVD1bClZ._CdxDiVDTWOWMdxOVeU2035FgbIK(System.String[])
 }
```

**Comment by TY-NiD50** [comment] 2021-10-09 04:55
Is as stated, I double-click the desktop icon, and it displays this issue. I have installed the vs_install_1.15.6.exe from ground up without anti-virus intervening.

**Comment by copygirl** [comment] 2021-10-09 06:05
Closing as duplicate of 1303. I wrote there:

> I believe this should be fixed by installing .NET Framework 4.6.1 or 4.6.2.
> Go [here](https://dotnet.microsoft.com/download/dotnet-framework/net462) and download the Runtime for this version of .NET.

Let me know if that doesn't fix it. I believe the devs are working on making the error more clear.

**Closed by copygirl** 2021-10-09 06:05 UTC
Labels: status: duplicate

**Comment by TY-NiD50** [comment] 2021-10-09 19:25
Thank you. It did the job, in the future I will look for closed issues of the same type.
