### ISSUE TITLE
Support Beams are placed incorrectly when sitting

### ISSUE THREAD

**Issue by LarekFlynn** [anegostudios/VintageStory-Issues#4597] opened 2024-12-05 06:53 UTC
### Game Version

v1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

probably related to issue #3594
when seated the endpoint of a beam doesn't match the preview, instead it is placed as if you were looking at the same angle while standing

### How to reproduce

mine a block on the level with your legs, leaving a block unsupported above that point.
sit to see the underside of that block and begin a support from the ground directly beneath it.
targeting the center of the bottom of the upper block(looking slightly upwards from seated) place end of support.
support instead connects to upper portion of the side face of the block instead of its bottom.
this is the same place that you are looking if you stand up.

### Logs

```Log```

**Comment by maltiez2** [comment] 2024-12-07 11:02
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/3594
When IFP is tuned off all works correctly

**Comment by LarekFlynn** [comment] 2024-12-08 08:21
Issue is present when IFP is turned off. End points place as if you were not sitting.

**Comment by LarekFlynn** [comment] 2024-12-09 16:16
@Craluminum2413 could you reopen this please?

**Comment by Craluminum2413** [comment] 2024-12-09 16:46
@LarekFlynn No, it is duplicate

**Closed** 2024-12-09 16:45 UTC
Labels: status: duplicate
