### ISSUE TITLE
world not runing

### ISSUE THREAD

**Issue by melnote** [anegostudios/VintageStory-Issues#4548] opened 2024-11-21 23:56 UTC
### Game Version

v1.20.0-pre.11

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

led a pig on a rope across the river. the game crashed. the world doesn't start. repair doesn't work too

### How to reproduce

say how fix it

### Logs

Running on 64 bit Windows 10.0.19045.0 with 31864 MB RAM
Game Version: v1.20.0-pre.11 (Unstable)
22.11.2024 2:51:55: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockShapeFromAttributes.OnUnloaded(ICoreAPI api)
   at Vintagestory.Client.NoObf.ClientMain.Dispose()
   at Vintagestory.Client.NoObf.ClientMain.DestroyGameSession(Boolean gotDisconnected)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleDisconnectPlayer(Packet_Server packet)
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet)
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run()
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt)
   at Vintagestory.Client.ScreenManager.Render(Single dt)
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e)
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1()
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)

**Comment by Craluminum2413** [comment] 2024-11-22 10:52
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4095

**Closed by Craluminum2413** 2024-11-22 10:52 UTC
Labels: status: incomplete
