### ISSUE TITLE
Boat Clicking crush

### ISSUE THREAD

**Issue by ImHirou** [anegostudios/VintageStory-Issues#4094] opened 2024-09-18 17:48 UTC
### Game Version

v1.20.pre-1

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Running on 64 bit Windows 10.0.19045.0 with 16296 MB RAM
Game Version: v1.20.0-pre.1 (Unstable)
18.09.2024 20:46:10: Critical error occurred
Loaded Mods: game@1.20.0-pre.1, creative@1.20.0-pre.1, survival@1.20.0-pre.1
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.EntityBehaviorAttachable.TryAttach(ItemSlot itemslot, Int32 slotIndex) in VSSurvivalMod\Entity\Behavior\BehaviorAttachable.cs:line 270
   at Vintagestory.GameContent.EntityBehaviorAttachable.OnInteract(EntityAgent byEntity, ItemSlot itemslot, Vec3d hitPosition, EnumInteractMode mode, EnumHandling& handled) in VSSurvivalMod\Entity\Behavior\BehaviorAttachable.cs:line 180
   at Vintagestory.GameContent.EntityBoat.OnInteract(EntityAgent byEntity, ItemSlot itemslot, Vec3d hitPosition, EnumInteractMode mode) in VSSurvivalMod\Systems\Boats\EntityBoat.cs:line 467
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsNoBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 394
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 819
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1023
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 694
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 669
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

### How to reproduce

Just clicking boat with chest in hands and ctrl pressed

**Comment by Craluminum2413** [comment] 2024-09-18 17:53
Duplicate of #4093, crash is the same

**Closed by Craluminum2413** 2024-09-18 17:53 UTC
Labels: status: new
