### ISSUE TITLE
The Game Crashes When I Try To Load My World

### ISSUE THREAD

**Issue by SteampunkWolf** [anegostudios/VintageStory-Issues#619] opened 2020-10-24 17:19 UTC
**Game Version:** 1.13.4
**Platform:** Windows
**Modded:** No

### Description
When I Try To Enter My World The Game Crashes
### How to reproduce
1. Go Into Your Game
2. Start Loading A World
3. It crashes

### Expected behavior
I Expected The Game To Not Crash

### Screenshots
I Don't Know How To Screenshot

### Logs
```Running on 64 bit Windows with 8 GB RAM 
Version: v1.13.4 (Stable)10/24/2020 10:10:07 AM: Critical error occurred
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.MemoryStream.InternalReadInt32()
   at Vintagestory.API.Common.EntityAgent.FromBytes(BinaryReader reader, Boolean forClient)
   at Vintagestory.API.Common.EntityPlayer.FromBytes(BinaryReader reader, Boolean forClient)
   at Vintagestory.Client.NoObf.ClientSystemEntities.createOrUpdateEntityFromPacket(_QZrkPDkApxKITNHv7gQ8CjGzfic entitypacket, ClientMain game, Boolean addToLoadQueue)
   at Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntityLoadedPacket(_5JvvYf9KFEDVZitFymVPmMx6YcA serverpacket)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _FVGd1lrg8990jw7ZGueNjtrnCWl._toICAyZ9EYSaLsmD4KTuQWUbqjP(Single )
   at _LSAAgZhw31Rqs2is6nnojfZBbQC._4BykKOCicJqCBHpyWIgTmxWrTrg(Single )
   at _LSAAgZhw31Rqs2is6nnojfZBbQC._6XmOxKoTYrFLRCGd58p58XW43nD(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._EEzpApWBQHtHR4iMJabXK2wDvlA(_ex0VSgRAdtsvhANmJHZHaf9ATWt , String[] )
   at _IcGByoJhapvESnm6vaOawAHbkeU._EEzpApWBQHtHR4iMJabXK2wDvlA(ThreadStart )
-------------------------------

**Comment by copygirl** [comment] 2020-10-24 18:28
Likely duplicate of #390. You will probably be able to resolve the issue by opening the world in "Repair Mode", accessible by pressing the pencil icon in the world selection screen. Did anything happen last time you played the game? Such as a crash, power outage or so?

**Comment by SteampunkWolf** [comment] 2020-10-24 22:29
No, Nothing happened other than i was exploring and it went into the "not responding" mode. i had to close it but when i tried to get back in it didn't work. I have created a new world with different settings but on the same seed and I am actually doing better than I was before. Thank you so much for your help and I will do what you said to try to get my old world back.

**Comment by SteampunkWolf** [comment] 2020-10-24 22:30
(if it wasnt clear when i created a new world it worked)

**Comment by copygirl** [comment] 2020-10-24 23:03
Alright. The game freezing like that will have to be investigated some time, but it's difficult to without even the logs. If someone else runs into this, please provide these before restarting the game, as it might offer some details. Will close this issue for now.

@SteampunkWolf Enjoy the game!

**Closed by copygirl** 2020-10-24 23:03 UTC
Labels: status: duplicate
