### ISSUE TITLE
Game crashes before I can load into multiplayer

### ISSUE THREAD

**Issue by Damien278** [anegostudios/VintageStory-Issues#2715] opened 2023-05-09 03:00 UTC
### Game Version

v1.18.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Every time I try to load into the my friend's multiplayer server, it loads to about 1,000 kilobytes, and then it crashes telling me there is a problem with the mods on the game. I haven't downloaded anything but the main game. so this is extremely confusing to me.
![Screenshot 2023-05-08 225221](https://user-images.githubusercontent.com/132970035/236982503-954a9197-692d-4fbc-8771-50f4b8c31534.png)

### How to reproduce

1. Load in the game as normal, 2. Attempt to join a multiplayer server, 3. Once it hits about 1,000 kilobytes, the game crashes and sends you the separate crash tab with the log I pasted below.

### Logs

```Log```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.1 (Stable)
5/8/2023 10:51:46 PM: Critical error occurred
Loaded Mods: game@1.18.1, creative@1.18.1, survival@1.18.1
System.Exception: Asset game:config/traits.json could not be found
   at Vintagestory.Common.AssetManager.Get(AssetLocation Location) in VintagestoryLib\Common\FileIO\AssetManager.cs:line 274
   at Vintagestory.GameContent.CharacterSystem.loadCharacterClasses() in VSSurvivalMod\Systems\Character\Character.cs:line 160
   at System.Action.Invoke()
   at Vintagestory.Client.NoObf.ClientSystemStartup.OnAllAssetsLoaded_ClientSystems(Int32 i) in VintagestoryLib\Client\Systems\Startup.cs:line 843
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 755
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 304
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 724
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 627
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 126
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 5/8/2023 10:51:47 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.1.0, time stamp: 0x6443b447
Faulting module name: KERNELBASE.dll, version: 10.0.22621.1555, time stamp: 0x235a45d0
Exception code: 0xe0434352
Fault offset: 0x000000000008fdec
Faulting process id: 0x0x2a08
Faulting application start time: 0x0x1d982212ba90c57
Faulting application path: C:\Users\jakem\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: cd87f512-1870-499b-b7c6-c3cc75dfecfc
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 5/8/2023 10:51:46 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Collections.Generic.KeyNotFoundException
   at Vintagestory.Client.NoObf.ShapeTesselatorManager.TesselateBlockForInventory(Vintagestory.API.Common.Block)
   at Vintagestory.Client.NoObf.ShapeTesselatorManager.TesselateBlocksForInventory_ASync(System.Collections.Generic.IList`1<Vintagestory.API.Common.Block>)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
--------------
{ TimeGenerated = 5/8/2023 10:42:48 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Collections.Generic.KeyNotFoundException
   at Vintagestory.Client.NoObf.ShapeTesselatorManager.TesselateBlock(Vintagestory.API.Common.Block)
   at Vintagestory.Client.NoObf.ShapeTesselatorManager.TesselateBlocks_Async(System.Collections.Generic.IList`1<Vintagestory.API.Common.Block>)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }

**Comment by radfast** [comment] 2023-05-09 08:36
Check your game installation folder, in the `/assets/game/config` folder, is the file `traits.json` there?  Can you open it in a text editor?     If that looks OK, try asking your friend to check that the file is also present on the server.

The error report states that file can't be found.  The game is crashing because it can't proceed without it / we assumed nobody would ever want to delete that file.

**Comment by Craluminum2413** [comment] 2023-05-09 12:21
Duplicate of #2615

**Closed by Craluminum2413** 2023-05-09 12:21 UTC
Labels: status: incomplete
