### ISSUE TITLE
Game has crashed when hovering onto flint stones [RU_locale]

### ISSUE THREAD

**Issue by Schmarotzer** [anegostudios/VintageStory-Issues#2065] opened 2022-07-29 11:41 UTC
**Game Version:** 1.17.0rc2  
**Platform:** Windows 10
**Modded:** No
**SP/MP:** Singleplayer / Multiplayer

### Description
Game has crashed when I hovering onto flint in my inventory. I think it crashed because of incorrect russian localisation

### How to reproduce
1. Open Creative or pick up filnt
2. Open inventory, hover mouse onto flint
3. Game crashes

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.0-rc.2 (Unstable)
Loaded Mods: game@1.17.0-rc.2, creative@1.17.0-rc.2, survival@1.17.0-rc.2
29.07.2022 18:07:28: Critical error occurred
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в Vintagestory.API.Client.HotkeyComponent.GenHotkeyTexture() в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\HotkeyComponent.cs:строка 49
   в Vintagestory.API.Client.GuiElementRichtext.ComposeFor(ElementBounds bounds, Context ctx, ImageSurface surface) в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementRichtext.cs:строка 418
   в Vintagestory.API.Client.GuiElementRichtext.Compose(Boolean genTextureLater) в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementRichtext.cs:строка 118
   в Vintagestory.API.Client.GuiElementItemstackInfo.<>c__DisplayClass20_1.<AsyncRecompose>b__1() в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementItemstackInfo.cs:строка 178
   в Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:строка 1138
   в Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:строка 123
   в Vintagestory.Client.ScreenManager.Render(Single dt) в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:строка 664
   в Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:строка 608
   в Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\GameWindow.cs:строка 125
   в System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   в OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 476
   в OpenTK.GameWindow.DispatchRenderFrame() в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 452
   в OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 375
   в Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   в Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:строка 87
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 29.07.2022 17:50:53, Site = , Source = Application Error, Message = Имя сбойного приложения: Vintagestory.exe, версия: 1.17.0.0, метка времени: 0x62e01e15
Имя сбойного модуля: KERNELBASE.dll, версия: 10.0.18362.1474, метка времени: 0x5ae7af90
Код исключения: 0xc0020001
Смещение ошибки: 0x0000000000043b19
Идентификатор сбойного процесса: 0x3fc8
Время запуска сбойного приложения: 0x01d8a338f1f5691c
Путь сбойного приложения: E:\Games\Vintagestory\Vintagestory.exe
Путь сбойного модуля: C:\WINDOWS\System32\KERNELBASE.dll
Идентификатор отчета: a843282a-e407-42ef-beef-5ea14eaebde8
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:  }
--------------
{ TimeGenerated = 29.07.2022 17:50:53, Site = , Source = .NET Runtime, Message = Приложение: Vintagestory.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за необработанного исключения.
Сведения об исключении: код исключения c0020001, адрес исключения 00007FFCCB5A3B19
Стек:
 }
--------------
{ TimeGenerated = 23.07.2022 16:11:20, Site = , Source = Application Error, Message = Имя сбойного приложения: Vintagestory.exe, версия: 1.17.0.0, метка времени: 0x62d05a40
Имя сбойного модуля: nvoglv64.dll, версия: 30.0.15.1215, метка времени: 0x62331d77
Код исключения: 0xc0000005
Смещение ошибки: 0x0000000000852fda
Идентификатор сбойного процесса: 0x552c
Время запуска сбойного приложения: 0x01d89e73217b0f95
Путь сбойного приложения: E:\Games\Vintagestory\Vintagestory.exe
Путь сбойного модуля: C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_c0e159863e7afdde\nvoglv64.dll
Идентификатор отчета: 61d88ca3-0e70-4806-8e79-9b1b9a68fb16
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:  }
```

**Comment by Craluminum2413** [comment] 2022-07-29 11:53
Duplicate of #2055

**Closed by Craluminum2413** 2022-07-29 11:53 UTC
Labels: status: new

**Comment by Schmarotzer** [comment] 2022-07-29 12:20
I fixed it on Crowdin for these lines:
-> itemdesc-clay-*
-> itemdesc-flint
<hk>shift</shift> was translated, but it should not have been translated
