### ISSUE TITLE
Game crashed when creating a new world with current seed data

### ISSUE THREAD

**Issue by KibaAlaric** [anegostudios/VintageStory-Issues#821] opened 2021-03-22 08:47 UTC
**Game Version:** v1.14.8
**Platform:** Windows
**Modded:** Yes
.Grass Stuff - Tach Roofing
.Primitive Survival
.Survival Handbook Categories
.Essentials
.CarryCapacity
.HUD Clock
.StepUp
.Creative Mode
.Survival Mode
.Workbench Expansion
.GraveMod
.No Monsters Mod

### Description
The issue I had ran into was I was playing in my world as usual and wanted to recreate a new world with the same seed to keep the spawn and world gen I had but as soon as I hit the button to do so the game crashed.

### How to reproduce
1. Make a 'normal world as you usually would then just choose to create a new world with the same seed data'
2. Use it on 'PC?'
3. It crashes / doesn't do the thing.

### Expected behavior
I expected to be able to create a new world with the current seed data that I was playing on.

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Running on 64 bit Windows with 0 GB RAM 
Version: v1.14.8 (Stable)3/22/2021 4:35:31 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at _PW8NVVq6wBR9krMQ9GulRnv6PMD._h9K0G4wbrt2CCpt5A92lCnKV2gP()
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   at _oDnqPT3M9pq9hNGZM4RDtA6RTnG._TE0ypoo5kb57Ue2gLv7daIuY6VD(MouseEvent )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _YrS2W1MoaeqC4xqH8ItdZB6vADN._8t1BmEWVlCT9mjx5M0vFIzU9tif(_7T00Rjby4si0wyEBez5dXNqLm7h , String[] )
   at _ejKuc6cg0k8V39o8jDIzquyczbO._8t1BmEWVlCT9mjx5M0vFIzU9tif(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 3/11/2021 5:35:25 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2199860474778786707, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.7.0
P3: 10.0.18363.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\themu\AppData\Local\Temp\RDREA23.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREA34.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREA45.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREA62.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREA82.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 0c1ff763-0b89-42b7-ac46-3f432d38e29c
Report Status: 268435456
Hashed bucket: be3cf1634edaf807fe8779724a9c9b93
Cab Guid: 0 }

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.

Note that the crash log contains all crashes that have happened so far.
You likely only want to report the latest one.
```

**Comment by copygirl** [comment] 2021-03-22 09:11
Duplicate of #795.

**Closed by copygirl** 2021-03-22 09:11 UTC
Labels: status: new, type: bug
