### ISSUE TITLE
lakes don't fill all the way in

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#88] opened 2018-04-22 20:22 UTC
I've noticed that lakes don't fill in all the time during world generation. I haven't checked but I always assumed it was because it was crossing a chunk boundary.

**Comment by copygirl** [comment] 2018-04-22 21:45
Duplicate of #47?

**Comment by sirStroam** [comment] 2018-04-23 02:40
Yep

**Closed** 2018-04-23 02:41 UTC
