### ISSUE TITLE
Huge freezes with 1.15-rc1

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1110] opened 2021-07-07 15:32 UTC
**Game Version:** 1.15.0-rc1
**Platform:** Windows
**Modded:** No

### Description
Just upgraded to rc1 and since, I have freezes. Some of them are even 2-3 seconds longs, so long I'm sure it will end in a crash. But no. And not in a forest with foliage and other GPU consuming features. Even when walking in a cave, getting close to a waterfall, by example.
Is it just me ?

**Comment by tyronx** [comment] 2021-07-08 10:07
Can you provide us with further info as listed here please:
https://wiki.vintagestory.at/index.php?title=Debugging

**Comment by radfast** [comment] 2021-07-08 10:07
@Saricane  were you playing `pre.12` or other pre-releases - did you have this issue in any pre-release version.   Please let us know the latest version you played which did __not__ have this issue ... :)

**Comment by radfast** [comment] 2021-07-08 10:08
@Craluminum2413 and @PilotDoug you thumbs upped, are you saying you have the same issue?   If so same questions to you please ^^^^

**Comment by Saricane** [comment] 2021-07-08 10:16
@Radfast, I played (rather intensively) the 12 pre versions, and rc1 is the only one with those freezes. Everything was fine before.
@Tyron, I'll do my best this evening to give you the informations related in the debugging page.

**Comment by PilotDoug** [comment] 2021-07-08 10:20
I upgraded to 1.15 -rc1 yesterday and all was working smoothly until I used the quern. Shortly after that the program crashed. Since that time the program will crash without any game play about 30 seconds after launch. 
The exception report:
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.0-rc.1 (Unstable)7/8/2021 5:13:18 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityGroundStorage.DetermineStorageProperties(ItemSlot sourceSlot)
   at Vintagestory.GameContent.BlockEntityGroundStorage.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldForResolving)
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(_f47bFFjjZjqsZ07abkCWRRjJjq5 p, ClientMain game)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(_SPt7iF5LhXmcxMRSPZV1A0ZATGh packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _Hhyykp3OIyR3A9gDXvfRYXmIxHM._N2PKmadywKhrSAOGDRbet32cyTB(Single )
   at _GatfFd3kn5xATuUyKYscxn8d0CO._4TEOzZagWNPjzZVqfu2HCwbLFqC(Single )
   at _GatfFd3kn5xATuUyKYscxn8d0CO._x3D81oTSuYvhXUwgP6x9PwySgdc(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _woe4UEAalnRbwPXBTK09ZhdFcWO._5qgAk5LLuTcbcRWXQsq1b3Y8T8H(_arFvNaodTjXO5ObZ7eEgimkezLG , String[] )
   at _ZFpbvq06JtO6suJqmLDa8Hs9YeH._5qgAk5LLuTcbcRWXQsq1b3Y8T8H(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 7/6/2021 4:44:41 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1787358762948678399, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.0.0
P3: 60df0588
P4: KERNELBASE.dll
P5: 10.0.19041.1023
P6: 924f9cdb
P7: c000041d
P8: 0000000000034b89
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5F4F.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER62EA.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER62FB.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER630A.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER632B.tmp.txt
\\?\C:\Users\Gamer\AppData\Local\Temp\WER6406.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_6423145b6cda8c60d9d89ab0422ef3945fce7697_57f52630_370e31ed-a2fb-4473-b622-7e4e55a15dcc

Analysis symbol: 
Rechecking for solution: 0
Report Id: d8f62b02-23c9-4a0a-885d-638767b54de8
Report Status: 268435456
Hashed bucket: 9caaf748cfb7ef0978cdf95337bcd2ff
Cab Guid: 0 }
--------------
{ TimeGenerated = 7/6/2021 4:44:41 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.0.0
P3: 60df0588
P4: KERNELBASE.dll
P5: 10.0.19041.1023
P6: 924f9cdb
P7: c000041d
P8: 0000000000034b89
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5F4F.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER62EA.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER62FB.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER630A.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER632B.tmp.txt
\\?\C:\Users\Gamer\AppData\Local\Temp\WER6406.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_6423145b6cda8c60d9d89ab0422ef3945fce7697_57f52630_cab_370e31ed-a2fb-4473-b622-7e4e55a15dcc

Analysis symbol: 
Rechecking for solution: 0
Report Id: d8f62b02-23c9-4a0a-885d-638767b54de8
Report Status: 4
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 7/6/2021 4:44:41 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1242372221530262643, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.0.0
P3: 60df0588
P4: KERNELBASE.dll
P5: 10.0.19041.1023
P6: 924f9cdb
P7: c0020001
P8: 0000000000034b89
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5731.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5BE5.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5BF6.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5C04.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5C24.tmp.txt
\\?\C:\Users\Gamer\AppData\Local\Temp\WER5D02.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_dbd2f116e072cca4c58497f5d9981ab82ec3df4_57f52630_c1f71b27-b4cb-46a6-b7d2-2199e6dc0f16

Analysis symbol: 
Rechecking for solution: 0
Report Id: e41d35fb-c2a4-4c4a-8b87-7bf98f282ce5
Report Status: 268435456
Hashed bucket: 6e6897f86d0500c4913dcaf3ff1fcc73
Cab Guid: 0 }

**Comment by Saricane** [comment] 2021-07-08 10:22
Not sure we have the same problem. I'm not talking about crash, just lag/freezes. And I can use the quern without problem.

**Comment by Craluminum2413** [comment] 2021-07-08 10:46
@PilotDoug, send this to #1111, not here

**Comment by radfast** [comment] 2021-07-08 11:04
@Saricane  more questions please
1. do you experience the issue in a new Survival world, or only an existing world
2. if only an existing world, is it only in your base or everywhere
3. it only in your base, what is in and around your base, specifically any of the things with recent changes like Pit kilns, ground storage (i.e. clay items on the ground), or pies?    Please try either removing most of those things, or make a new world with just a few of those things, trying to isolate which thing specifically might be causing this
4. are you triggering any worldgen, by the player moving to new areas of the map?

**Comment by Saricane** [comment] 2021-07-08 11:30
@Radfast : it's survival mode, on a pre11 world.
I effectively noticed the worst freezes occured when discovering new chunks. The best example was when exiting a freshly discovered TL, so in newly generated chunks. Big freezes when trying to exit the destination cave, with nothing more than a small waterfall.
I am almost sure to have experienced some around the base, so in already long time discovered chunks. In this base, yes, I have ground storage  : charcoal, fire bricks, some molds, firewood, 3 kilns, no pies, no henboxes (no hens under aurora borealis, ha ha), but I did not make a link between using those storage and the freezes. May be, may be not. I will better focus on this when connecting again.

**Comment by radfast** [comment] 2021-07-08 11:36
OK please update us when you have a chance to try in game.

Please play with the Ctrl-F3 debug screen on, and use Windows+PrtScr to take a screenshot at the moment the game freezes

It will be helpful to have clear confirmation from you whether it is:
A)   Only when discovering new chunks  (including new chunks all around, if you use a new TL for the first time)
B)   Only when looking at the world surface   (you mentioned exiting the destination cave - though note that is also moving, so could have moved you into a new chunk triggering more chunk discovery at the far edge of your view distance)
C)   Only around your base area
D)   More than one of the above ...

Please also test whether turning down your view distance a lot, fixes the issue.   (Test that properly by still moving far across the map to test new chunk discovery.)   If that fixes it, what's the max you can turn it up to without having the issue.

You mentioned aurora borealis, is this issue only seen in the far North?

**Comment by Craluminum2413** [comment] 2021-07-08 15:26
When I change my move speed with F1/F2, it can cause huge freezes

**Comment by Craluminum2413** [comment] 2021-07-09 19:46
Can it be related to RAM consuming? When the game eats about 8 GB and I'm trying, for example, change move speed by using F1 and F2, it cause long lags.

I have i5-7400, GTX1050Ti, 16 GB of RAM. My min fps is always around 25-30 FPS for these settings:
![image](https://user-images.githubusercontent.com/69315569/125126133-50b32000-e103-11eb-8fed-6f6fb2fd6126.png)
![image](https://user-images.githubusercontent.com/69315569/125128927-632f5880-e107-11eb-913d-9462b14fbea6.png)

**Comment by radfast** [comment] 2021-07-12 20:36
More info please, on steps to reproduce this.  Game mode, single player?  Screen shot of graphics settings.  Was new worldgen generating at the time?  Screen shot of Ctrl+F3 debug screen.

**Comment by Saricane** [comment] 2021-07-13 04:49
I waited before posting here again, because I was waiting to have some new freezes. But in fact, I upgraded to rc2 as soon as it was released, and since I run it, no more freeze, no more lag, eveything is ok. I even tried to go far away to trigger worldgen, and even in running mode to stress the worldgen, but no way to have a single freeze. So I don't have any log or screenshot to bring here. And I dit not start a new world, that's always the same world, created with pre11.
Is it possible that the rc2 could have fixed something introduced in rc1 ?
On the other way, it does not seems that other players noticed such freezes, as there are no other bug report about that.
I guess you probably can close this issue, as I am the only one to report that and I can't even reproduce this no more.

**Comment by copygirl** [comment] 2021-07-13 05:46
That's good to hear. I will close this as resolved then.

**Closed by copygirl** 2021-07-13 05:46 UTC
Labels: priority: medium, status: resolved, target: performance

**Comment by radfast** [comment] 2021-07-13 10:19
> When the game eats about 8 GB of RAM (I have 16 GB in total) and I'm trying, for example, change move speed (not moving) by using F1 and F2, it can cause long lag spikes.
> 
> ![image](https://user-images.githubusercontent.com/69315569/125128927-632f5880-e107-11eb-913d-9462b14fbea6.png)

Please start a new issue with this, and provide further details on how to reproduce.  CPU usage (20%) and GPU usage (70%) look sensible if the game was running.  I can't imagine any reason why pressing the F1 or F2 keys would cause a lag spike...

**Comment by tyronx** [comment] 2021-07-13 10:41
also hitting Alt+F8 while at this high ram use would tell us if its actually used ram or simply not defragmented ram

**Comment by tyronx** [comment] 2021-07-13 10:41
if it is actually used ram, a memory dump would be helpful
