### ISSUE TITLE
Grass does not spread into medium soil

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#144] opened 2018-07-04 16:58 UTC
I am quite sure I noticed it in 1.5 already, still exists in 1.6 pre2. Public server.

As a testcase I created 2 elevated platforms, one made from low fertility barren soil, another - from medium.
Placed a crafted grass block into the middle, low - to low, medium - to medium.
Placed some blocks of all 3 types over the soil platform.
Result: grass spreads fine from low and medium fertilities, and into low and high fertilities.
Does not spread at all into medium fertility soil.

![2018-07-04_19-45-53](https://user-images.githubusercontent.com/25122345/42288602-164eb8f0-7fc4-11e8-843c-bf69b816edad.png)

**Comment by sirStroam** [comment] 2018-07-06 16:54
So this is back again.
https://github.com/anegostudios/VintageStory-Issues/issues/86

**Comment by Heptagon-ru** [comment] 2018-07-06 17:07
Oh, yeah, interesting, now it is reproducible on the test server.

**Comment by jchappelle** [comment] 2018-07-11 01:32
@Heptagon-ru I'm having trouble reproducing this. You may need to share your world with me. 

Here's something to try. There is a command to force a block to tick. Try standing on a soil block that you feel like should be growing and run the following command:
`/tickblock ~0 ~-1 ~0`

It will output either "Accepted Tick" or "Declined Tick". If accepted it will grow by one stage. Declined means it will not grow due to the growth rules which have to do with climate and whether a grass block is nearby. Grass can only grow 1 level up or down to adjacent blocks. 

But I think I'm going to need a backup of your world either way so it's up to you if you want to play with that command.

**Comment by Heptagon-ru** [comment] 2018-07-11 11:16
Since this is the public server I don't have access to the /tickblock command. You can visit the testcase build using the coords on the screenshot.

I created a new singleplayer world in 1.6 pre2 and tried the same - I get the same results, grass not growing into medium soil, /tickblock command says "Declined Tick". If replace medium soil with low - "Accepted Tick".
Here is the download link for the zipped singleplayer world: https://yadi.sk/d/Ss5TH_5b3Z4JXa

**Comment by Heptagon-ru** [comment] 2018-07-11 15:09
Just noticed a thing: I removed a wood plank block which was standing on a medium soil, and soil was barren under it. But after few seconds it became sparce grass. So the bug is not that stable. That block was in another chunk.
Anyway, I have 3 occurences of the bug: my testcase on public server, a patch of medium soil over the tunnel at WolfPass on the public server, and the singleplayer test world.
![2018-07-11_18-05-30](https://user-images.githubusercontent.com/25122345/42581515-935bb570-8535-11e8-966b-dd535238571e.png)

**Comment by jchappelle** [comment] 2018-07-11 16:51
Hmm. My first thought is that the climate is not appropriate. Thanks for all the info. I'll take a look tonight at the zipped world.

**Comment by jchappelle** [comment] 2018-07-12 02:07
@Heptagon-ru I've solved the mystery. Your zipped world was very helpful. Thank you for providing it.

It is a climate issue. Specifically the fertility of the climate is not high enough to meet the minimum fertility for medium soil to grow. If you want specifics, the climate is around 0.4 and the minimum fertility for medium soil to grow grass is 0.5. 

The details of this is in the `/assets/worldgen/terrain/standard/blocklayerconfig.json` file. In there you will see a section called `L1 Soil with grass`. If you change the minimum fertility for medium soil to something lower than 0.4 then it will grow.

This works as intended.

**Comment by jchappelle** [comment] 2018-07-12 02:21
Also, you can get the climate at your current position by running the following command:

`/wgen pos climate`

**Comment by sirStroam** [comment] 2018-07-12 03:14
Why does grass have an easier time growing on low fertility soil than medium fertility soil? Shouldn't it be opposite.

**Comment by Heptagon-ru** [comment] 2018-07-12 09:19
1. Thank you very much, @jchappelle ! I missed that detail when reading changelogs.
2. Since I don't have rights to call this command on a server, at least on the public one, I guess an ordinary player should just see which soil is native for the region and use it. Hopefully the worldgen will never place medium soil in incorrect climate.
3. Imho this needs to be mentioned in wiki asap unless already done. I will try to do it, even a raw page will do for start, just not to lose this info.
4.  Like @sirStroam, I also don't understand why soil with better fertility has problems growing grass when environment is harsher, but poorer soil does not. Following this logic - high fertility soil should allow to grow grass in very rare occasion, but it allows to grow grass in my bad testcase on the public server.
But for now this seems the matter of another ticket if someone wants to open it :)

I propose not to close this ticket until this basic info abouth grass growth exists in Wiki, because this is very important info and might raise the same questions in the future. I will try to add the info today.

Maybe moderators could change its type from "bug" to "question" and set status to "resolved" or something like that. Maybe some specific status would be nice saying that the issue is resolved but needs an important post-action.

**Comment by jchappelle** [comment] 2018-07-12 13:20
It works that way because it is following the rules of world gen. We didn't want grass to start growing into areas of the world after the game started if the world gen wouldn't have placed it there to begin with.

**Comment by jchappelle** [comment] 2018-07-12 13:21
Not sure why this closed automatically. I didn't try to do that. I'll reopen

**Comment by tyronx** [comment] 2018-07-12 17:31
@jchappelle i think it would be ok if the soil block would, for high and medium fertility soil, also test if a low fertility soil block can grow grass at that given location. This should not cause grass growing in areas it is not supposed to.

**Comment by Heptagon-ru** [comment] 2018-07-12 20:00
I have updated the wiki with this info. Poorly, but can't make a better version. I am not closing ticket because you guys are discussing the important matter and I hope it will bring an improvement to the game :) Please close when you find appropriate :)

**Comment by jchappelle** [comment] 2018-07-13 13:16
I'll make the change tyron described.

**Comment by jchappelle** [comment] 2018-07-14 00:19
Just committed the fix for this. Should go out in the next release.

**Comment by jchappelle** [comment] 2018-07-14 00:24
Fixed in whatever version comes after 1.6.0-pre.2

**Closed by jchappelle** 2018-07-14 00:24 UTC
Labels: status: new, status: resolved, target: survival, type: bug

**Comment by Heptagon-ru** [comment] 2018-07-20 15:49
Yeah, in pre3 grass seem to spread fine, thanks!

**Comment by jchappelle** [comment] 2018-07-20 18:33
Your welcome! Thank you for testing.
