### ISSUE TITLE
[1.20-rc.2] (Known issue) Resonance Archives generated with unknown blocks.

### ISSUE THREAD

**Issue by CookieBoy21** [anegostudios/VintageStory-Issues#4685] opened 2024-12-13 23:43 UTC
### Game Version

1.20-rc.2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Resonance archives generated unknown blocks on 1.20-rc.2.

### How to reproduce

Go to resonance archives in 1.20-rc.2.

### Screenshots

<img width="1280" alt="Vintagestory Screenshot 2024 12 14 - 00 41 23 19" src="https://github.com/user-attachments/assets/08be700d-a99c-42d4-832e-7594d8867dff" />
<img width="1280" alt="Vintagestory Screenshot 2024 12 14 - 00 39 43 10" src="https://github.com/user-attachments/assets/59a72317-0ccf-42d6-a666-2cb68d6605b3" />
<img width="1280" alt="Vintagestory Screenshot 2024 12 14 - 00 38 53 68" src="https://github.com/user-attachments/assets/45de7f31-ccba-422b-9fdc-5b501e88ce58" />

### Logs

```Log```

**Comment by barrowisp** [comment] 2024-12-14 00:04
same here.  and the Immobilized 
![2024-12-13_16-01-50](https://github.com/user-attachments/assets/cb5760dd-7771-4ea2-965a-30969ec6491a)
Eidolon is nowhere to be seen.

**Comment by barrowisp** [comment] 2024-12-14 00:38
in the lazaret, too
![2024-12-13_16-20-33](https://github.com/user-attachments/assets/269a64cb-8227-4211-8357-db6f711d625b)
![2024-12-13_16-37-31](https://github.com/user-attachments/assets/136c6d63-aa1a-4925-a4a2-2f4c6c54a676)

**Comment by radfast** [comment] 2024-12-14 00:50
Duplicate of #4684.  Very sorry about this, see the updated **Note** at the start of 1.20.0-rc.2 patch notes.  We will get a fixed 1.20.0-rc.3 out as soon as possible, right now it's the middle of the night here in Europe...

Once -rc.3 is available, you can fix any broken chunks using the `/wgen regen 1` command.

**Comment by CookieBoy21** [comment] 2024-12-14 13:04
Look fixed in 1.20-rc.3.

**Closed** 2024-12-14 13:09 UTC
Labels: status: duplicate, status: new, priority: high, version: 1.20
