### ISSUE TITLE
Texture to index mapping now depends on file name

### ISSUE THREAD

**Issue by sekelsta** [anegostudios/VintageStory-Issues#4733] opened 2024-12-18 17:48 UTC
### Game Version

1.20.0-rc.5

### Platform

Linux

### Modded

Yes - see "How to reproduce"

### SP/MP

None

### Description
Previously on 1.19.8, an entity with textureIndex in WatchedAttributes set to, say, 3, would use the texture at position 3 (0-indexed) in the list of textures and alternates in the entity file. Now in 1.20.0-rc.5, depending on the filenames of the textures that entity may be using a different texture without any change to the entity file. The order appears to be roughly (?) alphabetical by filename.

This is important to me because I have a mod assigning specific textures to chickens based on their genetics, and doing so is much easier if I can choose which texture goes which which index without having to rename the files for it.

### How to reproduce
Install a mod that does the following:
1. Harmony patch a client-side entity behavior such as harvestable so GetInfoText shows the entity's textureIndex
2. Replace an entity's textures with new ones listed in non-alphabetical order
3. Observe that the entity's texture index and displayed texture does not match the order the textures are given in the entity file
4. Bonus: Load mod on 1.19.8 and see that the displayed texture _does_ match the order given in the entity file.
An example mod that does these things is attached (as a zip of source files, not a mod ready to be installed):
[debugmod_source.zip](https://github.com/user-attachments/files/18187248/debugmod_source.zip)

### Screenshots
Attached mod on 1.19.8:
![Screenshot at 2024-12-18 12-14-34](https://github.com/user-attachments/assets/0596c174-5d0f-44b3-9170-1b4fc6c12eff)
Same save and mod on 1.20.0-rc.5:
![Screenshot at 2024-12-18 12-16-56](https://github.com/user-attachments/assets/17549a22-9e49-40eb-8c79-7af3632a39cb)

### Logs

```Log```

**Comment by sekelsta** [comment] 2024-12-18 17:48
I don't know how that happened I did not hit submit, let me edit

**Comment by radfast** [comment] 2024-12-19 01:34
We can't guarantee that Harmony patches are going to work the same way between two different major (or even minor) version numbers. We need to be able to adapt the game's internal code that's not exposed via the API.

Having said that, I have not yet identified the specific change in code which caused this problem.

It _might_ be easier (no guarantee) for us simply to expose the field/method you need via the API.   What, in code, do you need to access?

**Comment by tyronx** [comment] 2024-12-19 08:45
This bug is not related to harmony or the code api. I'll take a look

**Comment by tyronx** [comment] 2024-12-19 08:50
this is caused by commit 445ae219 made by dilli

**Comment by tyronx** [comment] 2024-12-19 08:59
thanks for the report, this will be fixed for rc.6

**Closed by tyronx** 2024-12-19 08:59 UTC
Labels: target: modding, status: new, department: code, version: 1.20
