### ISSUE TITLE
Game Crashes on Mac

### ISSUE THREAD

**Issue by Ayizan** [anegostudios/VintageStory-Issues#1568] opened 2022-01-12 01:07 UTC
**Game Version:** 1.16.0
**Platform:** Mac OS: Mojave 10.14.6
**Modded:** No     

### Description
The game crashes as soon as I try to open it. 1.15 works fine on my computer but anything after that crashes. 

### How to reproduce
1. Open game
2. It crashes
3. gives me the error attached in the screenshots below

### Screenshots
Screenshots of the error I get
[https://drive.google.com/file/d/1ldLLwEzFPNjaoAQ_jlp7JE0Tysprr_sB/view?usp=sharing](url)
[https://drive.google.com/file/d/1RSPrI-By3D4Cr_bZLmpKnZD4IwQqG3g9/view?usp=sharing](url)
### Logs
```
Version: v1.16.0 (Stable)1/11/2022 4:46:23 PM: Critical error occurred
System.DllNotFoundException: Lib64/libnanosvg.dylib assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) NanoSvg.SvgNativeMethods.nsvgCreateRasterizer()
  at Vintagestory.Client.NoObf.SvgLoader..ctor (Vintagestory.API.Client.ICoreClientAPI _capi) [0x0000d] in <d16f4e016eef4b52a1d7221d4e54ddfc>:0 
  at _FWCmTDksYHaqdWlerzat8XtkY7H..ctor (_vFhcDU5n6Z0hUte90jdaxlrDjR5 , Vintagestory.API.Client.ICoreClientAPI ) [0x00030] in <d16f4e016eef4b52a1d7221d4e54ddfc>:0 
  at _j3zstUfG5KXULmjLezNy4TVTGqd..ctor (_vFhcDU5n6Z0hUte90jdaxlrDjR5 ) [0x00025] in <d16f4e016eef4b52a1d7221d4e54ddfc>:0 
  at _vFhcDU5n6Z0hUte90jdaxlrDjR5._pYad7oBcQ5qtzQkYGDu4NFHQxhK (_5x3PJgrln4IBXPDNSNN0fecxKFb , System.String[] ) [0x00000] in <d16f4e016eef4b52a1d7221d4e54ddfc>:0 
  at _FKpOpQGqqf3cJWdQyWh1ysxsDBb._pYad7oBcQ5qtzQkYGDu4NFHQxhK (_5x3PJgrln4IBXPDNSNN0fecxKFb , System.String[] ) [0x003bf] in <bed49109127b412da64956a1d050210c>:0 
  at _FKpOpQGqqf3cJWdQyWh1ysxsDBb+_EbS2AEEJP4M13PeMC88IfKBzIZF._RNcFgtqGZOgUpj21Qsn4t2YRX9f () [0x00000] in <bed49109127b412da64956a1d050210c>:0 
  at _sejP0Tcz8wTg70ptIdRr3CwQmrE._pYad7oBcQ5qtzQkYGDu4NFHQxhK (System.Threading.ThreadStart ) [0x00007] in <d16f4e016eef4b52a1d7221d4e54ddfc>:0 
```

**Comment by copygirl** [comment] 2022-01-12 07:39
Duplicate of #1561. This one is a bit of tricky one to solve. For some Mac users the game loads fine. Others appear to have this issue.

**Closed by copygirl** 2022-01-12 07:39 UTC
Labels: status: duplicate
