### ISSUE TITLE
Game crashed walking around. Maybe an issue with a fruit tree??

### ISSUE THREAD

**Issue by duke-arioch** [anegostudios/VintageStory-Issues#2357] opened 2023-01-24 01:03 UTC
received the following error. Just walking around.

Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.17.10 (Stable)
1/23/2023 8:05:46 PM: Critical error occurred
Loaded Mods: game@1.17.10, creative@1.17.10, survival@1.17.10
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityFruitTreePart.GenFoliageMesh(Boolean withSticks, MeshData& foliageMesh, MeshData& sticksMesh) in VSSurvivalMod\Systems\FruitTree\BEFruitTreePart.cs:line 212
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.GenMeshes() in VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:line 250
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.GenMesh() in VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:line 236
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldForResolving) in VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:line 386
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(Packet_BlockEntity p, ClientMain game) in VintagestoryLib\Client\Model\ClientChunk.cs:line 422
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 817
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 1138
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 123
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 678
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 622
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 124
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 1/23/2023 3:13:50 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2073652534770059827, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.10.0
P3: 63bbdc3a
P4: KERNELBASE.dll
P5: 10.0.22621.963
P6: 766ca8ae
P7: c0020001
P8: 00000000000906bc
P9: 
P10: 

Attached files:
\\?\C:\Users\matth\AppData\Local\Temp\WER.3b46c5c3-515d-4116-b637-f8b976568438.tmp.WERDataCollectionStatus.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.5d43a1b4-f6f4-4192-aeba-62ad80d3359c.tmp.WERInternalMetadata.xml
WPR_initiated_DiagTrackMiniLogger_OneTrace_User_Logger_20230123_1_EC_0_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.256ab06e-52b0-4f77-bf35-5ec9c8e1886f.tmp.etl
WPR_initiated_DiagTrackMiniLogger_WPR System Collector_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.1af25c46-cacb-48d4-b234-033e854ed343.tmp.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.269ffd47-bb06-420a-a573-60ea75ebb5e4.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.41b2d49b-2882-4584-87c0-1d077d6f34dc.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.c8e31ac1-8c06-4ea4-a1dd-0107144796b2.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_8a89c2eeca3e1f4411ce6fb81fdd3aa369ac7eb2_90e27403_132b24de-3651-40fc-9c44-221790a3c502

Analysis symbol: 
Rechecking for solution: 0
Report Id: 3c06e141-017e-40fc-808e-d255bdd99226
Report Status: 268566528
Hashed bucket: b2c023a39d0ff899ecc717fe628eca33
Cab Guid: 0 }
--------------
{ TimeGenerated = 1/23/2023 3:13:45 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.17.10.0, time stamp: 0x63bbdc3a
Faulting module name: KERNELBASE.dll, version: 10.0.22621.963, time stamp: 0x766ca8ae
Exception code: 0xc0020001
Fault offset: 0x00000000000906bc
Faulting process id: 0x0x4e54
Faulting application start time: 0x0x1d92f59c7fcd074
Faulting application path: C:\Users\matth\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 3c06e141-017e-40fc-808e-d255bdd99226
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 1/23/2023 3:13:44 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FF848FB06BC
Stack:
   at System.Environment._Exit(Int32)
   at System.Environment._Exit(Int32)
   at System.Environment.Exit(Int32)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.NativeWindow.OnClosedInternal(System.Object, System.EventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.Platform.Windows.WinGLNative.HandleDestroy(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   at OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.DestroyWindow()
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(OpenTK.Platform.Windows.MSG ByRef)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(OpenTK.Platform.Windows.MSG ByRef)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double, Double)
   at Vintagestory.Client.ClientProgram.Start(Vintagestory.Client.ClientProgramArgs, System.String[])
   at Vintagestory.ClientNative.CrashReporter.Start(System.Threading.ThreadStart)
   at Vintagestory.Client.ClientProgram.Main(System.String[])
 }

**Comment by Craluminum2413** [comment] 2023-01-24 08:28
Duplicate of #2102

**Closed by Craluminum2413** 2023-01-24 08:28 UTC
