### ISSUE TITLE
Sudden crash with no explanation, log follows

### ISSUE THREAD

**Issue by Koollan** [anegostudios/VintageStory-Issues#1151] opened 2021-07-13 07:09 UTC
**Game Version:** 1.14
**Platform:** Windows  
**Modded:** No

### Description
Explain the issue you're running into.

### How to reproduce
N/A

### Expected behavior
Not to crash?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.10 (Stable)7/13/2021 12:07:52 AM: Critical error occurred
System.Exception: FBO Render2DLoadedTexture: This particular FBO configuration is not supported by the implementation.
   at Vintagestory.Client.NoObf.ClientPlatformWindows.CheckFboStatus(FramebufferTarget target, String fbtype)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.CreateFramebuffer(FramebufferAttrs fbAttrs)
   at Vintagestory.Client.NoObf.ClientMain.RenderTextureIntoTexture(LoadedTexture fromTexture, Single sourceX, Single sourceY, Single sourceWidth, Single sourceHeight, LoadedTexture intoTexture, Single targetX, Single targetY, Single alphaTest)
   at Vintagestory.GameContent.MultiChunkMapComponent.setChunk(Int32 dx, Int32 dz, Int32[] pixels)
   at Vintagestory.GameContent.ChunkMapLayer.<>c__DisplayClass38_0.<loadFromChunkPixels>b__0()
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _vKnDSS3ZW5fZhqcIJSzL9xbAUttA._mhcyOBzdAWALla9FVcjc15WACGi(Single )
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._3HP2xkrryy8Ktr1q1yqHHv9s1kb(Single )
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._JbXJA0SA6LQOS6diuqtXAjMb8Fo(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _ISiSTzGmXXpAqo3PzdxdVD1bClZ._ofvn0Tr1zNGCbNV3SxvKs2MXNP(_C7CLMRbe3BejVtaARYCgl7Bg1vl , String[] )
   at _0Y0SN1uu1V65pRLxvnN2xsIjXAg._ofvn0Tr1zNGCbNV3SxvKs2MXNP(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 6/15/2021 3:17:48 PM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.14.10.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 34e8

Start Time: 01d762338f6f7c97

Termination Time: 4

Application Path: C:\Users\welch\AppData\Roaming\Vintagestory\Vintagestory.exe

Report Id: ccc4a2ed-91fc-4df6-8280-746f57811700

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
--------------
{ TimeGenerated = 6/15/2021 3:17:47 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 6079b344
P4: a137
P5: 134217728
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3F77.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3F88.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3F97.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3FC7.tmp.txt
\\?\C:\Users\welch\AppData\Local\Temp\WER6011.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_Vintagestory.exe_1eb14fc8d3040b583e2ec964fbfecf6548db929_5674d60d_8ba36c0e-7d6c-4115-9c53-1bae504eae31

Analysis symbol: 
Rechecking for solution: 0
Report Id: ccc4a2ed-91fc-4df6-8280-746f57811700
Report Status: 97
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 6/14/2021 9:43:25 PM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.14.10.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 1438

Start Time: 01d7619fe1bf51e0

Termination Time: 4

Application Path: C:\Users\welch\AppData\Roaming\Vintagestory\Vintagestory.exe

Report Id: 09980d7e-a74c-4c64-b3b9-af7a113e4596

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
```

**Comment by Craluminum2413** [comment] 2021-07-13 07:17
#749 ?

**Comment by tyronx** [comment] 2021-07-13 08:17
Indeed a duplicate of that.

**Closed by tyronx** 2021-07-13 08:17 UTC
Labels: status: new

**Comment by copygirl** [comment] 2021-07-13 08:24
Has the game previously worked? Does restarting your computer resolve the issue? Currently we believe the issue is related to a faulty graphics card or driver.

**Comment by Koollan** [comment] 2021-07-13 19:53
> Has the game previously worked? Does restarting your computer resolve the issue? Currently we believe the issue is related to a faulty graphics card or driver.

Usually, I get graphical bugs and crashes similar to this and the last report I made.
Funnily enough, it must be the game. Since the last time, I replaced my 1050 Ti for a different 1050 Ti, with my drivers all being up to date. I think that the 1050 Ti doesn't interface with the game very well, is my theory of the issue.

**Comment by tyronx** [comment] 2021-07-14 08:38
hm. I have a 1050 Ti and never seen any issues like this when playing or testing Vintage Story.

**Comment by Koollan** [comment] 2021-07-16 00:20
It's difficult to say. It seems to happen out of the blue. One thing that happens at times is that multiple chunks fail to load / render, causing the chunks to be invisible (it still loads on the map and I can still move around on the invisible ground).

This has happened on both of my 1050 Ti cards. If it's pertinent, they are both Zotac.
