### ISSUE TITLE
persistent RenderHeldItem crash after middle clicking 

### ISSUE THREAD

**Issue by diana-crd** [anegostudios/VintageStory-Issues#4330] opened 2024-10-19 16:52 UTC
### Game Version

1.20.0-pre.5 and -pre.6

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

while in creative mode, middle-clicking on large wooden gears while holding axles in your current active slot corrupts the save (crashes both immediately and upon trying to load the save again). The first time it happened I had been messing around with different windmill setups and middle-clicking stuff for about 30 minutes so there's a decent chance this issue only happens with those specific items, but I haven't tested all the permutations yet. If it's of any help I should also mention it first happened to me on version pre.5 but persisted after updating to pre.6.

### How to reproduce

1. enter creative mode
2. place a large wooden gear in the world
3. middle click on large wooden gear while holding an axle in your active slot (without having large wooden gears in your hotbar).
4. game will crash
5. attempting to reload that save will cause the game to crash again with the same error log.

### Logs

```Log```
Running on 64 bit Windows 10.0.19045.0 with 8056 MB RAM
Game Version: v1.20.0-pre.6 (Unstable)
19/10/2024 18:41:14: Critical error occurred
Loaded Mods: game@1.20.0-pre.6, creative@1.20.0-pre.6, survival@1.20.0-pre.6
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityShapeRenderer.RenderItem(Single dt, Boolean isShadowPass, ItemStack stack, AttachmentPointAndPose apap, ItemRenderInfo renderInfo) in VSEssentials\EntityRenderer\EntityShapeRenderer.cs:line 477
   at Vintagestory.GameContent.EntityShapeRenderer.RenderHeldItem(Single dt, Boolean isShadowPass, Boolean right) in VSEssentials\EntityRenderer\EntityShapeRenderer.cs:line 473
   at Vintagestory.GameContent.EntityPlayerShapeRenderer.DoRender3DOpaque(Single dt, Boolean isShadowPass) in VSEssentials\EntityRenderer\EntityPlayerShapeRenderer.cs:line 230
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderOpaque3D(Single deltaTime) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 79
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 819
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 825
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 741
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 207
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

{ TimeGenerated = 19/10/2024 18:39:37, Site = , Source = Application Error, Message = Nome dell'applicazione che ha generato l'errore: Vintagestory.exe, versione: 1.20.0.0, timestamp: 0x66470000
Nome del modulo che ha generato l'errore: openal32.dll, versione: 1.23.0.0, timestamp: 0x63dd31ad
Codice eccezione: 0x40000015
Offset errore 0x00000000000df046
ID processo che ha generato l'errore: 0x2b38
Ora di avvio dell'applicazione che ha generato l'errore: 0x01db2245569423ff
Percorso dell'applicazione che ha generato l'errore: C:\Users\Diana\AppData\Roaming\VintagestoryPre\Vintagestory.exe
Percorso del modulo che ha generato l'errore: C:\Users\Diana\AppData\Roaming\VintagestoryPre\Lib\openal32.dll
ID segnalazione: 2591c302-60b4-400f-baea-9b31896f9d1b
Nome completo pacchetto che ha generato l'errore: 
ID applicazione relativo al pacchetto che ha generato l'errore:  }

**Comment by Craluminum2413** [comment] 2024-10-19 17:33
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4314

**Closed by Craluminum2413** 2024-10-19 17:33 UTC
Labels: status: new

**Comment by radfast** [comment] 2024-12-20 02:28
For info the issue was fixed in version 1.20.0-pre.7
