### ISSUE TITLE
Cave-in at mantle teleports rock to ground level.

### ISSUE THREAD

**Issue by curstwist** [anegostudios/VintageStory-Issues#4482] opened 2024-11-10 02:08 UTC
### Game Version

v.1.20 pre.11

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

I had a cave in at when I mined down to the mantle (standard, cave-in enabled).  It began a huge cascade but with no where for the rock to go.  Upon returning to the surface, I found the cell covered in the the displaced rock.  I can provide a save if necessary. 

### How to reproduce

1. Mine to mantle with cave-ins enabled.
2. I had a ladder at the block just above the mantle. 
3. trigger cave-in
4. return to surface

### Screenshots

![2024-11-09_21-03-23](https://github.com/user-attachments/assets/33c00950-1ee4-4b2b-915c-58fd3752efcd)

andesite was the final layer

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2024-11-10 10:31
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/3567

**Closed by Craluminum2413** 2024-11-10 10:31 UTC
Labels: status: new
