### ISSUE TITLE
Common crash in singleplayer (RC-1, RC-2, RC-3)

### ISSUE THREAD

**Issue by ne4tOr** [anegostudios/VintageStory-Issues#2080] opened 2022-07-31 08:42 UTC
**Game Version:** 1.17.0 RC-3  
**Platform:** Windows
**Modded:** No   
**SP/MP:** Singleplayer  

### Description

Starting from the RC-1 versions of the game, there are crashes every 5 minutes of the game. This is repeated in the RC-3 update.
I'm using a clean client without modifications.

**Important, everything works correctly in the PRE-5 version**

### How to reproduce
1. Create a new world, or load an existing one. Error occurs during gameplay
3. It crashes

### Logs
```
Running on 64 bit Windows with 8 GB RAM 
Game Version: v1.17.0-rc.3 (Unstable)
Loaded Mods: game@1.17.0-rc.3, creative@1.17.0-rc.3, survival@1.17.0-rc.3
31.07.2022 11:40:03: Critical error occurred
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в Vintagestory.API.Client.HotkeyComponent.GenHotkeyTexture() в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\HotkeyComponent.cs:строка 49
   в Vintagestory.API.Client.GuiElementRichtext.ComposeFor(ElementBounds bounds, Context ctx, ImageSurface surface) в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementRichtext.cs:строка 418
   в Vintagestory.API.Client.GuiElementRichtext.Compose(Boolean genTextureLater) в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementRichtext.cs:строка 118
   в Vintagestory.API.Client.GuiElementItemstackInfo.<>c__DisplayClass20_1.<AsyncRecompose>b__1() в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementItemstackInfo.cs:строка 178
   в Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:строка 1138
   в Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:строка 123
   в Vintagestory.Client.ScreenManager.Render(Single dt) в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:строка 664
   в Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:строка 608
   в Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\GameWindow.cs:строка 125
   в System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   в OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 476
   в OpenTK.GameWindow.DispatchRenderFrame() в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 452
   в OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 375
   в Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   в Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:строка 87

**Comment by Craluminum2413** [comment] 2022-07-31 08:48
Duplicate of #2055

**Closed by Craluminum2413** 2022-07-31 08:48 UTC
Labels: status: new
