### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by derwilms** [anegostudios/VintageStory-Issues#430] opened 2020-03-05 18:01 UTC
**Game Version:** 1.12.5
**Platform:** Windows 10
**Modded:** No 

### Description
Crash at Start

### How to reproduce
Game crashed by starting up

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Running on 64 bit Windows with 12 GB RAM 
Version: v1.12.5 (Stable)05.03.2020 18:45:54: Critical error occurred
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.LoadTexture(IBitmap bmp, Boolean linearMag, Int32 clampMode, Boolean generateMipmaps)
   bei _mKeEWUbBZsjLS6VlGWgOoYQFk2K._KNs6g2GMtsTu5gnL4MXdRgZVlLh()
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._HdDsdRJDH8nMF88r278C4eqdINGA()
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._gjiBClIE7Yspuz65gCqPGSAnUYeb()
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._NbPATb9BXlxRc4ZhH2GgyFCUInp(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _hCuHXesCXlp0LGSdrsPFpw4up5n._mOm8EuKIvHpaJoztxNWRpAoOpbM(_55ISULxdcpPfF8D2JP831aWhOBe , String[] )
   bei _iCfIbY24GyBXP5lAwqsSlD9COxC._mOm8EuKIvHpaJoztxNWRpAoOpbM(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 02.03.2020 16:59:24, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund eines internen Fehlers in der .NET-Laufzeit beendet. bei IP 00007FF951DE57DE (00007FF951DE0000) mit Exitcode 80131506.
 }
{ TimeGenerated = 02.03.2020 14:26:02, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund eines internen Fehlers in der .NET-Laufzeit beendet. bei IP 00007FF951E21FB3 (00007FF951DE0000) mit Exitcode 80131506.
 }
{ TimeGenerated = 24.02.2020 17:48:43, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund eines internen Fehlers in der .NET-Laufzeit beendet. bei IP 00007FF951E2B60C (00007FF951DE0000) mit Exitcode 80131506.
 }

**Comment by copygirl** [comment] 2020-03-05 19:06
Duplicate of #407. Update the game to 1.12.6 to fix.

**Closed by copygirl** 2020-03-05 19:06 UTC
Labels: status: duplicate
