### ISSUE TITLE
doppelganger

### ISSUE THREAD

**Issue by EyelinerGame** [anegostudios/VintageStory-Issues#3570] opened 2024-02-09 01:34 UTC
### Platform

Windows

### Modded

None

### SP/MP

Multiplayer

### Description

I am on Win 10, Multiplayer partner is on Arch Linux. I went back to base, and their char was standing by the reed chest as if using it. But they weren't. They were off over 100 chunks away exploring. Stabbing the doppelganger did not effect them. 
The only way they disappeared was by me disconnecting and reloading. 

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2024-02-09 18:42
Duplicate of #1704

**Comment by radfast** [comment] 2024-03-11 16:53
@Craluminum2413 although doppelganger reports are duplicates, the code has changed in many ways since a similar issue was first reported in #1704.  And specifically, I attempted to fix this issue in game version 1.19.4 - therefore I am very interested to see any reports of doppelganger issues still in game version 1.19.4+   (there may not be any now, if I managed to find the fix...)

**Closed by radfast** 2024-03-11 16:53 UTC
Labels: status: duplicate
