### ISSUE TITLE
Can't pick up a placed cake

### ISSUE THREAD

**Issue by Terrorpixel1991** [anegostudios/VintageStory-Issues#2125] opened 2022-08-20 05:37 UTC
**Game Version:** 1.16.5 Stable  
**Platform:** Windows
**Modded:** No  
**SP/MP:** Singleplayer 

### Description
If i've place a cooked cake i cant pick it up again. I have to cut it into peaces. But the Mouse over says I can pick it up with empty hand right click. 

### How to reproduce
1. Place a cake
2. Try to pick it up
3. Didn't work

### Screenshots
![2022-08-20_07-35-43](https://user-images.githubusercontent.com/7849136/185730692-6d4b8212-24ee-46dd-b92d-05870f58c707.png)

**Comment by Barhandar** [comment] 2022-08-20 09:44
Duplicate of #2090

**Closed** 2022-08-20 10:25 UTC
Labels: status: duplicate
