### ISSUE TITLE
Crash on LAN game exit (with one other person)

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#2504] opened 2023-03-23 01:01 UTC
### Game Version

1.18.0pre6

### Platform

Windows

### Modded

Modded

### SP/MP

None

### Description

I have StepUp and VSCCI installed for mods. That's it besides the vanilla stuff.
When exiting the game after a LAN game it crashes with this result: 

[Hastebin link](https://hastebin.com/share/tecajuyube.yaml)

**Comment by Craluminum2413** [comment] 2023-03-23 01:39
Duplicate of #2465

**Closed by Craluminum2413** 2023-03-23 01:39 UTC
Labels: status: new
