### ISSUE TITLE
Editing labeled chests crashes the game.

### ISSUE THREAD

**Issue by ModarTheGreat** [anegostudios/VintageStory-Issues#3953] opened 2024-07-02 17:55 UTC
### Game Version

v1.19.7

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### How to reproduce

1. Place a labeled chest.
2. Write "Metal materials" on it.
3. Move your "text cursor" behind lowercase "m" in "materials".
3. Press delete key (not backspace) to remove lowercase "m", then (try to) replace it with its uppercase counterpart.
4. The game will immediately crash.

Important note: The game won't crash after deleting "m" with a backspace key. No clue as to why that happens.

### Screenshots

https://github.com/anegostudios/VintageStory-Issues/assets/171681294/fe1a97e9-8500-4c7d-9905-125e0354fbf5

### Logs

Running on 64 bit Windows 10.0.19045.0 with 8060 MB RAM
Game Version: v1.19.7 (Stable)
02.07.2024 19:17:21: Critical error occurred
Loaded Mods: game@1.19.7, creative@1.19.7, survival@1.19.7
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at Vintagestory.API.Client.GuiElementEditableTextBase.OnKeyPress(ICoreClientAPI api, KeyEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 573
   at Vintagestory.API.Client.GuiComposer.OnKeyPress(KeyEvent args) in VintagestoryApi\Client\UI\GuiComposer.cs:line 639
   at Vintagestory.API.Client.GuiDialog.OnKeyPress(KeyEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 464
   at Vintagestory.Client.NoObf.GuiManager.OnKeyPress(KeyEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 379
   at Vintagestory.Client.NoObf.ClientMain.OnKeyPress(KeyEvent eventArgs) in VintagestoryLib\Client\ClientMain.cs:line 1819
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyPress(TextInputEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 218
   at OpenTK.Windowing.Desktop.NativeWindow.CharCallback(Window* window, UInt32 codepoint)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Craluminum2413** [comment] 2024-07-02 19:20
Duplicate of #3910

**Closed by Craluminum2413** 2024-07-02 19:20 UTC
Labels: status: new
