### ISSUE TITLE
Putting bucket of milk into barrel causes drinking of one liter of milk

### ISSUE THREAD

**Issue by petrnowak** [anegostudios/VintageStory-Issues#1724] opened 2022-02-19 08:30 UTC
**Game Version:** 1.16.3
**Platform:** Linux (Ubuntu)   
**Modded:** Yes (Fancydoors, Medieval expansion, HUD Clock, Rope bridges, Workbench expansion)  
**SP/MP:** Multiplayer (Survival)  

### Description
Putting bucket of milk into barrel causes drinking of one liter of milk (???).

### How to reproduce
1. Do have ONE bucket full of milk (10 liters).
2. Put (all) milk into empty barrel.
3. There is only 9 liters of the milk in the barrel.

### Expected behavior
Barrel should have 10 liters of the milk.

**Comment by copygirl** [comment] 2022-02-19 08:48
I'll close this as a duplicate of #1670, since it's a very similar issue and might be solved with the same fix.

**Closed by copygirl** 2022-02-19 08:48 UTC
Labels: status: duplicate

**Comment by Barhandar** [comment] 2022-08-20 09:36
Are you *sure* the bucket had 10L of milk in it? As mentioned, there's a standing bug where you get 9L from milking instead of 10L because your character immediately drinks the milk.
