### ISSUE TITLE
A Grizly Killed Me And My Baskets Disappeared

### ISSUE THREAD

**Issue by MtSheepFarm** [anegostudios/VintageStory-Issues#3281] opened 2023-12-05 05:38 UTC
### Game Version

v.1.18.5

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

During gameplay I was killed by a grizly, and although I made it to my death pile in time to collect my items from my death pile (game is set to 1 hour before item despawn, tho I made it to pile in ~8 minuts anyway) my baskets for extra inventory were all completely missing. All items that were in my hotbar were all still right where they should have been, but the baskets were gone. My inventory was completely full at the time I died. I have one world gen mod, a mod for extra trader buildings, and a logs to sticks recipe mod, but nothing that should affect inventory or creatures. 

### How to reproduce

Step 1. Have inventory completely full, one linnen pouch and three baskets. Step 2. Get killed by a bear, sleep thru the night, then go to death pile to try and collect items.

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2024-02-05 10:15
Duplicate of #3133

**Closed by Craluminum2413** 2024-02-05 10:15 UTC
Labels: status: new
