### ISSUE TITLE
Blank Hot bar slot + crash

### ISSUE THREAD

**Issue by ParkerHGordon** [anegostudios/VintageStory-Issues#791] opened 2021-02-17 20:49 UTC
I found a trader and tried to break some of their things (a chest, some gears, and a broken vessel) with an empty hot bar slot (which didn't work because it was claimed by the trader). I then went and chopped down a tree and came back to the trader to mark the spot on my map. I'm not sure if the glitch was happening before this, but after getting out of the map, I realized that my pine logs were invisible in my hot bar. I had a practically full inventory, so when I chopped down the tree the blocks should have took up the empty spot in my hot bar, but they were invisible. I went to my inventory and clicked the empty slot and suddenly I had the logs in my mouse as if they were there the whole time. I tried throwing the logs on the ground and picking them back up, tried putting other things in that hot bar slot, and no matter what I did the slot remained empty even though the items were held in my player model's hand. I eventually put a spear in that slot, and after that my model was stuck holding a spear, even if I had different items in the slot (I didn't try selecting other hot bar slots to see if I would still be stuck holding the spear). So, I tried to throw the spear, and that crashed the game. 

I should also mention that I have the Carry Capacity mod, and that I also tried to pick up the chest in the trader's place (which also didn't work). I'm not sure if it's a problem with the mod or the game, but I thought I'd still mention it here just in case. Sorry if this doesn't end up being a bug in the game itself.

Here's the crash log:

```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.7 (Stable)2/17/2021 1:17:58 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.ItemSpear.OnHeldInteractStop(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _XJ8aPSlEBe0PiHYbVJEdfXv1yjvA._Kgao3H1tkjUV97mMFigKazMDiUo(Single )
   at _QXfAdKxrJ1KaNtwiV64JU2IvnpC._cl7z8c5uEEaIF1fo0XdijiZbRYk(Single )
   at _QXfAdKxrJ1KaNtwiV64JU2IvnpC._peV5mb21IaSJTAYBddj4gA99BDo(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _03wQBzfCnykaMLiRGgbQzrKOcn3._QN2fpVgRVBDOLs27GIkkdMlxeKf(_a9AJZVMB0wcgfRPD19VvLtZCbaX , String[] )
   at _NdjU5BXvKkfOW2d88pNMbEAjE1q._QN2fpVgRVBDOLs27GIkkdMlxeKf(ThreadStart )
-------------------------------
```

**Comment by copygirl** [comment] 2021-02-17 21:49
Duplicate of #361. At this point it's starting to look like maybe CarryCapacity is partially responsible, after all.

**Closed by copygirl** 2021-02-17 21:49 UTC
Labels: status: duplicate, type: crash
