### ISSUE TITLE
Game corrupted by windmill axles, game no longer starts.

### ISSUE THREAD

**Issue by RedPine91** [anegostudios/VintageStory-Issues#876] opened 2021-05-02 13:56 UTC
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/6411492/client-crash.txt)
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/6411494/client-debug.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/6411495/client-main.txt)

I tried to mess with windmills in creative mode.  Game crashed while working on axles.

Disabled all mods and started a new creative mode.  Game still crashed after a bit.

Game now crashes on startup, before I've even tried to create or load into a world.  See logs.

**Comment by copygirl** [comment] 2021-05-02 14:27
Did you disable the official mods the game comes with? Those are "Essentials", "Creative Mode" and "Survival Mode".
That is likely the cause of this crash:
```
2.5.2021 07:46:38 [Fatal] System.Exception: This save game requires world generator superflat but no such generator was found! I cannot continue like this, sorry :(
If you really need the contents of the save game, build a tiny mod that registers such world generator that just generates air blocks
   at Vintagestory.Server.ServerSystemSupplyChunks.LoadWorldgenHandlerAndSpawnChunks()
   at Vintagestory.Server.ServerMain.EnterRunPhase(EnumServerRunPhase runPhase)
   at Vintagestory.Server.ServerMain.Launch()
   at _ISiSTzGmXXpAqo3PzdxdVD1bClZ._WpGAXiVoJmxWu1fCRjqBgmcU7Y8()
```

The crash with the angled gears comes from VSHUD's placement preview feature.
See if there is a newer version of the mod, or report to the mod author.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at VSHUD.FixAngledGears.Fix(BlockAngledGears bAg, IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel, String& failureCode)
   at VSHUD.FixAngledGears.TryPlaceBlock(BlockAngledGears __instance, IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel, String& failureCode, Boolean& __result)
   at Vintagestory.GameContent.Mechanics.BlockAngledGears.TryPlaceBlock_Patch2(BlockAngledGears this, IWorldAccessor world, IPlayer byPlayer, ItemStack itemstack, BlockSelection blockSel, String& failureCode)
   at VSHUD.NewPlacementPreview.Postfix(Block __instance, ItemSlot slot, EntityAgent byEntity)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnGameTick(Single dt)
   [...]
```

**Comment by RedPine91** [comment] 2021-05-03 17:08
Whoops, i indeed did.  Still, even with survival disabled, the game needs
to boot up so thst i can reenable survival. Had to do a hard reinstall, so
i cant replicate the issue.

I believe vshud mod while placing axles in creative was the initial cause
of crashes, but again, i hard reinstalled already Nd havent been able to
replicate  the issue yet.

On Sunday, May 2, 2021, copygirl ***@***.***> wrote:
> Did you disable the official mods the game comes with? Those are
"Essentials", "Creative Mode" and "Survival Mode".
> That is likely the cause of this crash:
>
> 2.5.2021 07:46:38 [Fatal] System.Exception: This save game requires world
generator superflat but no such generator was found! I cannot continue like
this, sorry :(
> If you really need the contents of the save game, build a tiny mod that
registers such world generator that just generates air blocks
> at
Vintagestory.Server.ServerSystemSupplyChunks.LoadWorldgenHandlerAndSpawnChunks()
> at Vintagestory.Server.ServerMain.EnterRunPhase(EnumServerRunPhase
runPhase)
> at Vintagestory.Server.ServerMain.Launch()
> at _ISiSTzGmXXpAqo3PzdxdVD1bClZ._WpGAXiVoJmxWu1fCRjqBgmcU7Y8()
>
> The crash with the angled gears comes from VSHUD's placement preview
feature.
> See if there is a newer version of the mod, or report to the mod author.
>
> System.NullReferenceException: Object reference not set to an instance of
an object.
> at VSHUD.FixAngledGears.Fix(BlockAngledGears bAg, IWorldAccessor world,
IPlayer byPlayer, BlockSelection blockSel, String& failureCode)
> at VSHUD.FixAngledGears.TryPlaceBlock(BlockAngledGears __instance,
IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel, String&
failureCode, Boolean& __result)
> at
Vintagestory.GameContent.Mechanics.BlockAngledGears.TryPlaceBlock_Patch2(BlockAngledGears
this, IWorldAccessor world, IPlayer byPlayer, ItemStack itemstack,
BlockSelection blockSel, String& failureCode)
> at VSHUD.NewPlacementPreview.Postfix(Block __instance, ItemSlot slot,
EntityAgent byEntity)
> at
Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnGameTick(Single
dt)
> [...]
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci3.googleusercontent.com/proxy/w3ptxC9Uq0xuRuhhFF4GNs5P_hPh0jjEm1GpQixpEp3dm9_LfzJgiHo0b07Er_Df0gnr3keFyFP2F8MZhhIUyExYSBDtnNgERrocf-om-7o209wI6TgGh871L_k0csKQvIWEaIBY4EAjjs4dUFPBDQUg4shlSntAASYACOVKLpkl2VTooVzouPwff7kPlOiCF0SM9G19_-X1heyHRFjJCAHdihVUMQ9blVLXWT-amQ=s0-d-e1-ft#https://github.com/notifications/beacon/AHGQG2L5SCQGNL4S7K4MKF3TLVOODA5CNFSM437NTOHKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGGCUNNA.gif>

**Comment by copygirl** [comment] 2021-05-03 18:04
Will close this as resolved for now, then!

**Closed by copygirl** 2021-05-03 18:04 UTC
Labels: status: resolved, target: modding, type: crash
