### ISSUE TITLE
Game Crashes on World Load in Multiplayer Server

### ISSUE THREAD

**Issue by thekrazykitten** [anegostudios/VintageStory-Issues#4656] opened 2024-12-11 04:37 UTC
### Game Version

1.20.0-rc.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

On attempting to load my friend's multiplayer world, I crash. I submitted a similar issue about a week ago, after getting about 30 minutes into a new world with a friend and suddenly hard crashing. My friend found a ruins structure at roughly the same time that I crashed, and since then I have been unable to load the world without the game client closing and bringing up the issue tracker. In previous versions, I would frequently crash upon loading certain blocks, although in those cases typically the error message would just say that the client thread crashed, before sending me to the main menu. When I submitted my most recent bug report, it was reccommended that I reinstall the game in order to fix the issue. Upon reinstallation, I still crash immediately upon loading the world. The point in the world loading where I crashed, according to my friend, was shortly after my character began rendering, but before the game pronounced me as having joined the game.

### How to reproduce

As far as I know, I just crash upon world load. I don't know if anyone else has this issue.

### Logs

```Log```Running on 64 bit Windows 10.0.22631.0 with 8023 MB RAM
Game Version: v1.20.0-rc.1 (Unstable)
12/10/2024 9:27:41 PM: Critical error occurred
Loaded Mods: 
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'The ThreadLocal object has been disposed.'.
   at System.Threading.ThreadLocal`1.GetValueSlow()
   at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionStatesNative(IWorldAccessor world, ItemSlot inslot) in VintagestoryApi\Common\Collectible\Collectible.cs:line 2501
   at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionStates(IWorldAccessor world, ItemSlot inslot) in VintagestoryApi\Common\Collectible\Collectible.cs:line 2446
   at Vintagestory.API.Common.CollectibleObject.AppendPerishableInfoText(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1805
   at Vintagestory.API.Common.CollectibleObject.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1648
   at Vintagestory.GameContent.ItemPoultice.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VSSurvivalMod\Item\ItemPoultice.cs:line 70
   at Vintagestory.API.Common.ItemStack.GetDescription(IWorldAccessor world, ItemSlot inSlot, Boolean debug) in VintagestoryApi\Common\Collectible\ItemStack.cs:line 400
   at Vintagestory.GameContent.GuiHandbookItemStackPage..ctor(ICoreClientAPI capi, ItemStack stack) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 40
   at Vintagestory.GameContent.ModSystemSurvivalHandbook.onCreatePagesAsync() in VSSurvivalMod\Systems\Handbook\SurvivalHandbook.cs:line 86
   at Vintagestory.GameContent.GuiDialogHandbook.LoadPages_Async() in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 418
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 120
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 12/5/2024 6:24:32 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: KERNELBASE.dll, version: 10.0.22621.4391, time stamp: 0x7433a115
Exception code: 0xe0434352
Fault offset: 0x000000000005fa4c
Faulting process id: 0x0xcb98
Faulting application start time: 0x0x1db477b94c597e5
Faulting application path: C:\Users\thekr\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 1dfa7e25-9180-4cbb-b5c3-c7cc83e47272
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by thekrazykitten** [comment] 2024-12-11 04:38
I can requisition the log files for the server side if that would be helpful for helping to debug this issue.

**Comment by Craluminum2413** [comment] 2024-12-11 11:17
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4225

**Closed by Craluminum2413** 2024-12-11 11:17 UTC
Labels: status: new
