### ISSUE TITLE
Cloud height slider doesn't work in WE

### ISSUE THREAD

**Issue by AreYSerious** [anegostudios/VintageStory-Issues#3584] opened 2024-02-14 12:53 UTC
### Game Version

v1.19.3

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Just try the worldedit cloud height slider and you will see.

### Logs

```Log```

**Comment by Th3Dilli** [comment] 2024-03-09 09:36
I have tested this on 1.19.5-rc.1 now and so far it seems to work as it should.

maybe it needs some other combinations of settings to not work anymore?

**Comment by AreYSerious** [comment] 2024-03-09 09:38
I will test it later on the latest version and see if it still doesnt work...

**Comment by AreYSerious** [comment] 2024-03-10 16:29
v1.19.5 rc1
https://www.youtube.com/watch?v=c0_YnG9Tq-w

**Comment by Craluminum2413** [comment] 2024-03-10 16:40
Can't reproduce on 1.19.5-rc.1

**Comment by AreYSerious** [comment] 2024-03-10 16:53
Nice

**Comment by AreYSerious** [comment] 2024-03-10 18:00
im on 1.19.5-rc.1 and for me, it doesn't work. pure vanilla

**Comment by AreYSerious** [comment] 2024-03-10 18:22
maybe its a windows problem. It looks like its getting the numbers wrong when using the slider.

**Comment by Th3Dilli** [comment] 2024-03-18 19:47
ok i was able to repro the issue now, it seems to be related to German as OS language (or others that doe number formating with ",")

will be fixed in the next release, ty

**Closed by Th3Dilli** 2024-03-18 19:47 UTC
Labels: target: creative, status: new, department: code
