### ISSUE TITLE
Welcome text in chat box in singleplayer does not use translation

### ISSUE THREAD

**Issue by tannyl** [anegostudios/VintageStory-Issues#4409] opened 2024-10-31 12:33 UTC
### Game Version

1.20.0-pre.9

### Platform

Linux

### Modded

None

### SP/MP

Singleplayer

### Description

The welcome text (translation key is `survive-and-star-trek`) shown in the chat box when you start singleplayer does not use the translated version from the translation files.

### How to reproduce

1. Start singleplayer using English as the language and see the welcome message in the chat box.  
2. Change the language and restart the game.  
3. Start singleplayer again and see the same welcome message in English instead of in the chosen language.

### Screenshots

![survive-and-star-trek](https://github.com/user-attachments/assets/c573182a-95f7-4a74-b570-8507cb16a48e)

### Logs

```Log```

**Comment by MyraMidnight** [comment] 2024-12-20 11:39
![image](https://github.com/user-attachments/assets/c0da919b-369f-4645-aa72-d263382196fe)
Since this is a translatable message, it does not seem to be used in the game to actually translate the message in chat window.
still an issue in the 1.20.0-rc.5

And there seem to be many more messages lying around that aren't in the translation files from commands I imagine, like seen in the screenshot, was using the `.reload lang`. Not a huge issue because technical stuff tends to not translate well, but it's worth a try, lol.

**Comment by radfast** [comment] 2024-12-23 15:04
This is intended behavior. The welcome message is configurable for each game world, and is therefore only a suggestion/placeholder/default inserted by game code when the game world is first created. It **does** correctly use the language setting which is in force when the world is first created (just tested and confirmed). After the world is created, the name is baked into the worldconfig for that world, so any _later_ changes in the language setting will not affect it.

The world admin (i.e. you, in single player) can change the welcome message to anything you like, using command `/worldconfig WelcomeMessage new-message` where  `new-message` is the new message of course.

The WelcomeMessage is set once per server world. It cannot be translated into each player's own language by the game when the message arrives at the client side, as obviously it could be any custom string.

(Related to, but not the same as, the issue where player death messages are broadcast in the dying player's language, not the reading player's language.  In general we have no system to translate **incoming** chat messages on the client side.)

@MyraMidnight on your related point, the commands themselves are not translated, nor is the commands help, and we do not aim to translate the output of game control / debug type commands which would usually only be used by a server admin or experienced player. We do aim to localize the output of common "inherent" commands, I mean anything the player might see in chat without the player actually typing a command themselves - for example, the Timeswitch activation - but even there we probably did not get all of them yet...

**Comment by radfast** [comment] 2024-12-23 15:41
OK ...

So this is intended behavior. The welcome message is configurable on every server/game installation, in file `serverconfig.json`.

The "survive and prosper" text is only a suggestion/placeholder/default inserted by game code when the `serverconfig.json` settings file is first created. In principle, it **does** correctly use the language setting which is in force when that file is created, however I can see that many people might not have yet set their language setting when they first run the game.

After the first run of a game installation, the welcome message is baked into the serverconfig settings fie, so any _later_ changes in the language setting will not affect it.

However, any single player (or in multiplayer, any admin ) can change the welcome message to anything you like, using command `/serverconfig welcome new-message` where  `new-message` is the new message of course. Or by editing the `serverconfig.json` directly, it's the same thing in the end.  There can also be a `motd`.

The welcome message is set uniquely per server. It cannot be translated into each player's own language by the game when the message arrives at the client side, (a) because it has already been localized by the server, and (b) because it could be any custom string, in this case it names the player.

I don't think we want to automatically update the server's welcome message in `serverconfig.json` any time the user changes language, as that would overwrite any existing custom message.

(Related to, but not the same as, the issue where player death messages are broadcast in the dying player's language, not the reading player's language.  In general we have no system to translate **incoming** chat messages on the client side, servers do the localization of chat messages.)

For now I'm going to call this intended behavior, and mark it "won't fix". The proper fix is for the player/server owner to use the `/serverconfig welcome` message which I mentioned.  Longer term, the dev team can maybe look at using a special code in chat messages to tell the client that the server is sending a lang key which **does** need to be translated client-side, the difficulty is how then to deal with its parameters.

**Closed by radfast** 2024-12-23 15:41 UTC
Labels: status: new, target: localization, department: code, department: lang

**Comment by tannyl** [comment] 2024-12-23 16:18
I fully understand not translating custom welcome messages. Does not make sense to even try to do that.

The proper solution with the server sending lang keys instead of the fully translated string seems to be a good solution in the long run.
