### ISSUE TITLE
Panning

### ISSUE THREAD

**Issue by Xandoria** [anegostudios/VintageStory-Issues#1960] opened 2022-06-24 19:24 UTC
**Game Version:** 1.17.0-pre1 
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
Panning does not work anymore.

### How to reproduce
1. Place some bony soil block on the ground next to water
2. Go in the water
3. Use the pan on the bony soil block. The block loses one layer.
4. Pan in the water
5. Nothing is obtained from the panning
6. Repeat
7. Still nothing obtained from panning
8. Go far away
9. Come back later
10. All the bony blocks have been restored to their previous state without missing layers.

```

**Comment by copygirl** [comment] 2022-06-24 19:26
Duplicate of #1924.

**Closed by copygirl** 2022-06-24 19:26 UTC
Labels: status: duplicate
