### ISSUE TITLE
Crash after creating singleplayer world

### ISSUE THREAD

**Issue by bonenaut7** [anegostudios/VintageStory-Issues#4754] opened 2024-12-20 18:03 UTC
### Game Version

v1.20 rc.5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Crash after creating singleplayer world and entering creative mode, flying around a bit.
Got kicked out of singleplayer server with the message to check logs
(View distance is set to 512 blocks)

### How to reproduce

1. Create singleplayer world
2. Enter creative mode
3. Fly around a bit?

### Logs

```
20.12.2024 20:58:39 [Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.Server.PhysicsManager.TickFixedRate30TPS() in VintagestoryLib\Server\PhysicsManager.cs:line 314
   at Vintagestory.Server.PhysicsManager.ServerTick(Single dt) in VintagestoryLib\Server\PhysicsManager.cs:line 104
   at Vintagestory.Common.GameTickListener.OnTriggered(Int64 ellapsedMilliseconds) in VintagestoryLib\Common\Model\GameTickListener.cs:line 27
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 57
   at Vintagestory.Server.ServerMain.Process() in VintagestoryLib\Server\ServerMain.cs:line 893
20.12.2024 20:58:39 [Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.Server.PhysicsManager.DoWork(Int32 threadNumber) in VintagestoryLib\Server\PhysicsManager.cs:line 559
   at Vintagestory.Common.LoadBalancer.SynchroniseWorkToMainThread(Object source) in VintagestoryLib\Common\LoadBalancer.cs:line 84
   at Vintagestory.Server.PhysicsManager.TickFixedRate30TPS() in VintagestoryLib\Server\PhysicsManager.cs:line 314
   at Vintagestory.Server.PhysicsManager.ServerTick(Single dt) in VintagestoryLib\Server\PhysicsManager.cs:line 104
   at Vintagestory.Common.GameTickListener.OnTriggered(Int64 ellapsedMilliseconds) in VintagestoryLib\Common\Model\GameTickListener.cs:line 27
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 57
   at Vintagestory.Server.ServerMain.Process() in VintagestoryLib\Server\ServerMain.cs:line 893
```

**Comment by radfast** [comment] 2024-12-21 00:31
Please can you post up your `servermagicnumbers.json` file - if you changed it, then the version with the same settings as used when this crash occurred please.   The file should be found in the standard data folder, `%appdata%\VintagestoryData`.

**Comment by bonenaut7** [comment] 2024-12-21 10:27
Oh, looks like it's too old
[servermagicnumbers.json](https://github.com/user-attachments/files/18218145/servermagicnumbers.json)

**Comment by radfast** [comment] 2024-12-21 12:59
Further question, @bonenaut7: please provide full `server-main.log` from the game session when this occurred.  (You'll probably need to look in `Logs/Archive` to find it, the older folders there are timestamped)

**Comment by bonenaut7** [comment] 2024-12-22 23:07
@radfast unfortunately logs has been overwritten when i was trying to make tests for previous issue
Logs are not saving to archive for some reason for me, could it be caused by some option in game settings?

**Comment by radfast** [comment] 2024-12-23 03:09
That's a shame, never mind.

The reported issue is fundamentally a mystery to us - not reproducible, as marked here.  Two or three in the dev team have now looked at it and we can see no way that anything in the relevant code can be `null`.  However, .NET7 runtime optimisations and in-lining of code do significantly alter line numbers, so could be something we are not seeing.  In upcoming game version 1.20.0-rc.6, which is maybe 5-8 days away, we have added additional try/catch/throw and logging to try to pinpoint the cause of this issue if it occurs again.

I would hope that meanwhile you can just continue to play normally, it may be this was a 'one-off' and will not recur.

> Logs are not saving to archive for some reason for me (I have only client-side logs there), could it be caused by some option in game settings?
There's no such option that I'm aware of.  If you are playing Multiplayer then sure, you will only have client-side logs for that particular game session.  But for Singleplayer games, each subfolder in the Archives folder should store 9 log files - 4 client logs, 5 server logs.  If that is not happening it needs to be looked into.  Some possible thoughts:

1. Are you alternating between singleplayer and multiplayer games? 
2. Do you have the log files open in another app, for example a text editor?
3. Are you doing anything coder-like to the game, for example developing your own mod, or applying coder tools or debuggers to the game code while it's running?   (That's OK, our game code has a "readable source" licence and we intend for modders to be able to read and explore it freely)

More generally,

**Comment by radfast** [comment] 2024-12-24 17:37
@bonenaut7 for the original issue, please do try updating to 1.20.0-rc.6 which contains additional debugging code around this specific issue (it doesn't change the behavior, just logs more info), and it does also fix plenty of other issues.

If you experience any further crash, please do post a fresh `server-main.log` or relevant extract

**Comment by radfast** [comment] 2024-12-24 22:26
As discussed in my final post on #4783, I have now found and fixed the root cause of this crash. The fix will be included in next build when it comes, whether that is 1.20.0-rc.7 or 1.20.0-stable. May be a few days.

**Closed by radfast** 2024-12-24 22:26 UTC
Labels: status: in-progress, department: code, status: can't reproduce
