### ISSUE TITLE
[1.19.0-rc.5] "Shield Raised" arm animation gets stuck when shield is put onto ground.

### ISSUE THREAD

**Issue by AncletYinglet** [anegostudios/VintageStory-Issues#3395] opened 2024-01-06 10:33 UTC
### Game Version

v1.19.0-rc.5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

As title explains. First person and third person animations are both effected by this. Putting a shield down onto the ground raises your arm permanently until you put a shield back into your right hand, which effectively resets your arm position. This cannot be undone by swapping to other blocks or items.

Note that you can also place the shield down into an already-existing ground storage with another item by simply Ctrl-clicking, in which case this does not trigger the bug. Only while crouching with the shield while submitting to ground storage does this occur.

### How to reproduce

1. Acquire shield
2. Shift+Ctrl+RMB shield onto ground
3. Observe 

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/148595378/e8f8b42b-1b47-4433-a1c0-aa60d7d6483a)

**Comment by pingouyn** [comment] 2024-01-07 02:49
Looks like it's similar to #3361, could have a common cause?

**Comment by AncletYinglet** [comment] 2024-01-07 03:21
> Looks like it's similar to #3361, could have a common cause?

Ah, yeah, it looks like the exact same, actually.

**Comment by Craluminum2413** [comment] 2024-01-07 03:24
Duplicate of #3361

**Closed by Craluminum2413** 2024-01-07 03:24 UTC
Labels: status: new, version: 1.19
