### ISSUE TITLE
Crash Report - When rendering Fruit Tree leaves

### ISSUE THREAD

**Issue by mvillaronga** [anegostudios/VintageStory-Issues#2695] opened 2023-05-03 06:48 UTC
### Game Version

v1.18.1 Stable

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

System crashes when walking in the world.  I disabled all my mods as I thought it might be related to the upgraded renderer I had installed but I still see the issue when all mods are disabled.  I have pasted the crash listing below.

### How to reproduce

It appears that when I come in range of a fruit tree to render the game crashes.  I can upload a world file backup if asked.

### Logs

```Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.18.1 (Stable)
5/2/2023 10:25:34 PM: Critical error occurred
Loaded Mods: game@1.18.1, creative@1.18.1, survival@1.18.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityFruitTreePart.GenFoliageMesh(Boolean withSticks, MeshData& foliageMesh, MeshData& sticksMesh) in VSSurvivalMod\Systems\FruitTree\BEFruitTreePart.cs:line 212
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.GenMeshes() in VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:line 250
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.GenMesh() in VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:line 236
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldForResolving) in VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:line 386
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(Packet_BlockEntity p, ClientMain game) in VintagestoryLib\Client\Model\ClientChunk.cs:line 399
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 409
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 744
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 681
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 625
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 119
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by Craluminum2413** [comment] 2023-05-03 09:07
Duplicate of #2610

**Closed by Craluminum2413** 2023-05-03 09:07 UTC
Labels: status: new
