### ISSUE TITLE
Crash from specific chunk

### ISSUE THREAD

**Issue by DeopLeornian** [anegostudios/VintageStory-Issues#2104] opened 2022-08-09 23:15 UTC
**Game Version:** v1.17.0-rc.5 (Unstable)
**Platform:** Windows
**Modded:** Yes, but crash occurs when they are disabled
**SP/MP:** Singleplayer 

### Description
There seems to be a particular chunk that crashes when I get too close to it.  That part of the map has been explored before.

Crash also happened in rc.4 and rc.3

### How to reproduce
If I go close to the chunk in my save it crashes.  Can't reproduce it on a fresh save.

### Expected behavior
To not crash

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.0-rc.5 (Unstable)
Loaded Mods: game@1.17.0-rc.5, creative@1.17.0-rc.5, survival@1.17.0-rc.5
8/9/2022 18:07:10: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityFruitTreePart.GenFoliageMesh(Boolean withSticks, MeshData& foliageMesh, MeshData& sticksMesh) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\FruitTree\BEFruitTreePart.cs:line 183
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.GenMeshes() in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:line 241
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.GenMesh() in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:line 228
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldForResolving) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:line 372
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(Packet_BlockEntity p, ClientMain game) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Model\ClientChunk.cs:line 409
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(Packet_Server packet) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 808
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:line 1138
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 123
   at Vintagestory.Client.ScreenManager.Render(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:line 664
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:line 608
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 125
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 87
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 8/9/2022 18:07:13, Site = , Source = Windows Error Reporting, Message = Fault bucket 1467817390384888267, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.0.0
P3: 62f2b368
P4: KERNELBASE.dll
P5: 10.0.21390.1
P6: e83522b9
P7: c0020001
P8: 000000000004491c
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.eae39d6f-8dc0-4777-9b18-9d1ab189a84b.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.ab97e05e-5278-47d9-8846-99caba0ad68e.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.f6dcecfc-0ee2-482e-8c3d-26fc77d7cc45.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.fee9f388-be7f-4f57-a6f8-22f8edef7966.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.6396198f-0b27-4cc4-afc8-a4961e971865.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_f0dea859c31af1f9301b44629e806f9fb6ea2549_54985b8a_6f9a3f0c-7c3a-4acd-82ce-eff6139befc9

Analysis symbol: 
Rechecking for solution: 0
Report Id: f307ac73-26b3-4621-b6dc-345c5e6621a8
Report Status: 268566528
Hashed bucket: 49af4774482a6588b45ebc23c50839cb
Cab Guid: 0 }
--------------
{ TimeGenerated = 8/9/2022 18:07:11, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.17.0.0, time stamp: 0x62f2b368
Faulting module name: KERNELBASE.dll, version: 10.0.21390.1, time stamp: 0xe83522b9
Exception code: 0xc0020001
Fault offset: 0x000000000004491c
Faulting process id: 0x3f90
Faulting application start time: 0x01d8ac449fb75b54
Faulting application path: C:\Users\Timothy\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: f307ac73-26b3-4621-b6dc-345c5e6621a8
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 8/9/2022 18:07:10, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FFF5AD4491C
Stack:
 }
```

**Comment by Craluminum2413** [comment] 2022-08-10 09:12
Duplicate of #2102

**Closed by Craluminum2413** 2022-08-10 09:12 UTC
Labels: status: new
