### ISSUE TITLE
burned trunks keep the right side of them in the world as an invisible block

### ISSUE THREAD

**Issue by nebuxmz** [anegostudios/VintageStory-Issues#1636] opened 2022-01-24 22:19 UTC
**Game Version:1.1.6.1 stable
**Platform:** Windows
**Modded:no
**SP/MP:** Singleplayer

### Description
if a trunk burns, the right side is kept in the world as an invisible block. and can't be removed
### How to reproduce
1. burn a trunk, and try to put something in his right side space block
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
![2022-01-24_22-11-43](https://user-images.githubusercontent.com/98090075/150874508-e4e5059d-8115-4d38-8e20-8d2cbca5c118.png)

### Logs
```
Paste crash between the triple backticks.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.
```

**Comment by Craluminum2413** [comment] 2022-01-24 22:21
Duplicate of #1625?

**Comment by copygirl** [comment] 2022-01-25 15:53
Possibly related but I wouldn't say duplicate, especially due to Vanilla / modded reason.

**Comment by Craluminum2413** [comment] 2022-01-25 16:55
Both blocks have Multiblock behavior

**Comment by copygirl** [comment] 2022-01-25 18:13
@Craluminum2413 Just because Vanilla defines both those behaviors, it doesn't mean they're necessarily compatible together. But that's off-topic in relation to this issue.

**Closed** 2023-04-09 22:51 UTC
Labels: status: resolved
