### ISSUE TITLE
Some texture issue

### ISSUE THREAD

**Issue by kousakak** [anegostudios/VintageStory-Issues#1252] opened 2021-08-07 02:44 UTC
**Game Version:** 1.15.3  
**Platform:** Windows  
**Modded:** No  

### Description
Something wrong with texture of grass,not sure whether other plants and crops have this issue or not.Same issure happened on cattail and fixed long ago.
And something wrong with saltpeter on the block.

### Screenshots
![2021-08-02_15-27-53](https://user-images.githubusercontent.com/60339803/128585055-7c4bb746-32c0-4c7d-aa14-7a72631591a4.png)
![2021-08-02_15-44-00](https://user-images.githubusercontent.com/60339803/128585241-7bc01488-6118-4f7c-8392-430415253109.png)

**Comment by copygirl** [comment] 2021-08-07 06:37
First is duplicate of #921. Second is just the model of saltpeter when viewed using noclip, from what I understand. Thank you for reporting however.

**Closed by copygirl** 2021-08-07 06:37 UTC
Labels: status: duplicate
