### ISSUE TITLE
Index was outside the bounds of the array

### ISSUE THREAD

**Issue by WickedSchnitzel** [anegostudios/VintageStory-Issues#4318] opened 2024-10-16 20:44 UTC
### Game Version

1.20-pre6

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Was flying with a (modded) glider and then when pressing E to open the inventory, it crashed. Not sure if that's caused by the mod or is something vanilla to fix.

### Logs

```Running on 64 bit Windows 10.0.19045.0 with 32723 MB RAM
Game Version: v1.20.0-pre.6 (Unstable)
16.10.2024 22:40:04: Critical error occurred
Loaded Mods: bettercrates@1.7.1, game@1.20.0-pre.6, weaponpackalphaunoff@1.5.1, fantasycreatures@0.7.1, creative@1.20.0-pre.6, vsquest@1.2.0, survival@1.20.0-pre.6, cob2@1.6.8, cobserver@1.0.2, cob@1.9.6
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.API.Client.GuiElementVerticalTabs.SetValue(Int32 index, Boolean triggerHandler) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementVerticalTabs.cs:line 309
   at Vintagestory.Client.NoObf.GuiDialogInventory.ComposeCreativeInvDialog() in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogInventory.cs:line 248
   at Vintagestory.Client.NoObf.GuiDialogInventory.ComposeGui(Boolean firstBuild) in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogInventory.cs:line 91
   at Vintagestory.Client.NoObf.GuiDialogInventory.OnGuiOpened() in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogInventory.cs:line 444
   at Vintagestory.API.Client.GuiDialog.TryOpen(Boolean withFocus) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 289
   at Vintagestory.API.Client.GuiDialog.TryOpen() in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 269
   at Vintagestory.Client.NoObf.GuiDialogInventory.TryOpen() in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogInventory.cs:line 437
   at Vintagestory.API.Client.GuiDialog.Toggle() in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 343
   at Vintagestory.API.Client.GuiDialog.OnKeyCombinationToggle(KeyCombination viaKeyComb) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 410
   at Vintagestory.Client.NoObf.GuiDialogInventory.OnKeyCombinationToggle(KeyCombination viaKeyComb) in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogInventory.cs:line 541
   at Vintagestory.Client.HotkeyManager.TriggerHotKey(KeyEvent keyEventargs, IWorldAccessor world, IPlayer player, Boolean allowCharacterControls, Boolean isGlobal, Boolean fallBack, Boolean keyup) in VintagestoryLib\Client\HotkeyManager.cs:line 431
   at Vintagestory.Client.NoObf.ClientMain.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1744
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(KeyboardKeyEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 230
   at OpenTK.Windowing.Desktop.NativeWindow.KeyCallback(Window* window, Keys key, Int32 scancode, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 05.10.2024 19:27:55, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.20.0.0, Zeitstempel: 0x66470000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x108
Startzeit der fehlerhaften Anwendung: 0x01db174bd557cd11
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Kai\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: c5c178d4-7c88-4521-8c4b-e03ddf588682
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 04.10.2024 00:10:14, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.20.0.0, Zeitstempel: 0x66470000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x12d8
Startzeit der fehlerhaften Anwendung: 0x01db15e0eec09e82
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Kai\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: 89a8deb7-6e9e-48e4-b168-f1ea5d56350a
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 04.10.2024 00:03:56, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.20.0.0, Zeitstempel: 0x66470000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x2244
Startzeit der fehlerhaften Anwendung: 0x01db15e0063c3e94
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Kai\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: 63cf9c82-a473-427c-ae35-e74a4dcc38ac
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }```

**Comment by Craluminum2413** [comment] 2024-10-16 20:46
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4191

**Closed by Craluminum2413** 2024-10-16 20:46 UTC
Labels: status: new
