### ISSUE TITLE
Cave art / decors reappearing after block has been broken

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#992] opened 2021-06-12 18:53 UTC
**Game Version:** 1.15.0-pre3
**Platform:** Windows 
**Modded:** No

### Description
Cannot get rid of a cave art.

### How to reproduce
1. Take a charcoal and draw a pattern on some support.
2. Destroy the support and replace it, or place another type of block at the same location.
3. Quit and restart game
4. The pattern is back.
5. This bug allow you to draw cave art on mud block (draw on stone, replace by mud, et voilà)

### Workaround

1. Destroy the block with the ugly cave art.
2. Quit and restart.
3. Place the block again.

### Expected behavior
Destroyed pattern should not reappear.

**Comment by Craluminum2413** [comment] 2021-06-13 13:25
I wonder, will can we draw with chalk / limestone

**Comment by Saricane** [comment] 2021-06-13 13:32
Could be nice on darkest stones.

**Comment by tyronx** [comment] 2021-06-14 09:47
hm, i cannot reproduce this in a superflat world

**Comment by Saricane** [comment] 2021-06-14 10:07
> 
> 
> hm, i cannot reproduce this in a superflat world

I have strange behaviour with this bug. I had 2 patterns. One on a vertical face of a cobblestone, another on a cobblestone floor.
I can get rid of the pattern on the cobblestone floor with the method described above. But the "vertical" pattern ALWAYS come back at a moment or another (unless I leave that block empty). It comes back even on the empty half of a vertical slab, floating in the air. I'll try to make some tests in creative mode and put screenshots.

**Comment by Saricane** [comment] 2021-06-14 16:09
Ok Tyron, I made some more tests. Firstly, in "superflat world", cannot even draw a pattern. I never use this mode, so I don't know why. It's probably me.

But in survival mode, I have now a better understanding of the bug. Here's a more precise recipe to reproduce it.

1. draw a pattern
2. save and restart game
3. destroy the block and replace it by the same kind of block
4. save and restart game : the pattern is back. Problem.
5. destroy the block again and replace it by a non printable block (hay, sand, ...)
6. save and restart
7. the non printable block is now printed.

Screenshots below of all those actions.

![2021-06-14_17-42-17](https://user-images.githubusercontent.com/84909583/121923636-6bc88500-cd3b-11eb-9d6c-bb37dd382dd4.png)
![2021-06-14_17-43-57](https://user-images.githubusercontent.com/84909583/121923678-7551ed00-cd3b-11eb-8f95-4603f2696062.png)
![2021-06-14_17-44-57](https://user-images.githubusercontent.com/84909583/121923693-78e57400-cd3b-11eb-94c0-43ca9667cbf5.png)
![2021-06-14_17-45-55](https://user-images.githubusercontent.com/84909583/121923702-7b47ce00-cd3b-11eb-817e-379a04755395.png)
![2021-06-14_17-46-48](https://user-images.githubusercontent.com/84909583/121923712-7e42be80-cd3b-11eb-9e9a-773d9e11aa8b.png)
![2021-06-14_17-47-25](https://user-images.githubusercontent.com/84909583/121923722-80a51880-cd3b-11eb-84f6-69ad6f787377.png)
![2021-06-14_17-48-20](https://user-images.githubusercontent.com/84909583/121923731-826edc00-cd3b-11eb-85cd-75ceba12c1d5.png)

**Comment by radfast** [comment] 2021-06-26 21:27
This is more of a suggestion than a bug.  The suggestion is "Please add a way to erase cave art".

The cave art can be destroyed simply by breaking the block it's drawn on.  I'd say that is fairly intuitive and realistic.

**Comment by Saricane** [comment] 2021-06-26 21:43
> This is more of a suggestion than a bug. The suggestion is "Please add a way to erase cave art".

This is absolutely not a suggestion. The drawing reappear and reappear, even if you destroy the block, even if you replace it by another block, even if you replace it by another kind of block, even if this new block is non printable, even if you let the block empty and a grass spawn, etc ...

**Comment by tyronx** [comment] 2021-06-27 08:49
Yes, this does sound like a bug

**Comment by radfast** [comment] 2021-07-01 19:40
Please excuse my comment from 5 days ago, it was based on a quick reading of the title of this issue.

I have carefully followed the steps you describe, and a few variations that I can think of, and I cannot reproduce this issue.  If you have time, it would be amazing if you can:
- re-test the issue in `pre.11`
- check that the sequence of steps 1-7 you have described still covers it
- let me know any other details, e.g. what tool do you use to break the granite block at step 3, is the player in survival or creative
- any additional points to note like is this at a chunk edge
- do you have to destroy and replace the block at step 3 very rapidly?

The cause of the issue you have described is that destroying the granite block at step 3, did not remove the cave art from the chunk, server-side.   It removed it client-side only.  The save game saves what is stored on the server.   Cave art only checks whether it is on a valid stone surface at the time it is drawn, so if the save game has Cave art at a position, then that Cave art will be drawn on whatever block.  And switching the block from Granite to Hay to Glass slab is doing the same thing: breaking the block, is not removing the cave art server-side.

It's possible this issue has been fixed already since 17 days ago, through improved server/client syncing of Cave art ...

**Comment by radfast** [comment] 2021-07-01 20:06
Also, are you in Single Player mode, or is this only seen a standalone server?

**Comment by Saricane** [comment] 2021-07-01 20:56
No problem with this little misunderstanding, Radfast :-)
I'm making the tests you asked, but before I've got some more acurate conclusions to bring here, I can say for sure that the bug is still there. I'm now playing survival (single player mode) with pre11 on a pre6 world, and my first try with steps 1-7 gave exactly the same results. This is a screenshot of the last step.
About chunk edge, it turns out that yes, the block on the screenshot is at a chunk boundary (but not in a corner). But, even if I need to complete more tests, I already have a second example of another block which is not at a boundary. I don't remember about the tests I made on the beginning of this posts, I don't have this world anymore.
In those tests, I use an iron pickaxe.

I will proceed to more tests tomorrow.

![2021-07-01_22-19-29](https://user-images.githubusercontent.com/84909583/124187527-3c957000-dabe-11eb-9e42-7574af89f22f.png)

**Comment by Saricane** [comment] 2021-07-03 12:43
First try I just made with pre12 (on a pre11 world) 

1. Draw something on a cobblestone wall
2. Quit and restart
3. Remove the cobblestone block and put it again on the same place. I mean the SAME cobblestone block (not only a cobblestone block). No drawing (logical).
4. Quit and restart, the drawing is back.

**Comment by Craluminum2413** [comment] 2021-07-03 12:47
So it can't be reproduced with rocks?

**Comment by Saricane** [comment] 2021-07-03 12:49
Did not try with pre12, but the set of screenshots at the beginning of this post was made with rocks in creative mode. Have to try again.

**Comment by radfast** [comment] 2021-07-04 17:36
Hmm it's weird that you guys can reproduce this and I cannot.  Guess I should try again.  Both of you are testing in single player games?

**Comment by Craluminum2413** [comment] 2021-07-04 17:41
I have not tried to reproduce this, so I have nothing to do with it

**Comment by Saricane** [comment] 2021-07-05 04:43
Another example on this screenshot (still pre12 on a standard pre11 world, single player,  survival mode)
This wall was made of cobblestone, with one printed block. I just replaced the whole wall with ice. When I restart the game, the ice is printed. You can even notice that the ice block is labelled "Glacier ice with charcoal drawing". I did nothing more complicated.
But I admit this bug is very very nasty. I made tons of tests yesterday, to find a way to reproduce with 100% success, but no way.
It occurs ... when it wants :-)

## Screenshot
![2021-07-05_06-24-58](https://user-images.githubusercontent.com/84909583/124418462-cf066f80-dd5b-11eb-9f0d-c7cf7b320b28.png)

**Comment by radfast** [comment] 2021-07-16 22:54
Off topic, but the art on the Glacier ice looks so cool, perhaps we should allow it.

What I understand from your post is that this is an intermittent issue, which might explain why I am having trouble reproducing it.  I still believe the cause of the issue is that the art is not being removed, server side, when the host block is first destroyed at step 3.  Everything else is an expected consequence of that.

**Comment by radfast** [comment] 2021-07-20 14:12
Issue may not be limited to cave art, see [reported issue with rush matting](https://discord.com/channels/302152934249070593/334233095374897152/866903186785959956)

**Comment by Craluminum2413** [comment] 2021-07-20 14:15
I can't to see this issue in discord, can you just send it here?

**Comment by radfast** [comment] 2021-07-20 14:17
it's OK, the note is more for me :)

The Discord issue is simply that breaking rush matting, sometimes it "comes back" on the same block later.

**Comment by Saricane** [comment] 2021-07-20 18:16
Yes, I just read this issue about rush matting, and may be the origin is the same. I hope this will help you to find the bug.

**Comment by tyronx** [comment] 2021-08-30 11:56
found this today. should be fixed next release 👍

**Closed by tyronx** 2021-08-30 11:56 UTC
Labels: target: survival, status: confirmed, priority: medium, department: code
