### ISSUE TITLE
wrong stacking of firewood in clay oven

### ISSUE THREAD

**Issue by JustForVS** [anegostudios/VintageStory-Issues#2207] opened 2022-09-21 15:15 UTC
**Game Version:** 1.17.4  
**Platform:** Windows 10   
**Modded:** Yes (hudclock-2.8.0, ProspectorInfo-3.2.0, singlepause-1.0.3, ZoomButton1.3.0)  
**SP/MP:** Singleplayer

### Description
After Patch to 1.17.4 firewood is stacked wrong in clay oven, when opening is directing to west or east (see screen shot).
Happens in creative mode, too.

### How to reproduce
1. Make a clay oven
2. Set clay oven with opening directing to west or east (according to world map) and fill it with firewood
3. firewood is stacked wrong

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Paste crash between the triple backticks.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.
```

**Comment by JustForVS** [comment] 2022-09-21 15:17
![Unbenannt](https://user-images.githubusercontent.com/87942616/191543501-a68e6d2e-ac81-4eba-862d-e72b6ac68726.jpg)

**Comment by Saricane** [comment] 2022-09-21 21:16
I can confirm.

**Comment by Zamaky345** [comment] 2022-09-25 16:01
I can confirm this too and ingots are stacking wrong on shelfs too, might be the same problem.

**Comment by Craluminum2413** [comment] 2022-09-25 16:05
@Zamaky345 There is an issue for ingots on shelves #1773

**Comment by Zamaky345** [comment] 2022-09-25 17:21
> @Zamaky345 There is an issue about ingots on shelves #1773

Thanks for letting me know o/

**Comment by Zamaky345** [comment] 2022-09-25 17:22
@Craluminum2413 
thanks for letting me know

**Comment by JustForVS** [comment] 2022-10-27 14:22
Still happens when loading a game and oven was already filled with firewood (not burning).
As soon as firewood is burning, it is stacked correct.

**Comment by kurazarrh** [comment] 2022-11-01 02:51
Can confirm @JustForVS 's comment; stacking logs in the oven appears correctly now, but after closing & reloading a save, the logs face the wrong way, and lighting them on fire corrects the orientation.

**Comment by KxTxLiNn** [comment] 2022-11-04 13:25
Can confirm it's still happening in 1.17.9.

**Comment by Craluminum2413** [comment] 2023-03-05 20:14
Fixed since 1.18.0-pre.1

**Closed by Craluminum2413** 2023-03-05 20:14 UTC
Labels: status: confirmed, department: code
