### ISSUE TITLE
Able to put 8 stacks of items into Shelf

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1888] opened 2022-05-06 10:29 UTC
**Game Version:** 1.16.5
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### How to reproduce
1. Place a shelf
2. Place a chute above
3. Place a chest above the chute
4. Put any shelvable item into the chest (better with very high stacks, e.g. nuggets)
5. It did put 8 stacks inside shelf
6. Break shelf
7. It dropped 8 stacks

### Videos
https://user-images.githubusercontent.com/69315569/167115194-ff76bcd9-eb90-4b07-8e69-c0311526e18f.mp4

**Comment by copygirl** [comment] 2022-05-06 12:38
Thanks for the additional effort but I think these issues are so similar they actually do fit into the same issue.
Closing as duplicate of #1887.

**Closed by copygirl** 2022-05-06 12:38 UTC
Labels: status: duplicate
