### ISSUE TITLE
Can't Save and Quit World without game crash

### ISSUE THREAD

**Issue by Ginko72** [anegostudios/VintageStory-Issues#2502] opened 2023-03-21 21:23 UTC
### Game Version

1.18-pre7

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

While on a long ocean voyage on the raft, attempts to save and exit failed.  Even now that I've returned to my base, I can still not save and quit this world.  Each attempt results in a crash.  On the bright side, the game state does seem to be saved because restarting VS and selecting my world returns me to my last location.

### Logs

```Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.0-pre.7 (Unstable)
3/21/2023 2:17:27 PM: Critical error occurred
Loaded Mods: 
System.NotImplementedException: The method or operation is not implemented.
   at Vintagestory.GameContent.EntityBoat.Dispose() in VSSurvivalMod\Systems\Boats\EntityBoat.cs:line 482
   at Vintagestory.Client.NoObf.ClientEventManager.Dispose() in VintagestoryLib\Client\Util\ClientEventManager.cs:line 556
   at Vintagestory.Client.NoObf.ClientMain.Dispose() in VintagestoryLib\Client\ClientMain.cs:line 2621
   at Vintagestory.Client.NoObf.ClientMain.DestroyGameSession(Boolean gotDisconnected) in VintagestoryLib\Client\ClientMain.cs:line 2536
   at Vintagestory.Client.NoObf.GuiDialogEscapeMenu.OnLeaveWorld() in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogEscapeMenu.cs:line 323
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 304
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\GuiElement.cs:line 677
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 292
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 440
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 564
   at Vintagestory.Client.NoObf.GuiDialogEscapeMenu.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogEscapeMenu.cs:line 388
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 416
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 229
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 808
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1551
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 369
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2/20/2023 9:23:34 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1431080498583360532, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.11.0
P3: 10.0.19045.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\TIMSTO~1\AppData\Local\Temp\RDR7CE2.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7D12.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7D23.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7D40.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7D70.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: cd9d969b-4d9c-4ab2-b14b-6a77f6d76e61
Report Status: 268435456
Hashed bucket: a386333e91cb17c6d3dc38219b0cd414
Cab Guid: 0 }
--------------
{ TimeGenerated = 12/21/2022 11:11:12 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1356069915386531490, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.9.0
P3: 10.0.19045.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\TIMSTO~1\AppData\Local\Temp\RDR5308.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5318.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5358.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER536C.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER53AC.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 0921ee39-e796-4222-ab19-4928f26be2df
Report Status: 268435456
Hashed bucket: b6682851523a865272d1ba673d354ea2
Cab Guid: 0 }
--------------
{ TimeGenerated = 11/2/2022 8:51:54 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: AppHangTransient
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.9.0
P3: 63501532
P4: unknown
P5: unknown
P6: unknown
P7: unknown
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER77BE.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER77CF.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER77DD.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER780D.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: f7ae116c-f7ab-4e2a-8689-166addf5eee8
Report Status: 2049
Hashed bucket: 
Cab Guid: 0 }```

**Comment by Craluminum2413** [comment] 2023-03-21 22:38
Duplicate of #2465

**Closed** 2023-03-22 08:43 UTC
Labels: status: duplicate
