### ISSUE TITLE
Crashes trying to connect to server

### ISSUE THREAD

**Issue by TheCaptain13** [anegostudios/VintageStory-Issues#3661] opened 2024-03-02 19:32 UTC
### Game Version

1.19.4

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Try to connect to the server and it crashes.

### How to reproduce

I press the button to connect and then it crashes for me.

### Logs

Running on 64 bit Windows 10.0.22621.0 with 32665 MB RAM
Game Version: v1.19.4 (Stable)
02/03/2024 19:28:47: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.ShaderAPI.ReloadShaders() in VintagestoryLib\Client\API\ShaderAPI.cs:line 53
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerReady(Packet_Server packet) in VintagestoryLib\Client\Systems\Startup.cs:line 881
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 446
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 440
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 776
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 313
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by reisnersteve** [comment] 2024-03-02 20:11
Can confirm, for me it happens with modded servers before downloading data

`Running on 64 bit Windows 10.0.22631.0 with 32665 MB RAM
Game Version: v1.19.4 (Stable)
02.03.2024 21:11:40: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.ShaderAPI.ReloadShaders() in VintagestoryLib\Client\API\ShaderAPI.cs:line 53
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerReady(Packet_Server packet) in VintagestoryLib\Client\Systems\Startup.cs:line 881
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 776
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 313
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
`

**Comment by Craluminum2413** [comment] 2024-03-02 20:17
What mods are installed?

**Comment by reisnersteve** [comment] 2024-03-02 20:19
I was able to fix it by deleting all mods and the folders - ModsByServer and Mods

**Comment by Craluminum2413** [comment] 2024-03-08 08:26
Duplicate of #3648

**Closed by Craluminum2413** 2024-03-08 08:26 UTC
Labels: status: incomplete
