### ISSUE TITLE
Light sources Light artifacts

### ISSUE THREAD

**Issue by Prinzip** [anegostudios/VintageStory-Issues#2884] opened 2023-07-04 06:28 UTC
### Game Version

1.18.6

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

If you hold a lantern in your hand, the light source is 10x lighter than if you hang it on the wall. This results in a lot of shadows projected with the same lantern on the wall. This should be checked. Attached are pictures with the same lantern.

PS: This happens also with other light sources.

### Screenshots

![2023-07-04_08-21-31](https://github.com/anegostudios/VintageStory-Issues/assets/19502273/da134d9a-2804-407f-9c8b-b600a7138171)
![2023-07-04_08-21-34](https://github.com/anegostudios/VintageStory-Issues/assets/19502273/942f1478-8a2d-4e9d-9f70-23c3dd6856c9)

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2023-07-04 10:27
Duplicate of #2448

**Closed by Craluminum2413** 2023-07-04 10:27 UTC
Labels: status: new
