### ISSUE TITLE
Can't pickup raw unfired cooking pot without breaking it.

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#3539] opened 2024-01-30 02:00 UTC
### Game Version

v1.19.3

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

After making most unfired versions of things, you can pick them up by right clicking with an empty hand. This is not the current case with the unfired cooking pot.

### How to reproduce

Use clay to make cooking pot. Upon finishing, right click with empty hand.

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2024-02-04 09:27
Duplicate of #3532

**Closed by Craluminum2413** 2024-02-04 09:27 UTC
Labels: status: new, department: json
