### ISSUE TITLE
Crash Report "since two days after bought it"

### ISSUE THREAD

**Issue by Enthelexia** [anegostudios/VintageStory-Issues#449] opened 2020-03-06 20:37 UTC
**Game Version:** v1.12.5 (Stable
**Platform:** Windows 10
**Modded:** No 

### Description
Once i get in the main menu, but never was in Game cause the following log in´s crashed

### Logs
```
Running on 64 bit Windows with 64 GB RAM 
Version: v1.12.5 (Stable)06.03.2020 21:27:38: Critical error occurred
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.LoadTexture(IBitmap bmp, Boolean linearMag, Int32 clampMode, Boolean generateMipmaps)
   bei _mKeEWUbBZsjLS6VlGWgOoYQFk2K._KNs6g2GMtsTu5gnL4MXdRgZVlLh()
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._HdDsdRJDH8nMF88r278C4eqdINGA()
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._gjiBClIE7Yspuz65gCqPGSAnUYeb()
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._NbPATb9BXlxRc4ZhH2GgyFCUInp(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _hCuHXesCXlp0LGSdrsPFpw4up5n._mOm8EuKIvHpaJoztxNWRpAoOpbM(_55ISULxdcpPfF8D2JP831aWhOBe , String[] )
   bei _iCfIbY24GyBXP5lAwqsSlD9COxC._mOm8EuKIvHpaJoztxNWRpAoOpbM(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 04.03.2020 23:47:12, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: Ausnahmecode c0020001, Ausnahmeadresse 00007FFD1B06A839
Stapel:
   bei System.Environment._Exit(Int32)
   bei System.Environment._Exit(Int32)
   bei System.Environment.Exit(Int32)
   bei System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   bei OpenTK.NativeWindow.OnClosedInternal(System.Object, System.EventArgs)
   bei System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   bei OpenTK.Platform.Windows.WinGLNative.HandleDestroy(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   bei OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   bei OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   bei OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   bei OpenTK.Platform.Windows.WinGLNative.DestroyWindow()
   bei OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   bei OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   bei OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   bei OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   bei OpenTK.Platform.Windows.Functions.PeekMessage(OpenTK.Platform.Windows.MSG ByRef, IntPtr, Int32, Int32, OpenTK.Platform.Windows.PeekMessageFlags)
   bei OpenTK.Platform.Windows.Functions.PeekMessage(OpenTK.Platform.Windows.MSG ByRef, IntPtr, Int32, Int32, OpenTK.Platform.Windows.PeekMessageFlags)
   bei OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   bei OpenTK.GameWindow.Run(Double, Double)
   bei _hCuHXesCXlp0LGSdrsPFpw4up5n._mOm8EuKIvHpaJoztxNWRpAoOpbM(_55ISULxdcpPfF8D2JP831aWhOBe, System.String[])
   bei _iCfIbY24GyBXP5lAwqsSlD9COxC._mOm8EuKIvHpaJoztxNWRpAoOpbM(System.Threading.ThreadStart)
   bei _hCuHXesCXlp0LGSdrsPFpw4up5n._HDnbZ9U7ok6mEhsXb9UbGfTHtaF(System.String[])
 }

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.

Note that the crash log contains all crashes that have happened so far.
You likely only want to report the latest one.
```
![Unbenannt](https://user-images.githubusercontent.com/61888451/76120843-a6008e00-5ff2-11ea-96b8-5f90238afd8a.jpg)

**Comment by copygirl** [comment] 2020-03-06 20:38
Duplicate of issue #407. This has been fixed for update 1.12.6, which has been out for a while. Please update.

**Closed by copygirl** 2020-03-06 20:38 UTC
Labels: status: duplicate
