### ISSUE TITLE
what means this??

### ISSUE THREAD

**Issue by AleGM2004** [anegostudios/VintageStory-Issues#3952] opened 2024-07-01 13:29 UTC
### Game Version

v1.19.8

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

compré el dia de ayer el juego y estuvé desde las 10am hasta las 4am tratando de descargarlo, pero simplemente no pudé, cada que vez que quiero abrir el juego me aparece una ventana de Crash Reportes con el siguiente texto: Running on 64 bit Windows 10.0.19045.0 with 8092 MB RAM
Game Version: v1.19.8 (Stable)
01/07/2024 3:59:08: Critical error occurred
Loaded Mods: 
OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: WGL: OpenGL profile requested but WGL_ARB_create_context_profile is unavailable
   at OpenTK.Windowing.Desktop.GLFWProvider.DefaultErrorCallback(ErrorCode errorCode, String description)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwCreateWindow(Int32 width, Int32 height, Byte* title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.CreateWindow(Int32 width, Int32 height, String title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.Desktop.NativeWindow..ctor(NativeWindowSettings settings)
   at OpenTK.Windowing.Desktop.GameWindow..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings)
   at Vintagestory.Client.NoObf.GameWindowNative..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings) in VintagestoryLib\Client\ClientPlatform\GameWindowNative.cs:line 14
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 281
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

### Screenshots

![WhatsApp Image 2024-07-01 at 09 25 37](https://github.com/anegostudios/VintageStory-Issues/assets/174280302/47b51a92-12c8-4ed0-a3dd-66ed199c6438)
El primero me aparece siempre que abro "Vintage Story"
![WhatsApp Image 2024-07-01 at 09 25 36](https://github.com/anegostudios/VintageStory-Issues/assets/174280302/0777a719-68e1-461d-9433-f74a634dec7f)
The second one images appears  in "VintageStoryserver"

### Logs

1.7.2024 03:59:08 [Notification] Client logger started.
1.7.2024 03:59:08 [Notification] Game Version: v1.19.8 (Stable)
1.7.2024 03:59:08 [Notification] Process path: C:\Users\user\AppData\Roaming\Vintagestory\Vintagestory.exe
1.7.2024 03:59:08 [Notification] Operating System: Windows 10.0.19045.0
1.7.2024 03:59:08 [Notification] CPU Cores: 4
1.7.2024 03:59:08 [Notification] Available RAM: 8092 MB
1.7.2024 03:59:09 [Fatal] Game Version: v1.19.8 (Stable)
01/07/2024 3:59:08: Critical error occurred
Loaded Mods: 
OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: WGL: OpenGL profile requested but WGL_ARB_create_context_profile is unavailable
   at OpenTK.Windowing.Desktop.GLFWProvider.DefaultErrorCallback(ErrorCode errorCode, String description)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwCreateWindow(Int32 width, Int32 height, Byte* title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.CreateWindow(Int32 width, Int32 height, String title, Monitor* monitor, Window* share)
   at OpenTK.Windowing.Desktop.NativeWindow..ctor(NativeWindowSettings settings)
   at OpenTK.Windowing.Desktop.GameWindow..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings)
   at Vintagestory.Client.NoObf.GameWindowNative..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings) in VintagestoryLib\Client\ClientPlatform\GameWindowNative.cs:line 14
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 281
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
Crash written to file at "C:\Users\user\AppData\Roaming\VintagestoryData\Logs\client-crash.txt"

**Comment by Craluminum2413** [comment] 2024-07-01 14:49
Duplicate of #3950

**Closed by Craluminum2413** 2024-07-01 14:49 UTC
Labels: status: new
