### ISSUE TITLE
Gamecrash on launcher start up

### ISSUE THREAD

**Issue by Thunderbolt101** [anegostudios/VintageStory-Issues#602] opened 2020-10-01 17:13 UTC
**Game Version:** 1.12.5
**Platform:** Windows
**Modded:** No

### Description
Game crashes as soon I double click the game icon.

### How to reproduce
1. Start the game.
2. It crashes.

### Expected behavior
It should have started the game launcher.

### Logs
```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.12.5 (Stable)01.10.2020 19:07:25: Critical error occurred
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.LoadTexture(IBitmap bmp, Boolean linearMag, Int32 clampMode, Boolean generateMipmaps)
   bei _mKeEWUbBZsjLS6VlGWgOoYQFk2K._KNs6g2GMtsTu5gnL4MXdRgZVlLh()
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._HdDsdRJDH8nMF88r278C4eqdINGA()
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._gjiBClIE7Yspuz65gCqPGSAnUYeb()
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._NbPATb9BXlxRc4ZhH2GgyFCUInp(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _hCuHXesCXlp0LGSdrsPFpw4up5n._mOm8EuKIvHpaJoztxNWRpAoOpbM(_55ISULxdcpPfF8D2JP831aWhOBe , String[] )
   bei _iCfIbY24GyBXP5lAwqsSlD9COxC._mOm8EuKIvHpaJoztxNWRpAoOpbM(ThreadStart )
-------------------------------

**Comment by copygirl** [comment] 2020-10-01 17:16
Duplicate of #407.

You're using an old version and the bug has long been fixed. Feel free to check out the workarounds in the linked issue.

**Comment by Thunderbolt101** [comment] 2020-10-01 17:16
Thanks!

**Closed by copygirl** 2020-10-01 17:16 UTC
Labels: status: duplicate
