### ISSUE TITLE
Wood timber framework missing textures

### ISSUE THREAD

**Issue by Xandoria** [anegostudios/VintageStory-Issues#2408] opened 2023-02-28 10:31 UTC
### Game Version

v1.18.0-pre.3

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

The Wood timber framework is missing some textures.

### How to reproduce

Place it in Creative to see.

### Screenshots

![WoodTimberFramework](https://user-images.githubusercontent.com/26251843/221828201-d6b21bd5-9f9e-4483-88ab-4391e4ea9032.png)

### Logs

```Log```

**Comment by RedramVS** [comment] 2023-12-14 02:04
This model was intended to be used in the Resonance archives engineering room.  It was never intended to be player craftable, and so those 'missing' faces were never intended to be exposed.  In the end it was not used in the final iteration of the engineering room.  This block will be transferred to the legacy folder.

**Closed by RedramVS** 2023-12-14 02:04 UTC
Labels: status: new, department: json, version: 1.18
