### ISSUE TITLE
Using Tool Rack forces game crash

### ISSUE THREAD

**Issue by Janxxy** [anegostudios/VintageStory-Issues#687] opened 2020-12-13 08:28 UTC
**Game Version:** 1.14.2
**Platform:** Windows 
**Modded:** No 

### Description
Upon attempting to use tool racks it will force crash the entire game for player. Happened on a server and affected every player the same way

### How to reproduce
1. Obtain tool rack
2. Attempt to place or remove any tool from it
3. Crashes the entire game and brings up crash report

### Expected behavior
We hoped it would just give us our items

### Screenshots
https://gyazo.com/6c6d8ae6bb1c7d1b4a67bb6b887e598d

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.2 (Stable)12/13/2020 1:20:06 AM: Critical error occurred
System.ArgumentException: Cannot render a non-initialized or disposed VAO
   at Vintagestory.Client.NoObf.ClientPlatformWindows.RenderMesh(MeshRef modelRef)
   at Vintagestory.Client.NoObf.ClientMain.RenderTextureIntoFrameBuffer(LoadedTexture fromTexture, Single sourceX, Single sourceY, Single sourceWidth, Single sourceHeight, FrameBufferRef fb, Single targetX, Single targetY, Single alphaTest)
   at Vintagestory.Client.NoObf.ClientMain.RenderTextureIntoTexture(LoadedTexture fromTexture, Single sourceX, Single sourceY, Single sourceWidth, Single sourceHeight, LoadedTexture intoTexture, Single targetX, Single targetY, Single alphaTest)
   at Vintagestory.GameContent.MultiChunkMapComponent.setChunk(Int32 dx, Int32 dz, Int32[] pixels)
   at Vintagestory.GameContent.ChunkMapLayer.<>c__DisplayClass38_0.<loadFromChunkPixels>b__0()
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _uWwiuXC8cGTH1JnsWiUY9FUaXOo._0WtXQJqGAidcdKMfPHF0OxDIauE(Single )
   at _ydpin5JFjepNgd3JOZRb2z5I5Fg._LvRZFcsDWyPwKLB1F2UK7fQ2N6d(Single )
   at _ydpin5JFjepNgd3JOZRb2z5I5Fg._GO2qaUrk9dl0IceTLiA7P4LcpAB(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _Ine8FeGTtDXciSIfaZMHMwCLKGBA._8puLW8J44fiq3A5hthQTfB8WNxc(_SbVlAI6dJIZ4JRt0da0lu23DF14 , String[] )
   at _lErb0L2e9E9htuT2VVnAsXIZqc7A._8puLW8J44fiq3A5hthQTfB8WNxc(ThreadStart )
-------------------------------

**Comment by copygirl** [comment] 2020-12-13 08:37
I've been told this issue can be worked around by disabling the minimap (`F6`).

**Comment by JulianGro** [comment] 2020-12-15 19:49
We have the minimap on, but haven't experienced such a crash. Maybe the rack needs to be visible on the minimap?

**Comment by tyronx** [comment] 2021-06-25 00:57
Duplicate of #873

**Closed by tyronx** 2021-06-25 00:57 UTC
Labels: status: new, target: survival, type: crash
