### ISSUE TITLE
Crush

### ISSUE THREAD

**Issue by Levael** [anegostudios/VintageStory-Issues#2721] opened 2023-05-09 20:52 UTC
### Game Version

v1.18.2-rc.4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Just crash with "out of range exception" while writing in a book

### How to reproduce

I was writing some stuff in a book

### Logs

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.2-rc.4 (Unstable)
5/9/2023 11:48:41 PM: Critical error occurred
Loaded Mods: game@1.18.2-rc.4, creative@1.18.2-rc.4, survival@1.18.2-rc.4
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Vintagestory.GameContent.GuiDialogEditableBook.onTryTextChange(List`1 lines) in VSSurvivalMod\Systems\WritingSystem\GuiDialogEditableBook.cs:line 78
   at Vintagestory.API.Client.GuiElementEditableTextBase.LoadValue(List`1 newLines) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 281
   at Vintagestory.API.Client.GuiElementEditableTextBase.SetValue(String text, Boolean setCaretPosToEnd) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 266
   at Vintagestory.GameContent.GuiDialogReadonlyBook.updatePage(Boolean setCaretPosToEnd) in VSSurvivalMod\Systems\WritingSystem\GuiDialogReadonlyBook.cs:line 174
   at Vintagestory.GameContent.GuiDialogEditableBook.OnKeyDown(KeyEvent args) in VSSurvivalMod\Systems\WritingSystem\GuiDialogEditableBook.cs:line 239
   at Vintagestory.Client.NoObf.GuiManager.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 361
   at Vintagestory.Client.NoObf.ClientMain.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1738
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(Object sender, KeyboardKeyEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 250
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.NativeWindowBase.OnKeyDown(Key key, Boolean repeat) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\NativeWindowBase.cs:line 130
   at OpenTK.Platform.Windows.WinGLNative.HandleKeyboard(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 646
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 828
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1551
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 369
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 5/8/2023 1:24:26 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2068211042396813861, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.2.0
P3: 64562762
P4: atio6axx.dll
P5: 31.0.14051.5006
P6: 64419890
P7: c0000005
P8: 0000000000c5ae6f
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA76C.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERABA3.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERABB4.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERABC5.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERABF5.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_4f94772607d51b244b1183ef3944c34ec99f3c_f4b25888_9714191f-3c61-448e-85da-805d40dbceb4

Analysis symbol: 
Rechecking for solution: 0
Report Id: face1012-c36c-482b-8b7a-682dd8d91f7b
Report Status: 268435456
Hashed bucket: ff5af859d52c04eeacb3c2fc369a3a25
Cab Guid: 0 }
--------------
{ TimeGenerated = 5/8/2023 1:24:23 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.2.0, time stamp: 0x64562762
Faulting module name: atio6axx.dll, version: 31.0.14051.5006, time stamp: 0x64419890
Exception code: 0xc0000005
Fault offset: 0x0000000000c5ae6f
Faulting process id: 0x4108
Faulting application start time: 0x01d98132536b7c66
Faulting application path: D:\Games\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\DriverStore\FileRepository\u0391252.inf_amd64_b298c070ddf486e2\B391109\atio6axx.dll
Report Id: face1012-c36c-482b-8b7a-682dd8d91f7b
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 5/8/2023 1:24:22 AM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FFDAC1EAE6F
 }

**Comment by radfast** [comment] 2023-05-10 06:53
Duplicate of #2572.  Will be resolved in upcoming 1.18.2 in the next few days, until then please don't move the cursor to the right when it is already at the end of a book.

**Closed by radfast** 2023-05-10 06:53 UTC
Labels: status: new
