### ISSUE TITLE
pit kiln crash

### ISSUE THREAD

**Issue by morawa93** [anegostudios/VintageStory-Issues#1123] opened 2021-07-08 12:11 UTC
**Game Version:** 1.15.0 rc.1
**Platform:** Windows  
**Modded:** No   

### Description
Explain the issue you're running into.

### How to reproduce
1. Make a pit kiln 
2. Use it on molds
3. It crashes when you leave the server and right click it 

### Expected behavior
crashing

### Screenshots
![image](https://user-images.githubusercontent.com/87130001/124919268-5111c500-dff6-11eb-9c6d-63157d2bd845.png)

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.0-rc.1 (Unstable)7/8/2021 2:04:57 PM: Critical error occurred
System.NullReferenceException: Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
   w Vintagestory.GameContent.BlockEntityGroundStorage.DetermineStorageProperties(ItemSlot sourceSlot)
   w Vintagestory.GameContent.BlockEntityGroundStorage.OnPlayerInteract(IPlayer player, BlockSelection bs)
   w Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Block selectedBlock, BlockSelection blockSelection)
   w Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   w Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   w Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   w Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   w Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   w _Hhyykp3OIyR3A9gDXvfRYXmIxHM._kL6wH0r9p9pVrlTOg8ZqnOfBCeq(Single )
   w _GatfFd3kn5xATuUyKYscxn8d0CO._4TEOzZagWNPjzZVqfu2HCwbLFqC(Single )
   w _GatfFd3kn5xATuUyKYscxn8d0CO._x3D81oTSuYvhXUwgP6x9PwySgdc(Single )
   w Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   w System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   w OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   w OpenTK.GameWindow.DispatchRenderFrame()
   w OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   w _woe4UEAalnRbwPXBTK09ZhdFcWO._5qgAk5LLuTcbcRWXQsq1b3Y8T8H(_arFvNaodTjXO5ObZ7eEgimkezLG , String[] )
   w _ZFpbvq06JtO6suJqmLDa8Hs9YeH._5qgAk5LLuTcbcRWXQsq1b3Y8T8H(ThreadStart )
-------------------------------

```

**Comment by Craluminum2413** [comment] 2021-07-08 12:20
Duplicate of #1111?

**Comment by tyronx** [comment] 2021-07-08 13:13
argh, i removed debug code in the end, but also removed required code 🤦 
fixed in rc.2

**Closed by tyronx** 2021-07-08 13:13 UTC
Labels: status: new
