### ISSUE TITLE
Handbook displays wrong "storable in" section

### ISSUE THREAD

**Issue by tels-git** [anegostudios/VintageStory-Issues#2281] opened 2022-11-07 11:17 UTC
### Game Version

v1.17.9

### Platform

Linux

### Modded

Modded

### Description

Attributes like these:

```
        "attributes": {
                "inContainerTexture": { "base": "em:item/resource/ash/{category}/incontainer/{type}" },
                "displaycaseable": false,
                "shelvable": false,
                "onDisplayTransform": {
                        "translation": { "x": 0.05, "y": 0, "z": 0 },
                        "origin": { "x": 0.5, "y": 0, "z": 0.5 },
                        "scale": 0.65
                }
        },
        "attributesByType": {
                "ash-organic-plant": {
                        "displaycaseable": true,
                        "shelvable": true
                },
                "ash-organic-wood": {
                        "displaycaseable": true,
                        "shelvable": true
                }
        },
```

cause the "sludge" to still say it can be stored on a shelf, despite that it actually cannot be stored there. Moving the displayTransform to individual attributes does not fix this, either.

### How to reproduce

See JSON code below.

### Screenshots

![display_case](https://user-images.githubusercontent.com/29096965/200297451-8cc3d8b9-8326-4e38-9f13-33417d698dc4.jpg)

### Logs

```
{
        "code": "ash",
	"enabled": false,
	"variantgroups": [
		{ "code": "category", "states": [
			"organic"
		] },
		{ "code": "type", "states": [
			"plant",
			"wood",
			"sludge"
		] }
	],
	"attributes": {
		"inContainerTexture": { "base": "em:item/resource/ash/{category}/incontainer/{type}" },
		"displaycaseable": false,
		"shelvable": false,
		"onDisplayTransform": {
			"translation": { "x": 0.05, "y": 0, "z": 0 },
			"origin": { "x": 0.5, "y": 0, "z": 0.5 },
			"scale": 0.65
		}
	},
	"attributesByType": {
		"ash-organic-*": {
			"handbook": { "extraSections": [ { "title": "handbook-item-usage", "text": "handbook-item-usage-ash-{category}-{type}" } ] }
		},
		"ash-organic-plant": {
			"displaycaseable": true,
			"shelvable": true
		},
		"ash-organic-wood": {
			"displaycaseable": true,
			"shelvable": true
		}
	},
	"combustiblePropsByType": {
		"ash-organic-sludge": {
			"meltingPoint": 600,
			"meltingDuration": 35,
			"smeltedRatio": 2,
			"smeltingType": "convert",
			"smeltedStack": { "type": "item", "code": "game:potash", "stacksize": 1 },
			"requiresContainer": false
		}
	},
	"replaceable": 900,
	"resistance": 1,
	"emitSideAo": { "all": false },
	"texturesByType": {
		"*": { "all": { "base": "em:item/resource/ash/{category}/{type}" } }
	},
        "shapeByType": {
		"*": { "base": "em:item/resource/powdered" }
	},
        "creativeinventoryByType": {
		"*": { "general": ["*"], "items": ["*"] }
	},
        "maxstacksize": 64,
        "materialDensity": 500,
	"heldTpIdleAnimation": "holdbothhands",
	"tpHandTransform": {
		"translation": { "x": -1.67, "y": -1.25, "z": -0.8 },
		"rotation": { "x": 70, "y": 11, "z": -65 },
		"scale": 0.41
        },
        "fpHandTransform": {
		"translation": { "x": 0, "y": 0, "z": 0.15 },
		"rotation": { "x": -170, "y": 90, "z": -172 },
		"scale": 1.4
        },
	"guiTransform": {
		"translation": { "x": -2, "y": 1, "z": -25 },
                "rotation": { "x": 158, "y": 28, "z": 3 },
		"origin": { "x": 0.29, "y": -0.05, "z": 0.8 },
		"scale": 2.5
        }
}
```

**Comment by Craluminum2413** [comment] 2022-11-07 17:30
Seems like intended feature since [1.16.0 update](https://www.vintagestory.at/forums/topic/6214-homesteading-part-2-combat-update-stable-1160/#comment-30050:~:text=Feature%3A%20*byType%20precedence%3A%20For%20the%20Json%20assets%20blocktype%2C%20itemtype%20and%20entitytype%2C%20can%20now%20define%20an%20attribute%20as%20well%20as%20a%20*byType%20attribute%2C%20whereas%20the%20latter%20takes%20precedence%2C%20e.g.%20stackSize%3A%2032%20would%20be%20overwritten%20by%20stackSizeByType%3A%20%7B%20%22*%22%3A%2016%20%7D)

"Feature: *byType precedence: For the Json assets blocktype, itemtype and entitytype, can now define an attribute as well as a *byType attribute, whereas the latter takes precedence, e.g. stackSize: 32 would be overwritten by stackSizeByType: { "*": 16 }"

**Comment by Craluminum2413** [comment] 2022-11-07 17:33
Also, the wildcard should always be at the end, for example:
```json
	"attributesByType": {
		"ash-organic-plant": {
			"displaycaseable": true,
			"shelvable": true
		},
		"ash-organic-wood": {
			"displaycaseable": true,
			"shelvable": true
		},
		"ash-organic-*": {
			"handbook": { "extraSections": [ { "title": "handbook-item-usage", "text": "handbook-item-usage-ash-{category}-{type}" } ] }
		}
	},
```

**Comment by tels-git** [comment] 2022-12-09 16:21
`Seems like intended feature since 1.16.0 update` 

No, this is NOT an intended feature. The "feature intention" is that ByType overrides respectively *adds* to the attributes.

And if you read the JSON and the bug report carefully, you will see that:

* attributes defines false for **all types**
* attributesByType selectively enables it for a certain type

Despite that, the handbook still says the item where the storable was NOT activated, that the item can be stored there. If you try it in game, you can see you cannot store the item in a display case (which is correct), but the handbook says you can (which is wrong).

As for the "*" at the end - this makes no difference in this bug report.

**Comment by Craluminum2413** [comment] 2022-12-09 20:26
What will happen if you remove `"ash-organic-*"` from `attributesByType`? Just wondering

**Comment by tyronx** [comment] 2023-01-09 08:40
The asset loader is not designed to support multiple definitions of the same property, i.e. `attributes` and `attributesByType`. 
The suggested fix by @Craluminum2413 should work. If it doesn't please upload a minimalistic mod zip that reproduces the issue.

**Comment by tels-git** [comment] 2023-01-23 13:08
I don't quite understand your msg, Tyron:

* what exactly is the suggested fix by Craluminum2413?
* I'm unsure what the asset loader has to do with this issue, as clear *some* parts of the game (the actualy doing) get the meaning right, and some don't (the handbook).

Either the asset loader loads it correct, then it should work in both cases, or it doesn't, then it wouldn't work in game and in handbook:

> Despite that, the handbook still says the item where the storable was NOT activated, that the item can be stored there. If you try it in game, you can see you cannot store the item in a display case (which is correct), but the handbook says you can (which is wrong).

**Comment by tels-git** [comment] 2023-01-23 13:26
Here is a small testmod. Load it, spawn wood ash, plant ash and ash sludge.

You will see  that ash sludge in the handbook says it can be stored in shelves, but it cannot actually be stored, which is correct. The handbook info is simply wrong.

I have so far not found a way to set the attributes so that the handbook is correct and the storage is also correct. (sludge should not be able to be displayed or stored on shelves)

[storabletest-0.0.1.zip](https://github.com/anegostudios/VintageStory-Issues/files/10480110/storabletest-0.0.1.zip)

![issue_2281_storing_ash](https://user-images.githubusercontent.com/29096965/214050910-cce5545b-0db5-453d-80ff-4c9040659413.jpg)

![issue_2281_storing_ash_2](https://user-images.githubusercontent.com/29096965/214050925-f06ad291-c1ef-4aab-bb87-6cce443da301.jpg)

**Comment by tyronx** [comment] 2023-01-23 16:44
Sorry my bad, ignore what I wrote earlier. I can reproduce the problem. Will be fixed next releasem thanks for the report, a workaround is to delete `"displaycaseable": false,` and `"shelvable": false,`

**Closed by tyronx** 2023-01-23 16:44 UTC
Labels: status: incomplete
