### ISSUE TITLE
Creating New  World from Existing Seed Crash

### ISSUE THREAD

**Issue by nskjellum** [anegostudios/VintageStory-Issues#824] opened 2021-03-25 01:47 UTC
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.8 (Stable)3/24/2021 8:45:38 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at _PW8NVVq6wBR9krMQ9GulRnv6PMD._h9K0G4wbrt2CCpt5A92lCnKV2gP()
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   at _oDnqPT3M9pq9hNGZM4RDtA6RTnG._TE0ypoo5kb57Ue2gLv7daIuY6VD(MouseEvent )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _YrS2W1MoaeqC4xqH8ItdZB6vADN._8t1BmEWVlCT9mjx5M0vFIzU9tif(_7T00Rjby4si0wyEBez5dXNqLm7h , String[] )
   at _ejKuc6cg0k8V39o8jDIzquyczbO._8t1BmEWVlCT9mjx5M0vFIzU9tif(ThreadStart )
-------------------------------

**Comment by copygirl** [comment] 2021-03-25 06:32
Duplicate of #795.

**Closed by copygirl** 2021-03-25 06:32 UTC
Labels: status: duplicate
