### ISSUE TITLE
Issue joining friends LAN game.

### ISSUE THREAD

**Issue by MLM9295** [anegostudios/VintageStory-Issues#2060] opened 2022-07-28 17:16 UTC
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.0-rc.2 (Unstable)
Loaded Mods: game@1.17.0-rc.2, creative@1.17.0-rc.2, survival@1.17.0-rc.2
7/28/2022 1:12:22 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.ClientMain.ProcessServerReady() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:line 1923
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:line 1138
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 381
   at Vintagestory.Client.ScreenManager.Render(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:line 704
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:line 608
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 125
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 87
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 7/28/2022 10:29:09 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2073705085795641004, type 5
Event Name: BEX64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.0.0
P3: 62e01e15
P4: nvoglv64.dll
P5: 30.0.15.1278
P6: 62731fe9
P7: 0000000001270305
P8: c0000409
P9: 0000000000000007
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER87F9.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_a06032577a3aa74ff76a064635d3211e52eab99_30d1a8e0_975131b9-2598-42d3-bb46-89e71c6ff55d

Analysis symbol: 
Rechecking for solution: 0
Report Id: c0ef89fe-5338-4cc7-af62-d49a7a9647a3
Report Status: 268435456
Hashed bucket: cbae9074da5f00c15cc747c9dfc526ac
Cab Guid: 0 }
--------------
{ TimeGenerated = 7/28/2022 10:29:07 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: BEX64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.0.0
P3: 62e01e15
P4: nvoglv64.dll
P5: 30.0.15.1278
P6: 62731fe9
P7: 0000000001270305
P8: c0000409
P9: 0000000000000007
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_a06032577a3aa74ff76a064635d3211e52eab99_30d1a8e0_975131b9-2598-42d3-bb46-89e71c6ff55d

Analysis symbol: 
Rechecking for solution: 0
Report Id: c0ef89fe-5338-4cc7-af62-d49a7a9647a3
Report Status: 4
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 7/28/2022 10:29:06 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.17.0.0, time stamp: 0x62e01e15
Faulting module name: nvoglv64.dll, version: 30.0.15.1278, time stamp: 0x62731fe9
Exception code: 0xc0000409
Fault offset: 0x0000000001270305
Faulting process id: 0x2c04
Faulting application start time: 0x01d8a28e2eba90dc
Faulting application path: C:\Users\Magan\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\DriverStore\FileRepository\nvhm.inf_amd64_4a2f8a62d5686839\nvoglv64.dll
Report Id: c0ef89fe-5338-4cc7-af62-d49a7a9647a3
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Cruors** [comment] 2022-07-28 17:29
We also failed with internet game and we are using the same internet right now but it worked while she was in another country, i have the port forwarded and firewall isn't blocking anything.

**Comment by Cruors** [comment] 2022-07-29 13:07
Stable branch works perfectly fine.

**Comment by Saricane** [comment] 2022-07-29 15:13
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/2054#issue-1318968596

**Closed** 2022-07-29 15:27 UTC
Labels: status: new
