### ISSUE TITLE
Random Crash while Harvesting mushrooms

### ISSUE THREAD

**Issue by OGMelchon** [anegostudios/VintageStory-Issues#3547] opened 2024-02-02 14:54 UTC
### Game Version

1.19.3

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Crashed While Harvesting mushrooms and now the world wont load

### Logs

Game Version: v1.19.3 (Stable)
2/2/2024 4:49:00 μμ: Critical error occurred
Loaded Mods: game@1.19.3, creative@1.19.3, survival@1.19.3
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockRockTyped.getRockType(String type) in VSSurvivalMod\Block\BlockRockTyped.cs:line 121
   at Vintagestory.GameContent.BlockRockTyped.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VSSurvivalMod\Block\BlockRockTyped.cs:line 104
   at Vintagestory.API.Common.ItemStack.GetDescription(IWorldAccessor world, ItemSlot inSlot, Boolean debug) in VintagestoryApi\Common\Collectible\ItemStack.cs:line 401
   at Vintagestory.API.Client.ItemstackComponentBase.OnRequireInfoText(ItemSlot slot) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\ItemstackComponentBase.cs:line 62
   at Vintagestory.API.Client.SlideshowItemstackTextComponent.OnRequireInfoText(ItemSlot slot) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\SlideshowItemstackTextComponent.cs:line 178
   at Vintagestory.API.Client.GuiElementItemstackInfo.AsyncRecompose() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementItemstackInfo.cs:line 142
   at Vintagestory.API.Client.GuiElementItemstackInfo.SetSourceSlot(ItemSlot nowSlot, Boolean forceRecompose) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementItemstackInfo.cs:line 252
   at Vintagestory.API.Client.ItemstackComponentBase.RenderItemstackTooltip(ItemSlot slot, Double renderX, Double renderY, Single dt) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\ItemstackComponentBase.cs:line 79
   at Vintagestory.API.Client.GuiElementRichtext.RenderInteractiveElements(Single deltaTime) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementRichtext.cs:line 472
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime) in VintagestoryApi\Client\UI\GuiComposer.cs:line 716
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 384
   at Vintagestory.GameContent.GuiDialogHandbook.OnRenderGUI(Single deltaTime) in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 493
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 318
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1006
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 675
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 650
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
Game Version: v1.19.3 (Stable)
2/2/2024 4:49:50 μμ: Critical error occurred
Loaded Mods: game@1.19.3, creative@1.19.3, survival@1.19.3
Newtonsoft.Json.JsonReaderException: Failed deserializing rockstrata.json: Unexpected character encountered while parsing value: �. Path '', line 0, position 0.
   at Vintagestory.Common.Asset.ToObject[T](JsonSerializerSettings settings) in VintagestoryLib\Common\Model\Asset.cs:line 65
   at Vintagestory.ServerMods.GenRockStrataNew.initWorldGen(Int32 seedDiff) in VSSurvivalMod\Systems\WorldGen\Standard\ChunkGen\2.GenRockStrata\GenRockStrata.cs:line 63
   at Vintagestory.ServerMods.GenRockStrataNew.initWorldGen() in VSSurvivalMod\Systems\WorldGen\Standard\ChunkGen\2.GenRockStrata\GenRockStrata.cs:line 57
   at Vintagestory.GameContent.ProPickWorkSpace.<>c__DisplayClass5_0.<OnLoaded>b__0() in VSSurvivalMod\Systems\Prospecting\ProPickWorkSpace.cs:line 34
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 120
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Comment by Craluminum2413** [comment] 2024-02-05 21:21
Duplicate of #3560

**Closed by Craluminum2413** 2024-02-05 21:21 UTC
Labels: status: duplicate
