### ISSUE TITLE
Throwing spear crashes game

### ISSUE THREAD

**Issue by JoIamar** [anegostudios/VintageStory-Issues#1014] opened 2021-06-16 05:51 UTC
**Game Version:** 1.15-pre.3
**Platform:** Windows
**Modded:** No

### Description
When trying to throw a spear, instead, it crashes my game.

### How to reproduce
Presumably a low durability spear
Throw at anything

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Unable to get a screenshot.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.0-pre.3 (Unstable)6/16/2021 12:39:29 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.CollectibleObject.<>c__DisplayClass70_0.<RefillSlotIfEmpty>b__0(ItemSlot invslot)
   at Vintagestory.API.Common.EntityPlayer.WalkInventory(OnInventorySlot handler)
   at Vintagestory.API.Common.CollectibleObject.DamageItem(IWorldAccessor world, Entity byEntity, ItemSlot itemslot, Int32 amount)
   at Vintagestory.GameContent.ItemSpear.OnHeldInteractStop(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _kG3l18Uo58XQnaOroOTVL156lmd._xkDAOmiQFj0Igekk6xBOkfLlbV2(Single )
   at _myXzIvBGuHgNhKsWypGDvkNbw4X._PeuIqQzFn7JdsiaCMO1A0nOHYOF(Single )
   at _myXzIvBGuHgNhKsWypGDvkNbw4X._12elMOUbssfuqzUtVoRc599RYNW(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _UwTpwIUKuzIrz4lc7aDEDr1w32f._ouD1c39oCQ2Eda0lkC3EXYeZtC7(_OdfjAwaG2wGU12XuYVt4myQv5bF , String[] )
   at _j9Ke4RlHC2L45ChATqqx7RI91CC._ouD1c39oCQ2Eda0lkC3EXYeZtC7(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 6/14/2021 11:39:18 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1252239485250825062, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.0.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\SAVAGE~1\AppData\Local\Temp\RDR346F.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3470.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3480.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3485.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER34B5.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: b5c1bc43-8885-473b-87c7-d49792f2a55a
Report Status: 268435456
Hashed bucket: 9a6d16c7ad62a31db160d92d5c17eb66
Cab Guid: 0 }

**Comment by copygirl** [comment] 2021-06-16 06:41
Duplicate of #944.

**Closed by copygirl** 2021-06-16 06:41 UTC
Labels: status: duplicate
