### ISSUE TITLE
Entities are not displayed (mobs, open chests, etc.)

### ISSUE THREAD

**Issue by arsenijpavlov** [anegostudios/VintageStory-Issues#2287] opened 2022-11-12 16:12 UTC
### Game Version

v1.17.4+

### Platform

Windows

### Modded

Vanilla

### Description

The problem is observed on new versions starting from v.1.17.4.
I checked options with updating and clean installation for a new version.
I tried to start a new world in the new version.
Did not help.

### How to reproduce

Perhaps the problem is related to the weak characteristics of the video card (a laptop Lenovo b50-30, without a discrete video card, is built into the processor), and in new versions the entity rendering mechanism has been changed.

### Screenshots

![image](https://user-images.githubusercontent.com/43166722/201482783-3a6e7736-4649-44f4-bc06-af6e7e7105fc.png)
![image](https://user-images.githubusercontent.com/43166722/201483540-c862562f-0777-4331-9f87-22a1533e6113.png)

### Logs

```Log```
[server-audit.txt](https://github.com/anegostudios/VintageStory-Issues/files/9995353/server-audit.txt)
[server-build.txt](https://github.com/anegostudios/VintageStory-Issues/files/9995354/server-build.txt)
[server-chat.txt](https://github.com/anegostudios/VintageStory-Issues/files/9995355/server-chat.txt)
[server-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/9995356/server-crash.txt)
[server-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/9995357/server-debug.txt)
[server-event.txt](https://github.com/anegostudios/VintageStory-Issues/files/9995358/server-event.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/9995359/server-main.txt)
[server-storyevent.txt](https://github.com/anegostudios/VintageStory-Issues/files/9995360/server-storyevent.txt)
[client-audit.txt](https://github.com/anegostudios/VintageStory-Issues/files/9995361/client-audit.txt)
[client-chat.txt](https://github.com/anegostudios/VintageStory-Issues/files/9995362/client-chat.txt)
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/9995363/client-crash.txt)
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/9995364/client-debug.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/9995365/client-main.txt)

**Comment by arsenijpavlov** [comment] 2022-11-14 07:25
Looked, it turns out this is already a duplicate of this report https://github.com/anegostudios/VintageStory-Issues/issues/2277

**Comment by Craluminum2413** [comment] 2022-11-14 11:18
Isn't there should be same crash to close it as duplicate?

**Comment by arsenijpavlov** [comment] 2022-11-14 11:45
I think these bugs have a common origin.
client-main.txt: [Error] after final compo   - OpenGL threw an error: InvalidOperationEnable Gl Debug Mode in the settings or clientsettings.json to track this error

**Comment by tyronx** [comment] 2022-11-20 18:47
this is a duplicate of #2277

**Closed by tyronx** 2022-11-20 18:47 UTC
Labels: status: new
