### ISSUE TITLE
Crashes when making small troughs with maple boards

### ISSUE THREAD

**Issue by rEverKlENd** [anegostudios/VintageStory-Issues#2189] opened 2022-09-11 20:15 UTC
**Game Version:** 1.17.3
**Platform:** Windows 
**Modded:** No 
**SP/MP:** Multiplayer 

### Description
Twice I tried to make troughs using maple boards. I was planning to make two, so I put double the amount into the slots, and then when I took the trough out, the game crashed and closed completely. I tried again, and the game logged me out of the server but did not close completely. When I logged back in, a small trough was on the ground. I was then able to make a second one with no problems.

### How to reproduce
See the description. I have no idea if you'll be able to reproduce it. 

### Expected behavior
I expected to be able to make the troughs with no issues. 

### Screenshots
Sorry, I didn't take any. 

### Logs
```
Running on 64 bit Windows with 8 GB RAM 
Game Version: v1.17.3 (Stable)
9/10/2022 10:20:09 PM: Critical error occurred
Loaded Mods: game@1.17.3, creative@1.17.3, survival@1.17.3
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Common.ItemSlotCraftingOutput.TryPutInto(ItemSlot sinkSlot, ItemStackMoveOperation& op) in VintagestoryLib\Common\GameContent\Inventory\ItemSlotCraftingOutput.cs:line 40
   at Vintagestory.API.Common.ItemSlotOutput.ActivateSlot(ItemSlot sourceSlot, ItemStackMoveOperation& op) in VintagestoryApi\Common\Inventory\ItemSlotOutput.cs:line 39
   at Vintagestory.API.Common.InventoryBase.ActivateSlot(Int32 slotId, ItemSlot sourceSlot, ItemStackMoveOperation& op) in VintagestoryApi\Common\Inventory\InventoryBase.cs:line 448
   at Vintagestory.Common.InventoryCraftingGrid.ActivateSlot(Int32 slotId, ItemSlot sourceSlot, ItemStackMoveOperation& op) in VintagestoryLib\Common\GameContent\Inventory\InventoryCraftingGrid.cs:line 112
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.SlotClick(ICoreClientAPI api, Int32 slotId, EnumMouseButton mouseButton, Boolean shiftPressed, Boolean ctrlPressed, Boolean altPressed) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 979
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseDownOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 772
   at Vintagestory.API.Client.GuiElement.OnMouseDown(ICoreClientAPI api, MouseEvent mouse) in VintagestoryApi\Client\UI\Elements\Impl\GuiElement.cs:line 638
   at Vintagestory.API.Client.GuiComposer.OnMouseDown(MouseEvent mouseArgs) in VintagestoryApi\Client\UI\GuiComposer.cs:line 459
   at Vintagestory.Client.NoObf.GuiDialogInventory.OnMouseDown(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogInventory.cs:line 546
   at Vintagestory.Client.NoObf.GuiManager.OnMouseDown(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 394
   at Vintagestory.Client.NoObf.ClientMain.OnMouseDown(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 2251
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonDown(Object sender, MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 220
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 792
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1554
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 368
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 9/8/2022 9:05:42 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1578939304548704450, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.2.0
P3: 63120498
P4: StackHash_0000
P5: 0.0.0.0
P6: 00000000
P7: 00000000
P8: PCH_84
P9: 
P10: 

Attached files:
\\?\C:\Users\C\AppData\Local\Temp\WER154F.tmp.WERDataCollectionStatus.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER250F.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER254E.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER254B.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER259B.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_459823c9e6e329de3284da66939c9c8544168_84fbe18f_6dc37d78-5c62-4aba-af49-8980990b35e6

Analysis symbol: 
Rechecking for solution: 0
Report Id: 163c942e-53af-4a27-bc9a-bc10c017b911
Report Status: 268566528
Hashed bucket: c1b813d6cf6fe5d0f5e984ee918720c2
Cab Guid: 0 }
--------------
{ TimeGenerated = 9/8/2022 9:05:35 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.17.2.0, time stamp: 0x63120498
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0x00000000
Fault offset: 0x0000000000000000
Faulting process id: 0x4c90
Faulting application start time: 0x01d8c3e4e4414397
Faulting application path: C:\Games\Vintagestory\Vintagestory.exe
Faulting module path: unknown
Report Id: 163c942e-53af-4a27-bc9a-bc10c017b911
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 9/8/2022 9:05:34 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FF8DFC84FD9
Stack:
   at System.Environment._Exit(Int32)
   at System.Environment._Exit(Int32)
   at System.Environment.Exit(Int32)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.NativeWindow.OnClosedInternal(System.Object, System.EventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.Platform.Windows.WinGLNative.HandleDestroy(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   at OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.DestroyWindow()
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(OpenTK.Platform.Windows.MSG ByRef)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(OpenTK.Platform.Windows.MSG ByRef)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double, Double)
   at Vintagestory.Client.ClientProgram.Start(Vintagestory.Client.ClientProgramArgs, System.String[])
   at Vintagestory.ClientNative.CrashReporter.Start(System.Threading.ThreadStart)
   at Vintagestory.Client.ClientProgram.Main(System.String[])
 }
```

**Comment by tyronx** [comment] 2022-09-12 11:19
hm, can't reproduce it unfortunately

**Comment by Craluminum2413** [comment] 2022-09-12 11:29
Duplicate of #2116

**Comment by Craluminum2413** [comment] 2022-09-12 11:31
Oh wait I haven't noticed that it was a comment

**Comment by Craluminum2413** [comment] 2022-09-12 11:31
This comment has reproduce steps
<https://github.com/anegostudios/VintageStory-Issues/issues/2116#issuecomment-1220623617>

**Comment by tyronx** [comment] 2022-09-20 10:38
duplicate report

**Closed by tyronx** 2022-09-20 10:38 UTC
Labels: status: new
