### ISSUE TITLE
Shields break on 1.17.1 update

### ISSUE THREAD

**Issue by nepnepneptunes** [anegostudios/VintageStory-Issues#2149] opened 2022-09-01 15:54 UTC
**Game Version:** 1.17.1
**Platform:** Windows  
**Modded:** No 
**SP/MP:** Singleplayer

### Description
My reinforced shield became a white square when I updated, so did the wooden shields in my chest.
I saw that someone else had an issue in the rc update and it went unresolved.
Annoying
The shield was damaged if that makes a difference (But who has a full health shield?)

### How to reproduce
1. Make a shield on 1.16 (I think any kind works)
2. Update it to 1.17
3. It turns into a white square

### Expected behavior
I expected it to not become a white square

### Screenshots
![2022-09-01_11-51-42](https://user-images.githubusercontent.com/57899808/187958245-faa40832-7e26-4c08-b640-9388951447c7.png)
![2022-09-01_11-35-41](https://user-images.githubusercontent.com/57899808/187958259-17a55af6-114f-4bc6-a41d-88d121c2f240.png)

### Logs
```
Didn't crash, first time I'm using github, so idk if I should delete this part or not
```

**Comment by daretmavi** [comment] 2022-09-04 12:38
See #2057

**Comment by Craluminum2413** [comment] 2022-09-04 13:30
Duplicate of #2057

**Closed by Craluminum2413** 2022-09-04 13:30 UTC
Labels: status: new
