### ISSUE TITLE
2 block tall leaning items, leaning on 1 block

### ISSUE THREAD

**Issue by Spidereggs** [anegostudios/VintageStory-Issues#3882] opened 2024-05-17 18:31 UTC
### Game Version

v.1.19.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

If you lean a 1 tall block tool on a block you can place a 2 block tall tool next to it, making it lean against the air. Also works the other way around by only placing the top block the (for example) shovel is leaning on, making your chisel float

### How to reproduce

Get a shovel and shears and lean the shears on the block first. Now place the shovel and it leans against the air. Must place shears first, otherwise it wont work.
Same way the other way around. Place a 2 block high wall and mine the bottom block, then place the shovel and afterwards the shears. Shears just lean against the air. Trying to place the shears first wont get you an error message, as intended

### Screenshots

![leaning](https://github.com/anegostudios/VintageStory-Issues/assets/61431518/a8964ec0-5f07-4c62-9011-c58fecfb91ac)

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2024-05-17 18:50
Duplicate of #1937

**Closed by Craluminum2413** 2024-05-17 18:50 UTC
Labels: status: new
