### ISSUE TITLE
No information in-game about changing the glass on the lantern.

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1122] opened 2021-07-08 09:30 UTC
**Game Version:** 1.15.0-rc.1
**Platform:** Windows
**Modded:** StepUp

### Description
If the lantern is originally made of `clear quartz`, you don't get it after replacing with the glass block

### How to reproduce
1. Craft a lantern, using any metal plate, `clear quartz` and candles
2. Place the lantern
3. Right-click on it while holding any glass block
4. You didn't get `clear quartz` back

### Expected behavior
Return previous items back

### Videos

https://user-images.githubusercontent.com/69315569/124897819-54ea1b00-dfe7-11eb-9531-1e726cf0bb33.mp4

**Comment by Craluminum2413** [comment] 2021-07-08 09:31
Just noticed that there is no tooltip that you can replace the glass on the lantern at all

**Comment by sirStroam** [comment] 2021-07-12 02:04
The lantern doesn't return any ingredients when the glass is changed. I'm not sure that is a bug. No information about changing the glass qualifies.

**Comment by Craluminum2413** [comment] 2021-07-12 10:02
The resources obtained by blood and sweat... I think it should always return items, no matter what it is

**Comment by Craluminum2413** [comment] 2021-07-12 14:10
I meant to display this all as tooltips when you aiming on the lantern. As it is much easier and faster than translating the handbook

**Comment by radfast** [comment] 2021-07-12 17:52
I've looked at the code, it has been intentionally coded not to return the quartz - in contrast, other types of glass should be returned.  I don't know why it is coded this way, it was before my time.  I'll raise it at the next suitable dev team discussion.

If that is the intended behavior then I agree it needs to be documented in-game.  But until we know for sure that that is the intended behavior, it's not worth spending time on the documentation aspect yet...

**Comment by tyronx** [comment] 2021-07-13 09:25
Its kinda intended yea, i see the colored glass as an overlay over the quartz window

@sirStroam you do get the glass back, but you need to be in survival mode

**Comment by RedramVS** [comment] 2022-06-29 14:40
Added additional text to handbook entry.  Note that if the lantern already has glass, you get that back.  However if it's a clear quartz lantern, you do not get clear quartz back.  Which I think is fine, its a disadvantage for clear quartz, and we can explain simply by saying the clear quartz is too brittle to successfully salvage it.
![Vintagestory Screenshot 2022 06 29 - 09 37 57 63](https://user-images.githubusercontent.com/36369046/176464506-ee3d2fa3-4d7c-4e99-b9ca-de42319ed8ae.png)

**Comment by RedramVS** [comment] 2023-04-20 15:54
I'm closing this one out.  If someone thinks it needs further tooltips or something, they can open a new issue.

**Closed** 2023-04-20 15:55 UTC
Labels: status: confirmed, department: json
