### ISSUE TITLE
System.NullReferenceException with ground collapse option

### ISSUE THREAD

**Issue by YakiSera** [anegostudios/VintageStory-Issues#3109] opened 2023-09-21 21:21 UTC
### Game Version

v1.18.13

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

System.NullReferenceException occurred when I played with my friend
We have a ground collapse option turned on.

### How to reproduce

Can't reproduce again

### Screenshots

-

### Logs

```Running on 64 bit Windows with 16319 MB RAM
Game Version: v1.18.13 (Stable)
22.09.2023 0:12:18: Critical error occurred
Loaded Mods: game@1.18.13, creative@1.18.13, survival@1.18.13
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityMycelium.setMushroomBlock(Block block) in VSSurvivalMod\BlockEntity\BEMycelium.cs:line 198
   at Vintagestory.GameContent.BlockEntityMycelium.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldAccessForResolve) in VSSurvivalMod\BlockEntity\BEMycelium.cs:line 346
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(Packet_BlockEntity p, ClientMain game) in VintagestoryLib\Client\Model\ClientChunk.cs:line 429
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 414
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 757
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 21.09.2023 20:48:07, Site = , Source = Application Error, Message = Имя сбойного приложения: Vintagestory.exe, версия: 1.18.12.0, метка времени: 0x64b07659
Имя сбойного модуля: openal32.dll, версия: 1.23.0.0, метка времени: 0x63dd31ad
Код исключения: 0x40000015
Смещение ошибки: 0x00000000000df046
Идентификатор сбойного процесса: 0x2c60
Время запуска сбойного приложения: 0x01d9ecb3b6e05133
Путь сбойного приложения: C:\Users\Sera\AppData\Roaming\Vintagestory\Vintagestory.exe
Путь сбойного модуля: C:\Users\Sera\AppData\Roaming\Vintagestory\Lib\openal32.dll
Идентификатор отчета: a2aa7c76-3094-4737-8856-e8ca33b3f66a
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:  }
--------------
{ TimeGenerated = 21.09.2023 2:13:36, Site = , Source = Application Error, Message = Имя сбойного приложения: Vintagestory.exe, версия: 1.18.12.0, метка времени: 0x64b07659
Имя сбойного модуля: openal32.dll, версия: 1.23.0.0, метка времени: 0x63dd31ad
Код исключения: 0x40000015
Смещение ошибки: 0x00000000000df046
Идентификатор сбойного процесса: 0x3f0
Время запуска сбойного приложения: 0x01d9ebfa80a96ca7
Путь сбойного приложения: C:\Users\Sera\AppData\Roaming\Vintagestory\Vintagestory.exe
Путь сбойного модуля: C:\Users\Sera\AppData\Roaming\Vintagestory\Lib\openal32.dll
Идентификатор отчета: 06f740b1-e257-41dc-9d6d-641e31ab0077
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:  }
--------------
{ TimeGenerated = 20.09.2023 0:07:00, Site = , Source = Application Error, Message = Имя сбойного приложения: Vintagestory.exe, версия: 1.18.12.0, метка времени: 0x64b07659
Имя сбойного модуля: openal32.dll, версия: 1.23.0.0, метка времени: 0x63dd31ad
Код исключения: 0x40000015
Смещение ошибки: 0x00000000000df046
Идентификатор сбойного процесса: 0x136c
Время запуска сбойного приложения: 0x01d9eb2648868fd8
Путь сбойного приложения: C:\Users\Sera\AppData\Roaming\Vintagestory\Vintagestory.exe
Путь сбойного модуля: C:\Users\Sera\AppData\Roaming\Vintagestory\Lib\openal32.dll
Идентификатор отчета: ad7057be-8a45-4270-8cf7-a66fa35b7d67
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:  }```

**Comment by Craluminum2413** [comment] 2023-10-02 00:46
Duplicate of #2836

**Closed by Craluminum2413** 2023-10-02 00:46 UTC
Labels: status: new
