### ISSUE TITLE
1.16.4 Sealed crocks  meals dont get their seals remove when you eat from them with bowl.

### ISSUE THREAD

**Issue by Aledark789** [anegostudios/VintageStory-Issues#1812] opened 2022-03-14 18:22 UTC
**Game Version:** 1.16.4
**Platform:** Windows
**Modded:** No
**SP/MP:** MP : TOPTS

### Description
Crock pots which have been sealed keep their seal mention on mouse over even tho you take portions from it with a bowl.

### How to reproduce
1. Cook something ( 4 red meat 4x slots or just eggs or porridge ..same thing)
2. Seal the portions in a crock pot with wax or fat (lets pretend 4 portions)
3. While you right click with a bowl and check the crock pot it remains sealed while i got 3 portions. Weird part is its keeping it sealed.

**Comment by Craluminum2413** [comment] 2022-03-14 18:24
Duplicate of #1690

**Closed** 2022-03-14 21:05 UTC
Labels: status: duplicate

**Comment by Aledark789** [comment] 2022-03-14 22:06
my bad sry
