### ISSUE TITLE
"Max joint" error

### ISSUE THREAD

**Issue by knord1** [anegostudios/VintageStory-Issues#3426] opened 2024-01-12 15:32 UTC
### Game Version

 v1.19.0-rc.6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Crash when jumping up a block.

### How to reproduce

Running and jumping around in a "swamp" (lot's of small dirt patches with water in-between) and the game crashes.

### Logs

```
Running on 64 bit Windows 10.0.19045.0 with 32717 MB RAM
Game Version: v1.19.0-rc.6 (Unstable)
2024-01-12 16:24:38: Critical error occurred
Loaded Mods: game@1.19.0-rc.6, creative@1.19.0-rc.6, survival@1.19.0-rc.6
System.Exception: Max joint cap of 36 reached, needs to be at least 43. In clientsettings.json, please try increasing the "maxAnimatedElements": setting to 46.  This works for most GPUs.  Otherwise you might need to disable the creature.
   at Vintagestory.API.Common.Animation.GenerateAllFrames(ShapeElement[] rootElements, Dictionary`2 jointsById, Boolean recursive) in VintagestoryApi\Common\Model\Animation\Animation.cs:line 97
   at Vintagestory.API.Common.ClientAnimator.AnimNowActive(RunningAnimation anim, AnimationMetaData animData) in VintagestoryApi\Common\Model\Animation\ClientAnimator.cs:line 225
   at Vintagestory.API.Common.AnimatorBase.OnFrame(Dictionary`2 activeAnimationsByAnimCode, Single dt) in VintagestoryApi\Common\Model\Animation\AnimatorBase.cs:line 115
   at Vintagestory.API.Common.AnimationManager.OnClientFrame(Single dt) in VintagestoryApi\Common\Model\Animation\AnimationManager.cs:line 347
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 49
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 808
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 724
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 317
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

```

**Comment by sirStroam** [comment] 2024-01-13 11:17
I too experienced this issue recently.

Game Version
v1.19.0-rc.6

Platform
Windows

Modded
Vanilla

SP/MP
LAN multiplayer

Description
Crash when exploring

How to reproduce
No sure. After the crash it didn't repeat.

Screenshots
No response

`Running on 64 bit Windows 10.0.22621.0 with 32690 MB RAM
Game Version: v1.19.0-rc.6 (Unstable)
1/12/2024 10:49:47 PM: Critical error occurred
Loaded Mods: game@1.19.0-rc.6, creative@1.19.0-rc.6, survival@1.19.0-rc.6
System.Exception: Max joint cap of 36 reached, needs to be at least 43. In clientsettings.json, please try increasing the "maxAnimatedElements": setting to 46.  This works for most GPUs.  Otherwise you might need to disable the creature.
   at Vintagestory.API.Common.Animation.GenerateAllFrames(ShapeElement[] rootElements, Dictionary`2 jointsById, Boolean recursive) in VintagestoryApi\Common\Model\Animation\Animation.cs:line 97
   at Vintagestory.API.Common.ClientAnimator.AnimNowActive(RunningAnimation anim, AnimationMetaData animData) in VintagestoryApi\Common\Model\Animation\ClientAnimator.cs:line 225
   at Vintagestory.API.Common.AnimatorBase.OnFrame(Dictionary`2 activeAnimationsByAnimCode, Single dt) in VintagestoryApi\Common\Model\Animation\AnimatorBase.cs:line 115
   at Vintagestory.API.Common.AnimationManager.OnClientFrame(Single dt) in VintagestoryApi\Common\Model\Animation\AnimationManager.cs:line 347
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 49
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 808
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 724
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 317
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
`

**Comment by tyronx** [comment] 2024-01-15 08:43
strange, do either of you run the game with special startup arguments? Perhaps its reading from the wrong clientsettings.json file.

**Comment by knord1** [comment] 2024-01-15 12:55
I did an "update 1.18 to 1.19" so it could be a 1.18 config that's not checked or removed.

**Comment by knord1** [comment] 2024-01-16 12:04
update:

- Uninstalled1.18. 
- Removed all files from AppData/Roaming
- Installer 1.19-rc.8.
- After several hours of playtime, no errors

**Comment by Craluminum2413** [comment] 2024-01-18 05:14
Duplicate of #3284

**Closed** 2024-01-18 05:17 UTC
Labels: status: duplicate
