### ISSUE TITLE
Stacked buckets can produce infinite liquid

### ISSUE THREAD

**Issue by Aizistral** [anegostudios/VintageStory-Issues#2128] opened 2022-08-23 15:10 UTC
**Game Version:** 1.16.5
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
Using at least two buckets, each filled to maximum (10L) capacity and stacked together, player can pour infinite amount of liquid out of them into barrels and other containers that can be placed in world. Default right-click behavior works fine, but using Ctrl+Right-Click to add 1 liter at a time will do so without reducing the amount of liquid in stacked buckets. This seems to work with all liquids.

Might be related to #1862 and/or #2089, but those seem to describe slightly different interactions.

### How to reproduce
1. Get 2 stacked buckets of liquid, say milk, storing 20L of milk total;
2. Place a barrel;
3. Ctrl+Right-Click with those buckets to gradually fill the barrel;
4. Behold!

### Expected behavior
No infinite liquid I guess.

**Comment by Craluminum2413** [comment] 2022-08-24 12:49
I'm not able to reproduce that

https://user-images.githubusercontent.com/69315569/186422441-61b5cbf0-13b2-419d-af8a-9e90d9a96a85.mp4

**Comment by Craluminum2413** [comment] 2022-08-24 13:01
So I have successfully reproduced this in 1.16.5, thus I think it was fixed in 1.17

**Closed by Craluminum2413** 2022-08-24 13:01 UTC
Labels: status: new
