### ISSUE TITLE
Critical Crash: climateLigtherPlantTint not in dictionary

### ISSUE THREAD

**Issue by Turtsie** [anegostudios/VintageStory-Issues#3467] opened 2024-01-18 16:45 UTC
### Game Version

1.19.0

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I was traveling through a biome with Hyenas when I jumped and the game crashed and is now no longer allowing me to enter the world whatsoever. Reading the crash log, I think it might be related to the minimap as I recently changed it from no color to true color. if there was a way to change the minimap without loading the world and using the command, I'd try it.
Attempted to run in repair mode and was unsuccessful.

### How to reproduce

Presently, I'm not sure. I tried to reproduce in another world but wasn't successful, possibly due to the inability to find the correct biome change, but I'm unsure!

### Screenshots

No visual aspect available since I'm not having a lot of luck replicating it

### Logs

Running on 64 bit Windows 10.0.22621.0 with 16013 MB RAM
Game Version: v1.19.0 (Stable)
1/18/2024 10:30:42 AM: Critical error occurred
Loaded Mods: game@1.19.0, creative@1.19.0, survival@1.19.0
System.Collections.Generic.KeyNotFoundException: The given key 'climateLighterPlantTint' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Vintagestory.Client.NoObf.ClientWorldMap.ApplyColorMapOnRgba(String climateColorMap, String seasonColorMap, Int32 color, Int32 posX, Int32 posY, Int32 posZ, Boolean flipRb) in VintagestoryLib\Client\ClientWorldMap.cs:line 395
   at Vintagestory.Client.NoObf.ClientMain.ApplyColorMapOnRgba(String climateColorMap, String seasonColorMap, Int32 color, Int32 posX, Int32 posY, Int32 posZ, Boolean flipRb) in VintagestoryLib\Client\ClientMain.cs:line 2661
   at Vintagestory.GameContent.BlockFruitTreeFoliage.GetColor(ICoreClientAPI capi, BlockPos pos) in VSSurvivalMod\Systems\FruitTree\BlockFruitTreeFoliage.cs:line 100
   at Vintagestory.GameContent.ChunkMapLayer.GenerateChunkImage(Vec2i chunkPos, IMapChunk mc, Int32[]& tintedImage, Boolean colorAccurate) in VSEssentials\Systems\WorldMap\ChunkLayer\ChunkMapLayer.cs:line 493
   at Vintagestory.GameContent.ChunkMapLayer.OnOffThreadTick(Single dt) in VSEssentials\Systems\WorldMap\ChunkLayer\ChunkMapLayer.cs:line 344
   at Vintagestory.GameContent.WorldMapManager.<OnLvlFinalize>b__22_0() in VSEssentials\Systems\WorldMap\WorldMapManager.cs:line 206

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 1/18/2024 10:29:39 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.0.0, time stamp: 0x65310000
Faulting module name: KERNELBASE.dll, version: 10.0.22621.2792, time stamp: 0x3091b6fb
Exception code: 0xe0434352
Fault offset: 0x000000000006567c
Faulting process id: 0x0xb2c
Faulting application start time: 0x0x1da4a247ae2a57c
Faulting application path: C:\Users\dowel\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: a969043b-a113-42d6-b0b8-7cb69c3d265f
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment] 2024-01-18 16:48
Duplicate of #3455

**Closed by Craluminum2413** 2024-01-18 16:48 UTC
Labels: status: new
