### ISSUE TITLE
Infinite Spears via Throwing when in LAN server

### ISSUE THREAD

**Issue by Timmiwurschtl** [anegostudios/VintageStory-Issues#398] opened 2020-03-01 12:25 UTC
**Game Version:** 1.12.5 (stable)
**Platform:** Windows 10
**Modded:** No

### Description
My partner on my LAN server can sometimes throw her spear, without loosing it in her inventory. She can then pick up the thrown spear, which is a copy of the spear in the inventory, and has two spears in her inventory. This can be reapeated as often as one wishes -> Infinite spear production :)

### How to reproduce
2. We don't know what leads to that behaviour, sometimes it is possible, sometimes it is not. Sleeping seems to have no effect on that.

### Expected behavior
The spear should vanish from the inventory when thrown.

**Comment by Bloodsaw** [comment] 2020-03-01 12:58
I remember that I read somewhere (maybe discord) that he/she was experiencing this if the spear was thrown into water.

I for myself also experienced it, but couldn't reproduce it reliable.
I just had the "feeling" that I came home with more spears.

**Comment by Timmiwurschtl** [comment] 2020-03-01 13:51
We definitely had that without water though, so I doubt that could be the reason. Today, we had the issue again, but we cannot say why... :)
If we run into that again, we will try different things and see if we can figure out what could be the reason.

**Comment by tyronx** [comment] 2020-03-01 15:34
What happens when you throw a spear is that if you have any other spears in your inventory it will be automatically moved into your active hand slot so you can throw them in quick succession. 

I might be that your partner simply had 2 spears in your inventory to begin with.

**Comment by Timmiwurschtl** [comment] 2020-03-02 06:09
She started with only up to two spears and she was able to end up with 5 spears or more. It was also possible for her to give me those copied spears.
Btw.: Really great game, it is so much fun to play! Great work and great effort! Looking forward to what will come in the future.

**Comment by Bloodsaw** [comment] 2020-03-02 21:55
@Timmiwurschtl could you observe if this only occur after longer play time? Sometimes @Angelnoir and me experience desync phenomenons after longer sessions. (Animations not in sync on our clients, players frozen for minutes and stuff like this)

**Comment by Timmiwurschtl** [comment] 2020-03-05 17:30
We figured out that my partner was able to beam spears from a storage vessel containing spears (made by her) to her inventory, even though she was far away. I watched the spears vanish from the storage vessel and appearing in her inventory when she was throwing the spear she had in her inventory. Quite amazing :)

I will give this a try for myself the next time, maybe it works for me, too. Did not check that yet.

**Comment by Bloodsaw** [comment] 2020-03-06 16:53
@Timmiwurschtl you're a genius, I was able to replicate this.

###  How to reproduce
1. Create some spears
2. Place half of them (for example) in a storage vessel
3. Throw the spears

The spears will refill automatically from the storage vessel after throwing the last spear from inventory. 

### Screenshots
![2020-03-06_17-46-13](https://user-images.githubusercontent.com/61588797/76103961-dfc19c80-5fd2-11ea-8cf4-b096df95aca1.png)
![2020-03-06_17-46-34](https://user-images.githubusercontent.com/61588797/76104044-fc5dd480-5fd2-11ea-88a0-b265f53e19cf.png)
![2020-03-06_17-46-44](https://user-images.githubusercontent.com/61588797/76104058-fff15b80-5fd2-11ea-96b2-727be84f5e71.png)

### Additional information

I also tested if this is range limited, but it seems to work no matter the distance to the storage vessel.

**Comment by Timmiwurschtl** [comment] 2020-03-06 19:31
Well done!
Nice feature xD Let's see for how long we can enjoy that...

**Comment by tyronx** [comment] 2020-04-11 14:07
This is fixed for version 1.3. Seems like the event of closing a chest inventory never properly arrived on the server side.

**Closed** 2020-04-11 16:40 UTC
Labels: status: resolved, target: survival, type: bug
