### ISSUE TITLE
Scroll rack game crash

### ISSUE THREAD

**Issue by Ashantin** [anegostudios/VintageStory-Issues#3188] opened 2023-10-30 15:18 UTC
### Game Version

v1.19 pre3

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

The scroll rack did not appear when I placed it on the ground. I used an axe to try to pick it up from where it was and the game crashed. 
Running on 64 bit Windows with 65397 MB RAM
Game Version: v1.19.0-pre.3 (Unstable)
30/10/2023 15:02:13: Critical error occurred
Loaded Mods: game@1.19.0-pre.3, creative@1.19.0-pre.3, survival@1.19.0-pre.3
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockScrollRack.GetSelectionBoxes(IBlockAccessor blockAccessor, BlockPos pos) in VSSurvivalMod\Block\BlockScrollRack.cs:line 91
   at Vintagestory.API.Common.Block.GetParticleBreakBox(IBlockAccessor blockAccess, BlockPos pos, BlockFacing facing) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 508
   at Vintagestory.API.Common.CollectibleParticleProperties.RandomBlockPos(IBlockAccessor blockAccess, BlockPos pos, Block block, BlockFacing facing) in VintagestoryApi\Common\Particle\CollectibleParticleProperties.cs:line 161
   at Vintagestory.API.Common.BlockBrokenParticleProps.get_Pos() in VintagestoryApi\Common\Particle\CollectibleParticleProperties.cs:line 95
   at Vintagestory.Client.NoObf.ParticlePoolQuads.SpawnParticles(IParticlePropertiesProvider particleProperties) in VintagestoryLib\Client\Systems\Render\Particle\ParticlePoolQuads.cs:line 209
   at Vintagestory.Client.NoObf.ParticleManager.SpawnParticles(IParticlePropertiesProvider properties) in VintagestoryLib\Client\Util\ParticleManager.cs:line 91
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleSpawnParticles(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 521
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 763
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 322
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 30/10/2023 14:41:45, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.0.0, time stamp: 0x6514d416
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process ID: 0x2118
Faulting application start time: 0x01da0b3f033e8b18
Faulting application path: D:\Vintagestory\Vintagestory\Vintagestory.exe
Faulting module path: D:\Vintagestory\Vintagestory\Lib\openal32.dll
Report ID: 829022e3-edac-4c0d-a92a-2a76d19f1202
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 30/10/2023 14:37:02, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.15.0, time stamp: 0x64e841c5
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process ID: 0x4108
Faulting application start time: 0x01da0b3a35a2a4bc
Faulting application path: D:\Vintagestory\Vintagestory\Vintagestory.exe
Faulting module path: D:\Vintagestory\Vintagestory\Lib\openal32.dll
Report ID: 4456be31-0390-4ee9-bc9b-e57d90e0ec3f
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 30/10/2023 14:05:31, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.15.0, time stamp: 0x64e841c5
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process ID: 0x38d4
Faulting application start time: 0x01da0b3a1d46203c
Faulting application path: D:\Vintagestory\Vintagestory\Vintagestory.exe
Faulting module path: D:\Vintagestory\Vintagestory\Lib\openal32.dll
Report ID: 93b6dc14-574e-47a9-9f30-9c0ee558fb64
Faulting package full name: 
Faulting package-relative application ID:  }

### How to reproduce

Make a scroll rack in survival. Place it on the ground. Try to pick it up with an axe.

### Logs

```Log```Running on 64 bit Windows with 65397 MB RAM
Game Version: v1.19.0-pre.3 (Unstable)
30/10/2023 15:02:13: Critical error occurred
Loaded Mods: game@1.19.0-pre.3, creative@1.19.0-pre.3, survival@1.19.0-pre.3
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockScrollRack.GetSelectionBoxes(IBlockAccessor blockAccessor, BlockPos pos) in VSSurvivalMod\Block\BlockScrollRack.cs:line 91
   at Vintagestory.API.Common.Block.GetParticleBreakBox(IBlockAccessor blockAccess, BlockPos pos, BlockFacing facing) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 508
   at Vintagestory.API.Common.CollectibleParticleProperties.RandomBlockPos(IBlockAccessor blockAccess, BlockPos pos, Block block, BlockFacing facing) in VintagestoryApi\Common\Particle\CollectibleParticleProperties.cs:line 161
   at Vintagestory.API.Common.BlockBrokenParticleProps.get_Pos() in VintagestoryApi\Common\Particle\CollectibleParticleProperties.cs:line 95
   at Vintagestory.Client.NoObf.ParticlePoolQuads.SpawnParticles(IParticlePropertiesProvider particleProperties) in VintagestoryLib\Client\Systems\Render\Particle\ParticlePoolQuads.cs:line 209
   at Vintagestory.Client.NoObf.ParticleManager.SpawnParticles(IParticlePropertiesProvider properties) in VintagestoryLib\Client\Util\ParticleManager.cs:line 91
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleSpawnParticles(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 521
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 763
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 322
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 30/10/2023 14:41:45, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.0.0, time stamp: 0x6514d416
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process ID: 0x2118
Faulting application start time: 0x01da0b3f033e8b18
Faulting application path: D:\Vintagestory\Vintagestory\Vintagestory.exe
Faulting module path: D:\Vintagestory\Vintagestory\Lib\openal32.dll
Report ID: 829022e3-edac-4c0d-a92a-2a76d19f1202
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 30/10/2023 14:37:02, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.15.0, time stamp: 0x64e841c5
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process ID: 0x4108
Faulting application start time: 0x01da0b3a35a2a4bc
Faulting application path: D:\Vintagestory\Vintagestory\Vintagestory.exe
Faulting module path: D:\Vintagestory\Vintagestory\Lib\openal32.dll
Report ID: 4456be31-0390-4ee9-bc9b-e57d90e0ec3f
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 30/10/2023 14:05:31, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.15.0, time stamp: 0x64e841c5
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process ID: 0x38d4
Faulting application start time: 0x01da0b3a1d46203c
Faulting application path: D:\Vintagestory\Vintagestory\Vintagestory.exe
Faulting module path: D:\Vintagestory\Vintagestory\Lib\openal32.dll
Report ID: 93b6dc14-574e-47a9-9f30-9c0ee558fb64
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment] 2023-10-30 15:53
Duplicate of #3187

**Closed by Craluminum2413** 2023-10-30 15:53 UTC
Labels: status: new
