### ISSUE TITLE
Items in crafting menu staying on death

### ISSUE THREAD

**Issue by LordDeatHunter** [anegostudios/VintageStory-Issues#1066] opened 2021-06-25 16:51 UTC
**Game Version:** 1.15.0-pre7
**Platform:** Windows
**Modded:** No

When dying, the items inside the crafting menu don't drop.

**Comment by Craluminum2413** [comment] 2021-06-25 16:53
Duplicate of #788

**Closed** 2021-06-25 16:55 UTC
Labels: status: duplicate
