### ISSUE TITLE
Stick bounce non stop

### ISSUE THREAD

**Issue by DanDinCri** [anegostudios/VintageStory-Issues#3990] opened 2024-07-29 13:19 UTC
### Game Version

1.19.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

After cutting down a pine tree with a flint axe, there's a stick that started bouncing, and every time it touches the ground the bounce speed increases. The stick reached a point where it's not comming down, so I can't screenshot it.

### How to reproduce

1. Cut down a pine tree with a flint axe.

### Logs

```Log```

**Comment by pingouyn** [comment] 2024-08-07 14:43
Starting playing in 1.18.x.  Has often happened to me with sticks on trees, and stones (the tiny stones) jumping up and down when breaking several rocks in caves...  Recurring issue

**Comment by Craluminum2413** [comment] 2024-08-15 19:18
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/1844

**Closed by Craluminum2413** 2024-08-15 19:18 UTC
Labels: status: new, department: code
