### ISSUE TITLE
Invisible Question Mark blocks at Translocators.

### ISSUE THREAD

**Issue by Gitcurt777** [anegostudios/VintageStory-Issues#3137] opened 2023-10-07 20:51 UTC
### Game Version

v1.18.14

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

First world. No mods. No modification of game files. Normal temperate world.

Some translocators have invisible blocks nearby (within the loot and junk) for me. Either while finding them. Or after teleporting to them. Two of these invisible blocks. Have dropped the white question mark blocks. Not sure what they are supposed to be.
Thought you should know. 

### How to reproduce

Find a translocator in my world.

### Screenshots

![2023-10-07_13-08-10](https://github.com/anegostudios/VintageStory-Issues/assets/54503925/edc9bd73-f8e7-454b-8501-285caab471f3)

### Logs

```Log```

**Comment by Vanir-dono** [comment] 2023-10-08 16:55
i believe they don't have texture yet, for me they're invisible

**Comment by Bumber64** [comment] 2023-10-08 17:00
Duplicate of #2900

**Closed** 2023-10-08 19:32 UTC
Labels: status: duplicate
