### ISSUE TITLE
.NET7/Linux: World map has white stripe artifacts

### ISSUE THREAD

**Issue by brndd** [anegostudios/VintageStory-Issues#2852] opened 2023-06-28 09:37 UTC
### Game Version

v1.18.6-rc2 .NET7

### Platform

Linux

### Modded

None

### SP/MP

Singleplayer

### Description

On the experimental .NET7 build on Linux, the world map is covered in horizontal white stripes. This issue does not happen on the Mono build.

System specifications:

- Fedora Linux 38
- Kernel 6.3.8
- Mesa 23.1.2
- dotnet 7.0.107

Hardware:

- AMD 6700XT
- Intel 12900k

### How to reproduce

1. Create a world on the experimental .NET7 build
2. Open the map
3. Observe artifacts

### Screenshots

![2023-06-28T12:27:01](https://github.com/anegostudios/VintageStory-Issues/assets/5822375/22b67dca-c98e-49e8-87a1-c77b0cdf6bf8)

### Logs

```Log```

[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/11892605/client-main.txt)

**Comment by radfast** [comment] 2023-06-28 10:24
Repeating what you said to me on Discord:

>  Hmm nope, doesn't happen on the 1.18.6-rc2 Mono build, so on my machine at least it's .NET7 exclusive

**Comment by radfast** [comment] 2023-06-28 10:56
Please see further details [on Discord](https://discord.com/channels/302152934249070593/1110493590167228416/1123566035946180648)

**Comment by radfast** [comment] 2023-06-28 14:13
Thank you again for reporting this and raising its prominence.  We have found the cause, and it is fixed in upcoming 1.18.6 stable (potentially that can be released later today)

**Closed by radfast** 2023-06-28 14:13 UTC
Labels: platform: linux, status: new, priority: medium
