### ISSUE TITLE
Smithing broken in a new way

### ISSUE THREAD

**Issue by malnaur** [anegostudios/VintageStory-Issues#3767] opened 2024-04-01 04:06 UTC
### Game Version

v1.19.6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I don't know why something that worked fine for a long time is now badly broken but it is.
1.19.4 - Hammer would stop striking randomly and a tool switch was needed to make it strike again.
1.19.5 - Hammer would randomly double-strike causing two actions instead of one.
1.19.6 - Hammer loses strike again but pausing a moment restores striking. Once it loses track, repeating rapid button presses produces the hammer waving at the workpiece but not actually striking. Pausing for a three count resumes striking on the next blow. This slows down smithing pretty badly and developing a rhythm is impossible.

Please make smithing great again.

### How to reproduce

Try working an ingot with blows at about 4/sec. See how it goes.

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2024-04-01 09:22
Duplicate of #3766

**Closed** 2024-04-01 09:23 UTC
Labels: status: duplicate
