### ISSUE TITLE
Prospecting Pick mode changing makes me crash

### ISSUE THREAD

**Issue by mono323** [anegostudios/VintageStory-Issues#1530] opened 2022-01-04 10:09 UTC
**Game Version:** 1.16 RC5 (latest)
**Platform:** Windows
**Modded:**  Yes (Primitive Survival)
**SP/MP:**  Multiplayer

### Description
im trying to use the prospecting pick upon changing mode (pressing F) it crashes

### How to reproduce
1. Make a 'Prospecting pick'
2. press F to change mode
3. It crashes.

### Expected behavior
voxels being moved but instead it crashes.

### Screenshots
not visual

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.16.0-rc.5 (Unstable)04.01.2022 11:02:49: Critical error occurred
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.Client.NoObf.GuiDialogToolMode.OnSlotClick(Int32 num)
   bei Vintagestory.API.Client.GuiElementSkillItemGrid.OnMouseDownOnElement(ICoreClientAPI api, MouseEvent args)
   bei Vintagestory.API.Client.GuiElement.OnMouseDown(ICoreClientAPI api, MouseEvent mouse)
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/7806841/client-crash.txt)

   bei Vintagestory.API.Client.GuiComposer.OnMouseDown(MouseEvent mouseArgs)
   bei Vintagestory.API.Client.GuiDialog.OnMouseDown(MouseEvent args)
   bei Vintagestory.Client.NoObf.GuiManager.OnMouseDown(MouseEvent args)
   bei Vintagestory.Client.NoObf.ClientMain.OnMouseDown(MouseEvent args)
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonDown(Object sender, MouseButtonEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:Zeile 792.
   bei OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   bei OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:Zeile 1554.
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 368.
   bei _nFNsDM20as86sGo44HbF6xxAkUD._UjMaM1bzP5Ozg5ilu06DMFIxPyO(_uhgd4BSf8z6N7PAibzFcq8c5IRD , String[] )
   bei _Y4Bk3tLdFsgoJryQq19g4IoitkE._UjMaM1bzP5Ozg5ilu06DMFIxPyO(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 04.01.2022 11:02:52, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.16.0.0, Zeitstempel: 0x61d08fe4
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.1348, Zeitstempel: 0x76fcd692
Ausnahmecode: 0xc000041d
Fehleroffset: 0x0000000000034f69
ID des fehlerhaften Prozesses: 0x2084
Startzeit der fehlerhaften Anwendung: 0x01d8014e7cda23b9
Pfad der fehlerhaften Anwendung: C:\Users\mderr\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\KERNELBASE.dll
Berichtskennung: 8d37e6c4-3717-4585-9634-40fbb15e329a
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 04.01.2022 11:02:50, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.16.0.0, Zeitstempel: 0x61d08fe4
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.1348, Zeitstempel: 0x76fcd692
Ausnahmecode: 0xc0020001
Fehleroffset: 0x0000000000034f69
ID des fehlerhaften Prozesses: 0x2084
Startzeit der fehlerhaften Anwendung: 0x01d8014e7cda23b9
Pfad der fehlerhaften Anwendung: C:\Users\mderr\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\KERNELBASE.dll
Berichtskennung: 3c0c79e5-cfb2-41ca-98a6-d275d8154c03
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 04.01.2022 11:02:50, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: Ausnahmecode c0020001, Ausnahmeadresse 00007FF9D8FE4F69
Stapel:
 }
```

**Comment by copygirl** [comment] 2022-01-04 10:54
Duplicate of #1523. Should be fixed in the next release.

Thanks for reporting!

**Closed by copygirl** 2022-01-04 10:54 UTC
Labels: status: duplicate
