### ISSUE TITLE
Critical error, IndexOutOfRangeException

### ISSUE THREAD

**Issue by dann1kid** [anegostudios/VintageStory-Issues#793] opened 2021-02-19 18:00 UTC
**Game Version:** 1.14.7
**Platform:** Windows 
**Modded:** Yes 

### Description
crush on enter the world

### How to reproduce
1 Make small world (5120*5120)
2 Try move out the border of the world (teleport)
3 get in onfinity window on enter

### Expected behavior
get on  empty space
Also, this world when move from single to server, spawn point is setting up on unknown place

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Running on 64 bit Windows with 96 GB RAM 
Version: v1.14.7 (Stable)19.02.2021 20:48:08: Critical error occurred
System.IndexOutOfRangeException: Индекс находился вне границ массива.
   в Vintagestory.Client.NoObf.ClientWorldMap.GetClimate(Int32 posX, Int32 posZ)
   в Vintagestory.Client.NoObf.ClientWorldMap.GetClimateAt(BlockPos pos, EnumGetClimateMode mode, Double totalDays)
   в _4t8EbLHMAB8hENInKlrCWDfjHuz._wPHTausaZnbno3nTTjMsFvjzmXl(Single )
   в Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   в Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   в Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   в _XJ8aPSlEBe0PiHYbVJEdfXv1yjvA._Kgao3H1tkjUV97mMFigKazMDiUo(Single )
   в _QXfAdKxrJ1KaNtwiV64JU2IvnpC._cl7z8c5uEEaIF1fo0XdijiZbRYk(Single )
   в _QXfAdKxrJ1KaNtwiV64JU2IvnpC._peV5mb21IaSJTAYBddj4gA99BDo(Single )
   в Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   в System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   в OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   в OpenTK.GameWindow.DispatchRenderFrame()
   в OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   в _03wQBzfCnykaMLiRGgbQzrKOcn3._QN2fpVgRVBDOLs27GIkkdMlxeKf(_a9AJZVMB0wcgfRPD19VvLtZCbaX , String[] )
   в _NdjU5BXvKkfOW2d88pNMbEAjE1q._QN2fpVgRVBDOLs27GIkkdMlxeKf(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 26.01.2021 20:56:25, Site = , Source = .NET Runtime, Message = Приложение: Vintagestory.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за необработанного исключения.
Сведения об исключении: код исключения c0020001, адрес исключения 00007FFFC739D759
Стек:
   в System.Environment._Exit(Int32)
   в System.Environment._Exit(Int32)
   в System.Environment.Exit(Int32)
   в System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   в OpenTK.NativeWindow.OnClosedInternal(System.Object, System.EventArgs)
   в System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   в OpenTK.Platform.Windows.WinGLNative.HandleDestroy(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   в OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   в OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   в OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   в OpenTK.Platform.Windows.WinGLNative.DestroyWindow()
   в OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   в OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   в OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   в OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   в OpenTK.Platform.Windows.Functions.PeekMessage(OpenTK.Platform.Windows.MSG ByRef, IntPtr, Int32, Int32, OpenTK.Platform.Windows.PeekMessageFlags)
   в OpenTK.Platform.Windows.Functions.PeekMessage(OpenTK.Platform.Windows.MSG ByRef, IntPtr, Int32, Int32, OpenTK.Platform.Windows.PeekMessageFlags)
   в OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   в OpenTK.GameWindow.Run(Double, Double)
   в _4eRDDOqtbaPbgjN2dJ1zzD1FCRy._ExJp6VhLWG4xQoHsVn72tgyNbeG(_bWl72q5sGuTQypu8W8r7cRXUcRF, System.String[])
   в _XKAWv6MyciUiZmECUonQCwPaCwE._ExJp6VhLWG4xQoHsVn72tgyNbeG(System.Threading.ThreadStart)
   в _4eRDDOqtbaPbgjN2dJ1zzD1FCRy._jyInOxlJtjeDvyVArlNd6UT8Cuf(System.String[])
 }
{ TimeGenerated = 24.01.2021 22:28:34, Site = , Source = .NET Runtime, Message = Приложение: Vintagestory.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за необработанного исключения.
Сведения об исключении: System.AccessViolationException
   в OpenTK.Graphics.OpenGL.GL.UniformMatrix4(Int32, Int32, Boolean, Single[])
   в Vintagestory.Client.NoObf.ShaderProgramBase.UniformMatrix(System.String, Single[])
   в VolumetricShading.ScreenSpaceReflections.OnRenderSsrOut()
   в VolumetricShading.ScreenSpaceReflections.OnRenderFrame(Single, Vintagestory.API.Client.EnumRenderStage)
   в Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(Vintagestory.API.Client.EnumRenderStage, Single)
   в Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(Vintagestory.API.Client.EnumRenderStage, Single)
   в Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single)
   в _Vq7Xo4xIdbZDwh8iDcGnovGKH7D._5RNBrkQoxljreqLqfZ3LUVDaIrr(Single)
   в _7KGTxxuvfNubJZCLAMEMJZBkPDeA._07k4LSTgxALpYbS1S6K07SItFcH(Single)
   в _7KGTxxuvfNubJZCLAMEMJZBkPDeA._aysJzMcCvicDqo8MC3TmjcDsfdZ(Single)
   в Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(System.Object, OpenTK.FrameEventArgs)
   в System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   в OpenTK.GameWindow.RaiseRenderFrame(Double, Double ByRef)
   в OpenTK.GameWindow.DispatchRenderFrame()
   в OpenTK.GameWindow.Run(Double, Double)
   в _4eRDDOqtbaPbgjN2dJ1zzD1FCRy._ExJp6VhLWG4xQoHsVn72tgyNbeG(_bWl72q5sGuTQypu8W8r7cRXUcRF, System.String[])
   в _XKAWv6MyciUiZmECUonQCwPaCwE._ExJp6VhLWG4xQoHsVn72tgyNbeG(System.Threading.ThreadStart)
   в _4eRDDOqtbaPbgjN2dJ1zzD1FCRy._jyInOxlJtjeDvyVArlNd6UT8Cuf(System.String[])

 }
{ TimeGenerated = 24.01.2021 22:23:34, Site = , Source = .NET Runtime, Message = Приложение: Vintagestory.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за необработанного исключения.
Сведения об исключении: System.AccessViolationException
   в OpenTK.Graphics.OpenGL.GL.UniformMatrix4(Int32, Int32, Boolean, Single[])
   в Vintagestory.Client.NoObf.ShaderProgramBase.UniformMatrix(System.String, Single[])
   в VolumetricShading.ScreenSpaceReflections.OnRenderSsrOut()
   в VolumetricShading.ScreenSpaceReflections.OnRenderFrame(Single, Vintagestory.API.Client.EnumRenderStage)
   в Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(Vintagestory.API.Client.EnumRenderStage, Single)
   в Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(Vintagestory.API.Client.EnumRenderStage, Single)
   в Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single)
   в _Vq7Xo4xIdbZDwh8iDcGnovGKH7D._5RNBrkQoxljreqLqfZ3LUVDaIrr(Single)
   в _7KGTxxuvfNubJZCLAMEMJZBkPDeA._07k4LSTgxALpYbS1S6K07SItFcH(Single)
   в _7KGTxxuvfNubJZCLAMEMJZBkPDeA._aysJzMcCvicDqo8MC3TmjcDsfdZ(Single)
   в Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(System.Object, OpenTK.FrameEventArgs)
   в System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   в OpenTK.GameWindow.RaiseRenderFrame(Double, Double ByRef)
   в OpenTK.GameWindow.DispatchRenderFrame()
   в OpenTK.GameWindow.Run(Double, Double)
   в _4eRDDOqtbaPbgjN2dJ1zzD1FCRy._ExJp6VhLWG4xQoHsVn72tgyNbeG(_bWl72q5sGuTQypu8W8r7cRXUcRF, System.String[])
   в _XKAWv6MyciUiZmECUonQCwPaCwE._ExJp6VhLWG4xQoHsVn72tgyNbeG(System.Threading.ThreadStart)
   в _4eRDDOqtbaPbgjN2dJ1zzD1FCRy._jyInOxlJtjeDvyVArlNd6UT8Cuf(System.String[])

 }
```

**Comment by copygirl** [comment] 2021-02-19 18:04
Related: #785

**Comment by Craluminum2413** [comment] 2023-04-10 10:44
Duplicate of #785

**Closed by Craluminum2413** 2023-04-10 10:45 UTC
Labels: status: new
