### ISSUE TITLE
Game crashing unhandled exception

### ISSUE THREAD

**Issue by dickynu13** [anegostudios/VintageStory-Issues#668] opened 2020-11-27 14:42 UTC
Running on 64 bit Windows with 8 GB RAM 
Version: v1.13.4 (Stable)11/23/2020 3:32:00 PM: Critical error occurred
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: dx/dz must be within [0,2]
   at Vintagestory.GameContent.MultiChunkMapComponent.unsetChunk(Int32 dx, Int32 dz)
   at Vintagestory.GameContent.ChunkMapLayer.OnViewChangedClient(List`1 nowVisible, List`1 nowHidden)
   at Vintagestory.GameContent.WorldMapManager.onViewChangedClient(List`1 nowVisible, List`1 nowHidden)
   at Vintagestory.GameContent.GuiElementMap.EnsureMapFullyLoaded()
   at Vintagestory.GameContent.GuiDialogWorldMap.<ComposeDialog>b__16_0(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _VtIDI6oYFpyEcQSZBFso9UVxS9aA._ZnYzeuHqveMMiEvOnpahncAMjfg(Single )
   at _LSAAgZhw31Rqs2is6nnojfZBbQC._4BykKOCicJqCBHpyWIgTmxWrTrg(Single )
   at _LSAAgZhw31Rqs2is6nnojfZBbQC._6XmOxKoTYrFLRCGd58p58XW43nD(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._EEzpApWBQHtHR4iMJabXK2wDvlA(_ex0VSgRAdtsvhANmJHZHaf9ATWt , String[] )
   at _IcGByoJhapvESnm6vaOawAHbkeU._EEzpApWBQHtHR4iMJabXK2wDvlA(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 11/24/2020 3:54:35 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at OpenTK.Graphics.OpenGL.GL.DrawElements(OpenTK.Graphics.OpenGL.PrimitiveType, Int32, OpenTK.Graphics.OpenGL.DrawElementsType, Int32)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.RenderMesh(Vintagestory.API.Client.MeshRef)
   at Vintagestory.GameContent.AnvilWorkItemRenderer.OnRenderFrame(Single, Vintagestory.API.Client.EnumRenderStage)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(Vintagestory.API.Client.EnumRenderStage, Single)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(Vintagestory.API.Client.EnumRenderStage, Single)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single)
   at _VtIDI6oYFpyEcQSZBFso9UVxS9aA._ZnYzeuHqveMMiEvOnpahncAMjfg(Single)
   at _LSAAgZhw31Rqs2is6nnojfZBbQC._4BykKOCicJqCBHpyWIgTmxWrTrg(Single)
   at _LSAAgZhw31Rqs2is6nnojfZBbQC._6XmOxKoTYrFLRCGd58p58XW43nD(Single)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(System.Object, OpenTK.FrameEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.GameWindow.RaiseRenderFrame(Double, Double ByRef)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double, Double)
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._EEzpApWBQHtHR4iMJabXK2wDvlA(_ex0VSgRAdtsvhANmJHZHaf9ATWt, System.String[])
   at _IcGByoJhapvESnm6vaOawAHbkeU._EEzpApWBQHtHR4iMJabXK2wDvlA(System.Threading.ThreadStart)
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._k39DsboSFqAvcX2gaWs5Tk5Zl6Q(System.String[])

 }
{ TimeGenerated = 11/24/2020 11:41:32 AM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at OpenTK.Graphics.OpenGL.GL.DrawElements(OpenTK.Graphics.OpenGL.PrimitiveType, Int32, OpenTK.Graphics.OpenGL.DrawElementsType, Int32)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.RenderMesh(Vintagestory.API.Client.MeshRef)
   at Vintagestory.GameContent.AnvilWorkItemRenderer.OnRenderFrame(Single, Vintagestory.API.Client.EnumRenderStage)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(Vintagestory.API.Client.EnumRenderStage, Single)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(Vintagestory.API.Client.EnumRenderStage, Single)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single)
   at _VtIDI6oYFpyEcQSZBFso9UVxS9aA._ZnYzeuHqveMMiEvOnpahncAMjfg(Single)
   at _LSAAgZhw31Rqs2is6nnojfZBbQC._4BykKOCicJqCBHpyWIgTmxWrTrg(Single)
   at _LSAAgZhw31Rqs2is6nnojfZBbQC._6XmOxKoTYrFLRCGd58p58XW43nD(Single)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(System.Object, OpenTK.FrameEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.GameWindow.RaiseRenderFrame(Double, Double ByRef)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double, Double)
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._EEzpApWBQHtHR4iMJabXK2wDvlA(_ex0VSgRAdtsvhANmJHZHaf9ATWt, System.String[])
   at _IcGByoJhapvESnm6vaOawAHbkeU._EEzpApWBQHtHR4iMJabXK2wDvlA(System.Threading.ThreadStart)
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._k39DsboSFqAvcX2gaWs5Tk5Zl6Q(System.String[])

 }
{ TimeGenerated = 11/24/2020 11:30:46 AM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at OpenTK.Graphics.OpenGL.GL.DrawElements(OpenTK.Graphics.OpenGL.PrimitiveType, Int32, OpenTK.Graphics.OpenGL.DrawElementsType, Int32)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.RenderMesh(Vintagestory.API.Client.MeshRef)
   at Vintagestory.GameContent.AnvilWorkItemRenderer.OnRenderFrame(Single, Vintagestory.API.Client.EnumRenderStage)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(Vintagestory.API.Client.EnumRenderStage, Single)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(Vintagestory.API.Client.EnumRenderStage, Single)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single)
   at _VtIDI6oYFpyEcQSZBFso9UVxS9aA._ZnYzeuHqveMMiEvOnpahncAMjfg(Single)
   at _LSAAgZhw31Rqs2is6nnojfZBbQC._4BykKOCicJqCBHpyWIgTmxWrTrg(Single)
   at _LSAAgZhw31Rqs2is6nnojfZBbQC._6XmOxKoTYrFLRCGd58p58XW43nD(Single)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(System.Object, OpenTK.FrameEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.GameWindow.RaiseRenderFrame(Double, Double ByRef)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double, Double)
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._EEzpApWBQHtHR4iMJabXK2wDvlA(_ex0VSgRAdtsvhANmJHZHaf9ATWt, System.String[])
   at _IcGByoJhapvESnm6vaOawAHbkeU._EEzpApWBQHtHR4iMJabXK2wDvlA(System.Threading.ThreadStart)
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._k39DsboSFqAvcX2gaWs5Tk5Zl6Q(System.String[])

 }

**Comment by copygirl** [comment] 2020-11-27 16:04
Duplicate of #601.

**Closed by copygirl** 2020-11-27 16:04 UTC
Labels: status: duplicate
