### ISSUE TITLE
Repeatable Crash Caused by Barrels

### ISSUE THREAD

**Issue by nskjellum** [anegostudios/VintageStory-Issues#2037] opened 2022-07-22 18:16 UTC
**Game Version:** v1.17.0-pre.5 (Unstable)
**Platform:** Windows 
**Modded:** Yes 
**SP/MP:** Singleplayer

### Description
World has Crashed Repeatedly within specific time frame from when it first started occurring. Exiting, saving, then loading the world again has not removed the issue, leading me to believe it is happening at a specific time for each crash. 

### How to reproduce
Unknown

### Expected behavior
Not Crashing

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.0-pre.5 (Unstable)
Loaded Mods: buzzwords@1.0.0, game@1.17.0-pre.5, prospectorinfo@3.1.2, creative@1.17.0-pre.5, survival@1.17.0-pre.5
7/22/2022 2:08:24 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockBarrel.getContentMesh(ItemStack stack, BlockPos forBlockPos, String shapefilename) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Barrel\BlockBarrel.cs:line 208
   at Vintagestory.GameContent.BlockBarrel.GenMesh(ItemStack contentStack, ItemStack liquidContentStack, Boolean issealed, BlockPos forBlockPos) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Barrel\BlockBarrel.cs:line 152
   at Vintagestory.GameContent.BlockEntityBarrel.GenMesh() in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Barrel\BEBarrel.cs:line 320
   at Vintagestory.GameContent.BlockEntityBarrel.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldForResolving) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Barrel\BEBarrel.cs:line 292
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(Packet_BlockEntity p, ClientMain game) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Model\ClientChunk.cs:line 409
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(Packet_Server packet) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 808
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:line 1138
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 123
   at Vintagestory.Client.ScreenManager.Render(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:line 664
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:line 608
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 125
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 87
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 7/21/2022 7:34:51 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2076450798123546995, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.0.0
P3: 62d57a08
P4: StackHash_0000
P5: 0.0.0.0
P6: 00000000
P7: 00000000
P8: PCH_84
P9: 
P10: 

Attached files:
\\?\C:\Users\nskje\AppData\Local\Temp\WER1134.tmp.WERDataCollectionStatus.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER20F4.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2114.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2121.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2170.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_b874b446cbd7b8f567da0edfb9b69e8255fde2_bda381a7_f9516dce-82e5-4352-b506-47cb404fbe3a

Analysis symbol: 
Rechecking for solution: 0
Report Id: 110676a2-ea81-42dd-8155-a50643ed9f43
Report Status: 268566528
Hashed bucket: 9ccc308b5ae6fe94dcd108ffd7baf973
Cab Guid: 0 }
--------------
{ TimeGenerated = 7/21/2022 7:34:46 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.17.0.0, time stamp: 0x62d57a08
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0x00000000
Fault offset: 0x0000000000000000
Faulting process id: 0x83ac
Faulting application start time: 0x01d89d5a0ab789ea
Faulting application path: D:\Games\Vintagestory\Vintagestory.exe
Faulting module path: unknown
Report Id: 110676a2-ea81-42dd-8155-a50643ed9f43
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 7/21/2022 7:34:44 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FFA10864FD9
Stack:
 }
```

**Comment by Craluminum2413** [comment] 2022-07-22 18:19
Duplicate of #2021

**Closed by Craluminum2413** 2022-07-22 18:19 UTC
Labels: status: new
