### ISSUE TITLE
A crash when clicking the edit button for a world on the worlds menu.

### ISSUE THREAD

**Issue by demulcent** [anegostudios/VintageStory-Issues#3324] opened 2023-12-21 05:09 UTC
### Game Version

1.18.15

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The game crashed when I clicked the "edit" button on a world after exiting another world. The world I exited was a creative world. The world I was trying to delete was a "playstyle-default" world. The "playstyle-default" world was created by disabling all mods, including the vanilla ones(creative, survival, and essentials) and creating a world. 

### How to reproduce

1. Be in a creative world. 2. Leave the creative world. 3. Press the "edit button on a separate world(may have to be a "playstyle-default" world. 4. The game may crash.

### Logs

Running on 64 bit Windows with 16316 MB RAM
Game Version: v1.18.15 (Stable)
12/21/2023 12:00:55 AM: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Common.WorldConfig.loadWorldConfigValuesFromPlaystyle() in VintagestoryLib\Common\Config\WorldConfig.cs:line 108
   at Vintagestory.Common.WorldConfig.selectPlayStyle(String playstylecode) in VintagestoryLib\Common\Config\WorldConfig.cs:line 99
   at Vintagestory.Common.WorldConfig.loadFromSavegame(SaveGame savegame) in VintagestoryLib\Common\Config\WorldConfig.cs:line 57
   at Vintagestory.Client.GuiScreenSingleplayerModify.initGui(SaveGame savegame) in VintagestoryLib\Client\MainMenu\Screens\Singleplayer\GuiScreenSingleplayerModify.cs:line 52
   at Vintagestory.Client.GuiScreenSingleplayerModify.OnScreenLoaded() in VintagestoryLib\Client\MainMenu\Screens\Singleplayer\GuiScreenSingleplayerModify.cs:line 176
   at Vintagestory.Client.ScreenManager.LoadScreen(GuiScreen screen) in VintagestoryLib\Client\ScreenManager.cs:line 938
   at Vintagestory.Client.GuiScreenSingleplayer.OnClickCellRight(Int32 cellIndex) in VintagestoryLib\Client\MainMenu\Screens\Singleplayer\GuiScreenSingleplayer.cs:line 158
   at Vintagestory.API.Client.GuiElementMainMenuCell.OnMouseUpOnElement(MouseEvent args, Int32 elementIndex) in VintagestoryApi\Client\UI\Elements\Impl\Misc\GuiElementMainMenuCell.cs:line 320
   at Vintagestory.API.Client.GuiElementCellList`1.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementCellList.cs:line 241
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 440
   at GuiScreen.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\MainMenu\Screens\Special\GuiScreen.cs:line 204
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 209
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 11/25/2023 9:14:25 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2007150627803250050, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9CB7.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA0EE.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA11E.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA11C.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA13C.tmp.txt
\\?\C:\Users\andre\AppData\Local\Temp\WERA278.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_4dc88abb-f4fc-47ca-9299-032f1749cdb5

Analysis symbol: 
Rechecking for solution: 0
Report Id: ce95e054-2624-4e3d-a2b6-285ed9dc613c
Report Status: 268566528
Hashed bucket: 38dd2bbe130a69d3fbdad4dc94ea3d82
Cab Guid: 0 }
--------------
{ TimeGenerated = 11/25/2023 9:14:24 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9CB7.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA0EE.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA11E.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA11C.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA13C.tmp.txt
\\?\C:\Users\andre\AppData\Local\Temp\WERA278.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_cab_4dc88abb-f4fc-47ca-9299-032f1749cdb5

Analysis symbol: 
Rechecking for solution: 0
Report Id: ce95e054-2624-4e3d-a2b6-285ed9dc613c
Report Status: 131076
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 11/25/2023 9:14:22 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.15.0, time stamp: 0x64e841c5
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x35d0
Faulting application start time: 0x01da200c223be377
Faulting application path: C:\Users\andre\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\andre\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: ce95e054-2624-4e3d-a2b6-285ed9dc613c
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment] 2024-02-05 10:30
Duplicate of #2692

**Closed by Craluminum2413** 2024-02-05 10:30 UTC
Labels: status: new
