### ISSUE TITLE
Smithing pattern rotating on Iron anvil head

### ISSUE THREAD

**Issue by ArcticCuddlefish** [anegostudios/VintageStory-Issues#836] opened 2021-03-29 19:11 UTC
**Game Version:** v1.14.8
**Platform:** Windows
**Modded:** No

### Description
Iron anvil top keeps flipping pattern and then a crash D:

### How to reproduce
Make an iron anvil top - juggle cracking slag off of blooms, heating bars, and slapping them onto and anvil top. The first two added fine, but then I had to reheat the head. When I put it back onto my bronze anvil, the pattern had flipped, such that my completed horn was now on the wrong side and needed to be rehammered. After working that most of the way through, I needed to reheat again. While it heated, I prepared my fourth bar from a bloom that had been heating. Took the new bar off, put the anvil head down, and added the iron... only to find the pattern had flipped back T_T

In the middle of smithing it into shape again, the game crashed. I'd been already having that problem with making iron bars, but if you follow the forge the correct shape, cut off the excess, and then knock one spot out of place and put it back, it'll count, even if it doesn't match the prescribed pattern. As long as the product is right, it's good. With the anvil, though, that's far too difficult to be worth it :(

I should note my anvil is against a wall with fire on a raised block to the right, and the forge on the left. In order to access different parts, I need to rotate with right click. On iron bars rotating will shift the pattern so that it's sometimes wrong by one voxel space both directions (eg, shit all blocks up and right one to fit the new pattern spacing), but the anvil pattern rotates with the anvil accurately and without fail. Just that sometimes when I put it down, it maps it backwards, and there's no clear way to rotate just the pattern or piece, at least not that I can see. I've tried repeating the steps, heating the anvil top and replacing it, just picking it up and setting it down, but no effect. I'm definitely moving my anvil out into the floor T_T

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.8 (Stable)3/29/2021 11:58:22 AM: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.BlockEntityAnvil.OnUpset(Vec3i voxelPos, BlockFacing towardsFace)
   at Vintagestory.GameContent.BlockEntityAnvil.OnUseOver(IPlayer byPlayer, Vec3i voxelPos, BlockSelection blockSel)
   at Vintagestory.GameContent.ItemHammer.OnHeldAttackStop(Single secondsPassed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _jeEziyUSYl0BpbOxT46FYwj5VWL._t25VgrofhlXMw6hHEZh8JHhJz1A(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._DvzT6D0wN3fMakeuDyljJJ09hok(Single )
   at _idIkJkIueHHf3Oz2WNlBdD0E1XR._V5piYzG7beYPldE6UVxY58dqacE(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _YrS2W1MoaeqC4xqH8ItdZB6vADN._8t1BmEWVlCT9mjx5M0vFIzU9tif(_7T00Rjby4si0wyEBez5dXNqLm7h , String[] )
   at _ejKuc6cg0k8V39o8jDIzquyczbO._8t1BmEWVlCT9mjx5M0vFIzU9tif(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 3/25/2021 10:38:28 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1564561481470198046, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.8.0
P3: 10.0.19041.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Sweyo\AppData\Local\Temp\RDR9E65.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9E76.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9E77.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9E91.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9EC1.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 39516809-9b0a-42ee-ac1e-827b3e737aa3
Report Status: 268435456
Hashed bucket: 2422f0d2706eedebe5b67060c44a411e
Cab Guid: 0 }

**Comment by Craluminum2413** [comment] 2021-06-12 07:46
Duplicate of #800

**Comment by ArcticCuddlefish** [comment] 2021-06-12 20:01
#800 only references the crashing and a voxel not moving, not the smithing pattern shifting and causing an exceptional amount of extra work.

**Comment by Craluminum2413** [comment] 2021-06-17 21:15
Okay, but the crash is the same as in #740

**Comment by copygirl** [comment] 2022-01-06 18:14
Going to close this as duplicate of a much newer issue, so hopefully it will be notice by the developers: #1545

**Closed by copygirl** 2022-01-06 18:14 UTC
Labels: status: duplicate, target: survival
