### ISSUE TITLE
Pies with solid crusts don't stack before and after altering the top crust

### ISSUE THREAD

**Issue by Shurhaian** [anegostudios/VintageStory-Issues#2791] opened 2023-06-01 19:45 UTC
### Game Version

v1.18.3 (and earlier)

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

When putting a top crust on a pie, if one then just picks up the pie immediately, it will stack with other such pies. If instead you cycle the top crust until it's solid again, it will *not* stack with pies that have never been cycled, but *will* stack with any other pies cycled back to a solid top crust.

### How to reproduce

1. Prepare ingredients for at least two identical, fully filled and covered pies - 8 dough, 16 filling.
2. Build the first pie, including the standard top crust. Immediately collect it.
3. Build the second pie similarly. Collect it. They will stack.
4. Put one of the pies down (or make another pie). When the pie is built, cycle the top crust with dough or a knife until it's the same solid crust again.
5. Attempt to pick up the pie.
6. Pie will not stack with the pie that has never been cycled but has a solid top crust.
7. Put down the uncycled pie and cycle its top crust until it's solid again.
8. Pick up pie and it will stack again.

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2023-06-01 23:38
Duplicate of #1727

**Closed** 2023-06-01 23:39 UTC
Labels: status: duplicate
