### ISSUE TITLE
Game crash when sleeping

### ISSUE THREAD

**Issue by SuperBobGER** [anegostudios/VintageStory-Issues#384] opened 2020-02-26 22:03 UTC
**Game Version:** 1.12.5
**Platform:** Windows 10
**Modded:** No

### Description
I went to sleep and the game crashed.

### How to reproduce
Could not reproduce crash.

### Logs
```
Version: v1.12.5 (Stable)26.02.2020 22:53:19: Critical error occurred
System.IndexOutOfRangeException: Der Index war außerhalb des Arraybereichs.
   bei Vintagestory.API.MathTools.SimplexNoiseOctave.Evaluate(Double x, Double y, Double z)
   bei Vintagestory.API.MathTools.SimplexNoise.Noise(Double x, Double y, Double z)
   bei Vintagestory.GameContent.WeatherPattern.RegenCloudTileCache(Vec3i tileOffset)
   bei Vintagestory.GameContent.WeatherSystemClient.EnsureCloudTileCacheIsFresh(Vec3i tilePos)
   bei Vintagestory.GameContent.CloudRenderer.UpdateCloudTilesOffThread(Int32 changeSpeed)
   bei Vintagestory.GameContent.CloudRenderer.<.ctor>b__30_2()
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart()
-------------------------------

```

**Comment by copygirl** [comment] 2020-02-27 06:06
Duplicate of #368. Thanks for reporting though, this means the crash is still present in 1.12.5.

**Closed by copygirl** 2020-02-27 06:06 UTC
Labels: status: new, type: bug
