### ISSUE TITLE
Heavy light flicker when water flows

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#26] opened 2018-03-23 05:40 UTC
Observed in 1.5.1.6.
Google disc folder with video and screenshots: 
https://drive.google.com/open?id=1iQclN9CsMWfEj9AxiCPSkvKMbyftgt7v
Description:
Have an underground room 7x7x5. Place a water block in the center with a bucket. Surround with 4 dirt blocks to prevent flowing. Place planks block on top of water, a lantern on top of planks.
Now destroy one dirt block with shovel. Water will start flowing and spreading and light in the room will switch off and on approx twice a second until water stops spreading.

**Comment by tyronx** [comment] 2018-06-09 20:41
It's a race condition problem. The relighting thread occasionally has to clear all the light within a certain radius. But the chunk tesselation thread runs independent and so may end up tesselating a chunk exactly in the moment an area of light has been cleared. 

Not sure whats the optimum solution for this. 
a.) Non blocking: The relighting thread only works on a copy of the light array. Bug free but will slow down relighting due to constant copying back and forth of the light array. Might need some intelligent way to reduce copying during lighting heavy lighting work. Probably best way to solve it

b) Blocking: Disallow tesselation of relit chunks. This may cause chunks to update very slowly for the players if a relight heavy task is done on it. Probably pretty bad to do it this way

**Comment by tatsu011** [comment] 2018-06-09 20:45
I can confirm this issue, but on my end it's not consistent (which is interesting).

**Comment by Craluminum2413** [comment] 2021-06-10 06:53
Is it fixed? I can't reproduce it in the latest versions

**Comment by Th3Dilli** [comment] 2023-07-21 09:02
this seems to be fixed now, not sure when exactly but I think we can close this

**Closed by Th3Dilli** 2023-07-21 09:02 UTC
Labels: target: engine, status: confirmed
