### ISSUE TITLE
Crash in VSSurvivalMod\Systems\FruitTree\BEFruitTreePart.cs:line 175

### ISSUE THREAD

**Issue by FalcoGer** [anegostudios/VintageStory-Issues#3410] opened 2024-01-07 22:47 UTC
### Game Version

1.18.15.0

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Crashes seemingly random when exploring

### How to reproduce

Run around?

### Logs

```Log
Running on 64 bit Windows with 81844 MB RAM
Game Version: v1.18.15 (Stable)
07.01.2024 23:44:25: Critical error occurred
Loaded Mods: aculinaryartillery@1.0.15, advancedsmithing@1.3.0, betterbackpacks@1.0.0, betterbricks@1.1.1, bettercompost@1.0.1, betterruins@0.2.5, bettertraders@0.0.2, cellardoor@1.4.0, chiseltools@1.10.0, Clothez@1.0.0, hqzlights@1.1.1, extrachests@1.7.0, fancysky@1.0.6, fantasycreatures@0.6.4, foundrymod@1.0.0, fulldrop@1.0.0, harptechfix@1.2.4, ingotheating@1.0.2, knappingmastery@1.0.1, longerburntime@1.0.1, longertorchtime@1.0.1, meteoricexpansion@1.2.4, morecaveart@1.0.0, moreicons_cs@1.1.0, moreanimalloot@1.1.2, moreenemyloot@1.2.1, morefirewood@1.0.1, moreflaxloot@1.1.0, MoreTorchHolders@1.0.0, orepulverizer@1.1.1, pieontheshelf@1.0.0, potontheshelf@1.0.0, preservationmod@1.0.0, primitivesurvival@3.3.0, propickfix@1.0.0, rackablefirestarter@1.0.0, removenegativearmoreffects@1.0.0, shinglesandthethings@1.0.2-rc.1, scraps@1.0.0, she1fish@1.1.0, sleekdoorcraft@1.0.0, smokychimneys@1.0.0, spyglass@0.4.7, stacks@1.0.4, talldisplaycases@1.0.0, temporalstormgear@1.0.1, upgraderefractorybriks@1.0.1, usefulscrap@2.0.2, vertplanks@1.1.0, viescraftmachines@2.2.2, visibleore@1.0.1, game@1.18.15, wildcrafttrees@1.2.4, wildcraft@1.6.6, zyrails0break0down0tools@1.18.14, alchemy@1.6.21, alloycalculator@1.0.0, animalcages@2.2.0, animationmanagerlib@0.2.1, egocaribautomapmarkers@2.6.0, beehivekiln@1.5.1, betterbackpacksfixed@1.0.4, betterbackpacksnoiron@1.0.1, betterfirepit@1.1.2, blacksmithenhancements@1.0.3, blocksoverlay@2.5.0, helblockpick@2.1.1, butchering@1.1.5, carryon@1.6.1, cbetterfertilizer@1.0.1, chickenSit@2.0.0, clearerquartz@1.0.0, commonlib@2.2.0, composter@1.1.0, cooperativecombat@1.1.1, Crateful@1.2.7, electricity@0.0.10, expandedfoods@1.6.8, farmlanddropssoil@1.4.0, fixhandbookclutter@1.0.5, fromgoldencombs@1.4.25, glowingprojectiles@1.1.3, hudclock@3.3.0, mapautocenter@1.1.1, moreanimals@1.3.1, morestickcrafting@1.0.2, petai@1.8.1, pileful@1.1.2, claywheel@1.1.0, prospecttogether@1.2.4, recyclestorage@1.0.1, simplestep@1.0.8, slidingdoor@1.0.0, spawnhighlight@1.1.0, statushud@1.4.3, stillnecessaries@1.0.1, stonebakeoven@1.1.1, stonerailings@1.1.0, storageoptions@1.0.1, creative@1.18.15, vsinstruments@1.2.4, survival@1.18.15, VsWaypointSharing@1.0.6, wildfarmingrevival@1.1.6, workbenchexpansion@1.7.0, xlib@0.7.4, metalrecovery@0.1.19-pre.1, awearablelight@1.0.10, beehivekilnwithclay@1.0.0, betterstonerailings@1.0.0, bullseye@2.5.1, extraoverlays@1.3.1, feverstonehorses@1.5.5, feverstonewilds@1.4.3, foxtaming@1.3.0, fsmlib@0.1.13, sleekdoorglass@1.0.0, maltiezbows@1.0.1, morecandles@1.1.3, playercorpse@1.8.0, slanted_display_cases@1.0.0, stonequarry@3.1.7, undamageablet3@1.0.0, wolftaming@1.8.0, xskills@0.7.5, betterbackpacksforawearablelight@1.0.4, fsmbullseye@1.1.0, maltiezcrossbows@0.1.4, maltiezfirearms@0.3.9, wildcraftxskillspatch@0.2.0
System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
   at System.String.Format(String format, Object[] args)
   at Vintagestory.GameContent.ErrorReporter.Logger_EntryAdded(EnumLogType logType, String message, Object[] args) in VSEssentials\Systems\ErrorReporter.cs:line 164
   at Vintagestory.GameContent.BlockEntityFruitTreePart.getOrCreateTexPos(AssetLocation texturePath) in VSSurvivalMod\Systems\FruitTree\BEFruitTreePart.cs:line 175
   at Vintagestory.GameContent.BlockEntityFruitTreePart.GenFoliageMesh(Boolean withSticks, MeshData& foliageMesh, MeshData& sticksMesh)
   at Vintagestory.GameContent.BlockEntityFruitTreeFoliage.GenMesh() in VSSurvivalMod\Systems\FruitTree\BEFruitTreeFoliage.cs:line 38
   at Vintagestory.GameContent.BlockEntityFruitTreeFoliage.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldForResolving) in VSSurvivalMod\Systems\FruitTree\BEFruitTreeFoliage.cs:line 67
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(Packet_BlockEntity p, ClientMain game) in VintagestoryLib\Client\Model\ClientChunk.cs:line 429
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 414
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 757
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 07.01.2024 23:30:52, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Nicht verfügbar
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFFC5.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_2595c5a5-133c-408f-a4b7-17845a2b22c1

Analysis symbol: 
Rechecking for solution: 0
Report Id: 2df9b1ed-e3e1-48df-94ca-c4f00a062625
Report Status: 131172
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 07.01.2024 23:30:52, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Nicht verfügbar
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC1BE.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_36b9a5f8-c7a8-4881-8a53-825b2885bb71

Analysis symbol: 
Rechecking for solution: 0
Report Id: 269bc01a-3c6f-4aad-91f5-26b6ac132b57
Report Status: 131172
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 07.01.2024 23:30:52, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Nicht verfügbar
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD53F.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_8b97e242-8157-4e37-a37b-58f7e31fefa7

Analysis symbol: 
Rechecking for solution: 0
Report Id: 1f47cdf5-e064-41af-8746-41a324a38f9d
Report Status: 131172
Hashed bucket: 
Cab Guid: 0 }
```

**Comment by Craluminum2413** [comment] 2024-01-07 22:49
Most likely caused by mod

**Comment by FalcoGer** [comment] 2024-01-07 23:06
> Most likely caused by mod

probably, but should generate an error and write to log, not crash the game.

**Comment by Th3Dilli** [comment] 2024-02-13 14:13
I was not able to reproduce the error but now the game should not crash anymore 

will be in next release

**Closed by Th3Dilli** 2024-02-13 14:13 UTC
Labels: status: new
