### ISSUE TITLE
Game crash, suspected pit kiln issue. 

### ISSUE THREAD

**Issue by Tarod7** [anegostudios/VintageStory-Issues#1114] opened 2021-07-07 19:23 UTC
**Game Version:** 15 rc 1  
**Platform:** Windows 
**Modded:** No  

### Description
Crash

Only client crash server still up

version of this server has been updated several times.

went to check pit kilns and they're empty, then it crashed again when i right clicked the empty kiln.

First log for first crash, second for right click crash.

### How to reproduce
No idea, I was just mining. guessing pit kilns finished maybe?

### Expected behavior
no crash

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Running on 64 bit Windows with 64 GB RAM 
Version: v1.15.0-rc.1 (Unstable)7/7/2021 12:15:42 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityGroundStorage.DetermineStorageProperties(ItemSlot sourceSlot)
   at Vintagestory.GameContent.BlockEntityGroundStorage.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldForResolving)
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(_f47bFFjjZjqsZ07abkCWRRjJjq5 p, ClientMain game)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(_SPt7iF5LhXmcxMRSPZV1A0ZATGh packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _Hhyykp3OIyR3A9gDXvfRYXmIxHM._N2PKmadywKhrSAOGDRbet32cyTB(Single )
   at _GatfFd3kn5xATuUyKYscxn8d0CO._4TEOzZagWNPjzZVqfu2HCwbLFqC(Single )
   at _GatfFd3kn5xATuUyKYscxn8d0CO._x3D81oTSuYvhXUwgP6x9PwySgdc(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _woe4UEAalnRbwPXBTK09ZhdFcWO._5qgAk5LLuTcbcRWXQsq1b3Y8T8H(_arFvNaodTjXO5ObZ7eEgimkezLG , String[] )
   at _ZFpbvq06JtO6suJqmLDa8Hs9YeH._5qgAk5LLuTcbcRWXQsq1b3Y8T8H(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 7/6/2021 9:07:08 AM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.15.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 244c

Start Time: 01d77280cded26ba

Termination Time: 3

Application Path: C:\Users\tarod\AppData\Roaming\Vintagestory\Vintagestory.exe

Report Id: 0b17293b-5613-4801-aefc-8f5eceb615bb

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
--------------
{ TimeGenerated = 7/6/2021 9:07:07 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1225439024055515305, type 5
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.0.0
P3: 60df0588
P4: e41a
P5: 134217728
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5F72.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5F82.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5F81.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5F92.tmp.txt
\\?\C:\Users\tarod\AppData\Local\Temp\WER578.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_Vintagestory.exe_229d38c62b9f9870b87762a59a17df3979c5c289_57f52630_e4dc5df3-2f2c-4481-a0c7-eb12227c1f53

Analysis symbol: 
Rechecking for solution: 0
Report Id: 0b17293b-5613-4801-aefc-8f5eceb615bb
Report Status: 268435456
Hashed bucket: 7368f5c536f62cb91101a24cbabaf8a9
Cab Guid: 0 }
--------------
{ TimeGenerated = 6/15/2021 9:42:23 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1617108784218071861, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 10.0.19041.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\tarod\AppData\Local\Temp\RDR86A9.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER86AA.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER86BA.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER86C8.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER86E8.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: a19d4c72-14e8-4e42-af38-87ce9a134ab4
Report Status: 268435456
Hashed bucket: 53ec02d71894ee5b26711fdf167b6335
Cab Guid: 0 }
```
```
Running on 64 bit Windows with 64 GB RAM 
Version: v1.15.0-rc.1 (Unstable)7/7/2021 12:20:39 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityGroundStorage.DetermineStorageProperties(ItemSlot sourceSlot)
   at Vintagestory.GameContent.BlockEntityGroundStorage.OnPlayerInteract(IPlayer player, BlockSelection bs)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Block selectedBlock, BlockSelection blockSelection)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _Hhyykp3OIyR3A9gDXvfRYXmIxHM._kL6wH0r9p9pVrlTOg8ZqnOfBCeq(Single )
   at _GatfFd3kn5xATuUyKYscxn8d0CO._4TEOzZagWNPjzZVqfu2HCwbLFqC(Single )
   at _GatfFd3kn5xATuUyKYscxn8d0CO._x3D81oTSuYvhXUwgP6x9PwySgdc(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _woe4UEAalnRbwPXBTK09ZhdFcWO._5qgAk5LLuTcbcRWXQsq1b3Y8T8H(_arFvNaodTjXO5ObZ7eEgimkezLG , String[] )
   at _ZFpbvq06JtO6suJqmLDa8Hs9YeH._5qgAk5LLuTcbcRWXQsq1b3Y8T8H(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 7/6/2021 9:07:08 AM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.15.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 244c

Start Time: 01d77280cded26ba

Termination Time: 3

Application Path: C:\Users\tarod\AppData\Roaming\Vintagestory\Vintagestory.exe

Report Id: 0b17293b-5613-4801-aefc-8f5eceb615bb

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
--------------
{ TimeGenerated = 7/6/2021 9:07:07 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1225439024055515305, type 5
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.0.0
P3: 60df0588
P4: e41a
P5: 134217728
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5F72.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5F82.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5F81.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5F92.tmp.txt
\\?\C:\Users\tarod\AppData\Local\Temp\WER578.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_Vintagestory.exe_229d38c62b9f9870b87762a59a17df3979c5c289_57f52630_e4dc5df3-2f2c-4481-a0c7-eb12227c1f53

Analysis symbol: 
Rechecking for solution: 0
Report Id: 0b17293b-5613-4801-aefc-8f5eceb615bb
Report Status: 268435456
Hashed bucket: 7368f5c536f62cb91101a24cbabaf8a9
Cab Guid: 0 }
--------------
{ TimeGenerated = 6/15/2021 9:42:23 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1617108784218071861, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 10.0.19041.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\tarod\AppData\Local\Temp\RDR86A9.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER86AA.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER86BA.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER86C8.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER86E8.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: a19d4c72-14e8-4e42-af38-87ce9a134ab4
Report Status: 268435456
Hashed bucket: 53ec02d71894ee5b26711fdf167b6335
Cab Guid: 0 }
```

**Comment by copygirl** [comment] 2021-07-07 19:24
Duplicate of #1111, but thank you for reporting!

**Closed by copygirl** 2021-07-07 19:24 UTC
Labels: status: duplicate
