### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by aruacool** [anegostudios/VintageStory-Issues#3014] opened 2023-08-11 13:12 UTC
### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

My game crashed randomly as i was exploring a forest

### How to reproduce

absolutely no idea how, closest thing i got is that i was alt-tabbing a bunch before it happened

### Logs

Running on 64 bit Windows with 32671 MB RAM
Game Version: v1.18.8 (Stable)
11/08/2023 16:08:48: Critical error occurred
Loaded Mods: game@1.18.8, creative@1.18.8, survival@1.18.8
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityMycelium.setMushroomBlock(Block block) in VSSurvivalMod\BlockEntity\BEMycelium.cs:line 198
   at Vintagestory.GameContent.BlockEntityMycelium.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldAccessForResolve) in VSSurvivalMod\BlockEntity\BEMycelium.cs:line 346
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(Packet_BlockEntity p, ClientMain game) in VintagestoryLib\Client\Model\ClientChunk.cs:line 429
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 414
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 757
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 75
   at OpenTK.Windowing.Desktop.GameWindow.DispatchRenderFrame()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 312
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 11/08/2023 13:40:02, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.8.0, time stamp: 0x6492041a
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x94c
Faulting application start time: 0x0x1d9cc3b2183d8a3
Faulting application path: C:\Users\MyUSER\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\MyUSER\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 8aab33a4-728c-49b9-b648-6ef665b26564
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 11/08/2023 12:49:54, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.8.0, time stamp: 0x6492041a
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x4148
Faulting application start time: 0x0x1d9cc38d61aab32
Faulting application path: C:\Users\MyUSER\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\MyUSER\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 88abf01c-50be-48b6-905b-065632879062
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 11/08/2023 12:10:18, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.8.0, time stamp: 0x6492041a
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x4ee8
Faulting application start time: 0x0x1d9cc3394a950f3
Faulting application path: C:\Users\MyUSER\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\MyUSER\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: bee37c35-b559-4b58-b421-730710a39bf8
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment] 2023-08-11 13:35
Duplicate of #2873

**Closed by Craluminum2413** 2023-08-11 13:35 UTC
Labels: status: new
