### ISSUE TITLE
Game will not start

### ISSUE THREAD

**Issue by REDACTED242** [anegostudios/VintageStory-Issues#603] opened 2020-10-01 19:17 UTC
**Game Version:** 1.13.4
**Platform:** Windows 8
**Modded:** No 

### Description
I try to launch it and it won't start. Just bought the game.

### How to reproduce

3. It crashes / doesn't do the thing.

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Running on 64 bit Windows with 4 GB RAM 
Version: v1.13.4 (Stable)10/1/2020 2:14:19 PM: Critical error occurred
System.MissingMethodException: Method not found: 'Void System.Runtime.GCSettings.set_LargeObjectHeapCompactionMode(System.Runtime.GCLargeObjectHeapCompactionMode)'.
   at Vintagestory.Client.NoObf.ClientPlatformWindows..ctor(_6Ki7onGUDN2hMDvAS3I5KRRsLrr logger)
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._EEzpApWBQHtHR4iMJabXK2wDvlA(_ex0VSgRAdtsvhANmJHZHaf9ATWt , String[] )
   at _IcGByoJhapvESnm6vaOawAHbkeU._EEzpApWBQHtHR4iMJabXK2wDvlA(ThreadStart )
-------------------------------

```

**Comment by copygirl** [comment] 2020-10-02 06:46
Duplicate of #591.

But do please let me know if the fix provided in the linked issue works for you.

**Closed by copygirl** 2020-10-02 06:46 UTC
Labels: status: duplicate
