### ISSUE TITLE
Crash at random times 

### ISSUE THREAD

**Issue by Esseit** [anegostudios/VintageStory-Issues#4658] opened 2024-12-11 07:47 UTC
### Game Version

1.20.0-rc.1

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

The game is crashing at seemingly random points during play, ill be walking around my starter base or making caly pots and the crash just happens. no warning or consistency as to what may cause it. i am running mods, but I'm just not sure what mod may be causing this or if its the RC version itself

### How to reproduce

none, happens at random 

### Logs

[```Log```](https://pastebin.com/rPQT7QRr)

**Comment by Craluminum2413** [comment] 2024-12-11 11:16
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4243

**Closed by Craluminum2413** 2024-12-11 11:16 UTC
Labels: status: new
