### ISSUE TITLE
Game Crashes with Rotten Food in a bowl and right click on a crook with food

### ISSUE THREAD

**Issue by wbhester** [anegostudios/VintageStory-Issues#3431] opened 2024-01-13 06:43 UTC
### Game Version

v1.18.15

### Platform

Windows

### Modded

None

### SP/MP

Multiplayer

### Description

Playing a remote server in multiplayer. I had a bowl with rotten food in it and I tried to pull a meal out of a crook. The game crashed with the message that I had been disconnected that was displayed to the other players. There were two other players at the time.

### How to reproduce

1. Get a meal in a bowl and allow it to rot. (Beef stew with cranberries if that matters)
2. Have a meal in a crook (Again it was beef stew with cranberries)
3. Right click 2 or 3 times on the crook with the bowl in hand

### Logs

```12.1.2024 22:50:59 [Notification] Client logger started.
12.1.2024 22:50:59 [Notification] Game Version: v1.18.15 (Stable)
12.1.2024 22:50:59 [Notification] OpenAL Initialized. Available Mono/Stereo Sources: 255/1
12.1.2024 22:50:59 [Notification] Process path: G:\Vintagestory\Vintagestory.exe
12.1.2024 22:50:59 [Notification] Operating System: Windows 10.0.22621.0
12.1.2024 22:50:59 [Notification] CPU Cores: 24
12.1.2024 22:50:59 [Notification] Available RAM: 32693 MB
12.1.2024 22:50:59 [Notification] Graphics Card Vendor: NVIDIA Corporation
12.1.2024 22:50:59 [Notification] Graphics Card Version: 3.3.0 NVIDIA 537.13
12.1.2024 22:50:59 [Notification] Graphics Card Renderer: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
12.1.2024 22:50:59 [Notification] Graphics Card ShadingLanguageVersion: 3.30 NVIDIA via Cg compiler
12.1.2024 22:50:59 [Notification] GL.MaxVertexUniformComponents: 4096
12.1.2024 22:50:59 [Notification] GL.MaxUniformBlockSize: 65536
12.1.2024 22:50:59 [Notification] Cairo Graphics Version: 1.17.3
12.1.2024 22:50:59 [Notification] OpenAL Version: 1.1 ALSOFT 1.23.0
12.1.2024 22:50:59 [Notification] C# Framework: .net 7.0.15
12.1.2024 22:50:59 [Notification] Zstd Version: 1.5.5
12.1.2024 22:50:59 [Notification] Start discovering assets
12.1.2024 22:50:59 [Notification] Found 23 base assets in category lang
12.1.2024 22:50:59 [Notification] Found 0 base assets in category patches
12.1.2024 22:50:59 [Notification] Found 22 base assets in category config
12.1.2024 22:50:59 [Notification] Found 0 base assets in category worldproperties
12.1.2024 22:50:59 [Notification] Found 46 base assets in category sounds
12.1.2024 22:50:59 [Notification] Found 97 base assets in category shapes
12.1.2024 22:50:59 [Notification] Found 72 base assets in category shaders
12.1.2024 22:50:59 [Notification] Found 16 base assets in category shaderincludes
12.1.2024 22:50:59 [Notification] Found 131 base assets in category textures
12.1.2024 22:50:59 [Notification] Found 4 base assets in category music
12.1.2024 22:50:59 [Notification] Found 0 base assets in category dialog
12.1.2024 22:50:59 [Notification] Found 411 base assets in total
12.1.2024 22:50:59 [Notification] Loading sounds
12.1.2024 22:50:59 [Notification] Sounds loaded
12.1.2024 22:50:59 [Notification] (Re-)loaded frame buffers
12.1.2024 22:50:59 [Notification] Loaded Shaderprogramm for render pass .
12.1.2024 22:50:59 [Notification] Begin loading shaders
12.1.2024 22:50:59 [Notification] Load shaders now
12.1.2024 22:50:59 [Notification] Loading shaders...
12.1.2024 22:50:59 [Notification] Loaded Shaderprogramm for render pass standard.
12.1.2024 22:50:59 [Notification] Loaded Shaderprogramm for render pass particlescube.
12.1.2024 22:50:59 [Notification] Loaded Shaderprogramm for render pass particlesquad.
12.1.2024 22:50:59 [Notification] Loaded Shaderprogramm for render pass sky.
12.1.2024 22:50:59 [Notification] Loaded Shaderprogramm for render pass nightsky.
12.1.2024 22:50:59 [Notification] Loaded Shaderprogramm for render pass woittest.
12.1.2024 22:50:59 [Notification] Loaded Shaderprogramm for render pass transparentcompose.
12.1.2024 22:50:59 [Notification] Loaded Shaderprogramm for render pass debugdepthbuffer.
12.1.2024 22:50:59 [Notification] Loaded Shaderprogramm for render pass helditem.
12.1.2024 22:51:00 [Notification] Loaded Shaderprogramm for render pass chunkopaque.
12.1.2024 22:51:00 [Notification] Loaded Shaderprogramm for render pass chunkliquid.
12.1.2024 22:51:00 [Notification] Loaded Shaderprogramm for render pass decals.
12.1.2024 22:51:00 [Notification] Loaded Shaderprogramm for render pass final.
12.1.2024 22:51:00 [Notification] Loaded Shaderprogramm for render pass gui.
12.1.2024 22:51:00 [Notification] Loaded Shaderprogramm for render pass blur.
12.1.2024 22:51:00 [Notification] Loaded Shaderprogramm for render pass chunktransparent.
12.1.2024 22:51:00 [Notification] Loaded Shaderprogramm for render pass findbright.
12.1.2024 22:51:00 [Notification] Loaded Shaderprogramm for render pass chunktopsoil.
12.1.2024 22:51:00 [Notification] Loaded Shaderprogramm for render pass godrays.
12.1.2024 22:51:00 [Notification] Loaded Shaderprogramm for render pass autocamera.
12.1.2024 22:51:00 [Notification] Loaded Shaderprogramm for render pass blockhighlights.
12.1.2024 22:51:00 [Notification] Loaded Shaderprogramm for render pass wireframe.
12.1.2024 22:51:00 [Notification] Loaded Shaderprogramm for render pass entityanimated.
12.1.2024 22:51:00 [Notification] Loaded Shaderprogramm for render pass luma.
12.1.2024 22:51:00 [Notification] Loaded Shaderprogramm for render pass blit.
12.1.2024 22:51:00 [Notification] Loaded Shaderprogramm for render pass particlesquad2d.
12.1.2024 22:51:00 [Notification] Loaded Shaderprogramm for render pass shadowmapentityanimated.
12.1.2024 22:51:00 [Notification] Loaded Shaderprogramm for render pass shadowmapgeneric.
12.1.2024 22:51:00 [Notification] Loaded Shaderprogramm for render pass texture2texture.
12.1.2024 22:51:00 [Notification] Loaded Shaderprogramm for render pass celestialobject.
12.1.2024 22:51:00 [Notification] Loaded Shaderprogramm for render pass guitopsoil.
12.1.2024 22:51:00 [Notification] Loaded Shaderprogramm for render pass colorgrade.
12.1.2024 22:51:00 [Notification] Loaded Shaderprogramm for render pass guigear.
12.1.2024 22:51:00 [Notification] Loaded Shaderprogramm for render pass ssao.
12.1.2024 22:51:00 [Notification] Loaded Shaderprogramm for render pass bilateralblur.
12.1.2024 22:51:00 [Notification] Cached session key is valid, validating with server
12.1.2024 22:51:00 [Notification] Server validation response: Good
12.1.2024 22:51:00 [Notification] Will search the following paths for mods:
12.1.2024 22:51:00 [Notification]     G:\Vintagestory\Mods
12.1.2024 22:51:00 [Notification]     C:\Users\heste\AppData\Roaming\VintagestoryData\Mods
12.1.2024 22:51:03 [Notification] Connecting to 108.194.209.240...
12.1.2024 22:51:03 [Error] Unable to read srv record, will connect to supplied hostname. Error: Non-Existent Domain
;; ->>HEADER<<- opcode: Query, status: Non-Existent Domain, id: 63993
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
12.1.2024 22:51:04 [Notification] Initialized GUI Manager
12.1.2024 22:51:04 [Notification] Initialized Server Connection
12.1.2024 22:51:04 [Notification] Connected to server, downloading data...
0 kilobyte received
12.1.2024 22:51:05 [Notification] Loading and pre-starting client side mods...
12.1.2024 22:51:05 [Notification] Will search the following paths for mods:
12.1.2024 22:51:05 [Notification]     G:\Vintagestory\Mods
12.1.2024 22:51:05 [Notification]     C:\Users\heste\AppData\Roaming\VintagestoryData\Mods
12.1.2024 22:51:05 [Notification] Found 3 mods (0 disabled)
12.1.2024 22:51:05 [Notification] Mods, sorted by dependency: game, creative, survival
12.1.2024 22:51:05 [Notification] Instantiated 101 mod systems from 3 enabled mods
12.1.2024 22:51:05 [Notification] Done loading and pre-starting client side mods.
12.1.2024 22:51:05 [Notification] External Origins in load order: modorigin@G:\Vintagestory\assets\creative\, modorigin@G:\Vintagestory\assets\survival\
12.1.2024 22:51:05 [Notification] Found 0 external assets in category lang
12.1.2024 22:51:05 [Notification] Found 9 external assets in category patches
12.1.2024 22:51:05 [Notification] Found 54 external assets in category config
12.1.2024 22:51:05 [Notification] Found 25 external assets in category worldproperties
12.1.2024 22:51:05 [Notification] Found 348 external assets in category sounds
12.1.2024 22:51:05 [Notification] Found 3179 external assets in category shapes
12.1.2024 22:51:05 [Notification] Found 13 external assets in category shaders
12.1.2024 22:51:05 [Notification] Found 0 external assets in category shaderincludes
12.1.2024 22:51:05 [Notification] Found 5243 external assets in category textures
12.1.2024 22:51:05 [Notification] Found 67 external assets in category music
12.1.2024 22:51:05 [Notification] Found 18 external assets in category dialog
12.1.2024 22:51:05 [Notification] Found 0 external assets in category compatibility
12.1.2024 22:51:05 [Notification] Reloaded lang file now with mod assets
12.1.2024 22:51:05 [Notification] Compatibility lib: 0 assets added, 0 assets replaced.
12.1.2024 22:51:05 [Notification] JsonPatch Loader: 2 patches total, no issues
12.1.2024 22:51:05 [Notification] Processed server identification
12.1.2024 22:51:05 [Notification] Map initialized
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass anvilworkitem.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass lines.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass aurora.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass rift.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass sleepoverlay.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass machinegear.
12.1.2024 22:51:05 [Notification] Started 64 systems on Client:
12.1.2024 22:51:05 [Notification]     Mod 'VSEssentials.dll' (game):
12.1.2024 22:51:05 [Notification]         Vintagestory.ServerMods.Core
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.EntityPartitioning
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.ErrorReporter
12.1.2024 22:51:05 [Notification]         Vintagestory.ServerMods.ModCompatiblityUtil
12.1.2024 22:51:05 [Notification]         Vintagestory.ServerMods.NoObf.ModJsonPatchLoader
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.ModSystemDormancyStateChecker
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.ModSystemItemRendererOptimizer
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.FallingBlockParticlesModSystem
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.CharacterExtraDialogs
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.EntityNameTagRendererRegistry
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.POIRegistry
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.RoomRegistry
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.WeatherSystemCommands
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.WeatherSystemClient
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.WorldMapManager
12.1.2024 22:51:05 [Notification]         Vintagestory.ServerMods.LoadColorMaps
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.ClothManager
12.1.2024 22:51:05 [Notification]     Mod 'VSSurvivalMod.dll' (survival):
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.ModSystemControlPoints
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.SurvivalCoreSystem
12.1.2024 22:51:05 [Notification]         Vintagestory.Client.NoObf.ModSystemBossHealthBars
12.1.2024 22:51:05 [Notification]         Vintagestory.ServerMods.DebugSystem
12.1.2024 22:51:05 [Notification]         Vintagestory.ServerMods.UpgradeTasks
12.1.2024 22:51:05 [Notification]         Vintagestory.ServerMods.ModSystemDetailModeSync
12.1.2024 22:51:05 [Notification]         Vintagestory.ServerMods.ModSystemTiledDungeonGenerator
12.1.2024 22:51:05 [Notification]         Vintagestory.ServerMods.GenFromHeightmap
12.1.2024 22:51:05 [Notification]         Vintagestory.ServerMods.GenMaps
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.MyceliumSystem
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.ModSystemSupportBeamPlacer
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.ModSystemCatchCreature
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.ModSystemGliding
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.ModSystemMeasuringRope
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.ScreenshakeToClientModSystem
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.ResoArchivesSpawnConditions
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.ModSystemAuction
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.ModSystemBlockReinforcement
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.Core
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.ModSystemBoatingSound
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.CharacterSystem
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.MealMeshCache
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.DialogueSystem
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.FruitingSystem
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.ModSystemHandbook
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.ModSystemTutorial
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.ModSystemNightVision
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.ModJournal
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.LiquidItemStackRenderer
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.ModSystemStructureLocator
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.ModLootRandomizer
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.MicroBlockModelCache
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.ModSystemRifts
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.ModSystemRiftWeather
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.ModSleeping
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.TeleporterManager
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.ModTemperature
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.SystemTemporalStability
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.TemporalStabilityEffects
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.ModSystemWearableStats
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.ModSystemEditableBook
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.Mechanics.MechanicalPowerMod
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.TradeHandbookInfo
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.RecipeRegistrySystem
12.1.2024 22:51:05 [Notification]         Vintagestory.GameContent.TraderOutfits
12.1.2024 22:51:05 [Notification]     Mod 'VSCreativeMod.dll' (creative):
12.1.2024 22:51:05 [Notification]         Vintagestory.ServerMods.Core
12.1.2024 22:51:05 [Notification]         Vintagestory.ServerMods.WorldEdit.WorldEdit
12.1.2024 22:51:05 [Notification] Loading shaders...
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass standard.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass particlescube.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass particlesquad.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass sky.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass nightsky.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass woittest.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass transparentcompose.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass debugdepthbuffer.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass helditem.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass chunkopaque.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass chunkliquid.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass decals.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass final.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass gui.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass blur.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass chunktransparent.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass findbright.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass chunktopsoil.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass godrays.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass autocamera.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass blockhighlights.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass wireframe.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass entityanimated.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass luma.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass blit.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass particlesquad2d.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass shadowmapentityanimated.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass shadowmapgeneric.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass texture2texture.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass celestialobject.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass guitopsoil.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass colorgrade.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass guigear.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass ssao.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass bilateralblur.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass anvilworkitem.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass lines.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass aurora.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass rift.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass sleepoverlay.
12.1.2024 22:51:05 [Notification] Loaded Shaderprogramm for render pass machinegear.
12.1.2024 22:51:05 [Notification] Reloaded shaders now with mod assets
12.1.2024 22:51:05 [Notification] Reloaded sounds, now with mod assets
12.1.2024 22:51:05 [Notification] Received level init
12.1.2024 22:51:05 [Notification] Connected to server, downloading data...
297 kilobyte received
12.1.2024 22:51:06 [Notification] Connected to server, downloading data...
745 kilobyte received
12.1.2024 22:51:06 [Notification] Connected to server, downloading data...
936 kilobyte received
12.1.2024 22:51:06 [Notification] Received server assets
12.1.2024 22:51:06 [Notification] Composed 1 4096x4096 entities texture atlases from 384 textures
12.1.2024 22:51:07 [Notification] Received 3040 item types from server
12.1.2024 22:51:07 [Notification] Loaded 9252 block types from server
12.1.2024 22:51:07 [Notification] Collected 1802 shapes to tesselate.
12.1.2024 22:51:07 [Notification] Composed 1 4096x4096 items texture atlases from 1593 textures
12.1.2024 22:51:08 [Notification] Composed 1 4096x4096 blocks texture atlases from 4310 textures
12.1.2024 22:51:08 [Notification] Server assets loaded
12.1.2024 22:51:08 [Notification] Loaded Shaderprogramm for render pass instanced.
12.1.2024 22:51:08 [Notification] Loading world map cache db...
12.1.2024 22:51:08 [Notification] Initialized Music Engine
12.1.2024 22:51:09 [Notification] Texture size is 32 so decal atlas size of 128x128 should suffice
12.1.2024 22:51:10 [Notification] Blocks tesselated
12.1.2024 22:51:10 [Notification] Received level finalize
12.1.2024 22:51:10 [Notification] Loaded Shaderprogramm for render pass clouds.
12.1.2024 22:51:10 [Notification] ===============================================================
12.1.2024 22:51:10 [Notification] (^_^) No issues captured during startup
12.1.2024 22:51:10 [Notification] ===============================================================
12.1.2024 22:51:19 [Notification] Finished fully loading sounds (async)
12.1.2024 22:51:20 [Notification] Disconnected by the server (An action you (or your client) did caused an unhandled exception)
12.1.2024 22:51:20 [Notification] Destroying game session, waiting up to 200ms for client threads to exit
12.1.2024 22:51:21 [Notification] Exiting current game to disconnected screen, reason: An action you (or your client) did caused an unhandled exception
12.1.2024 22:51:29 [Warning] Texture with texture id 48 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
12.1.2024 22:51:29 [Warning] Texture with texture id 455 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
12.1.2024 22:51:29 [Warning] Texture with texture id 456 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
12.1.2024 22:51:29 [Warning] Texture with texture id 454 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
12.1.2024 22:51:29 [Warning] Texture with texture id 453 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
12.1.2024 22:51:29 [Warning] Texture with texture id 451 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
12.1.2024 22:51:29 [Warning] Texture with texture id 452 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
12.1.2024 22:51:29 [Warning] Texture with texture id 450 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
12.1.2024 22:51:29 [Warning] Texture with texture id 449 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
12.1.2024 22:51:29 [Warning] Texture with texture id 447 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
12.1.2024 22:51:29 [Warning] Texture with texture id 448 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
12.1.2024 22:51:29 [Warning] Texture with texture id 446 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
12.1.2024 22:51:29 [Warning] Texture with texture id 445 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
12.1.2024 22:51:29 [Warning] Texture with texture id 441 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
12.1.2024 22:51:29 [Warning] Texture with texture id 442 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
12.1.2024 22:51:29 [Warning] Texture with texture id 440 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
12.1.2024 22:51:29 [Warning] Texture with texture id 443 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
12.1.2024 22:51:29 [Warning] Texture with texture id 439 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
12.1.2024 22:51:29 [Warning] Texture with texture id 438 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
12.1.2024 22:51:29 [Warning] Texture with texture id 457 is leaking memory, missing call to Dispose. Set env var TEXTURE_DEBUG_DISPOSE to get allocation trace.
12.1.2024 22:51:46 [Notification] Exiting game now. Server running=False. Exit reason: Main screen quit button was pressed```

**Comment by Craluminum2413** [comment] 2024-01-13 06:53
Does it happen in 1.19?

**Comment by Th3Dilli** [comment] 2024-02-08 12:11
so far I was not able to reproduce this on 1.18.15 or 1.19.3

If you figure out how to reproduce that let use know

for now ill close this since it may have been caused by something else?

**Closed by Th3Dilli** 2024-02-08 12:11 UTC
Labels: status: incomplete, status: can't reproduce
