### ISSUE TITLE
system.aray.empty

### ISSUE THREAD

**Issue by biodark** [anegostudios/VintageStory-Issues#1354] opened 2021-10-11 10:06 UTC
**Game Version:** 1.15.6
**Platform:** Windows
**Modded:** No 
hi the game does not start and gives an error
Running on 64 bit Windows with 8 GB RAM 
Version: v1.15.6 (Stable)11.10.2021 13:55:52: Critical error occurred
System.MissingMethodException: Метод не найден: "!!0[] System.Array.Empty()".
   в _AP7WmUsyUYdtMlYkY1BnRzdg2ff._hdLzsTvaMxWzkcSVpoYJjLUlwAJ(_JsdNdoNt0XlKjq0tdupAM4oO6wn , String[] )
   в _0VK7uR5tb5rsnOGVuF83gJuGw9D._hdLzsTvaMxWzkcSVpoYJjLUlwAJ(ThreadStart )
-------------------------------
help please
sorry for bad eanglish

**Comment by copygirl** [comment] 2021-10-11 10:10
Duplicate of #1303.

> I believe this should be fixed by installing .NET Framework 4.6.1 or 4.6.2.
> Go [here](https://dotnet.microsoft.com/download/dotnet-framework/net462) and download the Runtime for this version of .NET.

**Closed as completed by copygirl** 2021-10-11 10:10 UTC
Labels: status: duplicate
