### ISSUE TITLE
First person hand animation stuck after putting down shield

### ISSUE THREAD

**Issue by Aonorai** [anegostudios/VintageStory-Issues#3454] opened 2024-01-17 22:54 UTC
### Game Version

v1.19

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

Updated and played a bit with the new hands on first person mode. Picked up a shield, it was great, tried to put it down using shift+ctrl+right click and managed to place it but the player hand got stuck in defense mode (using the shield). To resolve it I picked up the shield again and put it down very fast.

### Screenshots

![Untitled](https://github.com/anegostudios/VintageStory-Issues/assets/91459310/60f9abee-a6b8-4faa-8c1a-2110ca933b17)

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2024-01-18 05:25
Duplicate of #3361

**Closed** 2024-01-18 05:25 UTC
Labels: status: duplicate
