### ISSUE TITLE
1.17-pre5. Game crash during various interactions with the barrel (tannin, salt, crudled milk etc)

### ISSUE THREAD

**Issue by DonKamaro** [anegostudios/VintageStory-Issues#2050] opened 2022-07-25 23:26 UTC
**Game Version:** 1.17 pre5
**Platform:** Windows
**Modded:** No (only default mode by Tyron, like Creative Mode, Survival Mode and Essentials)
**SP/MP:** Singleplayer

### Description

The game crashes when trying to interact with the barrel. I tested the following combinations:
Put an oak log in a barrel of water = crash;
Put an acacia log in a barrel of water = crash; 
Put salt in a barrel of water = crash.
Put salt in a barrel of milk = crash.
Put pickled vegetable in a barrel of milk = crash.

The same result if you put these materials in a barrel without water. But at the same time, lime does not cause crash. I've tried putting lime in an empty barrel and lime in a barrel of water - in both cases limewater was successfully produced. But all other materials cause crash. At the same time, the amount of water in the barrel does not affect the result - a barrel with 10/20/30/40/50 liters of water equally crashes the game.

I test it many time in survival and creative mode (only SM), in many various world - the result is always the same when using the above materials.

Below I am attaching a crash report, which was when trying to place one oak log in a barrel with 10 liters of water. _Sorry, for some reason the report is partially in Russian. Even when switching the game to English, some lines in the report still remain in Russian. I did not understand how to get the report completely in English._

### Logs

Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.17.0-pre.5 (Unstable)
Loaded Mods: game@1.17.0-pre.5, creative@1.17.0-pre.5, survival@1.17.0-pre.5
26.07.2022 4:17:12: Critical error occurred
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в Vintagestory.GameContent.BlockBarrel.getContentMesh(ItemStack stack, BlockPos forBlockPos, String shapefilename) в C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Barrel\BlockBarrel.cs:строка 208
   в Vintagestory.GameContent.BlockBarrel.GenMesh(ItemStack contentStack, ItemStack liquidContentStack, Boolean issealed, BlockPos forBlockPos) в C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Barrel\BlockBarrel.cs:строка 152
   в Vintagestory.GameContent.BlockEntityBarrel.GenMesh() в C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Barrel\BEBarrel.cs:строка 320
   в Vintagestory.GameContent.BlockEntityBarrel.Inventory_SlotModified(Int32 slotId) в C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Barrel\BEBarrel.cs:строка 110
   в Vintagestory.API.Common.InventoryBase.DidModifyItemSlot(ItemSlot slot, ItemStack extractedStack) в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Common\Inventory\InventoryBase.cs:строка 480
   в Vintagestory.API.Common.ItemSlot.OnItemSlotModified(ItemStack sinkStack) в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Common\Inventory\ItemSlot.cs:строка 418
   в Vintagestory.API.Common.ItemSlotBarrelInput.OnItemSlotModified(ItemStack stack) в C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Inventory\ItemSlotBarrelInput.cs:строка 26
   в Vintagestory.API.Common.ItemSlot.TryPutInto(ItemSlot sinkSlot, ItemStackMoveOperation& op) в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Common\Inventory\ItemSlot.cs:строка 187
   в Vintagestory.Common.PlayerInventoryManager.TryTransferAway(ItemSlot sourceSlot, ItemStackMoveOperation& op, Boolean onlyPlayerInventory, StringBuilder shiftClickDebugText, Boolean slotNotifyEffect) в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\GameContent\Inventory\PlayerInventoryManager.cs:строка 239
   в Vintagestory.API.Common.InventoryBase.ActivateSlot(Int32 slotId, ItemSlot sourceSlot, ItemStackMoveOperation& op) в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Common\Inventory\InventoryBase.cs:строка 442
   в Vintagestory.API.Client.GuiElementItemSlotGridBase.SlotClick(ICoreClientAPI api, Int32 slotId, EnumMouseButton mouseButton, Boolean shiftPressed, Boolean ctrlPressed, Boolean altPressed) в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:строка 974
   в Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseDownOnElement(ICoreClientAPI api, MouseEvent args) в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:строка 772
   в Vintagestory.API.Client.GuiElement.OnMouseDown(ICoreClientAPI api, MouseEvent mouse) в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\GuiElement.cs:строка 638
   в Vintagestory.API.Client.GuiComposer.OnMouseDown(MouseEvent mouseArgs) в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\GuiComposer.cs:строка 440
   в Vintagestory.API.Client.GuiDialog.OnMouseDown(MouseEvent args) в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:строка 536
   в Vintagestory.Client.NoObf.GuiManager.OnMouseDown(MouseEvent args) в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Gui\GuiManager.cs:строка 394
   в Vintagestory.Client.NoObf.ClientMain.OnMouseDown(MouseEvent args) в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:строка 2248
   в Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonDown(Object sender, MouseButtonEventArgs e) в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\Input.cs:строка 220
   в System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   в System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   в OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:строка 792
   в OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   в OpenTK.Platform.Windows.WinGLNative.ProcessEvents() в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:строка 1554
   в OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) в C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:строка 368
   в Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   в Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) в C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:строка 87
-------------------------------

**Comment by Craluminum2413** [comment] 2022-07-25 23:36
Duplicate of #2021

**Closed by Craluminum2413** 2022-07-25 23:36 UTC
Labels: status: new
