### ISSUE TITLE
Game crashes when viewing firepits in handbook

### ISSUE THREAD

**Issue by astynax777** [anegostudios/VintageStory-Issues#985] opened 2021-06-12 03:01 UTC
**Game Version:** v1.15.0-pre.3
**Platform:** Windows
**Modded:** No

### Description
Open handbook, click on firepit (cold/in construction) and it crashes

### How to reproduce
Open handbook, click on firepit (cold/in construction) and it crashes

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.0-pre.3 (Unstable)6/11/2021 10:58:08 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.CollectibleObject.GetHandbookInfo(ItemSlot inSlot, ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor)
   at Vintagestory.API.Client.GuiHandbookItemStackPage.GetPageText(ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor)
   at Vintagestory.GameContent.GuiDialogHandbook.initDetailGui()
   at Vintagestory.API.Client.GuiElementHandbookList.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientMain.OnMouseUp(MouseEvent args)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _UwTpwIUKuzIrz4lc7aDEDr1w32f._ouD1c39oCQ2Eda0lkC3EXYeZtC7(_OdfjAwaG2wGU12XuYVt4myQv5bF , String[] )
   at _j9Ke4RlHC2L45ChATqqx7RI91CC._ouD1c39oCQ2Eda0lkC3EXYeZtC7(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 6/10/2021 4:44:07 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1655763307312757660, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.0.0
P3: 60bf9879
P4: mscorlib
P5: 4.8.4341.0
P6: 60230124
P7: 393d
P8: 0
P9: System.StackOverflowException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCECC.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE1A9.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE208.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE217.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE247.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_829ec64ab87565927ea117b44c4a15667a19e0_77693150_86961cb0-52b5-499f-931f-14897fb25471

Analysis symbol: 
Rechecking for solution: 0
Report Id: d9d27de5-1a3f-4920-ba69-8f7a42a8dc38
Report Status: 268435456
Hashed bucket: 60f7860134869c7c36fa73f49480bb9c
Cab Guid: 0 }
--------------
{ TimeGenerated = 6/10/2021 4:44:02 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.15.0.0, time stamp: 0x60bf9879
Faulting module name: mscorlib.ni.dll, version: 4.8.4341.0, time stamp: 0x60230124
Exception code: 0xc00000fd
Fault offset: 0x0000000000e2d200
Faulting process id: 0x6c84
Faulting application start time: 0x01d75e3949b371ee
Faulting application path: C:\Users\astyn\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\mscorlib\fa77f3773e7347d73b54c65ccbb4ba62\mscorlib.ni.dll
Report Id: d9d27de5-1a3f-4920-ba69-8f7a42a8dc38
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 6/10/2021 4:43:30 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1359678730607606919, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.0.0
P3: 60bf9879
P4: VintagestoryLib
P5: 1.15.0.0
P6: 60bf9879
P7: 1e8a
P8: 0
P9: System.StackOverflowException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3BE2.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4E91.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4EEF.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4EFD.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4F2D.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_fffa8f75da41187b2c69e07a30f3c89896ff2_77693150_c8ff32b4-472e-4382-aa8a-dfc53f38fdaf

Analysis symbol: 
Rechecking for solution: 0
Report Id: b8d7602b-1cbf-48ac-859e-460a3b2267ca
Report Status: 268435456
Hashed bucket: 879fa79dda3a7e0f72de8c9a02853c87
Cab Guid: 0 }
```

**Comment by Craluminum2413** [comment] 2021-06-12 06:16
Duplicate of #890

**Comment by copygirl** [comment] 2021-06-12 10:37
Same crash, different item. Could be something related to the item definition itself. Will keep separate for now.

**Comment by copygirl** [comment] 2021-06-17 20:03
Should be fixed. See mentioned issue.

**Closed by copygirl** 2021-06-17 20:03 UTC
Labels: status: resolved, type: crash
