### ISSUE TITLE
My game will not play in the Aura Fury server and crashes every time. What do i do?

### ISSUE THREAD

**Issue by Braxx2011** [anegostudios/VintageStory-Issues#2489] opened 2023-03-18 14:31 UTC
### Game Version

v.1.17.11

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Game crashes upon entry into the Aura Fury multi server.

### How to reproduce

It crashes upon game startup to the Aura Fury multiplayer server. I have tried on 3 different computers and still get the same crash. 

### Logs

```Log```Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.11 (Stable)
3/18/2023 7:22:09 AM: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 407
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 718
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 622
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 124
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2/19/2023 5:18:40 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2186699272363415476, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.11.0
P3: 10.0.19044.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\jmlin\AppData\Local\Temp\RDR7033.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7044.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7045.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7062.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7082.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: b22c1a2c-4fa6-4733-b0d9-2a53aa3a45a1
Report Status: 268435456
Hashed bucket: 0215b19e9f6a6c1d1e58b7670fd397b4
Cab Guid: 0 }
--------------
{ TimeGenerated = 2/18/2023 2:18:07 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1414032621744341770, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.11.0
P3: 63e108be
P4: clr.dll
P5: 4.8.4614.0
P6: 63995bc5
P7: c0000005
P8: 00000000001d027e
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA7C1.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAA33.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAA43.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAA41.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAA62.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_30859767861314bc204a9e8b15a1272543af156_1112ccc3_1a0d3a44-c238-445f-b252-8c9a2af98b7f

Analysis symbol: 
Rechecking for solution: 0
Report Id: 0f743835-a03a-4edb-aa8c-7dc107469f79
Report Status: 268435456
Hashed bucket: 5e59b072f98b9f98739fa72d77e2c30a
Cab Guid: 0 }
--------------
{ TimeGenerated = 2/18/2023 2:18:06 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.17.11.0, time stamp: 0x63e108be
Faulting module name: clr.dll, version: 4.8.4614.0, time stamp: 0x63995bc5
Exception code: 0xc0000005
Fault offset: 0x00000000001d027e
Faulting process id: 0x26f4
Faulting application start time: 0x01d943d2572e8704
Faulting application path: C:\Users\jmlin\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Report Id: 0f743835-a03a-4edb-aa8c-7dc107469f79
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment] 2023-03-18 14:38
Duplicate of #2380

**Closed by Craluminum2413** 2023-03-18 14:38 UTC
Labels: status: new
