### ISSUE TITLE
blocks are white with red question marks

### ISSUE THREAD

**Issue by popsugars4** [anegostudios/VintageStory-Issues#1562] opened 2022-01-11 00:31 UTC
**Game Version:** X.Y.Z  1.16
**Platform:** Windows / Mac / Linux (which?)   windows
**Modded:** No / Yes (which?)  
**SP/MP:** Singleplayer / Multiplayer (which?)  multiplayer

### Description
Explain the issue you're running into.
some of my blocks are white with red question marks. i went onto the wiki and tried the /fixmapping applyall and it did not work to fix the blocks. also i tried opening my single player and it just crashed and said to remove mods.
### How to reproduce
1. Make a '....'
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Paste crash between the triple backticks.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.
```

**Comment by copygirl** [comment] 2022-01-11 07:43
I assume you've updated from 1.15 to 1.16 and ran into this issue?
Were you previously playing with mods?
Please upload the server-main.txt - without it we'll be mostly guessing what could be wrong.

**Comment by popsugars4** [comment] 2022-01-12 03:36
i didn't have any mods on the server and yes i did do the update that is when the issue started with the blocks.

**Comment by copygirl** [comment] 2022-01-12 07:49
I'm a bit unfamiliar with the mapping fix process on servers.

One thing I would personally try is:
- Downgrade the game to 1.15.10.
- Disable all mods.
- Download the world and place it into your game's saves folder.  
- Hop into it once.
- Update to 1.16.0.
- Hop in again. Run the mapping fix using the popup.
- Reupload the world to the server.

**Comment by tyronx** [comment] 2022-01-13 16:39
Activate the debug screen (CRTRL+F3), look at a question mark block, make a screenshot and share it with us. That would tell us which block is broken/unmapped.

**Comment by popsugars4** [comment] 2022-01-14 19:54
well i took the picture like you said but none of the stuff showed up on the pictures. my torches and my pine plank floors are what is showing up like this but the one in the woods is the new mushrooms. I am not great at this whole computer stuff my brother set the server up and he is the one that has tried the commands his game will not even pull up it crashed and then wouldn't do anything after that. I love this game by the way I play it all the time so when it messed up I was sad i really hope we can get this figured out.
![2022-01-14_14-42-13](https://user-images.githubusercontent.com/97486334/149576422-b4e8c202-3ded-459f-8a4a-bf6f24a6da04.png)
![2022-01-14_14-45-11](https://user-images.githubusercontent.com/97486334/149576439-c536cc50-aefc-424f-b98f-7d7dfde2c005.png)
s

**Comment by copygirl** [comment] 2022-01-15 05:34
You probably pressed F4 by accident. This hides the HUD and the information that's supposed to show up when you press Ctrl+F3. When this happens you can just press F4 again to re-show the HUD. Can you try taking a screenshot again?

**Comment by popsugars4** [comment] 2022-01-15 13:46
no on my key board F4 kills the game and i made sure that i was pressing ctrl + F3 like tyron said but when i take the picture it doesn't show any of that on it. I will try to take it with my phone and send a picture that way. but the blocks that are showing like this are the new mushrooms, the torches, my bowls they disappeared, and my pine plank the full one not the slabs.

**Comment by popsugars4** [comment] 2022-01-15 13:53
ok i have no idea what has happened in the last 5 minutes but now it lets me load in but automatically freezes up and then the whole game closes. I thought it was the server at first so i tried my single player game but it is doing the same thing.

**Comment by copygirl** [comment] 2022-01-15 14:56
I'm not sure why the screenshots don't include the debug information.

Could you create a new issue for the crash you're getting?
(Though if it's something about TextureSource, that one is already reported.)

**Comment by popsugars4** [comment] 2022-01-16 13:17
i am not sure what is causing the crash it does not give me any detail about it. I load my game get in the game itself but it freezes and closes completely.

**Comment by copygirl** [comment] 2022-01-16 15:34
Can you upload your client-main.txt and server-main.txt, perhaps?

**Comment by popsugars4** [comment] 2022-01-17 19:39
I am unsure of what is happening with the game I can't get it to do anything but load my game freeze and then just close my brother is having the exact same problem I even tried to uninstall the game and see if that fixed the problem but it didn't change anything. I have another computer so I decided to download it on to it. I created a world and it works fine. If it was my computer then my brother wouldn't be having the exact same problem so I am at a loss to what is going on. I am not sure how to get the server-main.txt or the client-main.txt especially with it not even loading the game.

**Comment by copygirl** [comment] 2022-01-17 21:13
The log files are located at `%AppData%\VintagestoryData\Logs`.

**Comment by popsugars4** [comment] 2022-01-18 15:41
this is the crash report that i found i am still looking for the log info and how to get it on here.

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 1/18/2022 10:19:09 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1782938992179495309, type 5
Event Name: BEX64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.0.0
P3: 61dc5145
P4: nvoglv64.dll
P5: 23.21.13.9135
P6: 5ab586ed
P7: 0000000000fe03a9
P8: c0000409
P9: 0000000000000007
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB0D3.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE0ED.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE0FE.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE188.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE199.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_91bdb03d9369ed34c477a2b4d0281a5eb5e5fca8_d5c93aa4_21c10c69-a8b9-489d-ad43-67c8575f8be8

Analysis symbol: 
Rechecking for solution: 0
Report Id: aed189fb-ad42-41e2-9440-dec104036602
Report Status: 268435456
Hashed bucket: 06290dd057ae770048be4591250d418d
Cab Guid: 0 }
--------------
{ TimeGenerated = 1/18/2022 10:18:45 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.16.0.0, time stamp: 0x61dc5145
Faulting module name: nvoglv64.dll, version: 23.21.13.9135, time stamp: 0x5ab586ed
Exception code: 0xc0000409
Fault offset: 0x0000000000fe03a9
Faulting process id: 0x367c
Faulting application start time: 0x01d80c7e516b6d85
Faulting application path: D:\Vintagestory\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\DriverStore\FileRepository\nvaki.inf_amd64_018a3f62635ef597\nvoglv64.dll
Report Id: aed189fb-ad42-41e2-9440-dec104036602
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 1/16/2022 10:00:56 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1782938992179495309, type 5
Event Name: BEX64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.0.0
P3: 61dc5145
P4: nvoglv64.dll
P5: 23.21.13.9135
P6: 5ab586ed
P7: 0000000000fe03a9
P8: c0000409
P9: 0000000000000007
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA458.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB215.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB226.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB235.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB255.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_91bdb03d9369ed34c477a2b4d0281a5eb5e5fca8_d5c93aa4_05f88b40-15f7-4a5d-9deb-ac3b5e0da965

Analysis symbol: 
Rechecking for solution: 0
Report Id: 406d87d3-2d43-488c-b666-eff5600e275c
Report Status: 268435456
Hashed bucket: 06290dd057ae770048be4591250d418d
Cab Guid: 0 }

**Comment by popsugars4** [comment] 2022-01-18 15:45
not sure if those help any.

[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/7890328/client-crash.txt)
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/7890329/client-debug.txt)
[server-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/7890332/server-debug.txt)
[server-event.txt](https://github.com/anegostudios/VintageStory-Issues/files/7890334/server-event.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/7890336/server-main.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/7890340/client-main.txt)

**Comment by popsugars4** [comment] 2022-01-19 18:33
i am going to send you those again i think those are old i deleted everything and then reinstalled it so that all the old stuff is gone and i know these are the new ones
[client-main.txt](https://github.c
[server-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/7899675/server-debug.txt)
om/anegostudios/VintageStory-Issu
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/7899677/server-main.txt)
es/files/7899671/client-main.txt)
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/7899680/client-crash.txt)

.Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 1/19/2022 1:18:18 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1782938992179495309, type 5
Event Name: BEX64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.0.0
P3: 61dc5145
P4: nvoglv64.dll
P5: 23.21.13.9135
P6: 5ab586ed
P7: 0000000000fe03a9
P8: c0000409
P9: 0000000000000007
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2D3.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER24A4.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2716.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2743.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER27C1.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_91bdb03d9369ed34c477a2b4d0281a5eb5e5fca8_d5c93aa4_a7f7b87d-bd37-4e2b-8c20-967f4dcb1c15

Analysis symbol: 
Rechecking for solution: 0
Report Id: 1c6350dc-bf7a-4c8f-a207-e5babe75d8aa
Report Status: 268435456
Hashed bucket: 06290dd057ae770048be4591250d418d
Cab Guid: 0 }
--------------
{ TimeGenerated = 1/19/2022 1:17:54 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.16.0.0, time stamp: 0x61dc5145
Faulting module name: nvoglv64.dll, version: 23.21.13.9135, time stamp: 0x5ab586ed
Exception code: 0xc0000409
Fault offset: 0x0000000000fe03a9
Faulting process id: 0x854
Faulting application start time: 0x01d80d60b5635eff
Faulting application path: D:\Vintagestory\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\DriverStore\FileRepository\nvaki.inf_amd64_018a3f62635ef597\nvoglv64.dll
Report Id: 1c6350dc-bf7a-4c8f-a207-e5babe75d8aa
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 1/19/2022 9:27:24 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1782938992179495309, type 5
Event Name: BEX64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.0.0
P3: 61dc5145
P4: nvoglv64.dll
P5: 23.21.13.9135
P6: 5ab586ed
P7: 0000000000fe03a9
P8: c0000409
P9: 0000000000000007
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER81CE.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC716.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC794.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC7FF.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC81F.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_91bdb03d9369ed34c477a2b4d0281a5eb5e5fca8_d5c93aa4_2cde0a68-d1ac-4be7-9557-6f5f4755fe56

Analysis symbol: 
Rechecking for solution: 0
Report Id: 2f15fda7-3b4d-40d6-a70c-c5bfed4285fe
Report Status: 268435456
Hashed bucket: 06290dd057ae770048be4591250d418d
Cab Guid: 0 }

**Comment by copygirl** [comment] 2022-01-19 18:51
The client and server logs show that you were running version 1.14.10 of the game. Did you mean to install that version?

The error still appears to be the same as with last response. Check your video drivers.

I'm closing the issue for now since this is off-topic regarding the initial issue. But feel free to keep asking for help, I'll try to help where I can.

**Comment by popsugars4** [comment] 2022-01-20 17:05
the problem is i updated the modes and it is still doing this i have uninstalled it and reinstalled it and nothing i have tried so far is working going to try going back to the old version and see if i can at least play the game.

**Comment by popsugars4** [comment] 2022-01-21 01:31
ok i figured out why it would close the game so if anyone else is have the same issue with it loading into the game and then freezing and then closing go into your settings and change the game quality to a lower setting. now i for the blocks them selves they are still showing up white with a question mark i did figure out how to take a picture like tyron was asking me to not sure how good it will look or if you will be able to read it very well.
 
![image](https://user-images.githubusercontent.com/97486334/150449221-403ae391-c718-45ea-82d0-7aa624726cff.png)

**Comment by copygirl** [comment] 2022-01-21 08:12
Okay so the pine planks are actually a block that's known to the game, since it's actually called "Pine planks" rather than "game:planks-pine". Can you upload your client-main and server-main files again? Perhaps there is an error when the texture is being loaded. Will re-open since we're back to the original issue.

**Comment by popsugars4** [comment] 2022-01-21 13:45
i have been telling you what blocks are showing up like this. If i didn't have help from people that knows computer tech i would not know how to do most of this.

[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/7914040/client-main.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/7914045/server-main.txt)

**Comment by copygirl** [comment] 2022-01-21 15:41
I do remember you telling us which blocks this happened with but it's an important difference whether they show up as an unknown block (in which case it would not show as "Pine planks") or it is just missing its texture somehow. Since it's a texture issue, it doesn't have to do with incorrect mappings.

I would say try to load the map (or a backup thereof) without any mods (keep the default ones on: Survival, Creative and Essential), just to make sure it's not somehow caused by them.

If the issue persists, a developer will have to take a proper look at the issue.

And yeah I agree, having people able to find and upload log files easily is something the game is still lacking.

**Comment by popsugars4** [comment] 2022-01-21 17:34
I deleted all my mods before I even went into the game so there are no mods being used when I took the picture. And thank you for all your help. I was not trying to be an ass when I made that comment even though it kinda sounded like it. I was just letting y'all know that if I didn't have help from people who know the tech stuff I wouldn't know how to do the picture at all the other stuff I just got lucky with and found because those files you wanted are not readily visible I just got lucky when I checked the crash report that was in the folder and just got curious and opened it and there they where so you might want to explain that to others when you tell them that is what your needing. Just a tip because I didn't want to sound dumb and ask where they where at and I know there are others like me and want ask. But yeah I didn't have any mods on when I took the picture. So someone might want to look into it.

**Comment by popsugars4** [comment] 2022-01-25 15:23
![image](https://user-images.githubusercontent.com/97486334/151005479-c5d81bee-2653-47f9-a0ec-0025721bc426.png)

**Comment by popsugars4** [comment] 2022-01-25 15:24
![image](https://user-images.githubusercontent.com/97486334/151005704-6d3364bd-79e7-4312-b70b-12c14b230dbd.png)

**Comment by popsugars4** [comment] 2022-01-25 15:25
![image](https://user-images.githubusercontent.com/97486334/151005946-09e3db98-1ae6-4dbb-b7ee-1658ffead2f2.png)

**Comment by popsugars4** [comment] 2022-01-25 15:34
well we got others fixed but it broke others
![image](https://user-images.githubusercontent.com/97486334/151007765-8f5769d3-a21c-402e-9e09-0000c471a65a.png)

**Comment by lacrosse988** [comment] 2022-10-21 04:31
Is this a dead bug?

**Comment by Craluminum2413** [comment] 2023-04-11 11:49
Closing due to inactivity

**Closed by Craluminum2413** 2023-04-11 11:49 UTC
Labels: status: incomplete
