### ISSUE TITLE
v1.15rc1 is not playable

### ISSUE THREAD

**Issue by PilotDoug** [anegostudios/VintageStory-Issues#1113] opened 2021-07-07 17:41 UTC
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.0-rc.1 (Unstable)7/7/2021 12:36:38 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityGroundStorage.DetermineStorageProperties(ItemSlot sourceSlot)
   at Vintagestory.GameContent.BlockEntityGroundStorage.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldForResolving)
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(_f47bFFjjZjqsZ07abkCWRRjJjq5 p, ClientMain game)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(_SPt7iF5LhXmcxMRSPZV1A0ZATGh packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _Hhyykp3OIyR3A9gDXvfRYXmIxHM._N2PKmadywKhrSAOGDRbet32cyTB(Single )
   at _GatfFd3kn5xATuUyKYscxn8d0CO._4TEOzZagWNPjzZVqfu2HCwbLFqC(Single )
   at _GatfFd3kn5xATuUyKYscxn8d0CO._x3D81oTSuYvhXUwgP6x9PwySgdc(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _woe4UEAalnRbwPXBTK09ZhdFcWO._5qgAk5LLuTcbcRWXQsq1b3Y8T8H(_arFvNaodTjXO5ObZ7eEgimkezLG , String[] )
   at _ZFpbvq06JtO6suJqmLDa8Hs9YeH._5qgAk5LLuTcbcRWXQsq1b3Y8T8H(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 7/6/2021 4:44:41 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1787358762948678399, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.0.0
P3: 60df0588
P4: KERNELBASE.dll
P5: 10.0.19041.1023
P6: 924f9cdb
P7: c000041d
P8: 0000000000034b89
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5F4F.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER62EA.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER62FB.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER630A.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER632B.tmp.txt
\\?\C:\Users\Gamer\AppData\Local\Temp\WER6406.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_6423145b6cda8c60d9d89ab0422ef3945fce7697_57f52630_370e31ed-a2fb-4473-b622-7e4e55a15dcc

Analysis symbol: 
Rechecking for solution: 0
Report Id: d8f62b02-23c9-4a0a-885d-638767b54de8
Report Status: 268435456
Hashed bucket: 9caaf748cfb7ef0978cdf95337bcd2ff
Cab Guid: 0 }
--------------
{ TimeGenerated = 7/6/2021 4:44:41 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.0.0
P3: 60df0588
P4: KERNELBASE.dll
P5: 10.0.19041.1023
P6: 924f9cdb
P7: c000041d
P8: 0000000000034b89
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5F4F.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER62EA.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER62FB.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER630A.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER632B.tmp.txt
\\?\C:\Users\Gamer\AppData\Local\Temp\WER6406.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_6423145b6cda8c60d9d89ab0422ef3945fce7697_57f52630_cab_370e31ed-a2fb-4473-b622-7e4e55a15dcc

Analysis symbol: 
Rechecking for solution: 0
Report Id: d8f62b02-23c9-4a0a-885d-638767b54de8
Report Status: 4
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 7/6/2021 4:44:41 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1242372221530262643, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.0.0
P3: 60df0588
P4: KERNELBASE.dll
P5: 10.0.19041.1023
P6: 924f9cdb
P7: c0020001
P8: 0000000000034b89
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5731.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5BE5.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5BF6.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5C04.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5C24.tmp.txt
\\?\C:\Users\Gamer\AppData\Local\Temp\WER5D02.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_dbd2f116e072cca4c58497f5d9981ab82ec3df4_57f52630_c1f71b27-b4cb-46a6-b7d2-2199e6dc0f16

Analysis symbol: 
Rechecking for solution: 0
Report Id: e41d35fb-c2a4-4c4a-8b87-7bf98f282ce5
Report Status: 268435456
Hashed bucket: 6e6897f86d0500c4913dcaf3ff1fcc73
Cab Guid: 0 }

**Comment by Craluminum2413** [comment] 2021-07-07 17:42
Duplicate of #1111

**Closed** 2021-07-07 18:52 UTC
Labels: status: duplicate
