### ISSUE TITLE
Game crashes when creating a new world from the same seed

### ISSUE THREAD

**Issue by eightykv** [anegostudios/VintageStory-Issues#851] opened 2021-04-05 19:17 UTC
Running on 64 bit Windows with 32 GB RAM 
Version: v1.14.8 (Stable)4/5/2021 12:14:48 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at _PW8NVVq6wBR9krMQ9GulRnv6PMD._h9K0G4wbrt2CCpt5A92lCnKV2gP()
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   at _oDnqPT3M9pq9hNGZM4RDtA6RTnG._TE0ypoo5kb57Ue2gLv7daIuY6VD(MouseEvent )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _YrS2W1MoaeqC4xqH8ItdZB6vADN._8t1BmEWVlCT9mjx5M0vFIzU9tif(_7T00Rjby4si0wyEBez5dXNqLm7h , String[] )
   at _ejKuc6cg0k8V39o8jDIzquyczbO._8t1BmEWVlCT9mjx5M0vFIzU9tif(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 4/5/2021 12:13:30 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1652963209626238934, type 5
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.8.0
P3: 6033ac5b
P4: 77e3
P5: 67246080
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAA22.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\Critical_Vintagestory.exe_56f82eba5f359a35dab2e2c3d832bbf04ca619_4fd6768e_6241f2d6-b8d6-4d08-9172-707714199a57

Analysis symbol: 
Rechecking for solution: 0
Report Id: c8a4d88d-5673-4a1d-9839-235139400931
Report Status: 268435456
Hashed bucket: 27e35b0045814ea946f08148088fbfd6
Cab Guid: 0 }
--------------
{ TimeGenerated = 4/5/2021 12:13:29 PM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.14.8.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 2eb4

Start Time: 01d72a4814543ec5

Termination Time: 4294967295

Application Path: C:\Program Files\Vintagestory\Vintagestory.exe

Report Id: c8a4d88d-5673-4a1d-9839-235139400931

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Top level window is idle
 }
--------------
{ TimeGenerated = 4/5/2021 12:13:29 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.8.0
P3: 6033ac5b
P4: 77e3
P5: 67246080
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\Critical_Vintagestory.exe_56f82eba5f359a35dab2e2c3d832bbf04ca619_4fd6768e_6241f2d6-b8d6-4d08-9172-707714199a57

Analysis symbol: 
Rechecking for solution: 0
Report Id: c8a4d88d-5673-4a1d-9839-235139400931
Report Status: 4
Hashed bucket: 
Cab Guid: 0 }

**Comment by copygirl** [comment] 2021-04-05 21:22
Duplicate of #795.

**Closed by copygirl** 2021-04-05 21:22 UTC
Labels: status: duplicate
