### ISSUE TITLE
Player crashing with CharacterSystem.applyTraitAttributes

### ISSUE THREAD

**Issue by WickedSchnitzel** [anegostudios/VintageStory-Issues#3613] opened 2024-02-19 21:57 UTC
### Game Version

1.19.3

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Theres 1 player that always crashes with this error. Seems to be the only one. Did crash last wipe and this wipe as well. He did uninstall/reinstall and checked the folder for mods that could cause this. When i try to wipe his data, the game tells me that there's no data within the savegame.

### Logs

Running on 64 bit Windows 10.0.19045.0 with 15741 MB RAM
Game Version: v1.19.3 (Stable)
19/02/2024 22:38:59: Critical error occurred
Loaded Mods: weaponpacka@1.3.1, bettercrates@1.7.0, Ceramos@0.4.3, chiseltools@1.10.4, decor@1.0.14, extrachests@1.8.0, fantasycreatures@0.7.1, fixedpaths@1.0.1, flourbags@1.0.2, foundrymod@1.0.0, giantgouramis@1.0.2, millwright@1.1.4, moreicons_cs@1.1.0, peacockbasses@1.1.2, primitivesurvival@3.4.6, spyglass@0.5.0, Swordz@1.1.4, thecritterpack@0.8.6, translocatorengineeringredux@1.4.9, truesunfishes@1.1.2, game@1.19.3, alphaweaponpackfix@1.0.0, ancienttools@1.5.12, barbershop@0.4.0, beehivekiln@1.5.1, betterfirepit@1.1.4, betterjonasdevices@1.1.0, betterruins@0.3.3, carryon@1.7.4, commonlib@2.3.2, fairplayguardian@1.1.7, furniturelibrary@1.0.11, herbarium@1.0.5, sailboat@1.2.8, medievalexpansion@3.13.1, meteoricexpansion@1.2.5, morepiles@1.5.0, moreplaster@1.0.1, petai@2.2.3, rivers@2.4.0, simplestep@1.1.6, steadycam@1.3.0, stonebakeoven@1.1.3, tentbag@1.1.1, th3dungeon@0.2.1-rc.1, usefulstuff17@1.3.1, vinconomy@0.2.2, creative@1.19.3, vsinstruments@1.2.7, vsquest@1.2.0, survival@1.19.3, workbenchexpansion@1.8.0, xlib119@0.7.4-dev.1191, awearablelight@1.1.1, cob2@1.5.8, em@2.5.0, outerspacetunesmaster@1.0.0, outerspacetunesvolume1@1.0.0, outerspacetunesvolume2@1.0.0, playercorpse@1.9.0, rifteye@0.3.4, simplewinddirection@1.0.2, stonequarry@3.2.1, wildcraftfruit@1.0.1, wolftaming@2.1.0, xskills119@0.7.5-dev.1191, bricklayers@2.5.0, cob@1.7.0, vsvillagecob@0.1.9
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.CharacterSystem.applyTraitAttributes(EntityPlayer eplr) in VSSurvivalMod\Systems\Character\Character.cs:line 322
   at Vintagestory.GameContent.CharacterSystem.setCharacterClass(EntityPlayer player, String classCode, Boolean initializeGear) in VSSurvivalMod\Systems\Character\Character.cs:line 289
   at Vintagestory.GameContent.GuiDialogCreateCharacter.OnGuiOpened() in VSSurvivalMod\Gui\GuiDialogCreateCharacter.cs:line 308
   at Vintagestory.API.Client.GuiDialog.TryOpen(Boolean withFocus) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 288
   at Vintagestory.API.Client.GuiDialog.TryOpen() in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 268
   at Vintagestory.GameContent.GuiDialogCreateCharacter.PrepAndOpen() in VSSurvivalMod\Gui\GuiDialogCreateCharacter.cs:line 432
   at Vintagestory.GameContent.CharacterSystem.Event_PlayerJoin(IClientPlayer byPlayer) in VSSurvivalMod\Systems\Character\Character.cs:line 368
   at Vintagestory.Client.NoObf.ClientEventAPI.TriggerPlayerJoin(IClientPlayer plr) in VintagestoryLib\Client\API\ClientEventAPI.cs:line 259
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandlePlayerData(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 297
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 769
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 313
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 675
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 650
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 2
==================================
{ TimeGenerated = 19/02/2024 22:35:18, Site = , Source = Application Error, Message = Nombre de la aplicación con errores: Vintagestory.exe, versión: 1.19.3.0, marca de tiempo: 0x65310000
Nombre del módulo con errores: openal32.dll, versión: 1.23.0.0, marca de tiempo: 0x63dd31ad
Código de excepción: 0x40000015
Desplazamiento de errores: 0x00000000000df046
Identificador del proceso con errores: 0x5b18
Hora de inicio de la aplicación con errores: 0x01da637b7232a384
Ruta de acceso de la aplicación con errores: C:\Users\Raul-\AppData\Roaming\Vintagestory\Vintagestory.exe
Ruta de acceso del módulo con errores: C:\Users\Raul-\AppData\Roaming\Vintagestory\Lib\openal32.dll
Identificador del informe: 128e1002-f446-4335-be99-0050e9de66e9
Nombre completo del paquete con errores: 
Identificador de aplicación relativa del paquete con errores:  }
--------------
{ TimeGenerated = 01/02/2024 22:42:38, Site = , Source = Application Error, Message = Nombre de la aplicación con errores: Vintagestory.exe, versión: 1.19.3.0, marca de tiempo: 0x65310000
Nombre del módulo con errores: KERNELBASE.dll, versión: 10.0.19041.3930, marca de tiempo: 0x9141f979
Código de excepción: 0xe0434352
Desplazamiento de errores: 0x000000000002cf19
Identificador del proceso con errores: 0x28e8
Hora de inicio de la aplicación con errores: 0x01da5550ab1c6f01
Ruta de acceso de la aplicación con errores: C:\Users\Raul-\AppData\Roaming\Vintagestory\Vintagestory.exe
Ruta de acceso del módulo con errores: C:\Windows\System32\KERNELBASE.dll
Identificador del informe: 722f9079-f255-4c31-aea7-3aa9b1aa6dd7
Nombre completo del paquete con errores: 
Identificador de aplicación relativa del paquete con errores:  }

**Comment by Craluminum2413** [comment] 2024-02-24 19:15
Duplicate of #3436

**Closed by Craluminum2413** 2024-02-24 19:15 UTC
Labels: status: new
