### ISSUE TITLE
Malefactor's Sling considers kills as done by another creature

### ISSUE THREAD

**Issue by Seagul404** [anegostudios/VintageStory-Issues#2864] opened 2023-06-29 01:05 UTC
### Game Version

v1.18.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

After killing an animal with the sling, the dead animal is considered "killed by another creature"

### How to reproduce

1 kill an animal with a sling
2 observe corpse status

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/138079312/695cd276-b6d8-4c7b-9bd4-506d4546f7d5)

### Logs

```Log```

**Comment by Seagul404** [comment] 2023-06-29 01:09
Irrelevant note: I only killed a bighorn lamb for the screenshot, as it was the only nearby animal I could find.

**Comment by Craluminum2413** [comment] 2023-06-29 08:43
Duplicate of #2583, it was fixed a month ago

**Closed** 2023-06-29 08:44 UTC
Labels: status: duplicate
