### ISSUE TITLE
Issue with Buttons

### ISSUE THREAD

**Issue by Ruyeex** [anegostudios/VintageStory-Issues#2490] opened 2023-03-18 23:51 UTC
### Game Version

v.1.18.pre.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

None

### Description

![image](https://user-images.githubusercontent.com/99507424/226145868-6b7b6b2c-f7f6-431d-837d-acc248fde33c.png)
It's the overlap of buttons that can be quite annoying.

### How to reproduce

Just change it to portuguese portugal and go to the "Gestor de Modificações"

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2023-03-19 08:21
Other language, but the issue is the same. Duplicate of #2468

**Closed by Craluminum2413** 2023-03-19 08:21 UTC
Labels: status: new
