### ISSUE TITLE
Topping up a partially eaten bowl from a sealed crock makes it unsealed

### ISSUE THREAD

**Issue by Wesmania** [anegostudios/VintageStory-Issues#2969] opened 2023-07-30 21:12 UTC
### Game Version

v1.18.7

### Platform

Linux

### Modded

None

### SP/MP

Multiplayer

### Description

If you fill an empty bowl from a sealed crock, it remains sealed. However, if you then eat some of the food from the bowl so that the bowl has some food left, then top up the bowl from the sealed crock, it will unseal the crock.

### How to reproduce

* Make a sealed crock of food. Take note how long it takes to spoil.
* Take a portion with an empty bowl.
* Eat some of the food from the bowl, but not all of it.
* Grab more food from the crock with the same bowl.
* Observe how it takes much less time for the crock to spoil now.

**Comment by Craluminum2413** [comment] 2023-07-30 21:55
Duplicate of #852

**Closed by Craluminum2413** 2023-07-30 21:55 UTC
Labels: status: new
