### ISSUE TITLE
Tabs for new world customization are looking weird (when translated at least)

### ISSUE THREAD

**Issue by MyraMidnight** [anegostudios/VintageStory-Issues#4689] opened 2024-12-14 09:07 UTC
### Game Version

v1.20.0-rc.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Just when creating a new world, there is the option to customize to change the options, the tabs for the various options categories actually aren't all fully visible on full screen, and when window is smaller than expected, then those tabs simply go out of bounds and off screen.

This might only be an issue with translated interface, but this still is an issue.

### How to reproduce

1. Run the game in windowed mode
2. change language to Icelandic (and of course restart game)
3. Go to create a new world for single player ("Einspilun")
4. Go into customize 
5. Look at the tabs, specially if you resize the window

### Screenshots

![custom world options small window](https://github.com/user-attachments/assets/2fcc4d64-39a3-4529-bafd-8b19fabc45c1)
![custom world options](https://github.com/user-attachments/assets/9007ec95-8ecd-427f-8865-96714c04e313)

### Logs

```Log```

**Comment by MyraMidnight** [comment] 2024-12-14 09:25
I might aim at wording those things to be shorter, but still, when fullscreen the tabs technically fit

**Comment by Craluminum2413** [comment] 2024-12-14 10:39
Related? https://github.com/anegostudios/VintageStory-Issues/issues/4445

**Comment by MyraMidnight** [comment] 2024-12-16 11:31
@Craluminum2413  seems to be the same issue, yes

**Comment by Craluminum2413** [comment] 2024-12-16 11:41
Duplicate of #4445

**Closed by Craluminum2413** 2024-12-16 11:41 UTC
Labels: status: new, department: code
