### ISSUE TITLE
game crashes all the time

### ISSUE THREAD

**Issue by SmallYuka** [anegostudios/VintageStory-Issues#3579] opened 2024-02-12 20:29 UTC
### Game Version

v.1.19.3

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/159829679/a99490ac-28ea-4452-b47b-5da0fc0497a6)

**Comment by Craluminum2413** [comment] 2024-02-13 08:44
Duplicate of #3410

**Closed by Craluminum2413** 2024-02-13 08:44 UTC
Labels: status: new
