### ISSUE TITLE
game crashed 

### ISSUE THREAD

**Issue by Satras1** [anegostudios/VintageStory-Issues#4179] opened 2024-09-28 09:39 UTC
### Game Version

v.1.20.0 pre4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

not sure why. see included crash log

### Logs
```
Running on 64 bit Windows 10.0.19045.0 with 8060 MB RAM
Game Version: v1.20.0-pre.4 (Unstable)
28.09.2024 11:36:25: Critical error occurred
Loaded Mods: game@1.20.0-pre.4, creative@1.20.0-pre.4, survival@1.20.0-pre.4
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.API.MathTools.SimplexNoiseOctave.Evaluate(Double x, Double y, Double z) in VintagestoryApi\Math\Noise\SimplexOctave.cs:line 414
   at Vintagestory.API.MathTools.SimplexNoise.Noise(Double x, Double y, Double z) in VintagestoryApi\Math\Noise\SimplexNoise.cs:line 117
   at Vintagestory.GameContent.WeatherPattern.RegenCloudTileCache(Vec3i tileOffset) in VSEssentials\Systems\Weather\Model\Impl\WeatherPattern.cs:line 89
   at Vintagestory.GameContent.WeatherDataReaderBase.ensureCloudTileCacheIsFresh(Vec3i tilePos) in VSEssentials\Systems\Weather\WeatherDataReader.cs:line 275
   at Vintagestory.GameContent.CloudRenderer.UpdateCloudTilesOffThread(Int32 changeSpeed) in VSEssentials\Systems\Weather\CloudRenderer.cs:line 390
   at Vintagestory.GameContent.CloudRenderer.<.ctor>b__31_2() in VSEssentials\Systems\Weather\CloudRenderer.cs:line 166
```

**Comment by Craluminum2413** [comment] 2024-09-28 09:41
Duplicate of #4166

**Closed by Craluminum2413** 2024-09-28 09:41 UTC
Labels: status: new
