### ISSUE TITLE
Tool Ground Storage prompt shows as just [Crouch] + Right-click

### ISSUE THREAD

**Issue by PeculiarSana** [anegostudios/VintageStory-Issues#2146] opened 2022-08-31 23:06 UTC
**Game Version:** 1.17.0 (Stable)
**Platform:** Windows
**Modded:** No
**SP/MP:** Both

### Description
While perhaps not a bug per se, the prompt for storing tools on the ground still shows up as `[Crouch] + Right-Click`, even though the Handbook entry states `Ctrl + Shift + Right-Click`. 
This has been the case since 1.17.0-pre.1.

### Expected behavior
The prompt should show up as the full key combo needed, i.e. `[Sprint] + [Crouch] + Right-Click`.

### Screenshots
![Vintagestory_oOgQM8R9ko](https://user-images.githubusercontent.com/31283592/187799883-9f32b5be-f2ba-43e7-8783-c3d39bbe5e83.png)

**Comment by Craluminum2413** [comment] 2022-08-31 23:09
Duplicate of #1923

**Closed by Craluminum2413** 2022-08-31 23:09 UTC
Labels: status: new
