### ISSUE TITLE
Crash when sleeping

### ISSUE THREAD

**Issue by sekelsta** [anegostudios/VintageStory-Issues#4402] opened 2024-10-31 01:39 UTC
### Game Version

1.20-pre.9

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### How to reproduce

1. Open the game and enter a world
2. Place down a hay bed
3. Run `/time add 16` so you'll be tired enough to sleep
4. Sleep
5. Repeat steps 3 and 4 until you get a crash. Seems to happen about half the time.

### Logs

client-crash.log
```Running on 64 bit Linux (Ubuntu 22.04.5 LTS) [Kernel 6.8.0.47] with 15673 MB RAM
Game Version: v1.20.0-pre.9 (Unstable)
10/30/2024 8:33:23 PM: Critical error occurred
Loaded Mods: game@1.20.0-pre.9, creative@1.20.0-pre.9, survival@1.20.0-pre.9
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.API.MathTools.SimplexNoiseOctave.Evaluate(Double x, Double y, Double z) in VintagestoryApi\Math\Noise\SimplexOctave.cs:line 414
   at Vintagestory.API.MathTools.SimplexNoise.Noise(Double x, Double y, Double z) in VintagestoryApi\Math\Noise\SimplexNoise.cs:line 117
   at Vintagestory.GameContent.WeatherPattern.RegenCloudTileCache(Vec3i tileOffset) in VSEssentials\Systems\Weather\Model\Impl\WeatherPattern.cs:line 89
   at Vintagestory.GameContent.WeatherDataReaderBase.ensureCloudTileCacheIsFresh(Vec3i tilePos) in VSEssentials\Systems\Weather\WeatherDataReader.cs:line 275
   at Vintagestory.GameContent.CloudRenderer.UpdateCloudTilesOffThread(Int32 changeSpeed) in VSEssentials\Systems\Weather\CloudRenderer.cs:line 390
   at Vintagestory.GameContent.CloudRenderer.<.ctor>b__31_2() in VSEssentials\Systems\Weather\CloudRenderer.cs:line 158
```

**Comment by Craluminum2413** [comment] 2024-10-31 09:20
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4166

**Closed by Craluminum2413** 2024-10-31 09:20 UTC
Labels: status: new
