### ISSUE TITLE
2 tall tools placed against 1 high wall

### ISSUE THREAD

**Issue by BOR15** [anegostudios/VintageStory-Issues#3903] opened 2024-06-02 15:18 UTC
### Game Version

v1.19.8 (stable)

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Tools that can be placed against a wall on the floor that normally require a two tall wall can be placed against a single block if a tool requiring only 1 block has already been placed

### How to reproduce

Place a block, place a knife against it. now you can also place a spear against it.

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2024-06-02 15:30
Duplicate of #1937

**Closed by Craluminum2413** 2024-06-02 15:30 UTC
Labels: status: new
