### ISSUE TITLE
Due to block gravity, the server is freezing

### ISSUE THREAD

**Issue by iForged** [anegostudios/VintageStory-Issues#4822] opened 2024-12-28 19:24 UTC
### Game Version

1.20.0-rc.6

### Platform

Linux

### Modded

Modded

### SP/MP

Multiplayer

### Description

This isn’t the first time I’ve encountered the issue where coal pits cause the server to hang.
The server keeps running, but when items are dropped, they either stop being picked up or are picked up, but their textures remain on the ground.
The logs keep repeating the same message:
![image](https://github.com/user-attachments/assets/04b89df2-2c13-4b79-9b78-25ee475aa372)

From the logs, it’s unclear where the problematic blocks are located. I’ve encountered this issue before—back then, players admitted it was happening to them, so I teleported to the location and broke all the stuck coal blocks. This time, no one is confessing...
I’ve already disabled all block gravity on the server, but I did so after the collapse occurred...

### Logs

28.12.2024 18:45:21 [Error] Exception: Unable to cast object of type 'Vintagestory.GameContent.BlockSoil' to type 'Vintagestory.GameContent.BlockCharcoalPile'.
   at Vintagestory.GameContent.BlockCharcoalPile.OnFallOnto(IWorldAccessor world, BlockPos pos, Block block, TreeAttribute blockEntityAttributes) in VSSurvivalMod\Block\BlockCharcoalPile.cs:line 14
   at Vintagestory.GameContent.EntityBlockFalling.OnFallToGround(Double motionY) in VSEssentials\Entity\EntityBlockFalling.cs:line 519
   at Vintagestory.API.Common.EntityBehaviorPassivePhysics.ApplyTests(EntityPos pos) in VintagestoryApi\Common\EntityBehavior\BehaviorPassivePhysics.cs:line 266
   at Vintagestory.API.Common.EntityBehaviorPassivePhysics.OnPhysicsTick(Single dt) in VintagestoryApi\Common\EntityBehavior\BehaviorPassivePhysics.cs:line 353
   at Vintagestory.Server.PhysicsManager.DoWork(Int32 threadNumber) in VintagestoryLib\Server\PhysicsManager.cs:line 583

**Comment by Craluminum2413** [comment] 2024-12-28 19:26
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4815

**Closed by Craluminum2413** 2024-12-28 19:26 UTC
Labels: status: new
