### ISSUE TITLE
Fall colors on grass and leaves/vines have strange texture

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#2639] opened 2023-04-22 00:49 UTC
### Game Version

1.18.0

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Mods are corpse mod, stepup, and vscci and shouldn't effect this
Fall colors on grass and leaves/vines have strange texture as seen here: 
![image](https://user-images.githubusercontent.com/13642054/233752931-f1da10be-8b0e-4fe4-ac59-e948382806aa.png)
![image](https://user-images.githubusercontent.com/13642054/233752936-485ad8ad-7d4b-4419-8953-cee9ce6f7b75.png)

**Comment by noelle-lavenza** [comment] 2023-04-22 07:18
Duplicate of #2452.

**Closed** 2023-04-22 08:54 UTC
Labels: status: new
