### ISSUE TITLE
Iron anvil parts wont combine in 1.19.5 (they will in 1.19.4)

### ISSUE THREAD

**Issue by kaburs** [anegostudios/VintageStory-Issues#3746] opened 2024-03-23 14:41 UTC
### Game Version

v1.19.5

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

I just updated to 1.19.5, and assembling the iron anvil won't happen.
1. I started with a save game from lower versions (initially 1.18.15, then 1.19.3, 1.19.4).
2. I put the hot bottom part down, borax on it, then top part on that. 
3. Then I start hammering causing the top part to move down every hit, 
4. but it never turns into an anvil. The top part just keeps going down with every strike, gets under the borax layer, and under the bottom part.

Circumventing the issue? 
5. I then closed the game and started that save in my 1.19.4 game, in that version the assembling DOES work. I assembled the anvil and it shows as iron anvil.
6. Then I went back to 1.19.5 but the anvil was not the complete item, but the 3 parts again. It could not be used as anvil. I closed the game again.
7. I opened the game in 1.19.4 where it (because of saving in 1.19.5) registered as the 3 separate parts again. They had to be reheated and then assembled without any issue again.
8. Now in 1.19.4 the anvil looks useable, but I cannot be actually used, as the work put on top wont show.

### How to reproduce

1. I started with a save game from lower versions (initially 1.18.15, then 1.19.3, 1.19.4).
2. I put the hot bottom part down, borax on it, then top part on that. 
3. Then I start hammering causing the top part to move down every hit, 
4. but it never turns into an anvil. The top part just keeps going down with every strike, gets under the borax layer, and under the bottom part.

### Screenshots

![Under the borax already](https://github.com/anegostudios/VintageStory-Issues/assets/33288425/5f16abd5-4aaf-4ba4-b8ec-a81f0723bd48)
![Further under the borax](https://github.com/anegostudios/VintageStory-Issues/assets/33288425/55cd1a77-bda4-4948-ae90-92c586eaac5f)
![Through the bottom part and in the ground](https://github.com/anegostudios/VintageStory-Issues/assets/33288425/be7cb740-9da6-41b7-9714-c0a985b523a8)

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2024-03-23 15:41
What mods are installed?

**Comment by kaburs** [comment] 2024-03-23 16:45
Animal cages (Code) 3.0.2
Hanging Oil Lamps (Content) 1.0.1
HUD Clock (Code) 3.4.0
Pet AI (Code) 2.2.3
ProspectTogether (Code) 1.3.0
Recycle Clothes (Content) 1.0.0
Creative Mode (Code) 1.19.x
Essentials (Code) 1.19.x
Survival Mode (Code) 1.19.x
Wolf Taming (Code) 2.1.0

**Comment by tyronx** [comment] 2024-03-31 13:08
Tried to reproduce it, seems very tricky to do so.

Exiting and rejoining the world / restarting the server seems to fix it

**Comment by luvitto** [comment] 2024-04-02 20:06
I have the same problem. I started the game with 1.19.4, now it’s 1.19.6. Only one spawnhighlight mod installed. Restarting the game doesn't help.
![vs](https://github.com/anegostudios/VintageStory-Issues/assets/20174013/80bec8e0-ac3b-4316-a596-932fb83395ce)

**Comment by reivilibre** [comment] 2024-04-10 06:24
If it's of interest, I reproduced in Vanilla 1.19.5 (no mods). Asking the game host to restart the game did the job, and it then looked like it was going to be broken again but did actually settle into a finished anvil (maybe this is how it's meant to look, I don't know).

**Comment by Craluminum2413** [comment] 2024-04-10 07:54
@reivilibre does it happen in 1.19.7?

**Comment by reivilibre** [comment] 2024-04-10 10:46
> @reivilibre does it happen in 1.19.7?

I'll give it a go, but since reloading the world fixed it before, I suspect there is some other thing (with a big question mark) that needs to happen before it can be reproduced, and I don't know if I will actually get in a situation to trigger that again, since I don't know what it is :-)

**Comment by luvitto** [comment] 2024-04-24 11:11
> @reivilibre does it happen in 1.19.7?

I was able to complete the creation of the iron anvil by updating the game from 1.19.6 to 1.19.7 and loading an old save.

**Comment by Craluminum2413** [comment] 2024-09-26 13:30
Closing due to inactivity

**Comment by Craluminum2413** [comment] 2024-10-05 11:02
Looks like still happening in 1.20.0-pre.4

**Comment by lubosmichalic** [comment] 2024-10-06 14:32
I just got the same issue in 1.20.0-pre.5

**Comment by yellowincarnate** [comment] 2024-10-06 19:45
I've also run into this bug - it persisted after restarting the game client.  Is there any information that would be helpful?

**Comment by Craluminum2413** [comment] 2024-10-13 13:42
Fixed in pre.6

**Closed by Craluminum2413** 2024-10-13 13:42 UTC
Labels: status: confirmed, priority: high, department: code
