### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by Kaphalor** [anegostudios/VintageStory-Issues#1582] opened 2022-01-14 13:06 UTC
Running on 64 bit Windows with 32 GB RAM 
Version: v1.16.0 (Stable)14.01.2022 14:03:11: Critical error occurred
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.Client.NoObf.TextureSource..ctor(ClientMain game, Size2i atlasSize, Block block, Boolean forInventory)
   bei Vintagestory.Client.NoObf.ShapeTesselatorManager.TesselateBlock(Block block, Nullable`1 quantityElements)
   bei Vintagestory.Client.NoObf.ShapeTesselatorManager.TesselateBlocks(IList`1 blocks)
   bei Vintagestory.Client.NoObf.ClientMain.OnServerBlocksItemsReceivedStep4(Action onCompleted, Int32 blockCount)
   bei Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   bei _0dbBCVS4kT4NsuDZA84yDu7r3AG._1NlBQQ8qS5idQptIBQaAbARuOfxA(Single )
   bei _vFhcDU5n6Z0hUte90jdaxlrDjR5._HuDdfzha8ZKZvU2y0RbH58r7VzR(Single )
   bei _vFhcDU5n6Z0hUte90jdaxlrDjR5._XZOFA2JA54yZjH15yys9W7vL9hj(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 479.
   bei OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 454.
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 375.
   bei _FKpOpQGqqf3cJWdQyWh1ysxsDBb._pYad7oBcQ5qtzQkYGDu4NFHQxhK(_5x3PJgrln4IBXPDNSNN0fecxKFb , String[] )
   bei _sejP0Tcz8wTg70ptIdRr3CwQmrE._pYad7oBcQ5qtzQkYGDu4NFHQxhK(ThreadStart )

**Comment by Craluminum2413** [comment] 2022-01-14 13:11
Any mods installed? List them all

**Comment by Kaphalor** [comment] 2022-01-14 13:50
Content of the client-main.txt:
`14.1.2022 14:15:40 [Notification] Client logger started.
14.1.2022 14:15:40 [Notification] Game Version: v1.16.0 (Stable)
14.1.2022 14:15:40 [Notification] Screens:
14.1.2022 14:15:40 [Notification] 0: {X=0,Y=0,Width=1920,Height=1200}, \\.\DISPLAY1 (primary)
14.1.2022 14:15:41 [Notification] OpenAL Initialized. Available Mono/Stereo Sources: 255/1
14.1.2022 14:15:41 [Notification] Graphics Card Vendor: NVIDIA Corporation
14.1.2022 14:15:41 [Notification] Graphics Card Version: 3.3.0 NVIDIA 497.29
14.1.2022 14:15:41 [Notification] Graphics Card Renderer: NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2
14.1.2022 14:15:41 [Notification] Graphics Card ShadingLanguageVersion: 3.30 NVIDIA via Cg compiler
14.1.2022 14:15:41 [Notification] Cairo Graphics Version: 1.17.3
14.1.2022 14:15:41 [Notification] OpenAL Version: 1.1 ALSOFT 1.16.0
14.1.2022 14:15:41 [Notification] C# Framework: .net Framework 4.0.30319.42000
14.1.2022 14:15:41 [Notification] OpenTK Version: 3.3.2 (A set of fast, low-level C# bindings for OpenGL, OpenGL ES and OpenAL.)
14.1.2022 14:15:41 [Notification] Start discovering assets
14.1.2022 14:15:41 [Notification] Found 18 base assets in category lang
14.1.2022 14:15:41 [Notification] Found 0 base assets in category patches
14.1.2022 14:15:41 [Notification] Found 22 base assets in category config
14.1.2022 14:15:41 [Notification] Found 0 base assets in category worldproperties
14.1.2022 14:15:41 [Notification] Found 50 base assets in category sounds
14.1.2022 14:15:41 [Notification] Found 96 base assets in category shapes
14.1.2022 14:15:41 [Notification] Found 74 base assets in category shaders
14.1.2022 14:15:41 [Notification] Found 16 base assets in category shaderincludes
14.1.2022 14:15:41 [Notification] Found 128 base assets in category textures
14.1.2022 14:15:41 [Notification] Found 4 base assets in category music
14.1.2022 14:15:41 [Notification] Found 0 base assets in category dialog
14.1.2022 14:15:41 [Notification] Found 408 base assets in total
14.1.2022 14:15:41 [Notification] Loading sounds
14.1.2022 14:15:41 [Notification] (Re-)loaded frame buffers
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass . 
14.1.2022 14:15:41 [Notification] CPU Cores: 8
14.1.2022 14:15:41 [Notification] Window was resized to 1920 1200, rebuilding framebuffers...
14.1.2022 14:15:41 [Notification] (Re-)loaded frame buffers
14.1.2022 14:15:41 [Notification] Waiting for async sound loading...
14.1.2022 14:15:41 [Notification] Sounds loaded
14.1.2022 14:15:41 [Notification] Begin loading shaders
14.1.2022 14:15:41 [Notification] Load shaders now
14.1.2022 14:15:41 [Notification] Loading shaders...
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass standard. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass particlescube. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass particlesquad. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass sky. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass nightsky. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass woittest. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass transparentcompose. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass debugdepthbuffer. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass helditem. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass chunkopaque. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass chunkliquid. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass decals. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass final. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass gui. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass blur. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass chunktransparent. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass findbright. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass chunktopsoil. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass godrays. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass autocamera. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass blockhighlights. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass wireframe. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass entityanimated. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass luma. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass blit. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass particlesquad2d. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass shadowmapentityanimated. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass shadowmapgeneric. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass texture2texture. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass celestialobject. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass guitopsoil. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass entityanimatedtransparent. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass colorgrade. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass guigear. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass ssao. 
14.1.2022 14:15:41 [Notification] Loaded Shaderprogramm for render pass bilateralblur. 
14.1.2022 14:15:41 [Notification] Cached session key is valid, validating with server
14.1.2022 14:15:42 [Notification] Server validation response: Good
14.1.2022 14:15:42 [Notification] Will search the following paths for mods:
14.1.2022 14:15:42 [Notification]     D:\Vintagestory\Mods
14.1.2022 14:15:42 [Notification]     C:\Users\Gamestream SUPPORT 3\AppData\Roaming\VintagestoryData\Mods
14.1.2022 14:15:47 [Notification] Master server list retrieved. Status ok. Response length: 141240
14.1.2022 14:16:03 [Notification] Master server list retrieved. Status ok. Response length: 141240
14.1.2022 14:16:48 [Notification] Connecting to 5.101.165.25...
14.1.2022 14:16:48 [Notification] Initialized GUI Manager
14.1.2022 14:16:48 [Notification] Initialized Server Connection
14.1.2022 14:16:48 [Notification] GuiScreenConnectingToServer constructed
14.1.2022 14:16:48 [Notification] Connected to server, downloading data...
0 kilobyte received
14.1.2022 14:16:49 [Notification] Loading and pre-starting client side mods...
14.1.2022 14:16:49 [Notification] Will search the following paths for mods:
14.1.2022 14:16:49 [Notification]     D:\Vintagestory\Mods
14.1.2022 14:16:49 [Notification]     C:\Users\Gamestream SUPPORT 3\AppData\Roaming\VintagestoryData\Mods
14.1.2022 14:16:49 [Notification] Found 3 mods (0 disabled)
14.1.2022 14:16:49 [Notification] Mods, sorted by dependency: game, creative, survival
14.1.2022 14:16:49 [Notification] Instantiated 76 mod systems from 3 enabled mods
14.1.2022 14:16:49 [Notification] Done loading and pre-starting client side mods.
14.1.2022 14:16:49 [Notification] External Origins in load order: modorigin@D:\Vintagestory\assets\creative\, modorigin@D:\Vintagestory\assets\survival\
14.1.2022 14:16:49 [Notification] Found 0 external assets in category lang
14.1.2022 14:16:49 [Notification] Found 8 external assets in category patches
14.1.2022 14:16:49 [Notification] Found 41 external assets in category config
14.1.2022 14:16:49 [Notification] Found 23 external assets in category worldproperties
14.1.2022 14:16:49 [Notification] Found 328 external assets in category sounds
14.1.2022 14:16:49 [Notification] Found 2316 external assets in category shapes
14.1.2022 14:16:49 [Notification] Found 9 external assets in category shaders
14.1.2022 14:16:49 [Notification] Found 0 external assets in category shaderincludes
14.1.2022 14:16:49 [Notification] Found 4115 external assets in category textures
14.1.2022 14:16:49 [Notification] Found 63 external assets in category music
14.1.2022 14:16:49 [Notification] Found 17 external assets in category dialog
14.1.2022 14:16:49 [Notification] Reloaded lang file now with mod assets
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass anvilworkitem. 
14.1.2022 14:16:49 [Notification] JsonPatch Loader: 2 patches total, no errors
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass aurora. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass rift. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass sleepoverlay. 
14.1.2022 14:16:49 [Notification] Started 48 systems on Client:
14.1.2022 14:16:49 [Notification]     Mod 'VSEssentials.dll' (game):
14.1.2022 14:16:49 [Notification]         Vintagestory.ServerMods.Core
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.EntityPartitioning
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.ErrorReporter
14.1.2022 14:16:49 [Notification]         Vintagestory.ServerMods.ModCompatiblityUtil
14.1.2022 14:16:49 [Notification]         Vintagestory.ServerMods.NoObf.ModJsonPatchLoader
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.FallingBlockParticlesModSystem
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.CharacterExtraDialogs
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.EntityNameTagRendererRegistry
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.POIRegistry
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.RoomRegistry
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.WeatherSystemCommands
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.WeatherSystemClient
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.WorldMapManager
14.1.2022 14:16:49 [Notification]         Vintagestory.ServerMods.LoadColorMaps
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.ClothManager
14.1.2022 14:16:49 [Notification]     Mod 'VSSurvivalMod.dll' (survival):
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.SaplingControl
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.SurvivalCoreSystem
14.1.2022 14:16:49 [Notification]         Vintagestory.ServerMods.GenFromHeightmap
14.1.2022 14:16:49 [Notification]         Vintagestory.ServerMods.GenMaps
14.1.2022 14:16:49 [Notification]         Vintagestory.ServerMods.DebugSystem
14.1.2022 14:16:49 [Notification]         Vintagestory.ServerMods.UpgradeTasks
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.MyceliumSystem
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.ModSystemAuction
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.ModSystemHandbook
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.LiquidItemStackRenderer
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.CharacterSystem
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.RecipeRegistrySystem
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.FruitingSystem
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.ModSystemRifts
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.ModSystemRiftWeather
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.ModTemperature
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.SystemTemporalStability
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.MealMeshCache
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.ModSystemWearableStats
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.ModSystemBlockReinforcement
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.ChiselBlockModelCache
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.GameEffects
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.ModJournal
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.ModLootRandomizer
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.ModSleeping
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.TeleporterManager
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.Mechanics.MechanicalPowerMod
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.TradeHandbookInfo
14.1.2022 14:16:49 [Notification]         Vintagestory.ServerMods.GenStructures
14.1.2022 14:16:49 [Notification]         Vintagestory.ServerMods.GenStructuresPosPass
14.1.2022 14:16:49 [Notification]         Vintagestory.GameContent.TraderOutfits
14.1.2022 14:16:49 [Notification]     Mod 'VSCreativeMod.dll' (creative):
14.1.2022 14:16:49 [Notification]         Vintagestory.ServerMods.Core
14.1.2022 14:16:49 [Notification]         Vintagestory.ServerMods.WorldEdit.WorldEdit
14.1.2022 14:16:49 [Notification] Loading shaders...
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass standard. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass particlescube. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass particlesquad. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass sky. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass nightsky. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass woittest. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass transparentcompose. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass debugdepthbuffer. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass helditem. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass chunkopaque. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass chunkliquid. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass decals. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass final. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass gui. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass blur. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass chunktransparent. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass findbright. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass chunktopsoil. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass godrays. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass autocamera. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass blockhighlights. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass wireframe. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass entityanimated. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass luma. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass blit. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass particlesquad2d. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass shadowmapentityanimated. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass shadowmapgeneric. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass texture2texture. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass celestialobject. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass guitopsoil. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass entityanimatedtransparent. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass colorgrade. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass guigear. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass ssao. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass bilateralblur. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass anvilworkitem. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass aurora. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass rift. 
14.1.2022 14:16:49 [Notification] Loaded Shaderprogramm for render pass sleepoverlay. 
14.1.2022 14:16:49 [Notification] Reloaded shaders now with mod assets
14.1.2022 14:16:49 [Notification] Processed server identification
14.1.2022 14:16:49 [Notification] Map initialized
14.1.2022 14:16:50 [Notification] Received level init
14.1.2022 14:16:50 [Notification] Connected to server, downloading data...
191 kilobyte received
14.1.2022 14:16:50 [Notification] Connected to server, downloading data...
351 kilobyte received
14.1.2022 14:16:50 [Notification] Connected to server, downloading data...
511 kilobyte received
14.1.2022 14:16:50 [Notification] Connected to server, downloading data...
513 kilobyte received
14.1.2022 14:16:50 [Notification] Received server assets
14.1.2022 14:16:51 [Notification] Connected to server, downloading data...
504 kilobyte received
14.1.2022 14:16:51 [Notification] Loaded 2379 item types from server
14.1.2022 14:16:51 [Warning] Did not find required shape game:shapes/block/metal/distiller.json anywhere. (defined in Shape for block game:distiller-north)
14.1.2022 14:16:51 [Warning] Did not find required shape game:shapes/block/plant/papyrus/medium.json anywhere. (defined in Shape for block game:tallplant-papyrus-land-normal-free)
14.1.2022 14:16:51 [Warning] Did not find required shape game:shapes/block/plant/papyrus/tall.json anywhere. (defined in Alternate shape for block game:tallplant-papyrus-land-normal-free alternate:1)
14.1.2022 14:16:51 [Warning] Did not find required shape game:shapes/block/plant/papyrus/harvested.json anywhere. (defined in Shape for block game:tallplant-papyrus-land-harvested-free)
14.1.2022 14:16:51 [Warning] Did not find required shape game:shapes/block/plant/waterreeds_ice.json anywhere. (defined in Shape for block game:tallplant-coopersreed-ice-normal-free)
14.1.2022 14:16:51 [Warning] Did not find required shape game:shapes/block/plant/waterreeds.json anywhere. (defined in Shape for block game:tallplant-coopersreed-water-normal-free)
14.1.2022 14:16:51 [Warning] Did not find required shape game:shapes/block/wood/torch/ground.json anywhere. (defined in Shape for block game:redtorch-up)
14.1.2022 14:16:51 [Warning] Did not find required shape game:shapes/block/wood/torch/wall.json anywhere. (defined in Shape for block game:redtorch-north)
14.1.2022 14:16:51 [Warning] Did not find required shape game:shapes/block/wood/torch-extinct/ground.json anywhere. (defined in Shape for block game:torch-extinct-up)
14.1.2022 14:16:51 [Warning] Did not find required shape game:shapes/block/wood/torch-burnedout/ground.json anywhere. (defined in Shape for block game:torch-burnedout-up)
14.1.2022 14:16:51 [Warning] Did not find required shape game:shapes/block/wood/torch-extinct/wall.json anywhere. (defined in Shape for block game:torch-extinct-north)
14.1.2022 14:16:51 [Warning] Did not find required shape game:shapes/block/wood/torch-burnedout/wall.json anywhere. (defined in Shape for block game:torch-burnedout-north)
14.1.2022 14:16:52 [Notification] Collected 1528 shapes to tesselate.
14.1.2022 14:16:52 [Fatal] Caught unhandled exception in BlockTextureCollection thread. Exiting game.
14.1.2022 14:16:52 [Fatal] System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.GameContent.BlockReeds.OnCollectTextures(ICoreAPI api, ITextureLocationDictionary textureDict)
   bei Vintagestory.Client.NoObf.BlockTextureAtlasManager.CollectTextures(IList`1 blocks, OrderedDictionary`2 shapes)
   bei Vintagestory.Client.NoObf.OffThreadCollectionBlocks.Process()
14.1.2022 14:16:52 [Notification] Composed 1 4096x4096 entities texture atlases from 181 textures (last textureid = 301)
14.1.2022 14:16:53 [Warning] Texture asset 'game:textures/block/food/pie/fill-redapple.png' not found (defined in Item game:ciderportion-redapple).
14.1.2022 14:16:53 [Warning] Texture asset 'game:textures/block/food/pie/fill-pinkapple.png' not found (defined in Item game:ciderportion-pinkapple).
14.1.2022 14:16:53 [Warning] Texture asset 'game:textures/block/food/pie/fill-yellowapple.png' not found (defined in Item game:ciderportion-yellowapple).
14.1.2022 14:16:53 [Warning] Texture asset 'game:textures/block/food/pie/fill-redapple.png' not found (defined in Item game:juiceportion-redapple).
14.1.2022 14:16:53 [Warning] Texture asset 'game:textures/block/food/pie/fill-pinkapple.png' not found (defined in Item game:juiceportion-pinkapple).
14.1.2022 14:16:53 [Warning] Texture asset 'game:textures/block/food/pie/fill-yellowapple.png' not found (defined in Item game:juiceportion-yellowapple).
14.1.2022 14:16:53 [Warning] Texture asset 'game:textures/block/food/pie/fill-redapple.png' not found (defined in Item game:spiritportion-redapple).
14.1.2022 14:16:53 [Warning] Texture asset 'game:textures/block/food/pie/fill-pinkapple.png' not found (defined in Item game:spiritportion-pinkapple).
14.1.2022 14:16:53 [Warning] Texture asset 'game:textures/block/food/pie/fill-yellowapple.png' not found (defined in Item game:spiritportion-yellowapple).
14.1.2022 14:16:53 [Notification] Composed 1 4096x4096 items texture atlases from 1235 textures (last textureid = 302)
14.1.2022 14:16:53 [Notification] Reloaded sounds (async), now with mod assets
14.1.2022 14:16:58 [Notification] Composed 1 4096x4096 blocks texture atlases from 1142 textures (last textureid = 303)
14.1.2022 14:16:58 [Notification] Loaded 86Heis47 block types from server
14.1.2022 14:16:58 [Notification] Color maps loaded

14.1.2022 14:16:59 [Error] Unable to initialize TextureSource for block game:tallplant-coopersreed-ice-harvested-free. Will crash now.
14.1.2022 14:16:59 [Fatal] Version: v1.16.0 (Stable)14.01.2022 14:16:59: Critical error occurred
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.Client.NoObf.TextureSource..ctor(ClientMain game, Size2i atlasSize, Block block, Boolean forInventory)
   bei Vintagestory.Client.NoObf.ShapeTesselatorManager.TesselateBlock(Block block, Nullable`1 quantityElements)
   bei Vintagestory.Client.NoObf.ShapeTesselatorManager.TesselateBlocks(IList`1 blocks)
   bei Vintagestory.Client.NoObf.ClientMain.OnServerBlocksItemsReceivedStep4(Action onCompleted, Int32 blockCount)
   bei Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   bei _0dbBCVS4kT4NsuDZA84yDu7r3AG._1NlBQQ8qS5idQptIBQaAbARuOfxA(Single )
   bei _vFhcDU5n6Z0hUte90jdaxlrDjR5._HuDdfzha8ZKZvU2y0RbH58r7VzR(Single )
   bei _vFhcDU5n6Z0hUte90jdaxlrDjR5._XZOFA2JA54yZjH15yys9W7vL9hj(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 479.
   bei OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 454.
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 375.
   bei _FKpOpQGqqf3cJWdQyWh1ysxsDBb._pYad7oBcQ5qtzQkYGDu4NFHQxhK(_5x3PJgrln4IBXPDNSNN0fecxKFb , String[] )
   bei _sejP0Tcz8wTg70ptIdRr3CwQmrE._pYad7oBcQ5qtzQkYGDu4NFHQxhK(ThreadStart )
-------------------------------
Crash written to file at "C:\Users\3\AppData\Roaming\VintagestoryData\Logs\client-crash.txt"

14.1.2022 14:16:59 [Notification] Exiting game now. Server running=False. Exit reason: Game crashed`

**Comment by copygirl** [comment] 2022-01-14 15:49
Closing as duplicate of #1572. As confirmed in #1579, the issue appears to be solved by reinstalling the game completely.

**Closed by copygirl** 2022-01-14 15:49 UTC
Labels: status: duplicate

**Comment by Kaphalor** [comment] 2022-01-14 19:19
Will check next week, but I'm not sure that a reinstall will help, since
the game was just installed on a machine where it never was installed
before.
Nevertheless, will give it a try next week.
Have a nice weekend.

copygirl ***@***.***> schrieb am Fr., 14. Jan. 2022, 16:50:

**Comment by copygirl** [comment] 2022-01-15 05:42
If the issue is not resolved by reinstalling, it might be a more serious issue than I initially though. I kept issue #1587 open for the developers to track and informed them again about the severity.
