### ISSUE TITLE
(1.14.0-rc3) Reading lore "destruction1"

### ISSUE THREAD

**Issue by Monolithys** [anegostudios/VintageStory-Issues#663] opened 2020-11-25 18:48 UTC
**Game Version:** v1.14.0-rc.3 
**Platform:** Windows
**Modded:** No

### Description
Try to read lore (in russian transcription) - i think all problem with link to translate

### How to reproduce
1. Try to read lore "Destruction 1"

### Logs
Running on 64 bit Windows with 32 GB RAM 
Version: v1.14.0-rc.3 (Unstable)25.11.2020 21:41:39: Critical error occurred
System.IndexOutOfRangeException: Индекс находился вне границ массива.
   в Vintagestory.GameContent.GuiDialogJournal.onClickItem(Int32 i)
   в Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   в Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   в Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   в Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   в Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args)
   в Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args)
   в Vintagestory.Client.NoObf.ClientMain.OnMouseUp(MouseEvent args)
   в Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   в System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   в System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   в OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   в OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   в OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   в OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   в _4BWchexiFigD9Q16Uzu1AHRcMkKA._F6I3lsgrc5VRUFEGnBoXsboBGFs(_zaqE2EDRPzgKzO45PKPCgTGhJk6 , String[] )
   в _ZkFtsNKa9prG34Jd8zC0yw7G6T4._F6I3lsgrc5VRUFEGnBoXsboBGFs(ThreadStart )
-------------------------------

If need something more - just say it.

**Comment by copygirl** [comment] 2020-11-25 19:06
This is a duplicate of #661 but thank you for reporting!

**Closed by copygirl** 2020-11-25 19:06 UTC
Labels: status: duplicate
