### ISSUE TITLE
Cave-in system critical problem.

### ISSUE THREAD

**Issue by CookieBoy21** [anegostudios/VintageStory-Issues#4439] opened 2024-11-05 00:46 UTC
### Game Version

v1.20.0 pre-9

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Rocks 3 blocks height above mantle have 100% instability. Touching it can trigger chain reaction of rocks collapses and they will fall on the surfaces. It's can burn/crash potato computers.

### How to reproduce

Just destroy rocks 3 blocks height above mantle.

### Screenshots

<img width="1280" alt="Vintagestory Screenshot 2024 11 05 - 00 47 44 08" src="https://github.com/user-attachments/assets/582a22c0-11a5-422a-bf00-7e02303534c3">

https://github.com/user-attachments/assets/8a2333e2-9552-4f80-8c2b-69815764ef1c

https://github.com/user-attachments/assets/3c5dd03d-4b20-4d7f-98fa-6d7074286a54

https://github.com/user-attachments/assets/a4502211-9393-47d9-895b-9a76d48b1eec

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2024-11-05 10:19
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/3567

**Closed by Craluminum2413** 2024-11-05 10:19 UTC
Labels: status: new
