### ISSUE TITLE
CTD when using a translocator

### ISSUE THREAD

**Issue by pingouyn** [anegostudios/VintageStory-Issues#3669] opened 2024-03-04 00:36 UTC
### Game Version

v1.19.3

### Platform

Linux

### Modded

None

### SP/MP

Multiplayer

### Description

Only mod used is HUD Clock.
CTD when using a translocator.

### How to reproduce

1. Repaired a translocator "A" close to my base.
2.  Used it for the first time and arrived at translocator "B".
3. Explored the newly found cave for a while.
4. Tried to use translocator "B" to go back to the base.  Crash to Desktop (log attached).  The server did not crash, only the client.
5. I launched the client again, I was in front of translocator "A", by the base.
6. Used translocator "A" again, then translocator "B".  No crash this time around, no error. 

### Logs

Running on 64 bit Linux (Ubuntu 23.10) [Kernel 6.5.0.21] with 31994 MB RAM
Game Version: v1.19.3 (Stable)
04/03/2024 01:26:34: Critical error occurred
Loaded Mods: game@1.19.3, hudclock@3.4.0, creative@1.19.3, survival@1.19.3
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 75
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 808
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 724
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 675
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 650
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by radfast** [comment] 2024-03-05 09:01
Likely a HUDClock issue.

(Reasoning: source code `VintagestoryLib\Client\Systems\Render\RenderEntities.cs` method `OnBeforeRender(Single dt)` has no line 75 in vanilla, it ends on line 72.  Therefore, to produce this stacktrace, a mod must have patched this code.)

If the error occurs in vanilla we can re-open, otherwise please report to HUDClock author.

**Comment by pingouyn** [comment] 2024-03-14 23:53
Hi radfast, I informed the Simple HUD Clock developer.  Sorry for the delay.

**Comment by rhonibaer** [comment] 2024-03-22 22:15
hi @radfast 
my mod is not using or calling the 'RenderEntities' class. so not caused by my mod.

**Comment by pingouyn** [comment] 2024-03-25 17:02
If someone is reading this, the case has been closed and I do not seem to have the option to re-open the report.

I do not know the process from this point forward.
Could someone at VS please let me know if the bug report is still valid and will be re-opened, or if I need to make a new one?

**Comment by Craluminum2413** [comment] 2024-04-08 15:09
Duplicate of #3550

**Closed by Craluminum2413** 2024-04-08 15:09 UTC
Labels: status: in-progress, 3rd party issue
