### ISSUE TITLE
I couldnt join any MP game at all, modded or vanilla

### ISSUE THREAD

**Issue by Waiban** [anegostudios/VintageStory-Issues#3834] opened 2024-04-21 19:03 UTC
### Game Version

v1.19.7

### Platform

Windows

### Modded

Both Vanilla and Modded

### SP/MP

Multiplayer

### Description

Hello, i cant join or play a multiplayer server (modded or vanilla) due to extreme slow speed when trying to join the server. It took ages to load any server and if i successfully joined one. I'll get hit by massive lag spike, making the game entirely unplayable. On top of that, i couldn't download any mods from VS moddb one-click install, it will freeze my game and i had to close it down from task manager. My friend also happened to have same problems like the slow loading speed and massive lags when playing MP together.

Please, Its been happening for two days and both of us cant enjoy the game to the fullest, everything was fine and dandy until we got hit by the bugs. It's stressed us out and amplified our burnout.

I believed it's game-wide bug, some players (from VS discord server's bug report) were affected and some doesn't. This is the only crash logs it geneterated from this headache of problem.

### How to reproduce

We really don't know how to reproduce as it just appeared yesterday and bogging us down.

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/31327547/f897079c-8ab3-4250-a590-83f6f6abce99)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/31327547/1d82c828-e58e-403d-baa3-a7a6dc6b3e61)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/31327547/a9e196c9-692c-4798-9120-dd8e9de6f3b9)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/31327547/de3c151f-1af1-42f7-896b-d780bf9e2f07)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/31327547/deaa8180-8a81-44ef-a48d-827aace50f89)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/31327547/11541a55-b23e-4e0e-be82-f7c538826e00)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/31327547/65b9e620-93a1-45ec-8b82-6a64b6098e95)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/31327547/ea9836ce-e405-47f6-bbb9-e073064c9aa4)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/31327547/086cf4a5-36cd-42f3-991e-7380bc3e35f2)

### Logs

```_Game Version: v1.19.7 (Stable)
4/21/2024 6:26:56 PM: Critical error occurred
Loaded Mods: 
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'The ThreadLocal object has been disposed.'.
   at System.Threading.ThreadLocal`1.GetValueSlow()
   at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionStatesNative(IWorldAccessor world, ItemSlot inslot) in VintagestoryApi\Common\Collectible\Collectible.cs:line 2466
   at Vintagestory.API.Common.CollectibleObject.AppendPerishableInfoText(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1822
   at Vintagestory.API.Common.CollectibleObject.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1759
   at Vintagestory.GameContent.GuiHandbookItemStackPage..ctor(ICoreClientAPI capi, ItemStack stack) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 33
   at Vintagestory.GameContent.ModSystemSurvivalHandbook.onCreatePagesAsync() in VSSurvivalMod\Systems\Handbook\SurvivalHandbook.cs:line 79
   at Vintagestory.GameContent.GuiDialogHandbook.LoadPages_Async() in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 418
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()_```

**Comment by Craluminum2413** [comment] 2024-06-29 15:31
Duplicate of #3947

**Closed** 2024-09-26 13:50 UTC
Labels: status: incomplete
