### ISSUE TITLE
Echo chamber crash the game

### ISSUE THREAD

**Issue by dann1kid** [anegostudios/VintageStory-Issues#1426] opened 2021-11-24 23:15 UTC
**Game Version:** 1,15,9
**Platform:** Windows 
**Modded:** Yes
**SP/MP:**  Multiplayer 

### Description
Trying to put the disc on the echo chamber leads to crash

### How to reproduce
1. Take a disk
2. Use it on 'echo chamber'
3. It crashes 

### Logs
```
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в Vintagestory.GameContent.BlockEntityEchoChamber.<>cDisplayClass20_0.<onTrackLoaded>b0()
   в Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   в _rnlVSzJ2AGPu2719D3re8Z7kN2c._iCctvUrJRYdSyJrBVxt5h8N0k5h(Single )
   в _o0lbNJXQO06me4d8j661Kh7y0zO._HmSBpw6fP4XFLEcv29tc0ifOKYvb(Single )
   в _o0lbNJXQO06me4d8j661Kh7y0zO._3U99eoPu0PaDLPVrL8tfzH5UDEJ(Single )
   в Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   в System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   в OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   в OpenTK.GameWindow.DispatchRenderFrame()
   в OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   в _M48MnHH5BAvHUzcYoEuchRW0acb._e0atQ8VmmvgBK7zb3Yh4iDqOiHY(_UGHNIsOGTJBe1BTRXYmLwHTbmS , String[] )
   в _xNqQDGqRsRSMIeuzt2MHKQHDzSd._e0atQ8VmmvgBK7zb3Yh4iDqOiHY(ThreadStart )
```

**Comment by Craluminum2413** [comment] 2021-11-25 09:19
Duplicate of #797

**Comment by Craluminum2413** [comment] 2021-12-22 22:33
@copygirl it is duplicate

**Closed** 2021-12-22 23:40 UTC
Labels: status: duplicate
