### ISSUE TITLE
game crashed when placing copper anvil (cannot reproduce)

### ISSUE THREAD

**Issue by thehuntedpie** [anegostudios/VintageStory-Issues#347] opened 2019-11-28 21:48 UTC
**Game Version:** 1.11.1 (stable)
**Platform:** Windows (which?)
**Modded:**  Yes (Abject Poverty Craft)

### Description
Explain the issue you're running into.

game crashed when placing copper anvil next to bronze anvil

### How to reproduce
cannot reproduce

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.11.1 (Stable)11/28/2019 11:46:07 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.InventoryBase.SlotsFromTreeAttributes(ITreeAttribute tree, ItemSlot[] slots, List`1 modifiedSlots)
   at Vintagestory.API.Common.InventoryGeneric.FromTreeAttributes(ITreeAttribute treeAttribute)
   at Vintagestory.GameContent.BlockEntityItemPile.FromTreeAtributes(ITreeAttribute tree, IWorldAccessor worldForResolving)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(_4H2TAYqyjJbArLiLvV3rsQmDeUo packet)
   at _ptqAFz0HkzTKz1h9p6ez8652aj5._EfJCtb1A0mwtdglHOV5xcLZFWYG(Single )
   at _fwfMex4OnvtnqBZuOa2VKa7wKfD._nmjOu6IAyvjdULmua74Q3WKReaE(Single )
   at _wvauHokYACjUxho1jIcXz9YF5Th._5CJ9MJ9J1WRa2HxE3foqOFPv0sD(Single )
   at _wvauHokYACjUxho1jIcXz9YF5Th._XZIzNlV22b6kWSOSFfx6dOcazY(Single )
   at _93p1ko0VOT3s5orIQ8NaBwI5pPD._E9qCRdX4Ew3gjatqIiLagcBrYM1A(Object , FrameEventArgs )
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _dlonPAHkYdoAFiGslNynsGbaDFq._8elR8MmcoDgjMIe2sgpAwab9Dnp(_BULmFtV7lvG1053qIyIBTMCX7RJ , String[] )
   at _lQgBjjHoFrDHvmqhGD1SL0CDl4UA._8elR8MmcoDgjMIe2sgpAwab9Dnp(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 11/23/2019 8:25:38 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at Vintagestory.API.Client.ElementBounds.buildBoundsFromChildren()
   at Vintagestory.API.Client.ElementBounds.CalcWorldBounds()
   at Vintagestory.API.Client.GuiElementDialogBackground.ComposeElements(Cairo.Context, Cairo.ImageSurface)
   at Vintagestory.API.Client.GuiComposer.Compose(Boolean)
   at Vintagestory.GameContent.GuiDialogBlockEntityRecipeSelector.SetupDialog()
   at Vintagestory.GameContent.BlockEntityKnappingSurface.OpenDialog(Vintagestory.API.Client.IClientWorldAccessor, Vintagestory.API.MathTools.BlockPos, Vintagestory.API.Common.ItemStack)
   at Vintagestory.GameContent.BlockEntityKnappingSurface.OnBeginUse(Vintagestory.API.Common.IPlayer, Vintagestory.API.Common.BlockSelection)
   at Vintagestory.GameContent.ItemStone.OnHeldAttackStart(Vintagestory.API.Common.ItemSlot, Vintagestory.API.Common.EntityAgent, Vintagestory.API.Common.BlockSelection, Vintagestory.API.Common.EntitySelection, Vintagestory.API.Common.EnumHandHandling ByRef)
   at _zuFnp2O9cz6sCtbgAJPykRFCTRF._bbFmLKoy4jnkvDbfq1GVATe9ohH(Vintagestory.API.Common.BlockSelection, Vintagestory.API.Common.EntitySelection, Vintagestory.API.Common.EnumHandInteract, Vintagestory.API.Common.EnumHandHandling ByRef)
   at _zuFnp2O9cz6sCtbgAJPykRFCTRF._BTbX0aLXDXXektI2hthiNDztwZH(Single)
   at _zuFnp2O9cz6sCtbgAJPykRFCTRF._q4c5LFgMxclWCoYDC4FD4FsI7cG(Single)
   at _AJmwB9gjRtQfKbEhJwx3zt8nBMo._1P3gicAQ2f0W4MdXai0ehZEgtGP(Vintagestory.API.Client.EnumRenderStage, Single)
   at _KTck4LCOI9Iqo8fFumFwcvnhzEf._1P3gicAQ2f0W4MdXai0ehZEgtGP(Vintagestory.API.Client.EnumRenderStage, Single)
   at _KTck4LCOI9Iqo8fFumFwcvnhzEf._vtqO5MeBAolhEI4OYcmCVe6z01w(Single)
   at _D00tv15uR3atThWOWk7dLtkesZS._vtqO5MeBAolhEI4OYcmCVe6z01w(Single)
   at _Uzs3ZIOcbeuAACiw0HSA5XAvMcKA._yE1rUldb2bSjw6eqwxEqzSn0q9O(Single)
   at _Uzs3ZIOcbeuAACiw0HSA5XAvMcKA._vNGHYtGKMIbjKqT6XUSd3vg0qMf(Single)
   at _k7exH1LagwKlon0bbWt5grgXY46._w10jFEuqMXWmlNpDfpiNvzId7nn(System.Object, OpenTK.FrameEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.GameWindow.RaiseRenderFrame(Double, Double ByRef)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double, Double)
   at _BpmYDwte9UgHL1NeHQCFwWPUFoAA._Sczbg0FjRjmNsd8yOfTFweX0FGBA(_dQW71ep8GlJRb0IDfmlVgByPa4e, System.String[])
   at _NMmYWPalISDmLBuhcXuBforA4SJ._Sczbg0FjRjmNsd8yOfTFweX0FGBA(System.Threading.ThreadStart)

 }
{ TimeGenerated = 9/19/2019 1:45:52 AM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FFFD55E85BC
Stack:
   at System.Environment._Exit(Int32)
   at System.Environment._Exit(Int32)
   at System.Environment.Exit(Int32)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.NativeWindow.OnClosedInternal(System.Object, System.EventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.Platform.Windows.WinGLNative.HandleDestroy(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   at OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.DestroyWindow()
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(OpenTK.Platform.Windows.MSG ByRef)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(OpenTK.Platform.Windows.MSG ByRef)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double, Double)
   at _EzYbY8XqDBpHTSntlGLRo1yyxG8._XiLrCitjPfhBs0UfoaQ5onoUxz5(_tgdBQ99mXDSNgCdsj3xYCQHkaYD, System.String[])
   at _LtZ3lNX4BW7l2WIPILwb1wFLLmj._XiLrCitjPfhBs0UfoaQ5onoUxz5(System.Threading.ThreadStart)
   at _EzYbY8XqDBpHTSntlGLRo1yyxG8._vHJc7ly1O5aWgHAKAmV8WEHUIeD(System.String[])
 }
```

**Comment by Bloodsaw** [comment] 2020-03-02 23:07
Could this be related to #385 and therefore fixed in the upcoming 1.12.6?
"Object reference not set to an instance of an object." could be the firepit ticker listener?

**Comment by Zaldaryon** [comment] 2020-03-06 21:01
When I placed a forge in the ground, it crashed.

- Few seconds before that, there was another forge in the same spot, not lit, and empty.
- The ground was made with granite cobblestone.
- It was on multiplayer, and the server had some small lag.

Running on 64 bit Windows with 16 GB RAM 
Version: v1.12.6 (Stable)06/03/2020 16:52:25: Critical error occurred
System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
   em Vintagestory.API.Common.InventoryBase.SlotsFromTreeAttributes(ITreeAttribute tree, ItemSlot[] slots, List1 modifiedSlots)
   em Vintagestory.API.Common.InventoryGeneric.FromTreeAttributes(ITreeAttribute treeAttribute)
   em Vintagestory.GameContent.BlockEntityItemPile.FromTreeAtributes(ITreeAttribute tree, IWorldAccessor worldForResolving)
   em Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(_7OUkGToX9NINMWWPfgPKDVWAzxq packet)
   em _CeG6XgwLRetaWBDy7Vuk520qgAQ._mQhaVaLnY2Z1jjUbgwS7BEeClrG(Single )
   em _WgVFI8rJI44rVQv521oBIjuWBxl._5QlzzE5xabSDGWATlodeOUeMK2b(Single )
   em _3bQQdrrneYMg7sUqAp4FsQ2XEfN._lShc2IGpVH0SOA7ydOiSsErkATH(Single )
   em _3bQQdrrneYMg7sUqAp4FsQ2XEfN._k3aLAIz3swGZO8aqd7pDrKnxALc(Single )
   em Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   em System.EventHandler1.Invoke(Object sender, TEventArgs e)
   em OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   em OpenTK.GameWindow.DispatchRenderFrame()
   em OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   em _TPKNmFO93xHjVpa9EspHS9LXWzH._TsFumLr7TNG7iLJEc5uVYqFSeNG(_qRgBLoQrmfmbiUcRN39BpLhs3mN , String[] )
   em _QHQMScYkRrkBYdQDlv19fyrujIx._TsFumLr7TNG7iLJEc5uVYqFSeNG(ThreadStart )

**Comment by tyronx** [comment] 2020-03-07 17:43
@Bloodsaw no, this crash is likely not related. The firepit issue is a rather recent one, it was introduced in one of the v1.12 versions. The reported crash here is from v1.11.

My 2 theories on this is:
- An orphaned block entity structure is stored at this block position and messes with things

- A race condition issue where, on the client side, momentarily the wrong block entity instance is at this 
block position and thus crashes because, for example a chest block entity tries to read its serialized tree data while in reality that data is actually for an item pile block entity.

No idea how to reproduce or what could be the cause at this point.

**Comment by sirStroam** [comment] 2021-06-30 06:32
Could not reproduce in 1.15 pre 10. Closing until reproducible or more reports.

**Closed by sirStroam** 2021-06-30 06:32 UTC
Labels: status: new, target: survival
