### ISSUE TITLE
Random Crash?

### ISSUE THREAD

**Issue by AndironMob** [anegostudios/VintageStory-Issues#4673] opened 2024-12-12 05:25 UTC
### Game Version

v1.20.0-rc.1 (Unstable)

### Platform

Windows

### Modded

None

### SP/MP

Multiplayer

### Description

Just finished clayforming crocks and bowls, was not actively inputting controls when the game crashed.

### Logs

Running on 64 bit Windows 10.0.19045.0 with 65375 MB RAM
Game Version: v1.20.0-rc.1 (Unstable)
12/12/2024 12:18:57 AM: Critical error occurred
Loaded Mods: game@1.20.0-rc.1, creative@1.20.0-rc.1, survival@1.20.0-rc.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityBehaviorPlayerPhysics.OnRenderFrame(Single dt, EnumRenderStage stage) in VSEssentials\Entity\Behavior\BehaviorPlayerPhysics.cs:line 352
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 188
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 824
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 161
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 127
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 329
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Craluminum2413** [comment] 2024-12-12 11:06
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4559

**Closed by Craluminum2413** 2024-12-12 11:06 UTC
Labels: status: new
