### ISSUE TITLE
it is impossible to make an "electrum plate"

### ISSUE THREAD

**Issue by drabont7** [anegostudios/VintageStory-Issues#2773] opened 2023-05-22 16:57 UTC
### Game Version

v1.18.5

### Platform

Windows

### Modded

Vanilla

### SP/MP

None

### Description

there is no "electrum" in "allowedVariants" in the plate.json
it is impossible to make an "electrum plate"
("electrum plate" used in "night vision mask" and "base return teleporter" recipes)

### Logs

```Log```

**Comment by DArkHekRoMaNT** [comment] 2023-05-22 17:07
You can't create electrum block too. And also cupronickel block, nails and strips

**Comment by drabont7** [comment] 2023-05-22 19:38
> 
"electrum plate" used in "night vision mask" and "base return teleporter" recipes

**Comment by radfast** [comment] 2023-05-23 14:15
This is currently intended behaviour in 1.18.5, these game elements will be added in future.   For now it cannot be classed as an "issue", because there are also no items manufactured from electrum plate.

**Comment by DArkHekRoMaNT** [comment] 2023-05-23 14:47
@radfast 
![image](https://github.com/anegostudios/VintageStory-Issues/assets/15899143/5a1ce336-0510-44bb-89bb-b9f66713e49a)

**Comment by radfast** [comment] 2023-05-23 15:50
oh bother, that is an issue then

**Comment by radfast** [comment] 2023-05-31 18:49
Fixed in next release, thanks for reporting and thanks for patience

**Closed by radfast** 2023-05-31 18:49 UTC
Labels: status: confirmed, priority: medium, department: json
