### ISSUE TITLE
Color Correction Making World Blue

### ISSUE THREAD

**Issue by Spaceturtle7** [anegostudios/VintageStory-Issues#4619] opened 2024-12-07 21:50 UTC
### Game Version

v1.20.0-rc.1

### Platform

Mac

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Color correction issues making things more blue than things should. Changing setting doesn't fix it.

### How to reproduce

1. Start game, 2. Create world, 3. Blue world.

### Screenshots

![Screenshot 2024-12-07 at 2 43 07 PM](https://github.com/user-attachments/assets/b78f98d2-5daa-4d6b-a999-6d1ef11655b3)

### Logs

[client-main.log](https://github.com/user-attachments/files/18049965/client-main.log)
[server-main.log](https://github.com/user-attachments/files/18049970/server-main.log)

**Comment by Craluminum2413** [comment] 2024-12-07 21:52
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4327

**Closed by Craluminum2413** 2024-12-07 21:52 UTC
Labels: status: new
