### ISSUE TITLE
1.15-pre2 crash reports

### ISSUE THREAD

**Issue by VolkodavMstivoy** [anegostudios/VintageStory-Issues#956] opened 2021-06-04 11:23 UTC
I expected bugs and crashes and want to help improving game. <3

### Logs
```
Running on 64 bit Windows with 4 GB RAM 
Version: v1.15.0-pre.2 (Unstable)04.06.2021 13:06:29: Critical error occurred
System.NullReferenceException: Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
   w Vintagestory.Common.WorldChunk.GetLocalBlockAtBlockPos(IWorldAccessor world, BlockPos position)
   w Vintagestory.GameContent.WeatherSimulationSnowAccum.UpdateSnowLayer(SnowAccumSnapshot sumsnapshot, Boolean ignoreOldAccum, IServerMapChunk mc, Vec2i chunkPos, IWorldChunk[] chunksCol)
   w Vintagestory.GameContent.WeatherSimulationSnowAccum.GetSnowUpdate(WeatherSimulationRegion simregion, IServerMapChunk mc, Vec2i chunkPos, IWorldChunk[] chunksCol)
   w Vintagestory.GameContent.WeatherSimulationSnowAccum.UpdateSnowLayerOffThread(WeatherSimulationRegion simregion, IServerMapChunk mc, Vec2i chunkPos)
   w Vintagestory.GameContent.WeatherSimulationSnowAccum.onThreadTick()
   w System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   w System.Threading.ThreadHelper.ThreadStart()
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 04.06.2021 13:06:31, Site = , Source = .NET Runtime, Message = Aplikacja: Vintagestory.exe
Wersja architektury: v4.0.30319
Opis: proces został przerwany z powodu nieobsłużonego wyjątku.
Informacje o wyjątku: System.NullReferenceException
   w Vintagestory.Common.WorldChunk.GetLocalBlockAtBlockPos(Vintagestory.API.Common.IWorldAccessor, Vintagestory.API.MathTools.BlockPos)
   w Vintagestory.GameContent.WeatherSimulationSnowAccum.UpdateSnowLayer(Vintagestory.GameContent.SnowAccumSnapshot, Boolean, Vintagestory.API.Common.IServerMapChunk, Vintagestory.API.MathTools.Vec2i, Vintagestory.API.Common.IWorldChunk[])
   w Vintagestory.GameContent.WeatherSimulationSnowAccum.GetSnowUpdate(Vintagestory.GameContent.WeatherSimulationRegion, Vintagestory.API.Common.IServerMapChunk, Vintagestory.API.MathTools.Vec2i, Vintagestory.API.Common.IWorldChunk[])
   w Vintagestory.GameContent.WeatherSimulationSnowAccum.UpdateSnowLayerOffThread(Vintagestory.GameContent.WeatherSimulationRegion, Vintagestory.API.Common.IServerMapChunk, Vintagestory.API.MathTools.Vec2i)
   w Vintagestory.GameContent.WeatherSimulationSnowAccum.onThreadTick()
   w System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   w System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   w System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   w System.Threading.ThreadHelper.ThreadStart()

 }

**Comment by Craluminum2413** [comment] 2021-06-04 11:28
How to reproduce them?

**Comment by Craluminum2413** [comment] 2021-06-04 11:29
#908

**Comment by Shuro** [comment] 2021-06-04 11:38
I think it is enough to have the base near mountains which can get some snow, but not 100% sure.

**Comment by copygirl** [comment] 2021-06-04 12:28
Closing as duplicate of #908. Please provide any information you may have to that issue.

**Closed by copygirl** 2021-06-04 12:28 UTC
Labels: status: duplicate, type: crash

**Comment by Craluminum2413** [comment] 2021-06-04 19:11
@Shuro Can you send a world seed? /seed

**Comment by Shuro** [comment] 2021-06-05 06:55
@Craluminum2413 Seed: 1256902896  I don't have coordinates, but it happened around the south, there is a basalt biome and south-east a mountain biome with snow on it.
