### ISSUE TITLE
Entity vanish

### ISSUE THREAD

**Issue by jaesaber** [anegostudios/VintageStory-Issues#2315] opened 2022-12-12 03:53 UTC
### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

All entities are not visible in both single player and multiplayer. Items being held are visible (sword, shield, torch etc.).

### Screenshots

![image](https://user-images.githubusercontent.com/75695375/206956953-092cf391-76d3-4874-aef4-b806a04ca8ab.png)

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2022-12-12 03:56
Duplicate of #2277

**Closed by Craluminum2413** 2022-12-12 03:56 UTC
Labels: status: new
