### ISSUE TITLE
Crash: Game crashed on start

### ISSUE THREAD

**Issue by phScholz** [anegostudios/VintageStory-Issues#441] opened 2020-03-06 07:20 UTC
**Game Version:** 1.12.5 (stable)
**Platform:** Windows 
**Modded:** No

### Description
Game crashes on start up. Apparently a NullReferenceException was thrown..

### How to reproduce
1. Well, on my system I only need to start the game ...
2. Loading shaders … 
3. Validating session with servers
4. Crash

### Expected behavior
The game starts normally :)

### Logs
````Running on 64 bit Windows with 8 GB RAM 
Version: v1.12.5 (Stable)06.03.2020 08:10:54: Critical error occurred
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.LoadTexture(IBitmap bmp, Boolean linearMag, Int32 clampMode, Boolean generateMipmaps)
   bei _mKeEWUbBZsjLS6VlGWgOoYQFk2K._KNs6g2GMtsTu5gnL4MXdRgZVlLh()
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._HdDsdRJDH8nMF88r278C4eqdINGA()
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._gjiBClIE7Yspuz65gCqPGSAnUYeb()
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._NbPATb9BXlxRc4ZhH2GgyFCUInp(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _hCuHXesCXlp0LGSdrsPFpw4up5n._mOm8EuKIvHpaJoztxNWRpAoOpbM(_55ISULxdcpPfF8D2JP831aWhOBe , String[] )
   bei _iCfIbY24GyBXP5lAwqsSlD9COxC._mOm8EuKIvHpaJoztxNWRpAoOpbM(ThreadStart )```

**Comment by phScholz** [comment] 2020-03-06 07:30
Alright. I just installed the new version 1.12.6 an now I can start the game again. Anyway, it would be nice to have some kind of notification that there actually is a new version available :) At least in the issue tracker program.

**Comment by copygirl** [comment] 2020-03-06 09:52
Duplicate of #407. Your issue is the 28th duplicate so far.

When you run into a reoccurring crash like that it would be nice if you could check whether there's already a new version released, or if you're going to report it on here, at least check the most recent issues (including [closed ones](https://github.com/anegostudios/VintageStory-Issues/issues?q=is%3Aissue+is%3Aclosed)), ideally even searching for one.

I suppose it would be worth pinning the issue. I just saw that's a possibility.

**Closed by copygirl** 2020-03-06 09:52 UTC
Labels: status: duplicate
