### ISSUE TITLE
Zero point of the map moves

### ISSUE THREAD

**Issue by JasminH62** [anegostudios/VintageStory-Issues#490] opened 2020-03-25 20:20 UTC
**Game Version:** 1.12.11 (Singleplayer)
**Platform:** Windows
**Modded:** No

Every time when I log in into the world, the zero point of the map is at a different point of the map.
Example: Position my Avatar at 0, xxx, 0 and log off, then log in again and the Avatar is at a different position, maybe 25, xxx, 37.
That seems to be bad as if I use the TP-Command I maybe arrive inside a mountain nearby.

I use Vintage-Story since V1.12.4 and I have found all times the same behavior.

Attached is a screenshot of some positions. The red columns marking the position of the different Zero-Points at some times of logging in.

![2020-03-25_20-39-18](https://user-images.githubusercontent.com/62670511/77580943-1bb69600-6edd-11ea-95de-96d4e0a3ce16.png)

P.S.: You are doing very great work and I really love to play the game!

**Comment by Bloodsaw** [comment] 2020-03-25 22:12
I can confirm this, as it happened to me a few times too. But I was not able to reproduce this reliable. Most of the time 0, x, 0 was in the same place.  

As I experienced it lately for the first time:
I set a way-point and wasn't able to find it afterwards on map. Showed them with `/waypoint list` and went to the coordinates which resulted in a totally different place I remembered. Created a new waypoint where I stand and in `/waypoint list` it showed completely different x y z values than on map or under minimap, but after relogging everything was fine again.

![image](https://user-images.githubusercontent.com/61588797/77589816-b7033780-6eec-11ea-902d-de11a9030dcf.png)
As you can see in the waypoint list the nr.3 has the coordinates [63, 140 -194] but on Map it shows [216, 146, -5] while waypoint nr.2 is missing on the map completely.

**Comment by tyronx** [comment] 2020-03-26 07:39
Woah, strange. Is that single player or multiplayer? If the latter, did that server change the `spawnRadius` value by any chance?

**Comment by JasminH62** [comment] 2020-03-26 09:53
Sorry, I forgot to write that it is single player. (Have updated the issue)

**Comment by tyronx** [comment] 2020-03-26 09:57
oi, i think you accidentally closed the issue

**Comment by JasminH62** [comment] 2020-04-09 13:54
After using now V1.12.14 and using a complete new world, the issue seems to be solved.

**Comment by copygirl** [comment] 2020-04-09 19:06
Alright, thank you! I will close it as such, then.

**Closed by copygirl** 2020-04-09 19:06 UTC
Labels: status: resolved, type: bug
