### ISSUE TITLE
crash open dashboard hosting serveur official 

### ISSUE THREAD

**Issue by antho47** [anegostudios/VintageStory-Issues#4494] opened 2024-11-11 12:34 UTC
### Game Version

v1.19.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Logs

Running on 64 bit Windows 10.0.19045.0 with 8056 MB RAM
Game Version: v1.19.8 (Stable)
11/11/2024 13:32:39: Critical error occurred
Loaded Mods: game@1.19.8, creative@1.19.8, survival@1.19.8
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.API.Client.GuiElementDropDown.ComposeCurrentValue() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementDropDown.cs:line 238
   at Vintagestory.API.Client.GuiElementDropDown.ComposeDynamicElements() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementDropDown.cs:line 230
   at Vintagestory.API.Client.GuiElementDropDown.ComposeElements(Context ctx, ImageSurface surface) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementDropDown.cs:line 146
   at Vintagestory.API.Client.GuiComposer.Compose(Boolean focusFirstElement) in VintagestoryApi\Client\UI\GuiComposer.cs:line 399
   at Vintagestory.Client.GuiScreenServerDashboard.screenSelectRegion(GameServerStatus status) in VintagestoryLib\Client\MainMenu\Screens\HostedServer\GuiScreenSelectRegion.cs:line 15
   at Vintagestory.Client.GuiScreenServerDashboard.onStatusReady(EnumAuthServerResponse reqStatus, GameServerStatus gameServerStatus) in VintagestoryLib\Client\MainMenu\Screens\HostedServer\GuiScreenServerDashboard.cs:line 52
   at Vintagestory.Client.Util.ServerCtrlBackendInterface.<>c__DisplayClass11_0.<GetStatus>b__0(EnumAuthServerResponse status, GameServerStatus response) in VintagestoryLib\Client\Util\ServerCtrlBackend\ServerCtrlBackendInterface.cs:line 133
   at Vintagestory.Client.Util.ServerCtrlBackendInterface.<>c__DisplayClass18_1`1.<runAction>b__1() in VintagestoryLib\Client\Util\ServerCtrlBackend\ServerCtrlBackendInterface.cs:line 225
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Craluminum2413** [comment] 2024-11-11 12:38
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/3158

**Closed by Craluminum2413** 2024-11-11 12:38 UTC
Labels: status: new
