### ISSUE TITLE
Muliplayer, on tutorial start 

### ISSUE THREAD

**Issue by KingKrazyKay** [anegostudios/VintageStory-Issues#2825] opened 2023-06-18 11:09 UTC
### Game Version

v1.18.5(stable)

### Platform

Windows

### Modded

None

### SP/MP

Multiplayer

### How to reproduce

Join a muliplayer world and press H. Once there go to the tutorials tab and click the Start button. Once the tutorial starts and you try to move it crashes

### Logs

Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.18.5 (Stable)
18/06/2023 2:04:10 pm: Critical error occurred
Loaded Mods: game@1.18.5, creative@1.18.5, survival@1.18.5
System.InvalidOperationException: Stack empty.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Stack`1.Peek()
   at Vintagestory.GameContent.GuiDialogHandbook.ReloadPage() in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 256
   at Vintagestory.GameContent.ModSystemTutorial.onStateUpdate(ActionBoolReturn`1 stepCall) in VSSurvivalMod\Systems\Handbook\Tutorial\ModSystemTutorial.cs:line 239
   at Vintagestory.Client.NoObf.InputAPI.TriggerInWorldAction(EnumEntityAction action, Boolean on, EnumHandling& handling) in VintagestoryLib\Client\API\InputAPI.cs:line 45
   at Vintagestory.API.Common.EntityControls.AttemptToggleAction(EnumEntityAction action, Boolean on) in VintagestoryApi\Common\Entity\EntityControls.cs:line 341
   at Vintagestory.Client.NoObf.SystemPlayerControl.OnGameTick(Single dt) in VintagestoryLib\Client\Systems\Player\PlayerControl.cs:line 83
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 85
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 813
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 712
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 165
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 683
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 627
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 126
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 07/06/2023 2:09:54 pm, Site = , Source = Windows Error Reporting, Message = Fault bucket 1813180379713846513, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.5.0
P3: 10.0.22621.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\ivano\AppData\Local\Temp\RDR59FD.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.7c2663c9-15b0-4507-89ec-7f4ecc8870cb.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.9c76851f-7cb0-407c-9971-d3addbc72235.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.d8e17d2a-38d1-480a-b5c5-bf2815e56c59.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.58e2178f-5f29-46f9-b8b3-deadebf3fa27.tmp.xml

These files may be available here:
NULL

Analysis symbol: 
Rechecking for solution: 0
Report Id: 3e4cdca1-39f6-48e4-a0b6-761207a79b12
Report Status: 268435456
Hashed bucket: ee80768c6970f7acd929b5f2de8d3cf1
Cab Guid: 0 }

**Comment by Craluminum2413** [comment] 2023-06-18 11:12
Duplicate of #2781

**Closed by Craluminum2413** 2023-06-18 11:12 UTC
Labels: status: new
