### ISSUE TITLE
Animation hand action repeated cycle

### ISSUE THREAD

**Issue by AkiraRiku** [anegostudios/VintageStory-Issues#3800] opened 2024-04-10 22:06 UTC
### Game Version

1.19.7

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Doing specific action like running action, mining, shoveling, cutting tree or any action that create animation for breaking blocks, a chance will occur while doing those mentioned action kept looping its animation. I've discovered this when I was randomly mining and running away predator, there was also an occurrence that when I was damage, the damage animation kept looping but no damage was made. It's becoming of an annoyance when doing specific job

### How to reproduce

1. do a specific action that has animation 2. Doing frequently occurs a looping action animation

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2024-04-11 10:52
Duplicate of #3774

**Closed by Craluminum2413** 2024-04-11 10:52 UTC
Labels: status: new
