### ISSUE TITLE
textures flickering black when placing blocks

### ISSUE THREAD

**Issue by reicherBene** [anegostudios/VintageStory-Issues#453] opened 2020-03-07 15:11 UTC
**Game Version:** 1.12.6
**Platform:** Windows
**Modded:** No

### Description
When placing a block, the textures of the blocks in a certain area around will briefly turn into black (sometimes just a little flicker, sometimes longer). 

### How to reproduce
I can't tell an exactly way to reproduce that but I tried around a little and I hope I found out some things that could help you reproducing.
* The bug only occurs when it's night.
* Only some blocks show that effect and I found out that this were blocks I newly placed in the world. Maybe these could be the blocks I've placed in the world after I updated Vintage Story to v1.12.6, but I'm not really sure about that. I've just created a new empty world and it appeares in the same way as in my old world.
* It doesn't occures with every placed block.
* Placing torches won't trigger that bug

### Expected behavior
Maybe keep its texture (or whatever the problem is)? It's not game breaking but kind of annoying when you want to build things.

**Comment by reicherBene** [comment] 2020-03-07 15:18
Maybe somebody can assign the labels 'status:new' and 'type:bug' ? It seems I'm not able to.
Thanks!

**Comment by reicherBene** [comment] 2020-03-07 15:26
Maybe somebody could add the missing labels? (type:bug, status:new)
(And explain me how to do that ;)
Thanks!

**Comment by copygirl** [comment] 2020-03-07 15:37
> Maybe somebody could add the missing labels? (type:bug, status:new)
> (And explain me how to do that ;)

When you select the "Bug Report" template it usually adds those labels automatically. Afterwards, only a contributor to the repository can change labels.

Regarding the issue, I think I've experienced this sometimes as well. The block light might flicker as it's recalculating in certain cases. Could be related to the ancient issue #26.

**Comment by reicherBene** [comment] 2020-03-11 19:02
Ok, since I've updated to 1.12.8, this issue is ocurring wherever I place blocks, not only in a limited area like before.

**Comment by tyronx** [comment] 2020-03-18 14:24
Thanks for the report. It is indeed a duplicate of #26

**Closed by tyronx** 2020-03-18 14:24 UTC
Labels: status: new, type: bug
