### ISSUE TITLE
Shift+click loot into full inventory loses item

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#444] opened 2020-03-06 12:31 UTC
**Game Version:** 1.12.6
**Platform:** Windows
**Modded:** No

### Description
When my inventory & hotbar are full and I shift+click an item from a loot container/mob into my inventory and there is no space the item is destroyed.

### How to reproduce
1. Kill a mob with drops
2. Fill your inventory with non-similar items
3. Shift+click to attempt a transfer of the item into your inventory

### Expected behavior
The item to stay in the inventory and not be destroyed. Perhaps the item to shake a little instead so that I know my inventory is full of non-similar items.

### Screenshots
None. Not taking pics of items not there. :3

**Comment by tyronx** [comment] 2020-03-18 14:23
thanks for the report, Vallen ^_^

I'm not able to reproduce the issue, but I did find some dialog oddities related creature harvesting in v1.12.9-rc.1, which I fixed. I assume this is what triggered this issue.

**Comment by copygirl** [comment] 2020-03-18 14:53
I'll close this as resolved for now. Please comment if it still occurs in the latest version.

**Closed by copygirl** 2020-03-18 14:53 UTC
Labels: status: resolved, target: survival, type: bug
