### ISSUE TITLE
using chalk to make a flint tool crash

### ISSUE THREAD

**Issue by prismatic-mind** [anegostudios/VintageStory-Issues#1393] opened 2021-11-03 23:35 UTC
**Game Version:** 1.5.7
**Platform:** Windows 10 
**Modded:** No 

### Description
Explain the issue you're running into.

### How to reproduce
1. place flint on ground selecting a tool (tested with axe & shovel)
2. Use chalk to break voxel
3. It crashes

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.7 (Stable)04/11/2021 00:32:35: Critical error occurred
System.IndexOutOfRangeException: L'index se trouve en dehors des limites du tableau.
   à Vintagestory.GameContent.BlockEntityKnappingSurface.OnRemove(Vec3i voxelPos, Int32 radius)
   à Vintagestory.GameContent.BlockEntityKnappingSurface.OnUseOver(IPlayer byPlayer, Vec3i voxelPos, BlockFacing facing, Boolean mouseMode)
   à Vintagestory.GameContent.ItemStone.OnHeldAttackStop(Single secondsPassed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   à Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt)
   à Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   à Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   à Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   à _gt983m53spH3zIRFvTrVgBj5MUb._m2KVBUzhniiatiiNT9yOoXoOOvL(Single )
   à _2hFm1B1DwOk1Z7yF6DtBdLeBFKaA._5soGXezAcR5oyhhq2pmELCuEn2M(Single )
   à _2hFm1B1DwOk1Z7yF6DtBdLeBFKaA._ZzmaNk5IGbtvQ61ssCzCszyBw2n(Single )
   à Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   à System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   à OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   à OpenTK.GameWindow.DispatchRenderFrame()
   à OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   à _LiN8p156auXcqjjOW5aVAZ0QkUc._fwMbTl3XHB2eqbxoLfc3FpMIE00(_CFodeVozKjT5VhVV66Wv4Bd7r3c , String[] )
   à _qBF2AKwdIhCkNZsjxBA24g20vlH._fwMbTl3XHB2eqbxoLfc3FpMIE00(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 23/10/2021 00:47:33, Site = , Source = Application Error, Message = Nom de l’application défaillante Vintagestory.exe, version : 1.15.7.0, horodatage : 0x6167103b
Nom du module défaillant : KERNELBASE.dll, version : 10.0.19041.1202, horodatage : 0xc9db1934
Code d’exception : 0xc0020001
Décalage d’erreur : 0x0000000000034f99
ID du processus défaillant : 0xde8
Heure de début de l’application défaillante : 0x01d7c74898f309fd
Chemin d’accès de l’application défaillante : C:\Users\espri\AppData\Roaming\Vintagestory\Vintagestory.exe
Chemin d’accès du module défaillant: C:\WINDOWS\System32\KERNELBASE.dll
ID de rapport : 4ae8e8e6-42ed-4cb2-8a14-74a1423cb226
Nom complet du package défaillant : 
ID de l’application relative au package défaillant :  }
--------------
{ TimeGenerated = 23/10/2021 00:47:32, Site = , Source = .NET Runtime, Message = Application : Vintagestory.exe
Version du Framework : v4.0.30319
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : code d'exception c0020001, adresse d'exception 00007FFCCE984F99
Pile :
   à System.Environment._Exit(Int32)
   à System.Environment._Exit(Int32)
   à System.Environment.Exit(Int32)
   à System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   à OpenTK.NativeWindow.OnClosedInternal(System.Object, System.EventArgs)
   à System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   à OpenTK.Platform.Windows.WinGLNative.HandleDestroy(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   à OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   à OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   à OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   à OpenTK.Platform.Windows.WinGLNative.DestroyWindow()
   à OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   à OpenTK.Platform.Windows.Functions.DispatchMessage(OpenTK.Platform.Windows.MSG ByRef)
   à OpenTK.Platform.Windows.Functions.DispatchMessage(OpenTK.Platform.Windows.MSG ByRef)
   à OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   à OpenTK.GameWindow.Run(Double, Double)
   à _LiN8p156auXcqjjOW5aVAZ0QkUc._fwMbTl3XHB2eqbxoLfc3FpMIE00(_CFodeVozKjT5VhVV66Wv4Bd7r3c, System.String[])
   à _qBF2AKwdIhCkNZsjxBA24g20vlH._fwMbTl3XHB2eqbxoLfc3FpMIE00(System.Threading.ThreadStart)
   à _LiN8p156auXcqjjOW5aVAZ0QkUc._T3I5LpJ7xVnAvOeqwIw97eoom3B(System.String[])
 }
--------------
{ TimeGenerated = 10/06/2021 00:29:11, Site = , Source = Application Hang, Message = Le programme Vintagestory.exe version 1.14.10.0 a cessé d'interagir avec Windows et a été fermé. Pour voir si plus d'informations sur le problème sont disponibles, vérifiez l'historique des problèmes dans le Panneau de configuration Sécurité et maintenance.

ID de processus : 54b0

Heure de début : 01d75d3f7d93307c

Heure d'arrêt : 7

Chemin d'accès à l'application : C:\Users\espri\AppData\Roaming\Vintagestory\Vintagestory.exe

ID de rapport : 72945e24-b962-44e8-afd3-dcf23047d412

Nom complet du package défectueux : 

ID de l'application relative à un package défectueux : 

Type de blocage : Unknown
 }
```

**Comment by Craluminum2413** [comment] 2021-11-04 09:38
Duplicate of #1279

**Closed** 2021-11-04 09:43 UTC
Labels: status: duplicate
