### ISSUE TITLE
Crash after few coal stacking in creative mode

### ISSUE THREAD

**Issue by Zelfior** [anegostudios/VintageStory-Issues#1885] opened 2022-05-03 19:04 UTC
**Game Version:** 1.16.5
**Platform:** Windows 
**Modded:** No (i had carry capacity, deathpoint and waypoint markers, but it shouldn't be related)
**SP/MP:** Singleplayer - creative

### Description
Tries making some coal pile in creative in a 1*4*3 hole (1 wide, 4 long, 3 deep), the pile didn't spread aside, and the game (while in singleplayer) showed at the top right that it lost connexion to the server, i could still play around but not put coal on the floor. I can't load the save anymore (i don't care as it was just a creative world to test stuffs for my survival).

### How to reproduce
I can't...

### Save file
https://drive.google.com/file/d/1zJiHn-EKaBsaIDRnakJJ5m66cNSkuoKG/view?usp=sharing

[Report.zip](https://github.com/anegostudios/VintageStory-Issues/files/8612999/Report.zip)

### Logs

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.16.5 (Stable)
Loaded Mods: game@1.16.5, creative@1.16.5, survival@1.16.5
03/05/2022 20:51:00: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.BlockCoalPile.GetSelectionBoxes(IBlockAccessor blockAccessor, BlockPos pos)
   at Vintagestory.Client.NoObf.ClientMain.GetBlockIntersectionBoxes(BlockPos pos)
   at Vintagestory.API.MathTools.AABBIntersectionTest.RayIntersectsBlockSelectionBox(BlockPos pos, BlockFilter filter)
   at Vintagestory.API.MathTools.AABBIntersectionTest.GetSelectedBlock(Single maxDistance, BlockFilter filter)
   at Vintagestory.Common.GameMain.RayTraceForSelection(IWorldIntersectionSupplier supplier, Ray ray, BlockSelection& blockSelection, EntitySelection& entitySelection, BlockFilter bfilter, EntityFilter efilter)
   at Vintagestory.Common.GameMain.RayTraceForSelection(IPlayer player, BlockSelection& blockSelection, EntitySelection& entitySelection, BlockFilter bfilter, EntityFilter efilter)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.UpdateCurrentSelection()
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.UpdatePicking(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _esGsESICkihAc8ShXuIoQwZFwP4._DPQfPEsBXX5ftH8l1sqqtyB2Itl(Single )
   at _8UC8FAMhwKY89IbtSRDjsNSApPJ._KbwUAfxjCHyIG0aK445AAA9FHl5(Single )
   at _8UC8FAMhwKY89IbtSRDjsNSApPJ._R0wAt2N0TpONMxGD0HJG3bDrRcI(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _7zNxEbLnuy6Bq08TdMSIu9ZbrKf._vvUTh6X5xLRNnjtX2xSE7z8yMeh(_SUsdg1ytavxaRcNNkhfDrODGhGP , String[] )
   at _yA4PJazdKq1OMm8H6js6v5AhQB._vvUTh6X5xLRNnjtX2xSE7z8yMeh(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 04/04/2022 19:19:18, Site = , Source = Windows Error Reporting, Message = Fault bucket 1715359538913174117, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.4.0
P3: 10.0.19044.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Thibault\AppData\Local\Temp\RDRE41A.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE42B.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE43B.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE456.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE476.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 4fab3381-1ac4-4cdc-bbf0-4f727f2dc028
Report Status: 268435456
Hashed bucket: 2de2e32f95852db547ce2e698aff6265
Cab Guid: 0 }
--------------
{ TimeGenerated = 19/03/2022 14:22:46, Site = , Source = Windows Error Reporting, Message = Fault bucket 1985187104426407589, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.4.0
P3: 6219e03d
P4: KERNELBASE.dll
P5: 10.0.19041.1566
P6: 0833f2d4
P7: c000041d
P8: 0000000000034f69
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER35D4.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3A0B.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3A2B.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3A3B.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3A5B.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_89db2dccbc3fc38d1ecd8748ab898f841988f28b_81245bb0_265ea0d6-06c8-414a-bbe1-e343c5067708

Analysis symbol: 
Rechecking for solution: 0
Report Id: f6c23d06-01ad-4715-843f-fb5592f568cb
Report Status: 268435456
Hashed bucket: 5ffa277be091f8790b8ccd274c05b6a5
Cab Guid: 0 }
--------------
{ TimeGenerated = 19/03/2022 14:22:44, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.16.4.0, time stamp: 0x6219e03d
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1566, time stamp: 0x0833f2d4
Exception code: 0xc000041d
Fault offset: 0x0000000000034f69
Faulting process id: 0x9c
Faulting application start time: 0x01d83b941b126ccb
Faulting application path: C:\Users\Thibault\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: f6c23d06-01ad-4715-843f-fb5592f568cb
Faulting package full name: 
Faulting package-relative application ID:  
}

**Comment by copygirl** [comment] 2022-05-03 19:10
Duplicate of #1776. Thank you for providing a world download.

**Closed by copygirl** 2022-05-03 19:10 UTC
Labels: status: duplicate
