### ISSUE TITLE
Biome or lighting bug

### ISSUE THREAD

**Issue by ivanpopelyshev** [anegostudios/VintageStory-Issues#2452] opened 2023-03-08 13:23 UTC
### Game Version

v1.18-pre5

### Platform

None

### Modded

None

### SP/MP

None

### Description

Look at screens

Repeating across chunks.There are greenhouses with different colored glass in a few chunks away.

I dont know whether its biome or lighting bug

### How to reproduce

I dont know yet

### Screenshots

![image](https://user-images.githubusercontent.com/695831/223724143-ccaa8d53-3f3e-4609-8ba3-9475237ac06c.png)

![image](https://user-images.githubusercontent.com/695831/223724161-741f5972-d1e8-464c-bc5f-17abd5312172.png)

### Logs

```Log```

**Comment by ivanpopelyshev** [comment] 2023-03-08 14:57
oh, now i see it. 
![image](https://user-images.githubusercontent.com/695831/223747091-dea63b00-5382-4e4e-a15f-654270434535.png)

**Comment by ivanpopelyshev** [comment] 2023-03-08 15:28
moved away from colored glass. restarted client.

![image](https://user-images.githubusercontent.com/695831/223755338-a1786fac-3bb4-44d0-837c-a5cc82ff91db.png)

Date is 12 December

**Comment by Craluminum2413** [comment] 2023-03-08 15:41
Color map

**Comment by ivanpopelyshev** [comment] 2023-03-08 15:53
Even better: 
![image](https://user-images.githubusercontent.com/695831/223762466-d8cc24fa-8dab-4b61-9c00-ca0d945af88a.png)

**Comment by tyronx** [comment] 2023-03-09 07:59
can you hit CTRL+F3 and make a screenshot of that please

**Comment by ivanpopelyshev** [comment] 2023-03-09 11:22
I'll fly around the world and search for it :) Different date - different colormap

**Comment by ivanpopelyshev** [comment] 2023-03-09 11:35
![image](https://user-images.githubusercontent.com/695831/224011401-661a80e4-622c-4960-8c64-1acbcbf0c16a.png)

Here it is. 6th dec on default month length in singleplayer

**Comment by ivanpopelyshev** [comment] 2023-03-09 11:39
I'm not the only one who saw that bug on the server

Btw, if you are looking for device-specific bugs, here is one: #2401

**Comment by Aurora5252** [comment] 2023-04-16 03:41
I was able to reproduce the problem on a new world created in v1.18.0-rc.6 after a full install.

How to reproduce : 

- Version : v1.18.0-rc.6
- Seed : 1127339594
- polar-equator distance : 50k

1. Create a new game with above parameter
2. Set game calendar to december 9
3. Teleport to 1403 115 509
4. Turn around and check dirt patern

![2023-04-15_23-26-41](https://user-images.githubusercontent.com/130882893/232264945-cd5e91ef-dd83-4cad-b498-a1b227a5ab94.png)

i investigated the problem when my world created with the same seed, but in 1.18.0-pre.7 then slowly upgraded in  v1.18.0-rc.6, shown the same bug at that date, but way worse like below.

![vintage_story_bug_rainbow](https://user-images.githubusercontent.com/130882893/232265176-1eeb0470-3011-4e9e-8847-721fbe5b61de.png)

**Comment by Aurora5252** [comment] 2023-04-16 19:59
After a new test (new world, same seed and 50k equator-distance) the problem occur between dec 6 to dec 9. before and after the texture is ok.

**Comment by noelle-lavenza** [comment] 2023-04-22 07:26
Caused by a change to `colormap.vsh` from 1.17 to 1.18. `rect.x + rect.z * clamp(seasonRel + b/40, 0.01, 0.99),` became `rect.x + rect.z * mod((seasonRel + b/128),1.0)`.
```glsl
        seasonColorMapUv = vec2(
            rect.x + rect.z * mod((seasonRel + b/128),1.0),    // This mod() operation instead of a clamp wraps it around to 0 if the addition of b pushes it above 1.0
            rect.y + rect.w * clamp(noise, 0.5 / (rect.w * atlasHeight), 15.5 / (rect.w * atlasHeight))
        );
```
The jump from the right to the left side of the colormap creates a seam. This applies to anything that uses season-based colors, for example leaves and vines, as seen in #2639. The modulo should probably just be changed back to a clamp, or the colormap should be turned into a seamless texture when tiled horizontally.

**Comment by tyronx** [comment] 2023-04-25 09:04
This shold be fixed in 1.18.1 though, thanks for the report

**Comment by noelle-lavenza** [comment] 2023-05-18 18:38
This is a different issue. This was for grass blocks (topsoil shader). That is for tall grass and berry bushes. They are different.

**Comment by Craluminum2413** [comment] 2023-05-18 18:40
Ok

**Closed by Craluminum2413** 2023-05-18 18:40 UTC
Labels: status: in-progress, department: code
