### ISSUE TITLE
boards stacking crash

### ISSUE THREAD

**Issue by Satras1** [anegostudios/VintageStory-Issues#1049] opened 2021-06-22 15:18 UTC
**Game Version:** 1.15.pre6
**Platform:** Windows 10
**Modded:** No

### Description
Game crashes when trying to stack more than 96 boards (2 full blocks) on one block

**Comment by Craluminum2413** [comment] 2021-06-22 16:17
Duplicate of #945

**Comment by tyronx** [comment] 2021-06-22 17:20
thanks for the report, indeed a duplicate, this will be fixed in pre.7

**Closed by tyronx** 2021-06-22 17:20 UTC
Labels: status: new, type: bug
