### ISSUE TITLE
Filled crock doesn't change look when placed in the world (like it does before 1.16 update)

### ISSUE THREAD

**Issue by Fireztonez** [anegostudios/VintageStory-Issues#1823] opened 2022-03-23 04:47 UTC
**Game Version:** 1.16.4 
**Platform:** Windows
**Modded:** No
**SP/MP:** SP

### Description
On VS 1.16.4 when you shift right-click to place in the world a crock, it always look like if it is empty, so it is impossible without looking block information on the top while looking at the block where it is placed on, to know if it is a filled one or empty one. I imagine this is due to the recent change allowing to placed the crock on the corner or the middle of the block, and placing with other 3 other thing on the same block place.

When you placed the crock on the a shelf, the texture on the crock is still showed correctly.

### Expected behavior
The crock should have the correct texture, like when it is on our inventory or a shelf we can easily see if the crock is filled or empty.

### Screenshots
![Capture d’écran 2022-03-23 004254](https://user-images.githubusercontent.com/19277301/159625633-07990bee-7618-40d2-9ef1-454f5d57586f.jpg)

Like I said, on the shelf the texture is okay (The filled crock should have that same texture when placed on the world)
![Capture d’écran 2022-03-23 004324](https://user-images.githubusercontent.com/19277301/159625731-2c21589d-123b-4ec4-bd3a-cd50893f7958.jpg)

**Comment by 5HT2** [comment] 2022-03-23 11:57
It's just rotated the wrong way. This isn't a bug, rather an oversight.

Tyron has already addressed this in a preview of an upcoming update,

![](https://cdn.discordapp.com/attachments/479736466453561345/951863057682931722/2022-03-11_17-23-12.jpg)

**Comment by copygirl** [comment] 2022-03-23 16:21
In that case the issue is already resolved - just have to wait for the release. Closing.
Thanks for reporting and thanks for the information about the upcoming fix.

**Closed by copygirl** 2022-03-23 16:21 UTC
Labels: status: resolved

**Comment by Fireztonez** [comment] 2022-03-23 17:35
> It's just rotated the wrong way. This isn't a bug, rather an oversight.
> 
> Tyron has already addressed this in a preview of an upcoming update,
> 
> ![](https://camo.githubusercontent.com/c895990211334a6caf572d09c60d96fe4bb990d1db81f6312ae136235a20ba4b/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3437393733363436363435333536313334352f3935313836333035373638323933313732322f323032322d30332d31315f31372d32332d31322e6a7067)

:o I see, thanks for information and I just saw the black face on it too, just not visible on both side depending the way you look at it, it is easy to miss it.
