### ISSUE TITLE
Picking up hot item without tongs causes crash

### ISSUE THREAD

**Issue by Alfouginn** [anegostudios/VintageStory-Issues#4735] opened 2024-12-19 01:06 UTC
### Game Version

1.20.0-rc.3

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Picking up an item, or having an item in my inventory that needs to be carried by tongs has resulted in a crash. Currently unable to log into the server used due to this issue.

### How to reproduce

Playing Tailor Character
Heat any metal item
Pick up without tongs.

### Logs

Running on 64 bit Windows 10.0.22631.0 with 64660 MB RAM
Game Version: v1.20.0-rc.3 (Unstable)
12/18/2024 6:02:19 PM: Critical error occurred
Loaded Mods: hangingoillamps@1.0.2, game@1.20.0-rc.3, creative@1.20.0-rc.3, survival@1.20.0-rc.3, treetapping@1.0.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityPlayerShapeRenderer.RenderHeldItem(Single dt, Boolean isShadowPass, Boolean right) in VSEssentials\EntityRenderer\EntityPlayerShapeRenderer.cs:line 270
   at Vintagestory.GameContent.EntityPlayerShapeRenderer.DoRender3DOpaque(Single dt, Boolean isShadowPass) in VSEssentials\EntityRenderer\EntityPlayerShapeRenderer.cs:line 202
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderOpaque3D(Single deltaTime) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 94
   at Vintagestory.API.Client.DummyRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in VintagestoryApi\Client\API\IClientEventAPI.cs:line 83
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 202
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 815
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 910
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 739
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 170
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 127
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 334
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 12/18/2024 2:15:35 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x1b77b4
Faulting application start time: 0x0x1db512d58483d35
Faulting application path: G:\Vintagestory\Vintagestory.exe
Faulting module path: G:\Vintagestory\Lib\openal32.dll
Report Id: 99e6f719-f630-4d13-af25-12688bce486a
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 12/18/2024 2:15:13 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x1b6cec
Faulting application start time: 0x0x1db512d3ba16f26
Faulting application path: G:\Vintagestory\Vintagestory.exe
Faulting module path: G:\Vintagestory\Lib\openal32.dll
Report Id: 35f504ce-925b-4b45-a6c6-449a72b4c885
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 12/18/2024 2:14:24 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x1b71f4
Faulting application start time: 0x0x1db512d2cdcbe82
Faulting application path: G:\Vintagestory\Vintagestory.exe
Faulting module path: G:\Vintagestory\Lib\openal32.dll
Report Id: e1218200-5338-4854-a8d7-b353e67a4bae
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment] 2024-12-19 10:14
Does it happen in rc.5?

**Comment by Craluminum2413** [comment] 2024-12-19 22:46
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4314

**Comment by radfast** [comment] 2024-12-20 00:53
Looking at this issue, we can fix it in upcoming 1.20.0-rc.6

@Alfouginn meanwhile, I think if you simply **make sure you have nothing in your _left_ hand** while picking up the hot item, you'll be good.

The issue occurs only with certain basic items, such as a **lit torch**, in the left hand, while you pick up a hot item in the right hand - worst case it might occur with anything in the left hand which is not tongs, but I think there's a good chance that actually a lantern or shield will also be okay, will not crash here.

I guess for this specific server, your player happens to already have the torch in left hand and hot item in right hand, so you insta-crash when you log-on, there's not much you can do about that except wait for 1.20.0-rc.6 I'm afraid.  At a guess it will be one or two days more...

**Comment by radfast** [comment] 2024-12-20 01:00
[On review we did not triage this particular issue correctly. It's a crash-loop, any game or server where the player is holding the relevant items will crash the client on joining, and so is basically bricked for that player at the moment. Crash would happen to anyone holding a torch in left hand, hot item in right hand. I think that falls within the definition of a "priority: critical" issue.]

**Closed** 2024-12-20 03:16 UTC
Labels: status: resolved, department: code

**Comment by Alfouginn** [comment] 2024-12-20 05:15
I can report that, for the server, the issue was resolved through the passage of time. Another player on the server to progress the time was enough to result in a successful log in. After the metal had cooled to a touchable level, of course.

Thank you for the timely response!
________________________________

**Comment by radfast** [comment] 2024-12-20 10:09
OK good news.  Do you think you had a lamp from Hanging Oil Lamps mod in your left hand, when the crash happened?

**Comment by radfast** [comment] 2024-12-20 11:32
I'm by now extremely certain this is oil lamp related, see discussion in last 24 hours on [Hanging Oil Lamps mod page](https://mods.vintagestory.at/hangingoillamps)
