### ISSUE TITLE
Crash to chiseling

### ISSUE THREAD

**Issue by Saytromi** [anegostudios/VintageStory-Issues#1660] opened 2022-01-30 19:17 UTC
**Game Version:** 1.16.1  
**Platform:** Windows / Mac / Linux (which?)  Windows 7 x64 
**Modded:** No / Yes (which?)  only client mods
**SP/MP:** Singleplayer / Multiplayer (which?)  single and multi

### Description
Explain the issue you're running into.

I decided to add a semi-block of maple boards to the chisel block of shale. The error is only in my chunk

### How to reproduce
1. Make a '....'
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Expected behavior
If not obvious, what did you expect to happen?
No crashed game

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

![unknown](https://user-images.githubusercontent.com/98710004/151713997-90cc3007-d4a0-41d0-a767-70f2837a1dc5.png)

### Logs
```
Paste crash between the triple backticks.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.
```
[message.txt](https://github.com/anegostudios/VintageStory-Issues/files/7966725/message.txt)

**Comment by copygirl** [comment] 2022-01-30 22:31
```
30.1.2022 20:25:19 [Fatal] System.IndexOutOfRangeException: Индекс находился вне границ массива.
   в Vintagestory.GameContent.BlockEntityMicroBlock.CreateMesh(ICoreClientAPI coreClientAPI, List`1 voxelCuboids, Int32[] materials, BlockPos posForRnd)
   в Vintagestory.GameContent.BlockEntityMicroBlock.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldAccessForResolve)
   в Vintagestory.Client.NoObf.ClientChunk.PreLoadBlockEntitiesFromPacket(_S17b8rDEYnAieG5ofhB19xI7LtA[] blockEntities, Int32 blockEntitiesCount, ClientMain game)
   в Vintagestory.Client.NoObf.ClientWorldMap.LoadChunkFromPacket(_jcDuneu0aSsWcueHWtk9H3GF49d p)
   [...]
```
Closing as duplicate of #1623.
If you can upload your world and link it in the above issue, that would be swell!

**Closed by copygirl** 2022-01-30 22:31 UTC
Labels: status: duplicate
