### ISSUE TITLE
Bear unable to jump out of a small hollow

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#2214] opened 2022-09-24 15:17 UTC
**Game Version:** 1.17.4
**OS:** Mint 
**Modded:** No
**SP/MP:** Singleplayer survival  

### Description
Bears (brown bear and polar bear for sure, don't know for pandas and sun bears) are often unable to jump out of a small hollow, like in the following video.

### Screenshots

https://user-images.githubusercontent.com/84909583/192105680-8b3f0037-cad0-4f0c-873f-5b33acff8bd2.mov

**Comment by Craluminum2413** [comment] 2022-10-02 10:41
Maybe this happens due to snow layers below the bear?

**Comment by tyronx** [comment] 2022-10-02 10:49
thanks for the report, i was able to reproduce it. will be fixed next release

**Closed by tyronx** 2022-10-02 10:49 UTC
Labels: status: new
