### ISSUE TITLE
Mouse Jumps Ingame Using Wayland

### ISSUE THREAD

**Issue by Carltoffel** [anegostudios/VintageStory-Issues#381] opened 2020-02-25 21:57 UTC
**Game Version:** 1.12.4
**Platform:** Arch Linux (Sway)
**Modded:** No

### Description
Clicking and scrolling resets the view to a specific direction.
Moving the mouse resets the scroll position (selected hotbar slot)

### How to reproduce
1. Start a game using Wayland (Sway)
2. Move the mouse and look in any direction
3. Click any button on the mouse including scrolling
4. The view resets to a specific direction

### Expected behavior
The view should not change.

### How to reproduce
1. Start a game using Wayland (Sway)
2. Scroll to select a slot in the hotbar
3. Move the mouse
4. The selected slot resets to a specific slot

### Expected behavior
The selected slot should not change.

Edit: I am aware of the fact that wayland is not being supported yet, this is just my experience trying it.

**Comment by copygirl** [comment] 2020-02-26 06:53
OpenTK, the library we use for windowing (among other things) is not aware of Wayland, so I'm assuming some sort of X11 shim runs inbetween. There might be minor differences in how it translates events that causes this odd behavior in the game. I'm thinking we can't do much about this.

**Comment by Bloodsaw** [comment] 2020-02-28 17:31
I can confirm this issue as described by @Carltoffel on Debian 10 with Gnome (default is Wayland).
Other Distributions that are affected (using Wayland by default if possible):
Fedora 25, Red Had Ent/Cent OS 8, Ubuntu 17.10 and it seems ChromeOS (using tailored debian 9 with wayland).

Maybe you should add this information in your installer.sh as a warning if the user is currently running wayland as display server.

**Comment by Carltoffel** [comment] 2020-02-29 06:55
@Bloodsaw they do inform about this problem [here](https://www.vintagestory.at/sysrequirements/). In my opinion obvious enough.
I really hope there will be a fix for wayland, because on my Navi 10 GPU I have many problems with X11 and wayland performs much better.
@copygirl I don't know that much about opentk, but maybe it would be helpful if you would open an issue on their [github](https://github.com/opentk/opentk/issues)

**Comment by copygirl** [comment] 2020-02-29 07:12
> @copygirl I don't know that much about opentk, but maybe it would be helpful if you would open an issue on their [github](https://github.com/opentk/opentk/issues)

It's unlikely they'd look into it, as the game depends on an older version of OpenTK and they're focusing on their new .NET Standard compatible release. It's more likely that the issue will be fixed just on our end, either through [our OpenTK fork](https://github.com/anegostudios/opentk) or in the game itself.

**Comment by Bloodsaw** [comment] 2020-02-29 10:14
@Carltoffel some Linux user don't even know what wayland or a display server is, and its easy to just print a warning message in the bash script. For example in Gnome the user still has a choice to switch back to X11 on logon screen and there could play the game under x11 while wayland is not supported. 
And in RHEL/centOS it depends on your graphics card + driver combination if wayland is used or not as default.

**Comment by priahoud** [comment] 2020-11-21 19:08
I just bought the game and promptly run into this issue on Fedora 33 running GNOME Shell under Wayland.

Some additional observations:
- The specific direction @Carltoffel mentioned is the direction the player is looking at the start of the game.
- The view resets to this direction not only by pressing any button on the mouse, but also by just scrolling the mouse wheel.
- [This simple test script](https://gist.github.com/priahoud/cfb4112ed9f878b1a61ea6480c26e929) built against the included OpenTK.dll is running just fine and reveals no sign of glitchy behaviour in the library.
- The mouse events are handled correctly by the game. It just behaves as if there is an extra "Reset View/Slot" event fired after.

Hope that helps. Would love to see this one resolved.

**Comment by copygirl** [comment] 2020-11-21 19:48
I do want to note that the engine uses mouse events (`OnMouseMove`, `OnMouseDown`, `OnMouseWheel`, ...) rather than testing the state each update frame. The mouse position also has to be centered so it can be continuously moved.

Depending on the OS and display server, OpenTK receives mouse events differently, especially when it comes to setting the mouse position. I don't remember if this is the exact problem, but if we know that we get a mouse move event immediately after setting the mouse position, we can ignore that one specifically. But Wayland is more asynchronous so it makes that difficult..?

I would debug this myself, but I'm honestly a little worried about messing up my system if I installed Wayland. I also don't personally use Windows or MacOS (which I don't even know if the team can continue supporting) to make sure my changes work across operating systems. Maybe one of these days... :flushed:

Thanks for looking into it, however.

**Comment by jascrain** [comment] 2021-02-20 01:31
I have seen this issue on Wayland also. When I run priahoud's program on Wayland, I see that the mouse coordinates seem to be relative coordinates. When I run it on Xorg, they seem to be absolute coordinates, origin at the center of the screen. I do know that Wayland display servers hide more information from programs, such as the window's exact position on the screen.

I suspect that if you are able to upgrade OpenTK, that may help, as a similar program run with OpenTK v4.5 always displays coordinates with origin at the top left corner.

**Comment by jascrain** [comment] 2021-02-21 00:59
I see several issues in the OpenTK fork. The primary one here is that on Wayland, the DeviceChanged event gets sent more often, and when that happens, OpenTK resets the mouse position. There is also a problem with parsing some XI2 motion events wrong, and possibly a threading issue.

**Comment by jascrain** [comment] 2021-02-21 01:54
I've submitted merge request anegostudios/opentk#2

**Comment by Th3Dilli** [comment] 2024-01-23 20:47
since 1.18.8 and the move to OpentTK 4 we have better wayland support and so far I haven't seen this issue again

so I assume this should be fixed

**Closed by Th3Dilli** 2024-01-23 20:47 UTC
Labels: target: engine, platform: linux, status: new
