### ISSUE TITLE
Artefacts and z-fighting with "reflectiveMode": 1

### ISSUE THREAD

**Issue by tels-git** [anegostudios/VintageStory-Issues#2169] opened 2022-09-05 10:04 UTC
**Game Version:** 1.17.2
**Platform:** Linux
**Modded:** Yes
**SP/MP:** Both

### Description
With NVIDIA cards under Linux, using either `reflective: true` in a block JSON or `reflectiveMode: 1` in a shape file shows z-fighting and half-transparent faces on blocks.

Can be observed on opaque glass blocks in the Bricklayer's mod.

### How to reproduce
1. Use Bricklayers 1.0.1 and Expanded Matter 1.0.0
2. Create an opaque glass block and place it
3. Watch blcok

### Expected behavior
Should show an effect similiar to 1.16.5

### Screenshots
![shader_zfight](https://user-images.githubusercontent.com/29096965/188423916-866a83df-5080-4f7b-9aad-2eeaa60979c7.png)

**Comment by tyronx** [comment] 2022-09-09 07:22
was not able to reproduce this issue on an amd rx 6600 xt

**Comment by tels-git** [comment] 2022-09-18 09:03
So far it was reported by at least two other people, both on NVIDIA cards.

**Comment by DArkHekRoMaNT** [comment] 2022-10-22 22:34
Same problem on:
NVIDIA GTX 1660 Super
NVIDIA Quadro 1000M

**Comment by tyronx** [comment] 2023-01-21 14:53
thanks for the repord, this should be fixed in 1.18

**Closed by tyronx** 2023-01-21 14:53 UTC
Labels: status: new
