### ISSUE TITLE
Random crash on multiplayer

### ISSUE THREAD

**Issue by evadw** [anegostudios/VintageStory-Issues#571] opened 2020-08-23 17:35 UTC
**Game Version:** 1.3.0
**Platform:** Windows
**Modded:** No

### Description
Game crashes periodically, exclusive to dedicated multiplayer.
(note: my server only has 2gb of ram, so I'm not sure if it's just running out)

### How to reproduce
1. play for a while on a new world (possibly generate a lot of chunks, i was about 10000 south of spawn and about 3000 east)
2. eventually you will get this crash, and you will continue to get it until you restart the server, which makes it better, but it comes back sooner every time

### Expected behavior
Obvious

### Screenshots
No screenshots
### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.13.0 (Stable)8/23/2020 1:23:36 PM: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.WeatherSystemClient.ProcessWeatherUpdate(WeatherState msg)
   at Vintagestory.GameContent.WeatherSystemClient.ProcessWeatherUpdates()
   at Vintagestory.GameContent.CloudRenderer.CloudTick(Single deltaTime)
   at Vintagestory.GameContent.CloudRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _1lotrgXN2NetimRAD4ZAefxwrjm._Ew2FBwtlqRJ9Adp9eFRdFA2PyGp(Single )
   at _GOvhuoHvUhV6DSqmhF1QtCbrUki._u475OTafdqfLJg04OqOzYKfDELL(Single )
   at _GOvhuoHvUhV6DSqmhF1QtCbrUki._hdByNlLQKfOWBdLqhR3ruj4UiBf(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _JQ8hJZaWfIKtgNCRVIFwsWJlGbD._PobINQXMJm1DRr8Q98KrBuOyaBI(_oOE8RvwwsA8CcfDxUcot5Tu1mbq , String[] )
   at _E1zChrmPoD6YADl4x90dHsneZYx._PobINQXMJm1DRr8Q98KrBuOyaBI(ThreadStart )
```

**Comment by copygirl** [comment] 2020-08-23 18:11
Closing as duplicate of #569.

**Closed by copygirl** 2020-08-23 18:11 UTC
Labels: status: duplicate
