### ISSUE TITLE
Updating to 1.18.10 pauses at 100% and does not complete.

### ISSUE THREAD

**Issue by Sharkeyv1** [anegostudios/VintageStory-Issues#3096] opened 2023-09-13 01:47 UTC
### Game Version

v1.18.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I tried to update to 1.18.10, first it gave me an error in the files and after that when I try to update it will get to 100% and not actually complete. I am worried if I uninstall I'll loose my worlds.

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/144863421/cf10460a-bed6-484d-8da1-5eceb016ef9d)

### Logs

```Log```12.9.2023 19:27:33 [Notification] Client logger started.
12.9.2023 19:27:33 [Notification] Game Version: v1.18.8 (Stable)
12.9.2023 19:27:35 [Notification] OpenAL Initialized. Available Mono/Stereo Sources: 255/1
12.9.2023 19:27:35 [Notification] CPU Cores: 4
12.9.2023 19:27:35 [Notification] Available RAM: 16275 MB
12.9.2023 19:27:35 [Notification] Graphics Card Vendor: Intel
12.9.2023 19:27:35 [Notification] Graphics Card Version: 3.3.0 - Build 26.20.100.8142
12.9.2023 19:27:35 [Notification] Graphics Card Renderer: Intel(R) HD Graphics 520
12.9.2023 19:27:35 [Notification] Graphics Card ShadingLanguageVersion: 3.30 - Build 26.20.100.8142
12.9.2023 19:27:35 [Notification] GL.MaxVertexUniformComponents: 4096
12.9.2023 19:27:35 [Notification] GL.MaxUniformBlockSize: 65536
12.9.2023 19:27:35 [Notification] Cairo Graphics Version: 1.17.3
12.9.2023 19:27:35 [Notification] OpenAL Version: 1.1 ALSOFT 1.23.0
12.9.2023 19:27:35 [Notification] C# Framework: .net 7.0.10
12.9.2023 19:27:35 [Notification] OpenTK Version: 3.3.2 (A set of fast, low-level C# bindings for OpenGL, OpenGL ES and OpenAL.)
12.9.2023 19:27:35 [Notification] Start discovering assets
12.9.2023 19:27:35 [Notification] Found 23 base assets in category lang
12.9.2023 19:27:35 [Notification] Found 0 base assets in category patches
12.9.2023 19:27:35 [Notification] Found 22 base assets in category config
12.9.2023 19:27:35 [Notification] Found 0 base assets in category worldproperties
12.9.2023 19:27:35 [Notification] Found 46 base assets in category sounds
12.9.2023 19:27:35 [Notification] Found 97 base assets in category shapes
12.9.2023 19:27:35 [Notification] Found 72 base assets in category shaders
12.9.2023 19:27:35 [Notification] Found 16 base assets in category shaderincludes
12.9.2023 19:27:35 [Notification] Found 131 base assets in category textures
12.9.2023 19:27:35 [Notification] Found 4 base assets in category music
12.9.2023 19:27:35 [Notification] Found 0 base assets in category dialog
12.9.2023 19:27:35 [Notification] Found 411 base assets in total
12.9.2023 19:27:35 [Notification] Loading sounds
12.9.2023 19:27:35 [Notification] Sounds loaded
12.9.2023 19:27:35 [Notification] (Re-)loaded frame buffers
12.9.2023 19:27:35 [Notification] Loaded Shaderprogramm for render pass .
12.9.2023 19:27:35 [Notification] Begin loading shaders
12.9.2023 19:27:35 [Notification] Load shaders now
12.9.2023 19:27:35 [Notification] Loading shaders...
12.9.2023 19:27:35 [Notification] Loaded Shaderprogramm for render pass standard.
12.9.2023 19:27:36 [Notification] Loaded Shaderprogramm for render pass particlescube.
12.9.2023 19:27:36 [Notification] Loaded Shaderprogramm for render pass particlesquad.
12.9.2023 19:27:36 [Notification] Loaded Shaderprogramm for render pass sky.
12.9.2023 19:27:36 [Notification] Loaded Shaderprogramm for render pass nightsky.
12.9.2023 19:27:36 [Notification] Loaded Shaderprogramm for render pass woittest.
12.9.2023 19:27:36 [Notification] Loaded Shaderprogramm for render pass transparentcompose.
12.9.2023 19:27:36 [Notification] Loaded Shaderprogramm for render pass debugdepthbuffer.
12.9.2023 19:27:36 [Notification] Loaded Shaderprogramm for render pass helditem.
12.9.2023 19:27:36 [Notification] Loaded Shaderprogramm for render pass chunkopaque.
12.9.2023 19:27:36 [Notification] Loaded Shaderprogramm for render pass chunkliquid.
12.9.2023 19:27:36 [Notification] Loaded Shaderprogramm for render pass decals.
12.9.2023 19:27:36 [Notification] Loaded Shaderprogramm for render pass final.
12.9.2023 19:27:37 [Notification] Loaded Shaderprogramm for render pass gui.
12.9.2023 19:27:37 [Notification] Loaded Shaderprogramm for render pass blur.
12.9.2023 19:27:37 [Notification] Loaded Shaderprogramm for render pass chunktransparent.
12.9.2023 19:27:37 [Notification] Loaded Shaderprogramm for render pass findbright.
12.9.2023 19:27:37 [Notification] Loaded Shaderprogramm for render pass chunktopsoil.
12.9.2023 19:27:37 [Notification] Loaded Shaderprogramm for render pass godrays.
12.9.2023 19:27:37 [Notification] Loaded Shaderprogramm for render pass autocamera.
12.9.2023 19:27:37 [Notification] Loaded Shaderprogramm for render pass blockhighlights.
12.9.2023 19:27:37 [Notification] Loaded Shaderprogramm for render pass wireframe.
12.9.2023 19:27:37 [Notification] Loaded Shaderprogramm for render pass entityanimated.
12.9.2023 19:27:37 [Notification] Loaded Shaderprogramm for render pass luma.
12.9.2023 19:27:37 [Notification] Loaded Shaderprogramm for render pass blit.
12.9.2023 19:27:37 [Notification] Loaded Shaderprogramm for render pass particlesquad2d.
12.9.2023 19:27:37 [Notification] Loaded Shaderprogramm for render pass shadowmapentityanimated.
12.9.2023 19:27:37 [Notification] Loaded Shaderprogramm for render pass shadowmapgeneric.
12.9.2023 19:27:37 [Notification] Loaded Shaderprogramm for render pass texture2texture.
12.9.2023 19:27:38 [Notification] Loaded Shaderprogramm for render pass celestialobject.
12.9.2023 19:27:38 [Notification] Loaded Shaderprogramm for render pass guitopsoil.
12.9.2023 19:27:38 [Notification] Loaded Shaderprogramm for render pass colorgrade.
12.9.2023 19:27:38 [Notification] Loaded Shaderprogramm for render pass guigear.
12.9.2023 19:27:38 [Notification] Loaded Shaderprogramm for render pass ssao.
12.9.2023 19:27:38 [Notification] Loaded Shaderprogramm for render pass bilateralblur.
12.9.2023 19:27:38 [Notification] Cached session key is valid, validating with server
12.9.2023 19:27:39 [Notification] Server validation response: Good
12.9.2023 19:27:39 [Notification] Will search the following paths for mods:
12.9.2023 19:27:39 [Notification]     C:\Users\shark\AppData\Roaming\Vintagestory\Mods
12.9.2023 19:27:39 [Notification]     C:\Users\shark\AppData\Roaming\VintagestoryData\Mods
12.9.2023 19:28:40 [Notification] Retrieving releases meta data
12.9.2023 19:31:56 [Error] An error occurred trying to start process 'C:\Users\shark\AppData\Local\Temp\vs_update_win-x64_1.18.10.exe' with working directory 'C:\Users\shark\AppData\Roaming\Vintagestory'. The process cannot access the file because it is being used by another process.
12.9.2023 19:31:56 [Error]    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Vintagestory.Client.GuiScreenGetUpdate.<>c__DisplayClass9_0.<<downloadInstaller>b__0>d.MoveNext() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\MainMenu\Screens\GuiScreenGetUpdate.cs:line 126
12.9.2023 19:33:11 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
12.9.2023 19:33:15 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
12.9.2023 19:34:23 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
12.9.2023 19:34:29 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers

**Comment by Th3Dilli** [comment] 2023-09-13 15:34
Duplicate of #3078

**Comment by Sharkeyv1** [comment] 2023-09-13 17:05
Thank you for linking a similar thread.

**Comment by Th3Dilli** [comment] 2023-09-21 09:14
Closing this now as well hopefully we do not get any more new reports on this since it s fixed since version 1.18.11 and we now are already at .13

**Closed by Th3Dilli** 2023-09-21 09:14 UTC
Labels: status: duplicate
