### ISSUE TITLE
Crash while loading worlds

### ISSUE THREAD

**Issue by anluin** [anegostudios/VintageStory-Issues#3051] opened 2023-08-27 09:28 UTC
### Game Version

v1.18.8

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

After updating to v1.18.8 the game crashes regularly when loading a world (world created in v1.18.8).
About 1 out of 10 tries the game doesn't crash and manages to load the world.
When creating a completely new world, the error does not occur as often.

The same exception occurs in two places:
```Crash Reports```
```
Running on 64 bit Linux with 15398 MB RAM
Game Version: v1.18.8 (Stable)
8/27/2023 11:04:31 AM: Critical error occurred
Loaded Mods: game@1.18.8, creative@1.18.8, survival@1.18.8
System.OverflowException: Arithmetic operation resulted in an overflow.
   at Vintagestory.Common.ArrayConvert.ByteToByte(Byte[] data, Int32 length) in VintagestoryLib\Common\Convert\ArrayConvert.cs:line 73
   at Vintagestory.Common.CompressionZSTD.Decompress(Byte[] fi, Int32 offset, Int32 length) in VintagestoryLib\Common\Convert\Compression.cs:line 684
   at Vintagestory.Common.Compression.DecompressCombined(Byte[] blocksCompressed, Int32[][]& blocks, Int32& refCount, Func`1 newArray) in VintagestoryLib\Common\Convert\Compression.cs:line 207
   at Vintagestory.Common.ChunkDataLayer.Decompress(Byte[] layerCompressed) in VintagestoryLib\Common\Model\ChunkDataLayer.cs:line 761
   at Vintagestory.Common.ChunkData.DecompressFrom(Byte[] blocksCompressed, Byte[] lightCompressed, Byte[] lightPaletteCompressed, Byte[] fluidsCompressed, Int32 chunkdataVersion) in VintagestoryLib\Common\Model\ChunkData.cs:line 333
   at Vintagestory.Common.WorldChunk.unpackNoLock() in VintagestoryLib\Common\Datastructures\WorldChunk.cs:line 285
   at Vintagestory.Common.WorldChunk.UnpackAndReadBlock(Int32 index, Int32 layer) in VintagestoryLib\Common\Datastructures\WorldChunk.cs:line 223
   at Vintagestory.GameContent.ChunkMapLayer.GenerateChunkImage(Vec2i chunkPos, IMapChunk mc, Int32[]& tintedImage, Boolean withSnow) in VSEssentials\Systems\WorldMap\ChunkLayer\ChunkMapLayer.cs:line 426
   at Vintagestory.GameContent.ChunkMapLayer.OnOffThreadTick(Single dt) in VSEssentials\Systems\WorldMap\ChunkLayer\ChunkMapLayer.cs:line 265
   at Vintagestory.GameContent.WorldMapManager.<OnLoaded>b__23_0() in VSEssentials\Systems\WorldMap\WorldMapManager.cs:line 220
```

```
Running on 64 bit Linux with 15398 MB RAM
Game Version: v1.18.8 (Stable)
8/27/2023 11:07:09 AM: Critical error occurred
Loaded Mods: game@1.18.8, creative@1.18.8, survival@1.18.8
System.OverflowException: Arithmetic operation resulted in an overflow.
   at Vintagestory.Common.ArrayConvert.ByteToByte(Byte[] data, Int32 length) in VintagestoryLib\Common\Convert\ArrayConvert.cs:line 73
   at Vintagestory.Common.CompressionZSTD.Decompress(Byte[] fi) in VintagestoryLib\Common\Convert\Compression.cs:line 678
   at Vintagestory.Common.Compression.Decompress(Byte[] data) in VintagestoryLib\Common\Convert\Compression.cs:line 113
   at Vintagestory.Common.BlockTypeNet.UnpackBlockPositions(Byte[] setBlocks) in VintagestoryLib\Common\Network\BlockTypeNet.cs:line 899
   at Vintagestory.Client.NoObf.SystemHighlightBlocks.HandlePacket(Packet_Server packet) in VintagestoryLib\Client\Systems\Render\HighlightBlocks.cs:line 300
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 452
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 446
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 746
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 712
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 75
   at OpenTK.Windowing.Desktop.GameWindow.DispatchRenderFrame()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 312
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

For some reason, the `Vintagestory.Common.ArrayConvert.ByteToByte` function is called with a negative length.
At least that's what I saw while debugging my mod.

### How to reproduce

Just try loading a world 😅

### Logs

```Log```
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/12447652/client-crash.txt)

**Comment by radfast** [comment] 2023-08-27 18:56
Are you running Ubuntu 22.04?   This is a known issue with that particular distro.   Our next release 1.18.9-rc.1 - likely coming within next 24 hours - should fix it

**Comment by radfast** [comment] 2023-08-27 19:01
I believe this is a duplicate of #2999 and #3009
If you are not running that Ubuntu version, please re-open

**Closed by radfast** 2023-08-27 19:01 UTC
Labels: status: duplicate, platform: linux, status: new, 3rd party issue
