### ISSUE TITLE
Crash on join server 0.17.0 pre5

### ISSUE THREAD

**Issue by schramj1** [anegostudios/VintageStory-Issues#2046] opened 2022-07-24 14:57 UTC
```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.0-pre.5 (Unstable)
Loaded Mods: game@1.17.0-pre.5, creative@1.17.0-pre.5, survival@1.17.0-pre.5
7/24/2022 10:50:33 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.ClientMain.ProcessServerReady() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:line 1918
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:line 1138
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 381
   at Vintagestory.Client.ScreenManager.Render(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:line 704
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:line 608
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 125
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 87
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 7/2/2022 3:16:46 PM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.17.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 5c64

Start Time: 01d88e47fb802d33

Termination Time: 5

Application Path: C:\Users\Jonathan\AppData\Roaming\Vintagestory\Vintagestory.exe

Report Id: 69de532c-5761-4094-ad4e-9f73774a3b08

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
--------------
{ TimeGenerated = 7/2/2022 3:16:44 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2029065431881072118, type 5
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.0.0
P3: 62bd3153
P4: 86d0
P5: 134217728
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3334.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3354.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3353.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3373.tmp.txt
\\?\C:\Users\Jonathan\AppData\Local\Temp\WER3A79.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_Vintagestory.exe_3250d621be7f82ce90d08efff8d2cd3763a1e4_e78f9500_b1a8bdee-1b1e-4e50-a7d6-80d0003ff6fc

Analysis symbol: 
Rechecking for solution: 0
Report Id: 69de532c-5761-4094-ad4e-9f73774a3b08
Report Status: 268435456
Hashed bucket: 8ae3f995abc31e092c28b042854bbdf6
Cab Guid: 0 }
--------------
{ TimeGenerated = 6/26/2022 7:04:55 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1169322480264892805, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.5.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Jonathan\AppData\Local\Temp\RDR4F7.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER508.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER509.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER511.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER531.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 2c8e6bb5-e0a2-4e46-a88e-da80eda5166a
Report Status: 268435456
Hashed bucket: 66b2146b18168122903a4499b8115185
Cab Guid: 0 }
```

**Comment by radfast** [comment] 2022-07-26 17:01
Thank you for reporting.

We believe the cause of this is likely to be a 1.17.0-pre.5 client connecting to a 1.17.0-pre.4 (or earlier) server.  Do you happen to know the server version / can you get the server log?

**In any case, both server and client should now update to 1.17.0-rc1 which is just out.**    Just in case the issue recurs in rc1 - we hope it will not recur - we have added logging for this issue **which will refer players to this issue report**.  Other players are welcome to post up here any errors they see which reference this issue #2046 - this will help us to identify the precise cause of the problem.

**Comment by doornydew** [comment] 2022-07-26 20:51
i have this exact same issue, but with the current rc2 build (me and my friend have been having this ever since pre5 HOWEVER)
its trying to call to a place that simply, does NOT exist, the user doesnt exist, and even on your own user, the files requested dont exist

**Comment by doornydew** [comment] 2022-07-26 21:09
just to be clear, pre 4 works JUST FINE, its has started happening ever since pre5 and beyond.

**Comment by Craluminum2413** [comment] 2022-07-26 21:10
Try 1.17.0-rc.2

**Comment by doornydew** [comment] 2022-07-26 21:12
already did, neither of us hosting and joining does ANYTHING, same exact error, no change at all.

**Comment by radfast** [comment] 2022-07-26 23:00
Thank you for reporting.  For clarity, the purpose of this issues reporting system is for you to give us details of the problem, so that we can work efficiently on fixing it.

The useful information here is that the line number has changed to 1923:

    26/07/2022 22:35:02: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
     at Vintagestory.Client.NoObf.ClientMain.ProcessServerReady() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:line 1923

It was 1918.  That is helpful to know.

There is nothing players can do except wait for us to figure this out and fix it.  Meanwhile Single Player games should be working fine in .rc2, but seems like multiplayer has issues for some people in any version later than `-pre.4`

**Comment by doornydew** [comment] 2022-07-27 00:13
i went ahead and tried to crash a couple more times, just to see if it would change, but mine def sticks on 1923

**Comment by tyronx** [comment] 2022-07-27 05:51
hey, can radfast and/or me try to join your server? Maybe that will help us reproduce it. You can write us the server host here or in direct messages over on discord.

**Comment by doornydew** [comment] 2022-07-27 08:27
me and my friend use hamachi, as neither of us can currently set up ports, i'll ask him when he gets on how and what

**Comment by tyronx** [comment] 2022-07-27 08:40
thanks

**Comment by radfast** [comment] 2022-07-27 10:11
To help us troubleshoot this issue, we would be really grateful for further help from anyone who has experienced the crash.

What we need precisely is this (all in version -rc.2 please):
(1)  Start a multiplayer server
(2)  Try to connect to that server using your player client
(3)  Hopefully it crashes at step (2), because we want to see exactly what is going on with this crash
(4)  Immediately after the crash, stop the server (`/stop` command)
(5)  Now upload or paste in full these logs:   `server-main`, `server-debug`, `client-main`, `client-debug`.    Take the server logs from the server, and the client logs from the client who crashed.  (Looking inside these log files, all four of them should cover the same time period when the crash happened - we need to see logs from both server and client covering this time.   All these logs put together will have enough information to tell us the sequence when the client tried to connect, and crashed.)

**Comment by radfast** [comment] 2022-07-27 10:38
hmm maybe we are being a bit slow here:  is everybody with this problem trying to connect via LAN?

**Comment by Saricane** [comment] 2022-07-29 15:59
I may add that I experience the same crash with rc2 in Open to Internet mode (not Open to Lan). Before that, everything was fine with v1.16.

**Comment by doornydew** [comment] 2022-07-29 17:56
Saricane, try pre.4, ever since pre.5 everything broke, if pre.4 does work for you, but pre.5 doesnt atleast we have a very good estemate where it buggered off

**Comment by Saricane** [comment] 2022-07-29 19:38
Yes @doornydew , I forgot to mention that everything was ok with 1.17-pre1,2,3,4. Problems came with pre5 and further.

**Comment by Gervasn** [comment] 2022-07-30 14:32
> Saricane, try pre.4, ever since pre.5 everything broke, if pre.4 does work for you, but pre.5 doesnt atleast we have a very good estemate where it buggered off

Hello,

same issue here, Open to Lan worked up to pre4 since Pre5 and RC2 "Open to LAN" crashes the client instantly!

**Comment by tyronx** [comment] 2022-08-09 17:52
still looking for an possibility to join one such server where connecting to it crashes - difficult to fix otherwise

**Comment by doornydew** [comment] 2022-08-09 18:17
me and my friend can probably get hamachi going,  but that would mean getting hamachi on your end too

**Comment by tyronx** [comment] 2022-08-09 18:19
yea, I got it installed already. If you could DM me id/pass for the hamachi network on discord I could join

**Comment by tyronx** [comment] 2022-08-09 19:57
ok, i got this fixed now with everyones help. Do test if it works for you now in rc5

**Comment by ApacheTech** [comment] 2022-09-18 01:05
Bump!

Still present in 1.17.3.

### Steps to reproduce:

1. Launch game.
2. Load existing single player world.
3. Once in-game, exit to main menu.
4. Without closing the game, load the same existing single player world.
5. Crash...

```
Running on 64 bit Windows with 128 GB RAM 
Game Version: v1.17.3 (Stable)
17/09/2022 23:33:55: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.ClientMain.ProcessServerReady() in VintagestoryLib\Client\ClientMain.cs:line 1921
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 1138
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 381
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 709
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 613
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 125
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

### Cause

I've recompiled `VintagestoryLib.dll`, with a change to `Vintagestory.Client.NoObf.SystemModHandler::StartModsFully()`.

```csharp
		internal void StartModsFully()
		{
			if (this.loader == null)
			{
				throw new Exception("SystemModHandler.loader is null, please report at https://github.com/anegostudios/VintageStory-Issues/issues/2046");
			}
			this.loader.RunModPhase(ModRunPhase.Normal);
		}
```

Now, I get the following crash:

```
Running on 64 bit Windows with 128 GB RAM 
Game Version: v1.17.3 (Stable)
18/09/2022 01:01:44: Critical error occurred
Loaded Mods: 
System.Exception: SystemModHandler.loader is null, please report at https://github.com/anegostudios/VintageStory-Issues/issues/2046
   at Vintagestory.Client.NoObf.SystemModHandler.StartModsFully() in main.cs:line 15
   at Vintagestory.Client.NoObf.ClientMain.ProcessServerReady() in VintagestoryLib\Client\ClientMain.cs:line 1923
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 1139
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 383
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 711
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 615
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 132
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by ApacheTech** [comment] 2022-09-18 05:19
## Proposed Fix

I've found the issue.

There's a race condition in `Vintagestory.Server.ServerMain::BuildServerAssetsPacket()`.

If you run the method synchronously, from `Vintagestory.Server.ServerMain::StartBuildServerAssetsPacket()`, the client can log in, every time.

Tested on SinglePlayer, and Local Server.

**Current:**
```csharp
private void StartBuildServerAssetsPacket()
{
    sapThread = new Thread(new ThreadStart(BuildServerAssetsPacket))
    {
        IsBackground = true,
        Name = "buildServerAssetsPacket"
    };
    sapThread.Start();
    Logger.VerboseDebug("Starting to build server assets packet");
}
```

**Fix:**
```csharp
private void StartBuildServerAssetsPacket()
{
    Logger.VerboseDebug("Starting to build server assets packet");
    BuildServerAssetsPacket();
}
```

Further verified, if you run `BuildServerAssetsPacket()` as an async `Task`, which is faster than spooling up a brand new `Thread`, it crashes out with the same error as before, even on the first time entering the world, at launch:

**Force Race Condition:**
```csharp
private void StartBuildServerAssetsPacket()
{
    Logger.VerboseDebug("Starting to build server assets packet");
    Task.Factory.StartNew(BuildServerAssetsPacket);
}
```

Also, `Vintagestory.Server.ServerMain::WaitOnBuildServerAssetsPacket()` isn't called at all, but even if it was called, it doesn't decrement the 250ms ttl. It would never end up aborting the thread and running synchronously.

**Comment by Craluminum2413** [comment] 2024-04-21 14:03
Closing due to inactivity

**Closed by Craluminum2413** 2024-04-21 14:03 UTC
Labels: target: multiplayer, status: in-progress
