### ISSUE TITLE
Game crashes while using anvil

### ISSUE THREAD

**Issue by jrddunbr** [anegostudios/VintageStory-Issues#620] opened 2020-10-24 19:35 UTC
**Game Version:**  v1.14.0-pre.2 
**Platform:** Windows
**Modded:** No

### Description
Game Crash

### How to reproduce
1. Set up automated hammer and steel anvil
2. Press (and hold) shift while looking at anvil
3. Right click an iron bloom onto the anvil

### Expected behavior
Either nothing, or place the bloom on the anvil (not sure about the game mechanic)

### Screenshots
None

### Logs
```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.14.0-pre.2 (Unstable)10/24/2020 3:31:03 PM: Critical error occurred
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Vintagestory.GameContent.BlockEntityAnvil.TryPut(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel)
   at Vintagestory.GameContent.BlockEntityAnvil.OnPlayerInteract(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel)
   at Vintagestory.GameContent.BlockAnvil.OnBlockInteractStart(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Block selectedBlock, BlockSelection blockSelection)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _2FvB4KLLiWD1BAdzVnyXmng2xqP._3C4wCdduIjbHNqGPohMCmuxT9Ff(Single )
   at _43oeJWBPhXqZxn9qAbiYjPuudfF._GhICgtkYa4Nw4FVwCjvekTrTlEi(Single )
   at _43oeJWBPhXqZxn9qAbiYjPuudfF._LaHik4LdIFdkTOzA4Sz2zqzl1QM(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _GXiu1zGKP9VctYZMQPrBn30TcjR._4RfQwlUytmnyKFMTa6unfhWf1xb(_3dOc8RzaGEHqEAoEFoJyT9um8xl , String[] )
   at _b8suU5fXgDUnWrC8BDWI5aagX9k._4RfQwlUytmnyKFMTa6unfhWf1xb(ThreadStart )
-------------------------------
```

**Comment by tyronx** [comment] 2020-10-25 13:29
Thanks for the report, this is a duplicate of #617

**Closed by tyronx** 2020-10-25 13:29 UTC
Labels: status: new, target: survival, type: crash
