### ISSUE TITLE
Game crashing when loading savegame

### ISSUE THREAD

**Issue by the-real-Scout** [anegostudios/VintageStory-Issues#544] opened 2020-07-11 09:42 UTC
**Game Version:** v1.13-pre.2
**Platform:** Windows 10
**Modded:** No 
### Description
Game crashed while ingame (singleplayer world). Unable to log in to this world again. Game will crash every time.

### How to reproduce
1. Not sure. Happened while exploring new chunks.
...
3. It crashes.

### Logs
```
Running on 64 bit Windows with 8 GB RAM 
Version: v1.13.0-pre.2 (Unstable)11.07.2020 11:28:40: Critical error occurred
System.IO.EndOfStreamException: Über das Ende des Datenstroms hinaus kann nicht gelesen werden.
   bei System.IO.__Error.EndOfFile()
   bei System.IO.MemoryStream.InternalReadInt32()
   bei Vintagestory.API.Common.EntityAgent.FromBytes(BinaryReader reader, Boolean forClient)
   bei Vintagestory.API.Common.EntityPlayer.FromBytes(BinaryReader reader, Boolean forClient)
   bei Vintagestory.Client.NoObf.ClientSystemEntities.createOrUpdateEntityFromPacket(_pJ7d8cWj1QhPMLCcV0BH2lDZ97Y entitypacket, ClientMain game, Boolean addToLoadQueue)
   bei Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntityLoadedPacket(_quwse21aSx8RK1ovmg94TvajUxM serverpacket)
   bei Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   bei _t8vZnPVpfweoHbId8xxe0ravjxX._1tcYuJqCpbaxyny2eD5lS5MGrQh(Single )
   bei _tzxTlR98foubswzEj4rovaFz9qG._QpWgUmjbxvXBbEe1TBeAzmBaX7i(Single )
   bei _tzxTlR98foubswzEj4rovaFz9qG._VhIAYcXUSRp10D1DXmcCYTRLW7H(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _oxj1ufzM2R8kaxZ4xbiYydqfAti._2if8JtNUYpxP4XqkSSeBVBwEvQT(_NiFDdOd6K1ToGQMpbMTAslU0qwp , String[] )
   bei _a3iHOOw6TGQJhQh3q7ShRbZDB1D._2if8JtNUYpxP4XqkSSeBVBwEvQT(ThreadStart )
-------------------------------

```

**Comment by copygirl** [comment] 2020-07-11 10:36
Closing as duplicate of #390 for now, even though it's not ideal yet. You should be able to fix the issue by clicking on the pencil icon next to the world and opening it in repair mode once.

**Closed by copygirl** 2020-07-11 10:36 UTC
Labels: status: duplicate
