### ISSUE TITLE
Crash when interacting with modded animal loot

### ISSUE THREAD

**Issue by TenthArchitect** [anegostudios/VintageStory-Issues#2306] opened 2022-12-08 02:33 UTC
### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

I attempted to add a fifth loot item to an animal (my modded moose) to see what would happen. Discovered that only the first four appeared and I removed the 1st, 2nd and 4th item from the inventory and closed that menu. I tried to reopen it again to see if the 5th loot item would appear and the game crashed without an error log.

### How to reproduce

Make a modded animal with 5 drops, interact with menu, close it, and open it again.

### Logs

[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/10181623/client-main.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/10181625/server-main.txt)
[client-audit.txt](https://github.com/anegostudios/VintageStory-Issues/files/10181630/client-audit.txt)
[server-audit.txt](https://github.com/anegostudios/VintageStory-Issues/files/10181631/server-audit.txt)
[server-event.txt](https://github.com/anegostudios/VintageStory-Issues/files/10181632/server-event.txt)
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/10181633/client-debug.txt)

**Comment by Craluminum2413** [comment] 2022-12-08 10:58
I can't reproduce it, I changed quantitySlots in behavior properties.
![image](https://user-images.githubusercontent.com/69315569/206429856-5fb80b24-1de3-439f-8e4b-7f33f24b087d.png)

![image](https://user-images.githubusercontent.com/69315569/206429572-bc14bd5f-bb31-410c-948c-a08f98270923.png)

**Comment by Craluminum2413** [comment] 2022-12-08 11:06
I forgot to ask, do you know there are two harvestable behaviors in both server and client behaviors?

**Comment by Craluminum2413** [comment] 2022-12-08 11:10
So I changed quantitySlots for both client and server and can no longer reproduce that issue
![image](https://user-images.githubusercontent.com/69315569/206432118-c8012280-a998-42b8-860d-a16915d5f35d.png)

**Comment by Craluminum2413** [comment] 2023-01-17 08:05
I think it is better to close it since I showed how to make it work

**Closed by Craluminum2413** 2023-01-17 08:05 UTC
Labels: status: incomplete
