### ISSUE TITLE
The game crashes - System.NullReferenceException - LoadTexture

### ISSUE THREAD

**Issue by Movion** [anegostudios/VintageStory-Issues#429] opened 2020-03-05 17:58 UTC
**Game Version:** 1.12.5 (Stable)
**Platform:** Windows
**Modded:** No

### Description
I get a crash report when i open the game. 

### How to reproduce
1. Open the link to the exe (or even the exe it selfs, also in admin mode)
2. The Loading of the game starts
3. "Loading mod meta infos" 
3. Than it crashes / do the crash report thing.

### Expected behavior
The game should start

### Logs
```
Paste crash here.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.

Note that the crash log contains all crashes that have happened so far.
You likely only want to report the latest one.
Running on 64 bit Windows with 12 GB RAM 
Version: v1.12.5 (Stable)05.03.2020 18:56:28: Critical error occurred
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.LoadTexture(IBitmap bmp, Boolean linearMag, Int32 clampMode, Boolean generateMipmaps)
   bei _mKeEWUbBZsjLS6VlGWgOoYQFk2K._KNs6g2GMtsTu5gnL4MXdRgZVlLh()
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._HdDsdRJDH8nMF88r278C4eqdINGA()
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._gjiBClIE7Yspuz65gCqPGSAnUYeb()
   bei _lt8TgSVuBImgzFgAFlSeVzSFsSy._NbPATb9BXlxRc4ZhH2GgyFCUInp(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _hCuHXesCXlp0LGSdrsPFpw4up5n._mOm8EuKIvHpaJoztxNWRpAoOpbM(_55ISULxdcpPfF8D2JP831aWhOBe , String[] )
   bei _iCfIbY24GyBXP5lAwqsSlD9COxC._mOm8EuKIvHpaJoztxNWRpAoOpbM(ThreadStart )
-------------------------------
```
Debug informations
```
5.3.2020 18:56:25 [Debug] Creating game window with window mode Fullscreen
5.3.2020 18:56:26 [VerboseDebug] Loadsounds, step 1
5.3.2020 18:56:26 [VerboseDebug] Loadsounds, step 2
5.3.2020 18:56:26 [VerboseDebug] Loadsounds, step 3
5.3.2020 18:56:27 [VerboseDebug] [VSCreativeMod.dll] Check for mod systems in mod C:\Users\Shadow\AppData\Roaming\Vintagestory\Mods\VSCreativeMod.dll
5.3.2020 18:56:27 [VerboseDebug] [VSCreativeMod.dll] Loaded assembly C:\Users\Shadow\AppData\Roaming\Vintagestory\Mods\VSCreativeMod.dll
5.3.2020 18:56:28 [VerboseDebug] [VSEssentials.dll] Check for mod systems in mod C:\Users\Shadow\AppData\Roaming\Vintagestory\Mods\VSEssentials.dll
5.3.2020 18:56:28 [VerboseDebug] [VSEssentials.dll] Loaded assembly C:\Users\Shadow\AppData\Roaming\Vintagestory\Mods\VSEssentials.dll
5.3.2020 18:56:28 [VerboseDebug] [VSSurvivalMod.dll] Check for mod systems in mod C:\Users\Shadow\AppData\Roaming\Vintagestory\Mods\VSSurvivalMod.dll
5.3.2020 18:56:28 [VerboseDebug] [VSSurvivalMod.dll] Loaded assembly C:\Users\Shadow\AppData\Roaming\Vintagestory\Mods\VSSurvivalMod.dll
5.3.2020 18:56:28 [VerboseDebug] GuiElementRichtext: before bounds: 9,75/-6  w/h = 225,22,5
5.3.2020 18:56:28 [VerboseDebug] GuiElementRichtext, add comp 0, posY=0, lineHeight=0
5.3.2020 18:56:28 [VerboseDebug] GuiElementRichtext, Comp bounds 0 w/h: 117/17,7171875
5.3.2020 18:56:28 [VerboseDebug] GuiElementRichtext, add comp 1, posY=0, lineHeight=17,7171875
5.3.2020 18:56:28 [VerboseDebug] GuiElementRichtext, Comp bounds 0 w/h: 0/17,7171875
5.3.2020 18:56:28 [VerboseDebug] GuiElementRichtext, add comp 2, posY=18, lineHeight=0
5.3.2020 18:56:28 [VerboseDebug] GuiElementRichtext, Comp bounds 0 w/h: 99/17,7171875
5.3.2020 18:56:28 [VerboseDebug] GuiElementRichtext, add comp 3, posY=18, lineHeight=17,7171875
5.3.2020 18:56:28 [VerboseDebug] GuiElementRichtext, Comp bounds 0 w/h: 2,25/17,7171875
5.3.2020 18:56:28 [VerboseDebug] GuiElementRichtext, add comp 4, posY=18, lineHeight=17,7171875
5.3.2020 18:56:28 [VerboseDebug] GuiElementRichtext, Comp bounds 0 w/h: 41/17,7171875
5.3.2020 18:56:28 [VerboseDebug] GuiElementRichtext: after loop. posY = 18
5.3.2020 18:56:28 [VerboseDebug] GuiElementRichtext: after bounds: 9,75/-6  w/h = 225,22,5
5.3.2020 18:56:28 [VerboseDebug] GuiElementRichtext: posY = 35,7171875
5.3.2020 18:56:28 [VerboseDebug] GuiElementRichtext: framewidth/height: 1280/720
5.3.2020 18:56:28 [VerboseDebug] Left bottom main menu text is at 9,75/677,2828125 w/h 225,36,7171875
```

**Comment by copygirl** [comment] 2020-03-05 19:06
Duplicate of #407. Please update to 1.12.6.

**Closed by copygirl** 2020-03-05 19:06 UTC
Labels: status: duplicate
