### ISSUE TITLE
se cierra el juego al cocinar masa de lino.

### ISSUE THREAD

**Issue by elfranzx** [anegostudios/VintageStory-Issues#2673] opened 2023-04-28 05:09 UTC
### Game Version

v1.18.1

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

cuando cocino un masa de lino, al retirarlo se cierra el juego 
![2023-04-28_01-02-50](https://user-images.githubusercontent.com/132038605/235058537-c0a539e9-00d0-4b40-97dd-1d69e2094e20.png)

### How to reproduce

al retirar la masa no deberia de cerrar el juego.

### Screenshots

![2023-04-28_01-03-41](https://user-images.githubusercontent.com/132038605/235058767-60d17dfb-2d53-4fea-984a-102045b6a0f2.png)
![image](https://user-images.githubusercontent.com/132038605/235058847-945e67e8-3303-416d-9670-650f72c88960.png)

### Logs

```Log```
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/11350066/client-main.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/11350067/server-main.txt)

**Comment by Craluminum2413** [comment] 2023-04-28 08:49
Duplicate of #2073

**Closed by Craluminum2413** 2023-04-28 08:49 UTC
Labels: status: new
