### ISSUE TITLE
1.20pre11 SoyBean stew have not texture in bowl or pot

### ISSUE THREAD

**Issue by DejFidOFF** [anegostudios/VintageStory-Issues#4574] opened 2024-11-29 14:11 UTC
### Game Version

1.20pre11

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

No texture for soybean stew

### Screenshots

![pot_soybean_stew](https://github.com/user-attachments/assets/b65f9ec1-0965-4c22-b8c9-994bc33a3bed)
![soybean_stew](https://github.com/user-attachments/assets/aeb3b25e-c1db-4aec-94a6-21acfb013b39)

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2024-11-29 14:19
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/3699

**Closed by Craluminum2413** 2024-11-29 14:19 UTC
Labels: status: new
