### ISSUE TITLE
Error message on normal exit of game

### ISSUE THREAD

**Issue by Bumber64** [anegostudios/VintageStory-Issues#3106] opened 2023-09-19 09:05 UTC
### Game Version

v1.18.12

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

I get an error message after exiting the game:

> Microsoft Visual C++ Runtime Library
> Runtime Error!
> Program: C:\Users\\`username`\AppData\Roaming\Vintage
> Story\Vintagestory.exe
> This application has requested the Runtime to terminate it in an
> unusual way.
> Please contact the application's support team for more information.

The issue started occurring after moving to .net 7 in v1.18.8.

### How to reproduce

1. Start the game.
2. Exit the game from the main menu.

### Logs

The game logs don't show anything out of the ordinary, with the last line of `client-main.txt` being:
`[Notification] Exiting game now. Server running=False. Exit reason: Main screen quit button was pressed`

Some info from `client-main.txt`:

> 19.9.2023 01:43:49 [Notification] Game Version: v1.18.12 (Stable)
> 19.9.2023 01:43:50 [Notification] OpenAL Initialized. Available Mono/Stereo Sources: 255/1
> 19.9.2023 01:43:50 [Notification] Process path: C:\Users\\`username`\AppData\Roaming\Vintage Story\Vintagestory.exe
> 19.9.2023 01:43:50 [Notification] Operating System: Windows 6.3.9600.0
> 19.9.2023 01:43:50 [Notification] CPU Cores: 8
> 19.9.2023 01:43:50 [Notification] Available RAM: 8109 MB
> 19.9.2023 01:43:50 [Notification] Graphics Card Vendor: NVIDIA Corporation
> 19.9.2023 01:43:50 [Notification] Graphics Card Version: 3.3.0 NVIDIA 425.31
> 19.9.2023 01:43:50 [Notification] Graphics Card Renderer: GeForce GTX 765M/PCIe/SSE2
> 19.9.2023 01:43:50 [Notification] Graphics Card ShadingLanguageVersion: 3.30 NVIDIA via Cg compiler
> 19.9.2023 01:43:50 [Notification] GL.MaxVertexUniformComponents: 4096
> 19.9.2023 01:43:50 [Notification] GL.MaxUniformBlockSize: 65536
> 19.9.2023 01:43:50 [Notification] Cairo Graphics Version: 1.17.3
> 19.9.2023 01:43:50 [Notification] OpenAL Version: 1.1 ALSOFT 1.23.0
> 19.9.2023 01:43:50 [Notification] C# Framework: .net 7.0.10
> 19.9.2023 01:43:50 [Notification] OpenTK Version: 3.3.2 (A set of fast, low-level C# bindings for OpenGL, OpenGL ES and OpenAL.)
> 19.9.2023 01:43:50 [Notification] Zstd Version: 1.5.5

Some info from `dxdiag`:
```
   Operating System: Windows 8.1 64-bit (6.3, Build 9600) (9600.winblue_ltsb_escrow.230105-1521)
           Language: English (Regional Setting: English)
System Manufacturer: ASUSTeK COMPUTER INC.
       System Model: G750JW
               BIOS: G750JW.207
          Processor: Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz (8 CPUs), ~2.4GHz

          Card name: NVIDIA GeForce GTX 765M
       Manufacturer: NVIDIA
          Chip type: GeForce GTX 765M
        Driver Name: nvd3dumx.dll,nvwgf2umx.dll,nvwgf2umx.dll,nvd3dum,nvwgf2um,nvwgf2um
Driver File Version: 25.21.0014.2531 (English)
     Driver Version: 25.21.14.2531
  Driver Attributes: Final Retail
   Driver Date/Size: 4/10/2019 04:53:26, 20689432 bytes

---------------
Diagnostics
---------------

Windows Error Reporting:
+++ WER0 +++:
Fault bucket 1449562791174489474, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.12.0
P3: 64b07659
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

+++ WER1 +++:
Fault bucket 1449562791174489474, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.12.0
P3: 64b07659
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

+++ WER2 +++:
Fault bucket 1727346527623634267, type 5
Event Name: WindowsWcpOtherFailure3
Response: Not available
Cab Id: 0

Problem signature:
P1: 6.3.9600
P2: sil\merged\ntu\ntsystem.cpp
P3: Windows::Rtl::SystemImplementation::DirectFileSystemProvider::SysCreateFile
P4: 2155
P5: c0190005
P6: 0x5ecc01b4
P7: 
P8: 
P9: 
P10: 

+++ WER3 +++:
Fault bucket 1207337929937765943, type 5
Event Name: WindowsWcpOtherFailure3
Response: Not available
Cab Id: 0

Problem signature:
P1: 6.3.9600
P2: sil\merged\ntu\ntsystem.cpp
P3: Windows::Rtl::SystemImplementation::DirectFileSystemProvider::SysCreateFile
P4: 2155
P5: c0000056
P6: 0x38777e1f
P7: 
P8: 
P9: 
P10: 

+++ WER4 +++:
Fault bucket 1449562791174489474, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.12.0
P3: 64b07659
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

+++ WER5 +++:
Fault bucket 1699485665392837858, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: gldriverquery.exe
P2: 0.0.0.0
P3: 59bc6c77
P4: SDL2.dll
P5: 6.3.9600.20718
P6: 636f3368
P7: c0000135
P8: 0009d322
P9: 
P10: 

+++ WER6 +++:
Fault bucket 1727346527623634267, type 5
Event Name: WindowsWcpOtherFailure3
Response: Not available
Cab Id: 0

Problem signature:
P1: 6.3.9600
P2: sil\merged\ntu\ntsystem.cpp
P3: Windows::Rtl::SystemImplementation::DirectFileSystemProvider::SysCreateFile
P4: 2155
P5: c0190005
P6: 0x5ecc01b4
P7: 
P8: 
P9: 
P10: 

+++ WER7 +++:
Fault bucket 1207337929937765943, type 5
Event Name: WindowsWcpOtherFailure3
Response: Not available
Cab Id: 0

Problem signature:
P1: 6.3.9600
P2: sil\merged\ntu\ntsystem.cpp
P3: Windows::Rtl::SystemImplementation::DirectFileSystemProvider::SysCreateFile
P4: 2155
P5: c0000056
P6: 0x38777e1f
P7: 
P8: 
P9: 
P10: 

+++ WER8 +++:
Fault bucket 2214170192790503688, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.10.0
P3: 64b07659
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

+++ WER9 +++:
Fault bucket 2214170192790503688, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.10.0
P3: 64b07659
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 
```

**Comment by Th3Dilli** [comment] 2023-09-21 08:15
Seems to be the same issues as #2891 but also on Windows 8.1

You can you try reinstalling [Visual C++](https://aka.ms/vs/17/release/vc_redist.x64.exe)

If that works great else we would recommend to use an update version of Windows. If you don't want to do that it should be fine for now besides the error message when closing the application as far as we can tell.

**Comment by Bumber64** [comment] 2023-09-23 19:26
Reinstalling the runtime didn't help. Guess I'll live with it.

**Comment by Th3Dilli** [comment] 2023-12-05 13:43
closing as duplicate of #2891

**Closed by Th3Dilli** 2023-12-05 13:43 UTC
Labels: 3rd party issue
