### ISSUE TITLE
Adding variant groups with JSON patch does not appear to work.

### ISSUE THREAD

**Issue by milochristiansen** [anegostudios/VintageStory-Issues#18] opened 2018-03-21 23:24 UTC
The following patch dose not produce any error, but the `game:bowl-soup` item does not exist either.

```
{ file: "game:blocktypes/clay/bowl", op: "replace", path: "/variantgroups/0/states", value: ["raw", "burned", "honey", "soup"] },
```

**Comment by copygirl** [comment] 2018-03-22 09:02
With the changes I'll be making, it should be possible to do:
```
{ file: "game:blocktypes/clay/bowl", op: "add",
  path: "/variantgroups/0/states/-", value: "soup" }
```

**Comment by copygirl** [comment] 2018-03-22 10:38
Going to close this as duplicate of #2 for now, as my changes should fix any other issues there are with the JSON patching library. I've tested to make sure both our patches work now.

**Closed by copygirl** 2018-03-22 10:38 UTC
Labels: status: new, target: modding, type: bug
