### ISSUE TITLE
'Homo sapiens' monster spawns

### ISSUE THREAD

**Issue by LiamW2006** [anegostudios/VintageStory-Issues#4547] opened 2024-11-21 23:10 UTC
### Game Version

v1.20.0-pre. 13

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

I was playing a new world on the homo sapiens difficulty and I encountered both of the new monsters. 

### How to reproduce

1. Make a world on the 'homo sapiens' difficulty. 2. Wait for night time 3. Let the new monsters spawn 

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2024-11-21 23:16
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4474

**Closed by Craluminum2413** 2024-11-21 23:16 UTC
Labels: status: new
