### ISSUE TITLE
Players on Server crashing when I sleep.

### ISSUE THREAD

**Issue by yupolx** [anegostudios/VintageStory-Issues#1603] opened 2022-01-18 05:45 UTC
**Game Version:** v1.16.1-rc.2
**Platform:** Windows
**Modded:** No
**SP/MP:** Multiplayer

### Description
All players except for the one that is sleeping game's crashes.

### How to reproduce
1. Make someone sleep.
2. Have someone click on a bed
3. Every client crashes EXCEPT the player who is sleeping.

### Expected behavior
The other clients do not crash.

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.
![2022-01-18_00-32-18](https://user-images.githubusercontent.com/93547477/149877572-8a61597a-56ca-4654-9305-313a8877a74f.png)
This was done right after I slept in the bed
### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.16.1-rc.2 (Unstable)
Loaded Mods: game@1.16.1-rc.2, creative@1.16.1-rc.2, survival@1.16.1-rc.2
1/18/2022 12:32:47 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityShapeRenderer.DoRender2D(Single dt)
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderFrame2D(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _DamzNweBDxmMicnVulmwlMVMgM0._sMengaVDGYAisCAjabTHQK1RXqp(Single )
   at _WdmvE2d6J9HzNHSLADtYYbMD8ON._yMRD15GhtGxOhlM5XwrrrhTIRjg(Single )
   at _WdmvE2d6J9HzNHSLADtYYbMD8ON._tUTr5b63b3ZOBglH3L8fLMXFFhE(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _onk6uFpqwcbPW6YzuZhhUdPywZf._VX8KgZtGV3ZCueYlgfrjdPvyuhh(_eyDkp85wcsatK4hyRtVBSqG8y9l , String[] )
   at _RE6vupBBnuxpHTQrO531ET777xk._VX8KgZtGV3ZCueYlgfrjdPvyuhh(ThreadStart )
-------------------------------
P9: 
P10: 

Attached files:
\\?\C:\Users\MAXIMI~1\AppData\Local\Temp\RDRD5D8.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD5E9.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD609.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD627.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD666.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: af4bc13b-958c-4138-a735-c6ba06525e59
Report Status: 268435456
Hashed bucket: 2654803b8137c9295485b96fec36f77d
Cab Guid: 0 }

**Comment by copygirl** [comment] 2022-01-18 07:47
Duplicate of #1603. Thanks for the report though.

**Closed by copygirl** 2022-01-18 07:47 UTC
Labels: status: duplicate

**Comment by Craluminum2413** [comment] 2022-01-18 11:11
You just closed the issue as duplicate of the same issue

**Comment by copygirl** [comment] 2022-01-18 12:22
Ah yes, apologies.
