### ISSUE TITLE
[Fatal] Caught unhandled exception in thread 'Relight'. Shutting down server.

### ISSUE THREAD

**Issue by RogueRaidenTV** [anegostudios/VintageStory-Issues#1833] opened 2022-03-31 09:40 UTC
**Game Version:** 1.16.4 
**Platform:** Windows / Mac / Linux (which?)   Ubuntu Server
**Modded:** No / Yes (which?)  Yes, See attachment
**SP/MP:** Singleplayer / Multiplayer (which?)  Multiplayer

### Description
Server crashes with error. Seemingly during normal play. Has happened twice now.

Time in logs about when it happened: 30.3.2022 20:52:27

[Mods and Error.txt](https://github.com/anegostudios/VintageStory-Issues/files/8388057/Mods.and.Error.txt)
[Logs.zip](https://github.com/anegostudios/VintageStory-Issues/files/8388058/Logs.zip)

**Comment by copygirl** [comment] 2022-03-31 10:21
Going to close this as a duplicate of #1718.
Check my latest message on that issue and provide some information if possible.

**Closed by copygirl** 2022-03-31 10:21 UTC
Labels: status: duplicate
