### ISSUE TITLE
Ga,e Crashing While Trying To Destroy Chiseled Block

### ISSUE THREAD

**Issue by AnthonyMantoani** [anegostudios/VintageStory-Issues#2241] opened 2022-10-12 18:08 UTC
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.7 (Stable)
12/10/2022 15:05:13: Critical error occurred
Loaded Mods: game@1.17.7, creative@1.17.7, survival@1.17.7
System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
   em Vintagestory.GameContent.BlockEntityMicroBlock.genCube(Int32 voxelX, Int32 voxelY, Int32 voxelZ, Int32 width, Int32 height, Int32 length, ICoreClientAPI capi, ITexPositionSource texSource, Single subPixelPaddingx, Single subPixelPaddingy, Block block, UInt32[] originalVoxelCuboids) na C:\Users\tyron\Documents\vintagestory\game\VSSurvivalMod\BlockEntity\BEMicroBlock.cs:linha 1229
   em Vintagestory.GameContent.BlockEntityMicroBlock.CreateDecalMesh(ICoreClientAPI coreClientAPI, List`1 voxelCuboids, ITexPositionSource decalTexSource, UInt32[] originalVoxelCuboids) na C:\Users\tyron\Documents\vintagestory\game\VSSurvivalMod\BlockEntity\BEMicroBlock.cs:linha 1128
   em Vintagestory.GameContent.BlockMicroBlock.GetDecal(IWorldAccessor world, BlockPos pos, ITexPositionSource decalTexSource, MeshData& decalModelData, MeshData& blockModelData) na C:\Users\tyron\Documents\vintagestory\game\VSSurvivalMod\Block\BlockMicroBlock.cs:linha 442
   em Vintagestory.Client.NoObf.SystemRenderDecals.UpdateDecal(BlockDecal decal) na C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Render\RenderDecals.cs:linha 264
   em Vintagestory.Client.NoObf.SystemRenderDecals.AddBlockBreakDecal(BlockPos pos, Int32 stage) na C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Render\RenderDecals.cs:linha 208
   em Vintagestory.Client.NoObf.SystemRenderDecals.OnPlayerBreakingBlock(BlockDamage blockDamage) na C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Render\RenderDecals.cs:linha 170
   em Vintagestory.Client.NoObf.ClientEventManager.TriggerBlockBreaking(BlockDamage blockDamage) na C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\Util\ClientEventManager.cs:linha 401
   em Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.ContinueBreakSurvival(BlockSelection blockSelection, Block block, Single dt) na C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:linha 819
   em Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) na C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:linha 598
   em Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) na C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:linha 86
   em Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) na C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\Util\ClientEventManager.cs:linha 201
   em Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) na C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:linha 1174
   em Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) na C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:linha 1362
   em Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) na C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:linha 202
   em Vintagestory.Client.ScreenManager.Render(Single dt) na C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:linha 718
   em Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) na C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:linha 622
   em Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) na C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\GameWindow.cs:linha 124
   em System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   em OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) na C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:linha 476
   em OpenTK.GameWindow.DispatchRenderFrame() na C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:linha 452
   em OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) na C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:linha 375
   em Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   em Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) na C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:linha 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 11/10/2022 09:31:25, Site = , Source = Application Error, Message = Nome do aplicativo com falha: Vintagestory.exe, versão: 1.17.6.0, carimbo de data/hora: 0x633bf838
Nome do módulo com falha: clr.dll, versão: 4.8.4515.0, carimbo de data/hora: 0x624ce98e
Código de exceção: 0xc0000005
Deslocamento da falha: 0x00000000006833c0
ID do processo com falha: 0x3c50
Hora de início do aplicativo com falha: 0x01d8dd6c01f41349
Caminho do aplicativo com falha: E:\Jogos\Vintage Story\Vintagestory.exe
Caminho do módulo com falha: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
ID do Relatório: 7403fbc7-8889-40ff-b9b2-89776325f466
Nome completo do pacote com falha: 
ID do aplicativo relativo ao pacote com falha:  }
--------------
{ TimeGenerated = 11/10/2022 09:18:44, Site = , Source = Application Error, Message = Nome do aplicativo com falha: Vintagestory.exe, versão: 1.17.6.0, carimbo de data/hora: 0x633bf838
Nome do módulo com falha: KERNELBASE.dll, versão: 10.0.19041.1949, carimbo de data/hora: 0xcb12e58e
Código de exceção: 0xe0434352
Deslocamento da falha: 0x0000000000034fd9
ID do processo com falha: 0x31b4
Hora de início do aplicativo com falha: 0x01d8dd6b5d039ea4
Caminho do aplicativo com falha: E:\Jogos\Vintage Story\Vintagestory.exe
Caminho do módulo com falha: C:\Windows\System32\KERNELBASE.dll
ID do Relatório: af710c82-6d21-4d4f-a95e-1ffc38703fca
Nome completo do pacote com falha: 
ID do aplicativo relativo ao pacote com falha:  }
--------------
{ TimeGenerated = 11/10/2022 09:18:43, Site = , Source = .NET Runtime, Message = Aplicativo: Vintagestory.exe
Versão do Framework: v4.0.30319
Descrição: O processo foi terminado devido a uma exceção sem tratamento.
Informações da Exceção: System.IO.FileLoadException
   em System.Reflection.RuntimeAssembly._nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   em System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(System.Reflection.AssemblyName, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   em System.Reflection.RuntimeAssembly.InternalLoadFrom(System.String, System.Security.Policy.Evidence, Byte[], System.Configuration.Assemblies.AssemblyHashAlgorithm, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   em System.Reflection.Assembly.LoadFrom(System.String)
   em Vintagestory.Client.ClientProgram.AssemblyResolve(System.Object, System.ResolveEventArgs)

Informações da Exceção: System.Exception
   em Vintagestory.ClientNative.CrashReporter.Crash(System.Exception)
   em Vintagestory.Client.ClientProgram.HandleUnhandledException(System.Object, System.UnhandledExceptionEventArgs)

Informações da Exceção: System.IO.FileLoadException
   em Vintagestory.ClientNative.CrashReporter.Crash(System.Exception)
   em Vintagestory.ClientNative.CrashReporter.Start(System.Threading.ThreadStart)
   em Vintagestory.Client.ClientProgram.Main(System.String[])

 }

**Comment by Craluminum2413** [comment] 2022-10-12 18:12
Duplicate of #2240

**Closed by Craluminum2413** 2022-10-12 18:12 UTC
Labels: status: new
