### ISSUE TITLE
Placeables objects leaning incorrectly to blocks

### ISSUE THREAD

**Issue by lollipocket** [anegostudios/VintageStory-Issues#2211] opened 2022-09-23 07:02 UTC
**Game Version:** 1.17.4  
**Platform:** Windows 10 home
**Modded:** Yes, CarryCapacity, ProspectorInfo
**SP/MP:** Singleplayer  

### Description
Placeable objects lean incorrectly to walls. They might also look sunken in the ground block, or floating in the air. This only happens with the objects that can lean on walls (tools, firestarter, etc), those on the ground (bowls etc) are fine.

### How to reproduce
1. Make a tool of any tier, such as an axe, or a spear.
2. Place it leaning on the wall (Ctrl+shift+right click)
3. It does not sit correctly on the wall. I noticed different tools have different behavior. Example: the axe I placed down looked sunken, the spear looked floating mid-air.

### Expected behavior
They should lean correctly instead.

### Screenshots
![2022-09-23_08-55-54](https://user-images.githubusercontent.com/110069579/191907059-a4877b81-3b2e-41e4-86d9-8f56d6d3b422.png)
![2022-09-23_08-56-14](https://user-images.githubusercontent.com/110069579/191907095-08f42934-bcd5-46a5-a0a7-3f3243027344.png)
![2022-09-23_08-56-36](https://user-images.githubusercontent.com/110069579/191907114-e92d1e50-0507-46f8-a22d-e1db9f9d9c46.png)

I'll paste the client.main log from today, if that's any help.
### Logs
```
23.9.2022 08:36:43 [Notification] Client logger started.
23.9.2022 08:36:43 [Notification] Game Version: v1.17.4 (Stable)
23.9.2022 08:36:43 [Notification] Screens:
23.9.2022 08:36:43 [Notification] 0: {X=0,Y=0,Width=1920,Height=1080}, \\.\DISPLAY1 (primary)
23.9.2022 08:36:44 [Notification] OpenAL Initialized. Available Mono/Stereo Sources: 255/1
23.9.2022 08:36:44 [Notification] Graphics Card Vendor: NVIDIA Corporation
23.9.2022 08:36:44 [Notification] Graphics Card Version: 3.3.0 NVIDIA 457.85
23.9.2022 08:36:44 [Notification] Graphics Card Renderer: GeForce GTX 745/PCIe/SSE2
23.9.2022 08:36:44 [Notification] Graphics Card ShadingLanguageVersion: 3.30 NVIDIA via Cg compiler
23.9.2022 08:36:44 [Notification] Cairo Graphics Version: 1.17.3
23.9.2022 08:36:44 [Notification] OpenAL Version: 1.1 ALSOFT 1.16.0
23.9.2022 08:36:44 [Notification] C# Framework: .net Framework 4.0.30319.42000
23.9.2022 08:36:44 [Notification] OpenTK Version: 3.3.2 (A set of fast, low-level C# bindings for OpenGL, OpenGL ES and OpenAL.)
23.9.2022 08:36:44 [Notification] Start discovering assets
23.9.2022 08:36:44 [Notification] Found 18 base assets in category lang
23.9.2022 08:36:44 [Notification] Found 0 base assets in category patches
23.9.2022 08:36:44 [Notification] Found 22 base assets in category config
23.9.2022 08:36:44 [Notification] Found 0 base assets in category worldproperties
23.9.2022 08:36:44 [Notification] Found 46 base assets in category sounds
23.9.2022 08:36:44 [Notification] Found 97 base assets in category shapes
23.9.2022 08:36:44 [Notification] Found 80 base assets in category shaders
23.9.2022 08:36:44 [Notification] Found 16 base assets in category shaderincludes
23.9.2022 08:36:44 [Notification] Found 128 base assets in category textures
23.9.2022 08:36:44 [Notification] Found 4 base assets in category music
23.9.2022 08:36:44 [Notification] Found 0 base assets in category dialog
23.9.2022 08:36:44 [Notification] Found 411 base assets in total
23.9.2022 08:36:44 [Notification] Loading sounds
23.9.2022 08:36:44 [Notification] Sounds loaded
23.9.2022 08:36:44 [Notification] (Re-)loaded frame buffers
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass .
23.9.2022 08:36:44 [Notification] CPU Cores: 4
23.9.2022 08:36:44 [Notification] Window was resized to 1920 1080, rebuilding framebuffers...
23.9.2022 08:36:44 [Notification] (Re-)loaded frame buffers
23.9.2022 08:36:44 [Notification] Begin loading shaders
23.9.2022 08:36:44 [Notification] Load shaders now
23.9.2022 08:36:44 [Notification] Loading shaders...
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass standard.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass particlescube.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass particlesquad.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass sky.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass nightsky.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass woittest.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass transparentcompose.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass debugdepthbuffer.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass helditem.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass chunkopaque.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass chunkliquid.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass decals.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass final.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass gui.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass blur.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass chunktransparent.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass findbright.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass chunktopsoil.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass godrays.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass autocamera.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass blockhighlights.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass wireframe.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass entityanimated.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass luma.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass blit.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass particlesquad2d.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass shadowmapentityanimated.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass shadowmapgeneric.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass texture2texture.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass celestialobject.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass guitopsoil.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass colorgrade.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass guigear.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass ssao.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass bilateralblur.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass grass.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass flowers.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass shadowgrass.
23.9.2022 08:36:44 [Notification] Loaded Shaderprogramm for render pass shadowflowers.
23.9.2022 08:36:44 [Notification] Cached session key is valid, validating with server
23.9.2022 08:36:46 [Notification] Server validation response: Good
23.9.2022 08:36:46 [Notification] Will search the following paths for mods:
23.9.2022 08:36:46 [Notification]     C:\Users\loren\AppData\Roaming\Vintagestory\Mods
23.9.2022 08:36:46 [Notification]     C:\Users\loren\AppData\Roaming\VintagestoryData\Mods
23.9.2022 08:55:20 [Notification] Initialized GUI Manager
23.9.2022 08:55:20 [Notification] Initialized Server Connection
23.9.2022 08:55:20 [Notification] Server args parsed
23.9.2022 08:55:20 [Notification] GuiScreenConnectingToServer constructed
23.9.2022 08:55:20 [Notification] Server main instantiated
23.9.2022 08:55:27 [Notification] Processed server identification
23.9.2022 08:55:27 [Notification] Map initialized
23.9.2022 08:55:27 [Notification] Received server assets
23.9.2022 08:55:27 [Notification] Loading and pre-starting client side mods...
23.9.2022 08:55:27 [Notification] Will search the following paths for mods:
23.9.2022 08:55:27 [Notification]     C:\Users\loren\AppData\Roaming\Vintagestory\Mods
23.9.2022 08:55:27 [Notification]     C:\Users\loren\AppData\Roaming\VintagestoryData\Mods
23.9.2022 08:55:27 [Notification] Found 5 mods (0 disabled)
23.9.2022 08:55:27 [Notification] Mods, sorted by dependency: game, carrycapacity, prospectorinfo, creative, survival
23.9.2022 08:55:27 [Notification] Instantiated 79 mod systems from 5 enabled mods
23.9.2022 08:55:27 [Notification] Done loading and pre-starting client side mods.
23.9.2022 08:55:27 [Notification] External Origins in load order: modorigin@C:\Users\loren\AppData\Roaming\Vintagestory\assets\creative\, modorigin@C:\Users\loren\AppData\Roaming\Vintagestory\assets\survival\, mod@CarryCapacity-VS1.16.0-v0.6.5.zip
23.9.2022 08:55:27 [Notification] Found 1 external assets in category lang
23.9.2022 08:55:27 [Notification] Found 11 external assets in category patches
23.9.2022 08:55:27 [Notification] Found 43 external assets in category config
23.9.2022 08:55:27 [Notification] Found 24 external assets in category worldproperties
23.9.2022 08:55:27 [Notification] Found 326 external assets in category sounds
23.9.2022 08:55:27 [Notification] Found 2692 external assets in category shapes
23.9.2022 08:55:27 [Notification] Found 13 external assets in category shaders
23.9.2022 08:55:27 [Notification] Found 0 external assets in category shaderincludes
23.9.2022 08:55:27 [Notification] Found 4478 external assets in category textures
23.9.2022 08:55:27 [Notification] Found 63 external assets in category music
23.9.2022 08:55:27 [Notification] Found 17 external assets in category dialog
23.9.2022 08:55:27 [Notification] Found 0 external assets in category compatibility
23.9.2022 08:55:27 [Notification] Reloaded lang file now with mod assets
23.9.2022 08:55:28 [Notification] JsonPatch Loader: 34 patches total, successfully applied 11 patches, missing files on 15 patches, unmet conditions on 10 patches, no issues
23.9.2022 08:55:28 [Notification] Received 2408 item types from server
23.9.2022 08:55:28 [Notification] Loaded 8570 block types from server
23.9.2022 08:55:28 [Notification] Reloaded sounds, now with mod assets
23.9.2022 08:55:29 [Notification] Composed 1 4096x4096 entities texture atlases from 184 textures (last textureid = 182)
23.9.2022 08:55:29 [Notification] Collected 1581 shapes to tesselate.
23.9.2022 08:55:30 [Notification] Composed 1 4096x4096 items texture atlases from 1233 textures (last textureid = 183)
23.9.2022 08:55:31 [Notification] Composed 1 4096x4096 blocks texture atlases from 3837 textures (last textureid = 184)
23.9.2022 08:55:31 [Notification] Server launched
23.9.2022 08:55:32 [Notification] Server assets loaded
23.9.2022 08:55:33 [Notification] Loaded Shaderprogramm for render pass anvilworkitem.
23.9.2022 08:55:33 [Notification] Loaded Shaderprogramm for render pass lines.
23.9.2022 08:55:33 [Notification] Loaded Shaderprogramm for render pass aurora.
23.9.2022 08:55:33 [Notification] Blocks tesselated
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass rift.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass machinegear.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass sleepoverlay.
23.9.2022 08:55:34 [Notification] Started 50 systems on Client:
23.9.2022 08:55:34 [Notification]     Mod 'VSEssentials.dll' (game):
23.9.2022 08:55:34 [Notification]         Vintagestory.ServerMods.Core
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.EntityPartitioning
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.ErrorReporter
23.9.2022 08:55:34 [Notification]         Vintagestory.ServerMods.ModCompatiblityUtil
23.9.2022 08:55:34 [Notification]         Vintagestory.ServerMods.NoObf.ModJsonPatchLoader
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.FallingBlockParticlesModSystem
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.CharacterExtraDialogs
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.EntityNameTagRendererRegistry
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.POIRegistry
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.RoomRegistry
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.WeatherSystemCommands
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.WeatherSystemClient
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.WorldMapManager
23.9.2022 08:55:34 [Notification]         Vintagestory.ServerMods.LoadColorMaps
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.ClothManager
23.9.2022 08:55:34 [Notification]     Mod 'VSSurvivalMod.dll' (survival):
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.SaplingControl
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.SurvivalCoreSystem
23.9.2022 08:55:34 [Notification]         Vintagestory.ServerMods.GenFromHeightmap
23.9.2022 08:55:34 [Notification]         Vintagestory.ServerMods.GenMaps
23.9.2022 08:55:34 [Notification]         Vintagestory.ServerMods.DebugSystem
23.9.2022 08:55:34 [Notification]         Vintagestory.ServerMods.UpgradeTasks
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.MyceliumSystem
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.ModSystemAuction
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.ModSystemHandbook
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.LiquidItemStackRenderer
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.CharacterSystem
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.FruitingSystem
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.ModSystemRifts
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.ModSystemRiftWeather
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.ModTemperature
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.SystemTemporalStability
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.MealMeshCache
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.ModSystemWearableStats
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.ModSystemBlockReinforcement
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.ChiselBlockModelCache
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.TemporalStabilityEffects
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.ModJournal
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.ModLootRandomizer
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.ModSleeping
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.TeleporterManager
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.Mechanics.MechanicalPowerMod
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.TradeHandbookInfo
23.9.2022 08:55:34 [Notification]         Vintagestory.ServerMods.GenStructures
23.9.2022 08:55:34 [Notification]         Vintagestory.ServerMods.GenStructuresPosPass
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.RecipeRegistrySystem
23.9.2022 08:55:34 [Notification]         Vintagestory.GameContent.TraderOutfits
23.9.2022 08:55:34 [Notification]     Mod 'VSCreativeMod.dll' (creative):
23.9.2022 08:55:34 [Notification]         Vintagestory.ServerMods.Core
23.9.2022 08:55:34 [Notification]         Vintagestory.ServerMods.WorldEdit.WorldEdit
23.9.2022 08:55:34 [Notification]     Mod 'CarryCapacity-VS1.16.0-v0.6.5.zip' (carrycapacity):
23.9.2022 08:55:34 [Notification]         CarryCapacity.CarrySystem
23.9.2022 08:55:34 [Notification]     Mod 'ProspectorInfo-3.1.2.zip' (prospectorinfo):
23.9.2022 08:55:34 [Notification]         ProspectorInfo.ProspectorInfoModSystem
23.9.2022 08:55:34 [Notification] Loading shaders...
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass standard.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass particlescube.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass particlesquad.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass sky.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass nightsky.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass woittest.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass transparentcompose.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass debugdepthbuffer.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass helditem.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass chunkopaque.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass chunkliquid.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass decals.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass final.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass gui.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass blur.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass chunktransparent.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass findbright.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass chunktopsoil.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass godrays.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass autocamera.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass blockhighlights.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass wireframe.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass entityanimated.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass luma.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass blit.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass particlesquad2d.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass shadowmapentityanimated.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass shadowmapgeneric.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass texture2texture.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass celestialobject.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass guitopsoil.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass colorgrade.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass guigear.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass ssao.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass bilateralblur.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass grass.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass flowers.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass shadowgrass.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass shadowflowers.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass anvilworkitem.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass lines.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass aurora.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass rift.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass machinegear.
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass sleepoverlay.
23.9.2022 08:55:34 [Notification] Reloaded shaders now with mod assets
23.9.2022 08:55:34 [Notification] Received level init
23.9.2022 08:55:34 [Notification] Loaded Shaderprogramm for render pass instanced.
23.9.2022 08:55:34 [Notification] Loading world map cache db...
23.9.2022 08:55:34 [Notification] Initialized Music Engine
23.9.2022 08:55:34 [Notification] Texture size is 32 so decal atlas size of 128x128 should suffice
23.9.2022 08:55:36 [Notification] Received level finalize
23.9.2022 08:55:36 [Notification] Loaded Shaderprogramm for render pass clouds.
23.9.2022 08:55:37 [Notification] Track music/summer-day.ogg now started
23.9.2022 08:55:52 [Notification] Finished fully loading sounds (async)
23.9.2022 08:56:20 [Notification] Wow, client daytime drifted off significantly from server daytime (23,5 mins)
23.9.2022 08:56:38 [Notification] Client pause state is now on
```

**Comment by Craluminum2413** [comment] 2022-09-23 09:52
Duplicate of #2203

**Closed by Craluminum2413** 2022-09-23 09:52 UTC
Labels: status: new
