### ISSUE TITLE
I disconnected while using a bed in a server. The bed in the merchant claim. Now everytime I join my client crashes.

### ISSUE THREAD

**Issue by carlitoss98** [anegostudios/VintageStory-Issues#1826] opened 2022-03-27 10:28 UTC
I disconnected while using a bed in a server. The bed in the merchant claim. Now everytime I join my client crashes. If you need more info just tell me.

```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.16.4 (Stable)
Loaded Mods: cralutweaks@1.0.0, expandedfoods@1.5.3-pre.4, primitivesurvival@2.8.0, tradeomat@1.6.0, game@1.16.4, morepiles@1.2.0, petai@1.3.7, playercorpse@1.3.1, creative@1.16.4, survival@1.16.4, feverstonehorses@1.2.6
27/03/2022 11:25:45: Critical error occurred
System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en Vintagestory.GameContent.BlockEntityBed.DidMount(EntityAgent entityAgent)
   en Vintagestory.API.Datastructures.SyncedTreeAttribute.FromBytes(BinaryReader stream)
   en Vintagestory.API.Common.Entities.Entity.FromBytes(BinaryReader reader, Boolean fromServer)
   en Vintagestory.API.Common.EntityAgent.FromBytes(BinaryReader reader, Boolean forClient)
   en Vintagestory.API.Common.EntityPlayer.FromBytes(BinaryReader reader, Boolean forClient)
   en Vintagestory.Client.NoObf.ClientSystemEntities.createOrUpdateEntityFromPacket(_yBL8zoBecliFkS2tQXGQIuD4v3j entitypacket, ClientMain game, Boolean addToLoadQueue)
   en Vintagestory.Client.NoObf.ClientChunk.LoadEntitiesFromPacket(_yBL8zoBecliFkS2tQXGQIuD4v3j[] entities, Int32 entitiesCount, ClientMain game)
   en Vintagestory.Client.NoObf.ClientWorldMap.loadChunkMT(_rRUf25tOqmvtcmyjeOruY6FKLsb p, ClientChunk chunk)
   en Vintagestory.Client.NoObf.ClientWorldMap.<>c__DisplayClass102_0.<LoadChunkFromPacket>b__0()
   en Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   en _4Bi1AGVssrIO0El8b8ygdS9FIfm._o5h005s1ovnxSPPqKWgI4tZUoCh(Single )
   en _lAuHsYOBOAjBMdATFXwLUtH7N00._JvY4M2412YZu1OS3Ull8wgZBu1j(Single )
   en _lAuHsYOBOAjBMdATFXwLUtH7N00._KmBeEx15nyyLrVqNDW6geSArpNr(Single )
   en Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   en System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   en OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) en C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:línea 476
   en OpenTK.GameWindow.DispatchRenderFrame() en C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:línea 452
   en OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) en C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:línea 375
   en _TRhArnJABwZoV9Vt7Ld2l65Xzgg._mhlr8s7wtMvxaJGpVy2Ag90jUBK(_3HJA5NvAIx31LXjscc3HGjXaR6q , String[] )
   en _q0zAVOrWbMX04rMA9G3HIFVuGjA._mhlr8s7wtMvxaJGpVy2Ag90jUBK(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 11/03/2022 2:21:56, Site = , Source = .NET Runtime, Message = Aplicación: Vintagestory.exe
Versión de Framework: v4.0.30319
Descripción: el proceso terminó debido a una excepción no controlada.
Información de la excepción: código de la excepción c0020001, dirección de la excepción 00007FFFC82B4F69
Pila:
 }
```

**Comment by copygirl** [comment] 2022-03-27 10:30
Duplicate of #1822.

**Closed by copygirl** 2022-03-27 10:30 UTC
Labels: status: duplicate
