### ISSUE TITLE
propickNodeSearchRadius IndexOutOfRangeException crash

### ISSUE THREAD

**Issue by Guybraltar** [anegostudios/VintageStory-Issues#622] opened 2020-10-25 15:49 UTC
**Game Version:** 1.13.4
**Platform:** Windows 
**Modded:** No 

### Description
When I tried to enable the Prospector pick Node Search function I accidentally input into the in-game console the command
/worldConfig propickNodeSearchRadius [8]  
This is causing the game to crash whenever I load into the world now.  I cannot find where this setting is held in the files so that I can remove the brackets.  I know the brackets are the issue, because I changed the setting with this commend several times before without putting in the brackets and it was fine and worked.  When I hover over the game file, to load, it shows the value for 
ProPick Node Search Radius: [8].  
I don't know what possessed me to type in the brackets, I just used the number on previous occasions.
### How to reproduce
1. In-game console, /worldConfig propickNodeSearchRadius [8]  ** make sure the brackets are there **
2. Save & Quit and reload the game save.  If you hover over it, you'll see the setting ProPick Node Search Radius: [8]
3. It crashes to desktop when the game should finish loading.

### Expected behavior
Normally this command just changes the NodeSearchRadius to whatever number you set it at.

### Screenshots
![20201025_114445](https://user-images.githubusercontent.com/35981903/97111962-1827ff00-16b8-11eb-9c67-dc727086e9e0.jpg)

### Logs
```
Running on 64 bit Windows with 24 GB RAM 
Version: v1.13.4 (Stable)10/25/2020 11:31:57 AM: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.Client.NoObf.HudHotbar.UpdateCurrentToolMode(Int32 newSlotIndex)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _VtIDI6oYFpyEcQSZBFso9UVxS9aA._ZnYzeuHqveMMiEvOnpahncAMjfg(Single )
   at _LSAAgZhw31Rqs2is6nnojfZBbQC._4BykKOCicJqCBHpyWIgTmxWrTrg(Single )
   at _LSAAgZhw31Rqs2is6nnojfZBbQC._6XmOxKoTYrFLRCGd58p58XW43nD(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _lYLQLGyldvbDG9rPQyiRVeIqQVp._EEzpApWBQHtHR4iMJabXK2wDvlA(_ex0VSgRAdtsvhANmJHZHaf9ATWt , String[] )
   at _IcGByoJhapvESnm6vaOawAHbkeU._EEzpApWBQHtHR4iMJabXK2wDvlA(ThreadStart )
-------------------------------
```

**Comment by copygirl** [comment] 2020-10-25 16:51
Possible duplicate of #612. Can you try in the latest pre-release version?

**Comment by Craluminum2413** [comment] 2021-06-02 12:38
You forgot to close the error. This has been fixed

**Closed** 2021-06-02 12:45 UTC
Labels: status: incomplete, type: crash
