### ISSUE TITLE
Interacting With an Aged Armor Stand Crashes Game

### ISSUE THREAD

**Issue by ifozz** [anegostudios/VintageStory-Issues#4183] opened 2024-09-29 03:57 UTC
### Game Version

v1.20.0 pre-4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Picking up an armour stand will crash the game.

### How to reproduce

1. Pick up an armour stand.

### Logs
```
Running on 64 bit Windows 10.0.19045.0 with 16147 MB RAM
Game Version: v1.20.0-pre.4 (Unstable)
29/09/2024 1:56:08 PM: Critical error occurred
Loaded Mods: game@1.20.0-pre.4, creative@1.20.0-pre.4, survival@1.20.0-pre.4
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityArmorStand.OnInteract(EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode) in VSSurvivalMod\Entities\EntityArmorStand.cs:line 59
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsNoBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 394
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 819
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1023
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 694
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 669
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by Craluminum2413** [comment] 2024-09-29 08:59
Can't reproduce

**Comment by ifozz** [comment] 2024-09-30 09:02
> Can't reproduce

After further testing, this bug only applies to aged armour stands.

**Comment by Saricane** [comment] 2024-10-06 09:55
Confirmed.

**Comment by maltiez2** [comment] 2024-11-06 11:07
Should be fixed in next update

**Closed by maltiez2** 2024-11-06 11:07 UTC
Labels: status: confirmed, priority: high, department: code, version: 1.20
