### ISSUE TITLE
Game crashes on attempt to join local-hosted server

### ISSUE THREAD

**Issue by FrozenGem** [anegostudios/VintageStory-Issues#3149] opened 2023-10-12 17:37 UTC
### Game Version

1.18.8, 1.18.15

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Game consistently crashes when it tries to open up client on attempt to join
Same issues happen on both versions

### Logs

[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/12885515/server-main.txt)
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/12885516/client-crash.txt)

> Running on 64 bit Windows with 8101 MB RAM
> Game Version: v1.18.8 (Stable)
> 12.10.2023 20:27:52: Critical error occurred
> Loaded Mods: game@1.18.8, creative@1.18.8, survival@1.18.8
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleDisconnectPlayer(Packet_Server packet)
>    at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
>    at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt)
>    at Vintagestory.Client.ScreenManager.Render(Single dt)
>    at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt)
>    at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e)
>    at OpenTK.Windowing.Desktop.GameWindow.DispatchRenderFrame()
>    at OpenTK.Windowing.Desktop.GameWindow.Run()
>    at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
>    at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1()
>    at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)

**Comment by nmlt** [comment] 2023-11-27 20:13
This might be because you're using the same account on both computers? That was at least my problem.

**Comment by Craluminum2413** [comment] 2024-02-15 08:40
Duplicate of #2847

**Closed by Craluminum2413** 2024-02-15 08:40 UTC
Labels: status: new
