### ISSUE TITLE
Animals do not drop items

### ISSUE THREAD

**Issue by TheX77e4** [anegostudios/VintageStory-Issues#3297] opened 2023-12-10 19:04 UTC
### Game Version

v1.19 pre9

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Not getting items from animals.
Created new world. Reinstalled game. 

### How to reproduce

1. Create world.
2. Hunt Animals
3. Scratch head in confusement.

### Screenshots

![2023-12-10_20-59-30](https://github.com/anegostudios/VintageStory-Issues/assets/153455931/b6c39030-730f-4b70-ba24-9f10b317547b)

### Logs

```Log```
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/13628911/client-main.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/13628912/server-main.txt)

**Comment by Craluminum2413** [comment] 2023-12-10 20:15
Duplicate of #3289

**Closed by Craluminum2413** 2023-12-10 20:15 UTC
Labels: status: duplicate

**Comment by JoaoGamer17** [comment] 2023-12-11 00:01
I have this same issue

**Comment by RedramVS** [comment] 2023-12-14 15:57
This will be fixedin pre10
