### ISSUE TITLE
Crash on Creating Single Player world

### ISSUE THREAD

**Issue by Aethandus** [anegostudios/VintageStory-Issues#4533] opened 2024-11-19 01:48 UTC
### Game Version

v19.8.0

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Trying to load a single player world, idk if i have mods installed they dont show up on my mods manager since i came off a modded multiplayer server

### Screenshots

Running on 64 bit Windows 10.0.19045.0 with 8054 MB RAM
Game Version: v1.19.8 (Stable)
11/18/2024 8:43:55 PM: Critical error occurred
Loaded Mods: 
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'The ThreadLocal object has been disposed.'.
   at System.Threading.ThreadLocal`1.GetValueSlow()
   at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionStatesNative(IWorldAccessor world, ItemSlot inslot) in VintagestoryApi\Common\Collectible\Collectible.cs:line 2507
   at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionStates(IWorldAccessor world, ItemSlot inslot) in VintagestoryApi\Common\Collectible\Collectible.cs:line 2455
   at Vintagestory.API.Common.CollectibleObject.AppendPerishableInfoText(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1814
   at Vintagestory.API.Common.CollectibleObject.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1657
   at Vintagestory.API.Common.Block.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 2257
   at Vintagestory.API.Common.ItemStack.GetDescription(IWorldAccessor world, ItemSlot inSlot, Boolean debug) in VintagestoryApi\Common\Collectible\ItemStack.cs:line 400
   at Vintagestory.GameContent.GuiHandbookItemStackPage..ctor(ICoreClientAPI capi, ItemStack stack) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 40
   at Vintagestory.GameContent.ModSystemSurvivalHandbook.onCreatePagesAsync() in VSSurvivalMod\Systems\Handbook\SurvivalHandbook.cs:line 84
   at Vintagestory.GameContent.GuiDialogHandbook.LoadPages_Async() in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 418
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 120
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 11/18/2024 8:05:23 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.5072, time stamp: 0xef4f0afe
Exception code: 0xe0434352
Fault offset: 0x000000000002ba99
Faulting process id: 0x1188
Faulting application start time: 0x01db3a1ed5af1271
Faulting application path: C:\Users\RBRWa\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 8891733b-b6bb-4119-a68f-91de61db32d2
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 11/18/2024 7:54:42 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.5072, time stamp: 0xef4f0afe
Exception code: 0xe0434352
Fault offset: 0x000000000002ba99
Faulting process id: 0x36c0
Faulting application start time: 0x01db3a1c426d209d
Faulting application path: C:\Users\RBRWa\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 4a69f473-847c-40d5-b3ea-99643adb4cef
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 11/15/2024 5:03:32 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.5072, time stamp: 0xef4f0afe
Exception code: 0xe0434352
Fault offset: 0x000000000002ba99
Faulting process id: 0xe04
Faulting application start time: 0x01db3795b17bfec3
Faulting application path: C:\Users\RBRWa\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: a9f8e29d-8849-4152-9428-1887bf14f290
Faulting package full name: 
Faulting package-relative application ID:  }

### Logs

```Log```Running on 64 bit Windows 10.0.19045.0 with 8054 MB RAM
Game Version: v1.19.8 (Stable)
11/18/2024 8:43:55 PM: Critical error occurred
Loaded Mods: 
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'The ThreadLocal object has been disposed.'.
   at System.Threading.ThreadLocal`1.GetValueSlow()
   at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionStatesNative(IWorldAccessor world, ItemSlot inslot) in VintagestoryApi\Common\Collectible\Collectible.cs:line 2507
   at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionStates(IWorldAccessor world, ItemSlot inslot) in VintagestoryApi\Common\Collectible\Collectible.cs:line 2455
   at Vintagestory.API.Common.CollectibleObject.AppendPerishableInfoText(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1814
   at Vintagestory.API.Common.CollectibleObject.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1657
   at Vintagestory.API.Common.Block.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 2257
   at Vintagestory.API.Common.ItemStack.GetDescription(IWorldAccessor world, ItemSlot inSlot, Boolean debug) in VintagestoryApi\Common\Collectible\ItemStack.cs:line 400
   at Vintagestory.GameContent.GuiHandbookItemStackPage..ctor(ICoreClientAPI capi, ItemStack stack) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 40
   at Vintagestory.GameContent.ModSystemSurvivalHandbook.onCreatePagesAsync() in VSSurvivalMod\Systems\Handbook\SurvivalHandbook.cs:line 84
   at Vintagestory.GameContent.GuiDialogHandbook.LoadPages_Async() in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 418
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 120
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 11/18/2024 8:05:23 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.5072, time stamp: 0xef4f0afe
Exception code: 0xe0434352
Fault offset: 0x000000000002ba99
Faulting process id: 0x1188
Faulting application start time: 0x01db3a1ed5af1271
Faulting application path: C:\Users\RBRWa\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 8891733b-b6bb-4119-a68f-91de61db32d2
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 11/18/2024 7:54:42 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.5072, time stamp: 0xef4f0afe
Exception code: 0xe0434352
Fault offset: 0x000000000002ba99
Faulting process id: 0x36c0
Faulting application start time: 0x01db3a1c426d209d
Faulting application path: C:\Users\RBRWa\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 4a69f473-847c-40d5-b3ea-99643adb4cef
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 11/15/2024 5:03:32 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.5072, time stamp: 0xef4f0afe
Exception code: 0xe0434352
Fault offset: 0x000000000002ba99
Faulting process id: 0xe04
Faulting application start time: 0x01db3795b17bfec3
Faulting application path: C:\Users\RBRWa\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: a9f8e29d-8849-4152-9428-1887bf14f290
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment] 2024-11-19 10:59
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4509

**Comment by Craluminum2413** [comment] 2024-11-19 11:00
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4225

**Closed by Craluminum2413** 2024-11-19 10:59 UTC
Labels: status: new

**Comment by Aethandus** [comment] 2024-11-19 16:36
Yeah it's a duplicate but HOW DO YOU FIX IT??? No one says anything ffs I'm sorry I'm stressing
