### ISSUE TITLE
Pot of cooked food can be stucked at wrong places

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1079] opened 2021-06-29 16:29 UTC
**Game Version:** 1.15.0-pre10
**Platform:** Windows 
**Modded:** No

### Description
Once filled, a cooking pot can be placed on a block side or below a block.

### Expected behavior
Less sticky recipes :-)

### Screenshots
![2021-06-29_18-22-12](https://user-images.githubusercontent.com/84909583/123834522-cb13c100-d907-11eb-8f13-37f5ce0b56c9.png)

**Comment by tyronx** [comment] 2021-06-30 11:11
hm. i'm not able to reproduce this. Is that really pre.10?

**Comment by Craluminum2413** [comment] 2021-06-30 11:30
I reproduced that

https://user-images.githubusercontent.com/69315569/123953205-a2df9d00-d9af-11eb-841c-9838d3717427.mp4

**Comment by Saricane** [comment] 2021-06-30 11:39
> 
> 
> hm. i'm not able to reproduce this. Is that really pre.10?

Yes. I always install the last "pre".

**Comment by tyronx** [comment] 2021-06-30 11:40
oooh, fascinating. Only works if you aim at the down face of a black

**Comment by tyronx** [comment] 2021-06-30 11:45
thanks should be fixed for pre.11

**Closed by tyronx** 2021-06-30 11:45 UTC
Labels: status: incomplete, target: survival
