### ISSUE TITLE
Game Crashes on TOPS Server join

### ISSUE THREAD

**Issue by KahvozeinsFang** [anegostudios/VintageStory-Issues#4599] opened 2024-12-05 13:47 UTC
### Game Version

v1.19.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Game crashes to desktop when trying to join the official public server (TOPS)

### How to reproduce

1. try to join the official public server
2. crashes to desktop

### Logs

Running on 64 bit Windows 10.0.19045.0 with 16287 MB RAM
Game Version: v1.19.8 (Stable)
12/5/2024 5:42:02 AM: Critical error occurred
Loaded Mods: game@1.19.8, creative@1.19.8, survival@1.19.8
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.WeatherSystemClient.OnRenderFrame(Single dt, EnumRenderStage stage) in VSEssentials\Systems\Weather\WeatherSystemClient.cs:line 140
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 200
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 806
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 858
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 730
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 12/5/2024 5:39:51 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x720
Faulting application start time: 0x01db471a5a2f08af
Faulting application path: C:\Users\playe\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\playe\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 8dfeab4c-e772-4f7c-bb8a-890ddc969f94
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 12/5/2024 5:28:57 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x2bbc
Faulting application start time: 0x01db47192b088734
Faulting application path: C:\Users\playe\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\playe\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 68ee0553-c3e1-40db-8347-44feda0f4b6f
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 12/5/2024 5:08:56 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x2fd4
Faulting application start time: 0x01db47167088dabd
Faulting application path: C:\Users\playe\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\playe\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 73162232-9956-47af-87dc-676cf590218c
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by bonenaut7** [comment] 2024-12-05 16:57
@Craluminum2413 duplicate of #4553

**Closed** 2024-12-05 16:59 UTC
Labels: status: incomplete
