### ISSUE TITLE
game crashes when cutting down tree

### ISSUE THREAD

**Issue by Satras1** [anegostudios/VintageStory-Issues#499] opened 2020-04-03 09:24 UTC
**Game Version:** 1.12.8
**Platform:** Windows 7
**Modded:** No

### Description
game crashes while/ shortly after cutting an oak tree with flint axe

### Logs
```
Running on 64 bit Windows with 4 GB RAM 
Version: v1.12.8 (Stable)03.04.2020 11:20:02: Critical error occurred
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.API.Common.EntityItem.FromBytes(BinaryReader reader, Boolean forClient)
   bei Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntitySpawnPacket(_9J05IwqX3DMJjYc4TgQdHtYCjUh serverpacket)
   bei _DheU0S41ys8PmWwanVxliVufAfL._8pFQWKHqjk1Z0lk74wVtfciws7e(Single )
   bei _EBtxK36Ixmcei9M4cHb3yN0CdBY._SBmZIE5zeKBZLld4sDoBkph45oC(Single )
   bei _TCuegFvuCG7xQqhWKljGWgaccAS._xnJNZgMqo5oGjGjHTS2kXgpC9eH(Single )
   bei _TCuegFvuCG7xQqhWKljGWgaccAS._uw3xmExX4CRVc5TYKty6OJkT52C(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _BjgcNpIFkj1jqrVxzsqeX8AsdOJ._Sxh5j8nPFBKHENmnO5xs7MH8hze(_dWKuoESsZrjrNSOe8XL3edrjaTJ , String[] )
   bei _OeweVW96y8iGyqsCmuTDn7vCxyG._Sxh5j8nPFBKHENmnO5xs7MH8hze(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 03.04.2020 07:56:53, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund eines Ausnahmefehlers beendet.
Ausnahmeinformationen: Ausnahmecode c0000005, Ausnahmeadresse 0000000069B2092F
 }
{ TimeGenerated = 01.04.2020 18:31:19, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund eines Ausnahmefehlers beendet.
Ausnahmeinformationen: Ausnahmecode c0000005, Ausnahmeadresse 0000000069B2092F
 }
{ TimeGenerated = 01.04.2020 17:39:51, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund eines Ausnahmefehlers beendet.
Ausnahmeinformationen: Ausnahmecode c0000005, Ausnahmeadresse 0000000069B2092F
 }
```

**Comment by copygirl** [comment] 2020-04-03 13:16
Going to close as duplicate of #472 for now. @tyronx should have another look at this, perhaps.

Regarding your issue, it likely has to do with there being a "corrupted" entity or chunk the game is trying to load. First, try updating your game, and if that doesn't help, as mentioned in the other issue: Try loading your world in **repair mode** after clicking on the pencil icon in the world selection screen.

**Closed by copygirl** 2020-04-03 13:16 UTC
Labels: status: duplicate
