### ISSUE TITLE
client crash on 1.17.0-rc2 connection via lan

### ISSUE THREAD

**Issue by Yury-K** [anegostudios/VintageStory-Issues#2054] opened 2022-07-27 03:21 UTC
Title says it all, once either of us connects to recently installed 1.17.0-rc2 (tested on both full install and update), that runs over LAN, client is crashed, while server continues to work. 

```
-------------------------------
Game Version: v1.17.0-rc.2 (Unstable)
Loaded Mods: game@1.17.0-rc.2, creative@1.17.0-rc.2, survival@1.17.0-rc.2
2022-07-26 8:04:49 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.ClientMain.ProcessServerReady() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:line 1923
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:line 1138
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 381
   at Vintagestory.Client.ScreenManager.Render(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:line 704
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:line 608
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 125
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 87
-------------------------------
```
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/9194771/client-debug.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/9194772/client-main.txt)
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/9194773/client-crash.txt)

**Comment by Gervasn** [comment] 2022-07-27 11:03
Same here, not MOD related

Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.17.0-rc.2 (Unstable)
Loaded Mods: game@1.17.0-rc.2, creative@1.17.0-rc.2, survival@1.17.0-rc.2
27/07/2022 12:59:01: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.ClientMain.ProcessServerReady() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:line 1923
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:line 1138
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 381
   at Vintagestory.Client.ScreenManager.Render(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:line 704
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:line 608
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 125
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 87
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 26/07/2022 08:49:31, Site = , Source = Windows Error Reporting, Message = Fault bucket 2119052920621213464, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.0.0
P3: 62d57a08
P4: KERNELBASE.dll
P5: 10.0.19041.1826
P6: 299341e8
P7: c0020001
P8: 0000000000034fd9
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER32A3.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER37C5.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER37E5.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER37F3.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3813.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_2a65f0e7bbf23e7d34fefd26effc71194deb20_bda381a7_f2a62bd5-97ff-4000-9e7a-0ce6c79d7260

Analysis symbol: 
Rechecking for solution: 0
Report Id: 2d9cb20d-839d-46f0-9234-b616df91e889
Report Status: 268435456
Hashed bucket: 9182a16b1c37b65eed68636771e1a718
Cab Guid: 0 }
--------------
{ TimeGenerated = 26/07/2022 08:49:28, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.17.0.0, time stamp: 0x62d57a08
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1826, time stamp: 0x299341e8
Exception code: 0xc0020001
Fault offset: 0x0000000000034fd9
Faulting process ID: 0xc4c
Faulting application start time: 0x01d8a0bbc49e937d
Faulting application path: E:\Spiele\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 2d9cb20d-839d-46f0-9234-b616df91e889
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 26/07/2022 08:49:27, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FFF85544FD9
Stack:
 }

**Comment by Saricane** [comment] 2022-07-27 17:24
Crash with Open to Internet mode. Client crash as soon as connection is established and data begins to download. Windows client with Linux server.

```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.0-rc.2 (Unstable)
Loaded Mods: game@1.17.0-rc.2, creative@1.17.0-rc.2, survival@1.17.0-rc.2
27/07/2022 18:58:04: Critical error occurred
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à Vintagestory.Client.NoObf.ClientMain.ProcessServerReady() dans C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:ligne 1923
   à Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) dans C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:ligne 1138
   à Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) dans C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:ligne 381
   à Vintagestory.Client.ScreenManager.Render(Single dt) dans C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:ligne 704
   à Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) dans C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:ligne 608
   à Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) dans C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\GameWindow.cs:ligne 125
   à System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   à OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) dans C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:ligne 476
   à OpenTK.GameWindow.DispatchRenderFrame() dans C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:ligne 452
   à OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) dans C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:ligne 375
   à Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   à Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) dans C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:ligne 87
-------------------------------
```

**Comment by Craluminum2413** [comment] 2022-07-29 15:29
Duplicate of #2046

**Closed by Craluminum2413** 2022-07-29 15:29 UTC
