### ISSUE TITLE
Issue with launching 1.16.0-rc.8

### ISSUE THREAD

**Issue by NotBobRoss** [anegostudios/VintageStory-Issues#1561] opened 2022-01-10 03:05 UTC
Game Version: 1.16.0-rc.8
Platform:  Mac (High Sierra 10.13.6)   
Modded:No 
SP/MP: Singleplayer 

### Description
Everytime I launch Vintage Story on my Mac, it crashes. Specifically the newest unstable version. All I get every time I click on the application is an error message in the crash window(a screenshot of which is attached below). I'm not sure if its incompatibility with macOS or something with the game itself.

### How to reproduce
1. Download 1.16.0-rc.8 from the Vintage Story website
2. Unpack it and launch it on a Mac(I was running High Sierra 10.13.6)
3. It crashes.

### Expected behavior
I was expecting the game to launch. It's a fresh install, without mods so I figured it would have worked.

### Screenshots
![Crash](https://user-images.githubusercontent.com/97419978/148713718-ceb54221-e80d-4498-9caf-357d1ceb03f2.png)

### Logs
```
Version: v1.16.0-rc.8 (Unstable)1/9/2022 9:58:51 PM: Critical error occurred
System.DllNotFoundException: Lib64/libnanosvg.dylib assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) NanoSvg.SvgNativeMethods.nsvgCreateRasterizer()
  at Vintagestory.Client.NoObf.SvgLoader..ctor (Vintagestory.API.Client.ICoreClientAPI _capi) [0x0000d] in <e9ac1be8a5f24f8da990a2f3ddb56a77>:0 
  at _JecrxPkOIbspFBHIxhTD1TIVbii..ctor (_jcH3FSJ7ohiDyiUVjeI57gTMlzF , Vintagestory.API.Client.ICoreClientAPI ) [0x00030] in <e9ac1be8a5f24f8da990a2f3ddb56a77>:0 
  at _uIAcdMbC4bCBSiOcbau93JcD8BDA..ctor (_jcH3FSJ7ohiDyiUVjeI57gTMlzF ) [0x00025] in <e9ac1be8a5f24f8da990a2f3ddb56a77>:0 
  at _jcH3FSJ7ohiDyiUVjeI57gTMlzF._aC3ylqMdqishY21wVe5qXxrZ5ob (_EE6B13xM9ADbX1bGtFaOKrVoXro , System.String[] ) [0x00000] in <e9ac1be8a5f24f8da990a2f3ddb56a77>:0 
  at _ZqUQ7pOQY5Qg73UAepClsoZVWgk._aC3ylqMdqishY21wVe5qXxrZ5ob (_EE6B13xM9ADbX1bGtFaOKrVoXro , System.String[] ) [0x003bf] in <5a63ddc141e4421582b46ef4f5af7fac>:0 
  at _ZqUQ7pOQY5Qg73UAepClsoZVWgk+_72nmz5YyUkBBFQEgigOqyRhhWn1._9X7H6hffpqzJWaYa7oKbZe0GhbP () [0x00000] in <5a63ddc141e4421582b46ef4f5af7fac>:0 
  at _mWFXvJdRjYXBzuYdW6hiXK5Fb5p._aC3ylqMdqishY21wVe5qXxrZ5ob (System.Threading.ThreadStart ) [0x00007] in <e9ac1be8a5f24f8da990a2f3ddb56a77>:0

```

**Comment by copygirl** [comment] 2022-01-10 07:45
Duplicate of #1506. I wonder why @tyronx has not tried my suggested fix yet.

**Comment by tyronx** [comment] 2022-01-10 11:15
Which suggested fix?

**Comment by tyronx** [comment] 2022-01-10 11:41
@NotBobRoss could you open the extracted vintagestory in the finder, and replace this file in the Lib/ folder and see if that works?

=> http://files.tyron.at/cairo-sharp.dll.config

**Comment by tyronx** [comment] 2022-01-10 12:02
By the way, I can launch rc.8 out of the box on Mac OS Catalina.

**Comment by copygirl** [comment] 2022-01-10 15:12
> Which suggested fix?

Changing "Lib64" with "../Lib64"?

**Comment by tyronx** [comment] 2022-01-10 15:17
Tested that on my macbook air now, that breaks VS.

**Comment by copygirl** [comment] 2022-01-10 15:32
See [my suggested fix and f-io's response](https://github.com/anegostudios/VintageStory-Issues/issues/1506#issuecomment-1002755007) on the other issue.

**Comment by tyronx** [comment] 2022-01-27 10:04
This issue in particular is fixed by now

**Closed by tyronx** 2022-01-27 10:04 UTC
Labels: platform: osx, status: in-progress, priority: critical
