### ISSUE TITLE
Shivers and bowtorns spawn on surface far from any rift when temporal stability is turned off

### ISSUE THREAD

**Issue by Naxdar** [anegostudios/VintageStory-Issues#4382] opened 2024-10-27 19:14 UTC
### Game Version

1.20-pre.7

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When temporal stability is turned off at world creation or by command (and then restarting the game), shivers and bowtorns spawn on the surface at night even though the rift activity is calm or there aren't any nearby. Turning temporal stability back on on the same world (and restarting) makes this behavior disappear and no monster spawn when they shouldn't.
Temporal rifts do spawn properly and are visible.

Another note, in almost a year in-game with this setting, I didn't get a single temporal storm although they are supposed to be turned on. This too may be affected by the wrong setting

### How to reproduce

Create a world with temporal stability off.
Advance the time until it's dark enough, skip a few days if the rift activity isn't calm enough.
The new 1.20 monsters spawn at night

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2024-10-27 20:50
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4193

**Closed by Craluminum2413** 2024-10-27 20:50 UTC
Labels: status: new
