### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Braxx2011** [anegostudios/VintageStory-Issues#2471] opened 2023-03-12 23:51 UTC
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.11 (Stable)
3/12/2023 4:46:25 PM: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 407
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 718
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 622
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 124
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 3/12/2023 1:06:00 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2186699272363415476, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.11.0
P3: 10.0.19044.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Jason\AppData\Local\Temp\RDR836C.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER838C.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER839D.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER84AE.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER851C.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 4155b885-5bed-4aef-9c73-8d25712fd2c0
Report Status: 268435456
Hashed bucket: 0215b19e9f6a6c1d1e58b7670fd397b4
Cab Guid: 0 }
--------------
{ TimeGenerated = 2/5/2023 4:10:10 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2054915892851142415, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.10.0
P3: 10.0.19044.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Jason\AppData\Local\Temp\RDRD604.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD6A1.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD6E1.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD74C.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD7BA.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: e74ae7b2-b308-4c35-a598-fe1890aa5251
Report Status: 268435456
Hashed bucket: 25c2d65fe412a5f0ec84871dfcb26f0f
Cab Guid: 0 }
--------------
{ TimeGenerated = 1/3/2023 4:21:26 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1417649126400918622, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.9.0
P3: 63501532
P4: atio6axx.dll
P5: 31.0.12027.7000
P6: 6351b15d
P7: c0000005
P8: 000000000033dc8f
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2081.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER363D.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER367C.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER368A.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3737.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_f69d644578aa0d4de2a1bb1d589b6c7acf49df_7fba9aec_0e8be911-56f6-4c7a-a184-d525d90062be

Analysis symbol: 
Rechecking for solution: 0
Report Id: a14705a0-f56a-4954-bd3f-854f8956688e
Report Status: 268435456
Hashed bucket: e1851ed00ecd275d03ac805e9345045e
Cab Guid: 0 }

**Comment by Craluminum2413** [comment] 2023-03-13 09:26
Duplicate of #2380

**Closed by Craluminum2413** 2023-03-13 09:26 UTC
