### ISSUE TITLE
v1.15.6-rc.2 knapping crash

### ISSUE THREAD

**Issue by multicody10** [anegostudios/VintageStory-Issues#1308] opened 2021-09-19 10:53 UTC
**Game Version:** v1.15.6-rc.2 (Unstable)
**Platform:** Windows
**Modded:** No

### Description
Finishing a knap crashes the game. Restarting the game has the item in the inventory.

### How to reproduce
Place two stones down to knap and finish the product.

### Expected behavior
The item should be finished and placed in the inventory without crashing.

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.6-rc.2 (Unstable)9/19/2021 6:50:41 AM: Critical error occurred
System.ArgumentException: Trying to render an empty VAO
   at Vintagestory.Client.NoObf.ClientPlatformWindows.RenderMesh(MeshRef modelRef)
   at Vintagestory.GameContent.KnappingRenderer.RenderRecipeOutLine()
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderAfterFinalComposition(Single dt)
   at _DXJNEmwVJN2e1mVFBQ5fTNR95yc._aLrho8PYHXGJeKPDayUCeRClMEf(Single )
   at _DXJNEmwVJN2e1mVFBQ5fTNR95yc._fFzUEjicM6tZAbcIuKZDCkHSfMJ(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _tWK3XnqdKwEz32DZgEFtVG3UU4k._ZGFqinpvIwFTz7F68DuIhzHOWm(_0yeWQ9WAjs9sBw2gtkuglYTlTmO , String[] )
   at _O6YHJJOUkiLLqUHLpLxBur1CoDP._ZGFqinpvIwFTz7F68DuIhzHOWm(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 9/19/2021 6:24:18 AM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.15.6.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 3d4c

Start Time: 01d7ad403f6c38e7

Termination Time: 19

Application Path: C:\Users\Cody\AppData\Roaming\Vintagestory\Vintagestory.exe

Report Id: 363e6e20-0a66-4eaf-a322-bdebf27530ef

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
--------------
{ TimeGenerated = 9/19/2021 6:24:18 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.6.0
P3: 6145ea90
P4: c2ee
P5: 134217728
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7063.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7083.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7084.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER70A4.tmp.txt
\\?\C:\Users\Cody\AppData\Local\Temp\WERCFA7.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_Vintagestory.exe_5d021725e38bb4bb4631cce1b3f3d0bc52ac63_7d238f48_af429a7a-3aac-45f9-ba72-61d26c4000cc

Analysis symbol: 
Rechecking for solution: 0
Report Id: 363e6e20-0a66-4eaf-a322-bdebf27530ef
Report Status: 97
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 9/19/2021 6:22:01 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.6.0
P3: 6145ea90
P4: 79b2
P5: 134217728
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER72C9.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER72E9.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER72F8.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7318.tmp.txt
\\?\C:\Users\Cody\AppData\Local\Temp\WERBA05.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_Vintagestory.exe_6c5828289353fb8199db77acef52d47a52463_7d238f48_24a7f3ae-a7ea-4390-9cdf-7b4b4cc8288f

Analysis symbol: 
Rechecking for solution: 0
Report Id: e4017c6a-5c2a-432c-ac04-d2d070c0cde8
Report Status: 97
Hashed bucket: 
Cab Guid: 0 }
```

**Comment by Craluminum2413** [comment] 2021-09-19 11:06
Duplicate of #1306

**Comment by copygirl** [comment] 2021-09-19 12:00
Thanks for reporting, however.

**Closed by copygirl** 2021-09-19 12:00 UTC
Labels: status: duplicate

**Comment by multicody10** [comment] 2021-09-19 12:27
Ah sorry about that, I didn't even bother to check. Glad I'm not the only one though.
