### ISSUE TITLE
Crash when Rapidly Generating Chunks - v1.19.0

### ISSUE THREAD

**Issue by HalfdeadKiller** [anegostudios/VintageStory-Issues#3456] opened 2024-01-18 00:01 UTC
### Game Version

v1.19.0

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Running on 64 bit Windows 10.0.19045.0 with 65452 MB RAM
Game Version: v1.19.0 (Stable)
1/17/2024 17:56:59: Critical error occurred
Loaded Mods: game@1.19.0, creative@1.19.0, survival@1.19.0
System.Exception: Max joint cap of 36 reached, needs to be at least 43. In clientsettings.json, please try increasing the "maxAnimatedElements": setting to 46.  This works for most GPUs.  Otherwise you might need to disable the creature.
   at Vintagestory.API.Common.Animation.GenerateAllFrames(ShapeElement[] rootElements, Dictionary`2 jointsById, Boolean recursive) in VintagestoryApi\Common\Model\Animation\Animation.cs:line 97
   at Vintagestory.API.Common.ClientAnimator.AnimNowActive(RunningAnimation anim, AnimationMetaData animData) in VintagestoryApi\Common\Model\Animation\ClientAnimator.cs:line 225
   at Vintagestory.API.Common.AnimatorBase.OnFrame(Dictionary`2 activeAnimationsByAnimCode, Single dt) in VintagestoryApi\Common\Model\Animation\AnimatorBase.cs:line 115
   at Vintagestory.API.Common.AnimationManager.OnClientFrame(Single dt) in VintagestoryApi\Common\Model\Animation\AnimationManager.cs:line 347
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 49
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 808
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 724
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

### Logs

```Log```

**Comment by pingouyn** [comment] 2024-01-18 00:41
Exact same error message than #3426 ?

**Comment by HalfdeadKiller** [comment] 2024-01-18 03:06
It appears so, yes. Apologies for the duplicate post.

**Comment by pingouyn** [comment] 2024-01-18 04:56
Actually, I believe it could also linked to a report that was closed: #3276 from 1.19.0-pre8.
I can't comment on the value 64 but the api docs for Vintage Story say this: "Max. amount of "bones" for animated model. Limited by max amount of shader uniforms of around 60, but depends on the gfx card".  I can only presume lower values are kept for compatibility with older GPU's but 46 seems to be the current recommended value according to bug report 3276.  PS: I'm not part of the dev team.

**Comment by Craluminum2413** [comment] 2024-01-18 05:16
Duplicate of #3284

**Closed** 2024-01-18 05:17 UTC
Labels: status: duplicate
