### ISSUE TITLE
Hot Crucible In inventory causes crashes

### ISSUE THREAD

**Issue by Namestop** [anegostudios/VintageStory-Issues#4424] opened 2024-11-02 23:02 UTC
### Game Version

v1.20.0pre.7 (Unstable)

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

My friend was unable to exists in the server without crashing because a hot crucible in his inventory. He couldn't log on to drop it or pick up tongs.

### How to reproduce

1. I had grabbed a partially heated crucible which burned me when I picked it up without tongs. 
2. It dropped and went to my friend's inventory. 
3. It damaged him after several moments, he dropped it out of pain before he crashed. 
4. I picked it up with tongs and set it on the floor, he came back and accidentally picked it up again before he was no longer able to be in the server without crashing all the players within. 

### Logs

Running on 64 bit Windows 10.0.19045.0 with 32509 MB RAM
Game Version: v1.20.0-pre.7 (Unstable)
11/2/2024 4:51:34 PM: Critical error occurred
Loaded Mods: HangingOilLamps@1.0.1, koboldplayermodelport@1.2.11, palisademodpatch@1.1.0, palisademod@1.1.0, primitivesurvival@3.7.0, sortablestorage@2.2.7, game@1.20.0-pre.7, egocaribautomapmarkers@4.0.0, carryon@1.8.0-pre.1, commonlib@2.5.0-rc.2, danatweaks@3.3.2, justanarrowheadmold@1.0.1, manualtoolcrafting@1.0.0, simplefootstepsredux@1.0.1, creative@1.20.0-pre.7, survival@1.20.0-pre.7, playercorpse@1.10.1-rc.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityPlayerShapeRenderer.RenderHeldItem(Single dt, Boolean isShadowPass, Boolean right) in VSEssentials\EntityRenderer\EntityPlayerShapeRenderer.cs:line 278
   at Vintagestory.GameContent.EntityPlayerShapeRenderer.DoRender3DOpaque(Single dt, Boolean isShadowPass) in VSEssentials\EntityRenderer\EntityPlayerShapeRenderer.cs:line 230
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderOpaque3D(Single deltaTime) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 79
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 819
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 825
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 741
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 207
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 11/2/2024 4:50:14 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x3cd4
Faulting application start time: 0x01db2d796cc28aa6
Faulting application path: C:\Users\Dusty\Desktop\PC Stuffs\Organized\Game Related\games\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\Dusty\Desktop\PC Stuffs\Organized\Game Related\games\Vintagestory\Lib\openal32.dll
Report Id: d357b93f-d4ca-4ca0-b0c0-859f041e3136
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment] 2024-11-03 11:17
Does it happen in pre.9?

**Comment by radfast** [comment] 2024-12-20 01:51
> Duplicate of #4314

@Craluminum2413 something wrong with the triage here.  This and #4735 are the same issue, and I now suspect mod-triggered. I notice both have **hanging oil-lamps** mod ...   The root cause is an item in the left-hand ItemSlot which has null `Attributes`. 

Neither this nor #4735 are duplicates of #4314, the crashing methods and line numbers in the stacktrace are different.

@Namestop this issue will be finally fixed in 1.20.0-rc.6, apologise for the delay.  Meanwhile you or other affected players might be able to solve the issue by tweaking hanging oillamps mod .jsons to give its blocks and items some simple attributes, like this:

     attributes: {  shelvable: true },

This tweak is only really needed for whatever hanging oillamps item the relevant player (the one with the hot item) has in their left hand slot

Or just wait for 1.20-rc.6

Deleting hanging oillamps mod will not solve the problem, most likely, because even a "missing" block or item in the left hand slot will cause the issue, that's kind of worse actually...

**Comment by Craluminum2413** [comment] 2024-12-20 01:54
I didn't notice that

**Closed** 2024-12-20 03:17 UTC
Labels: status: resolved
