### ISSUE TITLE
Small visual bug with shield on the groung (1.18.6)

### ISSUE THREAD

**Issue by DonKamaro** [anegostudios/VintageStory-Issues#2859] opened 2023-06-28 19:48 UTC
### Game Version

1.18.6 (also 1.18-rc.2)

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When the shield is placed on the ground, it becomes invisible. Placing other tools on the same block does not change the situation. Tested it in different worlds and on different shields. In most cases, the shield becomes invisible, sometimes only the edge is visible. The crude shield behaves especially strange - its texture changes when it is placed on the ground. 

### Screenshots

https://github.com/anegostudios/VintageStory-Issues/assets/108415547/eb8de5f6-2e2f-4f58-ad9e-ed21792f3e9a

**Comment by RedramVS** [comment] 2023-12-13 15:14
I cannot reproduce this.  I'm going to assume it's been fixed in the past 6 months.

**Closed by RedramVS** 2023-12-13 15:14 UTC
Labels: status: new, department: code, version: 1.18
