### ISSUE TITLE
Graphical Error in Handbook

### ISSUE THREAD

**Issue by TheJellyCat** [anegostudios/VintageStory-Issues#535] opened 2020-05-25 16:22 UTC
**Game Version:** 1.12.14
**Platform:** Windows
**Modded:** Yes (GraveMod, Lazy Warlock's Tweaks)

### Description
When mousing over items in the Handbook, putting the mouse between two items will overlay the images and the first line of the descriptions (but not the item names, oddly enough).

### How to reproduce
I specifically found this under the "obtained by breaking" and "ingredient for" sections on any item, but there may be others. 

### Screenshots
![image](https://user-images.githubusercontent.com/65913379/82829812-2b713d00-9e82-11ea-97f8-b3d180782f0e.png)

**Comment by tyronx** [comment] 2020-07-29 12:30
Duplicate of #513

**Closed by tyronx** 2020-07-29 12:30 UTC
Labels: status: new, type: bug
