### ISSUE TITLE
Standard mode night much too dark.

### ISSUE THREAD

**Issue by framingnoone** [anegostudios/VintageStory-Issues#847] opened 2021-04-02 20:40 UTC
**Game Version:** 1.4.8
**Platform:** Linux
**Modded:** No 

### Description
![image](https://user-images.githubusercontent.com/18292891/113451685-234e2c00-93c8-11eb-93ab-80baf6545a28.png)

Darkness nigh impenetrable even outside, and it gets even darker (to probably total blackness aside from stars) than that in a few minutes. Also, modding gamma with the clientconfig line has no visible effect.

### How to reproduce
Start standardl game, wait till night without a torch.
### Expected behavior
At least some amount of being able to see at night with standard graphics settings in survival mode.

### Screenshots
![image](https://user-images.githubusercontent.com/18292891/113451685-234e2c00-93c8-11eb-93ab-80baf6545a28.png)

### Logs
No crash

**Comment by copygirl** [comment] 2021-04-02 21:11
Unfortunately this is intentional at this time. I'd personally like it if it was dependent on moon phases and weather, so clear sky + full moon (or even a **super** moon) would brighten up the nights, while there could still be ones where you have little choice but to stay at home or deal with pitch blackness.

**Comment by framingnoone** [comment] 2021-04-02 23:11
Allow me to add my vote to the "this is a terrible choice for accessibility, and not that great for gameplay either" column.

**Comment by Dulciphi** [comment] 2021-04-18 19:43
I'll add my vote to keeping the day/night cycle and for caves that are actually dark inside. I like having a use for torches. Perhaps consider adding a config option for those who wish to only play during the day and without caves.

**Comment by sirStroam** [comment] 2021-06-30 05:33
This has been marked as a suggestion and we are no longer supporting suggestions here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/

**Closed by sirStroam** 2021-06-30 05:33 UTC
Labels: status: new, target: survival, type: suggestion

**Comment by sirStroam** [comment] 2021-07-02 06:00
The game already provides several different ways of obtaining light sources for which to see by at night. I don't see how this is limiting a players ability to play as intended.
