### ISSUE TITLE
Crash when cancelling new world generation

### ISSUE THREAD

**Issue by jevarlec** [anegostudios/VintageStory-Issues#4095] opened 2024-09-18 17:59 UTC
### Game Version

v1.20-pre.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The game crashes if new world generation is cancelled after `Center is unfolding` is outputted.

### How to reproduce

1. Select `single player`, click `create new world`, choose standard and click `create world`
2. Wait until `Center is unfolding` is outputted and click `Cancel`

### Logs

```Running on 64 bit Windows 10.0.19045.0 with 16285 MB RAM
Game Version: v1.20.0-pre.1 (Unstable)
18/09/2024 19:56:46: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockShapeFromAttributes.OnUnloaded(ICoreAPI api) in VSSurvivalMod\Block\BlockShapeFromAttributes.cs:line 170
   at Vintagestory.Client.NoObf.ClientMain.Dispose() in VintagestoryLib\Client\ClientMain.cs:line 2722
   at Vintagestory.Client.NoObf.ClientMain.DestroyGameSession(Boolean gotDisconnected) in VintagestoryLib\Client\ClientMain.cs:line 2655
   at Vintagestory.Client.GuiScreenConnectingToServer.onCancel() in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 206
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 318
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 311
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 447
   at GuiScreen.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\MainMenu\Screens\Special\GuiScreen.cs:line 204
   at Vintagestory.Client.ScreenManager.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\ScreenManager.cs:line 913
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 211
   at OpenTK.Windowing.Desktop.NativeWindow.OnMouseUp(MouseButtonEventArgs e)
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.NativeWindow.ProcessWindowEvents(Boolean waitForEvents)
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by Craluminum2413** [comment] 2024-09-18 18:03
Does it happen every time with every new world?

**Comment by jevarlec** [comment] 2024-09-18 18:04
Yes. Every time.

**Comment by AlexanderwithaA** [comment] 2024-11-09 04:41
I can confirm this as well, I’m getting it on 1.20 pre11 on linux

**Comment by Craluminum2413** [comment] 2024-12-15 20:58
Looks like it was fixed in rc.1

**Closed by Craluminum2413** 2024-12-15 20:58 UTC
Labels: status: confirmed, department: code, version: 1.20
