### ISSUE TITLE
Infinite pie piece

### ISSUE THREAD

**Issue by Aizistral** [anegostudios/VintageStory-Issues#2130] opened 2022-08-23 18:32 UTC
**Game Version:** 1.16.5
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
Placing down and subsequently picking up a piece of pie will always return a piece with 0,25 servings (i.e. full piece). Therefore player can keep partially consuming the piece and placing/taking it to get full one back every time (at least until it gets spoiled).

### How to reproduce
1. Make a pie
2. Cut it into pieces
3. Partially eat one piece
4. Place it into the world
5. Take it from the world
6. Behold!

### Expected behavior
Serving size is preserved when placing pie pieces into the world, or partially eaten pieces are not placeable at all.

**Comment by wasakoki** [comment] 2022-08-29 06:38
also was reported in #1916 , though that report was a while back and was never acknowledged so that one might of been forgotten about

**Comment by tyronx** [comment] 2022-08-29 07:07
Duplicate of #1916

**Closed by tyronx** 2022-08-29 07:07 UTC
Labels: status: new
