### ISSUE TITLE
[Manjaro] Sound does not work on Linux

### ISSUE THREAD

**Issue by Astrayo** [anegostudios/VintageStory-Issues#1897] opened 2022-05-16 23:48 UTC
**Game Version:** 1.16.5
**Platform:** Manjaro Linux  
**Modded:** No 
**SP/MP:** Singleplayer

### Description
Sounds do not work on Linux, despite manually setting the output device to my headset in the audio settings. Restarting did not fix the issue.

### How to reproduce
1. Run the game on Manjaro Linux
2. Observe the lack of audio

### Expected behavior
Sounds actually working.

### Screenshots
Not applicable

### Logs
I do not know where to find the logs on Linux, and I cannot see how it would be of help regardless as this has nothing to do with crashes.

**Comment by 5HT2** [comment] 2022-05-17 02:06
Can't reproduce. Are you using ALSA or Pulseaudio or Pipewire, or some combination of those?

**Comment by copygirl** [comment] 2022-05-17 05:25
Apologies for closing this issue, but this sounds more like a support issue that can be solved more easily by asking other Manjaro, Arch-based distros, or Linux users in general for help, such as on on the forums or Discord. Vintage Story runs fine according to a lot of posts on the [Linux distros/configurations under which VS is known to run](https://www.vintagestory.at/forums/topic/520-linux-distrosconfigurations-under-which-vs-is-known-to-run/) thread.

For the record, I have used PulseAudio in the pause and am now on PipeWire with `pipewire-pulse`.

**Closed by copygirl** 2022-05-17 05:25 UTC
Labels: status: invalid
