### ISSUE TITLE
Game crash when writing in a book

### ISSUE THREAD

**Issue by CodeHxr** [anegostudios/VintageStory-Issues#3117] opened 2023-09-27 19:25 UTC
### Game Version

v1.18.13

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I was writing pages into an editable book.  I was starting page three and backspacing to correct some typos and got a CTD with an error log.

### Logs

```Running on 64 bit Windows with 16312 MB RAM
Game Version: v1.18.13 (Stable)
9/27/2023 3:19:36 PM: Critical error occurred
Loaded Mods: game@1.18.13, creative@1.18.13, survival@1.18.13
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at Vintagestory.GameContent.GuiDialogEditableBook.onTryTextChange(List`1 lines) in VSSurvivalMod\Systems\WritingSystem\GuiDialogEditableBook.cs:line 78
   at Vintagestory.API.Client.GuiElementEditableTextBase.LoadValue(List`1 newLines) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 291
   at Vintagestory.API.Client.GuiElementEditableTextBase.SetValue(String text, Boolean setCaretPosToEnd) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 263
   at Vintagestory.GameContent.GuiDialogReadonlyBook.updatePage(Boolean setCaretPosToEnd) in VSSurvivalMod\Systems\WritingSystem\GuiDialogReadonlyBook.cs:line 166
   at Vintagestory.GameContent.GuiDialogEditableBook.onTextChanged(String text) in VSSurvivalMod\Systems\WritingSystem\GuiDialogEditableBook.cs:line 124
   at Vintagestory.API.Client.GuiElementEditableTextBase.TextChanged() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 328
   at Vintagestory.API.Client.GuiElementTextArea.TextChanged() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementTextArea.cs:line 32
   at Vintagestory.API.Client.GuiElementEditableTextBase.OnKeyBackSpace() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 559
   at Vintagestory.API.Client.GuiElementEditableTextBase.OnKeyDown(ICoreClientAPI api, KeyEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 422
   at Vintagestory.API.Client.GuiComposer.OnKeyDown(KeyEvent args, Boolean haveFocus) in VintagestoryApi\Client\UI\GuiComposer.cs:line 593
   at Vintagestory.API.Client.GuiDialog.OnKeyDown(KeyEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 435
   at Vintagestory.GameContent.GuiDialogReadonlyBook.OnKeyDown(KeyEvent args) in VSSurvivalMod\Systems\WritingSystem\GuiDialogReadonlyBook.cs:line 205
   at Vintagestory.GameContent.GuiDialogEditableBook.OnKeyDown(KeyEvent args) in VSSurvivalMod\Systems\WritingSystem\GuiDialogEditableBook.cs:line 213
   at Vintagestory.Client.NoObf.GuiManager.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 333
   at Vintagestory.Client.NoObf.ClientMain.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1705
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(KeyboardKeyEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 231
   at OpenTK.Windowing.Desktop.NativeWindow.KeyCallback(Window* window, Keys key, Int32 scancode, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 9/27/2023 2:07:06 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1237268411382838093, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.13.0
P3: 64b07659
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3D37.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER421A.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER422B.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4229.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER42C6.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_2ec7e698813894950b9b93e32146592f2344b2_ae564f4f_ebb11320-34a6-4875-a636-ad572abd0d6f

Analysis symbol: 
Rechecking for solution: 0
Report Id: 36f00844-425d-4078-83ed-efe2b56a1a70
Report Status: 268566528
Hashed bucket: 2245dcdc53ace9ebc12ba9109849334d
Cab Guid: 0 }
--------------
{ TimeGenerated = 9/27/2023 2:07:04 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.13.0, time stamp: 0x64b07659
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0xb30
Faulting application start time: 0x01d9f0e72c6ed1ee
Faulting application path: D:\Games\Vintagestory\Vintagestory.exe
Faulting module path: D:\Games\Vintagestory\Lib\openal32.dll
Report Id: 36f00844-425d-4078-83ed-efe2b56a1a70
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 9/26/2023 10:06:01 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1237268411382838093, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.13.0
P3: 64b07659
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7F63.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER85DD.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER85ED.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER85FB.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER861B.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_2ec7e698813894950b9b93e32146592f2344b2_ae564f4f_c476eded-6858-4071-91ab-ccb3c12abb67

Analysis symbol: 
Rechecking for solution: 0
Report Id: abf757c2-15ac-48a6-8e3a-bc410c9f4fdf
Report Status: 268566528
Hashed bucket: 2245dcdc53ace9ebc12ba9109849334d
Cab Guid: 0 }```

**Comment by Craluminum2413** [comment] 2023-09-27 19:35
Duplicate of #2740

**Closed by Craluminum2413** 2023-09-27 19:35 UTC
Labels: status: new
