### ISSUE TITLE
Forge toolpit not translated

### ISSUE THREAD

**Issue by daretmavi** [anegostudios/VintageStory-Issues#1790] opened 2022-03-06 13:49 UTC
**Game Version:** 1.16.4
**Platform:** Linux (KDE neon 20.04 5.24)
**Modded:** No
**SP/MP:** Singleplayer

### Description
Text in forge toolpit are not translated (Contents and Temperature)

### How to reproduce
1. Change the language to Slovak
2. Insert and use forge
3. Go with mouse over the forge - you can sell Contents and Temperature English Texts

### Expected behavior
Should be translated, if all text in crowdin are translated.

### Screenshots
![2022-03-05_17-51-53](https://user-images.githubusercontent.com/47914240/156926124-eb6d7a9b-5ae3-465e-a7f7-6d90803821dd.png)

**Comment by daretmavi** [comment] 2023-04-15 22:07
Tested with 1.18.0 rc6 and still not resolved
![obrázok](https://user-images.githubusercontent.com/47914240/232255134-d35694e1-22df-4364-ac5e-214119387b81.png)
 - see English texts

**Comment by Craluminum2413** [comment] 2023-04-15 22:31
Damd

**Comment by Craluminum2413** [comment] 2023-04-15 22:33
@daretmavi What language?

**Comment by Craluminum2413** [comment] 2023-04-15 22:42
@daretmavi I can't reproduce it on 1.18.0-rc.6, I close it again
![image](https://user-images.githubusercontent.com/69315569/232256159-7132d346-4593-4e18-951f-bd1c5637311b.png)

**Comment by Craluminum2413** [comment] 2023-04-15 22:43
Reinstall the game if you encounter this issue again

**Closed by Craluminum2413** 2023-04-15 22:42 UTC
Labels: status: in-progress, target: localization

**Comment by daretmavi** [comment] 2023-04-16 06:48
I just run the game from the extracted archive on linux.

It's weird, as I opened the old test world I got for a second the correct translation (it was blinking between SK and EN). I destroyed the forge and created it again to find out what is going on. Right now I see EN texts again.

**Comment by daretmavi** [comment] 2023-04-16 07:01
I know now.
I used the new sk.json from crowdin, but in the same time as I downloaded the new version, new strings was updated, what was not recognized in my browser.

And this was in it:
"forge-contentsandtemp": "Contents: {0}x {1}\nTemperature: {2} °C",
"forge-contentsandtemp-cold": "Obsahuje: {0}x {1}\nTeplota: Studené"

- this explains everything :)
