### ISSUE TITLE
Crash on starting a new world or joining multiplayer

### ISSUE THREAD

**Issue by WretchedAbyss** [anegostudios/VintageStory-Issues#3326] opened 2023-12-21 23:02 UTC
### Game Version

v1.19.0 pre 10

### Platform

Linux

### Modded

Vanilla

### SP/MP

None

### Description

It crashes at the start of a new world or on joining any multiplayer world. 
I am on Arch Linux. This could be part of the issue or perhaps not?

### How to reproduce

Just install the tar ball and create a world default settings and all.t

### Logs

```Log```Running on 64 bit Linux with 32003 MB RAM
Game Version: v1.19.0-pre.10 (Unstable)
12/21/2023 5:56:11PM: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.ClientMain.Dispose() in VintagestoryLib\Client\ClientMain.cs:line 2636
   at Vintagestory.Client.GuiScreenConnectingToServer.exitToDisconnectScreen() in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 416
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 306
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 317
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by radfast** [comment] 2023-12-22 16:41
Thanks for reporting. 

The cause of this was a different issue causing startup crashes in multiplayer sometimes.  Because the game crashed at startup, some things were not yet fully initialised, therefore the CrashReporter itself then crashed.

Both issues are fixed in next release, which might be upcoming today ;)

**Closed by radfast** 2023-12-22 16:41 UTC
Labels: status: new
