### ISSUE TITLE
Issue joining my server

### ISSUE THREAD

**Issue by Pandalife1819** [anegostudios/VintageStory-Issues#4384] opened 2024-10-27 19:40 UTC
### Game Version

1.19.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

I bought a server to host for me and my brother however i cannot join it to whitelist him at all as i keep crashing anytime i try to join. I've tried to revert to an older version and still cannot join my server but can join other servers just fine. after the crash this keeps popping up.
Running on 64 bit Windows 10.0.19045.0 with 32717 MB RAM
Game Version: v1.19.8 (Stable)
10/27/2024 2:39:06 PM: Critical error occurred

Loaded Mods: 
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Vintagestory.Client.NoObf.TextureAtlasManager.RegenMipMaps(Int32 atlasNumber) in VintagestoryLib\Client\Render\Atlas\TextureAtlasManager.cs:line 359
   at Vintagestory.Client.NoObf.TextureAtlasManager.<>c__DisplayClass51_0.<runtimeUpdateTexture>b__1() in VintagestoryLib\Client\Render\Atlas\TextureAtlasManager.cs:line 325
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 776
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 731
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 10/27/2024 11:11:09 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.4957, time stamp: 0xc5225d0f
Exception code: 0xe0434352
Fault offset: 0x000000000003b699
Faulting process id: 0xde0
Faulting application start time: 0x01db2869c8b3054a
Faulting application path: E:\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: f4285400-60bd-4c29-a44e-d290d856346e
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 10/27/2024 7:11:27 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.4957, time stamp: 0xc5225d0f
Exception code: 0xe0434352
Fault offset: 0x000000000003b699
Faulting process id: 0x56a0
Faulting application start time: 0x01db2869234bcf0a
Faulting application path: E:\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: fa576d12-b8a2-4262-98a0-d2feea42b78e
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 10/27/2024 6:59:17 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.4957, time stamp: 0xc5225d0f
Exception code: 0xe0434352
Fault offset: 0x000000000003b699
Faulting process id: 0x5568
Faulting application start time: 0x01db28671db32297
Faulting application path: E:\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 0ca5c4a0-174b-40cd-a235-a0300eae9785
Faulting package full name: 
Faulting package-relative application ID:  }

### How to reproduce

Open vintage story start server and attempt to join.

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2024-10-27 20:48
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4158

**Closed by Craluminum2413** 2024-10-27 20:48 UTC
Labels: status: incomplete
