### ISSUE TITLE
Vanilla crash when leaving a world with a number of drifters

### ISSUE THREAD

**Issue by Bughaw** [anegostudios/VintageStory-Issues#4509] opened 2024-11-13 19:58 UTC
### Game Version

v1.20.0pre13

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

World crash upon exit.  Nothing unusual going on, just dropped a dozen drifters in a test world, changed to survival and exited.  Game crashed upon world exit.  Save file attached.
[gloomy hermit world.vcdbs.zip](https://github.com/user-attachments/files/17738555/gloomy.hermit.world.vcdbs.zip)

### Logs
```
Running on 64 bit Linux (Linux Mint 21.3) [Kernel 6.8.0.48] with 13733 MB RAM
Game Version: v1.20.0-pre.13 (Unstable)
11/13/2024 11:52:17: Critical error occurred
Loaded Mods: 
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'The ThreadLocal object has been disposed.'.
   at System.Threading.ThreadLocal`1.GetValueSlow()
   at Vintagestory.Client.NoObf.ClientMain.get_Rand() in VintagestoryLib\Client\ClientMain.cs:line 2945
   at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionStatesNative(IWorldAccessor world, ItemSlot inslot) in VintagestoryApi\Common\Collectible\Collectible.cs:line 2501
   at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionStates(IWorldAccessor world, ItemSlot inslot) in VintagestoryApi\Common\Collectible\Collectible.cs:line 2446
   at Vintagestory.API.Common.CollectibleObject.AppendPerishableInfoText(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1805
   at Vintagestory.API.Common.CollectibleObject.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1648
   at Vintagestory.API.Common.Block.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 2285
   at Vintagestory.API.Common.ItemStack.GetDescription(IWorldAccessor world, ItemSlot inSlot, Boolean debug) in VintagestoryApi\Common\Collectible\ItemStack.cs:line 400
   at Vintagestory.GameContent.GuiHandbookItemStackPage..ctor(ICoreClientAPI capi, ItemStack stack) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 40
   at Vintagestory.GameContent.ModSystemSurvivalHandbook.onCreatePagesAsync() in VSSurvivalMod\Systems\Handbook\SurvivalHandbook.cs:line 86
   at Vintagestory.GameContent.GuiDialogHandbook.LoadPages_Async() in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 418
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 120
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by Craluminum2413** [comment] 2024-11-16 15:34
https://github.com/anegostudios/VintageStory-Issues/issues/4225

**Comment by Craluminum2413** [comment] 2024-11-19 10:59
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4225

**Closed by Craluminum2413** 2024-11-19 10:59 UTC
Labels: status: new, department: code
