### ISSUE TITLE
Pie disappears after baking 

### ISSUE THREAD

**Issue by chiyamadas** [anegostudios/VintageStory-Issues#2833] opened 2023-06-19 15:15 UTC
I've made about two pies, one meat and one turnip, and when i put them in the oven they just disappear.

**Comment by RedramVS** [comment] 2023-12-13 15:39
Due to lack of details - including whether user is using mods or not - and inability to reproduce with simple raw pies of named varieties, and age of issue, I'm closing this one.

**Closed by RedramVS** 2023-12-13 15:39 UTC
Labels: status: incomplete, status: can't reproduce
