### ISSUE TITLE
Placing Trapdoor in 1.12.0-pre.3 (also pre.2) causes CTD

### ISSUE THREAD

**Issue by yoshuamongrain** [anegostudios/VintageStory-Issues#360] opened 2020-01-03 20:53 UTC
**Game Version:** 1.12.0-pre.3
**Platform:** Windows 10 64bit
**Modded:** No

### Description
Placing a trapdoor causes a CTD

### How to reproduce
1. Make a trapdoor
2. Use it on anything tested so far
3. It crashes (CTD)

### Logs
```
Running on 64 bit Windows with 0 GB RAM 
Version: v1.12.0-pre.3 (Unstable)2020-01-03 15:50:13: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.ServerMods.BlockBehaviorOmniRotatable.TryPlaceBlock(IWorldAccessor world, IPlayer byPlayer, ItemStack itemstack, BlockSelection blockSel, EnumHandling& handling, String& failureCode)
   at Vintagestory.API.Common.Block.TryPlaceBlock(IWorldAccessor world, IPlayer byPlayer, ItemStack itemstack, BlockSelection blockSel, String& failureCode)
   at _ojAw9emAvKe8zqLqsPRdr9xlzOB._dJwePdWCWRS8Ydzv2GSjTt3KN8G(BlockSelection , String& )
   at _HUyuCghKhMVednHGpDEhZ7H1Fge._2KPD6AVhA8mIFzRel0o1f8E5FA(BlockSelection , Block , String& )
   at _HUyuCghKhMVednHGpDEhZ7H1Fge._hjBKwlpZdKhf0zu3o30vNvvrtDB(Single )
   at _HUyuCghKhMVednHGpDEhZ7H1Fge._5YAFbH9BQM9IymodpzLK9KqHgRc(Single )
   at _gcAgJGDeUV4pQlpEkr03sr6JB40._muqyb0vfG3PEPOKLbbmOdS3VhwL(EnumRenderStage , Single )
   at _ojAw9emAvKe8zqLqsPRdr9xlzOB._muqyb0vfG3PEPOKLbbmOdS3VhwL(EnumRenderStage , Single )
   at _ojAw9emAvKe8zqLqsPRdr9xlzOB._7MXZdQYFQOOWwGWCzaxGB6vklp5(Single )
   at _yoMBVVvSDfkFcbxhR4S4RydNOFE._7MXZdQYFQOOWwGWCzaxGB6vklp5(Single )
   at _eXZCoUhba7NjEQEmCGbXKIQ8MSOA._FCrirpCg3CkbfaP9XvJuuG0FqaT(Single )
   at _eXZCoUhba7NjEQEmCGbXKIQ8MSOA._S1gd9prv5sOn88m2XSX3soqEvrL(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _kjAEHgCRAsCJPQgGg79faT7OB7t._0XOewofVxER8pm50b0QD2nRj5rk(_7ylOsJ1ygqj9ry64tzsRpSpX8Qc , String[] )
   at _vdRBBGKq6gow1aRN3XkM0yd6kTb._0XOewofVxER8pm50b0QD2nRj5rk(ThreadStart )
-------------------------------

```

**Comment by tyronx** [comment] 2020-01-05 14:40
thanks for the report. Should be fixed in pre.4

**Comment by yoshuamongrain** [comment] 2020-01-05 16:10
Trying in world started in pre.1 with client updated from pre.3 to pre.4 this issue seems to not be fixed.

```
Running` on 64 bit Windows with 0 GB RAM 
Version: v1.12.0-pre.4 (Unstable)2020-01-05 11:07:38: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.ServerMods.BlockBehaviorOmniRotatable.TryPlaceBlock(IWorldAccessor world, IPlayer byPlayer, ItemStack itemstack, BlockSelection blockSel, EnumHandling& handling, String& failureCode)
   at Vintagestory.API.Common.Block.TryPlaceBlock(IWorldAccessor world, IPlayer byPlayer, ItemStack itemstack, BlockSelection blockSel, String& failureCode)
   at _z3DMMSBYq6n0mK1BaVByyhvVDxr._cci56okMlVLqiXklfdN2G85wBtG(BlockSelection , String& )
   at _I4jGwhFKYHOb0WZ1jkJuh5Rbejq._3b886ZJaKstnongKAJfQoE2bjQw(BlockSelection , Block , String& )
   at _I4jGwhFKYHOb0WZ1jkJuh5Rbejq._s3CxKhObZydEo1qd3Qbr2G4ITyJ(Single )
   at _I4jGwhFKYHOb0WZ1jkJuh5Rbejq._DwXApUkpHP34RZdThJGvZGnLxTM(Single )
   at _8yDP7RsLBSfQoXwuzN8uugxzdpi._b0CDbhITKGNLfFZw93fz1HZ9mdA(EnumRenderStage , Single )
   at _z3DMMSBYq6n0mK1BaVByyhvVDxr._b0CDbhITKGNLfFZw93fz1HZ9mdA(EnumRenderStage , Single )
   at _z3DMMSBYq6n0mK1BaVByyhvVDxr._UdDilJv535XMH0Ag2GfQSkpVEqH(Single )
   at _s8LeJZAGp0lBYQdhtI5rm2zr6AK._UdDilJv535XMH0Ag2GfQSkpVEqH(Single )
   at _mIN89BPfhWAYJcBQArYJtNee8Qi._I4oMVeazDR2xhSLC0MMdz9h7m2G(Single )
   at _mIN89BPfhWAYJcBQArYJtNee8Qi._9FyonUPVBnMaoJtPnyFgkqoBExf(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _hG3cjnuXqvBFIftztmAxyKIDzVK._djA1E8LGqTYn45ZuiP3uFxLopvF(_UYatkCgiPh2VvAulJFlAVY8VyYO , String[] )
   at _x6YypWdxqt6nvg5Y8amUBlgFCtR._djA1E8LGqTYn45ZuiP3uFxLopvF(ThreadStart )
-------------------------------
```

**Comment by tyronx** [comment] 2020-01-17 06:37
Unfortunately I'm unable to reproduce this issue. The crash you were getting in pre.4, is that from a newly crafted trapdoor?

**Comment by yoshuamongrain** [comment] 2020-01-19 15:13
I went and checked again, the trapdoors were created in an earlier version and have Placement mode "Only Horizontal".

When I craft new ones the have Placement mode "Auto" and the game does not crash when placing them.

If "Only Horizontal" trapdoors can not (or no longer) be crafted, then I guess this issue is fixed.

**Comment by copygirl** [comment] 2020-01-19 20:29
Can you place newly created trapdoors (that have the "auto" mode) into the crafting grid on their own and does it return another item? Does said block crash when placed?

**Comment by yoshuamongrain** [comment] 2020-01-19 20:49
No, when I place it in the crafting grid there is no other item created.
Also placing them in various configurations and then breaking them does not give a different item.

**Comment by tyronx** [comment] 2020-01-20 11:04
Ok yea, I'll take the freedom to close this. Please just ditch the broken trapdoors, thanks!

**Closed by tyronx** 2020-01-20 11:04 UTC
Labels: status: new, target: survival, type: crash

**Comment by copygirl** [comment] 2020-01-20 12:19
I'm not happy with this outcome. Wouldn't it be possible to add a null check in case people use blocks from the previous version? How are you going to explain this to people who have updated but notice the same crash and report it as a bug?
