### ISSUE TITLE
Stuck after sleeping in trader's bed

### ISSUE THREAD

**Issue by Filigrani** [anegostudios/VintageStory-Issues#2023] opened 2022-07-19 10:01 UTC
**Game Version:** 1.16.5 
**Platform:** Windows
**Modded:** No 
**SP/MP:** Singleplayer

### Description
Stuck after sleeping in trader's bed.

### How to reproduce
1. Find trader.
2. Sleep in bed.
3. Enjoy being stuck.

### Expected behavior
I should not stuck in block after sleeping.

### Screenshots
[Image](https://cdn.discordapp.com/attachments/384944384615120898/998890920852344903/unknown.png)
[Video](https://cdn.discordapp.com/attachments/384944384615120898/998892171388256297/Vintagestory_2022.07.19_-_13.52.03.02.DVR_Trim.mp4)

### Logs
[Server-main](https://cdn.discordapp.com/attachments/384944384615120898/998891448495771688/server-main.txt)
[Client-main](https://cdn.discordapp.com/attachments/384944384615120898/998891448755822652/client-main.txt)

**Comment by Craluminum2413** [comment] 2022-07-19 10:10
Duplicate of #614

**Closed** 2022-07-19 10:10 UTC
Labels: status: new
