### ISSUE TITLE
Arms begin flailing without input

### ISSUE THREAD

**Issue by JadzD2001** [anegostudios/VintageStory-Issues#3824] opened 2024-04-19 16:12 UTC
### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Occasionally while doing some building or mining, I notice my character begins their attack/use animations when there is no mouse input. Swapping tools or swapping to an empty hand does nothing and the character persists to whack away at nothing. I tried using L and R mouse input, entering menus or even using other tools to stop the animation, yet it persists. 

Reloading the world by exiting to the menu has been the fix for me so far.

### How to reproduce

While mining continuously or building continuously, the animation will begin and the arms and character begin moving without input.

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2024-04-19 16:25
Duplicate of #3774

**Closed by Craluminum2413** 2024-04-19 16:25 UTC
Labels: status: new
