### ISSUE TITLE
Incorrect nutrient number in meal in firepit

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#996] opened 2021-06-13 13:32 UTC
**Game Version:** 1.14.10
**Platform:** Windows 10
**Modded:** No

### Description
Playing on TOPTS (1.14.10 too afaik)
Have a meal portion in a bowl with 80 saturation from honey. (it has other components too)
When placed on a block, it shows 80 fruit saturation.
When placed into a firepit (as if to heat it a bit), it shows 0 fruit saturation.

I had similar bug before but was unable to reproduce. Just noticed that sometimes a meal has 0 fruit saturation from honey.

Screenshots attached.

### How to reproduce
1. Make a meat stew: 2 meats, 1 veg, 1 honey. Let it cool down.
2. Take it into a bowl.
3. Place bowl on a block - it shows 80 fruit saturation.
4. Place it into the input, non-fuel slot of firepit - it shows 0 fruit saturation.

### Expected behavior
To have 80 fruit saturation placed anywhere.

### Screenshots

![2021-06-13_16-20-48](https://user-images.githubusercontent.com/25122345/121809276-e4a8dd80-cc64-11eb-8b03-a42a80bcf80d.png)
![2021-06-13_16-20-57](https://user-images.githubusercontent.com/25122345/121809278-e5417400-cc64-11eb-8783-0f8648478005.png)

**Comment by Craluminum2413** [comment] 2021-06-13 13:46
Related to #857

**Comment by copygirl** [comment] 2021-06-13 15:59
Yeah I will close this a duplicate for now. Is the issue still present in the 1.15 pre-releases by the way?

**Closed by copygirl** 2021-06-13 15:59 UTC
Labels: status: duplicate

**Comment by Craluminum2413** [comment] 2021-06-13 16:01
Yes, the issue is still relevant

**Comment by Craluminum2413** [comment] 2021-06-19 12:11
If #857 is closed, then it should too
