### ISSUE TITLE
Items selected in the backpack slots show in on hand and on the player's back still.

### ISSUE THREAD

**Issue by Sonickirbystar** [anegostudios/VintageStory-Issues#4008] opened 2024-08-06 12:29 UTC
### Game Version

v.1.9.8 (Stable)

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Not a major issue effecting gameplay but just a visual bug. Title says how to reproduce and practically it all

### How to reproduce

Items selected in the backpack slots show in on hand and on the player's back still.

### Screenshots

![image](https://github.com/user-attachments/assets/5b47fa22-3320-4bad-ac60-e04216372a48)
![image](https://github.com/user-attachments/assets/e7bd6273-9388-4ac0-a1ab-27c535871dbf)

### Logs

No Logs needed

**Comment by Craluminum2413** [comment] 2024-08-07 08:44
Duplicate of #2418

**Closed by Craluminum2413** 2024-08-07 08:44 UTC
Labels: status: new
