### ISSUE TITLE
Duplicating dry mash using fruitpress

### ISSUE THREAD

**Issue by daddygiggles** [anegostudios/VintageStory-Issues#4544] opened 2024-11-21 16:03 UTC
### Game Version

v1.19.8

### Platform

None

### Modded

None

### SP/MP

Multiplayer

### Description

The fruitpress can duplicate dry mash consistently. Encountered on VS TOPS.

### How to reproduce

1. Add dry mash to an empty fruitpress
2. Remove the dry mash from the fruitpress
3. +1 mash added to player inventory (in survival)

**Comment by Craluminum2413** [comment] 2024-11-21 16:05
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/3868

**Closed as not planned by Craluminum2413** 2024-11-21 16:05 UTC
Labels: status: duplicate
