### ISSUE TITLE
Corpse migrates to surface if mob killed in close space.

### ISSUE THREAD

**Issue by RTHauke** [anegostudios/VintageStory-Issues#364] opened 2020-02-07 15:30 UTC
**Game Version:** 1.12.0.rc1
**Platform:** Linux
**Modded:** No

### Description
If a mob is killed in a tight space, say a 1-wide x 2-deep trench, or a any close space where the corpse object doesn't fit well, the corpse will migrate to the world surface.  I've seen this happen in caves, so it looks like the same issue.  The corpse starts out in the right position, so it's something happening after the object is created in the world.  I've lost corpses and their loot in this way numerous times underground because the corpse disappeared and I couldn't find it.

### How to reproduce
1. Make a 1-wide x 2-deep trench next to a garden to capture rabbits.
2. "Kill the rabbits! Kill the rabbits!"
3. Most of the corpses will migrate to the top of the trench, at the world surface.

### Expected behavior
Do a better bounds check on the corpse object.  If it's accessible, like touching an air or liquid block, don't move it.  Even if it's glitched into a wall, I'd prefer that over loosing the corpse as it migrates away to someplace it can fit.

### Screenshots
Can't access game at the moment, will post one later.

### Logs
No crash to log.

**Comment by tyronx** [comment] 2020-02-16 09:33
I agree this is completely derpy and shouldn't happen. 

(Technical details: The issue with it is that during the death animation, the creatures hitbox is moved to fit of the dead creature pose offset, but the piece of code that does that doesn't do any collision detection, so the creature ends up inside blocks)

**Comment by tyronx** [comment] 2020-02-23 08:54
I worked on this so it might be a bit less derpy in the next release.

**Comment by copygirl** [comment] 2020-02-23 15:01
You can help make sure it works as intended by trying out `1.12.5-rc.1`.

**Comment by Angelnoir** [comment] 2020-02-26 19:21
Since 1.12.5 stable is released you could retest this and confirm whether its fixed or not for you?

**Comment by copygirl** [comment] 2020-02-26 19:45
@Angelnoir Thanks for pointing this out. As far as we know the problem has been addressed, so I'll close it until it is reported as not working. (Or else we'll forget. We can always re-open.)

**Closed by copygirl** 2020-02-26 19:45 UTC
Labels: status: resolved, target: survival, type: bug
