### ISSUE TITLE
Buttons overlapping and text overflow in character creator window.

### ISSUE THREAD

**Issue by tannyl** [anegostudios/VintageStory-Issues#4441] opened 2024-11-05 14:28 UTC
### Game Version

1.20.0-pre.10

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When using a different language with longer words the **Last selection** button in the character creator screen can end up overlapping over the **Show dressed** button.

Also, the character class name box does not support long words. In the image below it should say _Almuemanden_ but the last **n** is cut off.

### How to reproduce

1. Start game
2. Switch to danish
3. Restart game
4. Start game and create new world
5. Look at button and name box in the character creator window.

### Screenshots

![Screenshot from 2024-11-05 15-27-30](https://github.com/user-attachments/assets/85e31ecc-7376-434f-93f9-a2c71f99f10d)
![Screenshot from 2024-11-05 15-27-39](https://github.com/user-attachments/assets/c9a0929c-cb40-427a-8839-e62cb0c33a25)

### Logs

```Log```

**Comment by tannyl** [comment] 2024-11-14 19:57
This is related to issue #4086

**Comment by Craluminum2413** [comment] 2024-11-14 20:14
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4086

**Closed by Craluminum2413** 2024-11-14 20:14 UTC
Labels: status: new, department: code
