### ISSUE TITLE
Unknown, seemingly takes effect when entering a specific door to a room

### ISSUE THREAD

**Issue by CardboardDecoy** [anegostudios/VintageStory-Issues#3308] opened 2023-12-14 04:31 UTC
### Game Version

v1.18.15 (Stable)

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Every time I enter from a specific doorway into my 'kitchen' area the game hard crashes and closes.

### How to reproduce

If I could give you the save you'd just have to take the shortest route into the kitchen. I've even walked around the building and entered the kitchen from other doorways, and can exit out of the problem doorway, but when I walk back in it crashes anyway.

### Logs

Here's Client-main, I pasted the Crash reporter text further down.

13.12.2023 18:34:55 [Notification] Client logger started.
13.12.2023 18:34:55 [Notification] Game Version: v1.18.15 (Stable)
13.12.2023 18:34:57 [Notification] OpenAL Initialized. Available Mono/Stereo Sources: 255/1
13.12.2023 18:34:57 [Notification] Process path: C:\Users\CardboardDecoy\AppData\Roaming\Vintagestory\Vintagestory.exe
13.12.2023 18:34:57 [Notification] Operating System: Windows 10.0.19045.0
13.12.2023 18:34:57 [Notification] CPU Cores: 4
13.12.2023 18:34:57 [Notification] Available RAM: 8150 MB
13.12.2023 18:34:57 [Notification] Graphics Card Vendor: NVIDIA Corporation
13.12.2023 18:34:57 [Notification] Graphics Card Version: 3.3.0 NVIDIA 536.23
13.12.2023 18:34:57 [Notification] Graphics Card Renderer: NVIDIA GeForce GTX 1070/PCIe/SSE2
13.12.2023 18:34:57 [Notification] Graphics Card ShadingLanguageVersion: 3.30 NVIDIA via Cg compiler
13.12.2023 18:34:57 [Notification] GL.MaxVertexUniformComponents: 4096
13.12.2023 18:34:57 [Notification] GL.MaxUniformBlockSize: 65536
13.12.2023 18:34:57 [Notification] Cairo Graphics Version: 1.17.3
13.12.2023 18:34:57 [Notification] OpenAL Version: 1.1 ALSOFT 1.23.0
13.12.2023 18:34:57 [Notification] C# Framework: .net 7.0.7
13.12.2023 18:34:57 [Notification] Zstd Version: 1.5.5
13.12.2023 18:34:58 [Notification] Start discovering assets
13.12.2023 18:34:58 [Notification] Found 23 base assets in category lang
13.12.2023 18:34:58 [Notification] Found 0 base assets in category patches
13.12.2023 18:34:58 [Notification] Found 22 base assets in category config
13.12.2023 18:34:58 [Notification] Found 0 base assets in category worldproperties
13.12.2023 18:34:58 [Notification] Found 46 base assets in category sounds
13.12.2023 18:34:58 [Notification] Found 97 base assets in category shapes
13.12.2023 18:34:58 [Notification] Found 72 base assets in category shaders
13.12.2023 18:34:58 [Notification] Found 16 base assets in category shaderincludes
13.12.2023 18:34:58 [Notification] Found 131 base assets in category textures
13.12.2023 18:34:58 [Notification] Found 4 base assets in category music
13.12.2023 18:34:58 [Notification] Found 0 base assets in category dialog
13.12.2023 18:34:58 [Notification] Found 411 base assets in total
13.12.2023 18:34:58 [Notification] Loading sounds
13.12.2023 18:34:58 [Notification] Sounds loaded
13.12.2023 18:34:58 [Notification] (Re-)loaded frame buffers
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass .
13.12.2023 18:34:58 [Notification] Begin loading shaders
13.12.2023 18:34:58 [Notification] Load shaders now
13.12.2023 18:34:58 [Notification] Loading shaders...
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass standard.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass particlescube.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass particlesquad.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass sky.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass nightsky.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass woittest.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass transparentcompose.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass debugdepthbuffer.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass helditem.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass chunkopaque.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass chunkliquid.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass decals.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass final.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass gui.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass blur.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass chunktransparent.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass findbright.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass chunktopsoil.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass godrays.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass autocamera.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass blockhighlights.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass wireframe.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass entityanimated.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass luma.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass blit.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass particlesquad2d.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass shadowmapentityanimated.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass shadowmapgeneric.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass texture2texture.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass celestialobject.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass guitopsoil.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass colorgrade.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass guigear.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass ssao.
13.12.2023 18:34:58 [Notification] Loaded Shaderprogramm for render pass bilateralblur.
13.12.2023 18:34:59 [Notification] Cached session key is valid, validating with server
13.12.2023 18:35:00 [Notification] Server validation response: Good
13.12.2023 18:35:00 [Notification] Will search the following paths for mods:
13.12.2023 18:35:00 [Notification]     C:\Users\CardboardDecoy\AppData\Roaming\Vintagestory\Mods
13.12.2023 18:35:00 [Notification]     C:\Users\CardboardDecoy\AppData\Roaming\VintagestoryData\Mods
13.12.2023 18:35:07 [Notification] Initialized GUI Manager
13.12.2023 18:35:07 [Notification] Initialized Server Connection
13.12.2023 18:35:07 [Notification] Server args parsed
13.12.2023 18:35:07 [Notification] Server main instantiated
13.12.2023 18:35:21 [Notification] Processed server identification
13.12.2023 18:35:21 [Notification] Map initialized
13.12.2023 18:35:21 [Notification] Received server assets
13.12.2023 18:35:21 [Notification] Loading and pre-starting client side mods...
13.12.2023 18:35:21 [Notification] Will search the following paths for mods:
13.12.2023 18:35:21 [Notification]     C:\Users\CardboardDecoy\AppData\Roaming\Vintagestory\Mods
13.12.2023 18:35:21 [Notification]     C:\Users\CardboardDecoy\AppData\Roaming\VintagestoryData\Mods
13.12.2023 18:35:21 [Notification] Found 3 mods (0 disabled)
13.12.2023 18:35:21 [Notification] Mods, sorted by dependency: game, creative, survival
13.12.2023 18:35:21 [Notification] Instantiated 101 mod systems from 3 enabled mods
13.12.2023 18:35:21 [Notification] Done loading and pre-starting client side mods.
13.12.2023 18:35:21 [Notification] External Origins in load order: modorigin@C:\Users\CardboardDecoy\AppData\Roaming\Vintagestory\assets\creative\, modorigin@C:\Users\CardboardDecoy\AppData\Roaming\Vintagestory\assets\survival\
13.12.2023 18:35:21 [Notification] Found 0 external assets in category lang
13.12.2023 18:35:21 [Notification] Found 9 external assets in category patches
13.12.2023 18:35:21 [Notification] Found 54 external assets in category config
13.12.2023 18:35:21 [Notification] Found 25 external assets in category worldproperties
13.12.2023 18:35:21 [Notification] Found 348 external assets in category sounds
13.12.2023 18:35:21 [Notification] Found 3179 external assets in category shapes
13.12.2023 18:35:21 [Notification] Found 13 external assets in category shaders
13.12.2023 18:35:21 [Notification] Found 0 external assets in category shaderincludes
13.12.2023 18:35:22 [Notification] Found 5243 external assets in category textures
13.12.2023 18:35:22 [Notification] Found 67 external assets in category music
13.12.2023 18:35:22 [Notification] Found 18 external assets in category dialog
13.12.2023 18:35:22 [Notification] Found 0 external assets in category compatibility
13.12.2023 18:35:22 [Notification] Reloaded lang file now with mod assets
13.12.2023 18:35:22 [Notification] Compatibility lib: 0 assets added, 0 assets replaced.
13.12.2023 18:35:22 [Notification] JsonPatch Loader: 24 patches total, successfully applied 6 patches, unmet conditions on 8 patches, no issues
13.12.2023 18:35:23 [Notification] Received 3040 item types from server
13.12.2023 18:35:23 [Notification] Loaded 9252 block types from server
13.12.2023 18:35:23 [Notification] Reloaded sounds, now with mod assets
13.12.2023 18:35:23 [Notification] Composed 1 4096x4096 entities texture atlases from 384 textures
13.12.2023 18:35:30 [Notification] Composed 1 4096x4096 items texture atlases from 1593 textures
13.12.2023 18:35:31 [Notification] Server launched
13.12.2023 18:35:31 [Notification] Collected 1802 shapes to tesselate.
13.12.2023 18:35:37 [Notification] Composed 1 4096x4096 blocks texture atlases from 4310 textures
13.12.2023 18:35:37 [Notification] Server assets loaded
13.12.2023 18:35:39 [Notification] Blocks tesselated
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass anvilworkitem.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass lines.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass aurora.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass rift.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass sleepoverlay.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass machinegear.
13.12.2023 18:35:40 [Notification] Started 64 systems on Client:
13.12.2023 18:35:40 [Notification]     Mod 'VSEssentials.dll' (game):
13.12.2023 18:35:40 [Notification]         Vintagestory.ServerMods.Core
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.EntityPartitioning
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.ErrorReporter
13.12.2023 18:35:40 [Notification]         Vintagestory.ServerMods.ModCompatiblityUtil
13.12.2023 18:35:40 [Notification]         Vintagestory.ServerMods.NoObf.ModJsonPatchLoader
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.ModSystemDormancyStateChecker
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.ModSystemItemRendererOptimizer
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.FallingBlockParticlesModSystem
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.CharacterExtraDialogs
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.EntityNameTagRendererRegistry
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.POIRegistry
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.RoomRegistry
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.WeatherSystemCommands
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.WeatherSystemClient
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.WorldMapManager
13.12.2023 18:35:40 [Notification]         Vintagestory.ServerMods.LoadColorMaps
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.ClothManager
13.12.2023 18:35:40 [Notification]     Mod 'VSSurvivalMod.dll' (survival):
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.ModSystemControlPoints
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.SurvivalCoreSystem
13.12.2023 18:35:40 [Notification]         Vintagestory.Client.NoObf.ModSystemBossHealthBars
13.12.2023 18:35:40 [Notification]         Vintagestory.ServerMods.DebugSystem
13.12.2023 18:35:40 [Notification]         Vintagestory.ServerMods.UpgradeTasks
13.12.2023 18:35:40 [Notification]         Vintagestory.ServerMods.ModSystemDetailModeSync
13.12.2023 18:35:40 [Notification]         Vintagestory.ServerMods.ModSystemTiledDungeonGenerator
13.12.2023 18:35:40 [Notification]         Vintagestory.ServerMods.GenFromHeightmap
13.12.2023 18:35:40 [Notification]         Vintagestory.ServerMods.GenMaps
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.MyceliumSystem
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.ModSystemSupportBeamPlacer
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.ModSystemCatchCreature
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.ModSystemGliding
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.ModSystemMeasuringRope
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.ScreenshakeToClientModSystem
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.ResoArchivesSpawnConditions
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.ModSystemAuction
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.ModSystemBlockReinforcement
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.Core
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.ModSystemBoatingSound
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.CharacterSystem
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.MealMeshCache
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.DialogueSystem
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.FruitingSystem
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.ModSystemHandbook
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.ModSystemTutorial
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.ModSystemNightVision
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.ModJournal
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.LiquidItemStackRenderer
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.ModSystemStructureLocator
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.ModLootRandomizer
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.MicroBlockModelCache
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.ModSystemRifts
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.ModSystemRiftWeather
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.ModSleeping
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.TeleporterManager
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.ModTemperature
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.SystemTemporalStability
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.TemporalStabilityEffects
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.ModSystemWearableStats
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.ModSystemEditableBook
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.Mechanics.MechanicalPowerMod
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.TradeHandbookInfo
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.RecipeRegistrySystem
13.12.2023 18:35:40 [Notification]         Vintagestory.GameContent.TraderOutfits
13.12.2023 18:35:40 [Notification]     Mod 'VSCreativeMod.dll' (creative):
13.12.2023 18:35:40 [Notification]         Vintagestory.ServerMods.Core
13.12.2023 18:35:40 [Notification]         Vintagestory.ServerMods.WorldEdit.WorldEdit
13.12.2023 18:35:40 [Notification] Loading shaders...
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass standard.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass particlescube.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass particlesquad.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass sky.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass nightsky.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass woittest.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass transparentcompose.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass debugdepthbuffer.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass helditem.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass chunkopaque.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass chunkliquid.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass decals.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass final.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass gui.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass blur.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass chunktransparent.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass findbright.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass chunktopsoil.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass godrays.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass autocamera.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass blockhighlights.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass wireframe.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass entityanimated.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass luma.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass blit.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass particlesquad2d.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass shadowmapentityanimated.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass shadowmapgeneric.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass texture2texture.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass celestialobject.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass guitopsoil.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass colorgrade.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass guigear.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass ssao.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass bilateralblur.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass anvilworkitem.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass lines.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass aurora.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass rift.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass sleepoverlay.
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass machinegear.
13.12.2023 18:35:40 [Notification] Reloaded shaders now with mod assets
13.12.2023 18:35:40 [Notification] Received level init
13.12.2023 18:35:40 [Notification] Loaded Shaderprogramm for render pass instanced.
13.12.2023 18:35:40 [Notification] Loading world map cache db...
13.12.2023 18:35:41 [Notification] Initialized Music Engine
13.12.2023 18:35:41 [Notification] Texture size is 32 so decal atlas size of 128x128 should suffice
13.12.2023 18:35:42 [Notification] Received level finalize
13.12.2023 18:35:42 [Notification] Loaded Shaderprogramm for render pass clouds.
13.12.2023 18:35:43 [Notification] ===============================================================
13.12.2023 18:35:43 [Notification] (^_^) No issues captured during startup
13.12.2023 18:35:43 [Notification] ===============================================================
13.12.2023 18:35:51 [Fatal] Game Version: v1.18.15 (Stable)
12/13/2023 6:35:51 PM: Critical error occurred
Loaded Mods: game@1.18.15, creative@1.18.15, survival@1.18.15
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.VanillaCookingRecipeNames.GetNameForIngredients(IWorldAccessor worldForResolve, String recipeCode, ItemStack[] stacks) in VSSurvivalMod\Systems\Cooking\CookingRecipe.cs:line 238
   at Vintagestory.GameContent.CookingRecipe.GetOutputName(IWorldAccessor worldForResolve, ItemStack[] inputStacks) in VSSurvivalMod\Systems\Cooking\CookingRecipe.cs:line 482
   at Vintagestory.GameContent.BlockCookedContainerBase.GetContainedInfo(ItemSlot inSlot) in VSSurvivalMod\Block\BlockCookedContainerBase.cs:line 337
   at Vintagestory.GameContent.BlockEntityGroundStorage.getContentSummary() in VSSurvivalMod\BlockEntity\BEGroundStorage.cs:line 964
   at Vintagestory.GameContent.BlockEntityGroundStorage.GetBlockName() in VSSurvivalMod\BlockEntity\BEGroundStorage.cs:line 911
   at Vintagestory.GameContent.BlockGroundStorage.GetPlacedBlockName(IWorldAccessor world, BlockPos pos) in VSSurvivalMod\Block\BlockGroundStorage.cs:line 344
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.ComposeBlockInfoHud() in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockAndEntityInfo.cs:line 56
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.BlockInView() in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockAndEntityInfo.cs:line 190
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.Every15ms(Single dt) in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockAndEntityInfo.cs:line 156
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 59
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 711
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
Crash written to file at "C:\Users\CardboardDecoy\AppData\Roaming\VintagestoryData\Logs\client-crash.txt"

13.12.2023 18:35:58 [Notification] Finished fully loading sounds (async)

**CRASH REPORTER TEXT BELOW THIS LINE**

Running on 64 bit Windows with 8150 MB RAM
Game Version: v1.18.15 (Stable)
12/13/2023 6:35:51 PM: Critical error occurred
Loaded Mods: game@1.18.15, creative@1.18.15, survival@1.18.15
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.VanillaCookingRecipeNames.GetNameForIngredients(IWorldAccessor worldForResolve, String recipeCode, ItemStack[] stacks) in VSSurvivalMod\Systems\Cooking\CookingRecipe.cs:line 238
   at Vintagestory.GameContent.CookingRecipe.GetOutputName(IWorldAccessor worldForResolve, ItemStack[] inputStacks) in VSSurvivalMod\Systems\Cooking\CookingRecipe.cs:line 482
   at Vintagestory.GameContent.BlockCookedContainerBase.GetContainedInfo(ItemSlot inSlot) in VSSurvivalMod\Block\BlockCookedContainerBase.cs:line 337
   at Vintagestory.GameContent.BlockEntityGroundStorage.getContentSummary() in VSSurvivalMod\BlockEntity\BEGroundStorage.cs:line 964
   at Vintagestory.GameContent.BlockEntityGroundStorage.GetBlockName() in VSSurvivalMod\BlockEntity\BEGroundStorage.cs:line 911
   at Vintagestory.GameContent.BlockGroundStorage.GetPlacedBlockName(IWorldAccessor world, BlockPos pos) in VSSurvivalMod\Block\BlockGroundStorage.cs:line 344
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.ComposeBlockInfoHud() in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockAndEntityInfo.cs:line 56
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.BlockInView() in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockAndEntityInfo.cs:line 190
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.Every15ms(Single dt) in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockAndEntityInfo.cs:line 156
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 59
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 711
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 12/8/2023 1:28:34 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2007150627803250050, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5CBA.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_278f48a0-2318-44a5-8728-75771243c60f

Analysis symbol: 
Rechecking for solution: 0
Report Id: 5c78e3f7-f5b9-49e2-95fa-1e72509c17f2
Report Status: 268566528
Hashed bucket: 38dd2bbe130a69d3fbdad4dc94ea3d82
Cab Guid: 0 }
--------------
{ TimeGenerated = 12/8/2023 1:28:34 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_278f48a0-2318-44a5-8728-75771243c60f

Analysis symbol: 
Rechecking for solution: 0
Report Id: 5c78e3f7-f5b9-49e2-95fa-1e72509c17f2
Report Status: 131076
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 12/8/2023 1:28:33 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.15.0, time stamp: 0x64e841c5
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x393c
Faulting application start time: 0x01da2a1d6717015b
Faulting application path: C:\Users\CardboardDecoy\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\CardboardDecoy\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 5c78e3f7-f5b9-49e2-95fa-1e72509c17f2
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment] 2024-02-15 08:30
Duplicate of #3210

**Closed by Craluminum2413** 2024-02-15 08:30 UTC
Labels: status: new
