### ISSUE TITLE
IndexOutOfRangeException in Cairo.GaussianBlur

### ISSUE THREAD

**Issue by xCoiotex** [anegostudios/VintageStory-Issues#587] opened 2020-09-18 21:19 UTC
```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.13.4 (Stable)18/09/2020 18:14:33: Critical error occurred
System.AggregateException: Um ou mais erros. ---> System.AggregateException: Um ou mais erros. ---> System.IndexOutOfRangeException: O índice estava fora dos limites da matriz.
   em Cairo.GaussianBlur.<>c__DisplayClass14_0.<boxBlurT_4>b__0(Int32 i)
   em System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   em System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   em System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- Fim do rastreamento de pilha de exceções internas ---
   em System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   em System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   em System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   em System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body)
   em Cairo.GaussianBlur.boxBlurT_4(Byte[] source, Byte[] dest, Int32 w, Int32 h, Int32 r)
   em Cairo.GaussianBlur.gaussBlur_4(Byte[] source, Byte[] dest, Double r)
   em System.Threading.Tasks.Task.Execute()
   --- Fim do rastreamento de pilha de exceções internas ---
   em System.Threading.Tasks.Task.FastWaitAll(Task[] tasks)
   em System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   em Cairo.GaussianBlur.Process(Double radial, Boolean blurAlpha)
   em Cairo.SurfaceTransformBlur.Blur(ImageSurface surface, Double range, Int32 xStart, Int32 yStart, Int32 xEnd, Int32 yEnd, Boolean blurAlpha)
   em Cairo.SurfaceTransformBlur.Blur(ImageSurface surface, Double range, Boolean blurAlpha)
   em Vintagestory.API.Client.GuiElementItemstackInfo.Recompose()
   em Vintagestory.API.Client.GuiElementItemstackInfo.SetSourceSlot(ItemSlot nowSlot)
   em Vintagestory.API.Client.ItemstackComponentBase.RenderItemstackTooltip(ItemSlot slot, Double renderX, Double renderY, Single dt)
   em Vintagestory.API.Client.SlideshowItemstackTextComponent.RenderInteractiveElements(Single deltaTime, Double renderX, Double renderY)
   em Vintagestory.API.Client.GuiElementRichtext.RenderInteractiveElements(Single deltaTime)
   em Vintagestory.API.Client.GuiComposer.Render(Single deltaTime)
   em Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime)
   em Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime)
   em Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   em Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   em Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   em _VtIDI6oYFpyEcQSZBFso9UVxS9aA._toICAyZ9EYSaLsmD4KTuQWUbqjP(Single )
   em _LSAAgZhw31Rqs2is6nnojfZBbQC._4BykKOCicJqCBHpyWIgTmxWrTrg(Single )
   em _LSAAgZhw31Rqs2is6nnojfZBbQC._6XmOxKoTYrFLRCGd58p58XW43nD(Single )
   em Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   em System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   em OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   em OpenTK.GameWindow.DispatchRenderFrame()
   em OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   em _lYLQLGyldvbDG9rPQyiRVeIqQVp._EEzpApWBQHtHR4iMJabXK2wDvlA(_ex0VSgRAdtsvhANmJHZHaf9ATWt , String[] )
   em _IcGByoJhapvESnm6vaOawAHbkeU._EEzpApWBQHtHR4iMJabXK2wDvlA(ThreadStart )
---> (Exceção Interna N° 0) System.AggregateException: Um ou mais erros. ---> System.IndexOutOfRangeException: O índice estava fora dos limites da matriz.
   em Cairo.GaussianBlur.<>c__DisplayClass14_0.<boxBlurT_4>b__0(Int32 i)
   em System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   em System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   em System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- Fim do rastreamento de pilha de exceções internas ---
   em System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   em System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   em System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   em System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body)
   em Cairo.GaussianBlur.boxBlurT_4(Byte[] source, Byte[] dest, Int32 w, Int32 h, Int32 r)
   em Cairo.GaussianBlur.gaussBlur_4(Byte[] source, Byte[] dest, Double r)
   em System.Threading.Tasks.Task.Execute()
---> (Exceção Interna N° 0) System.IndexOutOfRangeException: O índice estava fora dos limites da matriz.
   em Cairo.GaussianBlur.<>c__DisplayClass14_0.<boxBlurT_4>b__0(Int32 i)
   em System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   em System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   em System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
<---

-------------------------------
System.AggregateException: Um ou mais erros. ---> System.IndexOutOfRangeException: O índice estava fora dos limites da matriz.
   em Cairo.GaussianBlur.<>c__DisplayClass14_0.<boxBlurT_4>b__0(Int32 i)
   em System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   em System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   em System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- Fim do rastreamento de pilha de exceções internas ---
   em System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   em System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   em System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   em System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body)
   em Cairo.GaussianBlur.boxBlurT_4(Byte[] source, Byte[] dest, Int32 w, Int32 h, Int32 r)
   em Cairo.GaussianBlur.gaussBlur_4(Byte[] source, Byte[] dest, Double r)
   em System.Threading.Tasks.Task.Execute()
---> (Exceção Interna N° 0) System.IndexOutOfRangeException: O índice estava fora dos limites da matriz.
   em Cairo.GaussianBlur.<>c__DisplayClass14_0.<boxBlurT_4>b__0(Int32 i)
   em System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   em System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   em System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

-------------------------------
System.IndexOutOfRangeException: O índice estava fora dos limites da matriz.
   em Cairo.GaussianBlur.<>c__DisplayClass14_0.<boxBlurT_4>b__0(Int32 i)
   em System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   em System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   em System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 18/09/2020 18:14:33, Site = , Source = .NET Runtime, Message = Aplicativo: Vintagestory.exe
Versão do Framework: v4.0.30319
Descrição: O processo foi terminado devido a uma exceção sem tratamento.
Informações da Exceção: System.IndexOutOfRangeException
   em Cairo.GaussianBlur+<>c__DisplayClass14_0.<boxBlurT_4>b__0(Int32)
   em System.Threading.Tasks.Parallel+<>c__DisplayClass17_0`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<ForWorker>b__1()
   em System.Threading.Tasks.Task.InnerInvokeWithArg(System.Threading.Tasks.Task)
   em System.Threading.Tasks.Task+<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(System.Object)

Informações da Exceção: System.AggregateException
   em System.Threading.Tasks.Task.ThrowIfExceptional(Boolean)
   em System.Threading.Tasks.Task.Wait(Int32, System.Threading.CancellationToken)
   em System.Threading.Tasks.Parallel.ForWorker[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Int32, Int32, System.Threading.Tasks.ParallelOptions, System.Action`1<Int32>, System.Action`2<Int32,System.Threading.Tasks.ParallelLoopState>, System.Func`4<Int32,System.Threading.Tasks.ParallelLoopState,System.__Canon,System.__Canon>, System.Func`1<System.__Canon>, System.Action`1<System.__Canon>)
   em System.Threading.Tasks.Parallel.For(Int32, Int32, System.Threading.Tasks.ParallelOptions, System.Action`1<Int32>)
   em Cairo.GaussianBlur.boxBlurT_4(Byte[], Byte[], Int32, Int32, Int32)
   em Cairo.GaussianBlur.gaussBlur_4(Byte[], Byte[], Double)
   em System.Threading.Tasks.Task.Execute()

Informações da Exceção: System.AggregateException
   em System.Threading.Tasks.Task.FastWaitAll(System.Threading.Tasks.Task[])
   em System.Threading.Tasks.Parallel.Invoke(System.Threading.Tasks.ParallelOptions, System.Action[])
   em Cairo.GaussianBlur.Process(Double, Boolean)
   em Cairo.SurfaceTransformBlur.Blur(Cairo.ImageSurface, Double, Int32, Int32, Int32, Int32, Boolean)
   em Cairo.SurfaceTransformBlur.Blur(Cairo.ImageSurface, Double, Boolean)
   em Vintagestory.API.Client.GuiElementItemstackInfo.Recompose()
   em Vintagestory.API.Client.GuiElementItemstackInfo.SetSourceSlot(Vintagestory.API.Common.ItemSlot)
   em Vintagestory.API.Client.ItemstackComponentBase.RenderItemstackTooltip(Vintagestory.API.Common.ItemSlot, Double, Double, Single)
   em Vintagestory.API.Client.SlideshowItemstackTextComponent.RenderInteractiveElements(Single, Double, Double)
   em Vintagestory.API.Client.GuiElementRichtext.RenderInteractiveElements(Single)
   em Vintagestory.API.Client.GuiComposer.Render(Single)
   em Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single)
   em Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single)
   em Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(Vintagestory.API.Client.EnumRenderStage, Single)
   em Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(Vintagestory.API.Client.EnumRenderStage, Single)
   em Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single)
   em _VtIDI6oYFpyEcQSZBFso9UVxS9aA._toICAyZ9EYSaLsmD4KTuQWUbqjP(Single)
   em _LSAAgZhw31Rqs2is6nnojfZBbQC._4BykKOCicJqCBHpyWIgTmxWrTrg(Single)
   em _LSAAgZhw31Rqs2is6nnojfZBbQC._6XmOxKoTYrFLRCGd58p58XW43nD(Single)
   em Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(System.Object, OpenTK.FrameEventArgs)
   em System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   em OpenTK.GameWindow.RaiseRenderFrame(Double, Double ByRef)
   em OpenTK.GameWindow.DispatchRenderFrame()
   em OpenTK.GameWindow.Run(Double, Double)
   em _lYLQLGyldvbDG9rPQyiRVeIqQVp._EEzpApWBQHtHR4iMJabXK2wDvlA(_ex0VSgRAdtsvhANmJHZHaf9ATWt, System.String[])
   em _IcGByoJhapvESnm6vaOawAHbkeU._EEzpApWBQHtHR4iMJabXK2wDvlA(System.Threading.ThreadStart)

 }
```

**Comment by tyronx** [comment] 2020-09-24 12:18
Thanks for the report, could you give me some detail on when this crash happens and is it reproducible?

**Comment by xCoiotex** [comment] 2020-09-24 12:19
Hello, yeah it happens sometimes, i'll play more to see if I get another one

**Comment by copygirl** [comment] 2020-11-09 06:42
@xCoiotex Other than the game crashing, does anything notable happen around the time when you crash? I have a small hunch it could have something to do with the window size being changed, going in/out of fullscreen.

**Comment by xCoiotex** [comment] 2020-11-09 13:39
well this was waaay before I formated my pc, I'm still having issues after formating my pc, don't know if it is the same crash

I Do have 2 monitors, one for actual playing and the other for stream/chat

I have a amd 290x sapphire 4G with latest drivers, windows 10 - 20H4
There are 2 things that I'm suspicious of, my memory and m2 ssd is not compatible with my mobo, but still runs some of other games fine, until I have some random bsod related to KERNEL-POWER or KernelBase.dll , something about .NET runtime

I have no idea how to fix this random crashes related to kernelbase.dll and .net runtime

**Comment by xCoiotex** [comment] 2020-11-09 13:45
mobo x570
ssd hp ex900
ram: 16x2 Corsair CM4X16GC3200C16K2E-CN

**Comment by copygirl** [comment] 2020-11-09 14:19
If you're the only one with this issue - and so far I've not seen this being reported by anyone else - I'm wondering whether it could be an issue that has to do with your hardware specifically. I'm not that great at debugging issues remotely. The only thing that comes to mind might be seeing if your RAM is good. Perhaps you could test your computer's RAM?

Perhaps there is / could be an option to turn the blur off. I'm not sure on top of my head what it is used for.
Either way, @tyronx was wondering whether this could be reproduced, and you said this happens about every 10 minutes, so he might be able to see what he can do.

**Comment by xCoiotex** [comment] 2020-11-10 13:47
well I was trying yesterday to resolve this, I've formated the pc again, and did a lot of stuff trying to remove/update the .net framworks

The error persists in the this framework: Framework: v4.0.30319 .net Runtime 1026
I'm trying to find a solution, two people with similar problem in different applications seems to solves this by replacing the cpu, the problem is, I can't understand how to cpu is related to this specific problem, it's a ryzen 5 3600, bought last year at the launch...

I've tried to play this another game that had issues with drivers, Scrap mechanic, played for a straight hour without any problem

Some foruns says that problem is with the game, but before formating this wasn't happening

I just formated because a youtuber said that the windows 20h2 update needed a fresh install..

Also the memories are okay

I'm really struggling to find a solution, I hope I don't need to replace the CPU since I can play other games without problems

Also, thanks a lot for helping me with this

**Comment by copygirl** [comment] 2020-11-10 15:56
Microsoft's versioning can be very weird so not sure if your ".NET 4.0.something" is what you need. Could you see if you can install [.NET 4.7](https://www.microsoft.com/en-US/download/details.aspx?id=55167)? Unsure if this will resolve the issue but it can't hurt.

**Comment by xCoiotex** [comment] 2020-11-10 17:39
Well I've this .net 4.7 and other versions too but it says: The .Net Framework 4.7 can't be installed because a superior one is already installed in your computer

![image](https://user-images.githubusercontent.com/23199846/98710247-2afe2d00-2362-11eb-9084-76791be22c77.png)

I think I have the 4.8 net

![image](https://user-images.githubusercontent.com/23199846/98710505-7f091180-2362-11eb-8fba-ed02263f8354.png)

Also I saw somewhere that .net is doing a .net conference today to launch the 5 version... don't know if this would resolve if launched thought

**Comment by copygirl** [comment] 2020-11-10 18:32
Looks like it's not an issue with the .NET version, then.

**Comment by xCoiotex** [comment] 2020-11-10 19:02
got another one longer on 

App: Vintagestory.exe
Version of Framework: v4.0.30319

System.IndexOutOfRangeException
   em Cairo.GaussianBlur+<>c__DisplayClass14_0.<boxBlurT_4>b__0(Int32)
   em System.Threading.Tasks.Parallel+<>c__DisplayClass17_0`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<ForWorker>b__1()
   em System.Threading.Tasks.Task.InnerInvokeWithArg(System.Threading.Tasks.Task)
   em System.Threading.Tasks.Task+<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(System.Object)

Informações da Exceção: System.AggregateException
   em System.Threading.Tasks.Task.ThrowIfExceptional(Boolean)
   em System.Threading.Tasks.Task.Wait(Int32, System.Threading.CancellationToken)
   em System.Threading.Tasks.Parallel.ForWorker[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Int32, Int32, System.Threading.Tasks.ParallelOptions, System.Action`1<Int32>, System.Action`2<Int32,System.Threading.Tasks.ParallelLoopState>, System.Func`4<Int32,System.Threading.Tasks.ParallelLoopState,System.__Canon,System.__Canon>, System.Func`1<System.__Canon>, System.Action`1<System.__Canon>)
   em System.Threading.Tasks.Parallel.For(Int32, Int32, System.Threading.Tasks.ParallelOptions, System.Action`1<Int32>)
   em Cairo.GaussianBlur.boxBlurT_4(Byte[], Byte[], Int32, Int32, Int32)
   em Cairo.GaussianBlur.gaussBlur_4(Byte[], Byte[], Double)
   em System.Threading.Tasks.Task.Execute()

Informações da Exceção: System.AggregateException
   em System.Threading.Tasks.Task.FastWaitAll(System.Threading.Tasks.Task[])
   em System.Threading.Tasks.Parallel.Invoke(System.Threading.Tasks.ParallelOptions, System.Action[])
   em Cairo.GaussianBlur.Process(Double, Boolean)
   em Cairo.SurfaceTransformBlur.Blur(Cairo.ImageSurface, Double, Int32, Int32, Int32, Int32, Boolean)
   em Vintagestory.API.Client.GuiElementDialogBackground.ComposeElements(Cairo.Context, Cairo.ImageSurface)
   em Vintagestory.API.Client.GuiComposer.Compose(Boolean)
   em Vintagestory.Client.NoObf.GuiDialogInventory.ComposeCreativeInvDialog()
   em Vintagestory.Client.NoObf.GuiDialogInventory.ComposeGuis(Boolean)
   em Vintagestory.Client.NoObf.GuiDialogInventory.OnGuiOpened()
   em Vintagestory.API.Client.GuiDialog.TryOpen()
   em Vintagestory.API.Client.GuiDialog.OnKeyCombinationToggle(Vintagestory.API.Client.KeyCombination)
   em _yr9yuLESIXbmUAJtjZWuynSpQGC._3UK5YbcwN9zkAuIe8DoiykUGBhJ(Vintagestory.API.Client.KeyEvent, Vintagestory.API.Common.IWorldAccessor, Vintagestory.API.Common.IPlayer, Boolean, Boolean, Boolean)
   em Vintagestory.Client.NoObf.ClientMain.OnKeyDown(Vintagestory.API.Client.KeyEvent)
   em Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(System.Object, OpenTK.Input.KeyboardKeyEventArgs)
   em System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   em System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   em OpenTK.Platform.NativeWindowBase.OnKeyDown(OpenTK.Input.Key, Boolean)
   em OpenTK.Platform.Windows.WinGLNative.HandleKeyboard(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   em OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   em OpenTK.Platform.Windows.Functions.DispatchMessage(OpenTK.Platform.Windows.MSG ByRef)
   em OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   em OpenTK.GameWindow.Run(Double, Double)
   em _lYLQLGyldvbDG9rPQyiRVeIqQVp._EEzpApWBQHtHR4iMJabXK2wDvlA(_ex0VSgRAdtsvhANmJHZHaf9ATWt, System.String[])
   em _IcGByoJhapvESnm6vaOawAHbkeU._EEzpApWBQHtHR4iMJabXK2wDvlA(System.Threading.ThreadStart)

**Comment by xCoiotex** [comment] 2020-11-11 01:47
> Looks like it's not an issue with the .NET version, then.

Maybe it's not something to do with .net, but what it could be? if it's hardware how do I get a diagnost?

also don't know if this is related I'm also having this specific BSOD: Kernel-power 41 (63)
I'm sure that this bsod is related to hardware, it happens something while playing vintage story

**Comment by copygirl** [comment] 2020-11-11 02:15
For now, with my limited debugging knowledge, I've exhausted all my ideas. Maybe @tyronx can build a custom version of the game to find out the value and range that it falls outside of, to maybe get a better understanding of the issue..?

**Comment by xCoiotex** [comment] 2020-11-11 02:24
I'm also trying to get help with the microsoft support and some brazilians forums about hardware and bluescreens

**Comment by tyronx** [comment] 2020-11-12 14:43
Thanks for the report. This is probably fixed in pre.8. 

Technical info: Apart from above crash, the paralleism part of the blur algorithm seems completely out of place there. It's not meant for CPU heavy software, because sometimes it performs extremely slow, presumably because there's currently no free thread in the thread pool so it locks the main thread until done. I've rewrote it into a tighter, more optimized single threaded operation and it actually perform faster even in idle conditions now.

**Closed by tyronx** 2020-11-12 14:43 UTC
Labels: status: incomplete, target: engine, type: crash
