### ISSUE TITLE
Chat drops first character after starting to type (possibly only when chat is rebound)

### ISSUE THREAD

**Issue by MikeHollisJr2021** [anegostudios/VintageStory-Issues#3337] opened 2023-12-25 19:08 UTC
### Game Version

1.19.0rc2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

I don't know if this is a problem on the default control scheme or not, but I regularly rebind chat to <ENTER>  The issue is about 70% of the time when I press enter to begin chatting, the next keypress does not register. 

### How to reproduce

Rebind Chat to <ENTER> try typing a few lines in multiplayer

### Screenshots

![Hey Everyone](https://github.com/anegostudios/VintageStory-Issues/assets/91743912/decb7fab-1eab-4689-83a0-c7fc378f5bed)

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2023-12-28 14:12
Duplicate of #3208

**Closed by Craluminum2413** 2023-12-28 14:12 UTC
Labels: status: new
