### ISSUE TITLE
Branchy leaves turn grass to barren underneath

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#169] opened 2018-08-01 17:56 UTC
1.6 rc1, PTS.

Branchy leaves blocks  block "sky access" for grass blocks and they turn into barren ones, making forests, parks and alleys less beautiful.
As soon as destroy them, barren turns into grass under them.

![2018-08-01_20-52-25](https://user-images.githubusercontent.com/25122345/43539254-11b39828-95cd-11e8-92e0-d56f979b20e0.png)

![2018-08-01_20-52-31](https://user-images.githubusercontent.com/25122345/43539255-11d6c942-95cd-11e8-86e9-22c4df55a909.png)

**Comment by copygirl** [comment] 2018-08-01 17:59
Marking this for `1.6` milestone because it was likely caused by recent changes to leaves.

**Comment by Heptagon-ru** [comment] 2018-08-01 18:56
Btw, what is interesting: there are much more branchy leaves and solid wood blocks above other grass blocks, but only these rare ones turned barren. Maybe more will turn barren after getting ticks. But it seems a quite long time has passed and nothing has changed much.

**Comment by jchappelle** [comment] 2018-08-02 05:17
Currently grass will die if the light level is below 7. We should probably lower that to reduce these scenarios. I'll make a change for this.

**Comment by jchappelle** [comment] 2018-08-02 05:30
Just committed a change to set the growthLightLevel to 3 which means soil will only die if it's below 3.

**Closed by jchappelle** 2018-08-02 05:30 UTC
Labels: status: new, target: survival, type: bug
