### ISSUE TITLE
My game crashes when i start it up

### ISSUE THREAD

**Issue by Shinobo312** [anegostudios/VintageStory-Issues#969] opened 2021-06-05 23:03 UTC
This is the crash report so try to make sense of that
```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.14.10 (Stable)6/5/2021 5:57:43 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at VSHUD.WaypointUtils.Dispose()
   at Vintagestory.Common.ModLoader.Dispose()
   at Vintagestory.Client.NoObf.ClientMain.Dispose()
   at Vintagestory.Client.NoObf.ClientMain.DestroyGameSession(Boolean gotDisconnected)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _vKnDSS3ZW5fZhqcIJSzL9xbAUttA._mhcyOBzdAWALla9FVcjc15WACGi(Single )
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._3HP2xkrryy8Ktr1q1yqHHv9s1kb(Single )
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._JbXJA0SA6LQOS6diuqtXAjMb8Fo(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _ISiSTzGmXXpAqo3PzdxdVD1bClZ._ofvn0Tr1zNGCbNV3SxvKs2MXNP(_C7CLMRbe3BejVtaARYCgl7Bg1vl , String[] )
   at _0Y0SN1uu1V65pRLxvnN2xsIjXAg._ofvn0Tr1zNGCbNV3SxvKs2MXNP(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 6/5/2021 5:57:43 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.14.10.0, time stamp: 0x6079b344
Faulting module name: KERNELBASE.dll, version: 10.0.19041.964, time stamp: 0x812662a7
Exception code: 0xc0020001
Fault offset: 0x0000000000034b89
Faulting process id: 0x325c
Faulting application start time: 0x01d75a5e19e08433
Faulting application path: C:\Users\Shinobi\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 2e99460e-5e94-434f-881d-670f88ac7633
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 6/5/2021 5:49:47 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1462653544923052588, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 6079b344
P4: KERNELBASE.dll
P5: 10.0.19041.964
P6: 812662a7
P7: c000041d
P8: 0000000000034b89
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1E7F.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2007.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2018.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2018.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2028.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_1435832d6a888bddc4944b5adde84eb270185d_5674d60d_5934710c-8566-4c14-8328-51fc8a0f0197

Analysis symbol: 
Rechecking for solution: 0
Report Id: 19540e1a-c3a4-4322-9892-9870a57f3829
Report Status: 268566528
Hashed bucket: 56b977968b86c27bf44c63a64e9aba2c
Cab Guid: 0 }
--------------
{ TimeGenerated = 6/5/2021 5:49:46 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.14.10.0, time stamp: 0x6079b344
Faulting module name: KERNELBASE.dll, version: 10.0.19041.964, time stamp: 0x812662a7
Exception code: 0xc000041d
Fault offset: 0x0000000000034b89
Faulting process id: 0x2618
Faulting application start time: 0x01d75a5cf2950e93
Faulting application path: C:\Users\Shinobi\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 19540e1a-c3a4-4322-9892-9870a57f3829
Faulting package full name: 
Faulting package-relative application ID:  }
```

**Comment by Craluminum2413** [comment] 2021-06-05 23:23
How to reproduce? Any mods?

**Comment by Craluminum2413** [comment] 2021-06-05 23:59
Oh, this is VSHUD mod

**Comment by copygirl** [comment] 2021-06-06 05:39
Indeed, as you can see in the so-called stack trace, the issue occurs in VSHUD's code:
> ```
> System.NullReferenceException: Object reference not set to an instance of an object.
>     at VSHUD.WaypointUtils.Dispose()
> ```

The code itself appears to be closing the game, so since you say this occurs during start-up, you might get a more direct error if you remove VSHUD.

**Closed by copygirl** 2021-06-06 05:39 UTC
Labels: status: invalid
