### ISSUE TITLE
Animals escape pens randomly

### ISSUE THREAD

**Issue by pwbaim** [anegostudios/VintageStory-Issues#3411] opened 2024-01-08 04:17 UTC
I am finding animals outside their pens at random times wandering around. There was no route for them to escape and no predator attacks. This includes pigs in a double high fenced pen with a roof! I assume they are glitching through somehow when I re-enter the chunk. The interaction of animal hitboxes with gates are problematic in general (as I watch animals intersecting the gate still free to go either way after the gate closes). The solution to that in games like Valheim is to sweep the animal along with the closing gate (i.e., honor the animal hitbox AND gate hitbox). The glitching is not acceptable though. Perhaps the collision with other animals in crowded pens is resolved before the collision with the fence? Allowing animals to be pushed through randomly?

**Comment by Craluminum2413** [comment] 2024-01-10 07:37
Duplicate of #3311

**Closed by Craluminum2413** 2024-01-10 07:37 UTC
