### ISSUE TITLE
Last piece of pie provides no satiety

### ISSUE THREAD

**Issue by jdclifton** [anegostudios/VintageStory-Issues#3153] opened 2023-10-14 21:40 UTC
### Game Version

v1.18.15

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The last piece of a pie, regardless of if it is meat or vegetable based, does not provide any gain in hunger/satiety and is effectively wasted.

### How to reproduce

Make a pie, get rid of the first three pieces, eat the last one

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2023-10-14 21:43
Duplicate of #2117

**Closed by Craluminum2413** 2023-10-14 21:43 UTC
Labels: status: new

**Comment by AncletYinglet** [comment] 2024-01-21 16:22
This bug seems to have cropped up in v1.19.1 as well. The fourth slice of pie does not provide any satiety.
