### ISSUE TITLE
Game speed running at several times normal rate after game crash and reload

### ISSUE THREAD

**Issue by hiddenmutant** [anegostudios/VintageStory-Issues#4256] opened 2024-10-08 16:49 UTC
### Game Version

v1.20.0-pre.5 (Unstable)

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

game crashed after going to bed at night and being "asleep/in bed" for some time.  reopening game save file, time had progressed and player character was "out of bed/awake," but the world time speed was moving at a highly rapid rate for some reason (no settings were changed), satiety was also dropping rapidly alongside the speed of the clock, and other time-based progressions were affected (such as pit kilns finishing firing), but others were not (firewood in a firepit seemed to be being consumed at a "normal" rate, that is to say as though the game were at standard speed).

possibly unrelated issue, but reed baskets are not functioning as increased inventory despite being properly held in the righthand inventory hotbar.  unequipping and re-equipping, placing on ground or in storage and re-equipping, and restarting from the save file does not solve the issue.  they are 100% for sure reed baskets and NOT reed chests.

### How to reproduce

Sleep in hay bed at night, ceiling above bed was 3 blocks from floor, bed was adjacent to dirt block walls at the head of the bed and the left side, but not the foot of the bed or the right side.  Game crash and reload from save file.

### Logs

Running on 64 bit Windows 10.0.22631.0 with 64632 MB RAM
Game Version: v1.20.0-pre.5 (Unstable)
10/7/2024 11:01:30 PM: Critical error occurred
Loaded Mods: game@1.20.0-pre.5, creative@1.20.0-pre.5, survival@1.20.0-pre.5
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.API.MathTools.SimplexNoiseOctave.Evaluate(Double x, Double y, Double z) in VintagestoryApi\Math\Noise\SimplexOctave.cs:line 414
   at Vintagestory.API.MathTools.SimplexNoise.Noise(Double x, Double y, Double z) in VintagestoryApi\Math\Noise\SimplexNoise.cs:line 117
   at Vintagestory.GameContent.WeatherPattern.RegenCloudTileCache(Vec3i tileOffset) in VSEssentials\Systems\Weather\Model\Impl\WeatherPattern.cs:line 89
   at Vintagestory.GameContent.CloudRenderer.UpdateCloudTilesOffThread(Int32 changeSpeed) in VSEssentials\Systems\Weather\CloudRenderer.cs:line 390
   at Vintagestory.GameContent.CloudRenderer.<.ctor>b__31_2() in VSEssentials\Systems\Weather\CloudRenderer.cs:line 166

**Comment by Craluminum2413** [comment] 2024-10-08 16:51
Duplicate of #4166

**Closed by Craluminum2413** 2024-10-08 16:51 UTC
Labels: status: new
