### ISSUE TITLE
game crashed on start

### ISSUE THREAD

**Issue by derwilms** [anegostudios/VintageStory-Issues#500] opened 2020-04-03 19:24 UTC
**Game Version:** 1.12.14
**Platform:** Windows 
**Modded:** No 
### Description
Crashed on Start

### How to reproduce
'
3. It crashes

### Logs
```
Running on 64 bit Windows with 12 GB RAM 
Version: v1.12.14 (Stable)03.04.2020 19:07:30: Critical error occurred
System.IO.EndOfStreamException: Über das Ende des Datenstroms hinaus kann nicht gelesen werden.
   bei System.IO.__Error.EndOfFile()
   bei System.IO.MemoryStream.InternalReadInt32()
   bei Vintagestory.API.Common.EntityAgent.FromBytes(BinaryReader reader, Boolean forClient)
   bei Vintagestory.API.Common.EntityPlayer.FromBytes(BinaryReader reader, Boolean forClient)
   bei Vintagestory.Client.NoObf.ClientSystemEntities.createOrUpdateEntityFromPacket(_zXVe9s51OaHEH3Dbu8UDf1mpaep entitypacket, _hLaepLRCOckdCEvZTPp1GxfgrdT game, Boolean addToLoadQueue)
   bei Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntityLoadedPacket(_lX4DihH89EYnCCsHGxLyJXIlnWr serverpacket)
   bei _hLaepLRCOckdCEvZTPp1GxfgrdT._KRW87LoBbkCXLdwtgmWh156gLDo(Single )
   bei _wdM7EEtmCaPwd0J7vcjv5PBK3NA._UfbESUwVALAm24tWKSVekibkmyy(Single )
   bei _s54YxMQ8l5DBeihbmw81nJkPTSU._RT1lBvzfhVzcDZ6jmYewDTkUdvx(Single )
   bei _s54YxMQ8l5DBeihbmw81nJkPTSU._EZIJU8BLizIQdIOGgxu5BrkHzpV(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _gilSYm6aSzOct8TKUm64HAM8OHp._tyidesQGCE1oKHv8YEo8HwYCSty(_RxGTCHor7fqeGRNMEH5pZVfBHHK , String[] )
   bei _xmrDk9pogtvR6xvbzmBc2dtFsbu._tyidesQGCE1oKHv8YEo8HwYCSty(ThreadStart )
-------------------------------

```

**Comment by copygirl** [comment] 2020-04-03 21:19
I will likely close this as a duplicate of #390 some time, but I'll leave it up for visibility.

But first: Do you remember anything "odd" happening last time you played the game? Did it crash or did you forcefully close the game? Did your computer shut down unexpectedly?

As for resolving the issue: You can load the world in repair mode. Go to the singleplayer world selection, press the pencil icon and you'll see the button.

**Comment by derwilms** [comment] 2020-04-06 18:42
Hallo,

 

vorab danke für den Tipp mit dem repair mode.

Das hat super funktioniert. Demnach konnte ich dann auch nachvollziehen, dass ich in einer Höhle war und Braunkohle abgebaut … mitten im Doing ist dann der Absturz gekommen.

Ein Starten vor der Reparatur war nicht möglich.

Vorher hatte ich aber über mehrere Tage einige Abstürze meines Rechners.

 

Ich hoffe das hilft weiter ….

 

Greetz

 

Von: copygirl <notifications@github.com> 
Gesendet: Freitag, 3. April 2020 23:20
An: anegostudios/VintageStory-Issues <VintageStory-Issues@noreply.github.com>
Cc: derwilms <info@wilms.cc>; Author <author@noreply.github.com>
Betreff: Re: [anegostudios/VintageStory-Issues] game crashed on start (#500)

 

I will likely close this as a duplicate of #390 <https://github.com/anegostudios/VintageStory-Issues/issues/390>  some time, but I'll leave it up for visibility.

But first: Do you remember anything "odd" happening last time you played the game? Did it crash or did you forcefully close the game? Did your computer shut down unexpectedly?

As for resolving the issue: You can load the world in repair mode. Go to the singleplayer world selection, press the pencil icon and you'll see the button.

**Comment by copygirl** [comment] 2020-04-06 19:55
Alright, thank you. I will close this as a duplicate of #390, then. We'll be working on making the game more resistant to unexpected crashes, so they don't require you to hop into repair mode.

----

Okay, danke dir. Ich werde den Fehlerbericht dann als Duplikat von #390 schließen. Wir werden daran arbeiten, das Spiel mehr robust zu machen was unverhoffte Abstürze angeht, damit man nicht in den Reparaturmodus gehen muss.

**Closed by copygirl** 2020-04-06 19:55 UTC
Labels: status: new, type: crash
