### ISSUE TITLE
Game crashes after raft is used and kapt in inventory

### ISSUE THREAD

**Issue by adres4t-1** [anegostudios/VintageStory-Issues#2496] opened 2023-03-20 09:46 UTC
### Game Version

1.8 pre7

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

1. Craft a raft and oar, put it on water, jump in and out, put it back to the inventory then save and quit the game. This way game crashes to desktop. When thrown away by pressing Q then save and quit nothing happens. Raft will still be on the ground when loading the world up.

2. I also had an issue where I accidentaly clicked on a tree with raft and it began sailing upwards on the trunk, stopping only where there were leafs or moss; punching those away made the raft continue going up. Can't reproduce as I had mods active when that happened(wildcraft trees is my suspect. Screenshots below.

### How to reproduce

Craft a raft and oar, put it on water, jump in and out, put it back to the inventory then save and quit the game.

### Screenshots

2.
![2023-03-20_09-16-37](https://user-images.githubusercontent.com/101258969/226302570-b803f259-4b39-44c7-8b95-9f20dd0a22f9.png)
![2023-03-20_09-16-44](https://user-images.githubusercontent.com/101258969/226302579-d5701fa8-75af-4146-8a1e-850849b8662c.png)
![2023-03-20_09-16-22](https://user-images.githubusercontent.com/101258969/226302587-f15ad71b-65d6-4203-a9f4-64a704ce8a45.png)

### Logs

Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.18.0-pre.7 (Unstable)
20/03/2023 09:35:50: Critical error occurred
Loaded Mods: 
System.NotImplementedException: The method or operation is not implemented.
   at Vintagestory.GameContent.EntityBoat.Dispose() in VSSurvivalMod\Systems\Boats\EntityBoat.cs:line 482
   at Vintagestory.Client.NoObf.ClientEventManager.Dispose() in VintagestoryLib\Client\Util\ClientEventManager.cs:line 556
   at Vintagestory.Client.NoObf.ClientMain.Dispose() in VintagestoryLib\Client\ClientMain.cs:line 2621
   at Vintagestory.Client.NoObf.ClientMain.DestroyGameSession(Boolean gotDisconnected) in VintagestoryLib\Client\ClientMain.cs:line 2536
   at Vintagestory.Client.NoObf.GuiDialogEscapeMenu.OnLeaveWorld() in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogEscapeMenu.cs:line 323
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 304
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\GuiElement.cs:line 677
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 292
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 440
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 564
   at Vintagestory.Client.NoObf.GuiDialogEscapeMenu.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogEscapeMenu.cs:line 388
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 416
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 229
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 808
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1551
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 369
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 19/03/2023 20:21:17, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.0.0, time stamp: 0x640994ff
Faulting module name: atio6axx.dll, version: 31.0.14001.45012, time stamp: 0x63e6d8f3
Exception code: 0xc0000005
Fault offset: 0x0000000000405249
Faulting process ID: 0x4db0
Faulting application start time: 0x01d95a94bfd95353
Faulting application path: E:\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\DriverStore\FileRepository\u0388153.inf_amd64_a09a6ed88273e4ec\B388275\atio6axx.dll
Report ID: 1911f3fb-f094-4675-9e1b-46e45d7d0b24
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 19/03/2023 20:21:17, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FFCF58A5249
 }
--------------
{ TimeGenerated = 18/03/2023 22:14:33, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException
   at System.Threading.ThreadLocal`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetValueSlow()
   at Vintagestory.GameContent.BlockClutterBookshelf.RandomType(System.String)
   at Vintagestory.GameContent.BlockClutterBookshelf.GetTypeProps(System.String, Vintagestory.API.Common.ItemStack, Vintagestory.GameContent.BEBehaviorShapeFromAttributes)
   at Vintagestory.GameContent.BlockShapeFromAttributes.GetLightHsv(Vintagestory.API.Common.IBlockAccessor, Vintagestory.API.MathTools.BlockPos, Vintagestory.API.Common.ItemStack)
   at Vintagestory.API.Common.Block.GetHeldItemInfo(Vintagestory.API.Common.ItemSlot, System.Text.StringBuilder, Vintagestory.API.Common.IWorldAccessor, Boolean)
   at Vintagestory.GameContent.BlockShapeFromAttributes.GetHeldItemInfo(Vintagestory.API.Common.ItemSlot, System.Text.StringBuilder, Vintagestory.API.Common.IWorldAccessor, Boolean)
   at Vintagestory.API.Common.ItemStack.GetDescription(Vintagestory.API.Common.IWorldAccessor, Vintagestory.API.Common.ItemSlot, Boolean)
   at Vintagestory.GameContent.GuiHandbookItemStackPage..ctor(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Common.ItemStack)
   at Vintagestory.GameContent.ModSystemHandbook.onCreatePagesAsync()
   at Vintagestory.GameContent.GuiDialogHandbook.LoadPages_Async()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }

**Comment by Craluminum2413** [comment] 2023-03-20 09:59
Duplicate of #2465

**Closed by Craluminum2413** 2023-03-20 09:59 UTC
Labels: status: new
