### ISSUE TITLE
Chat bar doesn't accept first input when "Enter" is used as the key to open the chat

### ISSUE THREAD

**Issue by mrrhetorical** [anegostudios/VintageStory-Issues#3341] opened 2023-12-26 18:12 UTC
### Game Version

v1.19.0-rc3

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

When opening the chat, the first key that is pressed is not recognized in the chat window when typing a new message only when the ENTER key is bound to the action to open the chat.

### How to reproduce

1. Bind "Chat: Begin Typing" to ENTER
2. Press ENTER
3. Begin typing

**Comment by Craluminum2413** [comment] 2023-12-28 14:38
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/3208

**Closed by Craluminum2413** 2023-12-28 14:38 UTC
Labels: status: new
