### ISSUE TITLE
Game runs very poorly on Linux Mint

### ISSUE THREAD

**Issue by Altaelor** [anegostudios/VintageStory-Issues#2772] opened 2023-05-22 16:32 UTC
### Game Version

v1.18.5

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Recently moved onto Linux Mint, but sadly the game will run very poorly for some reason. I have the suspicion that possibly the game is forcefully using my Integrated graphic card instead of the Dedicated GPU.

I already tried the tweaks in the "Framerate and Performance for Linux users", and the game will run at 40 fps with massive stuttering even in medium, whereas in Windows I had 60+ with everything on high.

I also tried running the game with Steam to forcefully use the dedicated gpu but that didn´t work neither. 

My pc specs:

System:
  Kernel: 5.15.0-72-generic x86_64 bits: 64 compiler: gcc v: 11.3.0 Desktop: Cinnamon 5.6.8
    tk: GTK 3.24.33 wm: muffin dm: LightDM Distro: Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy
CPU:
  Info: 8-core model: AMD Ryzen 7 4800H with Radeon Graphics bits: 64 type: MT MCP arch: Zen 2
    rev: 1 cache: L1: 512 KiB L2: 4 MiB L3: 8 MiB
  Speed (MHz): avg: 1443 high: 2137 min/max: 1400/2900 boost: enabled cores: 1: 1397 2: 2137
    3: 1397 4: 1397 5: 1396 6: 1397 7: 1397 8: 1396 9: 1397 10: 1397 11: 1409 12: 1397 13: 1397
    14: 1397 15: 1397 16: 1397 bogomips: 92630
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: AMD Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] vendor: Micro-Star MSI
    driver: amdgpu v: kernel pcie: speed: 8 GT/s lanes: 16 ports: active: HDMI-A-1 empty: DP-1
    bus-ID: 03:00.0 chip-ID: 1002:731f
  Device-2: AMD Renoir vendor: Micro-Star MSI driver: amdgpu v: kernel pcie: speed: 16 GT/s
    lanes: 16 ports: active: eDP-1 empty: DP-2,DP-3,DP-4 bus-ID: 08:00.0 chip-ID: 1002:1636
16gb RAM

### Logs

```Log```

**Comment by radfast** [comment] 2023-05-23 14:12
1. The Ctrl+F3 debug screen will show you, at top left, which graphics card is being used.  Please post an example screenshot.

2. Did the game previously run OK on the same hardware under a different OS (a different Linux distro or Windows)?

3. Are you 100% confident you have the latest drivers for your GPU and they are issue-free?  Vintage Story makes surprisingly widespread usage of a driver's GLSL shaders even without the pretty turned on.  Some GPU drivers have been known to have GLSL bugs, even a small issue there could cause a problem.

4. Try a variety of graphics settings, basically try turning everything off (no shaders, no SSAO) and see if that is smooth, then gradually switch things back on to see if one specific feature is causing the issue

**Comment by Altaelor** [comment] 2023-05-23 20:06
1) Screenshot attached. I believe it is using the integrated GPU as thought.
![2023-05-23_22-02-38](https://github.com/anegostudios/VintageStory-Issues/assets/134141539/bd1807b4-4571-4203-a063-163e82f4ea1c)

2) The game ran flawlessly on Windows 10 (except for a little problem specified here: https://github.com/anegostudios/VintageStory-Issues/issues/2762)

3) I am not an expert on Linux and thus I can not guarantee I have the latest drivers. As far as I am concerned Linux Mint offers and out of the box experience and drivers should be updated accordingly. 

4) Same result for every settings. The game will run poorly and stutter with every option.

**Comment by radfast** [comment] 2023-05-26 23:32
Please try one of the .NET7 Linux clients posted in [this Discord thread](https://discord.com/channels/302152934249070593/1110493590167228416) - the latest being the most recent.

Another user has reported today:  "_this client  release fixes all the technical issues i was having before on linux (main menu freeze, performance issues, alt tab freeze). thanks!_"    Maybe the same will happen for you?

If that solves it please let us know!

**Comment by Altaelor** [comment] 2023-05-27 00:00
Sorry but I don´t understand what I should do with these files. I tried pasting them into my game folder and now it won´t run.

**Comment by DArkHekRoMaNT** [comment] 2023-05-27 00:20
> Sorry but I don´t understand what I should do with these files. The game executable won´t run. I tried pasting these files into my game folder and it won´t run neither.

You need to extract the tar.gz archive and run Vintagestory directly (no mono) or use run.sh, but make sure Vintagestory file has execute permission. And this is a clean install, you don't need to install it over existing files, just copy /assets/survival/music

**Comment by radfast** [comment] 2023-05-30 16:01
@Altaelor  have you been able to get the .NET7 Linux Client running, has this resolved your issue?

**Comment by Altaelor** [comment] 2023-05-31 19:45
> 

Thank you, the game runs fine now, but sadly it will crash whenever I try to join my favorite multiplayer server. I will leave the report below:

Running on 64 bit Linux with 15393 MB RAM
Game Version: v1.18.5 (Stable)
5/31/2023 9:43:21 PM: Critical error occurred
Loaded Mods: game@1.18.5, creative@1.18.5, survival@1.18.5
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.SystemModHandler.<>c.<OnServerIdentificationReceived>b__4_2(ModContainer mod) in C:\Games\Vintagestory\devnet6\VintagestoryLib\Client\Systems\ModHandler.cs:line 70
   at System.Linq.Enumerable.WhereSelectListIterator`2.ToList()
   at Vintagestory.Client.NoObf.SystemModHandler.OnServerIdentificationReceived() in C:\Games\Vintagestory\devnet6\VintagestoryLib\Client\Systems\ModHandler.cs:line 69
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerIdent(Packet_Server packet) in C:\Games\Vintagestory\devnet6\VintagestoryLib\Client\Systems\Startup.cs:line 154
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in C:\Games\Vintagestory\devnet6\VintagestoryLib\Client\Systems\NetworkProcess.cs:line 452
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in C:\Games\Vintagestory\devnet6\VintagestoryLib\Client\Systems\NetworkProcess.cs:line 446
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in C:\Games\Vintagestory\devnet6\VintagestoryLib\Client\ClientMain.cs:line 762
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in C:\Games\Vintagestory\devnet6\VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 341
   at Vintagestory.Client.ScreenManager.Render(Single dt) in C:\Games\Vintagestory\devnet6\VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in C:\Games\Vintagestory\devnet6\VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in C:\Games\Vintagestory\devnet6\VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 72
   at OpenTK.Windowing.Desktop.GameWindow.DispatchRenderFrame()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in C:\Games\Vintagestory\devnet6\VintagestoryLib\Client\ClientProgram.cs:line 311
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in C:\Games\Vintagestory\devnet6\VintagestoryLib\Client\ClientProgram.cs:line 133
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Games\Vintagestory\devnet6\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by radfast** [comment] 2023-05-31 22:33
The error occurs when your game is figuring out the mods you already have, prepatory to joining the modded server.

One of your mods is bugged (probably has a blank Info) causing this bug.

Try deleting everything in your `/Mods` folder except for VSSurvivalMod, VSCreativeMod and VSEssentials.  Then reconnect to this modded server.

------

Closing because the originally reported issue is resolved.  Any remaining issues seem caused by your particular mods, not by the game.

**Closed by radfast** 2023-05-31 22:33 UTC
Labels: platform: linux, status: incomplete
