### ISSUE TITLE
Can't join world

### ISSUE THREAD

**Issue by VeryGoodDog** [anegostudios/VintageStory-Issues#2422] opened 2023-03-01 21:00 UTC
### Game Version

1.18.0-pre.3

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When I open a world it begins normally but the screen gets locked/frozen on the loading screen.
The logs themselves show that the game is loading everything correctly and the player joins the world.

### Screenshots

![image](https://user-images.githubusercontent.com/22282562/222263300-c711118a-d7f7-493b-b2fa-73a67d8cde67.png)

### Logs

[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/10865288/client-debug.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/10865289/client-main.txt)
[server-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/10865294/server-debug.txt)
[server-event.txt](https://github.com/anegostudios/VintageStory-Issues/files/10865295/server-event.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/10865296/server-main.txt)
[server-storyevent.txt](https://github.com/anegostudios/VintageStory-Issues/files/10865297/server-storyevent.txt)

**Comment by VeryGoodDog** [comment] 2023-03-01 21:05
Sorry, the logs say that the player never joins.

**Comment by VeryGoodDog** [comment] 2023-03-01 23:10
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/10865710/client-debug.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/10865711/client-main.txt)
[server-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/10865713/server-debug.txt)
[server-event.txt](https://github.com/anegostudios/VintageStory-Issues/files/10865714/server-event.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/10865715/server-main.txt)
[server-storyevent.txt](https://github.com/anegostudios/VintageStory-Issues/files/10865716/server-storyevent.txt)

These are the logs from one time the world opened successfully.
The differences I can find in the client-main.txt from the times the game didn't start is that
- not all shaders are loaded
- no mod systems are started
- the client never loads the server assets

From the server-main.txt
- the server never received any attempted connections.

**Comment by Saricane** [comment] 2023-03-02 17:40
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/2396

**Closed** 2023-03-03 11:24 UTC
Labels: status: duplicate, platform: linux
