### ISSUE TITLE
Земля и часть интерфейса стали голубыми

### ISSUE THREAD

**Issue by Void10110** [anegostudios/VintageStory-Issues#4646] opened 2024-12-09 16:43 UTC
### Game Version

1.20.0-rc1

### Platform

Mac

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

первый запуск игры, в меню создания персонажа перекрашены коричневые и жёлтые элементы одежды, то же самое с некоторыми частями интерфейса и блоками.

### How to reproduce

не знаю. ошибка была с самого запуска игры, из за того что я первый раз запустил игру я даже не сразу понял что что то не так

### Screenshots

<img width="1440" alt="Снимок экрана 2024-12-09 в 21 28 55" src="https://github.com/user-attachments/assets/7a8a3029-6c3f-4d53-869e-7ec69ca189fd">
<img width="1440" alt="Снимок экрана 2024-12-09 в 21 29 36" src="https://github.com/user-attachments/assets/7810e7bc-6313-4d48-a245-35cd05d39216">

### Logs

в папке logs:
[client-audit.log](https://github.com/user-attachments/files/18064691/client-audit.log)
[client-chat.log](https://github.com/user-attachments/files/18064692/client-chat.log)
[client-crash.log](https://github.com/user-attachments/files/18064693/client-crash.log)
[client-debug.log](https://github.com/user-attachments/files/18064694/client-debug.log)
[client-main.log](https://github.com/user-attachments/files/18064695/client-main.log)
[server-audit.log](https://github.com/user-attachments/files/18064696/server-audit.log)
[server-build.log](https://github.com/user-attachments/files/18064697/server-build.log)
[server-chat.log](https://github.com/user-attachments/files/18064698/server-chat.log)
[server-debug.log](https://github.com/user-attachments/files/18064699/server-debug.log)
[server-main.log](https://github.com/user-attachments/files/18064700/server-main.log)
[server-worldgen.log](https://github.com/user-attachments/files/18064701/server-worldgen.log)
в папке archive:
в папке 2024-12-09_20_14_55: 
[client-audit.log](https://github.com/user-attachments/files/18064743/client-audit.log)
[client-chat.log](https://github.com/user-attachments/files/18064744/client-chat.log)
[client-debug.log](https://github.com/user-attachments/files/18064745/client-debug.log)
[client-main.log](https://github.com/user-attachments/files/18064747/client-main.log)
в папке 2024-12-09_20_16_28:
[client-audit.log](https://github.com/user-attachments/files/18064752/client-audit.log)
[client-chat.log](https://github.com/user-attachments/files/18064753/client-chat.log)
[client-debug.log](https://github.com/user-attachments/files/18064754/client-debug.log)
[client-main.log](https://github.com/user-attachments/files/18064755/client-main.log)
в папке 2024-12-09_20_47_57:
[client-audit.log](https://github.com/user-attachments/files/18064763/client-audit.log)
[client-chat.log](https://github.com/user-attachments/files/18064764/client-chat.log)
[client-debug.log](https://github.com/user-attachments/files/18064765/client-debug.log)
[client-main.log](https://github.com/user-attachments/files/18064766/client-main.log)
[server-audit.log](https://github.com/user-attachments/files/18064767/server-audit.log)
[server-build.log](https://github.com/user-attachments/files/18064768/server-build.log)
[server-chat.log](https://github.com/user-attachments/files/18064769/server-chat.log)
[server-debug.log](https://github.com/user-attachments/files/18064770/server-debug.log)
[server-main.log](https://github.com/user-attachments/files/18064771/server-main.log)

**Comment by Craluminum2413** [comment] 2024-12-09 16:45
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4327

**Closed by Craluminum2413** 2024-12-09 16:45 UTC
Labels: status: new
