### ISSUE TITLE
Food container weirdness.

### ISSUE THREAD

**Issue by Kaedwuff** [anegostudios/VintageStory-Issues#2704] opened 2023-05-07 01:21 UTC
### Game Version

v1.18.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

I am experiencing an issue related to food containers.

I am not sure of the full scope of this issue, but I am experiencing issues with bowls and other containers not working correctly.  The one in this picture can be picked up but attempting to eat it results in no food satiation and the bowl not being emptied.  Additionally, throwing the bowl causes it to vanish, failing to spawn and actual item, and when placing the bowl, I have frequent issues of the game losing track of where I placed it, or reverting the ground-stored bowl to another location every time I try, sometimes jittering wildly between bowls disappearing or reappearing in different orientations.  Sometimes, when I come back later, I find that the bowls have assumed the position they were in when I first logged in, even if I moved them.

This also seems to affect filled crockpots, I've lost two already as the game seems to lose track of their existence when I place them on a surface sometimes.

### How to reproduce

I'm not sure how reproducible it is, but it mainly occurs when picking up or putting containers down.

### Screenshots

![image](https://user-images.githubusercontent.com/12869074/236652819-7d364a8e-654e-4b46-a92c-8a6a2beb46e7.png)

### Logs

No logs.

**Comment by Echoweaver** [comment] 2023-05-08 01:30
I'm experiencing this too. Events that caused trouble today:

 - Right clicked to place a single red meat item in the cook pot inventory and the entire cook pot disappeared
 - Attempted to place a cook pot on a floor square that already contained a crucible and a bowl. Picked up the bowl and the pot disappeared.

I'm on a multiplayer server. Another player came to investigate, and my meal-filled cook pot was on the floor where I had tried to place it. He could fill a bowl and toss it to me.

Later I noticed that the cook pot from the first event above had turned back up in my inventory.

Sometimes I have no trouble at all with meals.

**Comment by Echoweaver** [comment] 2023-05-08 19:22
My issue was resolved by upgrading to the 1.18.2-rc2 candidate client.

**Comment by Athemis** [comment] 2023-05-08 20:04
Happened to me as well. Server was 1.18.2-rc2, client 1.18.1. Downgraded the server to 1.18.2-rc1 and everything worked as intended again. Haven't checked with 1.18.2-rc2 client _and_ server.

**Comment by Craluminum2413** [comment] 2024-09-30 09:56
Closed due to inactivity

**Closed by Craluminum2413** 2024-09-30 09:56 UTC
Labels: target: multiplayer, status: new
