### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by FalcoGer** [anegostudios/VintageStory-Issues#3267] opened 2023-12-02 03:38 UTC
### Game Version

v1.18.15.0

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Happened when placing down firewood, but firewood placing was fine just before.

### How to reproduce

1. No clue

### Logs

```Log
Running on 64 bit Windows with 81844 MB RAM
Game Version: v1.18.15 (Stable)
02.12.2023 04:31:44: Critical error occurred
Loaded Mods: aculinaryartillery@1.0.15, advancedsmithing@1.3.0, betterbackpacks@1.0.0, betterbricks@1.1.1, betterruins@0.2.4, hqzlights@1.1.1, extrachests@1.7.0, foundrymod@1.0.0, fulldrop@1.0.0, harptech@0.2.3, itemlights@1.0.2, knappingmastery@1.0.1, longerburntime@1.0.1, longertorchtime@1.0.1, meteoricexpansion@1.2.4, moreicons@1.1.0, moreanimalloot@1.0.1, moreenemyloot@1.1.0, morefirewood@1.0.1, moreflaxloot@1.0.1, MoreTorchHolders@1.0.0, orepulverizer@1.1.1, pieontheshelf@1.0.0, potontheshelf@1.0.0, preservationmod@1.0.0, primitivesurvival@3.3.0, rackablefirestarter@1.0.0, shinglesandthethings@1.0.2-rc.1, stacks@1.0.4, usefulscrap@2.0.2, viescraftmachines@2.2.2, visibleore@1.0.1, game@1.18.15, wildcraft@1.6.6, zyrails0break0down0tools@1.18.14, alchemy@1.6.16, egocaribautomapmarkers@2.6.0, beehivekiln@1.5.1, betterbackpacksfixed@1.0.4, betterbackpacksnoiron@1.0.1, butchering@1.1.5, carryon@1.6.1, cbetterfertilizer@1.0.1, commonlib@2.2.0, composter@1.1.0, expandedfoods@1.6.8, fixhandbookclutter@1.0.5, glowingprojectiles@1.1.3, hudclock@3.3.0, moreanimals@1.2.4, morestickcrafting@1.0.2, claywheel@1.1.0, prospectorinfo@4.3.0, recyclestorage@1.0.1, slidingdoor@1.0.0, stillnecessaries@1.0.1, stonerailings@1.1.0, creative@1.18.15, survival@1.18.15, VsWaypointSharing@1.0.6, wildfarmingrevival@1.1.6, workbenchexpansion@1.7.0, xlib@0.7.4, metalrecovery@0.1.19-pre.1, awearablelight@1.0.10, beehivekilnwithclay@1.0.0, betterstonerailings@1.0.0, bullseye@2.5.1, helvehammerext@1.5.2, morecandles@1.1.3, playercorpse@1.8.0, xskills@0.7.5, betterbackpacksforawearablelight@1.0.4
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleDisconnectPlayer(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 182
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 757
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 02.12.2023 03:43:50, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Nicht verfügbar
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8F27.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_3730b3dd-ef62-407a-b243-75cd99a93226

Analysis symbol: 
Rechecking for solution: 0
Report Id: 5bb7f637-d073-4d0b-bd62-67abafa0e7c8
Report Status: 131172
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 02.12.2023 03:43:50, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Nicht verfügbar
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAAA5.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_98f00e31-5558-4725-8e35-9727f3e97c46

Analysis symbol: 
Rechecking for solution: 0
Report Id: ebf58cd2-8e62-4fe9-a239-476325f70b62
Report Status: 131172
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 02.12.2023 03:43:49, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Nicht verfügbar
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9937.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_05b9ad46-47f0-4f19-969b-3d907650df7b

Analysis symbol: 
Rechecking for solution: 0
Report Id: d03f34cb-ae9d-464e-8315-5c92c7ba269b
Report Status: 131172
Hashed bucket: 
Cab Guid: 0 }
```

```xml
<?xml version="1.0" encoding="UTF-16"?>
<WERReportMetadata>
	<OSVersionInformation>
		<WindowsNTVersion>10.0</WindowsNTVersion>
		<Build>19042</Build>
		<Product>(0x30): Windows 10 Pro</Product>
		<Edition>Professional</Edition>
		<BuildString>19041.1706.amd64fre.vb_release.191206-1406</BuildString>
		<Revision>1706</Revision>
		<Flavor>Multiprocessor Free</Flavor>
		<Architecture>X64</Architecture>
		<LCID>1031</LCID>
	</OSVersionInformation>
	<ProblemSignatures>
		<EventType>APPCRASH</EventType>
		<Parameter0>Vintagestory.exe</Parameter0>
		<Parameter1>1.18.15.0</Parameter1>
		<Parameter2>64e841c5</Parameter2>
		<Parameter3>openal32.dll</Parameter3>
		<Parameter4>1.23.0.0</Parameter4>
		<Parameter5>63dd31ad</Parameter5>
		<Parameter6>40000015</Parameter6>
		<Parameter7>00000000000df046</Parameter7>
	</ProblemSignatures>
	<DynamicSignatures>
		<Parameter1>10.0.19042.2.0.0.256.48</Parameter1>
		<Parameter2>1031</Parameter2>
		<Parameter22>f55f</Parameter22>
		<Parameter23>f55fdb7cf1a3b41e21da1d2926595ced</Parameter23>
		<Parameter24>800d</Parameter24>
		<Parameter25>800debc02e9237a9ab29934a629c805c</Parameter25>
	</DynamicSignatures>
	<SystemInformation>
		<MID>0F4A7FC6-3E16-4F11-B63D-F78ECE5EDA52</MID>
		<SystemManufacturer>To Be Filled By O.E.M.</SystemManufacturer>
		<SystemProductName>X370 Killer SLI</SystemProductName>
		<BIOSVersion>P7.30</BIOSVersion>
		<OSInstallDate>1615230054</OSInstallDate>
		<OSInstallTime>1601-01-02T21:54:08Z</OSInstallTime>
		<TimeZoneBias>-01:00</TimeZoneBias>
	</SystemInformation>
	<SecureBootState>
		<UEFISecureBootEnabled>0</UEFISecureBootEnabled>
	</SecureBootState>
	<ReportInformation>
		<Guid>05b9ad46-47f0-4f19-969b-3d907650df7b</Guid>
		<CreationTime>2023-12-01T20:43:33Z</CreationTime>
	</ReportInformation>
</WERReportMetadata>
```

**Comment by Craluminum2413** [comment] 2024-02-15 08:40
Duplicate of #2847

**Closed by Craluminum2413** 2024-02-15 08:40 UTC
Labels: status: new
