### ISSUE TITLE
Pit kiln : empty after use

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1044] opened 2021-06-21 20:18 UTC
**Game Version:** 1.15.0-pre6
**Platform:** Windows 
**Modded:** No

### Description
2 distincts but simultaneous pit kilns : one containing 1 crucible, the other a long blade mold.
When the fire ends, the 2 kilns are empty.
Previously, I made another containing 1 cooking pot, 1 crook and 1 bowl, without any problem.

Might be related to #986, but I don't know what the author means by 'invisible'. Existing or not ? Here, in this issue, the kiln is really empty.

**Comment by Craluminum2413** [comment] 2021-06-21 20:33
Do you see any hitbox when hovering over a pit?

**Comment by Craluminum2413** [comment] 2021-06-21 20:37
By invisible, I meant invisible texture

**Comment by Saricane** [comment] 2021-06-21 20:38
No. Nothing else than a hole ;-)

**Comment by Craluminum2413** [comment] 2021-06-21 20:38
Try to put something in this hole

**Comment by Saricane** [comment] 2021-06-21 20:39
> 
> 
> By invisible, I meant invisible texture

So the objects were there and you have been able to retrieve them.

**Comment by Saricane** [comment] 2021-06-21 20:40
> 
> 
> Try to place something in this hole

It works. I placed a wooden pan, a torch, everything is ok.

**Comment by Craluminum2413** [comment] 2021-06-21 20:43
> So the objects were there and you have been able to retrieve them.

Yes, I was able to get them then

**Comment by Craluminum2413** [comment] 2021-06-21 20:58
I can't reproduce this

https://user-images.githubusercontent.com/69315569/122827024-8a56ef00-d2ec-11eb-9836-35cf89366d26.mp4

**Comment by Saricane** [comment] 2021-06-21 21:01
I don't know what to say  :-(
Thanks for your own test.
I'll try again.

**Comment by Saricane** [comment] 2021-06-22 05:30
I made many tests in flat mode, but I am totally unable to reproduce this bug. As this will not help the devs, Copygirl, you feel free to delete this entry. Thanks.

**Comment by copygirl** [comment] 2021-06-22 05:36
Yeah let us know if it happens again.

**Comment by Saricane** [comment] 2021-06-22 13:01
Again. With a storage vessel, this time. I know the screenshot below gives absolutely no information, but even if I'm unable to reproduce this bug each time, it's real. The only thing I can add is that in both cases, when the burning stopped, I was in water, panning, just close to the kiln. Yes I know there is no link between those two things :-)

![2021-06-22_14-53-32](https://user-images.githubusercontent.com/84909583/122928669-633f0280-d36a-11eb-9d00-ed3018ac4218.png)

**Comment by tyronx** [comment] 2021-06-22 17:17
There is a small-ish chance this is fixed in pre.7, which adds

- the firing process is paused while at a chunk edge
- the fire will now go out if a block is placed above it

**Closed by tyronx** 2021-06-22 17:17 UTC
Labels: status: incomplete, target: survival, type: bug
