### ISSUE TITLE
Critical Errror While Filling Barrel

### ISSUE THREAD

**Issue by wbottenberg** [anegostudios/VintageStory-Issues#2049] opened 2022-07-24 20:19 UTC
Game Version: 1.17.0 pre.5
Platform: Windows
Modded: some json mods
SP/MP: Singleplayer
Mode: Survival/Explorer

Was filling a barrel containing 50 l of water with a stack of 5 oak, game crashed
I've attached client-crash.txt, it's the last instance.
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/9176594/client-crash.txt)
.

**Comment by Craluminum2413** [comment] 2022-07-24 20:24
Duplicate of #2021

**Closed by Craluminum2413** 2022-07-24 20:24 UTC
