### ISSUE TITLE
Animated containers can cause crashes in chunk tesselation

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#962] opened 2021-06-05 11:17 UTC
**Game Version:** 1.15.0-pre2
**Platform:** Windows
**Modded:** No

### Description
game:block-normal-generic-stationarybasket-east in one of trader huts cause crash when trying to open

### Screenshots
![image](https://user-images.githubusercontent.com/69315569/120889946-67e48680-c608-11eb-8426-6585aa938e58.png)

###### Stationary basket on the back side of trader hut (assets\survival\worldgen\schematics\tradeoutposts\caravan-wagon\small-5.json)
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.0-pre.2 (Unstable)06/05/2021 13:56:15: Critical error occurred
System.Exception: Chunk retesselated listener number 0 threw an exception (a=False, b=False, b=False)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityAnimationUtil.<StartAnimation>b__16_0()
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerChunkRetesselated(Vec3i chunkPos, ClientChunk chunk)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerChunkRetesselated(Vec3i chunkPos, ClientChunk chunk)
   at Vintagestory.Client.NoObf.ChunkTesselatorManager.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _xArlFw5lpThzIY0BN36UerAlHzU._14ww1iwrPaPwPpAZqZCUdf3d4Sm(Single )
   at _uFwaliVbJcYmzlP3dwic7HSHMr2._EuQCmN4cQf8FBHYrlJxd8EhIdNnA(Single )
   at _uFwaliVbJcYmzlP3dwic7HSHMr2._HlDCi3DfsJHaHE4jniBarrjFlHLB(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _EKato5MKvGk9ELCMKyl4BGVO7pe._ninJWCWaWyMG9ZSA1Eyytms1G5F(_BjQ4x8rTRChySIeXrK1HK1YSqec , String[] )
   at _btwtpE4G1MfBqD34njKFCvBcSRd._ninJWCWaWyMG9ZSA1Eyytms1G5F(ThreadStart )
```

**Comment by Craluminum2413** [comment] 2021-06-05 11:21
Just in case, I mention it here. #288

**Comment by tyronx** [comment] 2021-06-07 19:41
thanks, this is now fixed for pre.3

**Comment by Craluminum2413** [comment] 2021-06-17 15:39
@tyronx I found the same crash again. Seems it happens with absolutely all treasures.
### Seed: `1363934971`
### Coordinates: `/tp 79 102 -149`
![2021-06-17_18-34-48](https://user-images.githubusercontent.com/69315569/122429078-2a361500-cf9b-11eb-8035-83a6467b07a8.png)

**Comment by tyronx** [comment] 2021-06-17 19:54
I'm not able to reproduce this crash. Whats the crash log? Is that a world created in v1.14?

**Comment by Craluminum2413** [comment] 2021-06-17 19:58
World was created in 1.15.0-pre.3 version

**Comment by Craluminum2413** [comment] 2021-06-20 21:23
I checked all schematics in `\assets\survival\worldgen\schematics\buriedtreasure`, but nothing caused crash. But when I create any world and look for buried treasures in `creative + no-clip`, then I often find those that cause crash

**Comment by copygirl** [comment] 2021-06-20 22:35
Does it have to do with them being buried? Block being above? Chunk being occlusion culled?

**Comment by Craluminum2413** [comment] 2021-06-20 22:47
It looks like it only crashes when I open the chest when my character is in blocks. But I don't know for sure

**Comment by tyronx** [comment] 2021-06-22 08:24
Oh I think its due to radfast culling rendering of those chests, which caused its animation util to never get initialized properly. If you block any adjacent block before opening, it doesn't crash. 

In any case, i fixed this now for pre.6

**Closed by tyronx** 2021-06-22 08:24 UTC
Labels: status: in-progress, target: survival, type: crash
