### ISSUE TITLE
Starting red clay forming crashes reproducible

### ISSUE THREAD

**Issue by GreaseMonk** [anegostudios/VintageStory-Issues#4110] opened 2024-09-19 10:57 UTC
### Game Version

v1.20 pre-1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

I ctrl+right clicked on the floor with red clay in hand to start clay molding and the game crashed.

### How to reproduce

See description. Reproducible every time.

### Screenshots

![image](https://github.com/user-attachments/assets/59111fd4-96c0-489a-8225-08c5196c0cfc)

### Logs

```
Running on 64 bit Windows 10.0.22631.0 with 32509 MB RAM
Game Version: v1.20.0-pre.1 (Unstable)
9/19/2024 12:55:26 PM: Critical error occurred
Loaded Mods: ClaimsRadar@1.1.0, game@1.20.0-pre.1, hudclock@3.4.0, creative@1.20.0-pre.1, survival@1.20.0-pre.1
System.Exception: Can't create itemstack without item!
   at Vintagestory.API.Common.ItemStack..ctor(Item item, Int32 stacksize) in VintagestoryApi\Common\Collectible\ItemStack.cs:line 225
   at Vintagestory.GameContent.BlockEntityClayForm.PutClay(ItemSlot slot) in VSSurvivalMod\BlockEntity\BEClayForm.cs:line 114
   at Vintagestory.GameContent.ItemClay.OnHeldInteractStart(ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, Boolean firstEvent, EnumHandHandling& handling) in VSSurvivalMod\Item\ItemClay.cs:line 110
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel, EnumHandInteract useType, EnumHandHandling& handling) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 862
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 452
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 819
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1023
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 694
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 669
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

```

**Comment by Craluminum2413** [comment] 2024-09-19 11:01
Duplicate of #4098

**Closed by Craluminum2413** 2024-09-19 11:01 UTC
Labels: status: new
