### ISSUE TITLE
Game crashing while trying to join to modified server

### ISSUE THREAD

**Issue by TRKiller** [anegostudios/VintageStory-Issues#2386] opened 2023-02-18 08:27 UTC
I was trying to play on the server with friends. They made a server with some mods, and one of them everyone installed it locally on their own PC because of some bugs. Well, I've tried to install also and play with them, but suddenly I'm getting crashing ever and ever again. They saying that it can happen because the server, for some reason, can't install mods on the client. But nothing works. Same error I'm getting even connecting without any mods
(Btw, everyone says that the server works ok with them, with a mod or without, and I was reinstalling the game twice, and nothing changed)

Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.17.11 (Stable)
18.02.2023 10:19:12: Critical error occurred
Loaded Mods: 
System.NullReferenceException: An object reference does not point to an instance of an object.
   in Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 407
   in Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 718
   in Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 622
   in Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 124
   in System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   in OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   in OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   in OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   in Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   in Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Craluminum2413** [comment] 2023-02-18 09:53
Duplicate of #2380

**Closed by Craluminum2413** 2023-02-18 09:53 UTC

**Comment by TRKiller** [comment] 2023-02-18 09:57
Server does not have any passwords, wtf?

**Comment by Craluminum2413** [comment] 2023-02-18 09:59
The crash log is the same

**Comment by TRKiller** [comment] 2023-02-18 10:00
Well, it CAN be, but server is without any passwords. How it could be possible, if everyone else is ok to join except me?

**Comment by TRKiller** [comment] 2023-02-18 10:02
And also, I was added to whitelist.

**Comment by Craluminum2413** [comment] 2023-02-18 10:03
Are base mods enabled?

**Comment by TRKiller** [comment] 2023-02-18 10:03
wait, brb.

**Comment by TRKiller** [comment] 2023-02-18 10:11
No one answers, but I think yeah, I hope so.
Why?

**Comment by Craluminum2413** [comment] 2023-02-18 10:13
I mean mods on your side

**Comment by TRKiller** [comment] 2023-02-18 10:14
![image](https://user-images.githubusercontent.com/41436009/219854909-922f5d5d-83b3-4aaf-aa47-76aa150d32a3.png)

**Comment by TRKiller** [comment] 2023-02-18 10:15
Guys said to install "Silent Story" Mod, for server.

**Comment by Craluminum2413** [comment] 2023-02-18 10:19
I can't think of anything else that can help you, sorry

**Comment by TRKiller** [comment] 2023-02-18 10:20
I can send video how it happens.

**Comment by TRKiller** [comment] 2023-02-18 10:28
Wanna show you something.

**Comment by TRKiller** [comment] 2023-02-18 10:28
![image](https://user-images.githubusercontent.com/41436009/219855519-afd91955-876c-4d35-877a-72e22a92cf2c.png)

**Comment by TRKiller** [comment] 2023-02-18 10:29
It says that I need to install mods to join server.

**Comment by TRKiller** [comment] 2023-02-18 10:29
AND it's not a server of my friends.
Maybe it's a problem from their side, so that's why i'm keeping getting crashes?
