### ISSUE TITLE
Fruitpress full of berry mash produces less juice than listed.

### ISSUE THREAD

**Issue by VirtualSkeleton** [anegostudios/VintageStory-Issues#1752] opened 2022-02-26 18:20 UTC
**Game Version:** 1.16.4
**Platform:** Windows   
**Modded:** Yes (Simple HUD Clock) 
**SP/MP:** Singleplayer and Multiplayer  

### Description
When loading a full batch of 32 berries into the fruitpress, the block info overlay and wet mash tooltip will both inform the player that 10 liters of juice will be produced. The resultant juice volume from pressing 32 berries ends up being 9.89 liters of juice.

### How to reproduce
1. Place a fruitpress, add bucket.
2. Fill with 32 berries
3. Note block info overlay and wet mash item's juice yield info
4. Juice wet mash
5. Note resultant juice volume in bucket.

### Screenshots
![image](https://user-images.githubusercontent.com/92191842/155854568-265c0b39-fd69-4884-bf70-c7c6f7a0f1e4.png)
![image](https://user-images.githubusercontent.com/92191842/155854575-006e24b1-c1b4-4a13-b104-bffe1f8debfd.png)
![image](https://user-images.githubusercontent.com/92191842/155854607-334d24f6-4ac5-4dbb-b30b-305d1ffe835b.png)

**Comment by l1ving** [comment] 2022-02-26 23:53
See also: #1622, #1529

**Comment by Craluminum2413** [comment] 2022-06-23 21:17
<https://www.reddit.com/r/VintageStory/comments/vj76hn/fruit_press_issue/>

**Comment by Barhandar** [comment] 2022-07-18 11:54
Another way to semi-reliably trigger this issue is to do it in two 5L batches, but put in the second batch without taking mash from the first out. This also erases said mash from existence.

**Comment by Barhandar** [comment] 2022-07-18 12:09
Also (cannot edit because github), berries produce 0.3125L of juice per item, which, if it was ignoring one item, would give 9.69L instead of 9.89. Modded (patched, Expanded Items allows juicing soybeans and grains for food oil) juiceable items that give 0.078125L/item, 1/4th the value exactly, _also_ produce erroneous output of 9.89L, so the error is inherent to the press rather than the juice value.

**Comment by Barhandar** [comment] 2022-07-18 18:49
Also, a mod (Honey Press) that patches honeycombs to produce exactly 1 (not 1.0) liters of honey per comb in the press also has 9.89L output when trying to press 10L.
This is the code responsible for the juicing: https://github.com/anegostudios/vssurvivalmod/blob/9f2f42da65ac74d1aff50f480c6c38769c87890a/BlockEntity/BEFruitpress.cs#L228 
...why does it explicitly convert doubles being assigned to doubles to floats? And the code to fix rounding errors clearly doesn't work/get reached, because it shouldn't even be able to return 9.89.

**Comment by Barhandar** [comment] 2022-08-01 13:08
Pretty sure the deficit is general fluid transfer bug rather than unique to juicing. For example, try putting water into a cooking pot with a bowl - you'll get to 5.99L in the pot and 0.01L (1 unit) in the bowl, and it'll require one more click to transfer the latter (on a server with modded recipient (Expanded Foods small cauldron, effectively a 20L bucket you can place in a firepit) it stopped on 2.99L and refused to move 0.01L, but it does move the last unit in unmodded SP, and fruit press bug isn't based on bucket capacity, just how much juice is already there).  
Thus I think the actual bug is that the fluid code puts less juice in the bucket than `litresToTransfer`, but fruit press deducts the full value from how much juice is present in the mash.

**Comment by Barhandar** [comment] 2022-10-15 08:11
The issue no longer happens in 1.17.6+ or needs a different method to reproduce: normal pressing of 10L, as well as two presses of 5L each, produce 10L in the bucket as expected.

**Comment by Craluminum2413** [comment] 2022-10-15 09:03
Yeah, it seems it was fixed in [1.17.3](https://www.vintagestory.at/forums/topic/9906-stabler-de-jank-and-game-juice-update-1173/#comment-40965:~:text=Fixed%3A%20Fruit%20press%20sometimes%20not%20yielding%2010L%20of%20juice)

**Closed by Craluminum2413** 2022-10-15 09:03 UTC
Labels: status: resolved, department: code
