### ISSUE TITLE
Game crashed when using cooking pot

### ISSUE THREAD

**Issue by astynax777** [anegostudios/VintageStory-Issues#970] opened 2021-06-06 13:27 UTC
**Game Version:** v1.15.0-pre.2
**Platform:** Windows
**Modded:** No

### Description
I'm playing multiplayer with my son and cooked some meat stew for him.  He picked up the cooking pot and tried to eat directly from it and it crashed his game.

### Logs
```
Running on 64 bit Windows with 8 GB RAM 
Version: v1.15.0-pre.2 (Unstable)6/5/2021 11:50:30 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockCookedContainer.OnHeldInteractStart(ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, Boolean firstEvent, EnumHandHandling& handHandling)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel, EnumHandInteract useType, EnumHandHandling& handling)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsNoBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _xArlFw5lpThzIY0BN36UerAlHzU._14ww1iwrPaPwPpAZqZCUdf3d4Sm(Single )
   at _uFwaliVbJcYmzlP3dwic7HSHMr2._EuQCmN4cQf8FBHYrlJxd8EhIdNnA(Single )
   at _uFwaliVbJcYmzlP3dwic7HSHMr2._HlDCi3DfsJHaHE4jniBarrjFlHLB(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _EKato5MKvGk9ELCMKyl4BGVO7pe._ninJWCWaWyMG9ZSA1Eyytms1G5F(_BjQ4x8rTRChySIeXrK1HK1YSqec , String[] )
   at _btwtpE4G1MfBqD34njKFCvBcSRd._ninJWCWaWyMG9ZSA1Eyytms1G5F(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 5/31/2021 8:20:10 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1252239485250825062, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.0.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\gabri\AppData\Local\Temp\RDR482D.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER488C.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER48BB.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER48C9.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4928.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 2050c36e-2439-4cd3-956f-e47c2a9e4c4f
Report Status: 268435456
Hashed bucket: 9a6d16c7ad62a31db160d92d5c17eb66
Cab Guid: 0 }
```

**Comment by Craluminum2413** [comment] 2021-06-06 13:36
Duplicate of #953

**Comment by copygirl** [comment] 2021-06-06 15:37
Indeed. Thank you for reporting it, however.

**Closed by copygirl** 2021-06-06 15:37 UTC
Labels: status: duplicate
