### ISSUE TITLE
Bizarre Save game issue

### ISSUE THREAD

**Issue by Xanzibaar** [anegostudios/VintageStory-Issues#1012] opened 2021-06-15 10:11 UTC
Recent saved games wont load and I cannot recreate any world with the 'Create a new world with this world seed' button

I can create a new game and play it, save it and leave it. If I try to reload it the load screen hangs:

![vintage story crash](https://user-images.githubusercontent.com/5358559/122031623-c955e380-cdc6-11eb-8cf5-f971508970ae.png)

However, If I load older save games over a few days they **_will_** load, I can even save and leave and reopen them successfully. I can load any game in repair mode with the same results as above on loading 'normally'

I do have a few mods installed, I have tried creating a new game with all added mods uninstalled so as to create a vanilla game with the same results.

Also, Using the 'Create a new world with this world seed' button crashes the game with **_any_** saved game:

```Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.10 (Stable)15/06/2021 11:05:34: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at _XdIuBv24vQ1JZohJexy6wrKepcG._plbbXOc9b5uBS8CNUoxbNm2MgS7()
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   at _tQNG2d15aM4IHF2517OUDULPBHL._TqANHNj1JY1XBE9yPv18vWLJBlG(MouseEvent )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _ISiSTzGmXXpAqo3PzdxdVD1bClZ._ofvn0Tr1zNGCbNV3SxvKs2MXNP(_C7CLMRbe3BejVtaARYCgl7Bg1vl , String[] )
   at _0Y0SN1uu1V65pRLxvnN2xsIjXAg._ofvn0Tr1zNGCbNV3SxvKs2MXNP(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 23/05/2021 14:20:31, Site = , Source = Windows Error Reporting, Message = Fault bucket 1999085723610005733, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\*****\AppData\Local\Temp\RDR63C3.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER63E3.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6404.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6440.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER648F.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 3b5a4f91-9195-478c-b3f1-455d4fbdb7f6
Report Status: 268435456
Hashed bucket: ee3def5252484136fbbe2ddfbf5440e5
Cab Guid: 0 }
--------------
{ TimeGenerated = 23/04/2021 10:53:22, Site = , Source = Windows Error Reporting, Message = Fault bucket 1999085723610005733, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Tabi\AppData\Local\Temp\RDR5F3.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER613.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER672.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7F7.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER875.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 9c8a45a3-8d52-4cd3-a997-fbfe1b1bcd8e
Report Status: 268435456
Hashed bucket: ee3def5252484136fbbe2ddfbf5440e5
Cab Guid: 0 }```

**Comment by Craluminum2413** [comment] 2021-06-15 10:32
Can you insert your crash in ``` ```

**Comment by Xanzibaar** [comment] 2021-06-15 10:35
Thanks, Was wondering how i did that!

**Comment by Craluminum2413** [comment] 2021-06-15 10:38
Duplicate of #795

**Closed** 2021-06-15 13:26 UTC
Labels: status: duplicate
