### ISSUE TITLE
Animation bug while digging/mining

### ISSUE THREAD

**Issue by Rebekapocolypse** [anegostudios/VintageStory-Issues#3838] opened 2024-04-23 16:54 UTC
### Game Version

v1.19.7

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Issue where mining animation does not stop after button is released. The animation continues even after switching items or interacting with other objects. Quitting and reloading the world is the only fix I've found. Its happened to me 4 times in the past couple hours of play. Not that big a deal but annoying for sure

### How to reproduce

Mining a block and switching items before the block is done mining seems to cause it. But most often it is caused by a tool breaking and being auto swapped in for a new tool.

### Logs

```Log```

**Comment by TheEaterr** [comment] 2024-04-24 14:36
I have this problem on windows 1.19.7 as well, but my game is vanilla.

**Comment by Craluminum2413** [comment] 2024-04-24 14:40
Duplicate of #3774

**Closed as not planned by Craluminum2413** 2024-04-24 14:40 UTC
Labels: status: duplicate
