### ISSUE TITLE
Text isn't updating in interface windows when cooking/smelting

### ISSUE THREAD

**Issue by Raven651** [anegostudios/VintageStory-Issues#2124] opened 2022-08-19 12:38 UTC
**Game Version:** 1.17.0-rc.5
**Platform:** Linux (Mint)   
**Modded:** No
**SP/MP:** Singleplayer

### Description
Text isn't updating in interface windows when cooking/smelting. Only way to update the text is to leave that interface and re-open it. This makes cooking/smelting incredibly cumbersome because you have to re-open the interface multiple times to see what meal/alloy you're making. 
- Temperature of the fire also does not display at all.
- Progress meter does not update whilst the interface is open (the actual progress does keep going, it's just the display that freezes).
- The 'remaining fuel' flame also does not update, the flame stays in whatever state it was in when the interface was opened.

This was working without issue on the last stable build v1.16.5

### How to reproduce
1. Make any kind of meal on a cooking pot by putting some food in.
2. The interface doesn't update to reflect what you're cooking.

### Screenshots
Putting copper in a crucible, but it doesn't say how much liquid copper will be made:

![Screenshot from 2022-08-19 13-25-47](https://user-images.githubusercontent.com/111576236/185619318-d5ab414d-259a-4357-aedf-aae242f9ee31.png)

Closing and re-opening the crucible interface now displays how much liquid copper will be made:

![Screenshot from 2022-08-19 13-25-58](https://user-images.githubusercontent.com/111576236/185619325-9aeefaa7-88c4-4d5f-bb5c-c5ca5338b55d.png)

Putting fuel in and lighting the fire - temperature is not shown:

![Screenshot from 2022-08-19 13-30-04](https://user-images.githubusercontent.com/111576236/185619332-0d34148c-9cdd-440d-984c-0a3fbaa24a47.png)

After removing copper bits, the interface has not updated to reflect that no copper will be smelted:

![Screenshot from 2022-08-19 13-30-14](https://user-images.githubusercontent.com/111576236/185619339-f3adabe1-2437-4d31-8ad8-d2d4a1db9f76.png)

**Comment by Craluminum2413** [comment] 2022-08-21 08:59
Duplicate of #2106

**Closed by Craluminum2413** 2022-08-21 08:59 UTC
Labels: status: new
