### ISSUE TITLE
Client Crashes when I try to edit a world save.

### ISSUE THREAD

**Issue by DoctorDunlap** [anegostudios/VintageStory-Issues#3076] opened 2023-09-03 18:09 UTC
Running on 64 bit Windows with 32673 MB RAM
Game Version: v1.18.8 (Stable)
9/3/2023 1:04:58 PM: Critical error occurred
Loaded Mods: aculinaryartillery@1.0.15, betterruins@0.2.2, bettertraders@0.0.2, giantgouramis@1.0.1, meteoricexpansion@1.2.4, peacockbasses@1.1.0, pieontheshelf@1.0.0, primitivesurvival@3.2.7, truesunfishes@1.1.0, game@1.18.8, alchemy@1.6.16, animalcages@2.2.0, carryon@1.5.0, expandedfoods@1.6.7, hudclock@3.3.0, simplestep@1.0.8, creative@1.18.8, survival@1.18.8, woodenfortifications@0.0.4, bullseye@2.5.0-rc.1, maltiezfirearms@0.1.10
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Common.WorldConfig.loadWorldConfigValuesFromPlaystyle() in VintagestoryLib\Common\Config\WorldConfig.cs:line 108
   at Vintagestory.Common.WorldConfig.selectPlayStyle(String playstylecode) in VintagestoryLib\Common\Config\WorldConfig.cs:line 99
   at Vintagestory.Common.WorldConfig.loadFromSavegame(SaveGame savegame) in VintagestoryLib\Common\Config\WorldConfig.cs:line 57
   at Vintagestory.Client.GuiScreenSingleplayerModify.initGui(SaveGame savegame) in VintagestoryLib\Client\MainMenu\Screens\Singleplayer\GuiScreenSingleplayerModify.cs:line 52
   at Vintagestory.Client.GuiScreenSingleplayerModify.OnScreenLoaded() in VintagestoryLib\Client\MainMenu\Screens\Singleplayer\GuiScreenSingleplayerModify.cs:line 176
   at Vintagestory.Client.ScreenManager.LoadScreen(GuiScreen screen) in VintagestoryLib\Client\ScreenManager.cs:line 938
   at Vintagestory.Client.GuiScreenSingleplayer.OnClickCellRight(Int32 cellIndex) in VintagestoryLib\Client\MainMenu\Screens\Singleplayer\GuiScreenSingleplayer.cs:line 158
   at Vintagestory.API.Client.GuiElementMainMenuCell.OnMouseUpOnElement(MouseEvent args, Int32 elementIndex) in VintagestoryApi\Client\UI\Elements\Impl\Misc\GuiElementMainMenuCell.cs:line 312
   at Vintagestory.API.Client.GuiElementCellList`1.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementCellList.cs:line 241
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\GuiElement.cs:line 714
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 440
   at GuiScreen.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\MainMenu\Screens\Special\GuiScreen.cs:line 204
   at Vintagestory.Client.ScreenManager.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\ScreenManager.cs:line 883
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 212
   at OpenTK.Windowing.Desktop.NativeWindow.OnMouseUp(MouseButtonEventArgs e)
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.DispatchUpdateFrame()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 312
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 9/3/2023 1:44:35 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1273209627708249444, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.8.0
P3: 6492041a
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAEE9.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB39D.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB40B.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB41B.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB4A9.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_8de098f737c744fcb2cfb2449b6f09668c35b_9d23d9f5_5974a896-e22c-48bb-a13b-93624cd63590

Analysis symbol: 
Rechecking for solution: 0
Report Id: 356beb41-64e7-4d5b-8b40-99c1a19ee4b2
Report Status: 268566528
Hashed bucket: 42c222969642167ad1ab596920285564
Cab Guid: 0 }
--------------
{ TimeGenerated = 9/3/2023 1:44:32 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.8.0, time stamp: 0x6492041a
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x2690
Faulting application start time: 0x01d9de31fcc759b9
Faulting application path: A:\Vintagestory\Vintagestory.exe
Faulting module path: A:\Vintagestory\Lib\openal32.dll
Report Id: 356beb41-64e7-4d5b-8b40-99c1a19ee4b2
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 9/3/2023 1:19:13 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1273209627708249444, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.8.0
P3: 6492041a
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF6FD.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7FE0.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8261.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8405.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8464.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_8de098f737c744fcb2cfb2449b6f09668c35b_9d23d9f5_c4aa57f4-f85e-4d09-bd93-8856f713b4b9

Analysis symbol: 
Rechecking for solution: 0
Report Id: 5cd72ec2-5a67-4281-90e1-c1d8a01abfd6
Report Status: 268566528
Hashed bucket: 42c222969642167ad1ab596920285564
Cab Guid: 0 }

**Comment by Craluminum2413** [comment] 2023-09-03 18:31
Duplicate of #2692

**Closed by Craluminum2413** 2023-09-03 18:31 UTC
