### ISSUE TITLE
Chunks wont generate

### ISSUE THREAD

**Issue by NastyFlytrap** [anegostudios/VintageStory-Issues#4438] opened 2024-11-04 22:59 UTC
### Game Version

v.1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Chunks wont generate and i dont have any mods that alter worldgen

Is there any way to make the game regenerate the missing chunks? It'd be a real shame if my world ended up with empty chunks forever :(

### How to reproduce

I used a translocator that took me about 7000k blocks away from the center of the world and a bit away from where the other half of the translocator is, the game just stops generating chunks.

If it helps, i set the polar equator distance to 25k and the overall size of the world to 256kx256k but im only like 7000k blocks from spawn, diagonally.

Edit: Had to turn on pileful to load the world because of all the stone piles around the world. You may see that in the log, its back on now.

### Screenshots

![2024-11-04_23-57-44](https://github.com/user-attachments/assets/27c8c7f4-9220-435b-b0c3-99e5933dd71e)
![2024-11-04_23-58-28](https://github.com/user-attachments/assets/9d02bc21-7791-485b-8066-4a65eda5c7f6)

### Logs

```Log```
[server-chat.txt](https://github.com/user-attachments/files/17624771/server-chat.txt)
[server-debug.txt](https://github.com/user-attachments/files/17624772/server-debug.txt)
[server-event.txt](https://github.com/user-attachments/files/17624773/server-event.txt)
[server-main.txt](https://github.com/user-attachments/files/17624774/server-main.txt)
[server-storyevent.txt](https://github.com/user-attachments/files/17624775/server-storyevent.txt)
[server-worldgen.txt](https://github.com/user-attachments/files/17624776/server-worldgen.txt)
[client-audit.txt](https://github.com/user-attachments/files/17624777/client-audit.txt)
[client-chat.txt](https://github.com/user-attachments/files/17624778/client-chat.txt)
[client-crash.txt](https://github.com/user-attachments/files/17624779/client-crash.txt)
[client-debug.txt](https://github.com/user-attachments/files/17624780/client-debug.txt)
[client-main.txt](https://github.com/user-attachments/files/17624781/client-main.txt)
[server-audit.txt](https://github.com/user-attachments/files/17624782/server-audit.txt)
[server-build.txt](https://github.com/user-attachments/files/17624783/server-build.txt)

**Comment by Craluminum2413** [comment] 2024-11-05 10:22
Try without any mods, if it doesn't help, reinstall the game

**Comment by NastyFlytrap** [comment] 2024-11-05 19:50
> Try without any mods, if it doesn't help, reinstall the game

I tried without mods(excluding pileful because i cant load the world without it....) and it still happens

**Comment by Craluminum2413** [comment] 2024-11-05 19:53
@NastyFlytrap Try without pileful mod

**Comment by Craluminum2413** [comment] 2024-11-05 19:54
@NastyFlytrap Try new world

**Comment by NastyFlytrap** [comment] 2024-11-05 19:56
> @NastyFlytrap Try new world

What is exactly the problem with this one? I read one of the logs and it said something about it being outside the array but can you explain what that means?

Is my savefile constrained in the amount of bytes it can be and therefore it doesnt have any 'free space' to save more chunks?

**Comment by Craluminum2413** [comment] 2024-11-05 19:57
@NastyFlytrap Something is messing with assets, you could also try reinstall the game

**Comment by NastyFlytrap** [comment] 2024-11-05 20:11
> @NastyFlytrap Something is messing with assets, you could also try reinstall the game

Okay, will try, i just wish i understood what the array thing was about. I know from the little programming i did what a matrix is, like a column and row 'table' of data, but not sure if an array is like that, and also why its limited, in this case

**Comment by NastyFlytrap** [comment] 2024-11-05 22:38
> @NastyFlytrap Something is messing with assets, you could also try reinstall the game

Reinstalled the game, turned on t_he stone pile mod_, earlier i said it was pileful but i was wrong, its the stonepiles mod that i need,

Problem still persists, but now it runs into the problem much sooner, pretty much anything outside the render distance when i step through the translocator is marked as a chunk that wont generate.

**Comment by radfast** [comment] 2024-12-10 15:29
I don't understand why this issue is open here.  It appears to be an issue with mods, please report it to the relevant mod author.  Vanilla (unmodded) Vintage Story version 1.19.8 does not do this in a newly generated world, _ergo_, it is not a Vintage Story issue.

For sure, if a mod is causing errors in code (technically 'Exceptions') for any reason during worldgen, then the world will never correctly generate and there may therefore be missing or incomplete chunks. That's not surprising. The code will not progress beyond an Exception, it will just stop there, and so maybe those chunks never get finished and added to the world.

The errors during worldgen are permanently saved in the file `server-worldgen.txt`, it also tells you the chunk coordinates.  Your `server-worldgen.txt` is full of errors.  All those chunks will be borked, most likely.

One more time, the errors are caused by a mod - in this case, it looks like it was some mod massively altering worldgen parameters for terrain, so that the terragen code then errors.  I don't know your modlist, if it's not immediately clear which mod is the problem, try disabling them all, starting a new world, then adding back one by one (restarting and generating some terrain for each new one) until the problem appears.

Although a skilled coder who knows VintageStory code thoroughly could maybe find the erroring piece of code and make a one off fix, it's really up to the mod author to do that in this case.

**Comment by radfast** [comment] 2024-12-10 15:32
Hmm, just seen @NastyFlytrap you say you don't have any mods which alter worldgen, sorry I missed that line in the issue report.

OK then a team member should try to generate the same world, with the same size parameters and equator distance and the same seed, and see what happens.  _Possibly_ you have found a magic seed which causes a problem in one specific part of the world.... in which case that would be a vanilla issue we should fix.

**Comment by NastyFlytrap** [comment] 2024-12-10 18:57
> Hmm, just seen @NastyFlytrap you say you don't have any mods which alter worldgen, sorry I missed that line in the issue report.
> 
> OK then a team member should try to generate the same world, with the same size parameters and equator distance and the same seed, and see what happens. _Possibly_ you have found a magic seed which causes a problem in one specific part of the world.... in which case that would be a vanilla issue we should fix.

Im not saying its not the mod's fault, however, its not supposed to alter world gen and i cant easily remove it because a single pile block from the mod will crash the game if i try loading it without it, and there is no easy way to just check the entire world for all these piles so i can just manually remove them ingame, so i cant turn the mod off either.

Its a weird scenario where its not supposed to be the fault of the mod, but we cant test without to make sure.

Also, after world generation fails like this, does it attempt to regen the same chunks once i reload the world or are these chunks borked to be dead empty forever? I have reloaded the world many times since making this post and it regenerates chunks in other places, but these few areas where i ran into the bug it still wont, even if i go further away and try to make the game generate new chunks, it still wont generate them in that area of the world, but will generate them in other parts of it

**Comment by radfast** [comment] 2024-12-11 17:51
Right. I've tested an **unmodded** game in 1.19.8 with this worldseed (world 'Voxelland2' with seed 938033360), with mapwidth and mapheight set to 256k blocks, and equator spawn distance 25k.

At (-6028, 125, 4884) chunks generate perfectly OK on my PC.

You didn't specify your full world settings, I assume everything else was on default, but if you adjusted values like Landcover, Landcover scale, Upheaval rate, Landform scale under the "World generation" section of the customise game screen, that would make a difference.

For confirmation you can post your 'Playstyle' text - so on the list of save games, click the pencil icon next to Voxelland2 to edit it, then click the copy button next to 'Playstyle: Standard' and post here what you copied.

For now I'm going to assume it was a correct call to say this is a mod issue / can't reproduce, and close it.   (Will re-open if the playstyle posted shows something else that I can attempt to reproduce)

**Closed by radfast** 2024-12-11 17:51 UTC
Labels: department: code, 3rd party issue

**Comment by radfast** [comment] 2024-12-11 17:55
@NastyFlytrap for completeness what is the crash on removing the mod?  The vanilla game should not crash when loading a block from a mod which has been removed, the vanilla game is designed just to show a ? block which should be inert / incapable of crashing anything.

You could also try the same test I did, i.e. create a new world in 1.19.8 vanilla, with the same seed and height/width and polar/equator distance, and travel to the same spot (you can use `/tp -6028 125 4884`) and see how it looks in vanilla

**Comment by NastyFlytrap** [comment] 2024-12-11 19:19
> @NastyFlytrap for completeness what is the crash on removing the mod? The vanilla game should not crash when loading a block from a mod which has been removed, the vanilla game is designed just to show a ? block which should be inert / incapable of crashing anything.
> 
> You could also try the same test I did, i.e. create a new world in 1.19.8 vanilla, with the same seed and height/width and polar/equator distance, and travel to the same spot (you can use `/tp -6028 125 4884`) and see how it looks in vanilla

{
  "gameMode": "survival",
  "startingClimate": "temperate",
  "spawnRadius": "50",
  "graceTimer": "0",
  "deathPunishment": "drop",
  "droppedItemsTimer": "3600",
  "seasons": "enabled",
  "playerlives": "-1",
  "lungCapacity": "40000",
  "daysPerMonth": "9",
  "harshWinters": "true",
  "blockGravity": "sandgravel",
  "caveIns": "off",
  "allowUndergroundFarming": true,
  "bodyTemperatureResistance": "0",
  "creatureHostility": "aggressive",
  "creatureStrength": "1",
  "playerHealthPoints": "15",
  "playerHungerSpeed": "1",
  "playerHealthRegenSpeed": "1",
  "playerMoveSpeed": "1.5",
  "foodSpoilSpeed": "1",
  "saplingGrowthRate": "1",
  "toolDurability": "1",
  "toolMiningSpeed": "3",
  "propickNodeSearchRadius": "6",
  "globalDepositSpawnRate": "1",
  "microblockChiseling": "all",
  "allowCoordinateHud": true,
  "allowMap": true,
  "colorAccurateWorldmap": true,
  "loreContent": true,
  "clutterObtainable": "ifrepaired",
  "temporalStorms": "sometimes",
  "tempstormDurationMul": "1",
  "temporalStability": true,
  "temporalRifts": "visible",
  "temporalGearRespawnUses": "-1",
  "temporalStormSleeping": "0",
  "worldClimate": "realistic",
  "landcover": "1",
  "oceanscale": "1",
  "upheavelCommonness": "0.3",
  "geologicActivity": "0.05",
  "landformScale": "1.0",
  "worldWidth": "256000",
  "worldLength": "256000",
  "worldEdge": "traversable",
  "polarEquatorDistance": "25000",
  "globalTemperature": "1",
  "globalPrecipitation": "1",
  "globalForestation": "0",
  "surfaceCopperDeposits": "0.12",
  "surfaceTinDeposits": "0.007",
  "snowAccum": "true",
  "allowLandClaiming": true,
  "classExclusiveRecipes": false,
  "auctionHouse": true,
  "playstyle": "surviveandbuild"
}

I turned off every mod, including stone piles, and the world loaded just fine. I have no idea whats wrong. I have removed every stone pile block from the world i could find since making this, but i'd be surprised if i caught all of them, so, idk.

I made a backup of the world before loading it, turned on creative mode, flew to -5950 or so, and 5030 ish, and the big gaping ravine starts there, and its kind of a donut of emptyness around the area in the picture. Couple hundred blocks away, around -5120 and 5050 it starts generating the world again as normal. There is also about 11 badly generated chunks at -5110 4560

Same problem happening at 820 -6140 to 1470 -7080. World stops generating around an area that was generated once i exited the translocator. The first area with its donut was also generated after a translocator, and then the generator just stopped.

I think my other earlier translocator areas are also doing this but i didnt take the effort to give coordinates for those right now. Sttrangely, the translocators i activated after making this post, dont seem to cause this problem.

Yea, can confirm. I went to a translocator area generated later, and it keeps generating and doesnt seem to stop.

I reloaded the world with all of the mods i use, and nothing seems to have changed as far as i can tell. However, i did notice that around the first translocator area, its a square shaped donuts, with four corners at -5121 4096, -7680 4096, -7680 6143, and -5121 6143 as the corners. I presume all the other areas have this square shaped void around them too. No clue why.

**Comment by radfast** [comment] 2024-12-11 22:47
> I turned off every mod, including stone piles, and the world loaded just fine

Clearly a mod issue.

The way the game works is like a pipeline, if anything errors anywhere along the pipeline then the chunk will not complete loading, at least not on the client, and so you won't be able to see it.  The game doesn't have a way to "load everything except this one erroring thing".  Instead, the mod authors are supposed to make their code and mods so that things do not error, they should be able to see the error messages in logs and any visual problems clear as day.

If you want to take this further, you can double-check exactly which mod is the cause (i.e. a new world behaves fine without mod X, but has problems with mod X) then report it to the mod author.

**Comment by NastyFlytrap** [comment] 2024-12-18 19:20
Problem happened again, same long modlist as before. Still no worldgen mods.

Here's the log
18.12.2024 20:17:19 [Notification] Upped server view distance because player is locally connected
18.12.2024 20:17:19 [Notification] Delayed join, need to load one spawn chunk first.
18.12.2024 20:17:19 [Notification] Placing player at 127719.05781298828 110.25 129478.43766767578
18.12.2024 20:17:21 [Event] NastyFlytrap 127.0.0.1 joins.
18.12.2024 20:17:21 [Notification] A client reconnected, resuming game calendar.
18.12.2024 20:17:22 [Error] Failed registering block game:commandblock-normal
18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:commandblock-normal' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271
18.12.2024 20:17:22 [Error] Failed registering block game:conditionalblock-east
18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:conditionalblock-east' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271
18.12.2024 20:17:22 [Error] Failed registering block game:conditionalblock-north
18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:conditionalblock-north' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271
18.12.2024 20:17:22 [Error] Failed registering block game:conditionalblock-west
18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:conditionalblock-west' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271
18.12.2024 20:17:22 [Error] Failed registering block game:conditionalblock-south
18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:conditionalblock-south' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271
18.12.2024 20:17:22 [Error] Failed registering block game:initcommandblock-normal
18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:initcommandblock-normal' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271
18.12.2024 20:17:22 [Error] Failed registering block game:tickerblock-normal
18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:tickerblock-normal' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271
18.12.2024 20:17:22 [Error] Failed registering block game:worldgenhook-normal
18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:worldgenhook-normal' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271
18.12.2024 20:17:22 [Error] Failed registering block game:meta-filler
18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:meta-filler' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271
18.12.2024 20:17:22 [Error] Failed registering block game:meta-pathway
18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:meta-pathway' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271
18.12.2024 20:17:22 [Error] Failed registering block game:meta-underground
18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:meta-underground' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271
18.12.2024 20:17:22 [Error] Failed registering block game:meta-spawner
18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:meta-spawner' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271
18.12.2024 20:17:22 [Error] Failed registering block game:meta-collider
18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:meta-collider' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271
18.12.2024 20:17:22 [Error] Failed registering block game:meta-music
18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:meta-music' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271
18.12.2024 20:17:22 [Error] Failed registering block game:stationarybasket-north
18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:stationarybasket-north' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271
18.12.2024 20:17:22 [Error] Failed registering block game:stationarybasket-east
18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:stationarybasket-east' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271
18.12.2024 20:17:22 [Error] Failed registering block game:stationarybasket-south
18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:stationarybasket-south' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271
18.12.2024 20:17:22 [Error] Failed registering block game:stationarybasket-west
18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:stationarybasket-west' is already in use)
   at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271
18.12.2024 20:17:24 [Warning] Server overloaded. A tick took 1752ms to complete.
18.12.2024 20:18:11 [Notification] Server ticking has been suspended

**Comment by Craluminum2413** [comment] 2024-12-18 19:30
> Problem happened again, same long modlist as before. Still no worldgen mods. Doesnt look like a mod issue to me.
> 
> Here's the log `18.12.2024 20:17:19 [Notification] Upped server view distance because player is locally connected 18.12.2024 20:17:19 [Notification] Delayed join, need to load one spawn chunk first. 18.12.2024 20:17:19 [Notification] Placing player at 127719.05781298828 110.25 129478.43766767578 18.12.2024 20:17:21 [Event] NastyFlytrap 127.0.0.1 joins. 18.12.2024 20:17:21 [Notification] A client reconnected, resuming game calendar. 18.12.2024 20:17:22 [Error] Failed registering block game:commandblock-normal 18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:commandblock-normal' is already in use) at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715 at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271 18.12.2024 20:17:22 [Error] Failed registering block game:conditionalblock-east 18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:conditionalblock-east' is already in use) at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715 at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271 18.12.2024 20:17:22 [Error] Failed registering block game:conditionalblock-north 18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:conditionalblock-north' is already in use) at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715 at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271 18.12.2024 20:17:22 [Error] Failed registering block game:conditionalblock-west 18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:conditionalblock-west' is already in use) at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715 at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271 18.12.2024 20:17:22 [Error] Failed registering block game:conditionalblock-south 18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:conditionalblock-south' is already in use) at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715 at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271 18.12.2024 20:17:22 [Error] Failed registering block game:initcommandblock-normal 18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:initcommandblock-normal' is already in use) at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715 at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271 18.12.2024 20:17:22 [Error] Failed registering block game:tickerblock-normal 18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:tickerblock-normal' is already in use) at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715 at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271 18.12.2024 20:17:22 [Error] Failed registering block game:worldgenhook-normal 18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:worldgenhook-normal' is already in use) at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715 at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271 18.12.2024 20:17:22 [Error] Failed registering block game:meta-filler 18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:meta-filler' is already in use) at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715 at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271 18.12.2024 20:17:22 [Error] Failed registering block game:meta-pathway 18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:meta-pathway' is already in use) at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715 at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271 18.12.2024 20:17:22 [Error] Failed registering block game:meta-underground 18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:meta-underground' is already in use) at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715 at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271 18.12.2024 20:17:22 [Error] Failed registering block game:meta-spawner 18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:meta-spawner' is already in use) at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715 at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271 18.12.2024 20:17:22 [Error] Failed registering block game:meta-collider 18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:meta-collider' is already in use) at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715 at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271 18.12.2024 20:17:22 [Error] Failed registering block game:meta-music 18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:meta-music' is already in use) at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715 at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271 18.12.2024 20:17:22 [Error] Failed registering block game:stationarybasket-north 18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:stationarybasket-north' is already in use) at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715 at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271 18.12.2024 20:17:22 [Error] Failed registering block game:stationarybasket-east 18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:stationarybasket-east' is already in use) at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715 at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271 18.12.2024 20:17:22 [Error] Failed registering block game:stationarybasket-south 18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:stationarybasket-south' is already in use) at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715 at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadBlocks>b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271 18.12.2024 20:17:22 [Error] Failed registering block game:stationarybasket-west 18.12.2024 20:17:22 [Error] Exception: Block must have a unique code ('game:stationarybasket-west' is already in use) at Vintagestory.Server.ServerMain.RegisterBlock(Block block) in VintagestoryLib\Server\ServerMain.cs:line 1715 at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.b__15_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 271 18.12.2024 20:17:24 [Warning] Server overloaded. A tick took 1752ms to complete. 18.12.2024 20:18:11 [Notification] Server ticking has been suspended`

Reinstall the game

**Comment by radfast** [comment] 2024-12-20 03:26
As @Craluminum2413 says.  That log seems full of errors, looks like there are some duplicate files in your game installation, maybe because you've installed a copy manually on top of another copy.  So take the following steps:

*  Take copies of any user files in the game installation folder which you need to keep  (there normally should not be any user files there, normally all the user-generated files are in a different folder found at `%appdata%\VintagestoryData`, unless you changed that)
*  Fully delete the game installation folder, all files
*  Install a fresh download of whichever version you want to play, 1.19.8 probably best if you want to keep all the same mods

Any further crashes, please paste here the **full** `client-main.log` and `server-main.log` log files from the game session which crashed.  It's useful to us to see the full files, not just extracts from them.

**Comment by NastyFlytrap** [comment] 2024-12-20 12:57
> As @Craluminum2413 says. That log seems full of errors, looks like there are some duplicate files in your game installation, maybe because you've installed a copy manually on top of another copy. So take the following steps:
> 
>     * Take copies of any user files in the game installation folder which you need to keep  (there normally should not be any user files there, normally all the user-generated files are in a different folder found at `%appdata%\VintagestoryData`, unless you changed that)
> 
>     * Fully delete the game installation folder, all files
> 
>     * Install a fresh download of whichever version you want to play, 1.19.8 probably best if you want to keep all the same mods
> 
> 
> Any further crashes, please paste here the **full** `client-main.log` and `server-main.log` log files from the game session which crashed. It's useful to us to see the full files, not just extracts from them.
> 
> Note: it's still most likely that any issues you still have in future will be mod issues. There is no "quality control" test for mods on the official modDB, it's possible for a modder to release a mod which is unfinished or causes issues. The most common problem is mods which worked for an older version of the game and now need updating; the mod might _state_ it works with game version X and higher but actually it doesn't ...

Yea i did a fresh install and no crashes like this since then. Emphasis on the 'like this' part because i did crash several times but i know those were mod problems

**Comment by radfast** [comment] 2024-12-22 13:35
Okay good to hear.  Mod problems are just that, mod problems: we do try to minimise "breaking changes" from version to version  but some are inevitable as we add game features or optimizations.  Modders need to check their mods work with latest version and update as necessary.  It's usually only small changes needed, nothing like the hellscape certain other games produce.  You can help by reporting crashes to the relevant mod, they _may_ not be aware
