### ISSUE TITLE
Mushroom Stew appears invisible once cooking has completed

### ISSUE THREAD

**Issue by Rosethorns** [anegostudios/VintageStory-Issues#1963] opened 2022-06-25 04:29 UTC
**Game Version:** 1.17.0.pre.1
**Platform:** Windows
**Modded:** Yes (Carryon, Animal Cages)  
**SP/MP:** Singleplayer

### Description
Any combination of different mushroom types causes the cooking pot or bowl to render empty when it contains the resulting stew

### How to reproduce
1. Make a pot of mushroom stew, use only different mushroom types (Dragons tooth / reshi mushroom / funeral bell / deers ear e.t.c)
2. Once the stew has completed it will render as an empty pot. However the pot will contain the completed meal.
3. If served into a bowl the bowl will also appear to contain nothing but be a valid meal. 

### Expected behavior
For mushroom stew containing various mushrooms to render correctly.

**Comment by tyronx** [comment] 2022-07-02 13:14
hm, i'm not able to reproduce this in pre.2. Is this still an issue?

**Comment by Rosethorns** [comment] 2022-07-02 21:55
The following screenshots are on
Pre.2
Mods Disabled.
Nvidia GTX RTX 2070 driver 30.0.15.1179 (one public version behind due to the latest causing even more issues)
![mushroom1](https://user-images.githubusercontent.com/2171914/177017147-df39c01c-e6d5-4170-824e-8ecabe3d3f71.png)
![mushroom2](https://user-images.githubusercontent.com/2171914/177017152-06256e66-a97b-4b97-8ef0-fd2345c4bf1f.png)
![mushroom3](https://user-images.githubusercontent.com/2171914/177017154-26d2e823-5b84-4c5b-b408-a05219980229.png)
![mushroom4](https://user-images.githubusercontent.com/2171914/177017156-bb4696f0-cd10-4992-a41f-b76ca44f24b9.png)

**Comment by tyronx** [comment] 2022-07-03 09:18
oooh, stew. For some reason i thought it was soup 🤦

**Comment by tyronx** [comment] 2022-07-03 09:29
thanks for the report, fixed in pre3

**Closed by tyronx** 2022-07-03 09:29 UTC
Labels: status: can't reproduce
