### ISSUE TITLE
Writing in Book

### ISSUE THREAD

**Issue by NinaraMamiko** [anegostudios/VintageStory-Issues#2725] opened 2023-05-11 05:38 UTC
### Game Version

v1.18.1 (Stable)

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Every time I try to write in a book I get a crash. 

The only mod I have installed is to heal while you sleep.

### How to reproduce

The book was the recipe that had plain leather only.

My character is sitting before I start to write.

The crash has happened three times. About one sentence in, two in game hours into writing, and about 14 in game hours into writing.

### Logs

`Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.1 (Stable)
5/10/2023 9:16:59 PM: Critical error occurred
Loaded Mods: healingwhilesleepingfix@1.0.1, game@1.18.1, creative@1.18.1, survival@1.18.1
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Vintagestory.GameContent.GuiDialogEditableBook.onTryTextChange(List`1 lines) in VSSurvivalMod\Systems\WritingSystem\GuiDialogEditableBook.cs:line 78
   at Vintagestory.API.Client.GuiElementEditableTextBase.LoadValue(List`1 newLines) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 281
   at Vintagestory.API.Client.GuiElementEditableTextBase.SetValue(String text, Boolean setCaretPosToEnd) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 266
   at Vintagestory.GameContent.GuiDialogReadonlyBook.updatePage(Boolean setCaretPosToEnd) in VSSurvivalMod\Systems\WritingSystem\GuiDialogReadonlyBook.cs:line 174
   at Vintagestory.GameContent.GuiDialogEditableBook.OnKeyDown(KeyEvent args) in VSSurvivalMod\Systems\WritingSystem\GuiDialogEditableBook.cs:line 239
   at Vintagestory.Client.NoObf.GuiManager.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 361
   at Vintagestory.Client.NoObf.ClientMain.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1736
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(Object sender, KeyboardKeyEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 250
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.NativeWindowBase.OnKeyDown(Key key, Boolean repeat) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\NativeWindowBase.cs:line 130
   at OpenTK.Platform.Windows.WinGLNative.HandleKeyboard(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 646
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 828
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1551
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 369
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 5/1/2023 7:23:35 PM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.18.1.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 }
--------------
{ TimeGenerated = 4/20/2023 9:11:13 PM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.18.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 }
--------------
{ TimeGenerated = 4/16/2023 6:59:33 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1880964244831943275, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.11.0
P3: 63e108be
P4: KERNELBASE.dll
P5: 10.0.22621.1555
P6: 235a45d0
P7: c000041d
P8: 000000000008fdec
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.1fc99eb8-6ce6-4d5e-96b8-c7919dec579d.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.ecbdd04e-4bbe-487c-9c20-c08ce79ab918.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.0acf9a58-27ca-430a-a386-31d2aecdc182.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.c684c895-f52f-433f-8c15-d0e5a0d3ae9e.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.36c5ce9c-f4c3-4293-8851-44de99c84f3d.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_9d8cf8972f1bf50868658e3c26e1f54c027de_1112ccc3_fdfb8edf-4887-4cd1-a30b-f6adee82b4cb

Analysis symbol: 
Rechecking for solution: 0
Report Id: cad169e5-6806-4f35-9b4b-ba4c0bf1ea32
Report Status: 268435456
Hashed bucket: 4fd7c6586457998c1a1a8703d06b3a6b
Cab Guid: 0 }

**Comment by Craluminum2413** [comment] 2023-05-11 09:41
Duplicate of #2572

**Closed by Craluminum2413** 2023-05-11 09:41 UTC
Labels: status: new
