### ISSUE TITLE
Crash during sleep

### ISSUE THREAD

**Issue by Cmehotron** [anegostudios/VintageStory-Issues#4345] opened 2024-10-21 20:08 UTC
### Game Version

v1.20.0-pre.6

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Sleeping on a straw bed if there are enemies nearby crashes the server
[client-crash.log](https://github.com/user-attachments/files/17466442/client-crash.log)
[client-debug.log](https://github.com/user-attachments/files/17466443/client-debug.log)
[client-main.log](https://github.com/user-attachments/files/17466444/client-main.log)
[server-audit.log](https://github.com/user-attachments/files/17466445/server-audit.log)
[server-debug.log](https://github.com/user-attachments/files/17466446/server-debug.log)
[server-main.log](https://github.com/user-attachments/files/17466447/server-main.log)

### Logs

Running on 64 bit Windows 10.0.19045.0 with 16333 MB RAM
Game Version: v1.20.0-pre.6 (Unstable)
21.10.2024 23:01:35: Critical error occurred
Loaded Mods: game@1.20.0-pre.6, creative@1.20.0-pre.6, survival@1.20.0-pre.6
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.API.MathTools.SimplexNoiseOctave.Evaluate(Double x, Double y, Double z) in VintagestoryApi\Math\Noise\SimplexOctave.cs:line 414
   at Vintagestory.API.MathTools.SimplexNoise.Noise(Double x, Double y, Double z) in VintagestoryApi\Math\Noise\SimplexNoise.cs:line 117
   at Vintagestory.GameContent.WeatherPattern.RegenCloudTileCache(Vec3i tileOffset) in VSEssentials\Systems\Weather\Model\Impl\WeatherPattern.cs:line 89
   at Vintagestory.GameContent.WeatherDataReaderBase.ensureCloudTileCacheIsFresh(Vec3i tilePos) in VSEssentials\Systems\Weather\WeatherDataReader.cs:line 275
   at Vintagestory.GameContent.CloudRenderer.UpdateCloudTilesOffThread(Int32 changeSpeed) in VSEssentials\Systems\Weather\CloudRenderer.cs:line 390
   at Vintagestory.GameContent.CloudRenderer.<.ctor>b__31_2() in VSEssentials\Systems\Weather\CloudRenderer.cs:line 166

**Comment by Craluminum2413** [comment] 2024-10-21 20:11
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4166

**Closed by Craluminum2413** 2024-10-21 20:11 UTC
Labels: status: new
