### ISSUE TITLE
Watering Can causes index out of range exception

### ISSUE THREAD

**Issue by drewje01** [anegostudios/VintageStory-Issues#4167] opened 2024-09-26 18:13 UTC
### Game Version

V19.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

i will spawn into my world and then it ends up crashing whenever i either swap away from the watering can or hover over it. 

### How to reproduce

1. boot into an official mp server
2. hover over a watering can
3. crash

### Logs

```Running on 64 bit Windows 10.0.22631.0 with 28565 MB RAM
Game Version: v1.19.8 (Stable)
9/26/2024 2:00:09 PM: Critical error occurred
Loaded Mods: game@1.19.8, creative@1.19.8, survival@1.19.8
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.BlockWateringCan.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VSSurvivalMod\Block\BlockWateringCan.cs:line 324
   at Vintagestory.API.Common.ItemStack.GetDescription(IWorldAccessor world, ItemSlot inSlot, Boolean debug) in VintagestoryApi\Common\Collectible\ItemStack.cs:line 400
   at Vintagestory.API.Common.ItemSlot.GetStackDescription(IClientWorldAccessor world, Boolean extendedDebugInfo) in VintagestoryApi\Common\Inventory\ItemSlot.cs:line 475
   at Vintagestory.Client.NoObf.HudMouseTools.OnRequireInfoText(ItemSlot slot) in VintagestoryLib\Client\Systems\Gui\Huds\HudMouseTools.cs:line 167
   at Vintagestory.API.Client.GuiElementItemstackInfo.AsyncRecompose() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementItemstackInfo.cs:line 125
   at Vintagestory.API.Client.GuiElementItemstackInfo.SetSourceSlot(ItemSlot nowSlot, Boolean forceRecompose) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementItemstackInfo.cs:line 252
   at Vintagestory.Client.NoObf.HudMouseTools.OnMouseEnterSlot(ItemSlot slot) in VintagestoryLib\Client\Systems\Gui\Huds\HudMouseTools.cs:line 211
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerOnMouseEnterSlot(ClientMain game, ItemSlot slot) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 516
   at Vintagestory.Client.NoObf.InputAPI.TriggerOnMouseEnterSlot(ItemSlot slot) in VintagestoryLib\Client\API\InputAPI.cs:line 48
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseMove(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 809
   at Vintagestory.API.Client.GuiComposer.OnMouseMove(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 512
   at Vintagestory.API.Client.GuiDialog.OnMouseMove(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 608
   at Vintagestory.Client.NoObf.GuiManager.OnMouseMove(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 433
   at Vintagestory.Client.NoObf.ClientMain.OnMouseMove(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1980
   at Vintagestory.Client.NoObf.ClientPlatformWindows.UpdateMousePosition() in VintagestoryLib\Client\ClientPlatform\Input.cs:line 111
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 7/4/2024 9:55:36 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x864c
Faulting application start time: 0x0x1dace7dc2585486
Faulting application path: C:\Users\jacob\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\jacob\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: a7dafe2c-9157-48e8-8864-aaa861b74f34
Faulting package full name: 
Faulting package-relative application ID:  }```

**Comment by Craluminum2413** [comment] 2024-09-26 18:16
Duplicate of #2829

**Closed by Craluminum2413** 2024-09-26 18:16 UTC
Labels: status: new
