### ISSUE TITLE
Fruit tree crashes game when growing?

### ISSUE THREAD

**Issue by ResplendentOwl** [anegostudios/VintageStory-Issues#1953] opened 2022-06-19 12:46 UTC
**Game Version:** 1.17.0
**Platform:** Windows
**Modded:** No 
**SP/MP:** Singleplayer open to Lan, one additional player.

### Description
Stumbled upon a fruit tree, left it alone. Came back to the server to find game would crash about 2 minutes after loading. Happened consistently for about 4 attempts. Crash log made it sound like a fruit tree was the culprit, we only knew of one that we had seen near or base, so I used /time set to slow down time and we ran at it Matrix style, murdered it with extreme prejudice and it appears to have been the culprit, as the server is doing fine back on normal time now.  It was a young pink apple tree. 

### How to reproduce
Let a young pink apple tree grow

###Logs
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.0-pre.1 (Unstable)
Loaded Mods: game@1.17.0-pre.1, creative@1.17.0-pre.1, survival@1.17.0-pre.1
6/19/2022 8:27:29 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.GenMeshes()
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.GenMesh()
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldForResolving)
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(Packet_BlockEntity p, ClientMain game)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(Packet_Server packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt)
   at Vintagestory.Client.ScreenManager.Render(Single dt)
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 6/16/2022 7:51:12 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1480545446510131094, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.0.0
P3: 10.0.22000.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\johns\AppData\Local\Temp\RDR2527.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.2ea8d4e4-c196-4fbf-be10-53b5d7f472b2.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.4644c00f-0d4b-4108-8f5a-0cea62b1b74f.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.d8182ba9-a428-4339-b832-766fd96ff76b.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.595d2c3b-e3fd-4ee0-a385-2e35b382d824.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 1e4529f3-a518-41b8-b383-0effc0f85f1f
Report Status: 268435456
Hashed bucket: 27186fb1f4fc4f8f048bf43d450ef796
Cab Guid: 0 }
--------------
{ TimeGenerated = 4/6/2022 7:20:54 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1418766722429139843, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.12.14.0
P3: 10.0.22000.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\johns\AppData\Local\Temp\RDRF824.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.19d0d8a7-fd77-4514-85a6-af0dea134d77.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.935f9e46-24fe-4092-9e33-d7a62c6c01c3.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.9721faf8-d08a-449e-96f3-25cef978526f.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.d201b904-c266-4a5e-bc11-5f0547913fed.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: b8f6f06f-da83-4604-bcac-e4860ca638e3
Report Status: 268435456
Hashed bucket: bb36266df17c2bc9a3b078d12d88bb83
Cab Guid: 0 }

**Comment by sirStroam** [comment] 2022-06-28 19:33
duplicate of
https://github.com/anegostudios/VintageStory-Issues/issues/1945

**Closed by sirStroam** 2022-06-28 19:33 UTC
Labels: status: duplicate
