### ISSUE TITLE
Can't "Create a new world with this world seed"

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#1107] opened 2021-07-07 04:24 UTC
**Game Version:** 1.15 pre 12
**Platform:** Windows
**Modded:** No

### Description
Choosing "Create a new world with this world seed" crashes the game.

### How to reproduce
1. Create a new world in pre 11
2. Update to pre 12
3. Go to edit old world and choose an option, "Create a new world with this world seed"

### Logs
```
Running on 64 bit Windows with 8 GB RAM 
Version: v1.15.0-pre.12 (Unstable)7/6/2021 9:17:37 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at _HjEFVfcsddGz5ZvKaPzfASUaO5f._rtbu46smfj0nCJEIJCcCJDsDaj5()
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   at _j3Q25BLCjleAbcybKwHiPmH2Fr6._D2IrBrsDgaHwnfDqbC1koaMERFw(MouseEvent )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _EDzzp7Hpd8xddMDFRXhr1o7oIQY._nqoOnIYMgMUtYNA7RgfEi9wJ0vg(_7pM8onzbt6xQmW4CcyQi8yStDQm , String[] )
   at _j4dcrn2yv0weafHheKLYzSBAck3._nqoOnIYMgMUtYNA7RgfEi9wJ0vg(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 6/25/2021 1:00:03 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1155247148303425079, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.0.0
P3: 60ce51ed
P4: KERNELBASE.dll
P5: 10.0.19041.1023
P6: 924f9cdb
P7: c0020001
P8: 0000000000034b89
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4AC6.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5093.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER50A4.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER50B1.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER50D2.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_ae741ec54f428bb4149b6c904a406339e8e8ae0_b5f6ba0e_952bd34f-2df5-4e35-84a5-8a62c11e9a78

Analysis symbol: 
Rechecking for solution: 0
Report Id: 9f61455d-ea30-4410-9d6d-0d763dfbb948
Report Status: 268566528
Hashed bucket: 6d6ccb91ba3b4c41900843291e689e37
Cab Guid: 0 }
--------------
{ TimeGenerated = 6/25/2021 12:59:50 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.15.0.0, time stamp: 0x60ce51ed
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1023, time stamp: 0x924f9cdb
Exception code: 0xc0020001
Fault offset: 0x0000000000034b89
Faulting process id: 0x4590
Faulting application start time: 0x01d76997df0a94e1
Faulting application path: C:\Users\Sirst\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 9f61455d-ea30-4410-9d6d-0d763dfbb948
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 6/25/2021 12:59:49 AM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FFFE3844B89
Stack:
 }
```

**Comment by copygirl** [comment] 2021-07-07 05:35
Duplicate of #795.

**Closed by copygirl** 2021-07-07 05:35 UTC
Labels: department: code, priority: high, status: confirmed
