### ISSUE TITLE
Chopping Redwood trees crashing the game when the axe breaks.

### ISSUE THREAD

**Issue by BigolBomb** [anegostudios/VintageStory-Issues#2840] opened 2023-06-22 00:33 UTC
### Game Version

v1.18.6 RC1

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Happened twice in a row.  Was raining out, used a stone axe to chop a redwood tree until the axe broke.  Game immediately crashed.  Reloaded and it did save the progress I had made after my axe broke and I still got wood from it.  Made a new axe and tried again and the game crashed again.  Upon reload I collected all the wood and turned it into firewood, and remade the axe.  Tried a different redwood tree and it didn't crash upon the axe breaking.  There was still a small amount of the trunk left of the tree that had crashed twice, so I finished it off and it didn't crash that time.

I have attached the client-main text file from after the 2nd crash.

### How to reproduce

Make a stone axe, chop a large redwood tree until the stone axe breaks.  Whether rain played a factor is unknown as it was still raining when I chopped the other tree that didn't crash.

### Logs

```Log```
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/11827250/client-main.txt)

**Comment by Craluminum2413** [comment] 2023-06-22 10:13
Duplicate of #2792

**Closed by Craluminum2413** 2023-06-22 10:13 UTC
Labels: status: new
