### ISSUE TITLE
Wrong interaction help

### ISSUE THREAD

**Issue by SolatK** [anegostudios/VintageStory-Issues#2018] opened 2022-07-16 03:48 UTC
**Game Version:** 1.17.0 -pre.4
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
To place tool on the ground you need to press ctrl+shift+RMB, but help text says only shift

### How to reproduce
1. Take a shovel
2. Read the help text

### Expected behavior
It should show actual keys

### Screenshots
![изображение](https://user-images.githubusercontent.com/29740451/179337894-0cc910dd-4ea7-4d00-8c69-c6eb26d79b24.png)

**Comment by Craluminum2413** [comment] 2022-07-16 08:29
Duplicate of #1923

**Comment by copygirl** [comment] 2022-07-16 08:37
I knew there was already an issue for this but I couldn't find it. Thank you!

**Closed by copygirl** 2022-07-16 08:37 UTC
Labels: status: duplicate
