### ISSUE TITLE
Crash to desktop while working iron anvil bottom

### ISSUE THREAD

**Issue by maddieknz** [anegostudios/VintageStory-Issues#1545] opened 2022-01-06 17:37 UTC
Running 1.16 rc 7 in single player
Mods: carry capacity, wolf taming
Windows 10

```
Running on 64 bit Windows with 64 GB RAM 
Version: v1.16.0-rc.7 (Unstable)1/6/2022 9:33:37 AM: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.BlockEntityAnvil.OnUpset(Vec3i voxelPos, BlockFacing towardsFace)
   at Vintagestory.GameContent.BlockEntityAnvil.OnUseOver(IPlayer byPlayer, Vec3i voxelPos, BlockSelection blockSel)
   at Vintagestory.GameContent.ItemHammer.OnHeldAttackStop(Single secondsPassed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _kZnNoePSscKtaMrsLcnZzM7kQOH._vh8lE0lsi6qV49UgtRtwC8RpPkc(Single )
   at _v9s5OwLoFIwbBsQUqPlBi0ELsLL._Fm1wLR6sv1UHTAR1QczZauSXAki(Single )
   at _v9s5OwLoFIwbBsQUqPlBi0ELsLL._XT7KTMJZfge9JI2QVT8SFKGJvab(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _HSfZLPMAirScIS5mjRd4VvWVnLR._65zj6UHUrDdAuLFkRrjFq3roWed(_565AC2yiO2B8c5wGvdNFla14mKN , String[] )
   at _sk4DJzd7gnWTJ09LSO3S0BTFXnU._65zj6UHUrDdAuLFkRrjFq3roWed(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 12/21/2021 9:48:36 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2137399946764805085, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.0.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\madde\AppData\Local\Temp\RDRBE.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCF.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE0.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFA.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER11A.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: d69a7242-86a1-466d-88ab-32360f45a84a
Report Status: 268435456
Hashed bucket: 90206cb8882a62a92da991ed59dae3dd
Cab Guid: 0 }
--------------
{ TimeGenerated = 11/3/2021 5:04:51 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1397969068706127840, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.7.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\madde\AppData\Local\Temp\RDRADF1.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAE02.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAE03.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAE20.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAE40.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 1d658d2f-6645-426b-9549-380f47595ed1
Report Status: 268435456
Hashed bucket: a9e621fc64de545c1366957613365fe0
Cab Guid: 0 }
--------------
{ TimeGenerated = 10/1/2021 7:34:05 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1775098558742058606, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.5.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\madde\AppData\Local\Temp\RDRD227.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD228.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD229.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD240.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD260.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: ee57ef09-197f-496b-8f0d-ff16a147979f
Report Status: 268435456
Hashed bucket: d490f7f3f456e29178a26abbfb20d66e
Cab Guid: 0 }
```

**Comment by copygirl** [comment] 2022-01-06 18:13
This bug has been around for a long time: #836

If you can find a specific set of moves that consistently crashes the game, so the developers could pin-point the cause and fix it, that would be amazing!

**Comment by tyronx** [comment] 2022-01-07 18:09
thanks for the report, i improperly fixed this crash, should be fixed for good next release

**Closed by tyronx** 2022-01-07 18:09 UTC
