### ISSUE TITLE
I really didnt know what happend XD

### ISSUE THREAD

**Issue by Kyel** [anegostudios/VintageStory-Issues#328] opened 2019-09-19 11:50 UTC
```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.10.8 (Stable)19.09.2019 13:45:53: Critical error occurred
System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: source
   bei System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
   bei Vintagestory.API.Datastructures.TreeAttribute.Equals(IWorldAccessor worldForResolve, IAttribute other, String currentPath, String[] ignorePaths)
   bei Vintagestory.API.Datastructures.TreeAttribute.Equals(IWorldAccessor worldForResolve, IAttribute other, String currentPath, String[] ignorePaths)
   bei Vintagestory.API.Datastructures.TreeAttribute.Equals(IWorldAccessor worldForResolve, IAttribute other, String[] ignorePaths)
   bei Vintagestory.API.Datastructures.TreeAttribute.IsSubSetOf(IWorldAccessor worldForResolve, IAttribute other)
   bei Vintagestory.API.Datastructures.TreeAttribute.IsSubSetOf(IWorldAccessor worldForResolve, IAttribute other)
   bei Vintagestory.API.Common.GridRecipe.MatchesShapeLess(ItemSlot[] suppliedSlots, Int32 gridWidth)
   bei Vintagestory.Common.InventoryCraftingGrid.FindMatchingRecipe()
   bei Vintagestory.API.Common.InventoryBase.DidModifyItemSlot(ItemSlot slot, ItemStack extractedStack)
   bei Vintagestory.Client.NoObf.GeneralPacketHandler.HandleInventoryUpdate(_ehQmfU5vPEGlEImedLyVanZKc0G packet)
   bei _h1N6rTJ6ncnehAaBwuUON3oyG1K._Zmw4bNmZszArG0h7B1z3Yia4loi(Single )
   bei _kxOxUM1FbTSsF53kBg1jlBiCKTe._2GDmxRgKFi5muRg2LSZqtrxhfId(Single )
   bei _cYGAL9TXFRJCDxj9rGAbTxjbRuc._QkozjPyPbFbvoUlBs8LMgevL8Ed(Single )
   bei _cYGAL9TXFRJCDxj9rGAbTxjbRuc._AE87ipLaLzB8j3PBV7KSLTzLVMH(Single )
   bei _HQGleOFDAHdeAXnBEAgFS9t56mX._1t7viAaCRulB6ss8U22WG3KSwkp(Object , FrameEventArgs )
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _vD3IjtuzqvEFvUJnO6ONrr7lnCc._bo5g2ECiKQA0RQggxwWQHuPgBUA(_O7bJvBa1whsaAWJt2oy0bp4DuqS , String[] )
   bei _6dADBT25ppaAcifqQVwaxF0HNX3._bo5g2ECiKQA0RQggxwWQHuPgBUA(ThreadStart )
-------------------------------

```

**Comment by tyronx** [comment] 2019-09-19 11:52
What did you do to make it happen? Looks like you tried to craft something?

**Comment by tyronx** [comment] 2019-09-19 11:55
Well probably found the cause of it either way, but i cannot verify as i don't know how to reproduce it

**Comment by copygirl** [comment] 2019-10-31 06:59
Should we assume this as addressed and close the issue?

**Comment by tyronx** [comment] 2019-10-31 07:00
yea, quite likely. hasn't appeared again since thing.

**Closed by tyronx** 2019-10-31 07:00 UTC
Labels: status: incomplete, type: bug
