### ISSUE TITLE
Slab snow texture issue

### ISSUE THREAD

**Issue by LeeFowler21** [anegostudios/VintageStory-Issues#3993] opened 2024-07-30 07:48 UTC
### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Sides on a upright slab that has a snow addition has a texture issue that makes it look like it has an edge along a flat surface on the sides.

### How to reproduce

Have an upright slab get covered by snow, have blocks around it.

### Screenshots

![2024-07-29_23-44-46](https://github.com/user-attachments/assets/265693bb-71e7-43e8-bf8f-214c8ffdb2c0)
![2024-07-29_23-45-04](https://github.com/user-attachments/assets/a638d37c-d430-4826-8ccb-ddb9858fdc6f)
![2024-07-30_01-37-40](https://github.com/user-attachments/assets/f99f99d4-56c4-4c94-980a-92249cac9435)
![2024-07-30_01-37-58](https://github.com/user-attachments/assets/87232039-969f-476b-af8b-b68936f556a0)
![2024-07-30_01-38-16](https://github.com/user-attachments/assets/87101c8b-19c3-4761-bc40-d071a8505c53)

### Logs

```Log```

**Comment by IsaacBStark** [comment] 2024-08-07 02:21
#3662 might be the same issue.

**Comment by Craluminum2413** [comment] 2024-08-07 08:39
Duplicate of #3662

**Closed** 2024-08-07 08:38 UTC
Labels: status: new, department: json, department: art
