### ISSUE TITLE
Items from raft not found in inventory after relog

### ISSUE THREAD

**Issue by facemizer** [anegostudios/VintageStory-Issues#4140] opened 2024-09-21 23:45 UTC
### Game Version

v1.20.0-pre.2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Items moved into/out of reed basket on raft are not saved to player inventory

### How to reproduce

1. Place a raft and add a reed chest (I had mine in front seat).
2. Add items to reed chest on raft.
3. Remove items from reed chest (some stacks may disappear when moved).
4. Save & quit world.
5. Items not present in inventory on relog

**Comment by Craluminum2413** [comment] 2024-09-22 09:08
Duplicate of #4130

**Closed by Craluminum2413** 2024-09-22 09:08 UTC
Labels: status: new
