### ISSUE TITLE
Footwear produces glitch player model when stored on ground

### ISSUE THREAD

**Issue by SingABrightSong** [anegostudios/VintageStory-Issues#2942] opened 2023-07-21 03:57 UTC
### Game Version

v.1.18.6

### Platform

Linux

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When holding boots, shoes, or other foot-slot clothing, a player can shift+right-click to store them on the ground. When this is done, the boots render as a glitch-textured player model, which can occupy either one or four spaces in a block as per ground storage, The boots can be picked up and will return to the player's inventory and be usable with no issue.

The issue can be reproduced in both Windows and Linux binaries, in both single-player and multiplayer sessions, in modded and vanilla games, on both .net4 and .net7 builds.

### How to reproduce

1. Hold footwear in right hand
2. Point cross-hair at ground
3. Hold shift
4. Right-click

### Screenshots

![2023-07-20_21-36-55](https://github.com/anegostudios/VintageStory-Issues/assets/1489009/4fbccc86-9b0f-4b65-8fa3-8c2ed4fc04d7)
![2023-07-20_21-41-26](https://github.com/anegostudios/VintageStory-Issues/assets/1489009/ae9ce89c-d968-4733-a25f-7b213dc3e2bc)
![2023-07-20_21-51-00](https://github.com/anegostudios/VintageStory-Issues/assets/1489009/c126bf7f-0abf-4cba-91b2-49395a84fad2)

### Logs

```20.7.2023 21:50:11 [Notification] Client logger started.
20.7.2023 21:50:11 [Notification] Game Version: .net7 Experimental build - v1.18.6 (Unstable)
20.7.2023 21:50:11 [Notification] OpenAL Initialized. Available Mono/Stereo Sources: 255/1
20.7.2023 21:50:11 [Notification] CPU Cores: 16
20.7.2023 21:50:11 [Notification] Available RAM: 31189 MB
20.7.2023 21:50:11 [Notification] Graphics Card Vendor: AMD
20.7.2023 21:50:11 [Notification] Graphics Card Version: 4.6 (Core Profile) Mesa 23.1.3
20.7.2023 21:50:11 [Notification] Graphics Card Renderer: AMD Radeon RX 7900 XT (gfx1100, LLVM 16.0.6, DRM 3.52, 6.3.9-1-default)
20.7.2023 21:50:11 [Notification] Graphics Card ShadingLanguageVersion: 4.60
20.7.2023 21:50:11 [Notification] GL.MaxVertexUniformComponents: 16384
20.7.2023 21:50:11 [Notification] GL.MaxUniformBlockSize: 2147483647
20.7.2023 21:50:11 [Notification] Cairo Graphics Version: 1.17.8
20.7.2023 21:50:11 [Notification] OpenAL Version: 1.1 ALSOFT 1.23.0
20.7.2023 21:50:11 [Notification] C# Framework: .net 7.0.8
20.7.2023 21:50:11 [Notification] Start discovering assets
20.7.2023 21:50:11 [Notification] Found 22 base assets in category lang
20.7.2023 21:50:11 [Notification] Found 0 base assets in category patches
20.7.2023 21:50:11 [Notification] Found 22 base assets in category config
20.7.2023 21:50:11 [Notification] Found 0 base assets in category worldproperties
20.7.2023 21:50:11 [Notification] Found 46 base assets in category sounds
20.7.2023 21:50:11 [Notification] Found 97 base assets in category shapes
20.7.2023 21:50:11 [Notification] Found 72 base assets in category shaders
20.7.2023 21:50:11 [Notification] Found 16 base assets in category shaderincludes
20.7.2023 21:50:11 [Notification] Found 131 base assets in category textures
20.7.2023 21:50:11 [Notification] Found 4 base assets in category music
20.7.2023 21:50:11 [Notification] Found 0 base assets in category dialog
20.7.2023 21:50:11 [Notification] Found 410 base assets in total
20.7.2023 21:50:11 [Notification] Loading sounds
20.7.2023 21:50:11 [Notification] Sounds loaded
20.7.2023 21:50:11 [Notification] (Re-)loaded frame buffers
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass .
20.7.2023 21:50:11 [Notification] Window probably resized, recalculating dialog bounds and recomposing gameloadingscreen...
20.7.2023 21:50:11 [Notification] Begin loading shaders
20.7.2023 21:50:11 [Notification] Load shaders now
20.7.2023 21:50:11 [Notification] Loading shaders...
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass standard.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass particlescube.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass particlesquad.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass sky.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass nightsky.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass woittest.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass transparentcompose.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass debugdepthbuffer.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass helditem.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass chunkopaque.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass chunkliquid.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass decals.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass final.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass gui.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass blur.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass chunktransparent.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass findbright.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass chunktopsoil.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass godrays.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass autocamera.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass blockhighlights.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass wireframe.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass entityanimated.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass luma.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass blit.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass particlesquad2d.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass shadowmapentityanimated.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass shadowmapgeneric.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass texture2texture.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass celestialobject.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass guitopsoil.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass colorgrade.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass guigear.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass ssao.
20.7.2023 21:50:11 [Notification] Loaded Shaderprogramm for render pass bilateralblur.
20.7.2023 21:50:11 [Notification] Cached session key is valid, validating with server
20.7.2023 21:50:11 [Notification] Window was resized to 1920 1080, rebuilding framebuffers...
20.7.2023 21:50:11 [Notification] (Re-)loaded frame buffers
20.7.2023 21:50:11 [Notification] Window probably resized, recalculating dialog bounds and recomposing gameloadingscreen...
20.7.2023 21:50:12 [Notification] Server validation response: Good
20.7.2023 21:50:12 [Notification] Will search the following paths for mods:
20.7.2023 21:50:12 [Notification]     /home/brightsong/ApplicationData/vintagestory/Mods
20.7.2023 21:50:12 [Notification]     /home/brightsong/.config/VintagestoryDataNet7/Mods
20.7.2023 21:50:27 [Notification] Initialized GUI Manager
20.7.2023 21:50:27 [Notification] Initialized Server Connection
20.7.2023 21:50:27 [Notification] Server args parsed
20.7.2023 21:50:27 [Notification] Server main instantiated
20.7.2023 21:50:30 [Notification] Processed server identification
20.7.2023 21:50:30 [Notification] Map initialized
20.7.2023 21:50:30 [Notification] Received server assets
20.7.2023 21:50:30 [Notification] Loading and pre-starting client side mods...
20.7.2023 21:50:30 [Notification] Will search the following paths for mods:
20.7.2023 21:50:30 [Notification]     /home/brightsong/ApplicationData/vintagestory/Mods
20.7.2023 21:50:30 [Notification]     /home/brightsong/.config/VintagestoryDataNet7/Mods
20.7.2023 21:50:30 [Notification] Found 5 mods (2 disabled)
20.7.2023 21:50:30 [Notification] Mods, sorted by dependency: game, creative, survival
20.7.2023 21:50:30 [Notification] Instantiated 101 mod systems from 3 enabled mods
20.7.2023 21:50:30 [Notification] Done loading and pre-starting client side mods.
20.7.2023 21:50:30 [Notification] External Origins in load order: modorigin@/home/brightsong/ApplicationData/vintagestory/assets/creative/, modorigin@/home/brightsong/ApplicationData/vintagestory/assets/survival/
20.7.2023 21:50:30 [Notification] Found 0 external assets in category lang
20.7.2023 21:50:30 [Notification] Found 9 external assets in category patches
20.7.2023 21:50:30 [Notification] Found 54 external assets in category config
20.7.2023 21:50:30 [Notification] Found 25 external assets in category worldproperties
20.7.2023 21:50:30 [Notification] Found 348 external assets in category sounds
20.7.2023 21:50:30 [Notification] Found 3179 external assets in category shapes
20.7.2023 21:50:30 [Notification] Found 13 external assets in category shaders
20.7.2023 21:50:30 [Notification] Found 0 external assets in category shaderincludes
20.7.2023 21:50:30 [Notification] Found 5243 external assets in category textures
20.7.2023 21:50:30 [Notification] Found 67 external assets in category music
20.7.2023 21:50:30 [Notification] Found 18 external assets in category dialog
20.7.2023 21:50:30 [Notification] Found 0 external assets in category compatibility
20.7.2023 21:50:30 [Notification] Reloaded lang file now with mod assets
20.7.2023 21:50:30 [Notification] Compatibility lib: 0 assets added, 0 assets replaced.
20.7.2023 21:50:30 [Notification] JsonPatch Loader: Nothing to patch
20.7.2023 21:50:30 [Notification] Reloaded sounds, now with mod assets
20.7.2023 21:50:30 [Notification] Received 3040 item types from server
20.7.2023 21:50:30 [Notification] Loaded 9252 block types from server
20.7.2023 21:50:30 [Notification] Composed 1 4096x4096 entities texture atlases from 384 textures
20.7.2023 21:50:31 [Notification] Collected 1802 shapes to tesselate.
20.7.2023 21:50:31 [Notification] Composed 1 4096x4096 items texture atlases from 1593 textures
20.7.2023 21:50:31 [Notification] Server launched
20.7.2023 21:50:32 [Notification] Composed 1 4096x4096 blocks texture atlases from 4310 textures
20.7.2023 21:50:32 [Notification] Server assets loaded
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass anvilworkitem.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass lines.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass aurora.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass rift.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass sleepoverlay.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass machinegear.
20.7.2023 21:50:32 [Notification] Started 64 systems on Client:
20.7.2023 21:50:32 [Notification]     Mod 'VSEssentials.dll' (game):
20.7.2023 21:50:32 [Notification]         Vintagestory.ServerMods.Core
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.EntityPartitioning
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.ErrorReporter
20.7.2023 21:50:32 [Notification]         Vintagestory.ServerMods.ModCompatiblityUtil
20.7.2023 21:50:32 [Notification]         Vintagestory.ServerMods.NoObf.ModJsonPatchLoader
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.ModSystemDormancyStateChecker
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.ModSystemItemRendererOptimizer
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.FallingBlockParticlesModSystem
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.CharacterExtraDialogs
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.EntityNameTagRendererRegistry
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.POIRegistry
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.RoomRegistry
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.WeatherSystemCommands
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.WeatherSystemClient
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.WorldMapManager
20.7.2023 21:50:32 [Notification]         Vintagestory.ServerMods.LoadColorMaps
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.ClothManager
20.7.2023 21:50:32 [Notification]     Mod 'VSSurvivalMod.dll' (survival):
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.ModSystemControlPoints
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.SurvivalCoreSystem
20.7.2023 21:50:32 [Notification]         Vintagestory.Client.NoObf.ModSystemBossHealthBars
20.7.2023 21:50:32 [Notification]         Vintagestory.ServerMods.DebugSystem
20.7.2023 21:50:32 [Notification]         Vintagestory.ServerMods.UpgradeTasks
20.7.2023 21:50:32 [Notification]         Vintagestory.ServerMods.ModSystemDetailModeSync
20.7.2023 21:50:32 [Notification]         Vintagestory.ServerMods.ModSystemTiledDungeonGenerator
20.7.2023 21:50:32 [Notification]         Vintagestory.ServerMods.GenFromHeightmap
20.7.2023 21:50:32 [Notification]         Vintagestory.ServerMods.GenMaps
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.MyceliumSystem
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.ModSystemSupportBeamPlacer
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.ModSystemCatchCreature
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.ModSystemGliding
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.ModSystemMeasuringRope
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.ScreenshakeToClientModSystem
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.ResoArchivesSpawnConditions
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.ModSystemAuction
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.ModSystemBlockReinforcement
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.Core
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.ModSystemBoatingSound
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.CharacterSystem
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.MealMeshCache
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.DialogueSystem
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.FruitingSystem
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.ModSystemHandbook
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.ModSystemTutorial
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.ModSystemNightVision
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.ModJournal
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.LiquidItemStackRenderer
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.ModSystemStructureLocator
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.ModLootRandomizer
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.MicroBlockModelCache
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.ModSystemRifts
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.ModSystemRiftWeather
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.ModSleeping
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.TeleporterManager
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.ModTemperature
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.SystemTemporalStability
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.TemporalStabilityEffects
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.ModSystemWearableStats
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.ModSystemEditableBook
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.Mechanics.MechanicalPowerMod
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.TradeHandbookInfo
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.RecipeRegistrySystem
20.7.2023 21:50:32 [Notification]         Vintagestory.GameContent.TraderOutfits
20.7.2023 21:50:32 [Notification]     Mod 'VSCreativeMod.dll' (creative):
20.7.2023 21:50:32 [Notification]         Vintagestory.ServerMods.Core
20.7.2023 21:50:32 [Notification]         Vintagestory.ServerMods.WorldEdit.WorldEdit
20.7.2023 21:50:32 [Notification] Loading shaders...
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass standard.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass particlescube.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass particlesquad.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass sky.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass nightsky.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass woittest.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass transparentcompose.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass debugdepthbuffer.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass helditem.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass chunkopaque.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass chunkliquid.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass decals.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass final.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass gui.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass blur.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass chunktransparent.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass findbright.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass chunktopsoil.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass godrays.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass autocamera.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass blockhighlights.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass wireframe.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass entityanimated.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass luma.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass blit.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass particlesquad2d.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass shadowmapentityanimated.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass shadowmapgeneric.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass texture2texture.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass celestialobject.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass guitopsoil.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass colorgrade.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass guigear.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass ssao.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass bilateralblur.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass anvilworkitem.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass lines.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass aurora.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass rift.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass sleepoverlay.
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass machinegear.
20.7.2023 21:50:32 [Notification] Reloaded shaders now with mod assets
20.7.2023 21:50:32 [Notification] Received level init
20.7.2023 21:50:32 [Notification] Loaded Shaderprogramm for render pass instanced.
20.7.2023 21:50:32 [Notification] Loading world map cache db...
20.7.2023 21:50:32 [Notification] Initialized Music Engine
20.7.2023 21:50:32 [Notification] Texture size is 32 so decal atlas size of 128x128 should suffice
20.7.2023 21:50:33 [Notification] Blocks tesselated
20.7.2023 21:50:33 [Notification] Received level finalize
20.7.2023 21:50:33 [Notification] Loaded Shaderprogramm for render pass clouds.
20.7.2023 21:50:34 [Notification] ===============================================================
20.7.2023 21:50:34 [Notification] (^_^) No issues captured during startup
20.7.2023 21:50:34 [Notification] ===============================================================
20.7.2023 21:50:34 [Notification] Client pause state is now on
20.7.2023 21:50:36 [Notification] Client pause state is now off
20.7.2023 21:50:42 [Notification] Finished fully loading sounds (async)
20.7.2023 21:51:09 [Notification] Client pause state is now on
20.7.2023 21:51:17 [Notification] Destroying game session, waiting up to 200ms for client threads to exit
20.7.2023 21:51:17 [Notification] Stopping single player server
20.7.2023 21:51:17 [Notification] Exiting current game to main menu, reason: leave world button pressed
20.7.2023 21:51:19 [Notification] Exiting game now. Server running=False. Exit reason: Main screen quit button was pressed
```

**Comment by Craluminum2413** [comment] 2023-07-21 09:40
Duplicate of #2862

**Closed by Craluminum2413** 2023-07-21 09:40 UTC
Labels: status: new
