### ISSUE TITLE
Entities turn black during winter

### ISSUE THREAD

**Issue by Londran** [anegostudios/VintageStory-Issues#2151] opened 2022-09-01 19:27 UTC
**Game Version:** 1.17.1  
**Platform:** Windows 
**Modded:** No / Yes (which?)  
ApacheTech.VintageMods.CampaignCartographer_v2.2.2.zip
BetterCrates_v1.4.2.zip
CarryCapacity-VS1.16.0-v0.6.5.zip
ExtraChests_v1.5.2.zip
FarmlandDropsSoil-VS1.15-v1.4.0.zip
PlayerCorpse_v1.17.0-pre.1_v1.3.2.zip
ProspectorInfo-3.2.0.zip
workbench-expansion-1.4.1
 xrowboat_0.0.3
**SP/MP:**  Multiplayer (which?) 

### Description
During winter, entities turn black

### How to reproduce
1. Have a nvidia graphics card (I have RTX3080)
2. Start game
3. Get to winter
4. See how drifters and chickens and rabbits get black

### Expected behavior
Normal textured entities

### Screenshots
![image](https://user-images.githubusercontent.com/5173517/187996325-25a43430-d9f3-4636-a62a-0715d96684c4.png)

**Comment by Craluminum2413** [comment] 2022-09-01 19:35
Can you try without mods?

**Comment by Craluminum2413** [comment] 2022-09-01 19:52
It looks like a frost overlay is a culprit, but I can't reproduce it

**Comment by pvh1987** [comment] 2022-09-01 20:23
The bug affects armor stands and straw dummies as well. At first, when the world is loaded, everything appears normal - but when I move just a little bit, all nearby affected entities turns black.

I investigated this yesterday when upgrading to 1.17.0 from 1.16.5. I found that from 1.17.0-rc.6 the bug is there, but not in earlier versions. The bug is still present in 1.17.1.

![2022-09-01_22-11-06](https://user-images.githubusercontent.com/25091173/188004547-9597ddfb-0698-478e-8353-651ce21f0e5f.png)

**Comment by Londran** [comment] 2022-09-01 20:37
> Can you try to reproduce that without mods?

I tried this, but I saw the issue also without mods.

**Comment by pvh1987** [comment] 2022-09-01 20:40
> > Can you try to reproduce that without mods?
> 
> I tried this, but I saw the issue also without mods.

I do not use any mods at all - I should have mentioned that in my comment above.

**Comment by Londran** [comment] 2022-09-01 20:42
> It looks like a frost overlay is a culprit, but I can't reproduce it

Did you try to reproduce this on a multiplayer server? I do not see the issue on singleplayer.

**Comment by Craluminum2413** [comment] 2022-09-01 20:47
> > It looks like a frost overlay is a culprit, but I can't reproduce it
> 
> Did you try to reproduce this on a multiplayer server? I do not see the issue on singleplayer.

I have tried both singleplayer and server hosted on my pc, no results

**Comment by pvh1987** [comment] 2022-09-01 20:48
> > It looks like a frost overlay is a culprit, but I can't reproduce it
> 
> Did you try to reproduce this on a multiplayer server? I do not see the issue on singleplayer.

Well, my world is a singleplayer world and the problem is there :-)

**Comment by Craluminum2413** [comment] 2022-09-01 20:49
What graphics settings you have?

**Comment by pvh1987** [comment] 2022-09-01 20:50
Here are my settings. I tried to change various settings yesterday but it did not solve the problem.

![image](https://user-images.githubusercontent.com/25091173/188009884-88fab949-928b-4349-8b93-8ba6d422caee.png)

**Comment by Craluminum2413** [comment] 2022-09-01 20:51
Also, what nvidia driver you have?

**Comment by pvh1987** [comment] 2022-09-01 20:53
As mentioned above, I have to move around a bit after the world has loaded. Then in a second or two, things turns black. So you might not see the bug immediately. In my pig farm, the pigs turns black when I get near them. And sometimes, some of the pigs will turn normal. And then black again after a while.

**Comment by pvh1987** [comment] 2022-09-01 20:55
> Also, what your nvidia driver version?

Driver version is 510.85.02. I just upgraded today from 470-something I think, to see if it changed anything. It did not. And on Windows I tested with 512-something.

**Comment by pvh1987** [comment] 2022-09-01 21:01
Endermen in Vintage Story - who would have thought? :smile:

![image](https://user-images.githubusercontent.com/25091173/188011776-73896db9-af4d-47fd-9ffe-be987c1bd142.png)

**Comment by EnigmaticaGH** [comment] 2022-09-01 23:04
Same bug for me in SP or MP. Graphics settings here:
![image](https://user-images.githubusercontent.com/11641630/188026819-d2b4c0e3-2f0b-4ecc-b514-11979a6ad069.png)

Nvidia Control Panel settings (notably Vsync forced on for GSYNC):
![image](https://user-images.githubusercontent.com/11641630/188026888-c6487a13-d777-4417-8e8b-87befbb52bb4.png)

PC Specs including driver version:
![image](https://user-images.githubusercontent.com/11641630/188026976-beb2d89e-11cf-40d6-a069-ba4aaff71545.png)

**Comment by Craluminum2413** [comment] 2022-09-02 14:34
Fixed in [1.17.2](https://www.vintagestory.at/forums/topic/9406-stabler-de-jank-and-game-juice-update-1172/#comment-40205:~:text=Fixed%3A%20Should%20fix%20all%20creatures%20black%20for%20some%20players)

**Closed by Craluminum2413** 2022-09-02 14:34 UTC
Labels: status: new
