### ISSUE TITLE
Server forgeting settings, UDP blocked

### ISSUE THREAD

**Issue by PotatoMagical** [anegostudios/VintageStory-Issues#4560] opened 2024-11-23 15:25 UTC
### Game Version

1.20 pre13

### Platform

Linux

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Hello, I am trying to host server on linux. I have succesfully hosted it on windows and wanted to try linux, did everything by tutorial, added port rules and even completely disabled any kind of firewall, but when I try to connect its says was not able to establish UDP connection. Everytime I run the server I have to turn off whitelist, afterwards I am greeted with this error. Am using debian 12, tried it with ubuntu 24(same), using VPS service that did work with windows, so I think the ports are not the problem rather than some permissions. Server.sh is run as vintagestory usre, running it with root makes no difference.

### Logs

```Log```

**Comment by iForged** [comment] 2024-11-24 00:03
My server is hosted on a VPS running Ubuntu 22.04 server.
The game server version is 1.20-pre13, and I am not experiencing any issues.
It would be helpful to receive the server startup logs from you.

**Comment by radfast** [comment] 2024-12-09 17:28
I believe this is not an issue in VintageStory code.  Linux servers work OK generally.

It sounds like the issue is how Linux is set up on the host machine, I don't think we can help with that. It's simply necessary to allow the running application to send and receive UDP packets as well as TCP packets.

I will close this for now, as being a third-party issue.

**Closed by radfast** 2024-12-09 17:28 UTC
Labels: target: multiplayer, status: new, department: code, version: 1.20
