### ISSUE TITLE
Linux : Lethal freeze when entering world

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#3474] opened 2024-01-19 07:12 UTC
### Game Version

1.16 to 1.19

### Platform

Linux

### Modded

None

### SP/MP

Multiplayer

### Description

Versions : since 1.16, still running on 1.19
With Windows : no problem (but I don't use windows)
With Linux (dual boot) :

- If I enter the world in my base, as soon as the scene begins to render, game freezes. Most of the times, it ends up in CTD after more than 1 min freeze. In this case, I have to load 7,8,10 times the game before expecting to play without a crash.
- If I enter the world from anywhere else, it's ok. But as soon as I get close to my base (so, loading chunks, I guess), the game freezes. But this time, after this very long freeze (between 30s and 60s), I can continue (no CTD).

So, every time I want to quit, I must take a TL to go far away from my base before I quit.
I tried to enter the game from another base than mine, which is far far more developped than my modest base, with heavy chiseling artwork and huge buildings and heavy mechanical power, absolutely no problem.

This freezes seems linked to my own base (which has nothing exotic), and I don't know why. Freeze time has increased slowly from nothing to light, then heavy, then now lethal.

I play on TOPTS (so, vanilla), but in my previous games (1.16 .. 1.18), in solo mode, I had the same problem, though just a few seconds when entering the game, and no crash. But the anomaly was already there. 
The base coords are -1000,-2500 

### Logs

```Log```

**Comment by Saricane** [comment] 2024-01-19 07:44
I can add some little clues :
- A few months ago, a friend hired me his GC (an ATI), I used this card in my hardware instead of mine, no more problem. My GC is a NVIDIA GeForce GTX 750 Ti.
- Another player on TOPTS, who was using sometimes my base, declared once that he experienced some unusual freeze when getting close to the base. But apparently, it was far lighter than the freezes I can see. I have absolutely no idea of the hardware/OS he was playing with.
- To describe more precisely what happen when entering the world : the 3D scene begin to render, most of the time partially. My character is totally freezed, no chat, no keyboard use, I just can wait. The sound is on. Some graphical elements are sometimes rendered after, like chests. Then the music stops, and the game crashes 3/4 seconds after.
- Funny fact : I am freezed, but mobs aren't. One time, I entered the game during a storm, and when the freezing ended, I was already dead, surrounded by a horde of drifters :-)

**Comment by radfast** [comment] 2024-01-19 14:18
Interesting, so it seems like it could be a Nvidia graphics driver issue on Linux, triggered by one of our in-game blocks or other game elements.

The cause is possibly in your base (but you wrote that your base is simple) or some object or entity near your base or underground.  Without testing in code it's impossible to know.

If there is anything relevant in `client-main.txt` log from a game session when this occurred, please share it.

You can also in Settings enable Developer mode, then in the final Settings tab (only shown in Developer mode), enable all the settings there.  That might give useful additional logging in `client-main.txt`.

Otherwise the only way to troubleshoot this I think is for a dev team member, running the game in Debug mode, to join TOPTS and go to those coordinates and see what happens.  Might be we cannot reproduce it due to having different hardware, I don't know yet...

**Comment by radfast** [comment] 2024-01-19 14:21
One more idea: try reducing your view distance to the absolute minimum (32) in the game's Main Menu / Settings.  Then join TOPTS and go to the position.  The small view distance will give us a much better idea of approximately the location of the block causing the issue.

If you don't mind doing that and giving us exact coordinates, then when I get some time this weekend I can go to TOPTS, export chunks from that area as a schematic, and send the schematics to you for individual testing in a flatworld.

**Comment by Saricane** [comment] 2024-01-20 09:08
First of all, thank you radfast for taking time to examine this issue. Very appreciated.
- Dev mode is always activated, it's very useful to understand some little bugs that everybody can report just by reading the additional informations on tooltips. But the 32 distance view is something I tried first, long time ago. It's ok to enter the game immediatly, but I'm still stucked with my bug :
-- I can't move : neighboring chunks does not load, so I can't leave the only loaded chunk
-- as soon as I increase the value (even 64, no more), freeze + CTD again
But you gave me an idea. I should leave the game at different location in the base or just near, and try this method again. If I can increase the view distance without crashing, the problem is not in this area.

- About the logs, I already viewed them, of course, even with all the dev mode logs activated. But as I'm not a dev, I don't see anything here that could be the source of the trouble. I'll provide you the logs at the next crash.
- Finally, I think the better way to find the guilty block type is your idea to extract the schematic of my full base and send them to me, so I can graft this in a creative world. This way, I can take all needed time to remove element after element until the problem is gone. If you can do this extract, just go to -1000,-2500, you'll see a base which frontiers are marked by a rectangular tree fence.

**Comment by Saricane** [comment] 2024-01-20 17:04
Here are the two logs files generated by a crash to desk. Nothing spectacular. And no other file to read.

[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/13998641/client-main.txt)
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/13998642/client-debug.txt)

**Comment by Saricane** [comment] 2024-01-20 17:16
I made a counter intuitive test : I always play with a 192 view distance (my GC is rather weak). I set it to 512 before loading the world. The freeze is still there, but reduced, and I can play !

**Comment by Th3Dilli** [comment] 2024-01-22 14:17
I do not see anything wrong in the logs, but I was able to reproduce the issue on Linux altho it just crashes without a trace so a bit hard to figure out but it seems item stacks rendered and you have a few crates with label,
but the main issue seems to be the debug and error options for opengl, those seem to it down a lot.

So another option would be to disable them on regualr play and when you encounter some issues enable them for logging purposes.

**Comment by Saricane** [comment] 2024-01-22 17:47
Thanks for the tests.
- The debug options are off when I play (except extended logs to have more complete tooltips). All other debug options have been activated just because Radfast asked it to have more logs.
- I did not know that ground staked items and labelled crates were so "expansive". I'll remove both to see if it's better.

**Comment by Saricane** [comment] 2024-01-22 21:44
I removed all the  ground storages, same freeze. Before removing the crates with labels, I counted 84 of them, it's a real "work" to transfer  the contents in trunks. Do you think 84 crates could weight on the balance, before I do this transfer for nothing ?
Another question : is a simple small stone on the ground considered as a ground storage (another player put thousands of them in the undergrounds a few months ago to concentrate drifters spawning in the arena) ?

**Comment by radfast** [comment] 2024-01-23 01:04
Stones on the ground ("Loose stones" block) are not ground storage.   In general, the rendering cost of ground storage depends on the number of items, for example a stack of 64 clay tiles is 4k triangles.  The game can easily handle 1 million triangles or more, so 4k isn't much to ask, but if you had 250 stacks of clay tiles like that then that would be challenging, would probably reduce fps similar to forest.

Sounds to me like the Crates with labels are the most likely cause, because (a) you have a lot of them (84 is a lot!) and (b) the label has its own custom renderer

**Comment by Saricane** [comment] 2024-01-23 15:36
I removed all the labelled crates and recovered a quick and normal game loading. Whatever the view distance chosen. It seems this was really the problem.
Before adapting my real world on TOPTS, one or two last questions : 
- you said the label on the crate has its own renderer, so if I replace labelled crates by anonymous crates, is it ok ?
- is there some other items you know to be "resources consuming", and that players cannot guess ? If so, may be a little wiki page in the technical section could be useful.

**Comment by Th3Dilli** [comment] 2024-01-23 20:54
just fyi I send Saricane their affected base for more local testing

but we need investigate further if we can do something about this other then just replacing crates

further
I tested also on windows and there it does not crash and also does no take that long to load

Nvidia RTX 2080 TI
i7 8700k
32GB RAM

**Comment by Drakker** [comment] 2024-02-24 20:24
I started piling crates with labels in my base on TOPTS too and I get the same thing when I log in, it freezes for a while then it plays fine.

**Comment by Th3Dilli** [comment] 2024-02-27 17:36
we had a deeper look at this and a fix is already on the way, so with the next release that should be fixed

**Closed by Th3Dilli** 2024-02-27 17:36 UTC
Labels: platform: linux, status: confirmed
