### ISSUE TITLE
Mods not activating

### ISSUE THREAD

**Issue by GamerMindset** [anegostudios/VintageStory-Issues#1584] opened 2022-01-14 17:46 UTC
**Game Version:** 1.16.0
**Platform:** Windows 
**Modded:** No / Yes (which?)  Trying
**SP/MP:** Singleplayer 

### Description
Mods aren't activating despite being recognized and turned on in the mod manager. (Their boxes are blue along with the Essentials, creative and survival.) In game they don't show up as blocks or in the handbook as they have previously. It seems to be all three of the mods I play with. I've tried both worlds that have previously used the mods and worlds that have not used the mods previously. I have uninstalled them, redownloaded them and reinstalled them. I've tried reloading mods. And I had just uninstalled and reinstalled the entire game which fixed a different problem. I have also restarted my computer as well.

**Comment by Aledark789** [comment] 2022-01-14 22:10
Should specify which mods and their versions you use.

**Comment by GamerMindset** [comment] 2022-01-14 22:24
The mods are;
golden combs 1.15.10_v1.3.5-rc6
ProspectorInfo 3.1.2
PlayerCorpse v1.16.0-pre.8_v1.3.0

**Comment by copygirl** [comment] 2022-01-15 05:37
Can you upload your `server-main.txt`? Maybe the mods fail to load for some reason or another and there is a "quiet" error.

**Comment by GamerMindset** [comment] 2022-01-15 06:32
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/7874404/server-main.txt)

**Comment by copygirl** [comment] 2022-01-15 14:50
I believe some mods require an update to version 1.16.0 of the game.

PlayerCorpse appears to load fine.
```
14.1.2022 10:28:44 [Notification] Started 71 systems on Server:
[...]
14.1.2022 10:28:44 [Notification]     Mod 'PlayerCorpse_v1.16.0-pre.8_v1.3.0' (playercorpse):
14.1.2022 10:28:44 [Notification]         SharedUtils.ConstantsCore
14.1.2022 10:28:44 [Notification]         SharedUtils.Extensions.LoggerNetwork
14.1.2022 10:28:44 [Notification]         PlayerCorpse.Core
```

FromGoldenCombs might be referencing methods or types that don't exist? (a guess)
```
14.1.2022 10:28:38 [Error] [fromgoldencombs] Exception thrown when attempting to retrieve all types of the assembly FromGoldenCombs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Vintagestory.Common.ModContainer.GetModSystems(Assembly assembly), InnerException: . Will ignore asssembly. Loader exceptions:
14.1.2022 10:28:38 [Error] [fromgoldencombs] System.TypeLoadException: Derived method 'updateMeshes' in type 'FromGoldenCombs.BlockEntities.BECeramicBroodPot' from assembly 'FromGoldenCombs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' cannot reduce access.
14.1.2022 10:28:38 [Error] [fromgoldencombs] System.TypeLoadException: Derived method 'updateMeshes' in type 'FromGoldenCombs.BlockEntities.BEFrameRack' from assembly 'FromGoldenCombs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' cannot reduce access.
14.1.2022 10:28:38 [Error] [fromgoldencombs] System.TypeLoadException: Derived method 'updateMeshes' in type 'FromGoldenCombs.BlockEntities.BELangstrothStack' from assembly 'FromGoldenCombs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' cannot reduce access.
14.1.2022 10:28:38 [Error] [fromgoldencombs] System.TypeLoadException: Derived method 'updateMeshes' in type 'FromGoldenCombs.BlockEntities.BELangstrothSuper' from assembly 'FromGoldenCombs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' cannot reduce access.
14.1.2022 10:28:38 [Error] [fromgoldencombs] An exception was thrown when trying to load assembly:
System.Exception: C:\Users\KarlV\AppData\Roaming\VintagestoryData\Mods\FromGoldenCombs-1.15.10_v1.3.5-rc.6\FromGoldenCombs.dll declared as code mod, but there are no .dll files that contain at least one ModSystem or has a ModInfo attribute
   at Vintagestory.Common.ModContainer.LoadAssembly(ModCompilationContext compilationContext, ModAssemblyLoader loader)
```

Unsure about ProspectorInfo. Did you by chance unzip the .zip file?
```
14.1.2022 10:28:38 [Error] [ProspectorInfo.dll] Missing ModInfoAttribute
```

Either way, this is mod related and the issues you're getting are related to mod installation, so maybe ask for support in the Discord? Check with the mod authors if the mods work with the newest version of the game.

(I'll also keep responding to the issue if you need more help, I'm just closing it because it's not a bug.)

**Closed by copygirl** 2022-01-15 14:50 UTC
Labels: status: invalid, status: new

**Comment by GamerMindset** [comment] 2022-01-15 17:45
Thanks for the assistance. Prospectorinfo is unzipped and in the folder. It shows up in the mod manager in game. Based on a look through of the parts you highlighted, it looks like some parts are missing so I'll redownload and reinstall them to see if that helps, or possibly try a previous version.

**Comment by copygirl** [comment] 2022-01-15 20:46
Do not unzip mods after you download them. The whole .zip files are meant to go into the mods folder.

The reason it still shows up in the mod manager is because it's technically possible to have single .dll files be loaded as mods (though not recommended), so it's still treated as a "sort of valid" mod. However, then none of the other files are treated as part of the same mod.

**Comment by GamerMindset** [comment] 2022-01-15 23:38
Huh, I didn't know that. Redownloaded and put the .zip files in the mod folder. They do show up differently in the mod manager in game. Unfortunately that doesn't seem to have changed their responsiveness in game.

**Comment by copygirl** [comment] 2022-01-16 10:27
FromGoldenCombs definitely needs to be updated by the mod author. ProspectorInfo might have to, as well. Check with the mod author, such as on the forums or Discord.
