### ISSUE TITLE
Honey use description incorrect

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#1227] opened 2021-07-27 04:30 UTC
**Game Version:** 1.15.2
**Platform:** Windows 
**Modded:** No 

### Description
When honey is selected it only displays right-click when you need to sneak and right click

### Screenshots
![image](https://user-images.githubusercontent.com/12073699/127095554-296cfc2e-3129-48d0-b12d-fe0937f97aab.png)

**Comment by copygirl** [comment] 2021-07-27 05:51
Duplicate of #1181?

**Comment by Craluminum2413** [comment] 2021-07-27 09:03
I circled the same area in red in the screenshot in my issue

**Comment by Craluminum2413** [comment] 2021-07-27 13:26
Yes, this is a duplicate

**Comment by tyronx** [comment] 2021-07-27 14:11
duplicate indeed

**Closed by tyronx** 2021-07-27 14:11 UTC
Labels: department: json, status: confirmed
