### ISSUE TITLE
Ladder sides become unlit/pitch black when surrounded by 2 blocks from all sides

### ISSUE THREAD

**Issue by Balduranne** [anegostudios/VintageStory-Issues#142] opened 2018-07-03 02:43 UTC
![2018-07-02_22-28-48](https://user-images.githubusercontent.com/10406037/42195931-4fd845c2-7e49-11e8-8ce4-39c4dddb7ac8.png)
If I remove even one block surrounding it, it goes back to normal.

**Comment by tatsu011** [comment] 2018-07-25 16:40
Does it do this with other blocks?

**Comment by Balduranne** [comment] 2018-07-25 16:51
You mean blocks other than bamboo, or other than ladders?

**Comment by tatsu011** [comment] 2018-07-25 17:33
Other than ladders.

**Comment by tyronx** [comment] 2018-07-25 17:41
It does. The source of the issue is the ambient occlusion system. I fixed some of the dark lighting issue on many plants already. Some blocks either need to be excluded from being AO'ed or somehow make AO work better.

**Comment by tatsu011** [comment] 2018-07-25 17:55
a possible model tag idea "NotFullBlock" which would mark the given model to be excluded from being AO'ed.

**Comment by copygirl** [comment] 2018-07-25 18:30
The ambient occlusion code probably incorrectly treats the dark faces just the same as the sides of the block. If they're in the middle of the block, they should be shaded by the light that's currently in the block itself.

**Comment by tyronx** [comment] 2018-07-26 07:50
@tatsu011 oh there is already a sideAO flag list for block types

**Comment by tatsu011** [comment] 2018-07-31 16:08
This bug should be fixed in the next release.

**Closed by tatsu011** 2018-07-31 16:08 UTC
Labels: status: resolved, target: survival, type: bug
