### ISSUE TITLE
Crates without parchment act as if they have one placed

### ISSUE THREAD

**Issue by Evutra** [anegostudios/VintageStory-Issues#3874] opened 2024-05-11 11:47 UTC
### Game Version

v1.19.7

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Crates with no parchment added to them will act as if they have one, showing a hitbox for drawing when facing it with charcoal in hand, does not consume it when the crate is empty nor filled with something but does block usage of the storage, allowing only to withdraw items since it does not conflict with the drawing convination.

This happen in all crates without parchment.

### How to reproduce

1. Place crate
2. Face with charcoal in hand
3. Center of frontal face of crate has the parchemnt hitbox even dough it does not have a parchment

### Screenshots

![Captura de pantalla 2024-05-11 134649](https://github.com/anegostudios/VintageStory-Issues/assets/87202121/369f8fce-8a9f-4d26-b4eb-8a17c9e2c56a)

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2024-05-11 12:03
Duplicate of #1758

**Closed by Craluminum2413** 2024-05-11 12:03 UTC
Labels: status: new
