### ISSUE TITLE
Server exception on save load

### ISSUE THREAD

**Issue by dann1kid** [anegostudios/VintageStory-Issues#1693] opened 2022-02-11 12:22 UTC
**Game Version:** 1.16.3
**Platform:** Windows 
**Modded:**  Yes 
**SP/MP:** Multiplayer 

### Description
Server throws exception on start game save

### How to reproduce
1. Make a server with listed mods
2. Start it and login
3. It throws this exceptions (I think it can be because of deleting some mods after using)

### Used mods
```
11.2.2022 15:14:56 [Notification] External Origins in load order: modorigin@C:\GSM\servers\4\serverfiles\assets\creative\, modorigin@C:\GSM\servers\4\serverfiles\assets\survival\, mod@2xArmorDurability_v1.0.0.zip, mod@animalcages_v2.0.6.zip, mod@BackpackPackStandard_v1.0.3.zip, mod@BetterDrifters_v2.1.3.zip, mod@CaveContent_v1.0.0.zip, mod@CottageWindows_v1.0.1.zip, mod@CreaturesandCritters1.0.7.zip, mod@fancydoors_v1.16.0-1.1.0.zip, mod@MoreClasses_v1.2.4.zip, mod@MoreDrifterLoot-1.5.1.zip, mod@MoreResin_1.0.zip, mod@MoreRoads 1.4.3.zip, mod@necessaries_v1.16.0-1.1.1.zip, mod@qptech1.6.4.zip, mod@RangedWeapons-0.4.5.zip, mod@wolffix_v1.0.0.zip, mod@alchemy-1.5.8.zip, mod@CarryCapacity-VS1.16.0-v0.6.4.zip, mod@FancyPlanters-v1.0.2.zip, mod@FixBadRecipes-v1.0.1.zip, mod@FixHandbookClutter-v1.0.1.zip, mod@Flint Chisel v1.0.2-VS1.16.0.zip, mod@FromGoldenCombs-1.16.0_v1.3.6-rc.3.zip, mod@medievalexpansion-3.7.1.zip, mod@MorePiles-v1.2.0.zip, mod@MorePilesQuasi-v1.0.1.zip, mod@petai_v1.3.4.zip, mod@PlaceEveryItem-v1.2.1.zip, mod@PlaceEveryItemFromMods-v1.0.1.zip, mod@PlayerCorpse_v1.16.0-pre.8_v1.3.0.zip, mod@ResinRenaissance1.0.1-Fixed.zip, mod@RuinVariants-v1.0.0.zip, mod@StoneBrickRebalance-v1.0.0.zip, mod@StonePathVariants-v1.0.2.zip, mod@StoneQuarry_v1.16.1_v1.6.0.zip, mod@usefulstuff_v2.2.3.zip, mod@wildfarming_v1.2.3.zip, mod@WoodBarrels-v1.0.1.zip, mod@WoodChests-v1.0.2.zip, mod@workbench-expansion-1.4.1.zip, mod@xlib_v0.6.8.zip, mod@ApacheTech.VintageMods.CampaignCartographer_v2.1.0-pre.1.zip, mod@bricklayers-0.8.1.zip, mod@Bullseye 2.2.4.zip, mod@cats_v1.3.1_petai_v1.3.x.zip, mod@Th3Essentials_1.1.5.zip, mod@wildcraft-v1.1.4.zip, mod@wolftaming_v1.3.1_petai_v1.3.x.zip, mod@xskills_v0.6.8.zip, mod@AlphaWeaponPack_v1.2.4.zip, mod@AnMiTech_v1.0.7.zip, mod@TemporalTinkerer_v2.3.4.zip
```

### Logs
```
11.2.2022 15:16:24 [Error] Exception thrown during handling event OnSaveGameLoaded: System.ArgumentNullException: Значение не может быть неопределенным.
Имя параметра: key
   в System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   в System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   в Vintagestory.GameContent.BarrelRecipe.GetNameToCodeMapping(IWorldAccessor world)
   в Vintagestory.ServerMods.RecipeLoader.LoadGenericRecipe[T](String className, AssetLocation path, T recipe, Action`1 RegisterMethod, Int32& quantityRegistered, Int32& quantityIgnored)
   в Vintagestory.ServerMods.RecipeLoader.LoadRecipes[T](String name, String path, Action`1 RegisterMethod)
   в Vintagestory.ServerMods.RecipeLoader.OnSaveGameLoaded()
   в System.Action.Invoke()
   в Vintagestory.Server.ServerEventManager.TriggerSaveGameLoaded()
```

**Comment by copygirl** [comment] 2022-02-11 18:32
Apologies, I will close this issue because it's very likely it was caused by a mod - any mod adding barrel recipes. Seek for help on the forums or Discord. The developers will not be able to reproduce the issue without messing around with mods. If there is an issue with the game code, the mod author can help outline the issue much better, such that the developers can actually fix it.

**Closed by copygirl** 2022-02-11 18:32 UTC
Labels: status: invalid
