### ISSUE TITLE
Crash on server join

### ISSUE THREAD

**Issue by NicodemusZeo** [anegostudios/VintageStory-Issues#4519] opened 2024-11-15 23:28 UTC
### Game Version

v1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Have many hours put into this world (over 70) with my friend and everything was fine until a random crash happened, something on his end said there was a memory issue but for me i cant even load into the game. Nothing was done out of the ordinary for me or him. its not a mod issue as we just disabled all mods and it still happened

### Screenshots

![Screenshot 2024-11-15 182747](https://github.com/user-attachments/assets/18b09ebf-af5c-400d-80a5-61fb6db4908f)

### Logs

[message.txt crash file vintage story.txt](https://github.com/user-attachments/files/17782371/message.txt.crash.file.vintage.story.txt)

**Comment by NicodemusZeo** [comment] 2024-11-15 23:45
so we just wiped my player data and i could join no problem, but i still need my old character. So we figured out it has something to do with my character data.

**Comment by Craluminum2413** [comment] 2024-11-16 10:36
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4202

**Closed by Craluminum2413** 2024-11-16 10:36 UTC
Labels: status: new
