### ISSUE TITLE
Bloomery sometimes allows player to place more fuel than necessary

### ISSUE THREAD

**Issue by eugeneko** [anegostudios/VintageStory-Issues#4076] opened 2024-09-09 08:57 UTC
### Game Version

v1.19.8

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

I know it is intended feature that player cannot put more fuel than necessary into the bloomery, and it usually works this way.

However, it does not work if I add fuel via x5 input.

### How to reproduce

1. Place bloomery
2. Place 4 quartz inside, which is equal to 2 glass and requires 1 charcoal to smelt.
3. Place fuel by 5, it lets me add 4 fuel for some reason.
4. Place fuel by 1 using the same setup (steps 1 and 2), it only lets me add 1 fuel.

Reproduces both in SP and MP.

There are no mods that may have affected blomeries.

Server-side mods:

- ProspectTogether-1.3.0-rc.3
- FarmlandDropsSoil-VS1.15-v1.4.0

### Screenshots

![2024-09-09_12-48-48](https://github.com/user-attachments/assets/12643c80-d526-4759-b7ec-95c4b1672a49)
![2024-09-09_12-48-50](https://github.com/user-attachments/assets/7657f7bf-0c39-43f6-a24d-0905d3fe407a)

**Comment by pingouyn** [comment] 2024-09-10 17:12
Also happened to me yesterday.
Added 20 iron nuggets - iron precisely not one of the 3 iron types - and I could add 5 black coal to the bloomery.  Basically I lost 4 black coal bits.
Hope that helps.

**Comment by maltiez2** [comment] 2024-12-01 13:18
Seems to be already fixed in 1.20, reopen if reproduced in 1.20

**Closed by maltiez2** 2024-12-01 13:18 UTC
Labels: status: new, department: code
