### ISSUE TITLE
Chat links can be clicked even when they're on an inactive tab

### ISSUE THREAD

**Issue by Barhandar** [anegostudios/VintageStory-Issues#2237] opened 2022-10-07 21:06 UTC
**Game Version:** 1.17.6
**Platform:** Windows
**Modded:** Yes
**SP/MP:** Multiplayer

### Description
Clicking the area in chat (including tabs themselves) where, on a different tab, there's a link such as prospecting result listing opens said link.

### How to reproduce
1. Prospect a chunk so that you have links to ores in the Info log tab.
2. Switch to General or Damage log tab. 
3. Click on the area where the link would be if Info log tab was open.
4. Observe that Handbook has opened, on the page of the relevant ore nugget, or main if prospecting result does not have a nugget associated (e.g. halite).

### Expected behavior
The links should only be clickable when the tab with the link is selected.

**Comment by Craluminum2413** [comment] 2022-10-07 21:10
Duplicate of #1096

**Closed by Craluminum2413** 2022-10-07 21:10 UTC
Labels: status: new
