### ISSUE TITLE
Game crashes when the World is loaded

### ISSUE THREAD

**Issue by kadirstyle** [anegostudios/VintageStory-Issues#454] opened 2020-03-07 17:18 UTC
**Game Version:** 1.12.6
**Platform:** Windows 10 
**Modded:** No

### Description
My game crashed, since then every time i try to load the savegame, whole game crashes.
But i can create new worlds without any Problem.

### Expected behavior
Stop crashing ? Maybe..

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.12.6 (Stable)07.03.2020 18:15:31: Critical error occurred
System.IO.EndOfStreamException: Über das Ende des Datenstroms hinaus kann nicht gelesen werden.
   bei System.IO.__Error.EndOfFile()
   bei System.IO.MemoryStream.InternalReadInt32()
   bei Vintagestory.API.Common.EntityAgent.FromBytes(BinaryReader reader, Boolean forClient)
   bei Vintagestory.API.Common.EntityPlayer.FromBytes(BinaryReader reader, Boolean forClient)
   bei Vintagestory.Client.NoObf.ClientSystemEntities.createOrUpdateEntityFromPacket(_SvdsJ8rAj5IJMgybr4V0EiweDqA entitypacket, _CeG6XgwLRetaWBDy7Vuk520qgAQ game, Boolean addToLoadQueue)
   bei Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntityLoadedPacket(_7OUkGToX9NINMWWPfgPKDVWAzxq serverpacket)
   bei _CeG6XgwLRetaWBDy7Vuk520qgAQ._mQhaVaLnY2Z1jjUbgwS7BEeClrG(Single )
   bei _AAX9lxzB4UBE4vpOAjnLc7EGRaAA._ukBPmjLVq1Em3v9POQXsw4ulMUE(Single )
   bei _3bQQdrrneYMg7sUqAp4FsQ2XEfN._lShc2IGpVH0SOA7ydOiSsErkATH(Single )
   bei _3bQQdrrneYMg7sUqAp4FsQ2XEfN._k3aLAIz3swGZO8aqd7pDrKnxALc(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _TPKNmFO93xHjVpa9EspHS9LXWzH._TsFumLr7TNG7iLJEc5uVYqFSeNG(_qRgBLoQrmfmbiUcRN39BpLhs3mN , String[] )
   bei _QHQMScYkRrkBYdQDlv19fyrujIx._TsFumLr7TNG7iLJEc5uVYqFSeNG(ThreadStart )
-------------------------------

**Comment by copygirl** [comment] 2020-03-07 18:45
This is a duplicate of #390. Unfortunately this can happen when the game closes unexpectedly, corrupting the world. You may provide your world as a download in the linked issues.

**Closed by copygirl** 2020-03-07 18:45 UTC
Labels: status: new, type: bug
