### ISSUE TITLE
Crash after save file load

### ISSUE THREAD

**Issue by Primal-Dark** [anegostudios/VintageStory-Issues#469] opened 2020-03-15 03:59 UTC
**No mods installed**
Crash after loading existing save file, regardless of settings.
Note: Save file repair _does_ eliminate the issue.
Running on 64 bit Windows with 24 GB RAM 
Version: **v1.12.8** (Stable)3/14/2020 8:47:40 PM: Critical error occurred

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.EntityItem.FromBytes(BinaryReader reader, Boolean forClient)
   at Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntitySpawnPacket(_9J05IwqX3DMJjYc4TgQdHtYCjUh serverpacket)
   at _DheU0S41ys8PmWwanVxliVufAfL._8pFQWKHqjk1Z0lk74wVtfciws7e(Single )
   at _EBtxK36Ixmcei9M4cHb3yN0CdBY._SBmZIE5zeKBZLld4sDoBkph45oC(Single )
   at _TCuegFvuCG7xQqhWKljGWgaccAS._xnJNZgMqo5oGjGjHTS2kXgpC9eH(Single )
   at _TCuegFvuCG7xQqhWKljGWgaccAS._uw3xmExX4CRVc5TYKty6OJkT52C(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _BjgcNpIFkj1jqrVxzsqeX8AsdOJ._Sxh5j8nPFBKHENmnO5xs7MH8hze(_dWKuoESsZrjrNSOe8XL3edrjaTJ , String[] )
   at _OeweVW96y8iGyqsCmuTDn7vCxyG._Sxh5j8nPFBKHENmnO5xs7MH8hze(ThreadStart )
-------------------------------
```

**Comment by copygirl** [comment] 2020-03-15 06:15
Did anything happen before the repeated crash-on-load? Was there a crash while you where playing? Computer turned off? Power outage? It would be important to know whether this is caused by something ingame.

Related to #468 - same error but closed due to being resolved for the player. This particular error appears to be new and reoccurring though.

**Comment by Primal-Dark** [comment] 2020-03-15 15:08
Come to think of it, my last play session froze after alt-tabbing out for a few minutes and I had to force close the application. I hadn't been able to play again until running the repair.

**Comment by copygirl** [comment] 2020-03-15 21:03
> Come to think of it, my last play session froze after alt-tabbing out for a few minutes [...]

That sounds like a known issue that's being worked on: #330
If you can reproduce this issue any time, maybe you can attempt to collect some information, see Tyron's [comment](https://github.com/anegostudios/VintageStory-Issues/issues/330#issuecomment-598178138).

**Comment by copygirl** [comment] 2020-03-15 21:41
Since all the information is here, the issue is resolved for the user (thanks to repair) and we're tracking protecting against corruptions with #396, I will close this as a duplicate.

**Closed by copygirl** 2020-03-15 21:41 UTC
Labels: status: duplicate
