### ISSUE TITLE
Dedicated multiplayer, attempting to read lore books causes disconnect (potential spoilers)

### ISSUE THREAD

**Issue by user-420** [anegostudios/VintageStory-Issues#4811] opened 2024-12-27 03:34 UTC
### Game Version

v1.20.0-rc.6

### Platform

Server Linux
Game Windows

### Modded

None

### SP/MP

Multiplayer

### Description

**Potential game spoilers below**

When attempting to any of the books of lore from The Resonance Archives causes you to get disconnect from the server for throwing an exception at the server.

Server was created in v1.20.0-rc.4 and is now v1.20.0-rc.6

### How to reproduce

1) Go to the Resonance Archives
2) Pick up any book from the library after the dungeon boss
3) Right click once, it gets added to your journal
4) Right click again and get kicked from the server

### Logs

```
26.12.2024 20:26:17 [Server Event] Player <playername> got removed. Reason: Threw an exception at the server
26.12.2024 20:26:17 [Server Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.StoryStructuresSpawnConditions.GetStoryStructureAt(BlockPos pos) in VSSurvivalMod\Lore\StoryStructuresSpawnConditions.cs:line 132
   at Vintagestory.GameContent.StoryStructureProtection.Event_OnTestBlockAccess(IPlayer player, BlockSelection blockSel, EnumBlockAccessFlags accessType, String& claimant, EnumWorldAccessResponse response) in VSSurvivalMod\Lore\StoryStructureProtection.cs:line 60
   at Vintagestory.Server.ServerSystemBlockSimulation.HandleBlockInteract(Packet_Client packet, ConnectedClient client) in VintagestoryLib\Server\Systems\World\BlockSimulation.cs:line 429
   at Vintagestory.Server.ServerSystemInventory.HandleHandInteraction(Packet_Client packet, ConnectedClient client) in VintagestoryLib\Server\Systems\Inventory.cs:line 255
   at Vintagestory.Server.ServerMain.HandleClientPacket(ConnectedClient client, Byte[] data) in VintagestoryLib\Server\ServerMainNetworking.cs:line 154
   at Vintagestory.Server.ServerMain.ProcessNetMessage(NetIncomingMessage msg, NetServer mainSocket) in VintagestoryLib\Server\ServerMainNetworking.cs:line 147
```

and a different player (same error):

```
26.12.2024 20:23:31 [Server Event] Player <playername2> got removed. Reason: Threw an exception at the server
26.12.2024 20:23:31 [Server Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.StoryStructuresSpawnConditions.GetStoryStructureAt(BlockPos pos) in VSSurvivalMod\Lore\StoryStructuresSpawnConditions.cs:line 132
   at Vintagestory.GameContent.StoryStructureProtection.Event_OnTestBlockAccess(IPlayer player, BlockSelection blockSel, EnumBlockAccessFlags accessType, String& claimant, EnumWorldAccessResponse response) in VSSurvivalMod\Lore\StoryStructureProtection.cs:line 60
   at Vintagestory.Server.ServerSystemBlockSimulation.HandleBlockInteract(Packet_Client packet, ConnectedClient client) in VintagestoryLib\Server\Systems\World\BlockSimulation.cs:line 429
   at Vintagestory.Server.ServerSystemInventory.HandleHandInteraction(Packet_Client packet, ConnectedClient client) in VintagestoryLib\Server\Systems\Inventory.cs:line 255
   at Vintagestory.Server.ServerMain.HandleClientPacket(ConnectedClient client, Byte[] data) in VintagestoryLib\Server\ServerMainNetworking.cs:line 154
   at Vintagestory.Server.ServerMain.ProcessNetMessage(NetIncomingMessage msg, NetServer mainSocket) in VintagestoryLib\Server\ServerMainNetworking.cs:line 147
```

**Comment by radfast** [comment] 2024-12-27 09:29
Duplicate of #4678 

Apologies that this issue is still occurring, as written on #4678 it is fixed from next upcoming version

**Closed** 2024-12-27 12:38 UTC
Labels: status: duplicate, status: resolved
