### ISSUE TITLE
v1.16.0-pre.11 crash to desktop 

### ISSUE THREAD

**Issue by Avalaryon** [anegostudios/VintageStory-Issues#1485] opened 2021-12-19 11:41 UTC
Game Version: v1.16.0-pre.11 
Platform: Windows 
Modded: No 
SP/MP: Singleplayer

### Description
If i click in Handbook on beeswax game crashes to desktop.

### How to reproduce
1. open handbook
2. search for beeswax
3. click on it and game crashes to desktop 

### Screenshots
attached

### Logs
attached
```

[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/7740712/client-crash.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/7740715/client-main.txt)
![2021-12-19_12-33-52](https://user-images.githubusercontent.com/96375125/146673536-6cc7a9b5-2779-498a-b9b1-f70fb67cb99a.png)

**Comment by Craluminum2413** [comment] 2021-12-19 11:44
Duplicate of #1430

**Comment by copygirl** [comment] 2021-12-19 14:15
Closing as duplicate. Thank you for reporting the issue, however!

**Closed by copygirl** 2021-12-19 14:15 UTC
Labels: status: duplicate
