### ISSUE TITLE
Handbook: Game crashes on trying to open any page of items or blocks

### ISSUE THREAD

**Issue by MostStupidCat** [anegostudios/VintageStory-Issues#1218] opened 2021-07-24 11:33 UTC
**Game Version:** 1.15.2 (stable)
**Platform:** Windows
**Modded:** Yes 

### Description
After the transition of the game from version 1.15.1 to version 1.15.2, when you open any page with a description of a block or object, the game instantly crashes
There are a decent number of mods, but the error occurred only after switching to a new version of the game

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.2 (Stable)24.07.2021 16:12:30: Critical error occurred
System.Exception: Can't create itemstack without block!
   в Vintagestory.API.Common.ItemStack..ctor(Block block, Int32 stacksize)
   в Vintagestory.GameContent.BlockVines.GetDrops(IWorldAccessor world, BlockPos pos, IPlayer byPlayer, Single dropQuantityMultiplier)
   в Vintagestory.API.Common.Block.GetHandbookDropsFromBreakDrops(ItemStack handbookStack, IPlayer forPlayer)
   в Vintagestory.API.Common.CollectibleObject.GetHandbookInfo(ItemSlot inSlot, ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor)
   в Vintagestory.API.Client.GuiHandbookItemStackPage.GetPageText(ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor)
   в Vintagestory.GameContent.GuiDialogHandbook.initDetailGui()
   в Vintagestory.API.Client.GuiElementHandbookList.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   в Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   в Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   в Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args)
   в Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args)
   в Vintagestory.Client.NoObf.ClientMain.OnMouseUp(MouseEvent args)
   в Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   в System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   в System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   в OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   в OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   в OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   в OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   в _DlY2IRaBbEwZdipnKtrb40WUzTZ._kVFD8SxIojOmGrxNtThdBHagQeh(_7hnpozI2lFsAA8Wa5CIiUgRAbXjA , String[] )
   в _gCIDaxCwdS0mkZub2rV5ATdV3hOA._kVFD8SxIojOmGrxNtThdBHagQeh(ThreadStart )
-------------------------------

```

**Comment by copygirl** [comment] 2021-07-24 12:09
Another example in #1217, looking up charred bread:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.AssetLocation.ResolveToDomainAndPath(String domainAndPath, String& domain, String& path)
   at Vintagestory.API.Common.CollectibleObject.GetHandbookInfo(ItemSlot inSlot, ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor)
   at Vintagestory.API.Client.GuiHandbookItemStackPage.GetPageText(ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor)
   at Vintagestory.GameContent.GuiDialogHandbook.initDetailGui()
   [...]
```

**Comment by tyronx** [comment] 2021-07-24 12:32
njuuuuuu :<

**Comment by tyronx** [comment] 2021-07-24 12:38
These are are 2 different bugs though. I fixed the bread one, but I cannot reproduce the originally reported crash, which presumably happens on wildvine?

**Comment by copygirl** [comment] 2021-07-24 12:49
@MostStupidCat Please provide a list of mods.

**Comment by Gaara23** [comment] 2021-07-25 05:15
> 
> 
> @MostStupidCat Please provide a list of mods.

Most likely the Survival Handbook Categories mod. It creates a crash when looking at item pages.

**Comment by MostStupidCat** [comment] 2021-07-25 05:28
I thought the same way and tried to find the problematic mod by removing
the mods one by one, but I never found the problematic one, but I will
continue to find out what is the reason. Perhaps some mods are in conflict
with each other, since I have about 30 of them (maybe I really went too far
with them).

вс, 25 июл. 2021 г. в 10:15, Gaara23 ***@***.***>:

**Comment by MostStupidCat** [comment] 2021-07-25 05:53
I finally found the problematic mod! This was Lumberjacks version 0.0.7. I will assume that the types of trees that the mod added began to conflict with those that appeared in the update. The only strange thing is that the error occurred only on version 1.15.2

**Comment by copygirl** [comment] 2021-07-25 05:58
The [Lumberjacks VSModDB](https://mods.vintagestory.at/show/mod/226) page does say "This is deprecated, please do not use it in new worlds!" and it's not marked as compatible with the new 1.15 update. Though it's likely not necessary anymore, I did test with the Survival Categories mod and found no issue.

**Closed by copygirl** 2021-07-25 05:58 UTC
Labels: priority: high, status: resolved
