### ISSUE TITLE
Map has blank white and brown areas

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#165] opened 2018-08-01 17:15 UTC
1.6 rc1, public test server

Map shows some randomly shaped areas in white and others, less in size, in dark brown.
I can't understand what in the world makes the map show that color.

![2018-08-01_20-09-09](https://user-images.githubusercontent.com/25122345/43537275-8d7f55ec-95c7-11e8-92e0-cb2d4f1ecfeb.png)
![2018-08-01_20-10-34](https://user-images.githubusercontent.com/25122345/43537276-8da3f94c-95c7-11e8-992e-e49aed83d9fc.png)

**Comment by tyronx** [comment] 2018-08-02 11:16
Caused by broken rainheight map values in pre 1.6 worlds. Added a command to rebuild the rain height map

**Comment by tyronx** [comment] 2018-08-03 18:05
is now fixed

**Closed by tyronx** 2018-08-03 18:05 UTC
Labels: status: in-progress, target: survival, type: bug

**Comment by Heptagon-ru** [comment] 2018-08-04 17:56
Map is awesome!
