### ISSUE TITLE
MacOS crash on startup

### ISSUE THREAD

**Issue by Chadm199** [anegostudios/VintageStory-Issues#2016] opened 2022-07-15 00:25 UTC
**Game Version:**1.16.5 
**Platform:**  / Mac / 
**Modded:** No / Yes (which?)  
**SP/MP:** Singleplayer / 

### Description
game crashes immediately on startup.  2015 MacBook Pro running Mojave.  I also have a new Mac (m1) that will run the game but buggy.  I know about the known issues/no support with Mac so I got my older Mac with a clean install of Mojave to try.  no luck.  game won't load at all.  

### How to reproduce
1. Make a '....'
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Game Version: v1.16.5 (Stable)
Loaded Mods: 
7/14/2022 4:44:07 PM: Critical error occurred
System.DllNotFoundException: Lib64/libnanosvg.dylib assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) NanoSvg.SvgNativeMethods.nsvgCreateRasterizer()
  at Vintagestory.Client.NoObf.SvgLoader..ctor (Vintagestory.API.Client.ICoreClientAPI _capi) [0x0000d] in <8316c93e98ed421da4237893dc4beacf>:0 
  at _9WdOtDnyBYGeAa2UvBC4bj5etZX..ctor (_8UC8FAMhwKY89IbtSRDjsNSApPJ , Vintagestory.API.Client.ICoreClientAPI ) [0x00030] in <8316c93e98ed421da4237893dc4beacf>:0 
  at _t6FF3Aj7eFoo7JoXLFzqHwjKXzF..ctor (_8UC8FAMhwKY89IbtSRDjsNSApPJ ) [0x00025] in <8316c93e98ed421da4237893dc4beacf>:0 
  at _8UC8FAMhwKY89IbtSRDjsNSApPJ._vvUTh6X5xLRNnjtX2xSE7z8yMeh (_SUsdg1ytavxaRcNNkhfDrODGhGP , System.String[] ) [0x00000] in <8316c93e98ed421da4237893dc4beacf>:0 
  at _7zNxEbLnuy6Bq08TdMSIu9ZbrKf._vvUTh6X5xLRNnjtX2xSE7z8yMeh (_SUsdg1ytavxaRcNNkhfDrODGhGP , System.String[] ) [0x003bf] in <ba2a76e506144f5084a46453a8f22fe3>:0 
  at _7zNxEbLnuy6Bq08TdMSIu9ZbrKf+_qZniT2fgiisIkqrp5iz6vEDMUVc._ZnDyalsB0FQk8So5sLBjhW87hXD () [0x00000] in <ba2a76e506144f5084a46453a8f22fe3>:0 
  at _yA4PJazdKq1OMm8H6js6v5AhQB._vvUTh6X5xLRNnjtX2xSE7z8yMeh (System.Threading.ThreadStart ) [0x00007] in <8316c93e98ed421da4237893dc4beacf>:0 

```

**Comment by copygirl** [comment] 2022-07-15 05:01
Thanks you for the report.
Though this is a duplicate of #1629.

**Closed by copygirl** 2022-07-15 05:01 UTC
Labels: status: duplicate
