### ISSUE TITLE
Omok table top offset

### ISSUE THREAD

**Issue by Zelger98** [anegostudios/VintageStory-Issues#2603] opened 2023-04-17 06:40 UTC
### Game Version

v1.18.0-rc.5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

The omok pieces do not seem to be placed correctly being offset by one squere south and one squere east.

### How to reproduce

Place any piece on a omok table top and it should be offset

### Screenshots

https://user-images.githubusercontent.com/126715524/232404316-46dc29b4-ac13-4009-8750-60b16cf45da2.mp4

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2023-04-17 08:20
Duplicate of #2562

**Closed** 2023-04-17 12:16 UTC
Labels: status: duplicate
