### ISSUE TITLE
strange colors in grass and bushes

### ISSUE THREAD

**Issue by Thor8472** [anegostudios/VintageStory-Issues#2752] opened 2023-05-18 14:38 UTC
![2023-05-18_16-19-23](https://github.com/anegostudios/VintageStory-Issues/assets/86563431/c1cd7ce3-4ab7-4ee9-924d-576c0da94cf6)

1.18.4

**Comment by Craluminum2413** [comment] 2023-05-18 16:04
Duplicate of #2452

**Comment by noelle-lavenza** [comment] 2023-05-18 18:39
No it isn't. This is a separate issue, relating to the bushes not having the leaf wind mode flag set, causing it to *not* be wrapped when it should be. It is quite literally the inverse of that issue.

**Comment by Craluminum2413** [comment] 2024-09-30 17:07
Closing due to inactivity

**Closed by Craluminum2413** 2024-09-30 17:07 UTC
Labels: status: new, department: code, version: 1.18
