### ISSUE TITLE
Crash by loading Savegame

### ISSUE THREAD

**Issue by BigDavinci** [anegostudios/VintageStory-Issues#425] opened 2020-03-05 16:13 UTC
**Game Version:** 1.12.6
Platform: Windows 
Modded: No 

I accidentally pressed the shutdown button on my laptop. After I started my leptop again and tried to load my game it crashed. I can start my second game without any problems.

```
Running on 64 bit Windows with 12 GB RAM 
Version: v1.12.6 (Stable)05.03.2020 16:52:45: Critical error occurred
System.IO.EndOfStreamException: Über das Ende des Datenstroms hinaus kann nicht gelesen werden.
   bei System.IO.__Error.EndOfFile()
   bei System.IO.MemoryStream.InternalReadInt32()
   bei Vintagestory.API.Common.EntityAgent.FromBytes(BinaryReader reader, Boolean forClient)
   bei Vintagestory.API.Common.EntityPlayer.FromBytes(BinaryReader reader, Boolean forClient)
   bei Vintagestory.Client.NoObf.ClientSystemEntities.createOrUpdateEntityFromPacket(_SvdsJ8rAj5IJMgybr4V0EiweDqA entitypacket, _CeG6XgwLRetaWBDy7Vuk520qgAQ game, Boolean addToLoadQueue)
   bei Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntityLoadedPacket(_7OUkGToX9NINMWWPfgPKDVWAzxq serverpacket)
   bei _CeG6XgwLRetaWBDy7Vuk520qgAQ._mQhaVaLnY2Z1jjUbgwS7BEeClrG(Single )
   bei _AAX9lxzB4UBE4vpOAjnLc7EGRaAA._ukBPmjLVq1Em3v9POQXsw4ulMUE(Single )
   bei _3bQQdrrneYMg7sUqAp4FsQ2XEfN._lShc2IGpVH0SOA7ydOiSsErkATH(Single )
   bei _3bQQdrrneYMg7sUqAp4FsQ2XEfN._k3aLAIz3swGZO8aqd7pDrKnxALc(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _TPKNmFO93xHjVpa9EspHS9LXWzH._TsFumLr7TNG7iLJEc5uVYqFSeNG(_qRgBLoQrmfmbiUcRN39BpLhs3mN , String[] )
   bei _QHQMScYkRrkBYdQDlv19fyrujIx._TsFumLr7TNG7iLJEc5uVYqFSeNG(ThreadStart )
-------------------------------

Event Log, last 3 entries
==================================
{ TimeGenerated = 05.03.2020 16:39:42, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund eines internen Fehlers in der .NET-Laufzeit beendet. bei IP 00007FFBA6E9957B (00007FFBA6CB0000) mit Exitcode 80131506.
 }
{ TimeGenerated = 05.03.2020 11:48:10, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: Ausnahmecode c0020001, Ausnahmeadresse 00007FFBB732A839
Stapel:
   bei System.Environment._Exit(Int32)
   bei System.Environment._Exit(Int32)
   bei System.Environment.Exit(Int32)
   bei System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   bei OpenTK.NativeWindow.OnClosedInternal(System.Object, System.EventArgs)
   bei System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   bei OpenTK.Platform.Windows.WinGLNative.HandleDestroy(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   bei OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   bei OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   bei OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   bei OpenTK.Platform.Windows.WinGLNative.DestroyWindow()
   bei OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   bei OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   bei OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   bei OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   bei OpenTK.Platform.Windows.Functions.PeekMessage(OpenTK.Platform.Windows.MSG ByRef, IntPtr, Int32, Int32, OpenTK.Platform.Windows.PeekMessageFlags)
   bei OpenTK.Platform.Windows.Functions.PeekMessage(OpenTK.Platform.Windows.MSG ByRef, IntPtr, Int32, Int32, OpenTK.Platform.Windows.PeekMessageFlags)
   bei OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   bei OpenTK.GameWindow.Run(Double, Double)
   bei _hCuHXesCXlp0LGSdrsPFpw4up5n._mOm8EuKIvHpaJoztxNWRpAoOpbM(_55ISULxdcpPfF8D2JP831aWhOBe, System.String[])
   bei _iCfIbY24GyBXP5lAwqsSlD9COxC._mOm8EuKIvHpaJoztxNWRpAoOpbM(System.Threading.ThreadStart)
   bei _hCuHXesCXlp0LGSdrsPFpw4up5n._HDnbZ9U7ok6mEhsXb9UbGfTHtaF(System.String[])
 }
```

**Comment by copygirl** [comment] 2020-03-05 19:12
I'm going to mark this as a duplicate of #390, but thank you for reporting. It means if Tyron meant to fix the (presumably) corrupted world crashing, it didn't work properly. In the linked issue, upload your world file, so Tyron can have a look at and potentially fix it. (He recommends using WeTransfer.)

**Closed by copygirl** 2020-03-05 19:12 UTC
Labels: status: duplicate
