### ISSUE TITLE
Crashing Repeatedly tryin to join a server I was playhing on

### ISSUE THREAD

**Issue by Frondale** [anegostudios/VintageStory-Issues#3538] opened 2024-01-29 23:29 UTC
### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

I was dragging a vanilla dummy from my backpack to my tool bar and then it crashed to desktop immediately. Every time I try to join it is crashing and giving an error report. I cannot log into  the server I had been playing fine on. The server owner has tried to fix this but we are at a loss now.

### How to reproduce

I was dragging a dummy from backpack to the toolbar.

### Logs

Running on 64 bit Windows 10.0.19045.0 with 16342 MB RAM
Game Version: v1.19.3 (Stable)
30/01/2024 9:48:38 AM: Critical error occurred
Loaded Mods: angelbelt@1.5.0, bedrespawner@1.0.0, betterruins@0.3.0, carpet@1.0.2, chiseltools@1.10.1, decor@1.0.13, justmoreruins@0.9.8, millwright@1.1.3, primitivesurvival@3.4.5, qptech@1.14.2, roas@1.0.0, temporal_gears_stack@1.0.0, game@1.19.3, zoombuttonreborn@1.6.0, abcsreborn@0.1.5, egocaribautomapmarkers@3.1.0, betterfirepit@1.1.3, carryon@1.7.2, commonlib@2.3.2, cuniculture@1.0.2, decoclock@0.9.3, hudclock@3.4.0, jopainting@1.4.0, sailboat@1.2.6, medievalexpansion@3.13.1, moreplaster@1.0.1, nbcartographer@2.0.9, playerlist@1.7.2, qpquests@1.0.0-pre.1, rivers@1.2.0, stonebakeoven@1.1.2, storagecontroller@1.0.6, th3expansion@1.2.0, usefulstuff17@1.3.0, vanvar@3.3.0, creative@1.19.3, survival@1.19.3, workbenchexpansion@1.8.0, em@2.5.0-pre.1, gespileslib@1.1.1, helvehammerext@1.6.0, onebedsleeping@2.3.0, playercorpse@1.9.0, bricklayers@2.5.0-pre.2, gespilesgran@1.0.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityItemRenderer.LoadModelMatrix(ItemRenderInfo renderInfo, Boolean isShadowPass, Single dt) in VSEssentials\EntityRenderer\EntityItemRenderer.cs:line 280
   at Vintagestory.GameContent.EntityItemRenderer.DoRender3DOpaque(Single dt, Boolean isShadowPass) in VSEssentials\EntityRenderer\EntityItemRenderer.cs:line 150
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderFrameShadows(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 177
   at Vintagestory.API.Client.DummyRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in VintagestoryApi\Client\API\IClientEventAPI.cs:line 83
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 199
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 799
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 862
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 723
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 675
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 650
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 30/01/2024 9:39:55 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.3.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x3304
Faulting application start time: 0x01da5307c81d09b9
Faulting application path: C:\Users\Owner\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\Owner\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: f1c99c56-b72d-4d54-94fb-33a4532f4477
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 29/01/2024 3:29:29 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.3.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x2344
Faulting application start time: 0x01da526fbf88b03c
Faulting application path: C:\Users\Owner\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\Owner\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: bb4f69d8-c8a6-4d07-931a-7f32f00f98cf
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 29/01/2024 2:21:45 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.3.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x3410
Faulting application start time: 0x01da526575cdbcf4
Faulting application path: C:\Users\Owner\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\Owner\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 7bf21797-4f3a-48c8-be7d-3dc9a66121af
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Frondale** [comment] 2024-01-29 23:47
We just solved my issue. It seems the zoom button mod I only use in single player was causing conflict with the server.

**Comment by Craluminum2413** [comment] 2024-02-04 09:24
Duplicate of #3529

**Closed by Craluminum2413** 2024-02-04 09:24 UTC
Labels: status: new
