### ISSUE TITLE
Crash when breaking (glitched) fruit tree

### ISSUE THREAD

**Issue by DejFidOFF** [anegostudios/VintageStory-Issues#1731] opened 2022-02-20 20:28 UTC
Game Version 1.16.3
Platform: Windows 10 21H1   
Modded: HUD Clock 2.7.0
Singleplayer

Breaking buttom part of glitched fruit tree by axe causing game crash.
If I try to break everything up thats ok.

Log:

```
Running on 64 bit Windows with 20 GB RAM 
Game Version: v1.16.3 (Stable)
Loaded Mods: game@1.16.3, hudclock@2.7.0, creative@1.16.3, survival@1.16.3
20.02.2022 21:25:17: Critical error occurred
System.NullReferenceException: Odkaz na objekt není nastaven na instanci objektu.
   v Vintagestory.GameContent.BlockFruitTreeBranch.GetTreeFellingBehavior(BlockPos pos, Vec3i fromDir, Int32 spreadIndex)
   v Vintagestory.GameContent.ItemAxe.FindTree(IWorldAccessor world, BlockPos startPos)
   v Vintagestory.GameContent.ItemAxe.OnBlockBreaking(IPlayer player, BlockSelection blockSel, ItemSlot itemslot, Single remainingResistance, Single dt, Int32 counter)
   v Vintagestory.API.Common.Block.OnGettingBroken(IPlayer player, BlockSelection blockSel, ItemSlot itemslot, Single remainingResistance, Single dt, Int32 counter)
   v Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.ContinueBreakSurvival(BlockSelection blockSelection, Block block, Single dt)
   v Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   v Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   v Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   v Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   v Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   v _TcPKe0ld0EAbHR8YsMG1OLy9q8O._vg1QFi5yvtdWtcWdYGzwV9j9PVf(Single )
   v _SbWHHe8Ad6lBV8IRbvWFqut7ren._mSnyaJUIQhBb8A1j3UUn7uh5BBO(Single )
   v _SbWHHe8Ad6lBV8IRbvWFqut7ren._b365Cpnna1p8GSaDyyO3EH2VfOD(Single )
   v Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   v System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   v OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) v C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:řádek 476
   v OpenTK.GameWindow.DispatchRenderFrame() v C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:řádek 452
   v OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) v C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:řádek 375
   v _muFH2BhSjNKo8GSc2o33Nm6Ckup._SwLkq72vc0vcc3OnHXTAS19pm9p(_tVmXPdKJ3JBDWFc8tBtvgftcfhl , String[] )
   v _XL1Xa21FKJVFetNmIumId5p6UDU._SwLkq72vc0vcc3OnHXTAS19pm9p(ThreadStart )
-------------------------------
```

![2022-02-20_21-27-13](https://user-images.githubusercontent.com/98642082/154862992-52fb5d14-4d50-4530-9a45-a90c29cdb241.png)

![2022-02-20_21-27-16](https://user-images.githubusercontent.com/98642082/154862996-83d2b58d-ac6b-4f76-8474-dd23970f810c.png)

**Comment by copygirl** [comment] 2022-02-20 21:12
Does the crash cause this glitched fruit tree?
Or was the glitched fruit tree generated like this? Or caused by another bug?

**Comment by DejFidOFF** [comment] 2022-02-20 21:22
Yes, crash cause this glitched fruit tree, but only when attemp to break the buttom part. And yes it was generated in the wild like this.

**Comment by copygirl** [comment] 2022-02-20 21:24
Sorry, you said the glitched tree (being made of 2 different tree types) was both generated like this AND caused by trying to cut it down? It can't be both. Which is it again?

**Comment by DejFidOFF** [comment] 2022-02-21 08:37
Yes it was generated like this. And trying to cut down the pink apple tree cutting causing the crash. If you break a leaves and cutting from yellow part its ok.

**Comment by DejFidOFF** [comment] 2022-02-21 09:04
May be one part of the tree  was generated in 1.16 ( 1.16.1) and second in 1.16.3 after I come back to the chunk.

**Comment by tyronx** [comment] 2022-02-24 06:41
thanks for the report, this should be fixed next release

**Closed by tyronx** 2022-02-24 06:41 UTC
Labels: status: new
