### ISSUE TITLE
Server side AfterActiveSlotChanged is broken

### ISSUE THREAD

**Issue by maltiez2** [anegostudios/VintageStory-Issues#3406] opened 2024-01-07 11:44 UTC
### Game Version

1.19.0-pre.6

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

`Vintagestory.Server.ServerEventManager.TriggerAfterActiveSlotChanged(IServerPlayer player, int fromSlot, int toSlot)` calls `InvokeSafeCancellable` instead of `InvokeSafe` when invoking `AfterActiveSlotChanged` that results in game trying to cast `Action<IServerPlayer, ActiveSlotChangeEventArgs>` to `Func<IServerPlayer, ActiveSlotChangeEventArgs, EnumHandling>` that results in crash.

### How to reproduce

Add handler to `ICoreServerAPI.Event.AfterActiveSlotChanged`

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/71325062/d7beea6e-5343-4280-9f65-47c4772e34c2)
![image](https://github.com/anegostudios/VintageStory-Issues/assets/71325062/4d5e77ad-79b5-4a07-bcc0-7715e28e573a)

### Logs

```6.1.2024 00:26:40 [Error] Exception when invoking 'AfterActiveSlotChanged':
6.1.2024 00:26:40 [Error] Exception: Unable to cast object of type 'System.Action`2[Vintagestory.API.Server.IServerPlayer,Vintagestory.API.Common.ActiveSlotChangeEventArgs]' to type 'Vintagestory.API.Common.Func`3[Vintagestory.API.Server.IServerPlayer,Vintagestory.API.Common.ActiveSlotChangeEventArgs,Vintagestory.API.Common.EnumHandling]'.
at Vintagestory.API.Common.EventHelper.<>c__DisplayClass1_0`2.<InvokeSafeCancellable>b__0(Delegate handler) in VintagestoryLib\Common\API\EventHelper.cs:line 32
at Vintagestory.API.Common.EventHelper.InvokeSafeCancellable(Delegate ev, ILogger exceptionLogger, String eventName, Func`2 mapper) in VintagestoryLib\Common\API\EventHelper.cs:line 69  ```

**Comment by tyronx** [comment] 2024-01-28 12:38
Duplicate of #3172

**Closed by tyronx** 2024-01-28 12:38 UTC
Labels: status: new, version: 1.19
