### ISSUE TITLE
Game crashes in a few minutes after joining a singleplayer world opened to the internet

### ISSUE THREAD

**Issue by KatyushaKlk** [anegostudios/VintageStory-Issues#4747] opened 2024-12-20 10:37 UTC
### Game Version

v1.20.0-rc.5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Hello, thank you for the game, my friend and I both play on the vanilla 1.20.0-rc.5 version of the game. My friend runs the game on Windows 11 and I run the game on Windows 10.

Whenever my friend opens his game to the internet, we can play together for about 5 to 10 minutes until I **inevitably crash** (see the logs below). My friend's game **doesn't crash** and he can continue playing normally, but I am not able to join his world until he **reloads** it.

It seems like I'm disconnected from the server a few seconds before the crash because I can't interact with the world during this time lapse.

It doesn't seem like my friend or myself were doing any specific action at the moment of the crashes.

Do you need more information?

### How to reproduce

1. Player A loads a single player world and opens it to the internet.
2. Player B joins the game.
3. Player B crashes after 5 to 10 minutes.
4. Player A must close, load, and reopen his world to the internet, otherwise player B won't be able to join again.

### Logs

```Running on 64 bit Windows 10.0.19045.0 with 16333 MB RAM
Game Version: v1.20.0-rc.5 (Unstable)
12/18/2024 11:08:46 PM: Critical error occurred
Loaded Mods: game@1.20.0-rc.5, creative@1.20.0-rc.5, survival@1.20.0-rc.5
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityBehaviorPlayerPhysics.OnRenderFrame(Single dt, EnumRenderStage stage) in VSEssentials\Entity\Behavior\BehaviorPlayerPhysics.cs:line 352
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 188
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 824
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 161
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 334
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93```

**Comment by Craluminum2413** [comment] 2024-12-21 11:43
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4559

**Closed by Craluminum2413** 2024-12-21 11:43 UTC
Labels: status: new, department: code, version: 1.20
