### ISSUE TITLE
Crashing when joining Multiplayer world (Open to LAN)

### ISSUE THREAD

**Issue by Azuzuzuli** [anegostudios/VintageStory-Issues#2083] opened 2022-07-31 22:26 UTC
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.0-rc.3 (Unstable)
Loaded Mods: game@1.17.0-rc.3, carrycapacity@0.6.5, creative@1.17.0-rc.3, survival@1.17.0-rc.3
7/31/2022 5:18:10 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.ClientMain.ProcessServerReady() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:line 1923
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:line 1138
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 381
   at Vintagestory.Client.ScreenManager.Render(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:line 704
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:line 608
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 125
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 87
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 7/26/2022 7:27:29 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2177858694758095880, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.0.0
P3: 10.0.19044.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\azuzu\AppData\Local\Temp\RDR8372.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8382.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER83A3.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER83C0.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER83FF.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 397c9791-48d7-47b4-b104-163951595b89
Report Status: 268435456
Hashed bucket: cd7dc5185a521ef09e394ef1b00d5c08
Cab Guid: 0 }
--------------
{ TimeGenerated = 6/11/2022 6:03:07 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1381417961401207149, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.5.0
P3: 10.0.19044.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\azuzu\AppData\Local\Temp\RDR5931.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5942.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5962.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER597C.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER59BC.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 7b679bf5-f1ed-4963-bdd2-5b600c91e6c7
Report Status: 268435456
Hashed bucket: 6ce2bbf81ba2523d132bc8511ba9c96d
Cab Guid: 0 }
--------------
{ TimeGenerated = 2/11/2022 3:59:16 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2017630819501840923, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.3.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\azuzu\AppData\Local\Temp\RDRD3A6.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD3B6.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD3D7.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD3F4.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD433.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: b41758c9-065a-4678-a634-1d05048eb0dd
Report Status: 268435456
Hashed bucket: 3f5d984b56cce389fc00108a5c499a1b
Cab Guid: 0 }

**Comment by Craluminum2413** [comment] 2022-08-01 11:58
Duplicate of #2046

**Closed by Craluminum2413** 2022-08-01 11:58 UTC
Labels: status: new
