### ISSUE TITLE
Support Beams get stuck in Chiseled Blocks

### ISSUE THREAD

**Issue by n4sr** [anegostudios/VintageStory-Issues#2959] opened 2023-07-27 07:22 UTC
### Game Version

v1.18.7

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

If you initiate the placement of a support beam on a chiseled block the beam is misaligned and permanently becomes apart of the chiseled block. You cannot remove the support beam without completely destroying the chiseled block. Copying the block in creative mode will also keep the bugged support beam within it.

### How to reproduce

1. Chisel a block.
2. Right-click with a support beam anywhere on the chiseled block to start placing a beam.
3. Right-click anywhere to finish placing the support beam.
4. The beam will now be misaligned and stuck within the chiseled block.

### Screenshots

![1](https://github.com/anegostudios/VintageStory-Issues/assets/54733427/7f4392ce-da5b-49a9-8fe8-a8245eed1eda)
![2](https://github.com/anegostudios/VintageStory-Issues/assets/54733427/12704d81-96fb-45aa-8653-89ab2d8f8e05)
![3](https://github.com/anegostudios/VintageStory-Issues/assets/54733427/487f6ca5-e64e-4e79-a8ea-e73503ded0e1)
![4](https://github.com/anegostudios/VintageStory-Issues/assets/54733427/2e53a92e-d157-4416-adb9-38dbd34e3eaa)

### Logs

```Log```

**Comment by VallenFrostweaver** [comment] 2023-07-27 07:46
Can confirm

**Comment by Craluminum2413** [comment] 2023-07-27 12:44
Duplicate of #2785

**Closed by Craluminum2413** 2023-07-27 12:44 UTC
Labels: status: new
