### ISSUE TITLE
"Shadow chunk" issue persists

### ISSUE THREAD

**Issue by 0nymous** [anegostudios/VintageStory-Issues#2320] opened 2022-12-13 19:34 UTC
### Game Version

v.1.17.9

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Certain chunks will render anomalously in an ominous fashion:
- The chunk is completely dark/covered by shadow from the outside despite being exposed to daytime light.
- Certain vertical objects (trees) appear to be cut off on the chunk's border.
- Upon entering the chunk the soundtrack stops and the cavern or underground musical cues begin to play - this is linked to the darkness issue.

The issue is quite rare: I've encountered the shadow chunks twice while travelling through a distance of 30 000 blocks in a single direction. Both of them were found during 1.17.9 world generation, however.

To my knowledge this is a longstanding issue, but the only mention I've found of it is here:
https://www.vintagestory.at/forums/topic/3366-shadowed-chunk/

### How to reproduce

1. Enter any world
2. Search the world loading new chunks until the issue is visible - unfortunately there doesn't seem to be anything doable to replicate it directly

### Screenshots

![2022-12-11_19-03-22](https://user-images.githubusercontent.com/69388369/207427129-00987d23-d127-45f5-baff-2614e6ce352f.png)
![2022-12-11_19-03-31](https://user-images.githubusercontent.com/69388369/207427138-8783d3b1-92c8-43f8-ba78-192ede60265b.png)
![2022-12-11_19-03-34](https://user-images.githubusercontent.com/69388369/207427145-864a7452-dde5-4c2e-a368-760bcb2f8d09.png)
![2022-12-11_19-03-37](https://user-images.githubusercontent.com/69388369/207427156-cec8aa89-e63c-4033-a96b-15e37f85500c.png)
![2022-12-11_19-04-04](https://user-images.githubusercontent.com/69388369/207427165-6d67795e-52f1-4440-84b4-d889c9a5a662.png)
![2022-12-11_22-37-23](https://user-images.githubusercontent.com/69388369/207427506-d5caa31f-db22-4180-b2c6-3c6af48d3cc1.png)
![2022-12-11_22-37-28](https://user-images.githubusercontent.com/69388369/207427626-9fd1fec5-9e09-4421-b585-382695d814a2.png)
![2022-12-11_22-37-39](https://user-images.githubusercontent.com/69388369/207427631-6b6fdafc-07c3-4301-8ca7-102cf7bf6bb1.png)

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2022-12-13 19:49
Duplicate of #353

**Closed by Craluminum2413** 2022-12-13 19:49 UTC
Labels: status: new
