### ISSUE TITLE
PhysicsManager.TickFixedRate30TPS()

### ISSUE THREAD

**Issue by WickedSchnitzel** [anegostudios/VintageStory-Issues#4783] opened 2024-12-24 12:39 UTC
### Game Version

1.20.0-rc.5

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Spamming console. No clue what causes it.

### Logs

[Server Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.Server.PhysicsManager.TickFixedRate30TPS() in VintagestoryLib\Server\PhysicsManager.cs:line 314
   at Vintagestory.Server.PhysicsManager.ServerTick(Single dt) in VintagestoryLib\Server\PhysicsManager.cs:line 104
   at Vintagestory.Common.GameTickListener.OnTriggered(Int64 ellapsedMilliseconds) in VintagestoryLib\Common\Model\GameTickListener.cs:line 27
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 57
   at Vintagestory.Server.ServerMain.Process() in VintagestoryLib\Server\ServerMain.cs:line 893

**Comment by WickedSchnitzel** [comment] 2024-12-24 12:40
Can it be some wrong setting within "servermagicnumbers"?

{
  "Comment": "You can use this config to increase/lower the cpu and network load of the server. A Warning though: Changing these numbers might make your server run unstable or slow. Use at your own risk! Until there is an official documentation, feel free to ask in the forums what the numbers do.",
  "DefaultEntityTrackingRange": 3,
  "DefaultSimulationRange": 96,
  "RequestChunkColumnsQueueSize": 2000,
  "ReadyChunksQueueSize": 200,
  "ChunksColumnsToRequestPerTick": 2,
  "ChunksToSendPerTick": 48,
  "ChunkRequestTickTime": 20,
  "ChunkColumnsToGeneratePerThreadTick": 20,
  "ServerAutoSave": 1050,
  "SpawnChunksWidth": 2,
  "TrackedEntitiesPerClient": 2500,
  "CalendarPacketSecondInterval": 25,
  "ChunkUnloadInterval": 4000,
  "UncompressedChunkTTL": 15000,
  "CompressedChunkTTL": 45000,
  "PlayerDesyncTolerance": 0.02,
  "PlayerDesyncMaxIntervalls": 20.0,
  "ChunkThreadTickTime": 5,
  "AntiAbuseMaxWalkBlocksPer200ms": 3,
  "AntiAbuseMaxFlySuspicions": 3,
  "AntiAbuseMaxTeleSuspicions": 8,
  "MaxPhysicsThreads": 4,
  "MaxWorldgenThreads": 4,
  "MaxEntitySpawnsPerTick": 8,
  "ServerMagicNumVersion": "1.3"
}

**Comment by radfast** [comment] 2024-12-24 14:35
Duplicate of #4754 

We do not believe this relates to your `servermagicnumbers.json`, specifically your MaxPhysicsThreads = 4, as the player reporting #4754 had MaxPhysicsThreads set to 1.

The issue is something deep in the code and appears to be "once a week" rare.  Please do try out game version **1.20.0-rc.6**, released today.  As well as fixing many other things, it has additional logging added to help us diagnose this specific crash if it ever happens again.

For a short time, let's keep both this and #4754 open for visibility, in case other players have the same issue.

**Comment by Craluminum2413** [comment] 2024-12-24 14:39
I can pin one of issues

**Comment by WickedSchnitzel** [comment] 2024-12-24 16:53
now the server crashed with

24.12.2024 16:50:33 [Server Error] Error while enumerating tickables
24.12.2024 16:50:33 [Server Error] Tickables total count is 1276
24.12.2024 16:50:33 [Server Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.Server.PhysicsManager.DoWork(Int32 threadNumber) in VintagestoryLib\Server\PhysicsManager.cs:line 583
24.12.2024 16:50:33 [Server Error] Exception: tickable 344 was null, that shouldn't happen
   at Vintagestory.Server.PhysicsManager.DoWork(Int32 threadNumber) in VintagestoryLib\Server\PhysicsManager.cs:line 604
   at Vintagestory.Common.LoadBalancer.SynchroniseWorkToMainThread(Object source) in VintagestoryLib\Common\LoadBalancer.cs:line 84
   at Vintagestory.Server.PhysicsManager.TickFixedRate30TPS() in VintagestoryLib\Server\PhysicsManager.cs:line 311
   at Vintagestory.Server.PhysicsManager.ServerTick(Single dt) in VintagestoryLib\Server\PhysicsManager.cs:line 103
   at Vintagestory.Common.GameTickListener.OnTriggered(Int64 ellapsedMilliseconds) in VintagestoryLib\Common\Model\GameTickListener.cs:line 27
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 57
   at Vintagestory.Server.ServerMain.Process() in VintagestoryLib\Server\ServerMain.cs:line 896

**Comment by WickedSchnitzel** [comment] 2024-12-24 16:53
all animals where either zooming around for some or standing pinned to one spot (while having the walking animation)

**Comment by WickedSchnitzel** [comment] 2024-12-24 16:54
its not once a week rare for me honestly.

**Comment by radfast** [comment] 2024-12-24 17:34
> now the server crashed with
> 
> 24.12.2024 16:50:33 [Server Error] Error while enumerating tickables 24.12.2024 16:50:33 [Server Error] Tickables total count is 1276 24.12.2024 16:50:33 [Server Error] Exception: Object reference not set to an instance of an object. at Vintagestory.Server.PhysicsManager.DoWork(Int32 threadNumber) in VintagestoryLib\Server\PhysicsManager.cs:line 583 24.12.2024 16:50:33 [Server Error] Exception: tickable 344 was null, that shouldn't happen at Vintagestory.Server.PhysicsManager.DoWork(Int32 threadNumber) in VintagestoryLib\Server\PhysicsManager.cs:line 604 at Vintagestory.Common.LoadBalancer.SynchroniseWorkToMainThread(Object source) in 

OK awesome, this is very helpful, our new debugging code is being triggered.

To keep your server running, please for now try setting `MaxPhysicsThreads` to 1, in your servermagicnumbers file  (effective for next server restart), see if that makes it "once a week rare"

**Comment by radfast** [comment] 2024-12-24 22:24
We've found the root cause of the issue :)

It's fixed in upcoming 1.20.0-rc.7 (or stable if we go immediately to stable now).

The root cause is simultaneous entity spawns on two different code threads at the same time, which is unlikely but could occur on a large scale multiplayer server like yours - this is probably why the issue has not been picked up before now.

Until we get the next release out, unfortunately the issue will continue to occur sometimes.  It will occur in all existing 1.20 versions but not 1.19.8.  I realize this is not great for your server.  If you are friends with @th3dilli you could maybe ask him directly to make a private server build for you, easier for us to do if you need a **Linux** server build.

**Closed by radfast** 2024-12-24 22:24 UTC
Labels: status: duplicate, target: multiplayer, status: in-progress, department: code

**Comment by WickedSchnitzel** [comment] 2024-12-25 19:22
[Server Error] Error while enumerating tickables
25.12.2024 19:19:42 [Server Error] Tickables total count is 6285
25.12.2024 19:19:42 [Server Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.Server.PhysicsManager.DoWork(Int32 threadNumber) in VintagestoryLib\Server\PhysicsManager.cs:line 583
25.12.2024 19:19:42 [Server Error] Exception: tickable 3352 was null, that shouldn't happen
   at Vintagestory.Server.PhysicsManager.DoWork(Int32 threadNumber) in VintagestoryLib\Server\PhysicsManager.cs:line 604
   at Vintagestory.Common.LoadBalancer.SynchroniseWorkToMainThread(Object source) in VintagestoryLib\Common\LoadBalancer.cs:line 84
   at Vintagestory.Server.PhysicsManager.TickFixedRate30TPS() in VintagestoryLib\Server\PhysicsManager.cs:line 311
   at Vintagestory.Server.PhysicsManager.ServerTick(Single dt) in VintagestoryLib\Server\PhysicsManager.cs:line 103
   at Vintagestory.Common.GameTickListener.OnTriggered(Int64 ellapsedMilliseconds) in VintagestoryLib\Common\Model\GameTickListener.cs:line 27
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 57
   at Vintagestory.Server.ServerMain.Process() in VintagestoryLib\Server\ServerMain.cs:line 896

**Comment by radfast** [comment] 2024-12-26 13:14
Thank you @WickedSchnitzel , see my post [above](https://github.com/anegostudios/VintageStory-Issues/issues/4783#issuecomment-2561474082)
