### ISSUE TITLE
NPCs flickering and semi-transparent after disabling Temporal Stability

### ISSUE THREAD

**Issue by OscarOG** [anegostudios/VintageStory-Issues#1644] opened 2022-01-25 23:02 UTC
**Game Version:** 1.16.1 (stable)
**Platform:** Windows 10  
**Modded:** No
**SP/MP:** Singleplayer

### Description
NPCs flickering.

### How to reproduce
1. If **Temporal Stability** is disabled, enable it `/worldconfig temporalStability true`.
2. Let the player´s stability fall to low leves, like 12% and let the negative effects start, especially the visuals effect.
3. Turn off Temporal Stability `/worldconfig temporalStability false`.
4. Save and exit the game.
5. Re-enter game and load the map, NPCs now should be flickering and be semi-transparent.

It can be solved by re-enabling Temporal Stability and restoring some stability to normal levels so the negative effects just stop and then turn stability off again.

### Expected behavior
It´s expected that this visual issue will not occur after disabling Temporary Stability at low levels.

### Screenshots
(none)

### Logs
(none)

**Comment by Craluminum2413** [comment] 2023-04-10 10:04
Duplicate of #406

**Closed by Craluminum2413** 2023-04-10 10:04 UTC
Labels: status: new
