### ISSUE TITLE
Crashed when making world. 

### ISSUE THREAD

**Issue by Winterdragon82** [anegostudios/VintageStory-Issues#2449] opened 2023-03-07 17:15 UTC
### Game Version

1.18.0-pre.5

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Game crashed when trying to create the new world. I was using the following mods. These mods WORK when I play 1.17

Additionalmolds
Animal cages
Anvil Metal Recovery+
Knapster
Arrowheads Recovery
Auto Map Markers
Backpack Pack Plus
Betterruins
Carry On
Hud Clock
Human-like Skins for Seraphs
Juicy Ores
More molds
More Torch hodlers
Moretreesmoreseeds
No Molding (for when i got burnt out on making them)
No negative traits
No trader money limit
OresAplenty
Ragnamans Seed From Crops
Grindless MOd
ResinFarm
Stackables
sticksfromfirewood
tree tapping
buffed vessels
Visually GLowing arrows
essentials
wildecraft

### How to reproduce

1. I just made a new world with some mods added in, crashed before it finished creating the world. 

### Logs

Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.18.0-pre.5 (Unstable)
3/7/2023 12:04:46 PM: Critical error occurred
Loaded Mods: 
System.InvalidCastException: Specified cast is not valid.
   at Vintagestory.Client.GuiScreenConnectingToServer.exitToDisconnectScreen() in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 427
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 316
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 717
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 620
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 126
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2/11/2023 1:17:38 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1402421717052153672, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.11.0
P3: 10.0.22621.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\crazy\AppData\Local\Temp\RDRBDF.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.0db6d751-0233-4ac0-a9c7-459eb9b55d6c.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.bd580af4-1f73-4d79-bef8-3acf803276ac.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.0f105f37-b464-4663-911d-1e7bfe992a9d.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.a22dcf63-4536-4ff8-a338-71d7b413c7e9.tmp.xml

These files may be available here:
NULL

Analysis symbol: 
Rechecking for solution: 0
Report Id: f02cbf20-bd2e-4a9a-97ff-2423c5e4fff1
Report Status: 268435456
Hashed bucket: 84f56296e9742f3d9376671f0e2fdf48
Cab Guid: 0 }
--------------
{ TimeGenerated = 1/12/2023 1:13:16 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1825730413453532425, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.10.0
P3: 10.0.22621.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\crazy\AppData\Local\Temp\RDRC2C5.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.386ccc07-1fcf-40c5-8139-33f02f6226a5.tmp.WERInternalMetadata.xml
WPR_initiated_DiagTrackMiniLogger_OneTrace_User_Logger_20230111_1_EC_0_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.d034e22f-53bb-42b8-95f7-4017312bad83.tmp.etl
WPR_initiated_DiagTrackMiniLogger_WPR System Collector_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.db2b207c-97c6-4770-a4c3-c3bcb5a622ce.tmp.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.3d6fe432-6abd-4ead-8e4d-80b6ea7412d6.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.9c5152e9-8ee0-4646-9b4a-90ab70817afb.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.4d4bc702-91e3-419d-8e4a-4668fb53982c.tmp.xml

These files may be available here:
NULL

Analysis symbol: 
Rechecking for solution: 0
Report Id: 111b8960-a449-4c81-a662-29b725496fb6
Report Status: 268435456
Hashed bucket: 9a8c1fe8af44cce6a9564c234d865d09
Cab Guid: 0 }

**Comment by Craluminum2413** [comment] 2023-03-07 17:18
Duplicate of #2380

**Closed by Craluminum2413** 2023-03-07 17:18 UTC
Labels: status: new

**Comment by Craluminum2413** [comment] 2023-03-07 17:20
Oh wait, here is InvalidCastException

**Comment by Craluminum2413** [comment] 2023-03-07 17:20
The rest of the crash log seem the same

**Comment by Winterdragon82** [comment] 2023-03-07 17:21
I turned off all the mods to see if it was a mod issue, and its still crashing.
