### ISSUE TITLE
Game crashed white trying to remove salt from a barrel

### ISSUE THREAD

**Issue by CARP42** [anegostudios/VintageStory-Issues#3472] opened 2024-01-19 02:08 UTC
First off forgive me for not knowing what I'm doing here, or how to search for the unknown issue..

I was spamming attempts to try and remove salt from a barrel, bucket, bowls etc.

I believe the following is the current crash data, there's 3 other mod related crashes still in the reporter.

{ TimeGenerated = 1/17/2024 7:49:03 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.15.0, time stamp: 0x64e841c5
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x4828
Faulting application start time: 0x01da49a3f27542a0
Faulting application path: C:\Users\jakma\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\jakma\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 14b32648-09f8-409e-8f29-a04c192830b2
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 1/16/2024 9:55:45 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2007150627803250050, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3519.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3A98.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3AD7.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3AD5.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3AF6.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_8ed3e48e-3463-454a-b32c-369e26da281c

Analysis symbol: 
Rechecking for solution: 0
Report Id: f344befa-71b8-41be-908a-fb551445dfc5
Report Status: 268566528
Hashed bucket: 38dd2bbe130a69d3fbdad4dc94ea3d82
Cab Guid: 0 }

**Comment by Craluminum2413** [comment] 2024-01-19 05:54
Duplicate of #1913

**Closed** 2024-01-19 05:55 UTC
Labels: status: duplicate
