### ISSUE TITLE
Exception thrown when using /weather commands via console

### ISSUE THREAD

**Issue by Ragolution** [anegostudios/VintageStory-Issues#736] opened 2021-01-09 20:36 UTC
**Game Version:** 1.14.5
**Platform:** Win7
**Modded:** No

### Description
When using Weather commands via console, the commands wont fire and the console will throw an exception.

### How to reproduce
1. Open console
2. weather command
3. exception

> 15:35:53 [Server Notification] Handling Command /weather setw auto
An unhandled Exception was thrown while executing Command. Check error log.
15:35:53 [Server Notification] An unhandled Exception was thrown while executing Command. Check error log.
15:35:53 [Server Error] Player Admin/console caused an exception through a command.
15:35:53 [Server Error] Command: /weather
15:35:53 [Server Error] Arguments: setw auto
15:35:53 [Server Error] Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.WeatherSystemCommands.cmdWeatherServer(IServerPlayer player, Int32 groupId, CmdArgs args)
   at Vintagestory.Common.EventManager.TriggerChatCommand(IPlayer player, Int32 channelId, String command, CmdArgs args)
   at Vintagestory.Server.ServerMain.HandleCommand(IServerPlayer player, Int32 groupid, String command, String argument)
15:35:53 [Server Error]    at Vintagestory.GameContent.WeatherSystemCommands.cmdWeatherServer(IServerPlayer player, Int32 groupId, CmdArgs args)
   at Vintagestory.Common.EventManager.TriggerChatCommand(IPlayer player, Int32 channelId, String command, CmdArgs args)
   at Vintagestory.Server.ServerMain.HandleCommand(IServerPlayer player, Int32 groupid, String command, String argument)

**Comment by tyronx** [comment] 2021-01-19 07:42
hm, i cannot reproduce this in v1.14.6

**Comment by copygirl** [comment] 2021-01-19 07:50
In that case I will close the issue. If you can still reproduce this in 1.14.6-rc.1 please let us know.

**Closed by copygirl** 2021-01-19 07:50 UTC
Labels: status: incomplete, type: bug
