### ISSUE TITLE
flowing water animation on ice

### ISSUE THREAD

**Issue by Carolusclen** [anegostudios/VintageStory-Issues#93] opened 2018-04-24 12:29 UTC
So if there is ice blocks in the water there is no flowing animation on the side of the ice for the water.
however, if the water is 2 or more blocks deep, then the water animation shows on the side of the ice.

**Comment by tyronx** [comment] 2018-05-23 09:51
Can you make a screenshot of that? I couldn't reproduce any oddities with water and ice

**Comment by tyronx** [comment] 2018-05-23 14:27
ok should be fixed for 1.5.4

**Closed by tyronx** 2018-05-23 14:27 UTC
Labels: status: new, type: bug
