### ISSUE TITLE
Continuous crash on world 

### ISSUE THREAD

**Issue by whatman44** [anegostudios/VintageStory-Issues#886] opened 2021-05-16 10:47 UTC
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.10 (Stable)16/05/2021 8:16:17 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.EntityItem.FromBytes(BinaryReader reader, Boolean forClient)
   at Vintagestory.Client.NoObf.ClientSystemEntities.HandleEntitySpawnPacket(_qiwXoSSrnCKEl5NMyGSjHlpQcE serverpacket)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _vKnDSS3ZW5fZhqcIJSzL9xbAUttA._mhcyOBzdAWALla9FVcjc15WACGi(Single )
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._3HP2xkrryy8Ktr1q1yqHHv9s1kb(Single )
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._JbXJA0SA6LQOS6diuqtXAjMb8Fo(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _ISiSTzGmXXpAqo3PzdxdVD1bClZ._ofvn0Tr1zNGCbNV3SxvKs2MXNP(_C7CLMRbe3BejVtaARYCgl7Bg1vl , String[] )
   at _0Y0SN1uu1V65pRLxvnN2xsIjXAg._ofvn0Tr1zNGCbNV3SxvKs2MXNP(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 16/05/2021 8:09:45 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1172072127245940601, type 5
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 6079b344
P4: 81f9
P5: 134217728
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC0D1.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC101.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC102.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC151.tmp.txt
\\?\C:\Users\trave\AppData\Local\Temp\WER510.tmp.appcompat.txt
\\?\C:\Users\trave\AppData\Local\Temp\WERB7A.tmp.xml
WERGenerationLog.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_Vintagestory.exe_c621a3d0119e22c65a87e2140e56a112c4f1cf_5674d60d_e9a6c4dd-7dc4-48d5-9684-dc8cd744ba7e

Analysis symbol: 
Rechecking for solution: 0
Report Id: 73129058-22c4-47e7-b29a-4658d939c958
Report Status: 268435456
Hashed bucket: cf8064cfa78a6d8ff0440963cba17779
Cab Guid: 0 }
--------------
{ TimeGenerated = 16/05/2021 8:09:43 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 6079b344
P4: 81f9
P5: 134217728
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC0D1.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC101.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC102.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC151.tmp.txt
\\?\C:\Users\trave\AppData\Local\Temp\WER510.tmp.appcompat.txt
\\?\C:\Users\trave\AppData\Local\Temp\WERB7A.tmp.xml
WERGenerationLog.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppHang_Vintagestory.exe_c621a3d0119e22c65a87e2140e56a112c4f1cf_5674d60d_cab_e9a6c4dd-7dc4-48d5-9684-dc8cd744ba7e

Analysis symbol: 
Rechecking for solution: 0
Report Id: 73129058-22c4-47e7-b29a-4658d939c958
Report Status: 5
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 16/05/2021 8:09:42 PM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.14.10.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 111c

Start Time: 01d74a1e2f3e8221

Termination Time: 4

Application Path: C:\Users\trave\AppData\Roaming\Vintagestory\Vintagestory.exe

Report Id: 73129058-22c4-47e7-b29a-4658d939c958

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }

**Comment by copygirl** [comment] 2021-05-16 13:04
See if running the world in repair mode helps (click the pencil when selecting the world). Closing as duplicate of #472.

**Closed by copygirl** 2021-05-16 13:04 UTC
