### ISSUE TITLE
Game crashes when going through translocator

### ISSUE THREAD

**Issue by pcoo0009** [anegostudios/VintageStory-Issues#3872] opened 2024-05-11 00:48 UTC
As in title
Happened to someone else going from spawn to the other side, then happened to me later going the other way
Here is my report:

```Running on 64 bit Windows 10.0.22631.0 with 16147 MB RAM
Game Version: v1.19.7 (Stable)
11/05/2024 10:46:15 AM: Critical error occurred
Loaded Mods: aculinaryartillery@1.1.3, chiseltools@1.11.1, decor@1.0.15, game@1.19.7, abcsreborn@0.2.1, betterruins@0.3.4, commonlib@2.3.7, expandedfoods@1.6.9, hudclock@3.4.0, sailboat@1.3.0, oldmap@1.0.0, spawnhighlight@1.2.0, vhfp@1.1.0, creative@1.19.7, survival@1.19.7, xlib@0.8.3-pre.1, playercorpse@1.9.0, stonequarry@3.2.1, xskills@0.8.5-pre.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 49
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 815
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 731
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93```

**Comment by Craluminum2413** [comment] 2024-05-11 09:37
Duplicate of #3550

**Closed by Craluminum2413** 2024-05-11 09:37 UTC
