### ISSUE TITLE
Can't fire storage vessel in pit kiln

### ISSUE THREAD

**Issue by gamenerd2026** [anegostudios/VintageStory-Issues#1102] opened 2021-07-03 23:06 UTC
1.15 Pre 12
Windows
**Modded:** No / Yes (which?)  
no
### Description
Explain the issue you're running into.
cant finish pit kiln
### How to reproduce
1. Make a raw storage vessel
2. Place it in the ground, and all dry grass
3. Can't place sticks on it, can't place firewood on it, can't lite the fire
I could place stick on it until recently, and I can with the pit kiln
### Expected behavior
be able to place stick/firewood to get it lighted

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Paste crash between the triple backticks.
none
In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.
```

**Comment by Saricane** [comment] 2021-07-04 12:20
I can't reproduce this on a flat world.

**Comment by copygirl** [comment] 2021-07-07 13:15
Will close this for now as rc.1 got released today and we probably would've noticed if this wasn't working. If you know the exact steps that can reproduce this in the latest version, please comment!

**Closed by copygirl** 2021-07-07 13:15 UTC
Labels: status: can't reproduce
