### ISSUE TITLE
Blue clay roofing changes its name

### ISSUE THREAD

**Issue by Ziver7** [anegostudios/VintageStory-Issues#1236] opened 2021-08-01 03:01 UTC
**Game Version:** 1.15.3
**Platform:** Windows 
**Modded:**  Yes

CarryCapacity
VSProspectorInfo

### Description
Slanted Blue Clay Roofing are changing their block names into "game:block-slantedroofing-blueclay..." whenever I place them down. Picking back up the changed block doesn't change their name back.

### How to reproduce
1. Place down Slanted Blue Clay Roofing
2. The roofing block now has the changed block name

### Screenshots
![image](https://user-images.githubusercontent.com/13258651/127757669-3e1d6e8b-8f84-4c1d-ab3c-49dbbce08efd.png)

**Comment by LuuBluum** [comment] 2021-08-02 01:21
Seems to be the case with thatch roofing, too.

![2021-08-01_21-19-51](https://user-images.githubusercontent.com/35275808/127792453-ebb0c8ef-b37d-49e7-8b18-6bd1cc927f60.png)

**Comment by Craluminum2413** [comment] 2021-08-03 11:01
I found this in `assets\survival\blocktypes\roofing\slantedroofing.json`:

```behaviors: [{name: "HorizontalOrientable", properties: {  dropBlockFace: "east", drop: { type: "block", code: "slantedroofing-{material}-north-free" }  }}],```

**Comment by kurazarrh** [comment] 2021-08-03 17:08
Confirmed this affects slate roof blocks; when picking up these name-changed blocks, they do not stack with the original ones, either.

**Comment by Craluminum2413** [comment] 2021-12-26 00:05
Was fixed in [1.15.6](https://www.vintagestory.at/forums/topic/5633-homesteading-balance-and-stability-patch-3-v1156/#:~:text=Fixed%3A%20Missing%20block%20names%20for%20clay%20roofing) and/or [1.15.8-rc.1](https://www.vintagestory.at/forums/topic/5880-unstable-ground-fog-patch-chisel-painting-event-v1158-rc1/#:~:text=Fixed%3A%20Broken%20slanted%20roofing%20not%20stacking%20with%20freshly%20crafted%20ones)

**Closed** 2021-12-30 17:24 UTC
Labels: status: resolved, department: json
