### ISSUE TITLE
Server crash on start

### ISSUE THREAD

**Issue by dann1kid** [anegostudios/VintageStory-Issues#1699] opened 2022-02-12 06:12 UTC
**Game Version:** 1.16.3
**Platform:** Windows 
**Modded:** Yes 
**SP/MP:** Multiplayer 

### Description
Modded server wont start cause exception

### How to reproduce
i dont know

### Logs
```
12.02.2022 9:04:53: Critical error occurred
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в Vintagestory.API.Config.TranslationService.Load(Boolean lazyLoad)
   в Vintagestory.API.Config.Lang.Load(ILogger logger, IAssetManager assetManager, String defaultLanguage)
   в Vintagestory.Server.ServerSystemModHandler.OnLoadAssets()
   в Vintagestory.Server.ServerMain.EnterRunPhase(EnumServerRunPhase runPhase)
   в Vintagestory.Server.ServerMain.Launch()
   в ⁭‎​⁭⁪​‭‏⁯‮‪‭‏‮​‬⁮‍⁯‎⁫⁭⁭‭‬⁯​‬‏⁪‬⁫‍⁪‌​⁮‫‍⁭‮.⁬⁯⁪‌⁬⁯​‏‬⁮⁬⁫‌⁬⁮‏‭‏⁭‍‌‏‭‭⁬⁬⁬⁭‮‌‪‮⁮‌⁯⁮‌⁭⁫‮‮()
   в _XL1Xa21FKJVFetNmIumId5p6UDU._SwLkq72vc0vcc3OnHXTAS19pm9p(ThreadStart )
```

**Comment by daretmavi** [comment] 2022-02-12 10:11
Is it starting without mods?

If yes then try to add mods one by one to see what mod is causing it and send bug report to mod developer.

**Comment by dann1kid** [comment] 2022-02-12 13:06
> Is it starting without mods?
> 
> If yes then try to add mods one by one to see what mod is causing it and send bug report to mod developer.

I investigated it and see why its drops. Wrong string in lang file crashes server

**Comment by copygirl** [comment] 2022-02-12 13:14
Which string?

**Comment by dann1kid** [comment] 2022-02-12 14:23
> Which string?
In a lang file of some mod.

**Comment by copygirl** [comment] 2022-02-12 16:13
Which mod? Which file? Which line? - If you happen to know.
I'm just trying to get down to what the cause of the issue is so it can be fixed - otherwise I'll just have to close this as incomplete and hope the mod author can resolve it or message us.

**Comment by dann1kid** [comment] 2022-02-14 05:48
It was my translate, but i hadnt time to look closely.

**Comment by copygirl** [comment] 2022-02-14 06:39
What did the faulty line look like? If the team can reproduce this, they can make it so in the future if someone makes the same mistake, it will show a meaningful error.

**Comment by dann1kid** [comment] 2022-02-14 08:21
I dont know which string, cause i double checked and not found any mistakes. Today i meet same error in mod "wild farming", but there is no any translates, only english strings. 
I sent that issue to its author.

**Comment by copygirl** [comment] 2022-02-14 12:42
Okay, strange. I'll close the issue for now until more information is available.

**Closed by copygirl** 2022-02-14 12:42 UTC
Labels: status: incomplete
