### ISSUE TITLE
Cannot place more portions into partially filled crock when not interacting with the top

### ISSUE THREAD

**Issue by Grzegorz1984** [anegostudios/VintageStory-Issues#1225] opened 2021-07-26 19:22 UTC
**Game Version:** 1.5.2  
**Platform:** Windows 10
**Modded:** No 

### Description
After making two pots of bluberry jam each with 6 portions i try to put them into crocks.
First crock is fine it fits 4 portions. Second crocks take 2 portions left from first pot but then
i cannot add two portions from the second bowl. In the end i am left with two crocks with
4 servings and one with 2 portions. 

### How to reproduce
1. Make two bowls of jam with 6 portions each.
2. Try to put them in 3 crocks.
3.  Cannot fit them all. Two portions left in pot.

### Expected behavior
12 portions should fit into 3 crocks with 4 portions each.

### Screenshots
![2021-07-26_21-13-08](https://user-images.githubusercontent.com/7847820/127046482-62a1302d-8fea-4589-a100-8333dda6a346.png)
![2021-07-26_21-15-53](https://user-images.githubusercontent.com/7847820/127046484-14da744e-fed7-4d7a-83b2-691ddde2af15.png)
![2021-07-26_21-16-17](https://user-images.githubusercontent.com/7847820/127046486-9490a5fd-7354-4917-9154-c40e6b3428c4.png)
![2021-07-26_21-16-24](https://user-images.githubusercontent.com/7847820/127046487-867f0db5-f275-4e29-ad53-a7819716e20c.png)
![2021-07-26_21-16-31](https://user-images.githubusercontent.com/7847820/127046489-859bbdd2-e1f8-4e3a-91b3-6a7f38666512.png)
![2021-07-26_21-16-37](https://user-images.githubusercontent.com/7847820/127046491-f8d27922-8ed8-4519-8b49-2096c46da7c9.png)

**Comment by Craluminum2413** [comment] 2021-07-26 19:28
Duplicate of #1036

**Comment by copygirl** [comment] 2021-07-26 19:35
Yes. Do you by chance remember whether you put the ingredients for the meals in the same order?

**Comment by Grzegorz1984** [comment] 2021-07-26 20:55
As you see in the screenshot order was exactly the same.

**Comment by copygirl** [comment] 2021-07-26 21:18
Okay, in that case it doesn't seem to be a duplicate of #1036, unless I misunderstand.

**Comment by Grzegorz1984** [comment] 2021-07-27 01:13
You are correct, the recipe is the same in both pots. It's not a duplicate of #1036.

**Comment by Craluminum2413** [comment] 2021-07-27 08:37
There is really not enough debug information about knowing exactly what is in these cooking pots

**Comment by Craluminum2413** [comment] 2021-07-27 09:41
I reproduced the bug, rename issue to `You cannot add the same portion if you click on the side of the crock`

https://user-images.githubusercontent.com/69315569/127132507-1509ab33-6ab2-4896-9fac-a9162ad7a40b.mp4

**Comment by Craluminum2413** [comment] 2021-07-27 09:43
Also, this issue doesn't apply to jam, this applies specifically to moving the meal between cooking pots and crocks

**Comment by Craluminum2413** [comment] 2021-07-27 09:49
`Cannot add meal to partially-filled crock if press on the side of crock without using Shift`

**Comment by Craluminum2413** [comment] 2021-12-19 12:39
Since 1.16 pre-releases made them Ground Storable, then this bug not no longer relevant and issue can be closed

**Closed** 2021-12-19 14:17 UTC
Labels: status: resolved
