### ISSUE TITLE
Last slice of pie has no saturation

### ISSUE THREAD

**Issue by TheCastleKeeper10** [anegostudios/VintageStory-Issues#4703] opened 2024-12-15 18:14 UTC
### Game Version

v1.20.0

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

The last slice of pie will frequently provide 0 saturation when consumed by the player. 

### How to reproduce

1. Make and cook a pie
2. Slice pie and consume the first three slices
3. Attempt to consume the fourth slice

Now using 1.20.0 but was occuring on older/stable versions as well.

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2024-12-15 18:22
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/2117

**Closed by Craluminum2413** 2024-12-15 18:22 UTC
Labels: status: new
