### ISSUE TITLE
Gamefile fatally corrupted after respawning

### ISSUE THREAD

**Issue by Aviatronix** [anegostudios/VintageStory-Issues#4396] opened 2024-10-30 11:35 UTC
### Game Version

v1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

I died by drifters after getting jump scared and fat fingered something close after respawning, causing my game to freeze and crash. When trying to relaunch the same save it turns out to be corrupted, giving the log which I pasted below in the log section.
I am utterly clueless as to what is causing the loading issue since I'm not familiar with the error codes.
I would really like to fix this save as there's quite some time already invested.

### Logs

Running on 64 bit Windows 10.0.22631.0 with 15711 MB RAM
Game Version: v1.19.8 (Stable)
30/10/2024 12:05:48: Critical error occurred
Loaded Mods: aculinaryartillery@1.2.1, ancientarmory@1.0.3, balancedthirst@0.0.44, buildingplus@1.1.2, HangingOilLamps@1.0.1, millwright@1.1.6, palisademod@1.1.0, TA_plainsandvalleys@1.0.5, primitivesurvival@3.5.8, game@1.19.8, animalcages@3.0.2, animationmanagerlib@0.8.8, butchering@1.6.7, carryon@1.7.4, commonlib@2.5.0-rc.2, expandedfoods@1.7.2, foodshelves@1.1.5, medievalexpansion@3.13.1, outlawmod@1.2.3, rivers@3.1.0, sailboat@1.3.1, simplecloth@1.0.2, creative@1.19.8, vsimgui@1.1.5, survival@1.19.8, vsvillage@1.0.6, wildfarmingrevival@1.2.4, bullseye-continued@2.5.8, tradercamps@1.1.4, configlib@1.3.13, em@2.6.3, stonequarry@3.3.1, bricklayers@2.5.6
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.Common.GameCalendar.getSunlightPixelRel(Single relx, Single rely) in VintagestoryLib\Common\GameCalendar.cs:line 588
   at Vintagestory.Common.ClientGameCalendar.Update() in VintagestoryLib\Common\GameCalendar.cs:line 134
   at Vintagestory.Client.NoObf.SystemCalendar.Eventapi_LevelFinalize() in VintagestoryLib\Client\Systems\Calendar.cs:line 49
   at Vintagestory.Client.NoObf.ClientEventAPI.TriggerLevelFinalize() in VintagestoryLib\Client\API\ClientEventAPI.cs:line 383
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleLevelFinalize(Packet_Server packet) in VintagestoryLib\Client\Systems\Startup.cs:line 1035
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 448
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 442
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 776
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 313
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 30/10/2024 11:59:23, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x3d08
Faulting application start time: 0x0x1db2ab9f0af3a6e
Faulting application path: C:\Users\woute\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\woute\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: abee6082-e9d1-4366-8787-85d0cde71007
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 30/10/2024 11:53:23, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x1f50
Faulting application start time: 0x0x1db2ab95126385c
Faulting application path: C:\Users\woute\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\woute\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 5e4cdb71-3c10-49f5-be67-ccf19d986d4d
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 30/10/2024 11:38:46, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x262c
Faulting application start time: 0x0x1db2ab78fae1464
Faulting application path: C:\Users\woute\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\woute\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: d5c27767-bcad-4387-8645-4e7e111d1ea9
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment] 2024-10-30 11:56
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4202

**Closed by Craluminum2413** 2024-10-30 11:56 UTC
Labels: status: new

**Comment by Aviatronix** [comment] 2024-10-30 19:29
@Craluminum2413 I would still like to know how to fix my save file...

**Comment by Aviatronix** [comment] 2024-10-31 13:41
Update should anyone read this, traced the issue down to a mod and am resolving it with the maker.

**Comment by clementhervy** [comment] 2024-12-29 00:12
@Aviatronix any luck fixing the affected save file? Which mod was it?
