### ISSUE TITLE
Game Crashes While Launching Application

### ISSUE THREAD

**Issue by mysteryblock** [anegostudios/VintageStory-Issues#457] opened 2020-03-07 20:54 UTC
**Game Version: v1.12.5(Stable)**
**Platform: Windows** 
**Modded: No**

### Description
Played the game on March 4th without issue. On March 6th I click the application icon and the game crashes while trying to launch. Persists today, March 7th. 

### How to reproduce
Double click on Vintage Story Icon from desktop. 

### Expected behavior
Game to launch. 

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Running on 64 bit Windows with 64 GB RAM 
Version: v1.12.5 (Stable)3/7/2020 12:49:22 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.ClientPlatformWindows.LoadTexture(IBitmap bmp, Boolean linearMag, Int32 clampMode, Boolean generateMipmaps)
   at _mKeEWUbBZsjLS6VlGWgOoYQFk2K._KNs6g2GMtsTu5gnL4MXdRgZVlLh()
   at _lt8TgSVuBImgzFgAFlSeVzSFsSy._HdDsdRJDH8nMF88r278C4eqdINGA()
   at _lt8TgSVuBImgzFgAFlSeVzSFsSy._gjiBClIE7Yspuz65gCqPGSAnUYeb()
   at _lt8TgSVuBImgzFgAFlSeVzSFsSy._NbPATb9BXlxRc4ZhH2GgyFCUInp(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _hCuHXesCXlp0LGSdrsPFpw4up5n._mOm8EuKIvHpaJoztxNWRpAoOpbM(_55ISULxdcpPfF8D2JP831aWhOBe , String[] )
   at _iCfIbY24GyBXP5lAwqsSlD9COxC._mOm8EuKIvHpaJoztxNWRpAoOpbM(ThreadStart )
-------------------------------

```

**Comment by mysteryblock** [comment] 2020-03-07 20:56
Specs: 
RTX 2080 ti
Ryzen 2700X
Windows 10 Pro
64 GB Ram

**Comment by Angelnoir** [comment] 2020-03-07 21:28
There is a new Version 1.12.6 available, the Bug is fixed there.
Connected to #407

**Comment by Bloodsaw** [comment] 2020-03-07 21:29
Like @Angelnoir said, just update to newest version.
You can download it from main VS page.

Duplicate of issue #407

**Closed by Bloodsaw** 2020-03-07 21:29 UTC
Labels: status: duplicate
