### ISSUE TITLE
Opening a firepit while holding a cooking pot does not work, while crucibles do work for this

### ISSUE THREAD

**Issue by 5HT2** [anegostudios/VintageStory-Issues#1750] opened 2022-02-26 13:14 UTC
**Game Version:** 1.16.4 
**Platform:** **Windows** / Mac / **Linux** (which?)   
**Modded:** **No** / Yes (which?)  
**SP/MP:** **Singleplayer** / **Multiplayer** (which?)  

### Description
Explain the issue you're running into.

Opening a firepit while holding a cooking pot does not work, while crucibles do work for this

### How to reproduce
1. Hold a cooking pot
2. Right click firepit

### Expected behavior
If not obvious, what did you expect to happen?

That it opens the firepit, just like it would with a crucible.

**Comment by copygirl** [comment] 2022-02-26 13:44
I believe the reason for this is cooking pots (similar to bowls) having a special right click handler for transferring meals.

**Comment by Craluminum2413** [comment] 2024-09-30 09:57
Can't reproduce, I assume it is fixed

**Closed by Craluminum2413** 2024-09-30 09:57 UTC
Labels: status: new
