### ISSUE TITLE
Empty buckets that have been placed don't stack with other empty buckets

### ISSUE THREAD

**Issue by jollki** [anegostudios/VintageStory-Issues#1546] opened 2022-01-06 20:59 UTC
**Game Version:** 1.16.0-rc.7
**Platform:** Linux
**Modded:** No
**SP/MP:** Singleplayer

### Description
An empty bucket that has been placed in-world and picked up will not stack with other empty buckets.
Filling and emptying the bucket resets it so they stack again.

### How to reproduce
1. Place an empty bucket with shift right-click
2. Pick it back up with right-click
3. Try to stack it with other empty buckets

### Expected behavior
Any empty buckets should stack together

**Comment by Craluminum2413** [comment] 2022-01-06 21:05
Duplicate of #862

**Closed** 2022-01-06 23:04 UTC
Labels: status: duplicate
