### ISSUE TITLE
System.NullReferenceException  recreate world from the seed

### ISSUE THREAD

**Issue by MateuszLas421** [anegostudios/VintageStory-Issues#874] opened 2021-04-26 19:05 UTC
**Game Version:** 1.14.10
**Platform:** Windows
**Modded:** No / 

### Description
Explain the issue you're running into.

### How to reproduce
I deactivated a world and wanted to create a new one using the create world button from a seed

### Expected behavior
creating a new world from a seed of an existing world

### Logs
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.10 (Stable)26.04.2021 20:58:18: Critical error occurred
System.NullReferenceException: Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
   w _XdIuBv24vQ1JZohJexy6wrKepcG._plbbXOc9b5uBS8CNUoxbNm2MgS7()
   w Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   w Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   w Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   w Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   w _tQNG2d15aM4IHF2517OUDULPBHL._TqANHNj1JY1XBE9yPv18vWLJBlG(MouseEvent )
   w Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   w System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   w System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   w OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   w OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   w OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   w OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   w _ISiSTzGmXXpAqo3PzdxdVD1bClZ._ofvn0Tr1zNGCbNV3SxvKs2MXNP(_C7CLMRbe3BejVtaARYCgl7Bg1vl , String[] )
   w _0Y0SN1uu1V65pRLxvnN2xsIjXAg._ofvn0Tr1zNGCbNV3SxvKs2MXNP(ThreadStart )
-------------------------------

Paste crash here.

[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/6379627/client-main.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/6379629/server-main.txt)
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/6379631/client-debug.txt)

```

**Comment by Craluminum2413** [comment] 2021-04-26 19:13
duplicate of #795

**Comment by copygirl** [comment] 2021-04-26 20:20
Indeed. Thank you for reporting it, though.

**Closed by copygirl** 2021-04-26 20:20 UTC
Labels: status: duplicate
