### ISSUE TITLE
Animals with code "fleeondamage" don't flee when damaged at long range

### ISSUE THREAD

**Issue by GhostLich** [anegostudios/VintageStory-Issues#2345] opened 2023-01-18 13:51 UTC
### Game Version

v1.17.10

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Gazelles and other animals with code: "fleeondamage" don't react or flee when damaged at long range, like with spears or bows.

### How to reproduce

Damage gazelle etc at long range. 

### Screenshots

https://user-images.githubusercontent.com/79675610/213188453-e0bc5c24-6715-4df8-af11-f4c75e9e954d.mp4

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2023-01-18 15:24
Duplicate of #1171

**Closed by Craluminum2413** 2023-01-18 15:24 UTC
Labels: status: new
