### ISSUE TITLE
Crash while exploring brand new world

### ISSUE THREAD

**Issue by FuriousProgrammer** [anegostudios/VintageStory-Issues#3462] opened 2024-01-18 04:34 UTC
### Game Version

v1.19.0

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

After breaking some berry bushes, in-world dropped models didn't disappear.

Dug some dirt, picked it up, and replaced it: berry bushes remained, and the dirt block dropped item was added and also remained in the world.

A few seconds later, the game crashed.

### How to reproduce

No clue

### Logs

```
Running on 64 bit Windows 10.0.19045.0 with 32682 MB RAM
Game Version: v1.19.0 (Stable)
1/17/2024 10:29:05 PM: Critical error occurred
Loaded Mods: game@1.19.0, creative@1.19.0, survival@1.19.0
System.Exception: Max joint cap of 36 reached, needs to be at least 43. In clientsettings.json, please try increasing the "maxAnimatedElements": setting to 46.  This works for most GPUs.  Otherwise you might need to disable the creature.
   at Vintagestory.API.Common.Animation.GenerateAllFrames(ShapeElement[] rootElements, Dictionary`2 jointsById, Boolean recursive) in VintagestoryApi\Common\Model\Animation\Animation.cs:line 97
   at Vintagestory.API.Common.ClientAnimator.AnimNowActive(RunningAnimation anim, AnimationMetaData animData) in VintagestoryApi\Common\Model\Animation\ClientAnimator.cs:line 225
   at Vintagestory.API.Common.AnimatorBase.OnFrame(Dictionary`2 activeAnimationsByAnimCode, Single dt) in VintagestoryApi\Common\Model\Animation\AnimatorBase.cs:line 115
   at Vintagestory.API.Common.AnimationManager.OnClientFrame(Single dt) in VintagestoryApi\Common\Model\Animation\AnimationManager.cs:line 347
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 49
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 808
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 724
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**EDIT:** `maxAnimatedElements` in `clientsettings.json` was already set to 46.

**Comment by pingouyn** [comment] 2024-01-18 05:10
"Max joint cap of 36 reached, needs to be at least 43."  Looks similar to #3456 and #3426.
If the game is properly installed (i.e. refresh of all the config files), "maxAnimatedElements" in %AppData%/VintagestoryData/clientsettings.json should say 46 according to post 3426.

**Comment by FuriousProgrammer** [comment] 2024-01-18 05:13
The config file *does* say 46 in my install, I didn't modify it after updating.

**Comment by Craluminum2413** [comment] 2024-01-18 05:17
Duplicate of #3284

**Closed** 2024-01-18 05:18 UTC
Labels: status: duplicate
