### ISSUE TITLE
Piglets squeal too loud, too often

### ISSUE THREAD

**Issue by Wreckstation** [anegostudios/VintageStory-Issues#2115] opened 2022-08-12 19:05 UTC
**Game Version:** 1.17.0-rc.5
**Platform:** Windows / Mac / Linux (which?) Windows  
**Modded:** No / Yes (which?)  Yes
**SP/MP:** Singleplayer / Multiplayer (which?) Both  

### Description
Piglets just are incredibly noisy. With the high number of babies each mother can produce, the overlapping squeals increases the volume even higher. This makes a horrible soundscape to be in.

### How to reproduce
1. Wait for any pig to reproduce
2. Exist near the lil guys. You can even be on the other side of a brick wall with no sound impediment.

### Expected behavior
There are a couple of methods I can think of to make it more tolerable:
- Lower squeal frequency
- Lower volume
- Have a system that prevents overlapping sounds from blasting people's ears.

No matter what implementation: I would like to enter my pig house and hear noises other than baby pig.

### Screenshots
N/A

### Logs
N/A

**Comment by darkpoetcc** [comment] 2022-08-19 01:02
Hmm...not sure if this is an issue, or more just your personal preference doesn't match the game's design.  I've never found it to be an issue, although it may be an accessibility concern / nightmare Tyron will choose to further address in the future.  That is if if the modding community doesn't just handle it in perpetuity.

If tweaking the ambient noise level or your headphone/speaker level isn't enough, I'd suggest looking into a specific mod to handle this, which is called **[Accessibility Tweaks](https://mods.vintagestory.at/accessibilitytweaks)**.  While it currently is only working through 1.16.5, I believe you should be able to create a 1.16.5 world, tweak the settings (you want `pig-wild-piglet` sounds (`piglet-hurt` is the actual squeal) modified, then play in 1.17.x.  

I'll take a look into what can be done for that...at least that way, for the meantime, you have something to make it more tolerable.  If nothing else, perhaps I can share a brief HOWTO for you to adjust this prior to the updated version of Accessibility Tweaks being released.

**Comment by darkpoetcc** [comment] 2022-08-19 04:44
Okay, it took a bit with everything else going on, but I've gotten a chance to look around for a few moments.  What I suggested will work (I tested it with many a piglet, around 50 to be exact).  The mod still works, you just cannot bring up the mod management dialog in the 1.17.x unstable versions yet...likely due to API changes.  If you're interested, what you need to do is described below.  

**NOTE:**  This unfortunately must be done on a per-world basis, but after you have created your ideal settings, you only need to copy/paste, per **Steps 9 - 12**

**NOTE:** If you are versed in editing JSON files, you can skip many of the steps below, and edit the JSON file by-hand.  That will remove the need to follow **Steps 3 - 6**

1. Install the `AccessibilityTweaks` v2.3.1 mod in your mod folder (I've chosen `%AppData%\Roaming\VintagestoryData\Mods`, but you can install it local to the game client, or whatever OS you're running's similar path)
2. Create a brand new 1.16.5 world; type doesn't matter, settings to not matter, so long as the world is compatible with `AccessibilityTweaks`
3. Open the Sound Edit dialog, by pressing **F8**
![image](https://user-images.githubusercontent.com/6785272/185542804-1a3751c0-7e74-4cd1-be98-35ca6a5e5296.png)
4. Search for *piglet* in the Search box, and click on the **piglet-hurt.ogg** row
![image](https://user-images.githubusercontent.com/6785272/185543004-7dab3034-5732-4ad7-8bcd-56767ad68a55.png)
5. Adjust the sound level to your desired level, or mute it altogether.  Click **OK**
![image](https://user-images.githubusercontent.com/6785272/185543247-893765e3-4bb9-45ed-8d71-b5b278d434f0.png)
6. Do this for any remaining sounds you want to adjust
7. _Save and Exit_ the world
8. Navigate to `%AppData%\Roaming\VintagestoryData\ModData\VintageMods\AccessibilityTweaks\World`, or the equivalent folder on your system.  You should see a GUID folder, corresponding to the time you created and edited the "template world" in **Step 2**
![image](https://user-images.githubusercontent.com/6785272/185543487-6f3e22eb-0d4e-4c91-82f1-0944068b02ca.png)
9. Copy the **settings-world-client.json** file from the folder
![image](https://user-images.githubusercontent.com/6785272/185543550-afd5eef1-648d-4ed2-9711-ab7a46ea514d.png)
10. With the `AccessibilityTweaks` mod still enabled, open your desired world in your preferred 1.17.x client, then _Save and Exit_ the world
11. Navigate to `%AppData%\Roaming\VintagestoryData\ModData\VintageMods\AccessibilityTweaks\World` again, or the equivalent folder on your system.  You should see a new GUID folder, which will correspond to the time you just opened your world in 1.17.x while `AccessibilityTweaks` was enabled
![image](https://user-images.githubusercontent.com/6785272/185543821-b1614cc8-9172-40c2-9bf1-86ec3859e0a0.png)
12. Paste the **settings-world-client.json** file into the new folder
13. You should now be able to launch the new world in 1.17.x, and still have the sound adjustments made

**Comment by wasakoki** [comment] 2022-08-31 20:41
same issue as #1780 more or less

**Comment by Craluminum2413** [comment] 2024-09-30 13:30
Duplicate of #1780

**Closed by Craluminum2413** 2024-09-30 13:30 UTC
Labels: status: new
