### ISSUE TITLE
END OF WORLD

### ISSUE THREAD

**Issue by NITRO1623** [anegostudios/VintageStory-Issues#2472] opened 2023-03-13 03:05 UTC
### Game Version

V1.18 PRE 6

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

this may not be an issue and part of the updates as we go but the world on the map just went white and as i went to location the end of the world appeared im only about 1000 blocks from spawn  below is picture to show

### How to reproduce

not sure how to reproduce problem this might be update of  pre 1 pre 2 pre 3 etc

### Screenshots

![2023-03-12_21-57-57](https://user-images.githubusercontent.com/112742241/224598700-324d4cef-325d-4700-8fc1-b27ad2ce3711.png)

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2023-03-13 09:24
Duplicate of #2462

**Closed by Craluminum2413** 2023-03-13 09:24 UTC
Labels: status: new
