### ISSUE TITLE
A pie slice will not grant satiety in some conditions

### ISSUE THREAD

**Issue by mag8n** [anegostudios/VintageStory-Issues#3578] opened 2024-02-12 20:23 UTC
### Game Version

v1.19.3

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

Normally, you have to cut a pie using a knife in up to four slices to eat it and restore satiety in survival, and you are not able to pick up and eat a pie otherwise. However, if there is only one slice left, you are able to pick it up and eat it anyway. Doing so will not restore any satiety, but if you do the same with a knife, it will restore satiety.

### How to reproduce

1. Note the current satiety level
2. Cut out three slices of a pie with a knife
3. Pick up the fourth slice without a knife
4. Eat it and note how the satiety level does not go up

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2024-02-13 08:42
Duplicate of #2117

**Closed by Craluminum2413** 2024-02-13 08:42 UTC
Labels: status: new
