### ISSUE TITLE
Crashes when you try to chop bamboo with a stone ax.

### ISSUE THREAD

**Issue by askoldws** [anegostudios/VintageStory-Issues#3268] opened 2023-12-02 07:18 UTC
### Game Version

v1.19.0-pre.7 

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Crashes when you try to chop bamboo with a stone ax. And I can no longer enter the world after crash

### How to reproduce

Try to chop bamboo with a stone ax and game will crash

### Logs

``Running on 64 bit Windows with 24353 MB RAM
Game Version: v1.19.0-pre.7 (Unstable) by OverF1X  
02.12.2023 11:06:40: Critical error occurred
Loaded Mods: game@1.19.0-pre.7, creative@1.19.0-pre.7, survival@1.19.0-pre.7
System.FormatException: Input string was not in a correct format.
   at System.Text.ValueStringBuilder.ThrowFormatInvalidString()
   at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
   at System.String.Format(String format, Object[] args)
   at Vintagestory.GameContent.ErrorReporter.Logger_EntryAdded(EnumLogType logType, String message, Object[] args) in VSEssentials\Systems\ErrorReporter.cs:line 173
   at Vintagestory.API.Common.LoggerBase.Error(String format, Object[] args) in VintagestoryApi\Common\API\ILogger.cs:line 237
   at Vintagestory.Client.NoObf.SystemRenderDecals.tesselateBlockDecal(Int32 blockId) in VintagestoryLib\Client\Systems\Render\RenderDecals.cs:line 103
   at Vintagestory.Client.NoObf.SystemRenderDecals.UpdateDecal(BlockDecal decal) in VintagestoryLib\Client\Systems\Render\RenderDecals.cs:line 251
   at Vintagestory.Client.NoObf.SystemRenderDecals.AddBlockBreakDecal(BlockPos pos, Int32 stage) in VintagestoryLib\Client\Systems\Render\RenderDecals.cs:line 237
   at Vintagestory.Client.NoObf.SystemRenderDecals.OnPlayerBreakingBlock(BlockDamage blockDamage) in VintagestoryLib\Client\Systems\Render\RenderDecals.cs:line 207
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerBlockBreaking(BlockDamage blockDamage) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 376
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.ContinueBreakSurvival(BlockSelection blockSelection, Block block, Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 807
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 456
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 101
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 796
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 989
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 322
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 01.12.2023 17:43:11, Site = , Source = Application Error, Message = Имя сбойного приложения: Vintagestory.exe, версия: 1.19.0.0, метка времени: 0x6514d416
Имя сбойного модуля: coreclr.dll, версия: 7.0.1023.36312, метка времени: 0x64b06d6c
Код исключения: 0xc0000005
Смещение ошибки: 0x00000000001c98a6
Идентификатор сбойного процесса: 0x2ccc
Время запуска сбойного приложения: 0x01da245c0f1a4141
Путь сбойного приложения: D:\Games\Vintage Story\Vintagestory.exe
Путь сбойного модуля: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.10\coreclr.dll
Идентификатор отчета: b2917988-b128-466c-aa55-e4fbef6a388e
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:  }```

**Comment by Craluminum2413** [comment] 2023-12-02 13:30
Duplicate of #3247

**Closed by Craluminum2413** 2023-12-02 13:30 UTC
Labels: status: new
