### ISSUE TITLE
CTD when clicking on aged armor stand

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#4232] opened 2024-10-05 20:16 UTC
### Game Version

v1.20 PRE5

### Platform

Linux

### Modded

None

### SP/MP

Singleplayer

### Description

Right click on an aged armor stand crashes to desktop. It's ok for a standard armor stand.

### Logs

```Running on 64 bit Linux (Linux Mint 22) [Kernel 6.8.0.44] with 15895 MB RAM
Game Version: v1.20.0-pre.5 (Unstable)
10/5/2024 10:12:55PM: Critical error occurred
Loaded Mods: game@1.20.0-pre.5, creative@1.20.0-pre.5, survival@1.20.0-pre.5
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityArmorStand.OnInteract(EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode) in VSSurvivalMod\Entities\EntityArmorStand.cs:line 59
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsNoBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 394
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 818
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1022
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by Craluminum2413** [comment] 2024-10-05 20:19
Duplicate of #4183

**Closed by Craluminum2413** 2024-10-05 20:19 UTC
Labels: status: new
