### ISSUE TITLE
Game crash on start up despite only a week ago the game worked fine?

### ISSUE THREAD

**Issue by Seeker3028** [anegostudios/VintageStory-Issues#2724] opened 2023-05-11 00:49 UTC
### Game Version

v1.18.1

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Couldn't load into the server today despite it working about a week ago. today was able to boot up the game. Then the game after successfully going into the main menu as I tried to login into a multiplayer modded server it crashed and now it won't even boot up to the main menu now it just automatically crashes.

### How to reproduce

just launch it

### Logs

```Log```Running on 64 bit Windows with 12 GB RAM 
Game Version: v1.18.1 (Stable)
5/10/2023 7:40:53 PM: Critical error occurred
Loaded Mods: 
System.NotSupportedException: Your graphics card does not support the extensions GL_ARB_framebuffer_object, GL_ARB_vertex_array_object, GL_ARB_draw_instanced, GL_ARB_explicit_attrib_location which is required to start the game
   at Vintagestory.Client.NoObf.ClientPlatformWindows.LogAndTestHardwareInfos() in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 202
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 5/10/2023 6:57:45 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2124504683926079515, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.1.0
P3: 6443b447
P4: ig9icd64.dll
P5: 23.20.16.4973
P6: 5a96b1e5
P7: c0000005
P8: 0000000000038c4c
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE51.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3427e967bd7dbe8d61d820654ea1367c8f6572c_844f11b8_8e72e596-c028-4106-9189-7f1e3d72330e

Analysis symbol: 
Rechecking for solution: 0
Report Id: 5cf41217-cc84-4024-92a1-c11d434d3e8d
Report Status: 270532608
Hashed bucket: 545f27aeeb920207dd7bc1c10111481b
Cab Guid: 0 }
--------------
{ TimeGenerated = 5/10/2023 6:57:41 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.1.0
P3: 6443b447
P4: ig9icd64.dll
P5: 23.20.16.4973
P6: 5a96b1e5
P7: c0000005
P8: 0000000000038c4c
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_3427e967bd7dbe8d61d820654ea1367c8f6572c_844f11b8_8e72e596-c028-4106-9189-7f1e3d72330e

Analysis symbol: 
Rechecking for solution: 0
Report Id: 5cf41217-cc84-4024-92a1-c11d434d3e8d
Report Status: 2097156
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 5/10/2023 6:57:38 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.1.0, time stamp: 0x6443b447
Faulting module name: ig9icd64.dll, version: 23.20.16.4973, time stamp: 0x5a96b1e5
Exception code: 0xc0000005
Fault offset: 0x0000000000038c4c
Faulting process id: 0x2300
Faulting application start time: 0x01d9839aa82f5112
Faulting application path: C:\Users\Grant\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\DriverStore\FileRepository\k127153.inf_amd64_3f3936d8dec668b8\ig9icd64.dll
Report Id: 5cf41217-cc84-4024-92a1-c11d434d3e8d
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment] 2023-05-11 07:28
What mods are installed?

**Comment by Craluminum2413** [comment] 2023-05-11 10:15
My guess is you are using this mod https://mods.vintagestory.at/fsrone

**Comment by noelle-lavenza** [comment] 2023-05-11 11:54
It seems to be running with the wrong graphics card. Please make sure the game is set to launch with your dedicated graphics card.

**Comment by radfast** [comment] 2023-05-11 13:58
Duplicate of #1956 and others

In other people's cases the cause of the issue seems to be a Windows update or graphics driver update.    That's probably your situation too.  Try updating your graphics driver or re-installing your current graphics driver.   If that doesn't work, maybe roll your system back to a restore point from a time before this issue happening.

**Closed by radfast** 2023-05-11 13:58 UTC
Labels: status: incomplete
