### ISSUE TITLE
WAILA Missing, HUD Disappearing, Blocks are Blue

### ISSUE THREAD

**Issue by TheeAriaLee** [anegostudios/VintageStory-Issues#4576] opened 2024-11-29 18:42 UTC
### Game Version

1.20.0 pre 13

### Platform

Mac

### Modded

None

### SP/MP

Singleplayer

### Description

I have Mac OS Sonoma M2. The issue presented itself when I updated to 1.20.0 pre 13 
I created a new world, no mods. 
-The WAILA is missing
-The HUD disappears when I move the mouse. I technically resolved this when I added this command: .clientconfig selectedBlockOutline false
but I am not sure if this is going to affect gameplay if it remains "false"
-Blocks are blue-ish even on the title screen

### Screenshots

![Screenshot 2024-11-29 at 1 39 00 PM](https://github.com/user-attachments/assets/9eba25e3-e525-4829-8b38-dde876e3009c)
![Screenshot 2024-11-29 at 1 37 31 PM](https://github.com/user-attachments/assets/d451034c-faec-4624-8dbf-cfe97e73f4d7)
![Screenshot 2024-11-29 at 1 37 10 PM](https://github.com/user-attachments/assets/f2aa9364-7ef7-4c00-9313-bfe54f6235fe)
![Screenshot 2024-11-28 at 10 28 28 AM](https://github.com/user-attachments/assets/c5a2129c-51a5-456d-922d-ea3e6d3d774e)
![Screenshot 2024-11-28 at 10 29 13 AM](https://github.com/user-attachments/assets/7ecc07a3-814b-4a09-a89c-60849daa6dc4)
![Screenshot 2024-11-28 at 10 29 30 AM](https://github.com/user-attachments/assets/6447ec09-ccb3-4217-bd38-7536c3e22887)
![Screenshot 2024-11-28 at 10 29 40 AM](https://github.com/user-attachments/assets/ba05614d-a80c-47ab-ae6b-ccf0df6354a8)

### Logs

```Log```

**Comment by TheeAriaLee** [comment] 2024-11-29 18:43
I loaded a friends server to test and it occurred there as well so I do believe this is a base game issue.

**Comment by Lynngr** [comment] 2024-12-02 03:15
I have the same issue on an M1 mac mini running Sequoia 15.1

**Comment by barrowisp** [comment] 2024-12-05 04:08
Hi @TheeAriaLee,
By WAILA I assume you mean the Block Info Overlay.  Have you tried toggling it on?  with Ctrl+B or in the settings menu.

**Comment by Skamandrios42** [comment] 2024-12-05 13:07
same issue as [https://github.com/anegostudios/VintageStory-Issues/issues/4327](https://github.com/anegostudios/VintageStory-Issues/issues/4327) i guess. I have the same problems using a MacBook Air (2022 m2, Ventura 13.6.7) on 1.20.0-rc1.

**Comment by Craluminum2413** [comment] 2024-12-05 13:09
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4327

**Closed by Craluminum2413** 2024-12-05 13:09 UTC
Labels: platform: osx, status: new, department: code, version: 1.20
