### ISSUE TITLE
VS 1.18.2 rc1 game instantly crash when right click on trader - trying interact with, SMP Conquest of Block

### ISSUE THREAD

**Issue by DejFidOFF** [anegostudios/VintageStory-Issues#2700] opened 2023-05-05 16:09 UTC
### Game Version

VS 1.18-rc2

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Game instantly crash when trying interact with any trader. ( right mouse click ) 

### Logs

Running on 64 bit Windows with 64 GB RAM 
Game Version: v1.18.2-rc.1 (Unstable)
05.05.2023 18:04:13: Critical error occurred
Loaded Mods: acorns@0.5.1, ancienttools@1.5.3, bettercrates@1.6.0, canmarket@0.2.6, Ceramos@0.3.1, chiseltools@1.8.4, drdecor@1.2.0, extrachests@1.7.0, foundrymod@1.0.0, furniturelibrary@1.0.8, instruments@1.2.0, primitivesurvival@3.1.9, spyglass@0.4.5, tprunes@1.0.8, thecritterpack@0.7.6, translocatorengineeringredux@1.4.1, game@1.18.2-rc.1, carryon@1.0.0, commonlib@2.0.4, glidervar@1.1.0, hudclock@2.9.1, sailboat@1.1.0, petai@1.7.2, rifteye@0.1.3, simplestep@1.0.4, creative@1.18.2-rc.1, vsquest@0.4.1, survival@1.18.2-rc.1, workbenchexpansion@1.6.1, xlib@0.7.0, awearablelight@1.0.8, captureanimals@2.5.0, cob@1.1.3, em@2.0.0, playercorpse@1.7.1, wolftaming@1.7.2, xskills@0.7.0, bricklayers@2.0.0
System.IndexOutOfRangeException: Index je mimo hranice pole.
   v Vintagestory.GameContent.DlgTalkComponent.Execute() v VSSurvivalMod\Systems\Dialogue\Component\DlgTalkComponent.cs:řádek 17
   v Vintagestory.GameContent.DialogueController.ContinueExecute() v VSSurvivalMod\Systems\Dialogue\DialogueController.cs:řádek 92
   v Vintagestory.GameContent.EntityBehaviorConversable.OnInteract(EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode, EnumHandling& handled) v VSSurvivalMod\Systems\Dialogue\BehaviorConversable.cs:řádek 249
   v Vintagestory.API.Common.EntityAgent.OnInteract(EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode) v VintagestoryApi\Common\Entity\EntityAgent.cs:řádek 293
   v Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsNoBlockSelected(Single dt) v VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:řádek 438
   v Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) v VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:řádek 89
   v Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) v VintagestoryLib\Client\Util\ClientEventManager.cs:řádek 197
   v Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) v VintagestoryLib\Client\ClientMain.cs:řádek 789
   v Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) v VintagestoryLib\Client\ClientMain.cs:řádek 981
   v Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) v VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:řádek 243
   v Vintagestory.Client.ScreenManager.Render(Single dt) v VintagestoryLib\Client\ScreenManager.cs:řádek 724
   v Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) v VintagestoryLib\Client\ScreenManager.cs:řádek 627
   v Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) v VintagestoryLib\Client\ClientPlatform\GameWindow.cs:řádek 126
   v System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   v OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) v C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:řádek 479
   v OpenTK.GameWindow.DispatchRenderFrame() v C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:řádek 454
   v OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) v C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:řádek 375
   v Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   v Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) v VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:řádek 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 08.04.2023 12:38:35, Site = , Source = .NET Runtime, Message = Aplikace: Vintagestory.exe
Verze Framework: v4.0.30319
Popis: Proces byl ukončen z důvodu neošetřené výjimky.
Informace o výjimce: System.Exception
   na Vintagestory.Client.NoObf.TextureAtlasManager.LoadBitmap(Vintagestory.Client.NoObf.ClientMain, Vintagestory.API.Common.AssetLocationAndSource)
   na Vintagestory.Client.NoObf.TextureAtlasManager.LoadCompositeBitmap_Single(Vintagestory.Client.NoObf.ClientMain, Vintagestory.API.Common.AssetLocationAndSource)
   na Vintagestory.Client.NoObf.TextureAtlasManager.LoadCompositeBitmap_NoOverlayDispose(Vintagestory.Client.NoObf.ClientMain, Vintagestory.API.Common.AssetLocationAndSource)
   na Vintagestory.Client.NoObf.TextureAtlasManager.LoadBitmapsAsync(Vintagestory.API.Common.BakedBitmap[])
   na System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   na System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   na System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   na System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
--------------
{ TimeGenerated = 08.04.2023 12:14:36, Site = , Source = Application Error, Message = Název chybující aplikace: Vintagestory.exe, verze: 1.18.0.0, časové razítko: 0x642c31fe
Název chybujícího modulu: KERNELBASE.dll, verze: 10.0.19041.2728, časové razítko: 0xe7e53a4e
Kód výjimky: 0xc0020001
Posun chyby: 0x000000000002cd29
ID chybujícího procesu: 0x4a0
Čas spuštění chybující aplikace: 0x01d96a02a4a80281
Cesta k chybující aplikaci: D:\games\Vintagestory\Vintagestory.exe
Cesta k chybujícímu modulu: C:\Windows\System32\KERNELBASE.dll
ID zprávy: 6e071799-ed9b-4e17-a3be-e9e110d44533
Úplný název chybujícího balíčku: 
ID aplikace související s chybujícím balíčkem:  }
--------------
{ TimeGenerated = 08.04.2023 12:14:35, Site = , Source = .NET Runtime, Message = Aplikace: Vintagestory.exe
Verze Framework: v4.0.30319
Popis: Proces byl ukončen z důvodu neošetřené výjimky.
Informace o výjimce: kód výjimky c0020001, adresa výjimky 00007FF971F3CD29
Zásobník:
   na System.Environment._Exit(Int32)
   na System.Environment._Exit(Int32)
   na System.Environment.Exit(Int32)
   na System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   na OpenTK.NativeWindow.OnClosedInternal(System.Object, System.EventArgs)
   na System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   na OpenTK.Platform.Windows.WinGLNative.HandleDestroy(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   na OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   na OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   na OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   na OpenTK.Platform.Windows.WinGLNative.DestroyWindow()
   na OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   na OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   na OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   na OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   na OpenTK.Platform.Windows.Functions.PeekMessage(OpenTK.Platform.Windows.MSG ByRef, IntPtr, Int32, Int32, OpenTK.Platform.Windows.PeekMessageFlags)
   na OpenTK.Platform.Windows.Functions.PeekMessage(OpenTK.Platform.Windows.MSG ByRef, IntPtr, Int32, Int32, OpenTK.Platform.Windows.PeekMessageFlags)
   na OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   na OpenTK.GameWindow.Run(Double, Double)
   na Vintagestory.Client.ClientProgram.Start(Vintagestory.Client.ClientProgramArgs, System.String[])
   na Vintagestory.ClientNative.CrashReporter.Start(System.Threading.ThreadStart)
   na Vintagestory.Client.ClientProgram.Main(System.String[])
 }

**Comment by Craluminum2413** [comment] 2023-05-05 16:12
Does it happen without any mods installed?

**Comment by DejFidOFF** [comment] 2023-05-05 16:54
It´s at SMP can´t log in without any mod installed

**Comment by WickedSchnitzel** [comment] 2023-05-05 18:45
> Does it happen without any mods installed?

I just tested it in singleplayer without mods and it did crash as well.

**Comment by WickedSchnitzel** [comment] 2023-05-05 18:51
The funny thing is that some people with 1.18.1 clients cant connect to the 1.18.2 server until they have installed 1.18.2 and some people got no issues connecting and for these people traders do work.

**Comment by JRbBrown** [comment] 2023-05-05 21:35
I had a crash under very similar circumstances, so I think it might be best to put it in the same thread: unmodded, world created in an earlier version of 1.18 (I think 1.18.0-rc3) and updated to 1.18.2-rc1. The first time I tried to interact with a trader after updating to 1.18.2-rc1, the game crashed. I had interacted with that trader previously, before updating. Log below.

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.2-rc.1 (Unstable)
5/5/2023 5:25:06 PM: Critical error occurred
Loaded Mods: game@1.18.2-rc.1, creative@1.18.2-rc.1, survival@1.18.2-rc.1
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.DlgTalkComponent.Execute() in VSSurvivalMod\Systems\Dialogue\Component\DlgTalkComponent.cs:line 17
   at Vintagestory.GameContent.DialogueController.ContinueExecute() in VSSurvivalMod\Systems\Dialogue\DialogueController.cs:line 92
   at Vintagestory.GameContent.EntityBehaviorConversable.OnInteract(EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode, EnumHandling& handled) in VSSurvivalMod\Systems\Dialogue\BehaviorConversable.cs:line 249
   at Vintagestory.API.Common.EntityAgent.OnInteract(EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode) in VintagestoryApi\Common\Entity\EntityAgent.cs:line 293
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsNoBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 438
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 197
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 789
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 981
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 243
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 724
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 627
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 126
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 4/7/2023 12:39:35 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1402421717052153672, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.11.0
P3: 10.0.22621.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\[username]\AppData\Local\Temp\RDR40D0.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.10e91c9c-9ec9-41ae-a204-ed54b2aaaf4d.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.63a30833-645b-4b47-8a00-47584823e75b.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.5b667427-9d81-4629-9a73-848c518601b8.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.b1d1d7f2-e768-4788-aee0-67c568040603.tmp.xml

These files may be available here:
NULL

Analysis symbol: 
Rechecking for solution: 0
Report Id: fe0741ad-030c-4540-a771-c7f1129edfcc
Report Status: 268435456
Hashed bucket: 84f56296e9742f3d9376671f0e2fdf48
Cab Guid: 0 }
--------------
{ TimeGenerated = 3/18/2023 5:11:38 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Vintagestory.GameContent.BlockLiquidContainerTopOpened.get_CapacityLitres()
   at Vintagestory.GameContent.BlockFruitPress+<>c__DisplayClass3_0.<OnLoaded>b__1()
   at Vintagestory.API.Util.ObjectCacheUtil.GetOrCreate[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Vintagestory.API.Common.ICoreAPI, System.String, Vintagestory.API.Util.CreateCachableObjectDelegate`1<System.__Canon>)
   at Vintagestory.GameContent.BlockFruitPress+<>c__DisplayClass3_0.<OnLoaded>b__0()
   at Vintagestory.Server.ServerMain.ProcessMainThreadTasks()
   at Vintagestory.Server.ServerMain.ProcessMain()
   at Vintagestory.Server.ServerMain.Stop(System.String)
   at Vintagestory.Client.ClientProgram.ServerThreadStart()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

 }
--------------
{ TimeGenerated = 3/8/2023 8:29:15 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: AppHangTransient
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.11.0
P3: 63e108be
P4: unknown
P5: unknown
P6: unknown
P7: unknown
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.135da207-c58c-4063-bb12-07e5874657fb.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.db692b2e-20eb-45eb-b0c4-a0f152faa0b2.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.4fa30e17-2dd8-4b5d-ad07-1c1a032094f5.tmp.txt

These files may be available here:
NULL

Analysis symbol: 
Rechecking for solution: 0
Report Id: 3130a235-158a-4262-89ff-18c0392d2d86
Report Status: 2049
Hashed bucket: 
Cab Guid: 0 }

**Comment by DejFidOFF** [comment] 2023-05-06 04:11
I was about downgrade to 1.18.1 connected to the server ( run 1.18.2 rc1 ) and all working just fine.

**Comment by radfast** [comment] 2023-05-06 14:15
I confirm I can reproduce this in 1.18.2-rc2 in single player.

**Comment by radfast** [comment] 2023-05-06 14:51
Thanks for reporting all.  This is fixed in next release (I don't yet know if that will be 1.18.2-rc3 or 1.18.2 stable release)

**Closed by radfast** 2023-05-06 14:51 UTC
Labels: status: confirmed, priority: high, department: code, version: 1.18
