### ISSUE TITLE
Items teleporting to barrels

### ISSUE THREAD

**Issue by doornydew** [anegostudios/VintageStory-Issues#2045] opened 2022-07-24 04:50 UTC
me and my friend are playing MP and we are trying to make some alcoholic beverages, but we have then been noticing a very weird bug in which if we EVER use shift to either mass make/transfer something from inventory or even TO inventory, it very occasionally magically ends up in the barrels EVEN IF THEY ARE SEALED.
it almost feels like the barrels are permanently "opened" in immersive mouse mode and items are just being shift clicked in.
we tried with and without immersive mouse mode, and we can confirm that does not change anything.
even on a server restart, and both our clients restarting, its definetly not fixed.
even if you havent interacted with the barrels AT ALL if one of us is at home, we have observed items teleporting in there from even 500 blocks away. we kinda have no clue whats happening at this point, but we have completely STOPPED using shift to transfer or build anything, and the problem haa since then stopped, until one of us forgets and shift clicks again.

**Comment by doornydew** [comment] 2022-07-24 04:57
should probably specify we are playing on pre.3, as appearently pre.4 makes me (client) crash 100% of the time when trying to join.
the only error i could see in there though, was that it was trying to pull a file from a user that doesnt even exist on my computer (maybe a dev name?)

**Comment by tyronx** [comment] 2022-07-24 09:40
Heya, thanks for the report. Sounds like the inventory of the barrel did not get properly closed. 

Do you happen to have a number of steps to reliably reproduce this issue?

**Comment by doornydew** [comment] 2022-07-24 13:43
i can about about sum it up how it STARTED happening.
we were getting berry juice by squashing berries i  the fruit press, and then taking the juice into a bucket, picked up the bucket, filled like, 3/4 different barrels (1 has ale and has something in its ITEM SLOT that one does NOT teleport items.)
we then closed the barrels with no items, 1 of the  barrels was full of juice completely, so we sealed it, we also sealed 2 other with NON full juice, but was appearently allowed. ever since we closed the first barrel, its been happening, we HAVE had stuff teleport to our "rot" barrel outside that has NEVER been closed, so we honestly dont have a 100% idea whats going on

**Comment by doornydew** [comment] 2022-07-24 13:44
we can try later to see if we can replicate it completely in another world, but that will take a while

**Comment by wasakoki** [comment] 2022-08-09 14:08
@tyronx 
tested in rc4 on SP and MP, the the most consistent way for me to duplicate the issue is by:
1. place a barrel and a chest in world (distance doesnt matter, as long as both the chest and barrel's chunks are loaded it seems), also obtain any item that can be inserted into a barrel's item slot and keep it in your inventory for now.
2. exit/log out of the world (this isn't actually necessary but allows you to "target" which barrel the item will glitch into if you've interacted with multiple barrels since logging in.)
3. re-enter the world
4. open the barrel you placed in step 1
6. close the barrel's UI (you can do this by right clicking or moving far enough away to auto-close the GUI, it does not matter as long as the barrel remains chunk loaded)
7. open the chest's ui (any chest works & i've tested up to ~50 block distance while in survival mode)
8. **shift** click the dummy item mentioned into the chest. you will see the item in the chest
9. close the chest and re-open it again. you will see the item is no longer there.
10. go to the barrel mentioned in step 4, open it's UI and you will see the item you placed in the chest in step 8

these steps are unnecessarily convoluted because reality all you need to do is open some barrels, go play the game normally, and "randomly" your items will seem to either, disappear, create client-side only duplicate items, or makes the items disappear from your client entirely whenever you shift click an item to move it through inventories (it is only clientside, so nothing is actually duplicated or deleted from my testing, as reloading the world fixes any client-server desync). either way i just made it so precise because doing it this makes it alot less "random" and is reproducible every time on my end this way.

**Comment by doornydew** [comment] 2022-08-09 15:38
these steps perfectly recreate the bug for me. 

> @tyronx tested in rc4 on SP and MP, the the most consistent way for me to duplicate the issue is by:
> 
>     1. place a barrel and a chest in world (distance doesnt matter, as long as both the chest and barrel's chunks are loaded it seems), also obtain any item that can be inserted into a barrel's item slot and keep it in your inventory for now.
> 
>     2. exit/log out of the world (this isn't actually necessary but allows you to "target" which barrel the item will glitch into if you've interacted with multiple barrels since logging in.)
> 
>     3. re-enter the world
> 
>     4. open the barrel you placed in step 1
> 
>     5. close the barrel's UI (you can do this by right clicking or moving far enough away to auto-close the GUI, it does not matter as long as the barrel remains chunk loaded)
> 
>     6. open the chest's ui (any chest works & i've tested up to ~50 block distance while in survival mode)
> 
>     7. **shift** click the item mentioned in step 1 into the chest. you will see the item in the chest
> 
>     8. close the chest and re-open it again. you will see the item is no longer there.
> 
>     9. go to the barrel mentioned in step 4, open it's UI and you will see the item you placed in the chest in step 8
> 
> 
> these steps are unnecessarily convoluted because reality all you need to do is open some barrels, go play the game normally, and "randomly" your items will seem to either, disappear, create client-side only duplicate items, or makes the items disappear from your client entirely whenever you shift click an item to move it through inventories (it is only clientside, so nothing is actually duplicated or deleted from my testing, as reloading the world fixes any client-server desync). either way i just made it so precise because doing it this makes it alot less "random" and is reproducible every time on my end this way.

**Comment by tyronx** [comment] 2022-08-09 17:04
oh wow, thanks a lot! I was able to reproduce this - for the fire pit as well. Should be fixed for next release.

**Closed by tyronx** 2022-08-09 17:04 UTC

**Comment by doornydew** [comment] 2022-08-09 17:31
WHOOOOO

**Comment by wasakoki** [comment] 2022-08-09 18:14
i totally didn't have a personal vendetta to figure out what happened and write that when i planted 2 stacks of duplicate ghost seeds yesterday that magically unplanted themselves and appeared in a barrel when i logged into my world today😅
