### ISSUE TITLE
Game Crash when interaction with aged armor stands 

### ISSUE THREAD

**Issue by Seadogsalazar** [anegostudios/VintageStory-Issues#4336] opened 2024-10-20 06:46 UTC
### Game Version

1.20.0-pre5 and 1.20.0-pre6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When interacting with the generated armor stand in the resonance archives in the guards room the game crashes to desktop. Along with the Armor stand seemingly not spawning with the loot that should potentially have. unsure on this part as this as my first time going to the archives 

### How to reproduce

Create new world 
Find Resonance archives 
Find Guard Room 
interact with the aged armor stands to the far left. 
Games should crash immediately  

### Screenshots

![image](https://github.com/user-attachments/assets/576fa859-4eda-47f4-944b-dff5fc3a5660)

### Logs

```Log```Running on 64 bit Windows 10.0.22631.0 with 32679 MB RAM
Game Version: v1.20.0-pre.5 (Unstable)
10/19/2024 11:26:20 PM: Critical error occurred
Loaded Mods: game@1.20.0-pre.5, creative@1.20.0-pre.5, survival@1.20.0-pre.5, xinvtweaks@1.6.3
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityArmorStand.OnInteract(EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode) in VSSurvivalMod\Entities\EntityArmorStand.cs:line 59
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsNoBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 394
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 818
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1022
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 10/12/2024 10:45:54 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x20fc
Faulting application start time: 0x0x1db1d30175b0e5a
Faulting application path: C:\Users\zfami\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\zfami\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 8423fcc1-075d-446e-8a9c-a46952c96ee9
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment] 2024-10-20 08:09
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4183

**Closed by Craluminum2413** 2024-10-20 08:09 UTC
Labels: status: new
