### ISSUE TITLE
Beehive kilns do not allow fire brick gratings

### ISSUE THREAD

**Issue by Bughaw** [anegostudios/VintageStory-Issues#4765] opened 2024-12-21 22:20 UTC
### Game Version

v1.20.0rc5

### Platform

Linux

### Modded

Modded

### SP/MP

Singleplayer

### Description

Fire brick gratings are considered not allowed blocks and highlighted in red.  But fire brick blocks are required to build the beehive kiln in the first place.### 

### How to reproduce

Build a beehive kiln out of fire brick blocks and fire brick gratings.  It doesn't work.

### Screenshots

![screenshot (3)](https://github.com/user-attachments/assets/e1d4f476-c7ec-45d9-8f9d-c7477a0f5c6f)

### Logs

```Crash```

**Comment by Craluminum2413** [comment] 2024-12-21 22:38
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4721

**Closed by Craluminum2413** 2024-12-21 22:38 UTC
Labels: status: new

**Comment by Bughaw** [comment] 2024-12-21 23:13
Sorry.  I looked at open issues.  I didn't check closed ones.  I'll check more carefully next time.
