### ISSUE TITLE
Items stored in reed basket in trader's cart vanished

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1069] opened 2021-06-25 21:04 UTC
**Game Version:** 1.15.0-pre7
**Platform:** Windows 
**Modded:** No

### Description
I stored various items in the reed basket inside agricultural trader's cart (the main cart, not a trailer), then went for a trip a few chunks away, and when I returned, the basket was empty.

**Comment by tyronx** [comment] 2021-06-26 07:52
is this reproducible?

**Comment by sirStroam** [comment] 2021-06-30 05:01
Unable to reproduce in 1.15 pre 10. Closing until more detail is provided.

**Closed by sirStroam** 2021-06-30 05:01 UTC
Labels: department: code, priority: medium, status: incomplete, target: survival, type: bug
