### ISSUE TITLE
Tops of tall Trees sometimes glitch out after being chopped

### ISSUE THREAD

**Issue by EllingtonElectrician** [anegostudios/VintageStory-Issues#926] opened 2021-05-29 02:05 UTC
on VS 1.15.0-pre 1

Tops of some very tall Trees with their leaves sometimes remain and are non solid and unremovable after the tree gets chopped with a axe.

Restarting the game is the only way the tree gets removed

![vs tree bug](https://user-images.githubusercontent.com/11165643/120054902-bc807400-c000-11eb-92b8-75b6a7e9b98d.jpg)

**Comment by copygirl** [comment] 2021-05-29 05:52
Sounds like the chunk was not re-rendered, or it's a case of a duplicate ghost chunk.

**Comment by Craluminum2413** [comment] 2021-05-29 11:36
Sometimes this happens even with deleting them with Eraser (world edit instrument)

**Comment by Craluminum2413** [comment] 2021-06-04 10:52
You can fix it by typing "/debug cr" command, it will clear one but not all chunks

**Comment by Craluminum2413** [comment] 2021-06-04 11:09
This happens to any removed blocks in huge amounts
![2021-06-04_14-08-12](https://user-images.githubusercontent.com/69315569/120792522-520a8f00-c53e-11eb-844d-e2b8589fd1e9.png)

**Comment by Craluminum2413** [comment] 2021-06-06 11:06
I think it is very much related

**Comment by Craluminum2413** [comment] 2021-06-06 11:06
I think it is very much related #828

**Comment by Craluminum2413** [comment] 2021-06-06 12:51
@EllingtonElectrician Can you please screenshot the same place with enabled ".debug wireframe chunk"? Screenshot the entire chunk where the tree was cut down

**Comment by tyronx** [comment] 2021-06-24 15:27
No yes, this is most definitely a duplicate of #828. I observed the same issue as well. Thanks for the report.

**Closed by tyronx** 2021-06-24 15:27 UTC
Labels: status: new, target: engine, type: bug
