### ISSUE TITLE
Crash 1.20.0-pre.5 on "value cannot be null"

### ISSUE THREAD

**Issue by l1tch** [anegostudios/VintageStory-Issues#4252] opened 2024-10-07 18:32 UTC
### Game Version

v1.20.0-pre.5

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

No issue just helping on debug

### How to reproduce

No idea, i just opened the help for an item (as many times)

### Logs
```
Running on 64 bit Windows 10.0.19045.0 with 32366 MB RAM
Game Version: v1.20.0-pre.5 (Unstable)
07/10/2024 20:27:31: Critical error occurred
Loaded Mods: game@1.20.0-pre.5, creative@1.20.0-pre.5, survival@1.20.0-pre.5
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at Vintagestory.GameContent.CrateProperties.get_Item(String type) in VSSurvivalMod\Block\BlockCrate.cs:line 46
   at Vintagestory.GameContent.CollectibleBehaviorBoatableCrate.GetQuantitySlots(ItemStack bagstack) in VSSurvivalMod\Block\BlockCrate.cs:line 188
   at Vintagestory.API.Common.CollectibleObject.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1577
   at Vintagestory.API.Common.Block.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 2243
   at Vintagestory.GameContent.BlockContainer.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VSSurvivalMod\Block\BlockContainer.cs:line 263
   at Vintagestory.GameContent.BlockCrate.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VSSurvivalMod\Block\BlockCrate.cs:line 684
   at Vintagestory.API.Common.ItemStack.GetDescription(IWorldAccessor world, ItemSlot inSlot, Boolean debug) in VintagestoryApi\Common\Collectible\ItemStack.cs:line 401
   at Vintagestory.API.Client.SlideshowItemstackTextComponent.OnRequireInfoText(ItemSlot slot) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\SlideshowItemstackTextComponent.cs:line 178
   at Vintagestory.API.Client.GuiElementItemstackInfo.AsyncRecompose() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementItemstackInfo.cs:line 142
   at Vintagestory.API.Client.GuiElementItemstackInfo.SetSourceSlot(ItemSlot nowSlot, Boolean forceRecompose) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementItemstackInfo.cs:line 252
   at Vintagestory.API.Client.ItemstackComponentBase.RenderItemstackTooltip(ItemSlot slot, Double renderX, Double renderY, Single dt) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\ItemstackComponentBase.cs:line 67
   at Vintagestory.API.Client.GuiElementRichtext.RenderInteractiveElements(Single deltaTime) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementRichtext.cs:line 484
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime) in VintagestoryApi\Client\UI\GuiComposer.cs:line 718
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 389
   at Vintagestory.GameContent.GuiDialogHandbook.OnRenderGUI(Single deltaTime) in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 500
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 318
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 818
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1022
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by Craluminum2413** [comment] 2024-10-07 18:33
How to reproduce?

**Comment by maltiez2** [comment] 2024-11-06 08:59
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4296 actually

**Closed** 2024-11-06 10:41 UTC
Labels: status: duplicate, department: code, version: 1.20
