### ISSUE TITLE
A block disappeared while chiseling in 1.16.5

### ISSUE THREAD

**Issue by bonniesansclyde** [anegostudios/VintageStory-Issues#2118] opened 2022-08-13 23:04 UTC
**Game Version:** 1.16.5 
**Platform:** Windows
**Modded:** Yes
**SP/MP:** Multiplayer  

### Description
Used a steel chisel on a mudbrick/red creative block. The block disappeared, and now crashes the client whenever we try to break it.

### How to reproduce
Unsure how to reproduce, as we have been chiseling we have other blocks like this that are fine.

### Logs
```
Loaded Mods: weaponpacka@1.2.4, ancienttools@1.4.2, animalcages@2.0.6, tonwexp@1.0.9, axleinblocks@1.0.12, backpackpackplus@1.0.3, betterdrifters@2.1.3, buildingplus@1.1.2, cavecontent@1.0.1, chiseltools@1.4.6, expandedfoods@1.5.3-pre.8, fancydoors@1.1.1, weaponpackg@1.0.0, moreclasses@1.2.4, necessaries@1.1.2, orecrystals@1.3.6, pieontheshelf@1.0.0, potontheshelf@1.0.0, primitivesurvival@2.9.2, qptech@1.9.0, tradeomat@1.6.1, viescraftmachines@1.17.1, game@1.16.5, alchemy@1.6.3, carrycapacity@0.6.5, fancyplanters@1.0.4, fixbadrecipes@1.0.2, lichen@1.6.1, medievalexpansion@3.7.1, moreanimals@1.2.3, petai@1.4.4, playercorpse@1.3.1, stonequarry@1.6.5, tpnet@1.5.1, usefulstuff@2.3.2, vanvar@1.1.3, creative@1.16.5, survival@1.16.5, wildfarming@1.2.8, woodbarrels@1.0.2, woodchests@1.0.3, workbenchexpansion@1.4.1, xlib@0.6.8, xrowboat@0.0.3, bricklayers@0.9.1, cats@1.4.2, feverstonehorses@1.2.6, wildcraft@1.2.1, wolftaming@1.4.0, xskillspatched@0.6.9-dev.8
8/13/2022 4:42:43 PM: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.Client.NoObf.SystemRenderDecals.UpdateDecal(BlockDecal decal)
   at Vintagestory.Client.NoObf.SystemRenderDecals.AddBlockBreakDecal(BlockPos pos, Int32 stage)
   at Vintagestory.Client.NoObf.SystemRenderDecals.OnPlayerBreakingBlock(_dUMdSRYWwkPRAgCF1VLBqj7zle3 blockDamage)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerBlockBreaking(_dUMdSRYWwkPRAgCF1VLBqj7zle3 blockDamage)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.ContinueBreakSurvival(BlockSelection blockSelection, Block block, Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
```

**Comment by Craluminum2413** [comment] 2022-08-19 09:51
Duplicate of #2040

**Closed by Craluminum2413** 2022-08-19 09:51 UTC
Labels: status: new
