### ISSUE TITLE
Crash after closing world.

### ISSUE THREAD

**Issue by NaturalHate** [anegostudios/VintageStory-Issues#3536] opened 2024-01-29 14:39 UTC
After closing a test world my game crashed. I'm not sure why it doesn't list the mods there, maybe because it happened upon entering the main menu again. I did do a reload of the world via hotkeys before closing it (I finished it), so maybe it's related to that.

```
Running on 64 bit Linux (Freedesktop SDK 22.08 (Flatpak runtime)) [Kernel 6.7.0.204] with 32010 MB RAM
Game Version: v1.19.3 (Stable)
1/29/2024 3:34:38 PM: Critical error occurred
Loaded Mods: 
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'The ThreadLocal object has been disposed.'.
   at System.Threading.ThreadLocal`1.GetValueSlow()
   at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionStatesNative(IWorldAccessor world, ItemSlot inslot) in VintagestoryApi\Common\Collectible\Collectible.cs:line 2382
   at Vintagestory.API.Common.CollectibleObject.AppendPerishableInfoText(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1767
   at Vintagestory.API.Common.CollectibleObject.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1713
   at Vintagestory.GameContent.GuiHandbookItemStackPage..ctor(ICoreClientAPI capi, ItemStack stack) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 33
   at Vintagestory.GameContent.ModSystemSurvivalHandbook.onCreatePagesAsync() in VSSurvivalMod\Systems\Handbook\SurvivalHandbook.cs:line 79
   at Vintagestory.GameContent.GuiDialogHandbook.LoadPages_Async() in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 411
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by NaturalHate** [comment] 2024-01-29 18:18
Maybe related crash when I tried reloading the world (after setting the worldmap command to switch to the colored one):

```
Running on 64 bit Linux (Freedesktop SDK 22.08 (Flatpak runtime)) [Kernel 6.7.0.204] with 32010 MB RAM
Game Version: v1.19.3 (Stable)
1/29/2024 7:16:46 PM: Critical error occurred
Loaded Mods: 
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Vintagestory.Client.NoObf.GuiManager.Dispose(ClientMain game) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 559
   at Vintagestory.Client.NoObf.ClientMain.Dispose() in VintagestoryLib\Client\ClientMain.cs:line 2597
   at Vintagestory.Client.NoObf.ClientMain.DestroyGameSession(Boolean gotDisconnected) in VintagestoryLib\Client\ClientMain.cs:line 2545
   at Vintagestory.Client.GuiScreenRunningGame.ExitOrRedirect(Boolean isDisconnect, String reason) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 273
   at Vintagestory.Client.GuiScreenRunningGame.ReloadWorld(String reason) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 261
   at Vintagestory.Client.ScreenManager.<setupHotkeyHandlers>b__49_1(KeyCombination viaKeyComb) in VintagestoryLib\Client\ScreenManager.cs:line 296
   at Vintagestory.Client.HotkeyManager.TriggerHotKey(KeyEvent keyEventargs, IWorldAccessor world, IPlayer player, Boolean allowCharacterControls, Boolean isGlobal, Boolean fallBack) in VintagestoryLib\Client\HotkeyManager.cs:line 375
   at Vintagestory.Client.NoObf.ClientMain.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1714
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown_Patch1(ClientPlatformWindows this, KeyboardKeyEventArgs e)
   at OpenTK.Windowing.Desktop.NativeWindow.KeyCallback(Window* window, Keys key, Int32 scancode, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by Craluminum2413** [comment] 2024-02-05 10:38
Duplicate of #2688

**Closed by Craluminum2413** 2024-02-05 10:38 UTC
Labels: status: duplicate
