### ISSUE TITLE
Boat direction reverses when looking all the way left.

### ISSUE THREAD

**Issue by RTHauke** [anegostudios/VintageStory-Issues#4429] opened 2024-11-03 16:33 UTC
### Game Version

v1.20.9

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When traveling in a boat, if you look all the way to the left, the direction of travel reverses.  If you're holding W you start going backwards.  If you're holding S you start going forwards.

This also happens in 1.20.8.

### How to reproduce

1. Jump into boat on large water area.
2. Look forward, press W to move.
3. Look all the way to the left.
4. Boat slows then starts moving backwards.
5. It appears to change to the opposite direction that you were moving.  Doing 1-4 while pressing S has the opposite effect.

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2024-11-03 16:36
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4137

**Closed by Craluminum2413** 2024-11-03 16:36 UTC
Labels: status: new
