### ISSUE TITLE
1.18 Game crashes on exit when a raft exists in the world.

### ISSUE THREAD

**Issue by AbortRetryFail** [anegostudios/VintageStory-Issues#2501] opened 2023-03-21 18:20 UTC
### Game Version

v1.18.0-pre.7

### Platform

Linux

### Modded

None

### SP/MP

Singleplayer

### Description

Game crashes on exit when a raft exists in the world.

I don't know if this is just my singleplayer game or any, but I get this error when I quit:

### How to reproduce

I guess:
1. Put a raft in the water
2. Paddle around a while
3. Quit the game

### Logs

```
Game Version: v1.18.0-pre.7 (Unstable)
3/21/2023 2:17:03 PM: Critical error occurred
Loaded Mods: 
System.NotImplementedException: The method or operation is not implemented.
  at Vintagestory.GameContent.EntityBoat.Dispose () [0x00000] in <5f7ac27833fb40b4bf6e191cd15a98aa>:0 
  at Vintagestory.Client.NoObf.ClientEventManager.Dispose () [0x00022] in <fe73de45fbe84d4c8546996bf4e463b8>:0 
  at Vintagestory.Client.NoObf.ClientMain.Dispose () [0x0018d] in <fe73de45fbe84d4c8546996bf4e463b8>:0 
  at Vintagestory.Client.NoObf.ClientMain.DestroyGameSession (System.Boolean gotDisconnected) [0x00149] in <fe73de45fbe84d4c8546996bf4e463b8>:0 
  at Vintagestory.Client.NoObf.GuiDialogEscapeMenu.OnLeaveWorld () [0x0001c] in <fe73de45fbe84d4c8546996bf4e463b8>:0 
  at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement (Vintagestory.API.Client.ICoreClientAPI api, Vintagestory.API.Client.MouseEvent args) [0x0004f] in <5115116e4aec4073837efdde590257c5>:0 
  at Vintagestory.API.Client.GuiElement.OnMouseUp (Vintagestory.API.Client.ICoreClientAPI api, Vintagestory.API.Client.MouseEvent args) [0x00014] in <5115116e4aec4073837efdde590257c5>:0 
  at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp (Vintagestory.API.Client.ICoreClientAPI api, Vintagestory.API.Client.MouseEvent args) [0x00009] in <5115116e4aec4073837efdde590257c5>:0 
  at Vintagestory.API.Client.GuiComposer.OnMouseUp (Vintagestory.API.Client.MouseEvent mouse) [0x0001a] in <5115116e4aec4073837efdde590257c5>:0 
  at Vintagestory.API.Client.GuiDialog.OnMouseUp (Vintagestory.API.Client.MouseEvent args) [0x00022] in <5115116e4aec4073837efdde590257c5>:0 
  at Vintagestory.Client.NoObf.GuiDialogEscapeMenu.OnMouseUp (Vintagestory.API.Client.MouseEvent args) [0x00000] in <fe73de45fbe84d4c8546996bf4e463b8>:0 
  at Vintagestory.Client.NoObf.GuiManager.OnMouseUp (Vintagestory.API.Client.MouseEvent args) [0x00028] in <fe73de45fbe84d4c8546996bf4e463b8>:0 
  at Vintagestory.Client.NoObf.ClientMain.OnMouseUp (Vintagestory.API.Client.MouseEvent args) [0x00093] in <fe73de45fbe84d4c8546996bf4e463b8>:0 
  at Vintagestory.Client.GuiScreenRunningGame.OnMouseUp (Vintagestory.API.Client.MouseEvent args) [0x00013] in <fe73de45fbe84d4c8546996bf4e463b8>:0 
  at Vintagestory.Client.ScreenManager.OnMouseUp (Vintagestory.API.Client.MouseEvent e) [0x0000d] in <fe73de45fbe84d4c8546996bf4e463b8>:0 
  at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp (System.Object sender, OpenTK.Input.MouseButtonEventArgs e) [0x0002c] in <fe73de45fbe84d4c8546996bf4e463b8>:0 
  at (wrapper delegate-invoke) System.EventHandler`1[OpenTK.Input.MouseButtonEventArgs].invoke_void_object_TEventArgs(object,OpenTK.Input.MouseButtonEventArgs)
  at OpenTK.NativeWindow.OnMouseUp (OpenTK.Input.MouseButtonEventArgs e) [0x00000] in <a4886e33f9fc416195d24950e7205b94>:0 
  at OpenTK.NativeWindow.OnMouseUpInternal (System.Object sender, OpenTK.Input.MouseButtonEventArgs e) [0x00000] in <a4886e33f9fc416195d24950e7205b94>:0 
  at (wrapper delegate-invoke) System.EventHandler`1[OpenTK.Input.MouseButtonEventArgs].invoke_void_object_TEventArgs(object,OpenTK.Input.MouseButtonEventArgs)
  at OpenTK.Platform.NativeWindowBase.OnMouseUp (OpenTK.Input.MouseButton button) [0x0002e] in <a4886e33f9fc416195d24950e7205b94>:0 
  at OpenTK.Platform.X11.X11GLNative.ProcessEvents () [0x008e3] in <a4886e33f9fc416195d24950e7205b94>:0 
  at OpenTK.NativeWindow.ProcessEvents (System.Boolean retainEvents) [0x00035] in <a4886e33f9fc416195d24950e7205b94>:0 
  at OpenTK.NativeWindow.ProcessEvents () [0x00000] in <a4886e33f9fc416195d24950e7205b94>:0 
  at OpenTK.GameWindow.Run (System.Double updates_per_second, System.Double frames_per_second) [0x000da] in <a4886e33f9fc416195d24950e7205b94>:0 
  at OpenTK.GameWindow.Run () [0x00000] in <a4886e33f9fc416195d24950e7205b94>:0 
  at Vintagestory.Client.ClientProgram.Start (Vintagestory.Client.ClientProgramArgs args, System.String[] rawArgs) [0x00421] in <269013a257d7483f9834799a960d0296>:0 
  at Vintagestory.Client.ClientProgram+<>c__DisplayClass16_0.<.ctor>b__0 () [0x00000] in <269013a257d7483f9834799a960d0296>:0 
  at Vintagestory.ClientNative.CrashReporter.Start (System.Threading.ThreadStart start) [0x00007] in <fe73de45fbe84d4c8546996bf4e463b8>:0 
Crash written to file at "/home/arf/.config/VintagestoryData/Logs/client-crash.txt"
```

**Comment by Craluminum2413** [comment] 2023-03-21 18:23
Duplicate of #2465

**Closed by Craluminum2413** 2023-03-21 18:23 UTC
Labels: status: new
