### ISSUE TITLE
Beams can't be broken in chiseld plate.

### ISSUE THREAD

**Issue by Alexiestree** [anegostudios/VintageStory-Issues#3558] opened 2024-02-05 03:05 UTC
### Game Version

1.19.3

### Platform

Linux

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

wooden plate was chiseled and after I used beam to decorate. beam got stuck to the chiseled stairs and you cant destroy it.

### How to reproduce

chisel some wooden plate and put a beam on it and try to break a beam from it

### Screenshots

![Снимок экрана от 2024-02-05 08-02-13](https://github.com/anegostudios/VintageStory-Issues/assets/7397194/b5f97bb9-ce5b-496b-aff7-cd7f8063169a)

### Logs

```Log```

**Comment by Alexiestree** [comment] 2024-02-05 03:07
it was chiseld plate*

**Comment by Craluminum2413** [comment] 2024-02-05 10:18
Duplicate of #3313

**Closed by Craluminum2413** 2024-02-05 10:18 UTC
Labels: status: new
