### ISSUE TITLE
1.20rc6 Fruitpress error

### ISSUE THREAD

**Issue by DejFidOFF** [anegostudios/VintageStory-Issues#4816] opened 2024-12-28 00:42 UTC
### Game Version

1.20rc6

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Fruitpress causing spaming error in server console

### How to reproduce

Press a cranberries at fruitpress, leave a bucket with juice there and also dry mash. I guess when dry mash spoils it causing error.

### Logs

[Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityFruitPress.onTick100msServer_Patch2(BlockEntityFruitPress this, Single dt)
   at Vintagestory.Common.GameTickListener.OnTriggered(Int64 ellapsedMilliseconds) in VintagestoryLib\Common\Model\GameTickListener.cs:line 27

**Comment by pizza2004** [comment] 2024-12-28 02:09
Did this rot with the machine screwed down, per chance?

**Comment by DejFidOFF** [comment] 2024-12-28 09:03
> Did this rot with the machine screwed down, per chance? Also, what mods are you using?

have no idea I was actingfast before server crash.
https://www.vintagestory.cz/downloads/Waterworld_mods_www.vintagestory.cz.pdf

**Comment by pizza2004** [comment] 2024-12-28 19:20
I tried a bunch of different stuff in a vanilla world and was unable to reproduce this error.  Any more information you could give to determine if it's because of vanilla would be appreciated.

**Comment by DejFidOFF** [comment] 2024-12-28 23:10
The error comes from nowhere:
28.12.2024 01:26:04 [Error] At position 128401, 116, 133959 for block fruitpress-we a BlockEntityFruitPress threw an error when ticked:
28.12.2024 01:26:04 [Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityFruitPress.onTick100msServer_Patch2(BlockEntityFruitPress this, Single dt)
   at Vintagestory.Common.GameTickListener.OnTriggered(Int64 ellapsedMilliseconds) in VintagestoryLib\Common\Model\GameTickListener.cs:line 27

**Comment by DejFidOFF** [comment] 2024-12-28 23:11
Can´t give you more information, that´s all I have.

**Comment by pizza2004** [comment] 2024-12-29 00:00
Do you happen to know if any of the mods you have installed patch the fruitpress at all?  Has this only happened the one time?

**Comment by DejFidOFF** [comment] 2024-12-29 00:25
> Do you happen to know if any of the mods you have installed patch the fruitpress at all? Has this only happened the one time?

I think no mod patched fruitpress.

**Comment by pizza2004** [comment] 2024-12-29 05:39
Since I can't figure out any way to replicate this I'm going to close it for now.  If it happens again feel free to reopen the issue.

**Closed by pizza2004** 2024-12-29 05:39 UTC
Labels: department: code, status: can't reproduce
