### ISSUE TITLE
Game just crushing while get started

### ISSUE THREAD

**Issue by Pepuk99** [anegostudios/VintageStory-Issues#1788] opened 2022-03-06 08:32 UTC
**Game Version:**  1.16.3
**Platform:** Windows 10
**Modded:** No 
**SP/MP:** Singleplayer

### Description
Game just crushing while get started

![image](https://user-images.githubusercontent.com/101039436/156915558-3d3f632f-b0f3-49c6-a5c4-cb92c480e028.png)

.

**Comment by copygirl** [comment] 2022-03-06 09:04
You're using a pirated version, which is likely the cause of this issue.
We can't provide support for pirated versions.
Duplicate of #1736.

**Closed by copygirl** 2022-03-06 09:04 UTC
Labels: status: invalid
