### ISSUE TITLE
Server System.IndexOutOfRangeException: Index was outside the bounds of the array

### ISSUE THREAD

**Issue by DarthJimothy** [anegostudios/VintageStory-Issues#4492] opened 2024-11-11 00:50 UTC
I just got a new Official Game Server and am getting the above error message. I have turned off all my mods.
```
Running on 64 bit Windows 10.0.19045.0 with 36757 MB RAM
Game Version: v1.19.8 (Stable)
11/11/2024 11:12:54 AM: Critical error occurred
Loaded Mods: 
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.API.Client.GuiElementDropDown.ComposeCurrentValue() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementDropDown.cs:line 238
   at Vintagestory.API.Client.GuiElementDropDown.ComposeDynamicElements() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementDropDown.cs:line 230
   at Vintagestory.API.Client.GuiElementDropDown.ComposeElements(Context ctx, ImageSurface surface) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementDropDown.cs:line 146
   at Vintagestory.API.Client.GuiComposer.Compose(Boolean focusFirstElement) in VintagestoryApi\Client\UI\GuiComposer.cs:line 434
   at Vintagestory.Client.GuiScreenServerDashboard.screenSelectRegion(GameServerStatus status) in VintagestoryLib\Client\MainMenu\Screens\HostedServer\GuiScreenSelectRegion.cs:line 15
   at Vintagestory.Client.GuiScreenServerDashboard.onStatusReady(EnumAuthServerResponse reqStatus, GameServerStatus gameServerStatus) in VintagestoryLib\Client\MainMenu\Screens\HostedServer\GuiScreenServerDashboard.cs:line 52
   at Vintagestory.Client.Util.ServerCtrlBackendInterface.<>c__DisplayClass11_0.<GetStatus>b__0(EnumAuthServerResponse status, GameServerStatus response) in VintagestoryLib\Client\Util\ServerCtrlBackend\ServerCtrlBackendInterface.cs:line 133
   at Vintagestory.Client.Util.ServerCtrlBackendInterface.<>c__DisplayClass18_1`1.<runAction>b__1() in VintagestoryLib\Client\Util\ServerCtrlBackend\ServerCtrlBackendInterface.cs:line 225
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 2
==================================
{ TimeGenerated = 6/11/2024 8:00:55 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.5072, time stamp: 0xef4f0afe
Exception code: 0xe0434352
Fault offset: 0x000000000002ba99
Faulting process id: 0x4f30
Faulting application start time: 0x01db302e8811c1fa
Faulting application path: E:\Games\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 71a2a2a9-e554-413d-8a6c-1dfc638dc827
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 6/11/2024 8:00:32 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.5072, time stamp: 0xef4f0afe
Exception code: 0xe0434352
Fault offset: 0x000000000002ba99
Faulting process id: 0x2ac0
Faulting application start time: 0x01db302e7bce4fba
Faulting application path: E:\Games\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 4ebeb54b-a5fb-4de1-99a0-f7818f186256
Faulting package full name: 
Faulting package-relative application ID:  }
```

**Comment by Craluminum2413** [comment] 2024-11-11 10:48
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/3158

**Closed by Craluminum2413** 2024-11-11 10:48 UTC

**Comment by antho47** [comment] 2024-11-11 12:53
news?
