### ISSUE TITLE
seasonal coloring looks strange

### ISSUE THREAD

**Issue by stony99** [anegostudios/VintageStory-Issues#2575] opened 2023-04-11 19:04 UTC
### Game Version

v1.18-rc5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Lots of weird colored patches everywhere. My graphiccard is a GForce GTX 960

### Screenshots

https://postimg.cc/DW8J18Y0

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2023-04-11 19:07
Related tp #2452

**Comment by stony99** [comment] 2023-04-11 20:20
The problem seems to occur only with dirtblock(grassy), sand and gravel do not have the problem. The further south I go the less the problem occurs. At 20 °C outside temperature it seems to be completely gone.

**Comment by stony99** [comment] 2023-04-12 12:31
After 3-4 ingame days everything now looks normal again, no more weird patches.

**Comment by Aurora5252** [comment] 2023-04-16 04:00
I have writen a way to reproduce the problem in #2452 for those who want to test it.

**Comment by Craluminum2413** [comment] 2023-05-18 16:04
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/2452

**Closed by Craluminum2413** 2023-05-18 16:04 UTC
Labels: status: new
