### ISSUE TITLE
Physics Manager Crash

### ISSUE THREAD

**Issue by WickedSchnitzel** [anegostudios/VintageStory-Issues#4496] opened 2024-11-12 15:11 UTC
### Game Version

1.20.0-pre.13

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Sometimes crashes with below error (spamming server-main.txt). Before that happens i did notice entities not moving any more (but still animating), some floating in the air after being spawned by worldgen.

### Logs

[Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.Server.PhysicsManager.DoWork() in VintagestoryLib\Server\PhysicsManager.cs:line 524
   at Vintagestory.Common.LoadBalancer.SynchroniseWorkToMainThread() in VintagestoryLib\Common\LoadBalancer.cs:line 81
   at Vintagestory.Server.PhysicsManager.TickFixedRate30TPS() in VintagestoryLib\Server\PhysicsManager.cs:line 299
   at Vintagestory.Server.PhysicsManager.ServerTick(Single dt) in VintagestoryLib\Server\PhysicsManager.cs:line 100
   at Vintagestory.Common.GameTickListener.OnTriggered(Int64 ellapsedMilliseconds) in VintagestoryLib\Common\Model\GameTickListener.cs:line 27
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 57
   at Vintagestory.Server.ServerMain.Process() in VintagestoryLib\Server\ServerMain.cs:line 904

**Comment by Craluminum2413** [comment] 2024-11-12 15:12
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4328

**Closed by Craluminum2413** 2024-11-12 15:12 UTC
Labels: status: new, department: code, version: 1.20
