### ISSUE TITLE
DLL Not Found Exception - Crash on boot (Mac)

### ISSUE THREAD

**Issue by clderclderclder** [anegostudios/VintageStory-Issues#1814] opened 2022-03-16 04:05 UTC
Mac OS X El Capitan
Vintage Story 1.16.4

I am unable to boot and play game with a fresh install of 1.16.4 . Was able to use 1.15 versions on this Mac with no problems. I am trying to update so I can play multiplayer, but the game won’t boot and spits out this error message every time I try to open it:

Game Version: v1.16.4 (Stable)
Loaded Mods: 
3/15/2022 11:36:57 PM: Critical error occurred
System.DllNotFoundException: Lib64/libnanosvg.dylib assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) NanoSvg.SvgNativeMethods.nsvgCreateRasterizer()
  at Vintagestory.Client.NoObf.SvgLoader..ctor (Vintagestory.API.Client.ICoreClientAPI _capi) [0x0000d] in <6b6988c5e6264e7e8b7a32e875df9528>:0 
  at _TG5t77dO5Hrs6NYCtTdSBAAEJqq..ctor (_lAuHsYOBOAjBMdATFXwLUtH7N00 , Vintagestory.API.Client.ICoreClientAPI ) [0x00030] in <6b6988c5e6264e7e8b7a32e875df9528>:0 
  at _6FhnQpolR3UHct1jP4AASxniJNB..ctor (_lAuHsYOBOAjBMdATFXwLUtH7N00 ) [0x00025] in <6b6988c5e6264e7e8b7a32e875df9528>:0 
  at _lAuHsYOBOAjBMdATFXwLUtH7N00._mhlr8s7wtMvxaJGpVy2Ag90jUBK (_3HJA5NvAIx31LXjscc3HGjXaR6q , System.String[] ) [0x00000] in <6b6988c5e6264e7e8b7a32e875df9528>:0 
  at _TRhArnJABwZoV9Vt7Ld2l65Xzgg._mhlr8s7wtMvxaJGpVy2Ag90jUBK (_3HJA5NvAIx31LXjscc3HGjXaR6q , System.String[] ) [0x003bf] in <29d88641cda44fa481e9734466805d45>:0 
  at _TRhArnJABwZoV9Vt7Ld2l65Xzgg+_fSeTszd4whwFiRbaTa0d2CyPdfJ._SvbPzpxmSlo5pUMfGCrGwu2xebc () [0x00000] in <29d88641cda44fa481e9734466805d45>:0 
  at _q0zAVOrWbMX04rMA9G3HIFVuGjA._mhlr8s7wtMvxaJGpVy2Ag90jUBK (System.Threading.ThreadStart ) [0x00007] in <6b6988c5e6264e7e8b7a32e875df9528>:0

**Comment by copygirl** [comment] 2022-03-16 06:00
From my little understanding, they changed something about how DLLs are located on OSX and it's been making things difficult for us.

Duplicate of #1629.

**Closed by copygirl** 2022-03-16 06:00 UTC
Labels: status: duplicate

**Comment by clderclderclder** [comment] 2022-03-16 15:00
It is an older Macintosh computer that is running El Capitan for its operating system. I am still able to boot up and use 1.15 versions of Vintage Story, just not the new 1.16 versions. If there is anything I can do to fix the issue manually, I am very interested in trying.
