### ISSUE TITLE
Weird shadows with cobblestone slabs

### ISSUE THREAD

**Issue by VintageStoryPlayer** [anegostudios/VintageStory-Issues#4516] opened 2024-11-15 12:33 UTC
### Game Version

v.1.19.8

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

there are weird shadows on some of my stone slabs i turned some of these using a wrench although i don't know if that has anything to do with the shadows these shadows disappear if you stand directly beneath the block screenshot was taken and night light was a copper lantern the stone i used for the slabs is granite and this roof has axles connected to it that lead to a windmill and my smithy

### How to reproduce

i tried reproducing it in creative but it did not work

### Screenshots

![image](https://github.com/user-attachments/assets/808ee731-c6b4-48cd-a9e1-0952054aeb08)

### Logs

```Log```
[client-main.txt](https://github.com/user-attachments/files/17775376/client-main.txt)

**Comment by VintageStoryPlayer** [comment] 2024-11-15 12:38
oh ok thanks for letting me know

**Comment by Craluminum2413** [comment] 2024-11-15 12:47
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/3662

**Closed by Craluminum2413** 2024-11-15 12:47 UTC
Labels: status: new, department: code
