### ISSUE TITLE
Empty buckets that had milk in them will not stack with other empty buckets

### ISSUE THREAD

**Issue by svanheulen** [anegostudios/VintageStory-Issues#1671] opened 2022-02-03 01:19 UTC
**Game Version:** 1.16.3
**Platform:** Linux
**Modded:** Yes
**SP/MP:** Singleplayer

### Description
If you empty out a bucket of milk, the newly empty bucket will not stack with other empty buckets. But it will stack with empty buckets that had milk in them previously. If you place the bucket on the ground with shift + right-click and then pick it back up, it will properly stack again.

### How to reproduce
1. Have 2 empty buckets
2. Milk a sheep with one of the buckets
3. Pour the milk into a barrel
4. Try stacking the 2 empty buckets

**Comment by Craluminum2413** [comment] 2022-02-03 01:20
Duplicate of #862

**Closed** 2022-02-03 04:29 UTC
Labels: status: duplicate
