### ISSUE TITLE
Crash to desktop

### ISSUE THREAD

**Issue by pkwild54** [anegostudios/VintageStory-Issues#1116] opened 2021-07-07 22:54 UTC
**Game Version:** 1.15-rc-1
**Platform:** Windows 
**Modded:** Yes 

### Description
Crashes to desktop when attempting to sleep in bed.

### How to reproduce
1. Find an aged bed in a ruin.
2. Try to sleep in it.
3. It crashes.

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

#Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.0-rc.1 (Unstable)7/7/2021 5:49:51 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityGroundStorage.DetermineStorageProperties(ItemSlot sourceSlot)
   at Vintagestory.GameContent.BlockEntityGroundStorage.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldForResolving)
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(_f47bFFjjZjqsZ07abkCWRRjJjq5 p, ClientMain game)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(_SPt7iF5LhXmcxMRSPZV1A0ZATGh packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _Hhyykp3OIyR3A9gDXvfRYXmIxHM._N2PKmadywKhrSAOGDRbet32cyTB(Single )
   at _GatfFd3kn5xATuUyKYscxn8d0CO._4TEOzZagWNPjzZVqfu2HCwbLFqC(Single )
   at _GatfFd3kn5xATuUyKYscxn8d0CO._x3D81oTSuYvhXUwgP6x9PwySgdc(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _woe4UEAalnRbwPXBTK09ZhdFcWO._5qgAk5LLuTcbcRWXQsq1b3Y8T8H(_arFvNaodTjXO5ObZ7eEgimkezLG , String[] )
   at _ZFpbvq06JtO6suJqmLDa8Hs9YeH._5qgAk5LLuTcbcRWXQsq1b3Y8T8H(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 6/28/2021 12:14:15 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1999085723610005733, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Pamela\AppData\Local\Temp\RDR5F18.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5F57.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5F87.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6041.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6061.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 5a01ff05-4ab6-4ec7-92d3-c0aad8233c97
Report Status: 268435456
Hashed bucket: ee3def5252484136fbbe2ddfbf5440e5
Cab Guid: 0 }
--------------
{ TimeGenerated = 5/31/2021 7:23:33 AM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FFD2D8B4B89
Stack:
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at System.Environment._Exit(Int32)
   at System.Environment._Exit(Int32)
   at System.Environment.Exit(Int32)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.NativeWindow.OnClosedInternal(System.Object, System.EventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.Platform.Windows.WinGLNative.HandleDestroy(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   at OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.DestroyWindow()
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.PeekMessage(OpenTK.Platform.Windows.MSG ByRef, IntPtr, Int32, Int32, OpenTK.Platform.Windows.PeekMessageFlags)
   at OpenTK.Platform.Windows.Functions.PeekMessage(OpenTK.Platform.Windows.MSG ByRef, IntPtr, Int32, Int32, OpenTK.Platform.Windows.PeekMessageFlags)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double, Double)
   at _ISiSTzGmXXpAqo3PzdxdVD1bClZ._ofvn0Tr1zNGCbNV3SxvKs2MXNP(_C7CLMRbe3BejVtaARYCgl7Bg1vl, System.String[])
   at _0Y0SN1uu1V65pRLxvnN2xsIjXAg._ofvn0Tr1zNGCbNV3SxvKs2MXNP(System.Threading.ThreadStart)
   at _ISiSTzGmXXpAqo3PzdxdVD1bClZ._CdxDiVDTWOWMdxOVeU2035FgbIK(System.String[])
 }
--------------
{ TimeGenerated = 5/29/2021 10:45:02 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1999085723610005733, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Pamela\AppData\Local\Temp\RDR2A66.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2AA6.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2AC6.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2B60.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2B81.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: f0a100c6-5c4d-4c95-9ebe-6b3354b8e0bd
Report Status: 268435456
Hashed bucket: ee3def5252484136fbbe2ddfbf5440e5
Cab Guid: 0 }## Logs
```
Paste crash between the triple backticks.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.
```

**Comment by Craluminum2413** [comment] 2021-07-07 23:03
Duplicate of #1111

**Closed** 2021-07-08 05:22 UTC
Labels: status: duplicate
