### ISSUE TITLE
Creating pit kiln causes an exception

### ISSUE THREAD

**Issue by Tarod7** [anegostudios/VintageStory-Issues#1125] opened 2021-07-08 15:54 UTC
**Game Version:** 15 rc2
**Platform:** Windows 
**Modded:** No 

### Description
crash when trying to create pit kiln

### How to reproduce
Tried to make a new pit kiln, started putting straw in and got kicked.

### Logs
snip From Server
```
8.7.2021 08:46:43 [Event] Player Tarod got removed. Reason: Threw an exception at the server
8.7.2021 08:46:43 [Error] System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityGroundStorage.OnTryCreateKiln()
   at Vintagestory.GameContent.BlockPitkiln.TryCreateKiln(IWorldAccessor world, IPlayer byPlayer, BlockPos pos)
   at Vintagestory.GameContent.ItemDryGrass.OnHeldInteractStart(ItemSlot itemslot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, Boolean firstEvent, EnumHandHandling& handHandling)
   at Vintagestory.Server.ServerSystemInventory.HandleHandInteraction(_LnOW0ETdL8hAZbmBds0s0rwStAAA packet, ConnectedClient client)
   at Vintagestory.Server.ServerMain.ProcessNetMessage(NetIncomingMessage msg, NetServer mainSocket)
8.7.2021 08:48:30 [Event] Mods and systems notified, now saving everything...
8.7.2021 08:48:30 [Event] Will do offthread savegamedata saving...
```

client log snip
```
8.7.2021 08:46:43 [Notification] Disconnected by the server (An action you (or your client) did caused an unhandled exception)
8.7.2021 08:46:43 [Notification] Destroying game session, waiting up to 200ms for client threads to exit
8.7.2021 08:46:43 [Notification] Found 16 base assets in category lang
```

**Comment by Craluminum2413** [comment] 2021-07-08 16:02
Can't reproduce on my side (1.15.0-rc.2) in just created world

https://user-images.githubusercontent.com/69315569/124954558-e1fc9680-e01e-11eb-8fc2-f05beafcc1c0.mp4

**Comment by copygirl** [comment] 2021-07-08 16:04
Does this happen with a specific item you're trying to fire? Did you reuse an existing pit kiln (hole)?

**Comment by Tarod7** [comment] 2021-07-08 16:13
It was an existing hole, but it was empty. I can fill in the holes and make new ones. I'll check.

**Comment by Tarod7** [comment] 2021-07-08 16:18
When I logged back in there was an invisible pit kiln I had to break. new kilns in new spots are firing now.

**Comment by copygirl** [comment] 2021-07-08 16:26
Might have been a broken pit kiln from #1111 then? I will leave this issue up for a bit so we can confirm but remove the critical tag.

**Comment by Tarod7** [comment] 2021-07-08 16:45
New pit kiln works as expected.

**Comment by copygirl** [comment] 2021-07-08 18:13
Yeah if anyone can confirm that this happens with the "broken" pit kilns, then I'll feel comfortable closing it.

**Comment by tyronx** [comment] 2021-07-09 08:14
Any chance this server is on an older version?

**Comment by Tarod7** [comment] 2021-07-09 15:19
Definitely rc2, but the kiln may have been created in rc1

**Comment by copygirl** [comment] 2021-07-09 15:48
So far no new reports. I'll close it until new ones come in?

**Closed by copygirl** 2021-07-09 15:48 UTC
Labels: department: code, status: incomplete
