### ISSUE TITLE
Handbook: Crashes upon opening page of modded soil that can be turned into farmland

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#1361] opened 2021-10-17 13:12 UTC
**Game Version:** 1.15.7  
**Platform:** Windows
**Modded:** Yes

### How to reproduce
(my mod as example)
1. Install this mod [SoilVar-v1.0.0.zip](https://github.com/anegostudios/VintageStory-Issues/files/7359930/SoilVar-v1.0.0.zip)
2. Load new world (1.15.7 is recommended)
3. Switch to creative gamemode
4. Open creative inventory, go to `Soil Var` tab
5. Search `medium` (for example)
6. Hover over any variant and press `H`
7. It crashed

### Expected behavior
It shouldn't crash if they can be turned into farmland

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.7 (Stable)10/17/2021 16:01:25: Critical error occurred
System.OverflowException: Value was either too large or too small for a UInt16.
   at System.Convert.ToUInt16(Int64 value)
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at Vintagestory.API.Datastructures.JsonObject.AsArray[T](T[] defaultValue)
   at Vintagestory.API.Common.CollectibleObject.GetHandbookInfo(ItemSlot inSlot, ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor)
   at Vintagestory.API.Client.GuiHandbookItemStackPage.GetPageText(ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor)
   at Vintagestory.GameContent.GuiDialogHandbook.initDetailGui()
   at Vintagestory.GameContent.GuiDialogHandbook.OpenDetailPageFor(String pageCode)
   at Vintagestory.GameContent.ModSystemHandbook.OnHelpHotkey(KeyCombination key)
   at _9EEHbWiFHCW1EjFhcpHAlBwdtXY._24WrHJAtZTDEUUNk4atnNTjWqdi(KeyEvent , IWorldAccessor , IPlayer , Boolean , Boolean , Boolean )
   at Vintagestory.Client.NoObf.ClientMain.OnKeyDown(KeyEvent args)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(Object sender, KeyboardKeyEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.NativeWindowBase.OnKeyDown(Key key, Boolean repeat)
   at OpenTK.Platform.Windows.WinGLNative.HandleKeyboard(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _LiN8p156auXcqjjOW5aVAZ0QkUc._fwMbTl3XHB2eqbxoLfc3FpMIE00(_CFodeVozKjT5VhVV66Wv4Bd7r3c , String[] )
   at _qBF2AKwdIhCkNZsjxBA24g20vlH._fwMbTl3XHB2eqbxoLfc3FpMIE00(ThreadStart )
```

**Comment by tyronx** [comment] 2021-11-03 13:25
i'm not able to reproduce this, the handbook page opens up just fin
![2021-11-03_15-24-19](https://user-images.githubusercontent.com/762006/140068144-84d3f3b9-6408-4a6d-9b5f-bfec91caef7b.jpg)
e

**Comment by Craluminum2413** [comment] 2021-11-03 13:29
Try to open any medium soil variant

**Comment by bluelightning32** [comment] 2022-02-24 05:04
I get a similar crash in multiplayer mode on my client when I hit 'h' while hovering over an andesite block to look it up in the manual.

The crash does not reproduce in single player. I've run the server for a couple months, and I've upgraded mods many many times. So I'm guessing that the block ids have been increasing as I keep upgrading mods. For example, this message appeared in the server console last time I started it up:
```
> 20:55:36 [Server Debug] BlockID Remapper: Begin                                                                                                                                                        
> 20:55:36 [Server Debug] Block IDs loaded from savegame.                                                                                                                                                
> 20:55:53 [Server Debug] Found 56687 block requiring remapping                                                                                                                                          
> 20:55:55 [Server Debug] Remapped 0 new blockids                                                                                                                                                        
20:55:55 [Server Debug] Remapped 56687 existing blockids                                                                                                                                                 
20:55:55 [Server Debug] Found 4467 missing blocks                                                                                                                                                        
20:55:55 [Server Debug] Added unknown block for 4467 blocks                                                                                                                                              
> 20:55:55 [Server Debug] Block IDs have been written to savegame                                                                                                                                        
20:55:55 [Server Debug] ItemID Remapper: Begin                                                                                                                                                           
20:55:55 [Server Debug] Item IDs loaded from savegame.                                                                                                                                                   
> 20:55:55 [Server Debug] Found 6270 Item requiring remapping                                                                                                                                            
> 20:55:55 [Server Debug] Remapped 1 new Itemids                                                                                                                                                         
20:55:55 [Server Debug] Found 511 missing Items                                                                                                                                                          
20:55:55 [Server Debug] Added unknown Item for 511 Items
20:55:55 [Server Debug] Added 1 new Items to the mapping
20:55:55 [Server Debug] Item IDs have been written to savegame
```

```
Game Version: v1.16.4-rc.2 (Unstable)
Loaded Mods: ancienttools@1.3.6, tonwexp@1.0.9, backpackpack@1.0.3, bettercrates@1.4.1, cavecontent@1.0.1, dragonflies@1.1.4, extrachests@1.5.2, fancydoors@1.1.0, instruments@1.1.2, moremetals@1.0.9, m
oreroads@1.4.3, necessaries@1.1.1, primitivesurvival@2.8.0, qptech@1.7.3, rope-bridges@1.1.0, spidersilk@1.2.1, stackables@2.0.5, temporalhack@1.1.2, locustmod@2.3.5, theneighbours@0.4.12, tradeomat@1.
6.0, viescraftmachines@1.6.0, game@1.16.4-rc.2, vshud@2.0.31, zeekea@1.6.0, alchemy@1.5.9, carrycapacity@0.6.4, farmlife@1.2.2, fromgoldencombs@1.3.6-rc.4, lichen@1.6.1, medievalexpansion@3.7.1, petai@
1.3.5, playercorpse@1.3.1, prospectorinfo@3.1.2, stonequarry@1.6.3, tpnet@1.5.1, usefulstuff@2.3.2, creative@1.16.4-rc.2, survival@1.16.4-rc.2, wildfarming@1.2.7, woodbarrels@1.0.1, workbenchexpansion@
1.4.1, xlib@0.6.8, xmelee@0.0.10, xrowboat@0.0.3, bullseye@2.2.4, cats@1.3.3, feverstonehorses@1.2.5, wildcraft@1.1.5, wolftaming@1.3.2, xskills@0.6.8
2/23/2022 8:50:52 PM: Critical error occurred
Newtonsoft.Json.JsonSerializationException: Error converting value 74519 to type 'System.UInt16'. Path '', line 37, position 9. ---> System.OverflowException: Value was either too large or too small fo
r a UInt16.
  at System.Convert.ThrowUInt16OverflowException () [0x00000] in <d57a575dd6be4193a54eb87783bbd39c>:0 
  at System.Convert.ToUInt16 (System.Int64 value) [0x00014] in <d57a575dd6be4193a54eb87783bbd39c>:0 
  at System.Int64.System.IConvertible.ToUInt16 (System.IFormatProvider provider) [0x00000] in <d57a575dd6be4193a54eb87783bbd39c>:0 
  at System.Convert.ChangeType (System.Object value, System.Type conversionType, System.IFormatProvider provider) [0x0010d] in <d57a575dd6be4193a54eb87783bbd39c>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType (Newtonsoft.Json.JsonReader reader, System.Object value, System.Globalization.CultureInfo culture, Newtonsoft.Json.Serializati
on.JsonContract contract, System.Type targetType) [0x000aa] in <5753133c467642479854e5d6c1dc2798>:0 
   --- End of inner exception stack trace ---
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType (Newtonsoft.Json.JsonReader reader, System.Object value, System.Globalization.CultureInfo culture, Newtonsoft.Json.Serializati
on.JsonContract contract, System.Type targetType) [0x000eb] in <5753133c467642479854e5d6c1dc2798>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newt
onsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingV
alue) [0x0009b] in <5753133c467642479854e5d6c1dc2798>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x000d9] in <5753133c467642479854e5d6c1dc2798>:0 
  at Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00053] in <5753133c467642479854e5d6c1dc2798>:0 
  at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <5753133c467642479854e5d6c1dc2798>:0 
  at Newtonsoft.Json.Linq.JToken.ToObject (System.Type objectType, Newtonsoft.Json.JsonSerializer jsonSerializer) [0x00012] in <5753133c467642479854e5d6c1dc2798>:0 
  at Newtonsoft.Json.Linq.JToken.ToObject[T] (Newtonsoft.Json.JsonSerializer jsonSerializer) [0x00000] in <5753133c467642479854e5d6c1dc2798>:0 
  at Vintagestory.API.Common.JsonUtil.ToObject[T] (Newtonsoft.Json.Linq.JToken token, System.String domain, Newtonsoft.Json.JsonSerializerSettings settings) [0x0002f] in <82505808782a41bfa02c9b22b9ae98ea>:0 
  at Vintagestory.API.Datastructures.JsonObject.AsArray[T] (T[] defaultValue, System.String defaultDomain) [0x0003b] in <82505808782a41bfa02c9b22b9ae98ea>:0 
  at Vintagestory.GameContent.CollectibleBehaviorHandbookTextAndExtraInfo.GetHandbookInfo (Vintagestory.API.Common.ItemSlot inSlot, Vintagestory.API.Client.ICoreClientAPI capi, Vintagestory.API.Common.ItemStack[] allStacks, Vintagestory.API.Common.ActionConsumable`1[T] openDetailPageFor) [0x0071f] in <07ca31cd19094ef9b89023ba9a856d24>:0 
  at Vintagestory.GameContent.GuiHandbookItemStackPage.GetPageText (Vintagestory.API.Client.ICoreClientAPI capi, Vintagestory.API.Common.ItemStack[] allStacks, Vintagestory.API.Common.ActionConsumable`1[T] openDetailPageFor) [0x00014] in <07ca31cd19094ef9b89023ba9a856d24>:0 
  at Vintagestory.GameContent.GuiDialogHandbook.initDetailGui () [0x002ac] in <07ca31cd19094ef9b89023ba9a856d24>:0 
  at Vintagestory.GameContent.GuiDialogHandbook.OpenDetailPageFor (System.String pageCode) [0x0007d] in <07ca31cd19094ef9b89023ba9a856d24>:0 
  at Vintagestory.GameContent.ModSystemHandbook.OnHelpHotkey (Vintagestory.API.Client.KeyCombination key) [0x00085] in <07ca31cd19094ef9b89023ba9a856d24>:0 
  at _1PmdfurhDdeMHGekmkRuNd4nIc0._jddJChKaayopEm6it0zkDgwZlNj (Vintagestory.API.Client.KeyEvent , Vintagestory.API.Common.IWorldAccessor , Vintagestory.API.Common.IPlayer , System.Boolean , System.Boolean , System.Boolean ) [0x0009b] in <3aa4f8920680447d8df075ec4b7a22be>:0 
  at _1PmdfurhDdeMHGekmkRuNd4nIc0._jddJChKaayopEm6it0zkDgwZlNj (Vintagestory.API.Client.KeyEvent , Vintagestory.API.Common.IWorldAccessor , Vintagestory.API.Common.IPlayer , System.Boolean ) [0x0000a] in <3aa4f8920680447d8df075ec4b7a22be>:0 
  at Vintagestory.Client.NoObf.ClientMain.OnKeyDown (Vintagestory.API.Client.KeyEvent args) [0x000ba] in <3aa4f8920680447d8df075ec4b7a22be>:0 
  at _25hCbD9BEFkP69yUQhdpPQgkOvd._Uvp5FOw11TxIDfAgBJRHWOqQQ2N (Vintagestory.API.Client.KeyEvent ) [0x00000] in <3aa4f8920680447d8df075ec4b7a22be>:0 
  at _bjnBWlJotnHiR69aw1flHb4F023._Uvp5FOw11TxIDfAgBJRHWOqQQ2N (Vintagestory.API.Client.KeyEvent ) [0x0006e] in <3aa4f8920680447d8df075ec4b7a22be>:0 
  at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown (System.Object sender, OpenTK.Input.KeyboardKeyEventArgs e) [0x00082] in <3aa4f8920680447d8df075ec4b7a22be>:0 
  at (wrapper delegate-invoke) System.EventHandler`1[OpenTK.Input.KeyboardKeyEventArgs].invoke_void_object_TEventArgs(object,OpenTK.Input.KeyboardKeyEventArgs)
  at OpenTK.NativeWindow.OnKeyDown (OpenTK.Input.KeyboardKeyEventArgs e) [0x00000] in <a4886e33f9fc416195d24950e7205b94>:0 
  at OpenTK.NativeWindow.OnKeyDownInternal (System.Object sender, OpenTK.Input.KeyboardKeyEventArgs e) [0x00000] in <a4886e33f9fc416195d24950e7205b94>:0 
  at (wrapper delegate-invoke) System.EventHandler`1[OpenTK.Input.KeyboardKeyEventArgs].invoke_void_object_TEventArgs(object,OpenTK.Input.KeyboardKeyEventArgs)
  at OpenTK.Platform.NativeWindowBase.OnKeyDown (OpenTK.Input.Key key, System.Boolean repeat) [0x0002e] in <a4886e33f9fc416195d24950e7205b94>:0 
  at OpenTK.Platform.X11.X11GLNative.ProcessEvents () [0x00713] in <a4886e33f9fc416195d24950e7205b94>:0 
  at OpenTK.NativeWindow.ProcessEvents (System.Boolean retainEvents) [0x00035] in <a4886e33f9fc416195d24950e7205b94>:0 
  at OpenTK.NativeWindow.ProcessEvents () [0x00000] in <a4886e33f9fc416195d24950e7205b94>:0 
  at OpenTK.GameWindow.Run (System.Double updates_per_second, System.Double frames_per_second) [0x000da] in <a4886e33f9fc416195d24950e7205b94>:0 
  at OpenTK.GameWindow.Run () [0x00000] in <a4886e33f9fc416195d24950e7205b94>:0 
  at _As7FGAmUC8gaKIkRNk2zuk1jlJ._zleiWFUbDyAE8J9zHf00bJUUlQr (_M5s9po0jOCy75F2Bz2DU6XdfcDb , System.String[] ) [0x003dc] in <a6fcb5500db24417b1b0ac0664952eaa>:0 
  at _As7FGAmUC8gaKIkRNk2zuk1jlJ+_8zD9tDpTxnmzNOt6Q8wk9rsM5Nc._Xcm5hKwLxeFBfvT7REtBOs1k9iq () [0x00000] in <a6fcb5500db24417b1b0ac0664952eaa>:0 
  at _f8y3Fmmhb3dxIjBj0LM71AeVhBG._zleiWFUbDyAE8J9zHf00bJUUlQr (System.Threading.ThreadStart ) [0x00007] in <3aa4f8920680447d8df075ec4b7a22be>:0 
-------------------------------
System.OverflowException: Value was either too large or too small for a UInt16.
  at System.Convert.ThrowUInt16OverflowException () [0x00000] in <d57a575dd6be4193a54eb87783bbd39c>:0 
  at System.Convert.ToUInt16 (System.Int64 value) [0x00014] in <d57a575dd6be4193a54eb87783bbd39c>:0 
  at System.Int64.System.IConvertible.ToUInt16 (System.IFormatProvider provider) [0x00000] in <d57a575dd6be4193a54eb87783bbd39c>:0 
  at System.Convert.ChangeType (System.Object value, System.Type conversionType, System.IFormatProvider provider) [0x0010d] in <d57a575dd6be4193a54eb87783bbd39c>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType (Newtonsoft.Json.JsonReader reader, System.Object value, System.Globalization.CultureInfo culture, Newtonsoft.Json.Serialization.JsonContract contract, System.Type targetType) [0x000aa] in <5753133c467642479854e5d6c1dc2798>:0 
-------------------------------
```

**Comment by tyronx** [comment] 2022-02-24 06:04
Ok found it, will be fixed next release, thanks for the report!

**Closed by tyronx** 2022-02-24 06:04 UTC
Labels: target: modding, status: new
