### ISSUE TITLE
Smithing not working 

### ISSUE THREAD

**Issue by tmstbsjms** [anegostudios/VintageStory-Issues#3616] opened 2024-02-21 17:41 UTC
### Game Version

v1.19.4-rc.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When smithing hammering does nothing I used a bronze hammer on a bronze anvil attempting to make a copper plate changing work pieces does nothing reheating does nothing. Restarting game and computer does nothing to fix this issue.

### How to reproduce

I think to reproduce this bug you'd just need to smith.

### Screenshots

A picture would just be me hitting metal and nothing happening so it wouldn't help.

### Logs

```Log``` Unable to locate.

**Comment by Craluminum2413** [comment] 2024-02-21 17:48
Duplicate of #3593

**Closed by Craluminum2413** 2024-02-21 17:48 UTC
Labels: status: new
