### ISSUE TITLE
Unable to update to the newest version (1.18.10)

### ISSUE THREAD

**Issue by Zelger98** [anegostudios/VintageStory-Issues#3093] opened 2023-09-12 13:31 UTC
### Game Version

1.18.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

None

### Description

When clicking the Update install button at the top left of the main menu the installation starts. After downloading about 98% of the update, it stops and displays an error message found bellow. I was updating from 1.18.8 - 1.18.10

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/126715524/1d4d0977-26cb-4bcc-8b06-f3698f12b046)

![image](https://github.com/anegostudios/VintageStory-Issues/assets/126715524/c3ce9553-0d7e-452c-b452-f5f29e07adad)

### Logs

```Log```

**Comment by Th3Dilli** [comment] 2023-09-12 17:11
Duplicate of #3078

**Closed by Th3Dilli** 2023-09-12 17:11 UTC
Labels: status: new
