### ISSUE TITLE
v1.17.0-pre.5 crash when adding hides to limewater

### ISSUE THREAD

**Issue by Kagesh** [anegostudios/VintageStory-Issues#2033] opened 2022-07-21 15:09 UTC
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.0-pre.5 (Unstable)
Loaded Mods: game@1.17.0-pre.5, creative@1.17.0-pre.5, survival@1.17.0-pre.5
7/21/2022 10:05:28 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockBarrel.getContentMesh(ItemStack stack, BlockPos forBlockPos, String shapefilename) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Barrel\BlockBarrel.cs:line 208
   at Vintagestory.GameContent.BlockBarrel.GenMesh(ItemStack contentStack, ItemStack liquidContentStack, Boolean issealed, BlockPos forBlockPos) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Barrel\BlockBarrel.cs:line 152
   at Vintagestory.GameContent.BlockEntityBarrel.GenMesh() in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Barrel\BEBarrel.cs:line 320
   at Vintagestory.GameContent.BlockEntityBarrel.Inventory_SlotModified(Int32 slotId) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Barrel\BEBarrel.cs:line 110
   at Vintagestory.API.Common.InventoryBase.DidModifyItemSlot(ItemSlot slot, ItemStack extractedStack) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Common\Inventory\InventoryBase.cs:line 480
   at Vintagestory.API.Common.ItemSlot.OnItemSlotModified(ItemStack sinkStack) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Common\Inventory\ItemSlot.cs:line 418
   at Vintagestory.API.Common.ItemSlotBarrelInput.OnItemSlotModified(ItemStack stack) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Inventory\ItemSlotBarrelInput.cs:line 26
   at Vintagestory.API.Common.ItemSlot.ActivateSlotRightClick(ItemSlot sourceSlot, ItemStackMoveOperation& op) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Common\Inventory\ItemSlot.cs:line 387
   at Vintagestory.API.Common.InventoryBase.ActivateSlot(Int32 slotId, ItemSlot sourceSlot, ItemStackMoveOperation& op) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Common\Inventory\InventoryBase.cs:line 448
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.SlotClick(ICoreClientAPI api, Int32 slotId, EnumMouseButton mouseButton, Boolean shiftPressed, Boolean ctrlPressed, Boolean altPressed) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 979
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseDownOnElement(ICoreClientAPI api, MouseEvent args) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 772
   at Vintagestory.API.Client.GuiElement.OnMouseDown(ICoreClientAPI api, MouseEvent mouse) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\GuiElement.cs:line 638
   at Vintagestory.API.Client.GuiComposer.OnMouseDown(MouseEvent mouseArgs) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\GuiComposer.cs:line 440
   at Vintagestory.API.Client.GuiDialog.OnMouseDown(MouseEvent args) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 536
   at Vintagestory.Client.NoObf.GuiManager.OnMouseDown(MouseEvent args) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 394
   at Vintagestory.Client.NoObf.ClientMain.OnMouseDown(MouseEvent args) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:line 2248
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonDown(Object sender, MouseButtonEventArgs e) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\Input.cs:line 220
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 800
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1554
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 368
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 87
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 7/20/2022 10:43:19 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2141744315486943026, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.0.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Mark\AppData\Local\Temp\RDR799B.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7A29.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7A49.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7A54.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7A93.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 9d7e8d8a-00d1-4cf1-b736-4f14babed3bf
Report Status: 268435456
Hashed bucket: 5ba4867f167f40b4adb9011b844fb732
Cab Guid: 0 }
--------------
{ TimeGenerated = 6/20/2022 10:42:14 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2141744315486943026, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.0.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Mark\AppData\Local\Temp\RDR97B4.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9842.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9872.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9880.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER98BF.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 512daf53-f158-44cb-80d3-fb23a4e8b78d
Report Status: 268435456
Hashed bucket: 5ba4867f167f40b4adb9011b844fb732
Cab Guid: 0 }
--------------
{ TimeGenerated = 5/21/2022 10:37:33 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1169322480264892805, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.5.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Mark\AppData\Local\Temp\RDR9ABD.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9B3B.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9B5B.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9B68.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9BA8.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 0f3a6786-9524-4eb9-94d3-06d87f997389
Report Status: 268435456
Hashed bucket: 66b2146b18168122903a4499b8115185
Cab Guid: 0 }

**Comment by Craluminum2413** [comment] 2022-07-21 15:16
Duplicate of #2021

**Closed by Craluminum2413** 2022-07-21 15:16 UTC
Labels: status: new
