### ISSUE TITLE
Recurring Issue with Hay Blocks

### ISSUE THREAD

**Issue by ruggbean** [anegostudios/VintageStory-Issues#2154] opened 2022-09-02 16:43 UTC
**Game Version:** 1.17.1 - 1.17.2 
**Platform:** Windows
**Modded:** Yes (Carry Capacity, Zoom Button, Step Up, More Candles)
**SP/MP:** Multiplayer

### Description
Since 1.17.0 dropped, my hay blocks have all turned to ? asset cubes. The roof in the screenshot below are chiseled hay blocks.

### How to reproduce
The only way that I know to reproduce the issue is to move up or down in versions for any of 1.17. Once I replace or rechisel the hay blocks, the issue seems to be mitigated, even when I log out and log back in.

This issue has been noted by [NyxBSomethin](https://github.com/anegostudios/VintageStory-Issues/issues/2072) as well.

### Expected behavior
I expected my hay/hay roofs to be intact, especially since this doesn't seem to affect thatch or any other grass based items (that I am aware of)

### Screenshots
![2022-09-02_09-26-45](https://user-images.githubusercontent.com/109896152/188197774-48b9e9c3-f250-4cd2-a36f-1f874b038b76.png)

## Video
[1.17.1](https://www.youtube.com/watch?v=RqX8Jq_WDBI)
[1.17.2](https://www.youtube.com/watch?v=e0mhwVLQnXc)

### Logs
Not sure if these would be of any help regarding the issue, but here is a [Gist](https://gist.github.com/ruggbean/ff1c79bc219b0b78f8430f8bd8db2d91) of my client-main and server-main txt logs

**Comment by Craluminum2413** [comment] 2022-09-02 16:44
Duplicate of #2072

**Closed by Craluminum2413** 2022-09-02 16:44 UTC
Labels: status: duplicate
