### ISSUE TITLE
Crash: After updating to 1.15.7, looking at rock with chalk drawings crashes the client

### ISSUE THREAD

**Issue by AiraPlaysGames** [anegostudios/VintageStory-Issues#1389] opened 2021-10-29 13:14 UTC
**Game Version:** 1.15.7
**Platform:** Windows 10
**Modded:** No

### Description
After updating my server to 1.15.7 from 1.15.5, every time I look at rock blocks with chalk drawings on them (which were drawn in 1.15.5), the client crashes.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.7 (Stable)29-Oct-21 15:11:13: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.Block.GetPlacedBlockInfo(IWorldAccessor world, BlockPos pos, IPlayer forPlayer)
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.ComposeBlockInfoHud()
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.BlockInView()
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _gt983m53spH3zIRFvTrVgBj5MUb._m2KVBUzhniiatiiNT9yOoXoOOvL(Single )
   at _2hFm1B1DwOk1Z7yF6DtBdLeBFKaA._5soGXezAcR5oyhhq2pmELCuEn2M(Single )
   at _2hFm1B1DwOk1Z7yF6DtBdLeBFKaA._ZzmaNk5IGbtvQ61ssCzCszyBw2n(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _LiN8p156auXcqjjOW5aVAZ0QkUc._fwMbTl3XHB2eqbxoLfc3FpMIE00(_CFodeVozKjT5VhVV66Wv4Bd7r3c , String[] )
   at _qBF2AKwdIhCkNZsjxBA24g20vlH._fwMbTl3XHB2eqbxoLfc3FpMIE00(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 28-Oct-21 19:51:56, Site = , Source = Windows Error Reporting, Message = Fault bucket 1775098558742058606, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.5.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\SECRET~1\AppData\Local\Temp\RDR6565.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6566.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6576.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER65DF.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER661E.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 0a6890fa-b5ed-4759-a6cb-868dcd857b32
Report Status: 268435456
Hashed bucket: d490f7f3f456e29178a26abbfb20d66e
Cab Guid: 0 }
--------------
{ TimeGenerated = 23-Sep-21 17:12:30, Site = , Source = Windows Error Reporting, Message = Fault bucket 1775098558742058606, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.5.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\SECRET~1\AppData\Local\Temp\RDR9181.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9182.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER91A3.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER91C6.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER91F6.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 12043206-0aea-4e4c-b8ae-28793369e54c
Report Status: 268435456
Hashed bucket: d490f7f3f456e29178a26abbfb20d66e
Cab Guid: 0 }
--------------
{ TimeGenerated = 24-Aug-21 13:08:10, Site = , Source = Windows Error Reporting, Message = Fault bucket 1775098558742058606, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.5.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\SECRET~1\AppData\Local\Temp\RDRCE85.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCEA5.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCEB6.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCF40.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCF70.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: fbabe944-70fc-44a9-adbd-35684cd3e86f
Report Status: 268435456
Hashed bucket: d490f7f3f456e29178a26abbfb20d66e
Cab Guid: 0 }
```

**Comment by copygirl** [comment] 2021-10-30 18:43
Similar issue to #1385, which the player was able to fix by turning off the block info overlay and destroying the offending block.

**Comment by tyronx** [comment] 2021-11-03 11:31
Not able to reproduce this in a creative world, unfortunately

**Comment by tyronx** [comment] 2021-11-03 11:31
I'd need the crashing world for testing then

**Comment by AiraPlaysGames** [comment] 2021-11-05 10:54
Unfortunately I can't provide the world save. It was the Halloween event world, actually, and I solved it by using the world edit tools to delete the entire area with chalk drawings without looking at them. I don't have a backup from before then.

**Comment by tyronx** [comment] 2021-11-05 12:49
Okay, I'll close this issue for now then, until the next person comes across the same bug.

**Closed by tyronx** 2021-11-05 12:49 UTC
Labels: status: incomplete, priority: high
