### ISSUE TITLE
Order of ingredients in a recipe

### ISSUE THREAD

**Issue by Saricane** [anegostudios/VintageStory-Issues#1185] opened 2021-07-17 18:14 UTC
**Game Version:** 1.15.1
**Platform:** Windows 
**Modded:** No

### Description
I often cook several full pots of the same recipe, just to have a perfect filling of the crocks. Because a crock will receive the last 2 meals from the first pot, then the first two meals of the second pot.
But unfortunately, I must also put the ingredients in the pot in the same precise order.
I made 2 pots of porridge + 2 fruits. In the first pot, I put the grain then the fruits, and in the second pot, I put the fruits then the grain. In both case, the result is the same, labelled "Flax porridge with mashed redcurrants". But it is impossible to mix the two meals in the same crock.

### Expected behavior
When mixing meals in a crock, the game should only check if the recipe is the same, and not the order in which ingredients have been put in the cooking pot.

### Screenshots
![2021-07-17_19-48-49](https://user-images.githubusercontent.com/84909583/126046111-46dfa71f-b9af-49e9-8096-350e0d4343ec.png)

**Comment by Craluminum2413** [comment] 2021-07-17 18:18
I sure it's duplicate of #1036

**Comment by Saricane** [comment] 2021-07-17 18:25
Yes and ... no  :-)
In your report, despite the fact it is of course the same resulting meal, we can read that the names are differents. Ok, I agree with you, this should be the same name.
And in my report, the meal name is exactly the same, but the problem is this check on the ingredients order.

Actually, the 2 reports are closely linked, because in both cases, we cannot fill correctly the crocks.

**Comment by Craluminum2413** [comment] 2021-07-17 18:28
Read the first line of my report

**Comment by Craluminum2413** [comment] 2021-07-17 18:31
Maybe I need to concretize and write that I mean sort them alphabetically right in the code

**Comment by copygirl** [comment] 2021-07-17 19:32
I'll close this as a duplicate, as I think I understood the intention of @Craluminum2413's issue as covering this issue.

**Closed by copygirl** 2021-07-17 19:32 UTC
Labels: status: duplicate
