### ISSUE TITLE
Crash to desktop

### ISSUE THREAD

**Issue by WickedSchnitzel** [anegostudios/VintageStory-Issues#4448] opened 2024-11-05 21:20 UTC
### Game Version

1.20.0-pre.10

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Crashed without doing anything special

### Logs

5.11.2024 22:17:53 [Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.Server.PhysicsManager.DoWork() in VintagestoryLib\Server\PhysicsManager.cs:line 523
   at Vintagestory.Common.LoadBalancer.SynchroniseWorkToMainThread() in VintagestoryLib\Common\LoadBalancer.cs:line 81
   at Vintagestory.Server.PhysicsManager.TickFixedRate30TPS() in VintagestoryLib\Server\PhysicsManager.cs:line 298
   at Vintagestory.Server.PhysicsManager.ServerTick(Single dt) in VintagestoryLib\Server\PhysicsManager.cs:line 100
   at Vintagestory.Common.GameTickListener.OnTriggered(Int64 ellapsedMilliseconds) in VintagestoryLib\Common\Model\GameTickListener.cs:line 27
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 57
   at Vintagestory.Server.ServerMain.Process() in VintagestoryLib\Server\ServerMain.cs:line 904

**Comment by Craluminum2413** [comment] 2024-11-05 21:35
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4328

**Closed by Craluminum2413** 2024-11-05 21:35 UTC
Labels: status: new
