### ISSUE TITLE
Game crash sometimes when harvesting  fired objects in a kiln

### ISSUE THREAD

**Issue by dann1kid** [anegostudios/VintageStory-Issues#1423] opened 2021-11-21 21:37 UTC
**Game Version:** 1.15.9
**Platform:** Windows 
**Modded:**  Yes
**SP/MP:** Multiplayer 

### Description
Sometimes  crashes on interact with fired stack mug items 

### How to reproduce
1. Make a thing stack in the kiln (bricks etc)
2. Wait until its will be fired
3. It doesn't collects. Harvests only by destroy stack

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.9 (Stable)11/21/2021 11:21:07 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
at Vintagestory.GameContent.BlockGroundStorage.GetPlacedBlockInteractionHelp(IWorldAccessor world, BlockSelection selection, IPlayer forPlayer)
   at Vintagestory.Client.NoObf.HudElementBlockInteractionHelp.OnBlockChanged(BlockPos pos, Block oldBlock)
   at Vintagestory.API.Client.BlockChangedDelegate.Invoke(BlockPos pos, Block oldBlock)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerBlockChanged(ClientMain game, BlockPos pos, Block oldBlock)
   at Vintagestory.Client.NoObf.ClientWorldMap.MarkBlockDirty(BlockPos pos, IPlayer skipPlayer)
   at Vintagestory.GameContent.BlockEntityGroundStorage.OnPlayerInteract(IPlayer player, BlockSelection bs)
   at Vintagestory.GameContent.BlockGroundStorage.OnBlockInteractStart_Patch1(BlockGroundStorage this, IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Block selectedBlock, BlockSelection blockSelection)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _rnlVSzJ2AGPu2719D3re8Z7kN2c._TshCCJvNc6laaisiRTK6RNaXWQ1A(Single )
   at _o0lbNJXQO06me4d8j661Kh7y0zO._HmSBpw6fP4XFLEcv29tc0ifOKYvb(Single )
   at _o0lbNJXQO06me4d8j661Kh7y0zO._3U99eoPu0PaDLPVrL8tfzH5UDEJ(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _M48MnHH5BAvHUzcYoEuchRW0acb._e0atQ8VmmvgBK7zb3Yh4iDqOiHY(_UGHNIsOGTJBe1BTRXYmLwHTbmS , String[] )
   at _xNqQDGqRsRSMIeuzt2MHKQHDzSd._e0atQ8VmmvgBK7zb3Yh4iDqOiHY(ThreadStart )
```

**Comment by copygirl** [comment] 2021-11-21 23:44
Duplicate of #1422. Thanks for reporting, however!

**Closed by copygirl** 2021-11-21 23:44 UTC
Labels: status: duplicate
