### ISSUE TITLE
World wont load

### ISSUE THREAD

**Issue by pastelmangoo** [anegostudios/VintageStory-Issues#1563] opened 2022-01-11 00:34 UTC
Running on 64 bit Windows with 16 GB RAM 
Version: v1.16.0 (Stable)1/10/2022 6:32:12 PM: Critical error occurred
System.MissingMethodException: Method not found: '!!0[] Vintagestory.API.Datastructures.JsonObject.AsArray(!!0[])'.
   at CarryCapacity.Common.BlockBehaviorCarryable.TryGetVec3f(JsonObject json, String key, Vec3f& result)
   at CarryCapacity.Common.BlockBehaviorCarryable.GetTransform(JsonObject json, ModelTransform baseTransform)
   at CarryCapacity.Common.BlockBehaviorCarryable.Initialize(JsonObject properties)
   at Vintagestory.Common.BlockTypeNet.ReadBlockTypePacket(_1AeMKIMs7c00tz8Moxn97h5y1Ac packet, IWorldAccessor world, ClassRegistry registry)
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerAssetsStep1()
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleLightLevels(_hpqb4cNQuSfxZLdFacKLPiYYWAN packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _0dbBCVS4kT4NsuDZA84yDu7r3AG._1NlBQQ8qS5idQptIBQaAbARuOfxA(Single )
   at _vFhcDU5n6Z0hUte90jdaxlrDjR5._HuDdfzha8ZKZvU2y0RbH58r7VzR(Single )
   at _vFhcDU5n6Z0hUte90jdaxlrDjR5._XZOFA2JA54yZjH15yys9W7vL9hj(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _FKpOpQGqqf3cJWdQyWh1ysxsDBb._pYad7oBcQ5qtzQkYGDu4NFHQxhK(_5x3PJgrln4IBXPDNSNN0fecxKFb , String[] )
   at _sejP0Tcz8wTg70ptIdRr3CwQmrE._pYad7oBcQ5qtzQkYGDu4NFHQxhK(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 1/10/2022 6:30:29 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1626999641440620011, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.0.0
P3: 61dc5145
P4: KERNELBASE.dll
P5: 10.0.19041.1387
P6: 0b9a844a
P7: c000041d
P8: 0000000000034f69
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA479.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA71A.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA72B.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA73B.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA75B.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_1bf1956df8fd555bc61dcaccc5b8c1baf6252643_d5c93aa4_498cae05-a77f-418a-bcc1-c4381ba12d85

Analysis symbol: 
Rechecking for solution: 0
Report Id: 99684bc6-81a3-49a2-be35-a0598baeb35a
Report Status: 268435456
Hashed bucket: 643e109a2a36980c3694438dbdc18deb
Cab Guid: 0 }
--------------
{ TimeGenerated = 1/10/2022 6:30:28 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.16.0.0, time stamp: 0x61dc5145
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1387, time stamp: 0x0b9a844a
Exception code: 0xc000041d
Fault offset: 0x0000000000034f69
Faulting process id: 0x3f8c
Faulting application start time: 0x01d806825cdc6d6e
Faulting application path: C:\Users\Rose\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 99684bc6-81a3-49a2-be35-a0598baeb35a
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 1/10/2022 6:30:27 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1153965391760653583, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.0.0
P3: 61dc5145
P4: KERNELBASE.dll
P5: 10.0.19041.1387
P6: 0b9a844a
P7: c0020001
P8: 0000000000034f69
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER975A.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9A39.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9A5A.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9A58.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9A78.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_469a979013df393c23d0ec7e3feee9b17f6c29_d5c93aa4_babb4536-5ebe-431c-b335-de5c91a3265d

Analysis symbol: 
Rechecking for solution: 0
Report Id: 4c1baa26-d92c-4e98-975a-b3f387e423a7
Report Status: 268435456
Hashed bucket: 2fc88a1327eaf8efd003b568eafcfd0f
Cab Guid: 0 }

**Comment by Craluminum2413** [comment] 2022-01-11 00:36
The problem is in Carry Capacity mod

**Comment by YouariE** [comment] 2022-01-11 01:04
maby i have that same error, but whif a other mod?

System.TypeLoadException: Der Typ "Vintagestory.API.Common.Action`1" in der Assembly "VintagestoryAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" konnte nicht geladen werden.
   bei VolumetricShading.Events.EmitPreFinalRender(ShaderProgramFinal final)
   bei VolumetricShading.PlatformPatches.FinalCallsite(ShaderProgramFinal final)
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.RenderFinalComposition_Patch0(ClientPlatformWindows this)
   bei _vFhcDU5n6Z0hUte90jdaxlrDjR5._HuDdfzha8ZKZvU2y0RbH58r7VzR(Single )
   bei _vFhcDU5n6Z0hUte90jdaxlrDjR5._XZOFA2JA54yZjH15yys9W7vL9hj(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 479.
   bei OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 454.
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 375.
   bei _FKpOpQGqqf3cJWdQyWh1ysxsDBb._pYad7oBcQ5qtzQkYGDu4NFHQxhK(_5x3PJgrln4IBXPDNSNN0fecxKFb , String[] )
   bei _sejP0Tcz8wTg70ptIdRr3CwQmrE._pYad7oBcQ5qtzQkYGDu4NFHQxhK(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 11.01.2022 01:54:15, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.16.0.0, Zeitstempel: 0x61dc5145
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.1387, Zeitstempel: 0x0b9a844a
Ausnahmecode: 0xc000041d
Fehleroffset: 0x0000000000034f69
ID des fehlerhaften Prozesses: 0x2570
Startzeit der fehlerhaften Anwendung: 0x01d8066f5fc3cc49
Pfad der fehlerhaften Anwendung: C:\Users\lukas\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\KERNELBASE.dll
Berichtskennung: 851c153b-497b-420c-9811-b0fc7219a744
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 11.01.2022 01:54:12, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.16.0.0, Zeitstempel: 0x61dc5145
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.1387, Zeitstempel: 0x0b9a844a
Ausnahmecode: 0xc0020001
Fehleroffset: 0x0000000000034f69
ID des fehlerhaften Prozesses: 0x2570
Startzeit der fehlerhaften Anwendung: 0x01d8066f5fc3cc49
Pfad der fehlerhaften Anwendung: C:\Users\lukas\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\KERNELBASE.dll
Berichtskennung: acbeadcd-8b19-4777-ab6f-48a13fb4b65e
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 11.01.2022 01:54:12, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: Ausnahmecode c0020001, Ausnahmeadresse 00007FFD60314F69
Stapel:
 }

**Comment by Craluminum2413** [comment] 2022-01-11 01:07
> maby i have that same error, but whif a other mod?
> 
> ## System.TypeLoadException: Der Typ "Vintagestory.API.Common.Action`1" in der Assembly "VintagestoryAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" konnte nicht geladen werden. bei VolumetricShading.Events.EmitPreFinalRender(ShaderProgramFinal final) bei VolumetricShading.PlatformPatches.FinalCallsite(ShaderProgramFinal final) bei Vintagestory.Client.NoObf.ClientPlatformWindows.RenderFinalComposition_Patch0(ClientPlatformWindows this) bei _vFhcDU5n6Z0hUte90jdaxlrDjR5._HuDdfzha8ZKZvU2y0RbH58r7VzR(Single ) bei _vFhcDU5n6Z0hUte90jdaxlrDjR5._XZOFA2JA54yZjH15yys9W7vL9hj(Single ) bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
> bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 479.
> bei OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 454.
> bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 375.
> bei _FKpOpQGqqf3cJWdQyWh1ysxsDBb._pYad7oBcQ5qtzQkYGDu4NFHQxhK(_5x3PJgrln4IBXPDNSNN0fecxKFb , String[] )
> bei _sejP0Tcz8wTg70ptIdRr3CwQmrE._pYad7oBcQ5qtzQkYGDu4NFHQxhK(ThreadStart )
> # Event Log entries containing Vintagestory.exe, the latest 3
> ## { TimeGenerated = 11.01.2022 01:54:15, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.16.0.0, Zeitstempel: 0x61dc5145
> Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.1387, Zeitstempel: 0x0b9a844a
> Ausnahmecode: 0xc000041d
> Fehleroffset: 0x0000000000034f69
> ID des fehlerhaften Prozesses: 0x2570
> Startzeit der fehlerhaften Anwendung: 0x01d8066f5fc3cc49
> Pfad der fehlerhaften Anwendung: C:\Users\lukas\AppData\Roaming\Vintagestory\Vintagestory.exe
> Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\KERNELBASE.dll
> Berichtskennung: 851c153b-497b-420c-9811-b0fc7219a744
> Vollständiger Name des fehlerhaften Pakets:
> Anwendungs-ID, die relativ zum fehlerhaften Paket ist: }
> ## { TimeGenerated = 11.01.2022 01:54:12, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.16.0.0, Zeitstempel: 0x61dc5145
> Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.1387, Zeitstempel: 0x0b9a844a
> Ausnahmecode: 0xc0020001
> Fehleroffset: 0x0000000000034f69
> ID des fehlerhaften Prozesses: 0x2570
> Startzeit der fehlerhaften Anwendung: 0x01d8066f5fc3cc49
> Pfad der fehlerhaften Anwendung: C:\Users\lukas\AppData\Roaming\Vintagestory\Vintagestory.exe
> Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\KERNELBASE.dll
> Berichtskennung: acbeadcd-8b19-4777-ab6f-48a13fb4b65e
> Vollständiger Name des fehlerhaften Pakets:
> Anwendungs-ID, die relativ zum fehlerhaften Paket ist: }
> { TimeGenerated = 11.01.2022 01:54:12, Site = , Source = .NET Runtime, Message = Anwendung: Vintagestory.exe Frameworkversion: v4.0.30319 Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet. Ausnahmeinformationen: Ausnahmecode c0020001, Ausnahmeadresse 00007FFD60314F69 Stapel: }

There is a problem in VSHUD

**Comment by copygirl** [comment] 2022-01-11 07:52
Due to changes in the game, CarryCapacity had to update for version 1.16. The latest version of the mod (v0.6.4) should work. The same may be true for other mods. See their mod pages or forum posts if new versions have been released, or as their authors for help.

Since this is mod-related, I'm going to close this issue.

**Closed by copygirl** 2022-01-11 07:52 UTC
Labels: status: invalid
