### ISSUE TITLE
Invinsible mobs and playes

### ISSUE THREAD

**Issue by dedmayo** [anegostudios/VintageStory-Issues#2330] opened 2022-12-27 11:06 UTC
### Game Version

1.17.9

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

After i updated vintage story from version 1.17.3 to version 1.17.9 i cant see any creatures or players

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2022-12-27 14:07
Duplicate of #2277

**Closed by Craluminum2413** 2022-12-27 14:07 UTC
Labels: status: new
