### ISSUE TITLE
Mantle does not provide stability to rock above

### ISSUE THREAD

**Issue by Gorfinhofin** [anegostudios/VintageStory-Issues#3516] opened 2024-01-26 05:31 UTC
### Game Version

v1.19.2

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Rock blocks on top of the mantle are considered unsupported and have 100% instability. They can collapse if mined, and will animate and play the sound briefly before settling into place on top of the mantle again.

### How to reproduce

Dig down to mantle, check instability levels of rock.

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2024-11-06 15:19
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/3567

**Comment by Craluminum2413** [comment] 2024-11-06 15:19
Closed in favor of newer issue

**Closed by Craluminum2413** 2024-11-06 15:19 UTC
Labels: status: new, version: 1.19
