### ISSUE TITLE
Gaps Between Blocks

### ISSUE THREAD

**Issue by Desoroxxx** [anegostudios/VintageStory-Issues#3899] opened 2024-05-31 22:23 UTC
### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

As the tittle says when I move the camera around there sometime is the void showing up as a pixel or two between blocks.

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/82710983/20bcfda8-e159-483b-bb22-920f2106d1e6)

**Comment by Craluminum2413** [comment] 2024-06-01 09:46
Duplicate of #2401

**Closed by Craluminum2413** 2024-06-01 09:46 UTC
Labels: status: new
