### ISSUE TITLE
Unable to play the multiplayer because respawn button disconnects from the server

### ISSUE THREAD

**Issue by mikola-rollun** [anegostudios/VintageStory-Issues#2500] opened 2023-03-21 14:55 UTC
### Game Version

v1.17.11

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

The player is unable to play the game because "respawn" button makes player disconnected from the server

### How to reproduce

The player has to die (in game).
Some connection issue has to occur at this time.
Upon reconnectiong and pressing "respawn" the error should occur

Setup. A server with 4 players over LAN (using ZeroTier). One of 4 players is hosting the game
No antiviruses.
The host has no firewall.

The error is ~ 
`A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond`
OR
`The connection closed unexpectedly: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond`

### Screenshots

No screenshots. Reproduce section contains error message

### Logs

```Log```
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/11029639/client-main.txt)
[server-audit.txt](https://github.com/anegostudios/VintageStory-Issues/files/11029640/server-audit.txt)
[server-build.txt](https://github.com/anegostudios/VintageStory-Issues/files/11029641/server-build.txt)
[server-chat.txt](https://github.com/anegostudios/VintageStory-Issues/files/11029642/server-chat.txt)
[server-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/11029643/server-debug.txt)
[server-event.txt](https://github.com/anegostudios/VintageStory-Issues/files/11029644/server-event.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/11029645/server-main.txt)
[server-storyevent.txt](https://github.com/anegostudios/VintageStory-Issues/files/11029646/server-storyevent.txt)
[client-audit.txt](https://github.com/anegostudios/VintageStory-Issues/files/11029647/client-audit.txt)
[client-chat.txt](https://github.com/anegostudios/VintageStory-Issues/files/11029648/client-chat.txt)
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/11029649/client-crash.txt)
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/11029650/client-debug.txt)

The player unable to connect is ~  "Mefune" (the name is kind of that one. I'm sorry I don't remember)

**Comment by Craluminum2413** [comment] 2023-03-21 15:15
Duplicate of #2380

**Closed by Craluminum2413** 2023-03-21 15:15 UTC
Labels: status: new

**Comment by mikola-rollun** [comment] 2023-03-21 15:19
@Craluminum2413 Why is it a duplicate? Mine is about Respawn button and #2380 is about password

**Comment by Craluminum2413** [comment] 2023-03-21 15:23
Because crashes are identical
