### ISSUE TITLE
Download Failure

### ISSUE THREAD

**Issue by Digikeem** [anegostudios/VintageStory-Issues#3066] opened 2023-09-01 10:20 UTC
### Game Version

v1.18.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

"Download failed: An error occurred trying to start process
'C:\Users\*myname*\AppData\Local\Temp\vs_update_win-x64_1.18.9.exe'
with working directory"

The only option after receiving this error is "Cancel". Once closed, it takes me back to the main menu in version 1.18.8 (Stable).

### How to reproduce

1. Press the update notification in the top right popup on the main menu.
2. Begin downloading the update and get to 100% completion.
3. Get the error popup.

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/86095960/fa68fcc9-a9e6-4f42-8e85-42e7c617fba4)

### Logs

```Log```
1.9.2023 20:16:00 [Error] An error occurred trying to start process 'C:\Users\akeem\AppData\Local\Temp\vs_update_win-x64_1.18.9.exe' with working directory 'C:\Users\akeem\AppData\Roaming\Vintagestory'. The process cannot access the file because it is being used by another process.
1.9.2023 20:16:00 [Error]    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Vintagestory.Client.GuiScreenGetUpdate.<>c__DisplayClass9_0.<<downloadInstaller>b__0>d.MoveNext() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\MainMenu\Screens\GuiScreenGetUpdate.cs:line 126

**Comment by JustForVS** [comment] 2023-09-01 21:12
same issue for 1.18.10 (installing the update by starting the downloaded file works fine)

**Comment by Th3Dilli** [comment] 2023-09-13 15:35
Duplicate of #3078

**Closed** 2023-09-21 09:11 UTC
Labels: status: duplicate
