### ISSUE TITLE
CTD when trying to open plain cloth survival handbook page

### ISSUE THREAD

**Issue by b4ruu** [anegostudios/VintageStory-Issues#3366] opened 2024-01-03 19:32 UTC
### Game Version

v1.19.0-rc.5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Game crashes consistently when trying to open the plain cloth page in survival handbook

### How to reproduce

1. Open survival handbook
2. Try to select plain cloth
3. Game crashes to desktop
or
1. Open inventory
2. Hover mouse of plain cloth
3. Press the h key on keyboard
4. Game crashes to desktop

### Logs

Running on 64 bit Windows 10.0.22000.0 with 32689 MB RAM
Game Version: v1.19.0-rc.5 (Unstable)
03.01.2024 20:12:17: Critical error occurred
Loaded Mods: game@1.19.0-rc.5, creative@1.19.0-rc.5, survival@1.19.0-rc.5
System.DivideByZeroException: Attempted to divide by zero.
   at Vintagestory.API.Client.SlideshowGridRecipeTextComponent.RenderInteractiveElements(Single deltaTime, Double renderX, Double renderY, Double renderZ) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\SlideshowGridRecipeTextComponent.cs:line 315
   at Vintagestory.API.Client.GuiElementRichtext.RenderInteractiveElements(Single deltaTime) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementRichtext.cs:line 472
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime) in VintagestoryApi\Client\UI\GuiComposer.cs:line 716
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 384
   at Vintagestory.GameContent.GuiDialogHandbook.OnRenderGUI(Single deltaTime) in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 507
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 318
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1006
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 317
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Manic-C-Lo** [comment] 2024-01-03 23:50
this is an issue in the handbook when opening anything that has plain cloth as an ingredient

**Comment by FoxBlood75** [comment] 2024-01-04 13:57
> this is an issue in the handbook when opening anything that has plain cloth as an ingredient

Looks like it's anything that uses linen, cloth itself is ok, since you can still pull up all the dyed version recipes.
though add linen sack, and poultices to the list.. what I came to report then saw this :)

**Comment by Arasine** [comment] 2024-01-04 20:51
Yep, confirmed here.

**Comment by willrun4fun** [comment] 2024-01-04 22:49
Confirmed.  I got multiple crashes today clicking on Linen Sack.

**Comment by Rufert** [comment] 2024-01-05 08:03
Same when trying to access mining bag.

**Comment by Th3Dilli** [comment] 2024-01-05 14:35
thank you 

this will be fixed in the next release

**Comment by Diakon5** [comment] 2024-01-06 09:38
Happened to me with the Gambeson Armor.

**Closed** 2024-01-06 22:02 UTC
Labels: status: resolved, priority: high, version: 1.19
