### ISSUE TITLE
Multiple crashes!

### ISSUE THREAD

**Issue by mac69mano** [anegostudios/VintageStory-Issues#2463] opened 2023-03-09 18:18 UTC
### Game Version

v1.17.11 (Stable)

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Greetings,

I was just running around, hunting when the game crashed. I reloaded the last autosave, but a minute after that, the game crahed again. Wasn't doing anything out of the ordinary.

Here is the crash report:

Running on 64 bit Windows with 31 GB RAM 
Game Version: v1.17.11 (Stable)
9.3.2023 г. 20:10:30: Critical error occurred
Loaded Mods: game@1.17.11, creative@1.17.11, survival@1.17.11
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityFruitTreePart.GenFoliageMesh(Boolean withSticks, MeshData& foliageMesh, MeshData& sticksMesh) in VSSurvivalMod\Systems\FruitTree\BEFruitTreePart.cs:line 212
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.GenMeshes() in VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:line 250
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.GenMesh() in VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:line 236
   at Vintagestory.GameContent.BlockEntityFruitTreeBranch.FromTreeAttributes(ITreeAttribute tree, IWorldAccessor worldForResolving) in VSSurvivalMod\Systems\FruitTree\BEFruitTreeBranch.cs:line 386
   at Vintagestory.Client.NoObf.ClientChunk.AddOrUpdateBlockEntityFromPacket(Packet_BlockEntity p, ClientMain game) in VintagestoryLib\Client\Model\ClientChunk.cs:line 422
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntities(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 817
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 1138
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 123
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 678
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 622
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 124
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

### Logs

```Log```

**Comment by mac69mano** [comment] 2023-03-09 18:24
The game keeps crashing. Cant play for more than few seconds. Please, help.
Thank you in advance.

**Comment by Craluminum2413** [comment] 2023-03-09 18:32
Duplicate of #2102

**Closed by Craluminum2413** 2023-03-09 18:32 UTC
Labels: status: new
