### ISSUE TITLE
Adding multiple patches to the same file overwrites previous patches applied to the file.

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#76] opened 2018-04-15 13:24 UTC
The patcher doesn't follow the RFC. The RFC states, 
"An element to add to an existing array - whereupon the supplied
      value is added to the array at the indicated location.  Any
      elements at or above the specified index are shifted one position
      to the right.  The specified index MUST NOT be greater than the
      number of elements in the array.  If the "-" character is used to
      index the end of the array (see [RFC6901]), this has the effect of
      appending the value to the array."

Yet the following patch replaces each time instead of adding. With the following patch the drifter doesn't drop clay, but it will drop sticks and if you reverse the order of clay and sticks it'll drop clay instead.

`[
	{ file: "game:entities/land/drifter", op: "add", path: "/drops/0", value: 
		{
			type: "item",
			code: "clay-blue",
			quantity: { avg: 0.5, var: 1}
		}
	},
	{ file: "game:entities/land/drifter", op: "add", path: "/drops/0", value: 
		{
			type: "item",
			code: "stick",
			quantity: { avg: 0.3, var: 0 }
		}
	},
]`

maybe I am just miss understanding but this should make the temporal gear at index 2 and clay at index 1 and stick at index 0. It could also be that it's working perfectly fine and the game is only dropping the item at 0 due to a bug. Have not tested using "-"

update: tried using "/drops/-" instead of "/drops/0" and it follows the same behavior.

**Comment by tyronx** [comment] 2018-04-15 18:35
@copygirl is that relateed to your tweaks?

**Comment by copygirl** [comment] 2018-04-16 00:46
Most likely!

**Comment by copygirl** [comment] 2018-04-16 00:59
Are my most recent changes in the game yet? From what I could see, CarryCapacity works fine with the test version of the game, in which I use array insertion patching.

Otherwise, probably requires some more debugging, as I can't currently see the issue in the code. Hopefully I'll get to it, tomorrow.

**Comment by copygirl** [comment] 2018-04-16 13:52
Trying to debug this and am unable to. I put this `drifter.json` file in my CarryCapacity mod which I have updated for the test version:
```js
[
	{ file: "game:entities/land/drifter", op: "add", path: "/drops/0", value: {
		type: "item",
		code: "clay-blue",
		quantity: { avg: 0.5, var: 1 }
	} },
	{ file: "game:entities/land/drifter", op: "add", path: "/drops/0", value: {
		type: "item",
		code: "stick",
		quantity: { avg: 0.3, var: 0 }
	} },
]
```
..but unfortunately I get this message:
`[Client Notification] JsonPatch Loader: 4 patches total, successfully applied 2 patches, missing files on 2 patches, no errors`

My own 2 patches from the same folder appear to work fine.

**Comment by tyronx** [comment] 2018-04-16 17:27
You mean you can't reproduce it? And yes your recent changes are in 1.5.2, except for the one commit on april 5

**Comment by copygirl** [comment] 2018-04-16 18:54
I can't reproduce it, but only because I can't get the patches to load, so I can't verify it.

**Comment by sirStroam** [comment] 2018-04-17 01:30
[drifterdrops.zip](https://github.com/anegostudios/VintageStory-Issues/files/1917843/drifterdrops.zip)
Here's a test mod that works for me.

**Comment by copygirl** [comment] 2018-04-17 09:37
I only modified the `modinfo.json` to make it work in my development environment, but again, I get the message `[Client Notification] JsonPatch Loader: 6 patches total, successfully applied 2 patches, missing files on 4 patches, no errors`.

**Comment by sirStroam** [comment] 2018-04-17 14:12
Well I only have two patches and that says four. Is your drifter.json in the same place? Are you sure it's the drifter patches having issues?

**Comment by sirStroam** [comment] 2018-04-17 15:14
What if you put it in assets/game/patches and remove the 'game:' part from the path? Do you see anything wrong with the patch? Have you tried making your own version of the patches?

**Comment by tyronx** [comment] 2018-04-17 15:35
Also @copygirl you could add a debug log or 2 into the vanilla code for testing, as you got access to it.

**Comment by copygirl** [comment] 2018-04-17 17:05
Ah, fine. I guess I did self-assign this issue.

**Comment by sirStroam** [comment] 2018-04-17 17:54
Now that I am thinking of it, when I tried two patches on the wolf, one for damage and a second for spawn rates, it stopped decreasing the damage. It could have been because the damage patch came first. What if it's not an array issue but applying multiple patches to the same file issue as each patch some how erases the previous patch. I will test that later tonight when I am back at my computer.

**Comment by copygirl** [comment] 2018-04-17 20:14
I can't even get to the point of confirming, let alone debugging this, if my patch file doesn't load. I'm going to need some help, @tyronx!

**Comment by sirStroam** [comment] 2018-04-18 00:42
I have confirmed that if multiple patches are applied to a file, only the last one is applied. To test I increased the drop rate of gears and retested with the patch I posted here. The drifter dropped both gears and sticks but not clay. I then added a new patch at the very end that modified the damage drifters do to 3. The drifters no longer dropped either the clay or stick but still dropped the gears and did 3 damage.

**Comment by sirStroam** [comment] 2018-04-18 00:49
I don't know how patching is done but based on this experience I think each patch has a copy of the original file and then as they are applied each patch saves their version of the original file modified with the patch meaning whichever patch comes last to a file is the only one that is applied. This applies even if patches are in separate json files. I believe this also means that if my mod loads after another mod like carry capacity and modifies one of the same files that carry capacity does, carry capacity will no longer work on that item.

**Comment by tyronx** [comment] 2018-04-18 02:25
@copygirl as stated in discord, you are looking at the wrong log line. The client doesn't load the entities directly, only the server does.

**Comment by copygirl** [comment] 2018-04-18 10:03
@tyronx In that case, the confusion should be avoided by not attempting to apply those patch files on the client ^^

**Comment by sirStroam** [comment] 2018-04-18 10:33
No problem. The future of mod compatibility relies on it.

**Comment by copygirl** [comment] 2018-04-18 17:01
Found the (super simple) problem and fixed it for next release!

**Closed by copygirl** 2018-04-18 17:01 UTC
Labels: status: resolved, target: engine, type: bug

**Comment by tyronx** [comment] 2018-04-19 06:34
@copygirl there is now a sidetype arg for the patches to reduce confusion.

**Comment by copygirl** [comment] 2018-04-19 06:59
@tyronx I don't think that'll solve the confusion. I didn't know some things are only loaded on the server and then sent to the client.
