### ISSUE TITLE
Crash on alt+Tab to access game.

### ISSUE THREAD

**Issue by Joe-C-Stewart** [anegostudios/VintageStory-Issues#3828] opened 2024-04-20 18:03 UTC
### Game Version

v1.19.7 (Stable)

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

I Alt+Tab to begin playing on the multiplayer server.

### How to reproduce

Join server + Download mods for server + Alt+Tab Out to wait for your Avatar to spawn into Multiplayer world + Listen for in-game audio + Alt+Tab to bring up the full-screen game = Game crashes.

### Logs

```Log```
Running on 64-bit Windows 10.0.19045.0 with 16348 MB RAM
Game Version: v1.19.7 (Stable)
20/04/2024 18:51:46: Critical error occurred
Loaded Mods: aculinaryartillery@1.1.4, bettercrates@1.7.0, chiseltools@1.11.2, dsd@1.0.0, driftersbelongunderground@1.0.1, geoaddons@1.3.3, itemrecycle@0.4.0, juicyores@1.0.0, millwright@1.1.5, moredrifterloot@1.5.4, NoMoreDrifterThrowing@1.0.0, primitivesurvival@3.5.2, rope-bridges@1.1.0, bone2lime@1.0.2, game@1.19.7, abcsreborn@0.2.1, alchemy@1.6.31, ancienttools@1.5.18, animalcages@3.0.2, betterfirepit@1.1.4, betterruins@0.3.4, carryon@1.7.4, ColoredTorchesRedux@1.1.0, commonlib@2.3.7, expandedfoods@1.6.9, falldamageoptions@1.1.1, farmlanddropssoil@1.4.0, medievalexpansion@3.13.1, morepiles@1.5.0, neverwinter@1.5.3, petai@2.2.3, rockstratavariety@0.0.1, stonebakeoven@1.1.3, storagecontroller@1.0.8, th3dungeon@0.2.1, updatedtexturesandmodels@0.8.6, creative@1.19.7, vsimgui@1.1.3, survival@1.19.7, xlib@0.8.3-pre.1, em@2.5.2, feverstonewilds@1.4.5, stonequarry@3.2.1, xskills@0.8.5-pre.1, moreroads@1.5.6
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 49
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 815
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 731
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Craluminum2413** [comment] 2024-04-20 18:19
Duplicate of #3550

**Closed by Craluminum2413** 2024-04-20 18:19 UTC
Labels: status: new
