### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Black53** [anegostudios/VintageStory-Issues#428] opened 2020-03-05 17:30 UTC
**Game Version:**  v1.12.5
**Platform:** Windows
**Modded:** No
### Description
the game is crashing on startup

### Expected behavior
the game starts but doesn't get to the main screen

### Logs
```
Running on 64 bit Windows with 8 GB RAM 
Version: v1.12.5 (Stable)3/5/2020 12:17:21 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.ClientPlatformWindows.LoadTexture(IBitmap bmp, Boolean linearMag, Int32 clampMode, Boolean generateMipmaps)
   at _mKeEWUbBZsjLS6VlGWgOoYQFk2K._KNs6g2GMtsTu5gnL4MXdRgZVlLh()
   at _lt8TgSVuBImgzFgAFlSeVzSFsSy._HdDsdRJDH8nMF88r278C4eqdINGA()
   at _lt8TgSVuBImgzFgAFlSeVzSFsSy._gjiBClIE7Yspuz65gCqPGSAnUYeb()
   at _lt8TgSVuBImgzFgAFlSeVzSFsSy._NbPATb9BXlxRc4ZhH2GgyFCUInp(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _hCuHXesCXlp0LGSdrsPFpw4up5n._mOm8EuKIvHpaJoztxNWRpAoOpbM(_55ISULxdcpPfF8D2JP831aWhOBe , String[] )
   at _iCfIbY24GyBXP5lAwqsSlD9COxC._mOm8EuKIvHpaJoztxNWRpAoOpbM(ThreadStart )
-------------------------------

**Comment by AdjustableSquelch** [comment] 2020-03-05 17:56
got exactly the same. was working last night.

**Comment by copygirl** [comment] 2020-03-05 19:05
Duplicate of #407. Just update your game to the new 1.12.6 release which fixes this issue.

**Closed by copygirl** 2020-03-05 19:05 UTC
Labels: status: duplicate
