### ISSUE TITLE
Beeswax in handbook crashes game

### ISSUE THREAD

**Issue by Jamie-Louise** [anegostudios/VintageStory-Issues#1504] opened 2021-12-26 21:23 UTC
**Game Version:** 1.16.0-rc.3
**Platform:** Windows
**Modded:** No
**SP/MP:** Singleplayer

### Description
Accessing the handbook entry for beeswax causes the game to crash.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.16.0-rc.3 (Unstable)12/26/2021 2:43:29 PM: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionStatesNative(IWorldAccessor world, ItemSlot inslot)
   at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionState(IWorldAccessor world, ItemSlot inslot, EnumTransitionType type)
   at Vintagestory.Client.NoObf.InventoryItemRenderer.GetItemStackRenderInfo(ClientMain game, ItemSlot inSlot, EnumItemRenderTarget target, Single dt)
   at Vintagestory.Client.NoObf.InventoryItemRenderer.RenderItemstackToGui(ItemSlot inSlot, Double posX, Double posY, Double posZ, Single size, Int32 color, Boolean shading, Boolean origRotate, Boolean showStackSize)
   at Vintagestory.API.Client.SlideshowItemstackTextComponent.RenderInteractiveElements(Single deltaTime, Double renderX, Double renderY)
   at Vintagestory.API.Client.GuiElementRichtext.RenderInteractiveElements(Single deltaTime)
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime)
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime)
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _x2sphGvaQHYRL58iBmwDrxU4JDn._YW8xM33zLilYIiYmPz3LwkRyZnf(Single )
   at _8d8bxAkSchxDthWdXGk9L7JzIAp._COZH04DCHcYdj7FJVekhdO7h2zW(Single )
   at _8d8bxAkSchxDthWdXGk9L7JzIAp._NGLt2tlj0Kdb71xAZX2ab8OUsaY(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\VintageStory\opentk\src\OpenTK\GameWindow.cs:line 375
   at _Gqy4bfkYgCRmVM3rr5ctXVLZlMh._aoi1Mc6iTidbcOBRjahZfdoHVdN(_BNIaG9Y7PSPYLFpjzhV1OMF5mHh , String[] )
   at _0ynubLUTRXRju8HMEIDSQn5ni6F._aoi1Mc6iTidbcOBRjahZfdoHVdN(ThreadStart )
-------------------------------

```

**Comment by Craluminum2413** [comment] 2021-12-26 21:26
Duplicate of #1430

**Comment by copygirl** [comment] 2021-12-26 22:45
Thanks for reporting, I also hope this will be fixed soon.

Closing as duplicate.

**Closed by copygirl** 2021-12-26 22:45 UTC
Labels: status: duplicate
