### ISSUE TITLE
Parameter name: Unable to find a texture for texture code 'handle' in item game:shield-woodmetalleather. Giving up. Sorry.

### ISSUE THREAD

**Issue by Rosethorns** [anegostudios/VintageStory-Issues#1961] opened 2022-06-25 03:59 UTC
**Game Version:** 1.17.0.pre.1
**Platform:** Windows
**Modded:** Yes (Carryon, Animal Cages) 
**SP/MP:** Singleplayer

### Description
Crash

### How to reproduce
1. Handbook acacia planks
2. It crashes

### Logs
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.0-pre.1 (Unstable)
Loaded Mods: animalcages@2.0.6, game@1.17.0-pre.1, carrycapacity@0.6.5, sandsoftime@1.0.1, creative@1.17.0-pre.1, survival@1.17.0-pre.1
25/06/2022 3:57:22 pm: Critical error occurred
System.ArgumentNullException: Value cannot be null.
Parameter name: Unable to find a texture for texture code 'handle' in item game:shield-woodmetalleather. Giving up. Sorry.
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElement(Int32 indexForLogging, MeshData meshdata, ShapeElement element, TesselationMetaData meta)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(MeshData meshdata, ShapeElement[] elements, TesselationMetaData meta)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(MeshData meshdata, ShapeElement[] elements, TesselationMetaData meta)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(MeshData meshdata, ShapeElement[] elements, TesselationMetaData meta)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(Shape shapeBase, MeshData& modeldata, Vec3f wholeMeshRotation, Vec3f wholeMeshOffset, Single wholeMeshScale, TesselationMetaData meta)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(String type, AssetLocation name, CompositeShape compositeShape, MeshData& modeldata, ITexPositionSource texSource, Int32 generalGlowLevel, Byte climateColorMapIndex, Byte seasonColorMapIndex, Nullable`1 quantityElements, String[] selectiveElements)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateItem(Item item, MeshData& modeldata, ITexPositionSource texSource)
   at Vintagestory.GameContent.ItemShield.GenMesh(ItemStack itemstack)
   at Vintagestory.GameContent.ItemShield.OnBeforeRender(ICoreClientAPI capi, ItemStack itemstack, EnumItemRenderTarget target, ItemRenderInfo& renderinfo)
   at Vintagestory.Client.NoObf.InventoryItemRenderer.GetItemStackRenderInfo(ClientMain game, ItemSlot inSlot, EnumItemRenderTarget target, Single dt)
   at Vintagestory.Client.NoObf.InventoryItemRenderer.RenderItemstackToGui(ItemSlot inSlot, Double posX, Double posY, Double posZ, Single size, Int32 color, Boolean shading, Boolean origRotate, Boolean showStackSize)
   at Vintagestory.API.Client.SlideshowItemstackTextComponent.RenderInteractiveElements(Single deltaTime, Double renderX, Double renderY)
   at Vintagestory.API.Client.GuiElementRichtext.RenderInteractiveElements(Single deltaTime)
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime)
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime)
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt)
   at Vintagestory.Client.ScreenManager.Render(Single dt)
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 22/06/2022 12:30:26 pm, Site = , Source = Windows Error Reporting, Message = Fault bucket 1480545446510131094, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.0.0
P3: 10.0.22000.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\rosea\AppData\Local\Temp\RDR6AF4.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.ca1c8cea-d4fc-40e8-afe2-c54e74b1735f.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.b04d321d-aa29-4daf-9f2b-dbc16f23ab9d.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.2f490112-07e5-42b6-924e-796f01fec8f3.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.6adf13cf-c40e-4831-87f9-bf144fb17253.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: a0cdd4b6-6e7d-4ccf-bfdd-cd73bfd2b7ca
Report Status: 268435456
Hashed bucket: 27186fb1f4fc4f8f048bf43d450ef796
Cab Guid: 0 }
--------------
{ TimeGenerated = 6/04/2022 11:22:11 pm, Site = , Source = Windows Error Reporting, Message = Fault bucket 1726649466493275827, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.5.0
P3: 10.0.22000.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\rosea\AppData\Local\Temp\RDRF911.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.b34cc87a-b395-40d0-84ad-fc050103f23b.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.6e105625-b0fc-42c1-9727-e5ec9ef60e08.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.9ffa61fa-aa90-4b41-a827-1234e7e02b47.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.89efdc15-c82e-4501-b14a-f941bfbfe71f.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 05c75696-2c20-4e75-b3b7-6d363591fb86
Report Status: 268435456
Hashed bucket: 366589d3cc86a9fd17f64a8aa5f30eb3
Cab Guid: 0 }
--------------
{ TimeGenerated = 30/11/2021 5:03:16 am, Site = , Source = Windows Error Reporting, Message = Fault bucket 1240719451329337488, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.9.0
P3: 10.0.22000.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\rosea\AppData\Local\Temp\RDR67FE.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.030180b2-8dd9-4523-aa92-35cf48432607.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.6b53dba2-3022-4240-80af-bdd416c0535f.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.58a499ad-ea23-4e01-b516-77445e982eaf.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.dfed37f6-9b3f-4c8e-a141-dbb1cd1c670f.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 98f909df-ee8e-4d87-9e00-2e5631733cae
Report Status: 268435456
Hashed bucket: f3fbe0c0c09f525b5137ebc472671890
Cab Guid: 0 }

**Comment by copygirl** [comment] 2022-06-25 04:10
Duplicate of #1920.

**Closed by copygirl** 2022-06-25 04:10 UTC
Labels: status: duplicate
