### ISSUE TITLE
Game crashes when making compost

### ISSUE THREAD

**Issue by VolkodavMstivoy** [anegostudios/VintageStory-Issues#2035] opened 2022-07-22 08:50 UTC
**Game Version:** 1.17-pre 5
**Platform:** Windows 10
**Modded:** No
**SP/MP:** Singleplayer

### Description
If barrel with compost is ready it makes issues with game, I am not sure but before that game crashed 2 times, when I was in my village. After rebooting game third time I went into journey and game was stable. Soon enough I saw my barrel have no textures and indeed the compost was almost done when I was leaving. I believe those crashes was happening because of compost.

### How to reproduce
1. Make a compost in barrel (rot, 20 days...)
2. The barrel should disapear, you can interact and extract compost then use barrel as normal, it appears like usual but...
3. Try to dump this compost again into barrel
4. Crash

possibly:
2. when compost is done, barrel changes texture and crashes.

### Logs
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.0-pre.5 (Unstable)
Loaded Mods: game@1.17.0-pre.5, creative@1.17.0-pre.5, survival@1.17.0-pre.5
22.07.2022 10:31:07: Critical error occurred
System.NullReferenceException: Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
   w Vintagestory.GameContent.BlockBarrel.getContentMesh(ItemStack stack, BlockPos forBlockPos, String shapefilename) w C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Barrel\BlockBarrel.cs:wiersz 208
   w Vintagestory.GameContent.BlockBarrel.GenMesh(ItemStack contentStack, ItemStack liquidContentStack, Boolean issealed, BlockPos forBlockPos) w C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Barrel\BlockBarrel.cs:wiersz 152
   w Vintagestory.GameContent.BlockEntityBarrel.GenMesh() w C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Barrel\BEBarrel.cs:wiersz 320
   w Vintagestory.GameContent.BlockEntityBarrel.Inventory_SlotModified(Int32 slotId) w C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\Barrel\BEBarrel.cs:wiersz 110
   w Vintagestory.API.Common.InventoryBase.DidModifyItemSlot(ItemSlot slot, ItemStack extractedStack) w C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Common\Inventory\InventoryBase.cs:wiersz 480
   w Vintagestory.API.Common.ItemSlot.OnItemSlotModified(ItemStack sinkStack) w C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Common\Inventory\ItemSlot.cs:wiersz 418
   w Vintagestory.API.Common.ItemSlotBarrelInput.OnItemSlotModified(ItemStack stack) w C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Inventory\ItemSlotBarrelInput.cs:wiersz 26
   w Vintagestory.API.Common.InventoryBase.ActivateSlot(Int32 slotId, ItemSlot sourceSlot, ItemStackMoveOperation& op) w C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Common\Inventory\InventoryBase.cs:wiersz 448
   w Vintagestory.API.Client.GuiElementItemSlotGridBase.SlotClick(ICoreClientAPI api, Int32 slotId, EnumMouseButton mouseButton, Boolean shiftPressed, Boolean ctrlPressed, Boolean altPressed) w C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:wiersz 979
   w Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseDownOnElement(ICoreClientAPI api, MouseEvent args) w C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:wiersz 772
   w Vintagestory.API.Client.GuiElement.OnMouseDown(ICoreClientAPI api, MouseEvent mouse) w C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\GuiElement.cs:wiersz 638
   w Vintagestory.API.Client.GuiComposer.OnMouseDown(MouseEvent mouseArgs) w C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\GuiComposer.cs:wiersz 440
   w Vintagestory.API.Client.GuiDialog.OnMouseDown(MouseEvent args) w C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:wiersz 536
   w Vintagestory.Client.NoObf.GuiManager.OnMouseDown(MouseEvent args) w C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Gui\GuiManager.cs:wiersz 394
   w Vintagestory.Client.NoObf.ClientMain.OnMouseDown(MouseEvent args) w C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:wiersz 2248
   w Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonDown(Object sender, MouseButtonEventArgs e) w C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\Input.cs:wiersz 220
   w System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   w System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   w OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) w C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:wiersz 792
   w OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   w OpenTK.Platform.Windows.WinGLNative.ProcessEvents() w C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:wiersz 1554
   w OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) w C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:wiersz 368
   w Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   w Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) w C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:wiersz 87
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 22.07.2022 02:27:34, Site = , Source = .NET Runtime, Message = Aplikacja: Vintagestory.exe
Wersja architektury: v4.0.30319
Opis: proces został przerwany z powodu nieobsłużonego wyjątku.
Informacje o wyjątku: kod wyjątku: c0020001, adres wyjątku: 00007FF849114FD9
Stos:
 }

**Comment by Craluminum2413** [comment] 2022-07-22 09:11
Duplicate of #2021

**Comment by Craluminum2413** [comment] 2022-07-22 14:39
Forgot to close

**Closed by Craluminum2413** 2022-07-22 14:39 UTC
Labels: status: duplicate
