### ISSUE TITLE
Waypoints in Multiplayer with internet server connection not work correctly

### ISSUE THREAD

**Issue by rhonibaer** [anegostudios/VintageStory-Issues#455] opened 2020-03-07 18:34 UTC
**Game Version:** 1.12.6
**Platform:** Windows 
**Server Version:** 1.12.5
**Host by:** ping perfect
**Modded:** No 

### Description
Creating waypoints on the map (press M) will not shown after creation.
By using console command /waypoint add {color} {text} its working fine.

only happens on external Server connection.
with local dedicated server (Multiplayer with localhost server) it's working.

### How to reproduce
1. open map by press M
2. right click on map, try to create a waypoint
3. Server responses waypoint added successfull, but waypoint is not shown.

Try it the console command /waypoint add {...}  its working fine.

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

**Comment by CheetahG** [comment] 2020-03-09 20:34
Something I would like to add to this issue.
According to /waypoint list, all waypoints made with the map (right-clicking on the map) default to x=-2147483648 y=113 and z=-2147483648. Looks like an overflow to me

**Comment by Bloodsaw** [comment] 2020-03-10 17:20
How big is your world? Bigger than 1mil x 1mil?

**Comment by rhonibaer** [comment] 2020-03-10 18:16
my server world has default size. i think its 100k x 100k

**Comment by tyronx** [comment] 2020-03-12 11:37
I'd really love to find this issue. Are there any other patterns to this bug? 

Are all players of that particular server affected? Is only one particular server or are all external servers affected?

**Comment by CheetahG** [comment] 2020-03-12 13:42
My friend has a server on PingPerfect, I got one from G-Portal. Looks like both servers have the same problem I placed my waypoint at spawn and typed /waypoint list. The waypoint was wrong again.

**Comment by tyronx** [comment] 2020-03-12 13:45
@CheetahG does that apply just to you or any player that joins that server?

And secondly, could you temporarily invite me to that server for testing? I'd appreciate ^_^

**Comment by CheetahG** [comment] 2020-03-12 13:46
My buddy with the Ping-Perfect server had the same problem.
I'll pm you on discord, how about that? :D

**Comment by tyronx** [comment] 2020-03-12 13:48
yup, please ping me on discord

**Comment by tyronx** [comment] 2020-03-12 14:10
Found the cause, regional decimal seperator issues again. Will be fixed for next release.

**Closed** 2020-03-12 15:49 UTC
Labels: status: resolved, target: multiplayer, type: bug

**Comment by rhonibaer** [comment] 2020-03-12 16:33
Great job. :) thx for info.
