### ISSUE TITLE
Last pie slice gives no saturation when picked up without a knife

### ISSUE THREAD

**Issue by jacopouggeri** [anegostudios/VintageStory-Issues#4053] opened 2024-08-28 22:27 UTC
### Game Version

1.19.8

### Platform

Mac

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When picked up by hand (not with a knife), the last pie slice has an unusual tooltip: it says it is 1 serving (while normal pie slices have 0.25) and so displays 4x the saturation values. When eaten, it gives zero saturation.

### How to reproduce

1. Grab pie from creative menu or bake it
2. Cut 3 slices
3. Grab last one with an empty hand
4. Enjoy cursed pie

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2024-08-28 22:40
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/2117

**Closed by Craluminum2413** 2024-08-28 22:40 UTC
Labels: status: new
