### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by malnaur** [anegostudios/VintageStory-Issues#3460] opened 2024-01-18 02:24 UTC
### Game Version

1.19.0

### Platform

Windows

### Modded

None

### SP/MP

Multiplayer

### Description

Repeated crashes in or near my fruit orchard. From client-main.txt:

17.1.2024 21:18:09 [Fatal] Caught unhandled exception in thread 'asyncparticles'. Exiting game.
17.1.2024 21:18:09 [Error] Exception: The given key 'climateLighterPlantTint' was not present in the dictionary.
   at Vintagestory.Client.NoObf.ClientWorldMap.ApplyColorMapOnRgba(String climateColorMap, String seasonColorMap, Int32 color, Int32 posX, Int32 posY, Int32 posZ, Boolean flipRb) in VintagestoryLib\Client\ClientWorldMap.cs:line 396
   at Vintagestory.Client.NoObf.ClientMain.ApplyColorMapOnRgba(String climateColorMap, String seasonColorMap, Int32 color, Int32 posX, Int32 posY, Int32 posZ, Boolean flipRb) in VintagestoryLib\Client\ClientMain.cs:line 2661
   at Vintagestory.GameContent.BlockFruitTreeFoliage.GetColor(ICoreClientAPI capi, BlockPos pos) in VSSurvivalMod\Systems\FruitTree\BlockFruitTreeFoliage.cs:line 100
   at Vintagestory.GameContent.WeatherSimulationParticles.SpawnDustParticles(IAsyncParticleManager manager, WeatherDataSnapshot weatherData, EntityPos plrPos, Single dryness, Int32 onwaterSplashParticleColor) in VSEssentials\Systems\Weather\WeatherSimulationParticles.cs:line 410
   at Vintagestory.GameContent.WeatherSimulationParticles.asyncParticleSpawn(Single dt, IAsyncParticleManager manager) in VSEssentials\Systems\Weather\WeatherSimulationParticles.cs:line 371
   at Vintagestory.Client.NoObf.SystemRenderParticles.OnSeperateThreadGameTick(Single dt) in VintagestoryLib\Client\Systems\Render\Particle\RenderParticles.cs:line 270
   at Vintagestory.Client.NoObf.ClientThread.Update() in VintagestoryLib\Client\ClientThread.cs:line 75
   at Vintagestory.Client.NoObf.ClientThread.Process() in VintagestoryLib\Client\ClientThread.cs:line 61
17.1.2024 21:18:09 [Notification] Window was resized to 0 0? Window probably got minimized. Will not rebuild frame buffers
17.1.2024 21:18:30 [Notification] Destroying game session, waiting up to 200ms for client threads to exit
17.1.2024 21:18:30 [Notification] Exiting current game to main menu, reason: client thread crash
17.1.2024 21:18:36 [Warning] MeshRef with vao id 12960 with 1386 indices is leaking memory, missing call to Dispose. Set env var VAO_DEBUG_DISPOSE to get allocation trace.

### How to reproduce

No idea. This release is very buggy.

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2024-01-18 05:23
Duplicate of #3455

**Closed by Craluminum2413** 2024-01-18 05:23 UTC
Labels: status: new

**Comment by Lbroil** [comment] 2024-01-18 12:57
Try creating a world without using the full color map option. That stopped my game from crashing when I had the same issue.
