### ISSUE TITLE
1.7.2 Crash - happened both with and without culling on

### ISSUE THREAD

**Issue by qpreik** [anegostudios/VintageStory-Issues#205] opened 2018-10-04 11:18 UTC
```
Running on 64 bit Windows with 16GB RAM 
Version: 1.7.2 Survival Mode Edition (Stable)2018-10-04 7:16:31 AM: Critical error occurred
System.Exception: Fatal. Trying to render a disposed texture
   at Vintagestory.GameContent.ChunkMapComponent.Render(GuiElementMap map, Single dt)
   at Vintagestory.GameContent.GuiElementMap.RenderInteractiveElements(Single deltaTime)
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime)
   at Vintagestory.API.Client.GuiDialog.OnRender2D(Single deltaTime)
   at _wpPLE23zf00r39hpRKon5mqP5mA._M5nrgddBERj4CCHkumSKns4gesh(Single )
   at _pu0Z3WUuTo0DHdccm1wEZ5VVzrc._sDLAors0yPCAad9lAHhT1phBzyp(EnumRenderStage , Single )
   at _kX4YhEgqRvva0SLjxKCDZEJhpkR._F80cBHS04KZ9B8E0b5rAsNEZumM(Single )
   at _sFmQI8hVe51fSou0FLOaYCL8EqD._F80cBHS04KZ9B8E0b5rAsNEZumM(Single )
   at _2Eqi7oaQM5BUzCINi0IyyxKB9ZD._IPI7nxJPIOunZaCJGWA9hiO2uhF(Single )
   at _2Eqi7oaQM5BUzCINi0IyyxKB9ZD._NJ5w4222dkJ6FNuIYt9b535Qh6p(Single )
   at _Zr8OoYf7GQongNFU6zkFEVS5fGD._W9mUqPEMP8km0eDQS76XSLeB8Yf(Object , FrameEventArgs )
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _iZ8xtPBsvaQSibwvswDPCdcYlBH._rkEsrsqXE543FKlRBAYxM6PVbE(_TFMvTW5AHjfF1YiV4InIutPGVNs , String[] )
   at _vQsiKAINRamB4s7oNyzPaQWvktI._rkEsrsqXE543FKlRBAYxM6PVbE(ThreadStart )
```

**Comment by qpreik** [comment] 2018-10-04 11:22
Crashes at the bottom of the cliff, tried different ways down.

https://www.dropbox.com/s/f9v01yu4wy4jo5d/creepy%20hermit%20valley%20-%20crashes%20at%20bottom%20of%20cliff.zip?dl=0

**Comment by tyronx** [comment] 2018-10-04 13:56
Thanks, i'm working a fix. You can downgrade to v1.7.1 to avoid the crash

**Comment by copygirl** [comment] 2018-10-04 17:30
This looks to be a duplicate of #204. Let me know if that's not the case.

**Closed by copygirl** 2018-10-04 17:30 UTC
Labels: status: new, type: crash
