### ISSUE TITLE
Crash on multiplayer game start

### ISSUE THREAD

**Issue by JohnyChurch** [anegostudios/VintageStory-Issues#2295] opened 2022-11-20 14:13 UTC
### Game Version

v1.17.6 (stable)

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Crach on start

### How to reproduce

Crash when joining the server multiplayer game.

### Logs

Running on 64 bit Windows with 12 GB RAM 
Game Version: v1.17.6 (Stable)
20.11.2022 15:10:53: Critical error occurred
Loaded Mods: extrachests@1.6.0, fancydoors@1.1.1, primitivesurvival@3.0.5, rope-bridges@1.1.0, tradeomat@1.6.3, game@1.17.6, hudclock@2.8.0, medievalexpansion@3.8.1, mcrate@1.0.4, petai@1.5.5, prospectorinfo@3.1.2, stonequarry@2.0.0-rc.4, creative@1.17.6, survival@1.17.6, workbenchexpansion@1.5.1, feverstonehorses@1.3.9-rc.2
System.Exception: Don't know how to instantiate block of class 'RentChestBlock' did you forget to register a mapping?
   v Vintagestory.Common.ClassRegistry.CreateBlock(String blockClass) v C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Common\ClassRegistry.cs:řádek 129
   v Vintagestory.Common.BlockTypeNet.ReadBlockTypePacket(Packet_BlockType packet, IWorldAccessor world, ClassRegistry registry) v C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Common\Network\BlockTypeNet.cs:řádek 20
   v Vintagestory.Client.NoObf.GeneralPacketHandler.PopulateBlocks(Block[] blocks, Int32 start, Int32 maxCount) v C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:řádek 536
   v Vintagestory.Client.NoObf.GeneralPacketHandler.LoadBlockTypes() v C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:řádek 451
   v Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerAssets_Step1() v C:\Users\tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:řádek 418
   v System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   v System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   v System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   v System.Threading.ThreadPoolWorkQueue.Dispatch()

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 20.11.2022 15:10:54, Site = , Source = Application Error, Message = Název chybující aplikace: Vintagestory.exe, verze: 1.17.6.0, časové razítko: 0x633bf838
Název chybujícího modulu: KERNELBASE.dll, verze: 10.0.19041.2193, časové razítko: 0x7f7062e1
Kód výjimky: 0xe0434352
Posun chyby: 0x000000000002cd29
ID chybujícího procesu: 0x3298
Čas spuštění chybující aplikace: 0x01d8fce9dd564a19
Cesta k chybující aplikaci: C:\Users\PC\AppData\Roaming\Vintagestory\Vintagestory.exe
Cesta k chybujícímu modulu: C:\Windows\System32\KERNELBASE.dll
ID zprávy: 55a49a43-f0df-4968-b34f-9aeae1492d80
Úplný název chybujícího balíčku: 
ID aplikace související s chybujícím balíčkem:  }
--------------
{ TimeGenerated = 20.11.2022 15:10:53, Site = , Source = .NET Runtime, Message = Aplikace: Vintagestory.exe
Verze Framework: v4.0.30319
Popis: Proces byl ukončen z důvodu neošetřené výjimky.
Informace o výjimce: System.Exception
   na Vintagestory.Common.ClassRegistry.CreateBlock(System.String)
   na Vintagestory.Common.BlockTypeNet.ReadBlockTypePacket(Packet_BlockType, Vintagestory.API.Common.IWorldAccessor, Vintagestory.Common.ClassRegistry)
   na Vintagestory.Client.NoObf.GeneralPacketHandler.PopulateBlocks(Vintagestory.API.Common.Block[], Int32, Int32)
   na Vintagestory.Client.NoObf.GeneralPacketHandler.LoadBlockTypes()
   na Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerAssets_Step1()
   na System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   na System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   na System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   na System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
--------------
{ TimeGenerated = 20.11.2022 15:06:03, Site = , Source = .NET Runtime, Message = Aplikace: Vintagestory.exe
Verze Framework: v4.0.30319
Popis: Proces byl ukončen z důvodu neošetřené výjimky.
Informace o výjimce: System.Exception
   na Vintagestory.Common.ClassRegistry.CreateBlock(System.String)
   na Vintagestory.Common.BlockTypeNet.ReadBlockTypePacket(Packet_BlockType, Vintagestory.API.Common.IWorldAccessor, Vintagestory.Common.ClassRegistry)
   na Vintagestory.Client.NoObf.GeneralPacketHandler.PopulateBlocks(Vintagestory.API.Common.Block[], Int32, Int32)
   na Vintagestory.Client.NoObf.GeneralPacketHandler.LoadBlockTypes()
   na Vintagestory.Client.NoObf.GeneralPacketHandler.HandleServerAssets_Step1()
   na System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   na System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   na System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   na System.Threading.ThreadPoolWorkQueue.Dispatch()

 }

**Comment by fipil** [comment] 2022-11-20 14:20
The error is probably caused by my mod DjinlandEssentials update. I'm solving it now. Pls. close this issue.

**Comment by JohnyChurch** [comment] 2022-11-20 14:33
Mod issue, resolved with mod owner.

**Closed** 2022-11-20 14:33 UTC
Labels: status: invalid
