### ISSUE TITLE
crashed when trying to join random server

### ISSUE THREAD

**Issue by NoriteSC** [anegostudios/VintageStory-Issues#1958] opened 2022-06-21 16:41 UTC
```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.16.5 (Stable)
Loaded Mods: game@1.16.5, creative@1.16.5, survival@1.16.5
21.06.2022 18:21:14: Critical error occurred
System.Exception: FBO Render2DLoadedTexture: One or more attachment points are not framebuffer attachment complete. This could mean there’s no texture attached or the format isn’t renderable. For color textures this means the base format must be RGB or RGBA and for depth textures it must be a DEPTH_COMPONENT format. Other causes of this error are that the width or height is zero or the z-offset is out of range in case of render to volume.
   w Vintagestory.Client.NoObf.ClientPlatformWindows.CheckFboStatus(FramebufferTarget target, String fbtype)
   w Vintagestory.Client.NoObf.ClientPlatformWindows.CreateFramebuffer(FramebufferAttrs fbAttrs)
   w Vintagestory.Client.NoObf.TextureAtlasManager.GenFramebuffer()
   w Vintagestory.Client.NoObf.TextureAtlasManager.ComposeTextureAtlassesFromTextures(Dictionary`2 textureLocations, String itemclass)
   w Vintagestory.Client.NoObf.ClientMain.OnServerBlocksItemsReceivedStep2B(Action onCompleted, Int32 blockCount)
   w Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   w _vuG4DGUoqAIliPHbC5Jd2S4bgWAA._DPQfPEsBXX5ftH8l1sqqtyB2Itl(Single )
   w _8UC8FAMhwKY89IbtSRDjsNSApPJ._KbwUAfxjCHyIG0aK445AAA9FHl5(Single )
   w _8UC8FAMhwKY89IbtSRDjsNSApPJ._R0wAt2N0TpONMxGD0HJG3bDrRcI(Single )
   w Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   w System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   w OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) w C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:wiersz 479
   w OpenTK.GameWindow.DispatchRenderFrame() w C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:wiersz 454
   w OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) w C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:wiersz 375
   w _7zNxEbLnuy6Bq08TdMSIu9ZbrKf._vvUTh6X5xLRNnjtX2xSE7z8yMeh(_SUsdg1ytavxaRcNNkhfDrODGhGP , String[] )
   w _yA4PJazdKq1OMm8H6js6v5AhQB._vvUTh6X5xLRNnjtX2xSE7z8yMeh(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{TimeGenerated = 5/28/2022 20:33:16, Site =, Source = Application Hang, Message = Vintagestory.exe version 1.16.5.0 has stopped working with Windows and has been closed. To see if there is more information available about this issue, check the problem history in Security and Maintenance in Control Panel.

Process ID: 3ea0

Start time: 01d8727191c2ad2b

End time: 14

Application path: F: \ VintageStory1.16.5 \ Vintagestory.exe

Report ID: 2db0c4b9-9dfe-47f5-9f9d-fb50d305dac9

Faulting package full name:

ID of the application associated with the error package:

Hang Type: Unknown
}
```

**Comment by NoriteSC** [comment] 2022-06-21 16:49
i got it fixed by deleting appdata

**Comment by copygirl** [comment] 2022-06-21 16:56
If this happens again please be sure to provide the full log files as well.

**Comment by maestrogaffney** [comment] 2022-06-23 03:33
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.16.5 (Stable)
Loaded Mods: 
6/22/2022 8:29:38 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at _zXtrAlwcMxPDN3pkprgKfNJKDxy._CN6APN3drRhFjyu5nqigqRRs43X()
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   at _eiwcWjWOiipEBFF56arDK3XkTvG._NjwaSHiLd2LGFKsjyFwy2EWUdSw(MouseEvent )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 808
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1554
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 368
   at _7zNxEbLnuy6Bq08TdMSIu9ZbrKf._vvUTh6X5xLRNnjtX2xSE7z8yMeh(_SUsdg1ytavxaRcNNkhfDrODGhGP , String[] )
   at _yA4PJazdKq1OMm8H6js6v5AhQB._vvUTh6X5xLRNnjtX2xSE7z8yMeh(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 6/22/2022 8:28:19 PM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.16.5.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 42a4

Start Time: 01d886b13ae5257c

Termination Time: 5

Application Path: G:\Vintagestory\Vintagestory.exe

Report Id: 48bfd311-3c10-4041-b681-180a644c4203

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
--------------
{ TimeGenerated = 6/22/2022 8:28:17 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1561935616669702300, type 5
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.5.0
P3: 625674b5
P4: 86d0
P5: 134217728
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5AC0.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5AD0.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5AE1.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5AF1.tmp.txt
\\?\C:\Users\pgaff\AppData\Local\Temp\WER6011.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_Vintagestory.exe_f179f6a4610fc2ae518ff099abb911ea272189_1f70e3ae_0a88af32-11cc-4c85-a87c-aaf834206fa5

Analysis symbol: 
Rechecking for solution: 0
Report Id: 48bfd311-3c10-4041-b681-180a644c4203
Report Status: 268435456
Hashed bucket: 8da9a267396cd52695ad1c2af9a0d89c
Cab Guid: 0 }
--------------
{ TimeGenerated = 6/22/2022 8:27:53 PM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.16.5.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 2cd8

Start Time: 01d886b104005d00

Termination Time: 4

Application Path: G:\Vintagestory\Vintagestory.exe

Report Id: 94b6882d-4ae0-4bc3-b7c5-bc524076a7c1

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }

**Comment by copygirl** [comment] 2022-06-23 05:32
@maestrogaffney Your crash is not related to this issue. See #1901.

Also, going to close this issue for now.

**Closed by copygirl** 2022-06-23 05:32 UTC
Labels: status: incomplete
