### ISSUE TITLE
Last piece of pie doesn't give any saturation

### ISSUE THREAD

**Issue by Wonskaj** [anegostudios/VintageStory-Issues#4663] opened 2024-12-11 11:05 UTC
### Game Version

v1.20.0-rc 1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

While having two pieces of a pie left standing either on a table or a block if I only take one of them and leave the other for some time(not sure how long but definitely not spoiled) when I try to eat the last piece it give me 0 saturation. The issue doesn't happen if I take two last pieces into my inventory at the same time

### How to reproduce

1. Put a pie down
2. Take 3 pieces
3. Wait a few in game hours
4. Take last piece
5. Eat it

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2024-12-11 11:14
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/2117

**Closed by Craluminum2413** 2024-12-11 11:14 UTC
Labels: status: new
