### ISSUE TITLE
1.15 pre 7

### ISSUE THREAD

**Issue by SGTPHYSCO** [anegostudios/VintageStory-Issues#1068] opened 2021-06-25 20:15 UTC
**Game Version:** X.Y.Z
**Platform:** Windows / Mac / Linux (which?)
**Modded:** No / Yes (which?)

### Description
Explain the issue you're running into.

### How to reproduce
1. Make a '....'
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Paste crash here.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.

Note that the crash log contains all crashes that have happened so far.
You likely only want to report the latest one.
```

**Comment by SGTPHYSCO** [comment] 2021-06-25 20:21
Attemped to fire 4 plates, after lighting with torch immediately froze to this error.
Hope  Im posting this right.


 Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.0-pre.7 (Unstable)6/25/2021 4:09:15 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityPitKiln.IsAreaLoaded()
   at Vintagestory.GameContent.BlockEntityPitKiln.<>c__DisplayClass14_0.<Initialize>b__2(BlockPos pos)
   at Vintagestory.GameContent.BEBehaviorBurning.canBurn(BlockPos pos)
   at Vintagestory.GameContent.BEBehaviorBurning.OnFirePlaced(BlockPos firePos, BlockPos fuelPos, String startedByPlayerUid)
   at Vintagestory.GameContent.BlockEntityPitKiln.TryIgnite(IPlayer byPlayer)
   at Vintagestory.GameContent.BlockBehaviorCanIgnite.OnHeldInteractStop(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, EnumHandling& handling)
   at Vintagestory.API.Common.CollectibleObject.OnHeldInteractStop(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _tWLW0byDLIhtS1wxxVHI5lzRZDE._pYOg3eHClIOT1FF5vsNdyXdGM03(Single )
   at _6pW3IzjvlkXCwvQdAjU2jMcqPPaA._7YovFWQpW8u7nZERbVYDJRoxy6p(Single )
   at _6pW3IzjvlkXCwvQdAjU2jMcqPPaA._LsdcISpmOPNjHJfC7tNPJt4urmy(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _NfEIYGetj5nHaIEe1bMOq5qPVVe._uAPnYXwEzdCJ8CQ2oCBe9aHMUxo(_DqmInuVm7RykCDabuWwjzEo51Se , String[] )
   at _aLUPv552XTtNubHVap8iu7zzoZB._uAPnYXwEzdCJ8CQ2oCBe9aHMUxo(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 6/25/2021 3:30:25 PM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.15.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

**Comment by Craluminum2413** [comment] 2021-06-25 20:22
Duplicate of #1062 of course

**Comment by copygirl** [comment] 2021-06-25 20:23
Duplicate of #1062. However, thank you for reporting.

Seems like you accidentally created an issue that had no information. You can edit your own issues / comments.

**Closed by copygirl** 2021-06-25 20:23 UTC
Labels: status: duplicate
