### ISSUE TITLE
Bug 0x40000015

### ISSUE THREAD

**Issue by tsuna7777777** [anegostudios/VintageStory-Issues#4773] opened 2024-12-22 17:17 UTC
### Game Version

1.19.8

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

i crash everytime I launch the world.

### Logs

```Crash```Running on 64 bit Windows 10.0.22631.0 with 32694 MB RAM
Game Version: v1.19.8 (Stable)
22/12/2024 18:13:47: Critical error occurred
Loaded Mods: game@1.19.8, hudclock@3.4.0, creative@1.19.8, survival@1.19.8
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Common.InventoryNetworkUtil.UpdateSlotStack(ItemSlot slot, ItemStack newStack) in VintagestoryLib\Common\GameContent\Inventory\InventoryNetworkUtil.cs:line 492
   at Vintagestory.Common.InventoryNetworkUtil.UpdateFromPacket(IWorldAccessor resolver, Packet_InventoryContents packet) in VintagestoryLib\Common\GameContent\Inventory\InventoryNetworkUtil.cs:line 438
   at Vintagestory.Client.NoObf.ClientPlayer.AddOrUpdateInventory(ClientMain game, Packet_InventoryContents packet) in VintagestoryLib\Client\Model\ClientPlayer.cs:line 137
   at Vintagestory.Client.NoObf.ClientPlayer.UpdateFromPacket(ClientMain game, Packet_PlayerData packet) in VintagestoryLib\Client\Model\ClientPlayer.cs:line 159
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandlePlayerData(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 265
   at Vintagestory.Client.NoObf.ProcessPacketTask.ProcessPacket(Packet_Server packet) in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 448
   at Vintagestory.Client.NoObf.ProcessPacketTask.Run() in VintagestoryLib\Client\Systems\NetworkProcess.cs:line 442
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 776
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 313
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 22/12/2024 18:13:02, Site = , Source = Application Error, Message = Nom de l’application défaillante Vintagestory.exe, version : 1.19.8.0, horodatage : 0x661e0000
Nom du module défaillant : openal32.dll, version : 1.23.0.0, horodatage : 0x63dd31ad
Code d’exception : 0x40000015
Décalage d’erreur : 0x00000000000df046
ID du processus défaillant : 0x0x2330
Heure de début de l’application défaillante : 0x0x1db549470618500
Chemin d’accès de l’application défaillante : C:\Users\renan\AppData\Roaming\Vintagestory\Vintagestory.exe
Chemin d’accès du module défaillant: C:\Users\renan\AppData\Roaming\Vintagestory\Lib\openal32.dll
ID de rapport : fa2e460a-6e5f-4d56-9f64-4e2080c52e8c
Nom complet du package défaillant : 
ID de l’application relative au package défaillant :  }
--------------
{ TimeGenerated = 22/12/2024 18:09:41, Site = , Source = Application Error, Message = Nom de l’application défaillante VintageStory.exe, version : 1.19.8.0, horodatage : 0x661e0000
Nom du module défaillant : openal32.dll, version : 1.23.0.0, horodatage : 0x63dd31ad
Code d’exception : 0x40000015
Décalage d’erreur : 0x00000000000df046
ID du processus défaillant : 0x0x1cc0
Heure de début de l’application défaillante : 0x0x1db5494254f0dac
Chemin d’accès de l’application défaillante : C:\Users\renan\AppData\Roaming\Vintagestory\VintageStory.exe
Chemin d’accès du module défaillant: C:\Users\renan\AppData\Roaming\Vintagestory\Lib\openal32.dll
ID de rapport : 78a0901b-c098-4055-ab8f-2e86e98e4e68
Nom complet du package défaillant : 
ID de l’application relative au package défaillant :  }
--------------
{ TimeGenerated = 22/12/2024 18:08:32, Site = , Source = Application Error, Message = Nom de l’application défaillante Vintagestory.exe, version : 1.19.8.0, horodatage : 0x661e0000
Nom du module défaillant : openal32.dll, version : 1.23.0.0, horodatage : 0x63dd31ad
Code d’exception : 0x40000015
Décalage d’erreur : 0x00000000000df046
ID du processus défaillant : 0x0x3e94
Heure de début de l’application défaillante : 0x0x1db5493c882616c
Chemin d’accès de l’application défaillante : C:\Users\renan\AppData\Roaming\Vintagestory\Vintagestory.exe
Chemin d’accès du module défaillant: C:\Users\renan\AppData\Roaming\Vintagestory\Lib\openal32.dll
ID de rapport : dc491d91-4f73-46ff-902e-cfe1852841c6
Nom complet du package défaillant : 
ID de l’application relative au package défaillant :  }

**Comment by Craluminum2413** [comment] 2024-12-23 05:03
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4705

**Closed by Craluminum2413** 2024-12-23 05:03 UTC
Labels: status: new
