### ISSUE TITLE
Bone Soil disappears if Panned in Water

### ISSUE THREAD

**Issue by Desektion** [anegostudios/VintageStory-Issues#2095] opened 2022-08-07 13:39 UTC
**Game Version:** 1,17.0-rc.4
**Platform:** Windows 10   
**Modded:** No
**SP/MP:**  Only Tested in SP

### Description
Panning with Bone Soil that is placed inside of Water will cause it to disappear once it becomes layered. 

### How to reproduce
1. Put Bone Soil inside of Water
2. Use Wooden Pan on it
3. It disappears

### Expected behavior
Should turn into Layered Bone Soil (multiple uses of Panning)

### Screenshots
Here's a video :P
https://streamable.com/vy6dcf

**Comment by mrgeoffkat** [comment] 2022-08-07 18:13
I'm running 1.17rc-4 on my MP server and just checked bone soil pans like normal.  Hmmm.

**Comment by Upturnedthree** [comment] 2022-08-07 22:41
All panable blocks will wash away in water if you take a pan from them i do believe this is an intended feature. as once you have disturbed ground ie dug up a pan of soil or even just tilling it water will wash said disrupted soil much faster than the settled stuff

**Comment by Desektion** [comment] 2022-08-08 04:06
> 

I'm pretty sure that in the previous release candidate (rc.3) 
it was not this way and I cannot find in the changelog anything mentioning this as a feature or a change
Will re-install rc.3 and post if my memory is correct.

**Comment by Craluminum2413** [comment] 2022-08-08 08:13
The latest mention of fixing that bug was in [1.17.0-pre.3](https://info.vintagestory.at/v1dot17#:~:text=Fixed%3A%20Panning%20bony%20soil%20not%20working%20correctly)

**Comment by Craluminum2413** [comment] 2022-08-08 08:19
It looks like completely another bug that also affects all pannable blocks such as gravel, sand and bony soil

**Comment by wasakoki** [comment] 2022-08-09 12:25
for some more info this is how it (was supposed to) work in 1.16.5 according to the handbook but the 1.17.0-pre1 patchnotes mentioned removing the mechanic (i assume the blurb in the handbook entry was removed at this time too). i also could only reproduce this if 3 or all 4 of the sides of the block were exposed to water source blocks, otherwise it turned into a non-solid/submerged block as it's supposed to.

**Comment by tyronx** [comment] 2022-08-09 15:12
thanks for the report, this should be fixed in rc5

**Closed by tyronx** 2022-08-09 15:12 UTC
Labels: status: confirmed, priority: high
