### ISSUE TITLE
Audio Looping When Standing on Top of Reed Chests

### ISSUE THREAD

**Issue by Nova-07** [anegostudios/VintageStory-Issues#4654] opened 2024-12-10 21:34 UTC
### Game Version

v1.20.0

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

As in the title, when standing on the edge of a reed chest the placing (potentially stepping or jumping noise, I cannot tell due to the softness of the latter two) will loop indefinitely until you get off of the edge.

The only mods running at the time is https://mods.vintagestory.at/show/mod/16323, so I doubt that the two issues are related.

### How to reproduce

1] Stand on top of reed chest
2] get to the edge of the reed chest
3] The audio should begin to loop

### Screenshots

![2024-12-10_16-26-01](https://github.com/user-attachments/assets/4e54b92a-1db2-4828-9800-c6eca2ee42f6)
![2024-12-10_16-30-37](https://github.com/user-attachments/assets/50d36d6d-2d87-488e-8ff3-0875b7684149)

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2024-12-10 21:55
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4426

**Closed by Craluminum2413** 2024-12-10 21:55 UTC
Labels: status: new
