### ISSUE TITLE
Some chiseled block causes crash when login on server

### ISSUE THREAD

**Issue by dann1kid** [anegostudios/VintageStory-Issues#1659] opened 2022-01-30 19:12 UTC
**Game Version:** 1.16.1
**Platform:** Windows 
**Modded:** Yes 
**SP/MP:** Singleplayer 

### Description
You play as usual and after the game crashes and does not allow you to enter the server at all
 

### How to reproduce
make chiseled block and it may become to crashed chunk

### Expected behavior
Normal playing

### Screenshots
![unknown](https://user-images.githubusercontent.com/40342734/151713837-cd86516e-8ff8-461a-a0d4-caeff555d5cb.png)
![unknown (1)](https://user-images.githubusercontent.com/40342734/151713855-97e62ca7-7e93-4150-b809-9210b0c1b2b5.png)

### Logs
[message.txt](https://github.com/anegostudios/VintageStory-Issues/files/7966721/message.txt)

**Comment by copygirl** [comment] 2022-01-30 22:34
Closing as duplicate of #1623.

**Closed by copygirl** 2022-01-30 22:34 UTC
Labels: status: duplicate
