### ISSUE TITLE
1.18-pre6 Crashes when editing sign. (2nd different stacktrace in comments)

### ISSUE THREAD

**Issue by hlangeveld** [anegostudios/VintageStory-Issues#2467] opened 2023-03-12 13:56 UTC
Editing a sign. Repeating backspace. Crash.

Playing on Shalecreek server multiplayer 1.18-pre6 with non-basegame Mods: 
* moretraders@0.0.1,
* primitivesurvival@3.1.4
* stackables@2.0.5
* translocatorengineeringredux@1.4.0
* carryon@0.11.0-pre.1
* morebags@1.2.0
* prospectorinfo@4.1.2
* workbenchexpansion@1.6.0-pre.1

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.0-pre.6 (Unstable)
12/03/2023 14:42:00: Critical error occurred
Loaded Mods: moretraders@0.0.1, primitivesurvival@3.1.4, stackables@2.0.5, translocatorengineeringredux@1.4.0, game@1.18.0-pre.6, carryon@0.11.0-pre.1, morebags@1.2.0, prospectorinfo@4.1.2, creative@1.18.0-pre.6, survival@1.18.0-pre.6, workbenchexpansion@1.6.0-pre.1
System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Vintagestory.API.Client.GuiElementEditableTextBase.OnKeyBackSpace() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 536
   at Vintagestory.API.Client.GuiElementEditableTextBase.OnKeyDown(ICoreClientAPI api, KeyEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 404
   at Vintagestory.API.Client.GuiComposer.OnKeyDown(KeyEvent args, Boolean haveFocus) in VintagestoryApi\Client\UI\GuiComposer.cs:line 564
   at Vintagestory.API.Client.GuiDialog.OnKeyDown(KeyEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 416
   at Vintagestory.Client.NoObf.GuiManager.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 361
   at Vintagestory.Client.NoObf.ClientMain.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1711
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(Object sender, KeyboardKeyEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 250
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.NativeWindowBase.OnKeyDown(Key key, Boolean repeat) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\NativeWindowBase.cs:line 130
   at OpenTK.Platform.Windows.WinGLNative.HandleKeyboard(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 646
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 828
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1551
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 369
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by hlangeveld** [comment] 2023-03-12 16:24
Related bug in editing sign text in single player

Enter
```long long long long
long text|```

Press backspace four times and is shows like:

```long long long long
 long ```

Press it twice more, and we get:
```long long long long lon```

With the cursor dangling below the ng of the first `long`

At this point I tried something else: I enter `g`, the last character to have been removed.

This crashes the game.

If instead, I press another backspace, the cursor jumps straight up into the first `lon|g`

**Comment by hlangeveld** [comment] 2023-03-12 16:26
![image](https://user-images.githubusercontent.com/1230736/224558202-073f072f-a65c-42a3-98f5-80682b003bbb.png)

**Comment by hlangeveld** [comment] 2023-03-12 16:30
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.0-pre.6 (Unstable)
12/03/2023 17:13:08: Critical error occurred
Loaded Mods: game@1.18.0-pre.6, creative@1.18.0-pre.6, survival@1.18.0-pre.6
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Vintagestory.API.Client.GuiElementEditableTextBase.OnKeyPress(ICoreClientAPI api, KeyEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 558
   at Vintagestory.API.Client.GuiComposer.OnKeyPress(KeyEvent args) in VintagestoryApi\Client\UI\GuiComposer.cs:line 615
   at Vintagestory.API.Client.GuiDialog.OnKeyPress(KeyEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 452
   at Vintagestory.Client.NoObf.GuiManager.OnKeyPress(KeyEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 383
   at Vintagestory.Client.NoObf.ClientMain.OnKeyPress(KeyEvent eventArgs) in VintagestoryLib\Client\ClientMain.cs:line 1773
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyPress(Object sender, KeyPressEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 239
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.HandleChar(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 413
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 771
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1551
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 369
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by tyronx** [comment] 2023-03-18 14:08
i'm not able to reproduce the backspace crash unfortunately

**Comment by tyronx** [comment] 2023-03-18 17:49
oh, i was able to now

**Comment by tyronx** [comment] 2023-03-18 19:34
thanks for the reports, both should be fixed next release

**Closed by tyronx** 2023-03-18 19:34 UTC

**Comment by hlangeveld** [comment] 2023-03-19 14:59
Confirmed that crash has been resolved in -pre7

There still appears to be a minor issue with text getting lost after word wrap.
