### ISSUE TITLE
Crash on death caused by multiblock interaction?

### ISSUE THREAD

**Issue by TheMadSpider** [anegostudios/VintageStory-Issues#1886] opened 2022-05-04 21:58 UTC
Game Version: 1.16.5
Platform: Windows
Modded: No
SP/MP: Multiplayer

Description
was fighting a drifter during a temporal storm, died and the game crashed as i died, loaded back into the server, no gear in inventory or dropped onto the floor right where i died, thus deleting all my equipment.

How to reproduce
unable to reproduce currently

 Expected behaviour
all inventory to drop to the floor upon death

Screenshots
N/A

Logs

```
Game Version: v1.16.5 (Stable)
Loaded Mods: game@1.16.5, creative@1.16.5, survival@1.16.5
04/05/2022 22:34:05: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockMultiblock.OnBlockInteractCancel(Single secondsUsed, IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel, EnumItemUseCancelReason cancelReason)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnGameTick(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _esGsESICkihAc8ShXuIoQwZFwP4._lPY9uZeagiMGC6tvSE11dF7naaz(Single )
   at _8UC8FAMhwKY89IbtSRDjsNSApPJ._KbwUAfxjCHyIG0aK445AAA9FHl5(Single )
   at _8UC8FAMhwKY89IbtSRDjsNSApPJ._R0wAt2N0TpONMxGD0HJG3bDrRcI(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _7zNxEbLnuy6Bq08TdMSIu9ZbrKf._vvUTh6X5xLRNnjtX2xSE7z8yMeh(_SUsdg1ytavxaRcNNkhfDrODGhGP , String[] )
   at _yA4PJazdKq1OMm8H6js6v5AhQB._vvUTh6X5xLRNnjtX2xSE7z8yMeh(ThreadStart )
```

**Comment by copygirl** [comment] 2022-05-05 05:17
I think your items being gone is just an unfortunate side effect of the timing of the crash. There is the possibility of your player data (after losing your items) being saved before the chunks were saved, which contained the dropped items.

The crash mentions a multiblock. Do you have any idea what it could be talking about here?

**Comment by TheMadSpider** [comment] 2022-05-08 22:10
the server did not crash itself at all, it was completely fine when even after it happened, i did have a mining bag on me for the first time filled with stuff when it crashed. that was the first crash to ever have after i started using it.

**Comment by sirStroam** [comment] 2022-06-28 20:32
Closing due to being a single unreproducible report.

**Closed by sirStroam** 2022-06-28 20:32 UTC
Labels: status: incomplete
