### ISSUE TITLE
get this when ever i try to join a game 

### ISSUE THREAD

**Issue by Oke518** [anegostudios/VintageStory-Issues#2076] opened 2022-07-30 16:38 UTC
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.0-rc.2 (Unstable)
Loaded Mods: ancienttools@1.4.5, blacksmithname@1.0.5, composter@1.0.4, extraclayforming@1.0.0, gwb@1.0.1, pieontheshelf@1.0.0, potontheshelf@1.0.0, rackablefirestarter@1.0.0, sortablestorage@1.4.0, game@1.17.0-rc.2, vsquest@0.0.3, egocaribautomapmarkers@2.4.0-pre.1, fixhandbookclutter@1.0.5, lc@1.0.0, petai@1.5.2, ruinvariants@1.0.1, useplanksinpitkiln@1.0.0, creative@1.17.0-rc.2, survival@1.17.0-rc.2, vsvillage@0.2.2, cats@1.5.1, tradercamps@1.0.1, wolftaming@1.5.2
7/30/2022 12:22:58: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.ClientMain.ProcessServerReady() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:line 1923
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:line 1138
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 381
   at Vintagestory.Client.ScreenManager.Render(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:line 704
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:line 608
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 125
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 87
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 7/27/2022 14:08:23, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at Vintagestory.Common.ModCompilationContext..ctor()
   at Vintagestory.Common.ModLoader..ctor(Vintagestory.API.Common.ICoreAPI, Vintagestory.API.Common.EnumAppSide, Vintagestory.API.Common.ILogger, System.Collections.Generic.IEnumerable`1<System.String>, Boolean)
   at Vintagestory.Client.ScreenManager.loadMods()
   at Vintagestory.Client.ScreenManager.<DoGameInitStage4>b__52_0()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
--------------
{ TimeGenerated = 7/3/2022 23:54:18, Site = , Source = Windows Error Reporting, Message = Fault bucket 1381417961401207149, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.5.0
P3: 10.0.19044.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\MICHAE~1\AppData\Local\Temp\RDR89CF.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER89F0.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8A00.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8A2D.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8A4D.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: ff00c5c7-2c8c-4cc1-84b6-662ce4d007ea
Report Status: 268435456
Hashed bucket: 6ce2bbf81ba2523d132bc8511ba9c96d
Cab Guid: 0 }
--------------
{ TimeGenerated = 4/28/2022 14:39:58, Site = , Source = Windows Error Reporting, Message = Fault bucket 1381417961401207149, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.5.0
P3: 10.0.19044.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\MICHAE~1\AppData\Local\Temp\RDR9216.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9237.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9247.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9274.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER92B4.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: ec211b3c-f319-4223-89c2-098559857b2c
Report Status: 268435456
Hashed bucket: 6ce2bbf81ba2523d132bc8511ba9c96d
Cab Guid: 0 }

**Comment by Craluminum2413** [comment] 2022-07-30 16:42
Duplicate of #2046

**Closed by Craluminum2413** 2022-07-30 16:42 UTC
Labels: status: new
