### ISSUE TITLE
Metal Trapdoors hitbox updates incorrectly and sounds like a wooden door

### ISSUE THREAD

**Issue by pizza2004** [anegostudios/VintageStory-Issues#4102] opened 2024-09-18 20:56 UTC
### Game Version

v1.20.0 pre-1

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

When opening and closing the new iron trapdoor it is not properly updating the hitbox to show the new area.

The material is also wood.  And they can only be placed in one specific orientation although maybe that is intended.

### How to reproduce

Just place down an iron trapdoor in the world and interact with it.

### Logs

```Log```

**Comment by RedramVS** [comment] 2024-09-18 22:03
I've updated the material (and also made them craftable).  The orientation thing will take someone more skilled that me to resolve.

**Comment by Craluminum2413** [comment] 2024-09-30 11:48
Fixed in pre.4

**Comment by pizza2004** [comment] 2024-10-03 08:04
It is not fixed in pre.4, as the hitbox still does not update correctly.

**Comment by Craluminum2413** [comment] 2024-10-03 08:47
@pizza2004 Can't reproduce

**Comment by Craluminum2413** [comment] 2024-10-03 08:48
Ok reproduced with metal trapdoors

**Comment by Craluminum2413** [comment] 2024-10-03 08:56
@RedramVS Fix is the same as for wooden trapdoor, just make wooden trapdoor match metal trapdoor json, also there is handbook typo in metal trapdoor

**Comment by pizza2004** [comment] 2024-10-21 04:49
Metal Trapdoors should also probably have the sounds changed to match the iron door.

**Comment by pizza2004** [comment] 2024-11-22 16:25
The JSON file also has combustibleProps when it shouldn't, clearly copied from the wood file.  Same with the other metal doors (except the iron door) actually.

**Comment by tyronx** [comment] 2024-12-13 17:56
thanks for the report, this will be fixed in rc2

**Closed by tyronx** 2024-12-13 17:56 UTC
Labels: status: in-progress, priority: high, department: json, version: 1.20
