### ISSUE TITLE
sTUCK IN ANIMATION

### ISSUE THREAD

**Issue by poster39** [anegostudios/VintageStory-Issues#3809] opened 2024-04-14 08:17 UTC
### Game Version

1.19.7

### Platform

Windows

### Modded

None

### SP/MP

Multiplayer

### Description

Stuck in last animation.

### How to reproduce

I'm playing on the offcial MP servser and notice there's a bug that causes the character to be stuck in animation.
When prospecting, I will first shovel 4 dirt layers and then when I hit rock I will press the key on my keybaord ro quickly switch to my pros pick all while holding down my mouse button. This is have my character be stuck in a shovel animation. If standing still, it will do the shovel anim. If dong something else it will do that respective animation AND the shovel animation. Same goes for drowning. 

When taking hits while drowning it also getes stuck in the "getting damage" animation even if not taking damage anymore. Not sure how you can trigger that one. But last I was skinning an horned goat underwater when ity happened.

### Logs

no logs available

**Comment by Craluminum2413** [comment] 2024-04-14 08:27
Duplicate of #3774

**Closed by Craluminum2413** 2024-04-14 08:27 UTC
Labels: status: new
