### ISSUE TITLE
Hole in Ground/Chunk issue

### ISSUE THREAD

**Issue by BabySnakes101** [anegostudios/VintageStory-Issues#4649] opened 2024-12-10 06:15 UTC
### Game Version

v1.20.0-rc.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

`  "WorldConfig": {
    "Seed": "76567566669099",
    "SaveFileLocation": "----",
    "WorldName": "Name",
    "AllowCreativeMode": true,
    "PlayStyle": "wildernesssurvival",
    "PlayStyleLangCode": "preset-wildernesssurvival",
    "WorldType": "standard",
    "WorldConfiguration": {
      "gameMode": "survival",
      "startingClimate": "temperate",
      "spawnRadius": "100",
      "graceTimer": "0",
      "deathPunishment": "drop",
      "droppedItemsTimer": "600",
      "seasons": "enabled",
      "playerlives": "-1",
      "lungCapacity": "40000",
      "daysPerMonth": "9",
      "harshWinters": "true",
      "blockGravity": "sandgravelsoil",
      "caveIns": "on",
      "allowUndergroundFarming": false,
      "noLiquidSourceTransport": false,
      "bodyTemperatureResistance": "5",
      "creatureHostility": "aggressive",
      "creatureStrength": "1.5",
      "creatureSwimSpeed": "2",
      "playerHealthPoints": "15",
      "playerHungerSpeed": "1",
      "playerHealthRegenSpeed": "1",
      "playerMoveSpeed": "1.5",
      "foodSpoilSpeed": "1.25",
      "saplingGrowthRate": "1",
      "toolDurability": "1",
      "toolMiningSpeed": "1",
      "propickNodeSearchRadius": "6",
      "microblockChiseling": "stonewood",
      "allowCoordinateHud": false,
      "allowMap": true,
      "colorAccurateWorldmap": false,
      "loreContent": true,
      "clutterObtainable": "ifrepaired",
      "lightningFires": false,
      "allowTimeswitch": false,
      "temporalStability": true,
      "temporalStorms": "sometimes",
      "tempstormDurationMul": "1",
      "temporalRifts": "visible",
      "temporalGearRespawnUses": "20",
      "temporalStormSleeping": "0",
      "worldClimate": "realistic",
      "landcover": "1",
      "oceanscale": "1",
      "upheavelCommonness": "0.3",
      "geologicActivity": "0.05",
      "landformScale": "1.0",
      "worldWidth": "2048000",
      "worldLength": "1024000",
      "worldEdge": "traversable",
      "polarEquatorDistance": "100000",
      "globalTemperature": "1",
      "globalPrecipitation": "1",
      "globalForestation": "0",
      "globalDepositSpawnRate": "1",
      "surfaceCopperDeposits": "0.12",
      "surfaceTinDeposits": "0.007",
      "snowAccum": "true",
      "allowLandClaiming": false,
      "classExclusiveRecipes": true,
      "auctionHouse": true
    },
    "MapSizeY": 256,
    "CreatedByPlayerName": "BabySnakes",
    "DisabledMods": [],
    "RepairMode": false
  },`
  

  Occurred after a player crashed while exploring. Seems to be a chunk issue.
  

### How to reproduce

Not completely sure how reproduceable it is, however the seed and location is provided.

### Screenshots

![image](https://github.com/user-attachments/assets/bd6d445b-64fa-4725-857c-712a00cfe924)
![image](https://github.com/user-attachments/assets/3ed6a2fd-db9a-44df-b2d0-1e6474b35756)

### Logs

![image](https://github.com/user-attachments/assets/5593827e-90e5-4d95-926e-8f43dd372d94)

**Comment by tannyl** [comment] 2024-12-10 10:00
I have come across this while playing in v1.19.8 as well. Don't have any more info at the moment about it, but it does not seem to be specifically related to changes v1.20.

**Comment by BabySnakes101** [comment] 2024-12-10 14:12
> I have come across this while playing in v1.19.8 as well. Don't have any more info at the moment about it, but it does not seem to be specifically related to changes v1.20.

Do you know if this issue can be fixed without making a new world? For example regenerating the chunk?

**Comment by tannyl** [comment] 2024-12-10 19:36
@BabySnakes101, no I have not tried to fix it that time I had it happen. But it would be worth giving it a shot and regenerating that area. If the chunk is still missing after that, this could help the devs narrow down what code they need to look at. If you wanna try it, do remember to create a backup of the world first.

**Comment by Bughaw** [comment] 2024-12-11 00:49
I had this happen in 1.20.0rc1 as well.  Same hole in the map and world.  Not sure how it happened.  I'll backup the save so it can be provided if helpful.  I'm running rivers mod, not sure if that matters.
![screenshot](https://github.com/user-attachments/assets/768a783c-7bbe-4210-8de1-b6e8bdc98a81)

**Comment by Bughaw** [comment] 2024-12-11 00:55
There is also a weird barrier around the hole in my world, as if I reached the world border.

**Comment by BabySnakes101** [comment] 2024-12-11 02:06
> There is also a weird barrier around the hole in my world, as if I reached the world border.

Yeah, same here, can't jump in

**Comment by tannyl** [comment] 2024-12-11 13:33
The hole I got back in v1.19.8 did not stop me from falling down into it.

**Comment by radfast** [comment] 2024-12-11 18:28
Thanks for the reports.  The specific cause of the one seen in the OP is now fixed in upcoming 1.20-rc.2 - the same position in the same savegame should now load correctly.

For the other people experiencing similar issues, it's hard to know the cause without seeing logs.  In every case, something must be in logs as a "Server Error" or similar, at around the time the game tried to load the relevant chunk (which may be many minutes before you saw it, it depends how the player is moving, the game will always be loading chunks beyond the edge of your vision).  While the game is still considered 'Early Access' (although super full of great content IMHO), it's kind of intended that if something has gone wrong and been logged it should also be visibly wrong in-game.  I mean: if you see this type of issue, please do look in logs for the reported error, create a Github issue with the reported error, and then devs can fix the true cause of the problem.

**Closed by radfast** 2024-12-11 18:28 UTC
Labels: status: resolved, department: code
