### ISSUE TITLE
Granite cobblestone: chiseled blocks aren't localized

### ISSUE THREAD

**Issue by Damglador** [anegostudios/VintageStory-Issues#4841] opened 2024-12-31 00:25 UTC
### Game Version

v1.19.8

### Platform

Linux

### Modded

Modded

### SP/MP

None

### Description

Granite cobblestone is translated and available on [Crowdin](https://uk.crowdin.com/editor/vintage-story-game/2/en-uk?view=comfortable#1386), and full granite cobblestone blocks are translated in the game, not full ones are not. 

### How to reproduce

1. Switch to language where granite cobblestone is translated (in my case, Ukrainian) 
2. Find a granite cobblestone ruin (?), at least that's how I found out about the issue

### Screenshots

![Знімок 2024-12-31 01:03:32](https://github.com/user-attachments/assets/279ca296-6e36-46c2-9f29-9a4b10650f34)

**Comment by Damglador** [comment] 2024-12-31 00:37
I think the same thing applies to many or even all blocks, I also found: Cracked granite, aged wooden planks, granite rock

**Comment by pizza2004** [comment] 2024-12-31 03:07
Are you playing in single player or multiplayer?

**Comment by radfast** [comment] 2024-12-31 08:11
Duplicate of #4585

**Closed by radfast** 2024-12-31 08:11 UTC
Labels: status: duplicate
