### ISSUE TITLE
[1.20.0-pre.4] Crash after sleeping

### ISSUE THREAD

**Issue by MonsterHorns** [anegostudios/VintageStory-Issues#4224] opened 2024-10-04 11:58 UTC
### Game Version

v1.20.0-pre.4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Game crashes after sleeping:

```
Running on 64 bit Windows 10.0.19044.0 with 10217 MB RAM
Game Version: v1.20.0-pre.4 (Unstable)
04/10/2024 15:50:31: Critical error occurred
Loaded Mods: game@1.20.0-pre.4, creative@1.20.0-pre.4, survival@1.20.0-pre.4
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.API.MathTools.SimplexNoiseOctave.Evaluate(Double x, Double y, Double z) in VintagestoryApi\Math\Noise\SimplexOctave.cs:line 414
   at Vintagestory.API.MathTools.SimplexNoise.Noise(Double x, Double y, Double z) in VintagestoryApi\Math\Noise\SimplexNoise.cs:line 117
   at Vintagestory.GameContent.WeatherPattern.RegenCloudTileCache(Vec3i tileOffset) in VSEssentials\Systems\Weather\Model\Impl\WeatherPattern.cs:line 89
   at Vintagestory.GameContent.WeatherDataReaderBase.ensureCloudTileCacheIsFresh(Vec3i tilePos) in VSEssentials\Systems\Weather\WeatherDataReader.cs:line 275
   at Vintagestory.GameContent.CloudRenderer.UpdateCloudTilesOffThread(Int32 changeSpeed) in VSEssentials\Systems\Weather\CloudRenderer.cs:line 390
   at Vintagestory.GameContent.CloudRenderer.<.ctor>b__31_2() in VSEssentials\Systems\Weather\CloudRenderer.cs:line 166
```

### How to reproduce

1. Sleep in bed
2. Sometimes the game crashes

### Logs

[client-main.log](https://github.com/user-attachments/files/17257839/client-main.log)

**Comment by Craluminum2413** [comment] 2024-10-04 12:01
Duplicate of #4166

**Closed by Craluminum2413** 2024-10-04 12:01 UTC
Labels: status: new
