### ISSUE TITLE
1.15.0-pre8: System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ss-gnalvesteffer** [anegostudios/VintageStory-Issues#1074] opened 2021-06-26 22:50 UTC
**Game Version:** 1.15.0-pre8
**Platform:** Windows
**Modded:** No

### Description
I was playing on the official preview server and my game crashed.

### Logs
```
Running on 64 bit Windows with 64 GB RAM 
Version: v1.15.0-pre.8 (Unstable)2021-06-26 5:46:30 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Common.BlockAccessorBase.SetDecorsBulk(Int64 chunkIndex, Dictionary`2 newDecors)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _VQ30Ln02gyvoATEl8PlfeLVSgEr._B7JNvwI3nx9QEdgkJkgLg21lvde(Single )
   at _IJG2v0zGeUDfPbxVmwnXgzVbdHp._pSnRqX9ORNtB1LvHF1vzxnB3jpe(Single )
   at _IJG2v0zGeUDfPbxVmwnXgzVbdHp._g3nxKDmkyYJ7Dq7TaDsdBSLVw0A(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _yLUmmGhRYnnQv7zul2v0crZd2Tp._PwL995m4VTOZDErzGUzsRHij9rh(_rhrdlgKC766AwXQivHTdHkcGzAjb , String[] )
   at _EDKdxfQFQqcYQ64nBo1IPHJ5Kw9._PwL995m4VTOZDErzGUzsRHij9rh(ThreadStart )
-------------------------------

```

**Comment by copygirl** [comment] 2021-06-26 22:57
Duplicate of #1072, should be fixed in 1.15.0-pre.9. Let us know if that's not the case.

**Closed by copygirl** 2021-06-26 22:57 UTC
Labels: status: duplicate
