### ISSUE TITLE
Long Pause when closing menu

### ISSUE THREAD

**Issue by EarthwormO** [anegostudios/VintageStory-Issues#447] opened 2020-03-06 16:24 UTC
**Game Version:** 1.12.6
**Platform:** Windows 64
**Modded:** No 

### Description
When Pausing Single Player via hitting Escape to bring up the menu.  If you leave the menu open for a long time, like 5 minutes or more.  When Leaving the menu to get back to the game a long freeze occurs.  This seems to be dependent on the length of time the menu was open for pausing.  The longer the menu was open, the longer the freeze.  Seems like a longer freeze if fire is on screen, but that may not be true.

### How to reproduce
1. Get into a game, possibly have things built (Seemed to happen more the longer I played)
2. Hit escape, go do something else for a bit, at least 5 minutes.
3. Try and exit the menu

### Expected behavior
Get right back into the action.

```

**Comment by Bloodsaw** [comment] 2020-03-06 16:27
Duplicate of #330 
Please add your client-main.txt and server-main.txt in the mentioned issue.
You will find the logs in `%APPDATA%` and then `VintageStoryData\Logs`

**Closed** 2020-03-06 16:28 UTC
Labels: status: duplicate
