### ISSUE TITLE
NullReferenceException ClientAnimator

### ISSUE THREAD

**Issue by WickedSchnitzel** [anegostudios/VintageStory-Issues#4425] opened 2024-11-03 00:58 UTC
### Game Version

1.20.0-pre.9

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Game was crashing while i was reading an npc dialog.

### Logs

Running on 64 bit Windows 10.0.19045.0 with 32723 MB RAM
Game Version: v1.20.0-pre.9 (Unstable)
03.11.2024 01:55:00: Critical error occurred
Loaded Mods: aculinaryartillery@1.2.1, ancientarmory@1.0.5, bettercrates@1.7.1, chiseltools@1.12.10, decor@1.1.6, extrachests@1.8.0, fantasycreatures@0.7.1, fixedpaths@1.0.1, pantherinae@1.1.12, foundrymod@1.0.0, moreicons_cs@1.1.0, primitivesurvival@3.7.0, nvscaffolding@1.0.1, translocatorengineeringredux@1.5.4, game@1.20.0-pre.9, weaponpackalphaunoff@1.5.1, animalcages@3.0.3, betterruins@0.3.7, butterflycases@1.0.1, carryon@1.8.0-pre.1, commonlib@2.5.0-rc.2, decayingcreatures@0.0.8, expandedfoods@1.7.2, fairplayguardian@1.1.7, furniturelibrary@1.0.13, heatretention@1.0.2, playerlist@2.1.4, simplefootstepsredux@1.0.1, sleepvote@1.0.7, tentbag@2.1.3, thecritterpack@0.9.1, vanity@2.2.1, vinconomy@0.3.4, creative@1.20.0-pre.9, vsquest@1.2.0, vsserverpanel@0.1.5, survival@1.20.0-pre.9, cob2@1.6.8, cobserver@1.0.2, em@3.0.0-pre.1, outerspacetunesvolume1@1.0.2, outerspacetunesvolume2@1.0.2, playercorpse@1.10.1-rc.1, rifteye@0.3.7, stonequarry@3.4.0, cob@1.9.9, outerspacetunesmaster@1.0.2
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.ClientAnimator.calculateMatrices(Single dt) in VintagestoryApi\Common\Model\Animation\ClientAnimator.cs:line 294
   at Vintagestory.API.Common.AnimatorBase.OnFrame(Dictionary`2 activeAnimationsByAnimCode, Single dt) in VintagestoryApi\Common\Model\Animation\AnimatorBase.cs:line 109
   at Vintagestory.API.Common.AnimationManager.OnClientFrame(Single dt) in VintagestoryApi\Common\Model\Animation\AnimationManager.cs:line 430
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 74
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 819
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 825
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 741
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 207
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 31.10.2024 19:56:39, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.20.0.0, Zeitstempel: 0x66470000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x4508
Startzeit der fehlerhaften Anwendung: 0x01db2bc622d88b0e
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Kai\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: d8155287-a7c1-4cbb-82ca-42e6cc0a59be
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 17.10.2024 19:30:22, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.20.0.0, Zeitstempel: 0x66470000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x3300
Startzeit der fehlerhaften Anwendung: 0x01db20ba2c298678
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Kai\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: 213536ca-7d0c-426c-9a1f-adbe2d1be7a7
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }
--------------
{ TimeGenerated = 05.10.2024 19:27:55, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.20.0.0, Zeitstempel: 0x66470000
Name des fehlerhaften Moduls: openal32.dll, Version: 1.23.0.0, Zeitstempel: 0x63dd31ad
Ausnahmecode: 0x40000015
Fehleroffset: 0x00000000000df046
ID des fehlerhaften Prozesses: 0x108
Startzeit der fehlerhaften Anwendung: 0x01db174bd557cd11
Pfad der fehlerhaften Anwendung: C:\Users\Kai\AppData\Roaming\Vintagestory\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Users\Kai\AppData\Roaming\Vintagestory\Lib\openal32.dll
Berichtskennung: c5c178d4-7c88-4521-8c4b-e03ddf588682
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }

**Comment by Craluminum2413** [comment] 2024-11-03 11:16
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4243

**Closed by Craluminum2413** 2024-11-03 11:16 UTC
Labels: status: new
