### ISSUE TITLE
mac  rendering everything brown and red as blue

### ISSUE THREAD

**Issue by onyxsoda** [anegostudios/VintageStory-Issues#4622] opened 2024-12-08 14:28 UTC
### Game Version

1.20

### Platform

Mac

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

when i downloaded the new version the game rendered everything  brown and red to blue.
the crash log is from the water crashing bug when you go under water, but i hope it can give you any insight about the issue.

### How to reproduce

1,download it on mac

### Screenshots

<img width="1680" alt="Screenshot 2024-12-06 at 3 01 19 PM" src="https://github.com/user-attachments/assets/80070c98-75a7-4aaf-b3e0-663beb8dbb39">
<img width="1680" alt="Screenshot 2024-12-06 at 3 01 08 PM" src="https://github.com/user-attachments/assets/a211895a-fb3a-4067-b15d-86d2bfd02725">
<img width="1680" alt="Screenshot 2024-12-06 at 3 00 59 PM" src="https://github.com/user-attachments/assets/ed89b003-ee09-4aaf-a202-aa743f414085">

### Logs

Game Version: v1.20.0-rc.1 (Unstable)
12/6/2024 2:55:14PM: Critical error occurred
Loaded Mods: game@1.20.0-rc.1, creative@1.20.0-rc.1, survival@1.20.0-rc.1
System.Exception: This OpenAL function could not be loaded. This likely means that this extension isn't present in the current context.
   at OpenAL_AL_Extension_Null_GetProcAddress_Exception_Delegate_51e73be9-7cca-41ce-957e-483af6564519(Int32, Int32&)
   at OpenTK.Audio.OpenAL.ALC.EFX.DeleteFilters(Int32 count, Int32& filters)

**Comment by Craluminum2413** [comment] 2024-12-08 15:16
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4327

**Closed by Craluminum2413** 2024-12-08 15:16 UTC
Labels: status: new
