### ISSUE TITLE
keeps crashing windows 10

### ISSUE THREAD

**Issue by Exodiusk** [anegostudios/VintageStory-Issues#295] opened 2019-05-14 19:29 UTC
```
Running on 64 bit Windows with 4 GB RAM 
Version: v1.9.3 (Stable)5/14/2019 3:27:33 PM: Critical error occurred
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.MemoryStream.InternalReadInt32()
   at Vintagestory.API.Common.EntityAgent.FromBytes(BinaryReader reader, Boolean forClient)
   at _gbFD3yYlRfBk1tqchEM6hob48Vj._4IUcF6SqRSUejpjlt05JUg2Bb4j(_KYxNu4d2OW6yqTN3KdJcfo89cyI )
   at _PndAABz6mbLrIVY3bGkjFENAKYE._u2KBdQ1YadwFfy9QyaDloxApjuq(Single )
   at _NkoWRZbO8vbo2P0bHOmeWW5HFZm._VuoWA1NI32ePh577QetkPcWgv1j(Single )
   at _ClwmnLe1V7vR8n56XkbHz2NmshG._v6KGki9QaYXffAVL8MxroiYvLHZ(Single )
   at _ClwmnLe1V7vR8n56XkbHz2NmshG._bWLdqbxl84dj0WzW4hexmUSwPWP(Single )
   at _mEhEzZ8DmIQe7K9d4tBswO1fhgX._0oOO2PQajHpBpSzMJCyLMiw7tG(Object , FrameEventArgs )
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _3vfvgrHj6ymQxm8FJtx4Ruzypih._Z3lNUjeecYm8PMLFsAqAg3ack5w(_mmIyrGEQIkHEG3raFL54FrKNncQ , String[] )
   at _VPmpDmTQc9Jyy6X2oS97VHCLE8A._Z3lNUjeecYm8PMLFsAqAg3ack5w(ThreadStart )
-------------------------------
```

**Comment by tyronx** [comment] 2019-05-14 19:33
oh wow, wicked. Can you describe when that happens?
Does it also crash on a new world?

**Comment by Exodiusk** [comment] 2019-05-14 19:41
> 
> 
> oh wow, wicked. Can you describe when that happens?
> Does it also crash on a new world?

it basically just started today and for one thing....the game freezes every couple seconds and for another it just crashes out of nowhere upon starting up existing worlds...never had this problem till today and got worse upon 1.9.3 update. haven't tried a new world yet.

**Comment by tyronx** [comment] 2019-05-14 19:51
Can you upload me your savegame somewhere? I think its something in your world thats causing the issues.

**Comment by Exodiusk** [comment] 2019-05-14 19:51
alright....how should i send it to you?

**Comment by Exodiusk** [comment] 2019-05-14 19:53
and how do i get the savegame?

**Comment by tyronx** [comment] 2019-05-14 19:55
For example via https://wetransfer.com/

The savegame is in %appdata%/VintagestoryData/Saves  (you can get near to that folder when you click 'Open Mods Folder' in the mod manager)

**Comment by Exodiusk** [comment] 2019-05-14 19:58
here's the link: https://we.tl/t-6V2PON7wIY

**Comment by copygirl** [comment] 2019-05-14 19:59
How safe are saves from a crash during saving, bluescreen, power outage, ... by the way?

**Comment by tyronx** [comment] 2019-05-14 20:02
As safe as sqlite3 is, which claims to be pretty robust against those cases.

**Comment by Exodiusk** [comment] 2019-05-14 20:06
any luck?

**Comment by tyronx** [comment] 2019-05-14 20:06
Oh, you are on one or several mods, right?

**Comment by Exodiusk** [comment] 2019-05-14 20:07
one yeah

**Comment by tyronx** [comment] 2019-05-14 20:10
the neolithic mod?

**Comment by Exodiusk** [comment] 2019-05-14 20:11
yes

**Comment by Exodiusk** [comment] 2019-05-14 20:11
even with it disabled it was still crashing

**Comment by Exodiusk** [comment] 2019-05-14 20:28
any updates? tryna play lol

**Comment by copygirl** [comment] 2019-05-14 20:54
Please be patient. Game development and debugging takes a lot of time and effort. Tyron is looking into this and might even personally fix your world save, if he can.

**Comment by Exodiusk** [comment] 2019-05-14 20:56
Haha sorry lol. Currently writing a rather large suggestion as well for this amazingly beautiful game. I find it like a revolutionary minecraft that we've all been waiting for. Thanks!

**Comment by tyronx** [comment] 2019-05-15 10:24
Hm, unfortunately I cannot reproduce the crash using `VS-1.9.3-TheNeolithicMod-1.6.12`. 

There are lots of errors thrown in the log files, but these seem to be caused by the mod, not the vanilla game. Either way it feels like this crash could be cause by the neolithic mod writing corrupt entity data which is then sent to the client causing the crash. The creators of the the neolithic mod should look at this.

**Comment by Novocain1** [comment] 2019-05-15 10:32
With The Neolithic Mod enabled you will have to create a new world, your crash is caused by trying to use The Neolithic Mod on a vanilla world

**Comment by tyronx** [comment] 2019-05-15 10:37
In a near future version we should be able to prevent such mixup from happening

**Comment by copygirl** [comment] 2020-03-05 19:17
Closing as duplicate in favor of #390.

**Closed by copygirl** 2020-03-05 19:17 UTC
Labels: status: duplicate
