### ISSUE TITLE
Re: Distillery. Sleeping increases fuel consumption rate, but not production.

### ISSUE THREAD

**Issue by zbliss92** [anegostudios/VintageStory-Issues#4398] opened 2024-10-30 20:07 UTC
### Game Version

v1.19.8

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Fuel consumption rate is increased to match world time while sleeping, but the distilling process is not.

### How to reproduce

Fill distillery with wine and fuel. 
Go to sleep 
all fuel is consumed upon waking with almost no brandy made.
Boiler still has ~29L of wine

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2024-10-30 20:45
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/1640

**Closed by Craluminum2413** 2024-10-30 20:45 UTC
Labels: status: new
