### ISSUE TITLE
Random crash while waiting for something to cook.

### ISSUE THREAD

**Issue by tsmith656** [anegostudios/VintageStory-Issues#1313] opened 2021-09-19 23:54 UTC
**Game Version:** X.Y.Z  
**Platform:** Windows / Mac / Linux (which?)  
**Modded:** No / Yes (which?)  

### Description
Explain the issue you're running into.

### How to reproduce
1. Make a '....'
2. Use it on '....'
3. It crashes / doesn't do the thing.

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.6-rc.2 (Unstable)9/19/2021 7:52:36 PM: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.API.Common.Entities.Entity.OnCollideWithLiquid()
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.DisplaceWithBlockCollision(EntityPos pos, EntityControls controls, Single dt)
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.TickEntityPhysics(EntityPos pos, EntityControls controls, Single dt)
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.GameTick(Entity entity, Single dt)
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.onPhysicsTick(Single deltaTime)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _5PLCV9nT6lKYshnvhcLKYmPbSv2._SDEctPLMGfsOebRp3QVxVEQCiUh(Single )
   at _DXJNEmwVJN2e1mVFBQ5fTNR95yc._aLrho8PYHXGJeKPDayUCeRClMEf(Single )
   at _DXJNEmwVJN2e1mVFBQ5fTNR95yc._fFzUEjicM6tZAbcIuKZDCkHSfMJ(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _tWK3XnqdKwEz32DZgEFtVG3UU4k._ZGFqinpvIwFTz7F68DuIhzHOWm(_0yeWQ9WAjs9sBw2gtkuglYTlTmO , String[] )
   at _O6YHJJOUkiLLqUHLpLxBur1CoDP._ZGFqinpvIwFTz7F68DuIhzHOWm(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 9/18/2021 12:49:39 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1658733256924091269, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.5.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\tmsmi\AppData\Local\Temp\RDRD8F9.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD90A.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD90B.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD922.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD942.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 7185ead3-4a16-4320-9eba-5b2fd18de8e8
Report Status: 268435456
Hashed bucket: eb8d9853264150393705011bdc165385
Cab Guid: 0 }
Paste crash between the triple backticks.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.
```

**Comment by copygirl** [comment] 2021-09-20 05:33
Duplicate of #1309.
Thank you for reporting.
Please fill out all the information next time.

**Closed by copygirl** 2021-09-20 05:33 UTC
Labels: status: duplicate
