### ISSUE TITLE
Cascading cave-in near mantle causing blocks to fall upwards and spawn at surface. 

### ISSUE THREAD

**Issue by percussigant** [anegostudios/VintageStory-Issues#4389] opened 2024-10-28 14:30 UTC
### Game Version

v.1.20.pre7

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Digging down towards z-level 0, caused a cave-in that caused a cascade of cave-ins, as far as I could tell, with blocks that couldn't find a space to settle on, so they started popping up at surface. 

Reproduction video of it happening here

https://github.com/user-attachments/assets/d5f6c239-0894-4fd0-b500-95cfbc9443ff

This was from the stream. Full stream video is available there as well. 

https://www.twitch.tv/thepercussigant/clip/BeautifulGoldenSalmonUncleNox-4Ecn-UhQUn7aFeru?filter=clips&range=7d&sort=time

### How to reproduce

Be near the mantle / low enough
Cause a cave-in that cascades?
Non-stop cave in with sounds should occur. 
Fly up to surface to see the block volcano. 

### Screenshots

![2024-10-28_14-30-13](https://github.com/user-attachments/assets/1a1532b5-14b4-43d1-ab63-adeade0d9d0a)

### Logs

```Log```
[client-main.log](https://github.com/user-attachments/files/17543980/client-main.log)
[client-crash.log](https://github.com/user-attachments/files/17543981/client-crash.log)
[client-crash.txt](https://github.com/user-attachments/files/17543982/client-crash.txt)
[server-worldgen.txt](https://github.com/user-attachments/files/17543983/server-worldgen.txt)
[server-worldgen.log](https://github.com/user-attachments/files/17543984/server-worldgen.log)
[server-main.log](https://github.com/user-attachments/files/17543985/server-main.log)
[server-debug.log](https://github.com/user-attachments/files/17543986/server-debug.log)
[server-audit.log](https://github.com/user-attachments/files/17543987/server-audit.log)
[server-build.log](https://github.com/user-attachments/files/17543988/server-build.log)
[server-chat.log](https://github.com/user-attachments/files/17543989/server-chat.log)
[client-audit.log](https://github.com/user-attachments/files/17543990/client-audit.log)
[client-chat.log](https://github.com/user-attachments/files/17543991/client-chat.log)
[client-debug.log](https://github.com/user-attachments/files/17543992/client-debug.log)

**Comment by Craluminum2413** [comment] 2024-11-05 10:19
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/3567

**Closed by Craluminum2413** 2024-11-05 10:19 UTC
Labels: status: new, department: code
