### ISSUE TITLE
Game Crashes the Moment I try to Launch it

### ISSUE THREAD

**Issue by pezrabioso** [anegostudios/VintageStory-Issues#409] opened 2020-03-05 02:09 UTC
**Game Version:** 1.12.5
**Platform:** Windows
**Modded:** No

### Description
Game crashes the moment I try to launch it
### How to reproduce
1. Launch the game

### Expected behavior
For the game to open normally.

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.12.5 (Stable)05/03/2020 2:02:27: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.ClientPlatformWindows.LoadTexture(IBitmap bmp, Boolean linearMag, Int32 clampMode, Boolean generateMipmaps)
   at _mKeEWUbBZsjLS6VlGWgOoYQFk2K._KNs6g2GMtsTu5gnL4MXdRgZVlLh()
   at _lt8TgSVuBImgzFgAFlSeVzSFsSy._HdDsdRJDH8nMF88r278C4eqdINGA()
   at _lt8TgSVuBImgzFgAFlSeVzSFsSy._gjiBClIE7Yspuz65gCqPGSAnUYeb()
   at _lt8TgSVuBImgzFgAFlSeVzSFsSy._NbPATb9BXlxRc4ZhH2GgyFCUInp(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _hCuHXesCXlp0LGSdrsPFpw4up5n._mOm8EuKIvHpaJoztxNWRpAoOpbM(_55ISULxdcpPfF8D2JP831aWhOBe , String[] )
   at _iCfIbY24GyBXP5lAwqsSlD9COxC._mOm8EuKIvHpaJoztxNWRpAoOpbM(ThreadStart )
-------------------------------

**Comment by Acheron72P** [comment] 2020-03-05 04:10
Here you have the solution to the problem.
[https://github.com/anegostudios/VintageStory-Issues/issues/407](url)

**Comment by copygirl** [comment] 2020-03-05 06:09
Indeed a duplicate of #407.

**Closed by copygirl** 2020-03-05 06:09 UTC
Labels: status: duplicate, type: crash
