### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by pythonInRelay** [anegostudios/VintageStory-Issues#835] opened 2021-03-28 15:55 UTC
**Game Version:** 1.14.8
**Platform:** Windows

### Description
Clicked the button in the menu "remake world with this seed"

### Logs
```
Running on 64 bit Windows with 32 GB RAM 
Version: v1.14.8 (Stable)28/03/2021 18.53.07: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at _PW8NVVq6wBR9krMQ9GulRnv6PMD._h9K0G4wbrt2CCpt5A92lCnKV2gP()
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   at _oDnqPT3M9pq9hNGZM4RDtA6RTnG._TE0ypoo5kb57Ue2gLv7daIuY6VD(MouseEvent )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _YrS2W1MoaeqC4xqH8ItdZB6vADN._8t1BmEWVlCT9mjx5M0vFIzU9tif(_7T00Rjby4si0wyEBez5dXNqLm7h , String[] )
   at _ejKuc6cg0k8V39o8jDIzquyczbO._8t1BmEWVlCT9mjx5M0vFIzU9tif(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 17/03/2021 13.42.42, Site = , Source = Windows Error Reporting, Message = Fault bucket 1822032227626530173, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.8.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\redacted\AppData\Local\Temp\RDR20D6.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER20E7.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER20F7.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2105.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2125.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 72fbc312-e8f5-4b32-89a9-ce45684b6117
Report Status: 268435456
Hashed bucket: a995c73cc234971ef94928a850fe357d
Cab Guid: 0 }
--------------
{ TimeGenerated = 05/02/2021 18.30.02, Site = , Source = Windows Error Reporting, Message = Fault bucket 2030104223756818486, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.2.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\redacted\AppData\Local\Temp\RDR7AAF.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7AC0.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7AD1.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7ADE.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7AFF.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 8228447a-7a00-465e-b59b-90eb22382bd0
Report Status: 268435456
Hashed bucket: d62de5179f3713dc7c2c61091a0b9836
Cab Guid: 0 }
```

**Comment by copygirl** [comment] 2021-03-28 18:27
Duplicate of #795.

**Closed by copygirl** 2021-03-28 18:27 UTC
Labels: status: duplicate
