### ISSUE TITLE
Lower Block Export Quality

### ISSUE THREAD

**Issue by BradyThe** [anegostudios/VintageStory-Issues#4228] opened 2024-10-04 21:56 UTC
### Game Version

v1.20.0-pre4, v1.20.0-pre5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Running .exponepng (or .blockitempngexport for that matter) will result in a lower quality export of blocks and items. See examples below.

I am mainly reporting this, because this issue could be related to #4217 or any other graphical problems which haven't surfaced yet.

### Screenshots

v1.19.8:
![bonysoil](https://github.com/user-attachments/assets/8d1f1fdf-ce65-411e-a946-f8acf8cf46c8)

v1.20.0-pre4:
![bonysoil](https://github.com/user-attachments/assets/e489d2e1-fc20-4ff4-98c3-7faa662c2a6a)

**Comment by Craluminum2413** [comment] 2024-10-05 08:12
Can't reproduce
![bonysoil](https://github.com/user-attachments/assets/a22964c9-db60-4fab-ae54-ca513b34572b)

**Comment by Craluminum2413** [comment] 2024-10-05 08:13
Update, downgrade or reinstall your graphics drivers

**Comment by BradyThe** [comment] 2024-10-05 17:26
> Try to update, downgrade or reinstall your graphics drivers

Welp, time to buy a new graphics card then, because I am on the newest driver.

**Comment by Craluminum2413** [comment] 2024-10-05 17:37
@BradyThe Try downgrate then?

**Comment by BradyThe** [comment] 2024-10-05 17:54
> @BradyThe Try downgrate then?

The problem is that I am using a graphics card of the Radeon R9 200 series, which had its driver support ended in 2022. I don't think that downgrading will change anything, because the newest drivers (2022-06-23) works fine in 1.19.8, but does not in 1.20.0.

While it would be great if the block export would produce high quality pictures, I am more concerned about the implications.
In-game you can clearly notice a quality decrease as well.

**Example**
v1.19.8:
![2024-10-05_19-46-28](https://github.com/user-attachments/assets/ad126554-8762-4829-91c1-3608de813a90)

v1.20.0-pre4:
![2024-10-05_19-48-05](https://github.com/user-attachments/assets/5d1390fc-f7cd-4fb3-87ca-9e7da056b6db)

I reported this, because I currently don't know if this is a bug or just the unfortunate side effect of change (which I would accept once confirmed).

**Comment by BradyThe** [comment] 2024-10-05 21:28
Based on Tyrons storage texture adventures today, I had a look at chests and noticed that textures are blurry on opened chests or vessels, as well as on triggered traps (with and without content).
![2024-10-05_22-46-10](https://github.com/user-attachments/assets/387eb4e3-70bc-45c1-be98-847b1b0375ee)

The trader and seraph clothing issues are most likely related to the 3D clothing changes.

**Comment by Craluminum2413** [comment] 2024-10-05 21:31
@BradyThe Did you test it in pre.5?

**Comment by BradyThe** [comment] 2024-10-05 22:04
> @BradyThe Did you test it in pre.5?

Forgot to mention that this is indeed pre.5.

**Comment by BradyThe** [comment] 2024-10-13 16:31
Issue seems to be fixed in pre.6. I'll keep this open for a while to test some more, but for now I am optimistic.

**Comment by Craluminum2413** [comment] 2024-10-13 16:35
If it is fixed, then I close it

**Closed by Craluminum2413** 2024-10-13 16:35 UTC
Labels: status: incomplete, 3rd party issue, version: 1.20

**Comment by BradyThe** [comment] 2024-10-13 16:48
> If it is fixed, then I close it

I'd (short for "I would") recommend you to take some English lessons. "It **seems** fixed" does not have the meaning of "It **is** fixed".

### Verb
**seem** (third-person singular simple present **seems**, present participle **seeming**, simple past and past participle **seemed**)
1. (copulative) To appear; to look outwardly; to be perceived as.

Cheers, though.
