### ISSUE TITLE
Butchering a chick causes server-side exception and client disconnect

### ISSUE THREAD

**Issue by AbortRetryFail** [anegostudios/VintageStory-Issues#4373] opened 2024-10-25 18:31 UTC
### Game Version

v1.20.0-pre.7

### Platform

Linux

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

I killed and butchered a wild chick (low weight) and the server kicks me off. Player is hunter class if that matters.

### How to reproduce

1. Kill a chick.
2. Harvest it with a knife.

### Logs

```
25.10.2024 18:28:38 [Server Event] Player ARF got removed. Reason: Threw an exception at the server
25.10.2024 18:28:38 [Server Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityBehaviorHarvestable.generateDrops(IPlayer byPlayer, Single dropQuantityMultiplier) in VSEssentials\Entity\Behavior\BehaviorHarvestable.cs:line 435
   at Vintagestory.GameContent.EntityBehaviorHarvestable.SetHarvested(IPlayer byPlayer, Single dropQuantityMultiplier) in VSEssentials\Entity\Behavior\BehaviorHarvestable.cs:line 381
   at Vintagestory.GameContent.ItemKnife.OnHeldInteractStop(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel) in VSSurvivalMod\Item\ItemKnife.cs:line 195
   at Vintagestory.Server.ServerSystemInventory.HandleHandInteraction(Packet_Client packet, ConnectedClient client) in VintagestoryLib\Server\Systems\Inventory.cs:line 255
   at Vintagestory.Server.ServerMain.ProcessNetMessage(NetIncomingMessage msg, NetServer mainSocket) in VintagestoryLib\Server\ServerMainNetworking.cs:line 141
```

**Comment by Craluminum2413** [comment] 2024-10-25 18:59
Can't reproduce

**Comment by maltiez2** [comment] 2024-11-06 07:57
should be fixed in next release

**Closed** 2024-11-06 07:57 UTC
Labels: status: incomplete, department: code, version: 1.20
