### ISSUE TITLE
Omok placing is off by one X and one Y

### ISSUE THREAD

**Issue by boi-led-egg** [anegostudios/VintageStory-Issues#2593] opened 2023-04-15 07:32 UTC
### Game Version

v1.18.0-rc.6

### Platform

Linux

### Modded

Modded

### SP/MP

Singleplayer

### Description

When placing omok pieces, they are not placed where cursor is pointed, but off by one X and one Y coordinate.

### How to reproduce

1. Point at Omok table
2. Place a piece
3. Piece is not place where cursor was pointing

### Screenshots

![2023-04-15_00-27-33](https://user-images.githubusercontent.com/1443973/232196069-8ff105ff-cd66-45ea-aed7-b19374e7873b.png)
![2023-04-15_00-27-37](https://user-images.githubusercontent.com/1443973/232196078-02e0618b-9f5e-448a-b43c-2f5cc5022b04.png)

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2023-04-15 17:18
Duplicate of #2562

**Closed by Craluminum2413** 2023-04-15 17:18 UTC
Labels: status: new, version: 1.18

**Comment by boi-led-egg** [comment] 2023-04-15 19:43
It is not a duplicate, and it's a newer version, which is supposed to have it fixed.
