### ISSUE TITLE
Bug with chiseled stone blocks crashing game

### ISSUE THREAD

**Issue by Not60661** [anegostudios/VintageStory-Issues#931] opened 2021-05-29 06:09 UTC
**Game Version:** 1.15
**Platform:** Windows
**Modded:** Yes: Longer Fuel and Disable Drifters and Bells

### Description
Had one of every chiseled polished stone block in inventory.  Open bags, game crashes.

### How to reproduce
1. Make a chiseled stone block
2. Put it in bags
3. Open bags. Game crashes.
4. 
### Expected behavior
To open bags and combine blocks.

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Paste crash here.

https://gist.github.com/Not60661/f7c0b1014e64682e3ad1350fca2bdcef

**Comment by copygirl** [comment] 2021-05-29 06:41
Duplicate of #895, but thank you for reporting!

**Closed by copygirl** 2021-05-29 06:41 UTC
Labels: status: duplicate
