### ISSUE TITLE
Game crash when spawning a stack of items in creative (Ctrl + Click)

### ISSUE THREAD

**Issue by Exophobias** [anegostudios/VintageStory-Issues#2924] opened 2023-07-16 19:19 UTC
### Game Version

v1.18.6 (Stable)

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

Game crashes when spawning in a stack of any item (Control + left click)

### How to reproduce

1. Go into creative
2. For any item, hold Control and left click to spawn x64 of item
3. Game crashes, and on relog, the stack of items is in inventory but repeating process results in the same crash and log.

### Logs

```Log```
Running on 64 bit Windows with 80 GB RAM 
Game Version: v1.18.6 (Stable)
2023-07-16 12:15:17 PM: Critical error occurred
Loaded Mods: ancienttools@1.5.7, betterruins@0.2.1, bth@1.2.8, blacksmithname@1.1.0, canclasses@1.0.11, furniturelibrary@1.0.9, HangingOilLamps@1.0.1, hideandfabric@1.3.0, materialaging@1.0.0, medieval@2.01.26, pondfrogsi@1.1.0, primitivesurvival@3.2.4, rpgitemrarity@1.0.3, dzsalvageplus@1.0.1, she1fish@1.1.0, sca@1.0.0, ssppvv@1.0.5, viesblocks@2.4.2, game@1.18.6, wildcrafttrees@1.2.3, abcsreborn@0.0.6, altmapiconrenderer@1.2.1, canjewelry@0.1.10, carryon@1.2.0, coinage@1.6.1, cooperativecombat@1.1.0, crateful@1.0.3, fishing@1.1.3, itemizer@1.0.1, sailboat@1.1.0, mapautocenter@1.1.0, medievalexpansion@3.9.3, medievalmap@1.3.3, nemi@1.1.0, petai@1.7.10, th3dungeon@0.1.2, th3expansion@1.1.0, creative@1.18.6, survival@1.18.6, waypointcolours@1.1.0, weightmod@0.2.0, em@2.2.0, feverstonehorses@1.5.0, notenoughsand@1.4.0, rifteye@0.2.3, simplewinddirection@1.0.2, xinvtweaks@1.5.6, bricklayers@2.2.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Common.InventoryPlayerCreative.ActivateSlot(Int32 slotId, ItemSlot sourceSlot, ItemStackMoveOperation& op) in VintagestoryLib\Common\GameContent\Inventory\InventoryPlayerCreative.cs:line 96
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.SlotClick(ICoreClientAPI api, Int32 slotId, EnumMouseButton mouseButton, Boolean shiftPressed, Boolean ctrlPressed, Boolean altPressed) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 980
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseDownOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 773
   at Vintagestory.API.Client.GuiElement.OnMouseDown(ICoreClientAPI api, MouseEvent mouse) in VintagestoryApi\Client\UI\Elements\Impl\GuiElement.cs:line 703
   at Vintagestory.API.Client.GuiComposer.OnMouseDown(MouseEvent mouseArgs) in VintagestoryApi\Client\UI\GuiComposer.cs:line 460
   at Vintagestory.Client.NoObf.GuiDialogInventory.OnMouseDown(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogInventory.cs:line 551
   at Vintagestory.Client.NoObf.GuiManager.OnMouseDown(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 394
   at Vintagestory.Client.NoObf.ClientMain.OnMouseDown(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1821
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonDown(Object sender, MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 219
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 792
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1554
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 368
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2023-06-24 5:41:55 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1813180379713846513, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.5.0
P3: 10.0.22621.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\*****\AppData\Local\Temp\RDR9737.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.29d6e31c-a64b-41e5-a1da-516206c7e703.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.81551c39-85e3-483d-8370-32e4093c3356.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.20a160dd-6a5f-4ad6-8334-3d1229283b0b.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.b26963b8-1db3-4354-8673-1b60fe06b7fc.tmp.xml

These files may be available here:
NULL

Analysis symbol: 
Rechecking for solution: 0
Report Id: 191ef04f-1339-4be3-8c45-8c6043c37223
Report Status: 268435456
Hashed bucket: ee80768c6970f7acd929b5f2de8d3cf1
Cab Guid: 0 }
--------------
{ TimeGenerated = 2023-06-24 5:29:23 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException
   at System.Threading.ThreadLocal`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetValueSlow()
   at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionStatesNative(Vintagestory.API.Common.IWorldAccessor, Vintagestory.API.Common.ItemSlot)
   at Vintagestory.API.Common.CollectibleObject.AppendPerishableInfoText(Vintagestory.API.Common.ItemSlot, System.Text.StringBuilder, Vintagestory.API.Common.IWorldAccessor)
   at DynamicClass.Vintagestory.API.Common.CollectibleObject.GetHeldItemInfo_Patch0(Vintagestory.API.Common.CollectibleObject, Vintagestory.API.Common.ItemSlot, System.Text.StringBuilder, Vintagestory.API.Common.IWorldAccessor, Boolean)
   at Vintagestory.API.Common.Block.GetHeldItemInfo(Vintagestory.API.Common.ItemSlot, System.Text.StringBuilder, Vintagestory.API.Common.IWorldAccessor, Boolean)
   at Vintagestory.API.Common.ItemStack.GetDescription(Vintagestory.API.Common.IWorldAccessor, Vintagestory.API.Common.ItemSlot, Boolean)
   at Vintagestory.GameContent.GuiHandbookItemStackPage..ctor(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Common.ItemStack)
   at Vintagestory.GameContent.ModSystemHandbook.onCreatePagesAsync()
   at Vintagestory.GameContent.GuiDialogHandbook.LoadPages_Async()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
--------------
{ TimeGenerated = 2023-06-14 2:41:04 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Vintagestory.Common.BlockTypeNet.ReadBlockTypePacket(Packet_BlockType, Vintagestory.API.Common.IWorldAccessor, Vintagestory.Common.ClassRegistry)
   at Vintagestory.Client.NoObf.ClientSystemStartup.PopulateBlocks(Vintagestory.API.Common.Block[], Int32, Int32)
   at Vintagestory.Client.NoObf.ClientSystemStartup.LoadBlockTypes()
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step1()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }

**Comment by Guimoute** [comment] 2023-07-17 00:28
Does it crash with vanilla items or only modded?

**Comment by Exophobias** [comment] 2023-07-17 00:37
All items, vanilla or modded
________________________________

**Comment by Craluminum2413** [comment] 2024-02-05 10:38
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/2688

**Closed by Craluminum2413** 2024-02-05 10:38 UTC
Labels: status: new
