### ISSUE TITLE
Smithing randomly doesn

### ISSUE THREAD

**Issue by domprestia** [anegostudios/VintageStory-Issues#3701] opened 2024-03-10 15:41 UTC
### Game Version

v1.19.5-rc.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

S

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2024-03-10 15:46
Duplicate of #3681

**Closed by Craluminum2413** 2024-03-10 15:46 UTC
Labels: status: new

**Comment by domprestia** [comment] 2024-03-10 15:48
Woops, I should read the bugs already reported, sorry about that.
