### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by RandomUsernamePls** [anegostudios/VintageStory-Issues#3713] opened 2024-03-13 11:44 UTC
### Game Version

v1.19.4 (stable)

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

 Game crashed seemingly randomly.

### How to reproduce

I was making a clay storage vessel at night and the game crashed. Not sure if what I was doing is related at all.

### Logs

Running on 64 bit Windows 10.0.19045.0 with 8074 MB RAM
Game Version: v1.19.4 (Stable)
13.03.2024 12:35:57: Critical error occurred
Loaded Mods: game@1.19.4, creative@1.19.4, survival@1.19.4
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.BlockEntityClayForm.OnCopyLayer(Int32 layer) in VSSurvivalMod\BlockEntity\BEClayForm.cs:line 400
   at Vintagestory.GameContent.BlockEntityClayForm.OnUseOver(IPlayer byPlayer, Vec3i voxelPos, BlockFacing facing, Boolean mouseBreakMode) in VSSurvivalMod\BlockEntity\BEClayForm.cs:line 229
   at Vintagestory.GameContent.BlockEntityClayForm.OnUseOver(IPlayer byPlayer, Int32 selectionBoxIndex, BlockFacing facing, Boolean mouseBreakMode) in VSSurvivalMod\BlockEntity\BEClayForm.cs:line 151
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 329
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnGameTick(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 162
   at Vintagestory.Common.GameTickListener.OnTriggered(Int64 ellapsedMilliseconds) in VintagestoryLib\Common\Model\GameTickListener.cs:line 27
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 57
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 815
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 731
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Craluminum2413** [comment] 2024-03-13 11:51
Duplicate of #2284

**Closed by Craluminum2413** 2024-03-13 11:51 UTC
Labels: status: new

**Comment by radfast** [comment] 2024-03-17 13:41
Fixed in upcoming 1.19.5-stable, thanks for reporting.

(The duplicate is still helpful as it has more up-to-date stacktrace)
