### ISSUE TITLE
Survival Handbook crash.

### ISSUE THREAD

**Issue by PascalMancini** [anegostudios/VintageStory-Issues#3367] opened 2024-01-03 19:43 UTC
### Game Version

 v1.19.0-rc.5 (Unstable)

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When clicking on the mining bag in the survival handbook the game crash.

### How to reproduce

1.Open the survival handbook in game, 2.Search for Mining bag, 3.Click on Mining bag. 4.The game crash and open the Vintage Story crash reporter.

### Logs

```Running on 64 bit Windows 10.0.22621.0 with 16265 MB RAM
Game Version: v1.19.0-rc.5 (Unstable)
03/01/2024 20:26:44: Critical error occurred
Loaded Mods: game@1.19.0-rc.5, creative@1.19.0-rc.5, survival@1.19.0-rc.5
System.DivideByZeroException: Attempted to divide by zero.
   at Vintagestory.API.Client.SlideshowGridRecipeTextComponent.RenderInteractiveElements(Single deltaTime, Double renderX, Double renderY, Double renderZ) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\SlideshowGridRecipeTextComponent.cs:line 315
   at Vintagestory.API.Client.GuiElementRichtext.RenderInteractiveElements(Single deltaTime) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementRichtext.cs:line 472
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime) in VintagestoryApi\Client\UI\GuiComposer.cs:line 716
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 384
   at Vintagestory.GameContent.GuiDialogHandbook.OnRenderGUI(Single deltaTime) in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 493
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 318
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1006
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 317
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 03/01/2024 20:25:51, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.0.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x3e10
Faulting application start time: 0x0x1da3e79fefc4185
Faulting application path: C:\Users\enr\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\enr\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: cf3f13f5-c538-48c3-8afb-4e0578eaa618
Faulting package full name: 
Faulting package-relative application ID:  }```

**Comment by Craluminum2413** [comment] 2024-01-03 19:49
Duplicate of #3366

**Closed by Craluminum2413** 2024-01-03 19:49 UTC
Labels: status: new, version: 1.19
