### ISSUE TITLE
GameContent.StoryStructuresSpawnConditions error

### ISSUE THREAD

**Issue by WickedSchnitzel** [anegostudios/VintageStory-Issues#4798] opened 2024-12-25 15:57 UTC
### Game Version

1.20.0-rc.6

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

saw that in the console, again no clue what causes it

### Logs
```
[Server Event] Player Enoch got removed. Reason: Threw an exception at the server
25.12.2024 15:53:53 [Server Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.StoryStructuresSpawnConditions.GetStoryStructureAt(BlockPos pos) in VSSurvivalMod\Lore\StoryStructuresSpawnConditions.cs:line 132
   at Vintagestory.GameContent.StoryStructureProtection.Event_OnTestBlockAccess(IPlayer player, BlockSelection blockSel, EnumBlockAccessFlags accessType, String& claimant, EnumWorldAccessResponse response) in VSSurvivalMod\Lore\StoryStructureProtection.cs:line 60
   at Vintagestory.Server.ServerSystemBlockSimulation.HandleBlockInteract(Packet_Client packet, ConnectedClient client) in VintagestoryLib\Server\Systems\World\BlockSimulation.cs:line 429
   at Vintagestory.Server.ServerSystemInventory.HandleHandInteraction(Packet_Client packet, ConnectedClient client) in VintagestoryLib\Server\Systems\Inventory.cs:line 255
   at Vintagestory.Server.ServerMain.HandleClientPacket(ConnectedClient client, Byte[] data) in VintagestoryLib\Server\ServerMainNetworking.cs:line 154
   at Vintagestory.Server.ServerMain.ProcessNetMessage(NetIncomingMessage msg, NetServer mainSocket) in VintagestoryLib\Server\ServerMainNetworking.cs:line 147
```

**Comment by Craluminum2413** [comment] 2024-12-25 15:59
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4678

**Closed by Craluminum2413** 2024-12-25 15:59 UTC
Labels: status: new
