### ISSUE TITLE
Crash after throwing chert spear

### ISSUE THREAD

**Issue by astynax777** [anegostudios/VintageStory-Issues#944] opened 2021-05-31 15:58 UTC
**Game Version:** 1.15.0-pre.2
**Platform:** Windows
**Modded:** No

### Description
I was fighting a drifter and threw a flint spear and the game crashed.  I suspect it has to do with replacing the thrown spear with another spear.

### How to reproduce
It seemed random 
1. I had two flint spears in my inventory
2. I threw one and it switched to the second one
3. I picked up the one I threw and switched to it since it had less durability
4. I threw the spear again and it crashed

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.0-pre.2 (Unstable)5/31/2021 11:52:27 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.CollectibleObject.<>c__DisplayClass70_0.<RefillSlotIfEmpty>b__0(ItemSlot invslot)
   at Vintagestory.API.Common.EntityPlayer.WalkInventory(OnInventorySlot handler)
   at Vintagestory.API.Common.CollectibleObject.DamageItem(IWorldAccessor world, Entity byEntity, ItemSlot itemslot, Int32 amount)
   at Vintagestory.GameContent.ItemSpear.OnHeldInteractStop(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _xArlFw5lpThzIY0BN36UerAlHzU._rAqK7n8QXTUGs9UT1i65b3MIHIP(Single )
   at _uFwaliVbJcYmzlP3dwic7HSHMr2._EuQCmN4cQf8FBHYrlJxd8EhIdNnA(Single )
   at _uFwaliVbJcYmzlP3dwic7HSHMr2._HlDCi3DfsJHaHE4jniBarrjFlHLB(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _EKato5MKvGk9ELCMKyl4BGVO7pe._ninJWCWaWyMG9ZSA1Eyytms1G5F(_BjQ4x8rTRChySIeXrK1HK1YSqec , String[] )
   at _btwtpE4G1MfBqD34njKFCvBcSRd._ninJWCWaWyMG9ZSA1Eyytms1G5F(ThreadStart )
-------------------------------

**Comment by copygirl** [comment] 2021-05-31 17:49
This should have been fixed in this version. See #907. @radfast?

**Comment by copygirl** [comment] 2021-05-31 17:50
Out of curiosity, when were these spears crafted? In a pre-release? 1.14?

**Comment by astynax777** [comment] 2021-05-31 18:06
This was a new game  v1.15.0-pre.2.

**Comment by astynax777** [comment] 2021-05-31 18:19
I also wanted to note that after my game crashed, I loaded up the last autosave and two weird things happened with my pit kiln.  (I realize this is still a WIP, but figured I'd report it anyway just in case).  The kiln had been running all night before the crash happened, and after the crash they had returned to an unburnt state.  I relit them, then I picked up an anvil mold and placed it into a new pit diagonal from ones already burning and the mold just disappeared.  A few minutes later all 3 of the other pits that I had just relit stopped burning and all of the contents disappeared.  Perhaps this is related to the crash, but perhaps it's related to loading a save when the kiln were burning.  I didn't test to see if it was the latter.  Thanks!

**Comment by Shuro** [comment] 2021-05-31 21:58
Got the same problem in v1.15-pre2:
```
Version: v1.15.0-pre.2 (Unstable)31.05.2021 22:53:30: Critical error occurred
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.API.Common.CollectibleObject.<>c__DisplayClass70_0.<RefillSlotIfEmpty>b__0(ItemSlot invslot)
   bei Vintagestory.API.Common.EntityPlayer.WalkInventory(OnInventorySlot handler)
   bei Vintagestory.API.Common.CollectibleObject.DamageItem(IWorldAccessor world, Entity byEntity, ItemSlot itemslot, Int32 amount)
   bei Vintagestory.GameContent.ItemSpear.OnHeldInteractStop(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   bei Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt)
   bei Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   bei Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   bei Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   bei _xArlFw5lpThzIY0BN36UerAlHzU._rAqK7n8QXTUGs9UT1i65b3MIHIP(Single )
   bei _uFwaliVbJcYmzlP3dwic7HSHMr2._EuQCmN4cQf8FBHYrlJxd8EhIdNnA(Single )
   bei _uFwaliVbJcYmzlP3dwic7HSHMr2._HlDCi3DfsJHaHE4jniBarrjFlHLB(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _EKato5MKvGk9ELCMKyl4BGVO7pe._ninJWCWaWyMG9ZSA1Eyytms1G5F(_BjQ4x8rTRChySIeXrK1HK1YSqec , String[] )
   bei _btwtpE4G1MfBqD34njKFCvBcSRd._ninJWCWaWyMG9ZSA1Eyytms1G5F(ThreadStart )
   ```
   
   Spear had one durability. I could check since it was a multiplayer server and it only crashed for my client.

**Comment by BinaryKali** [comment] 2021-06-04 15:12
Not sure it helps but I've also had this same issue with a new mp (lan) server created with 1.15-pre2. It would always happen if my spear was going to break when thrown. I was able to reproduce it when my server came back up (didn't realize what the issue was and threw the spear again). Would it be helpful for me to add my log here as well?

**Comment by Craluminum2413** [comment] 2021-06-04 15:23
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Common.ClassRegistryAPI.CreateEntity(EntityProperties entityType)
   at Vintagestory.GameContent.ItemSpear.OnHeldInteractStop(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _xArlFw5lpThzIY0BN36UerAlHzU._rAqK7n8QXTUGs9UT1i65b3MIHIP(Single )
   at _uFwaliVbJcYmzlP3dwic7HSHMr2._EuQCmN4cQf8FBHYrlJxd8EhIdNnA(Single )
   at _uFwaliVbJcYmzlP3dwic7HSHMr2._HlDCi3DfsJHaHE4jniBarrjFlHLB(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _EKato5MKvGk9ELCMKyl4BGVO7pe._ninJWCWaWyMG9ZSA1Eyytms1G5F(_BjQ4x8rTRChySIeXrK1HK1YSqec , String[] )
   at _btwtpE4G1MfBqD34njKFCvBcSRd._ninJWCWaWyMG9ZSA1Eyytms1G5F(ThreadStart )
```

**Comment by Craluminum2413** [comment] 2021-06-11 19:07
Crashes only when throwing stone spears

**Comment by Craluminum2413** [comment] 2021-06-14 15:12
Rename this issue to `Game crashed while throwing stone spears`?

**Comment by astynax777** [comment] 2021-06-14 15:54
I've only used flint to make my spears. I never thought about using another stone type. Regardless, I renamed the issue.

**Comment by Craluminum2413** [comment] 2021-06-14 15:58
Well in 1.15.0-pre.3 only chert spear can cause crash. I guess they fixed in this version all spears except chert

**Comment by astynax777** [comment] 2021-06-14 16:05
Good to know.

**Comment by astynax777** [comment] 2021-06-17 02:11
I just crashed my game now for science! Flint spears definitely crash it.

**Comment by Craluminum2413** [comment] 2021-06-17 08:46
You mean 1.15.0-pre.3?

**Comment by Craluminum2413** [comment] 2021-06-20 17:55
**Not** fixed in 1.15.0-pre.5, don't close

**Comment by tyronx** [comment] 2021-06-22 16:22
Oh, these are 2 different crashes

**Comment by Craluminum2413** [comment] 2021-06-22 16:23
Yes, I don't think it's worth opening this as two different issues

**Comment by tyronx** [comment] 2021-06-22 16:23
also fixed for pre.7 now

**Closed by tyronx** 2021-06-22 16:23 UTC
Labels: status: new, target: survival, type: crash
