### ISSUE TITLE
Hotkeys don't work anymore for non-QWERTY keyboards 

### ISSUE THREAD

**Issue by Guimoute** [anegostudios/VintageStory-Issues#3026] opened 2023-08-15 21:03 UTC
### Game Version

v1.18.8 stable

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Hello,

Since the switch from .NET4 to .NET7 (including experimental releases), the game considers your keyboard is using a QWERTY layout.
That means you have to install the QWERTY layout, manually switch from your native layout into QWERTY when playing the game, remap all your hotkeys because they don't work anymore, and forget about writing in books / typing in the chat because you are not able to type in a different keyboard layout.  

Related Discord conversation: https://discord.com/channels/302152934249070593/1138841896861585508

### How to reproduce

Use an AZERTY keyboard with computer set to AZERTY layout and notice typing "AZER" yields "QWER".

### Screenshots

![2023-08-15_22-50-24](https://github.com/anegostudios/VintageStory-Issues/assets/51537797/2b748d42-e0c2-47ab-9312-47899b9a6b32)

### Logs

```Log```

**Comment by Th3Dilli** [comment] 2023-09-15 10:41
I can only partially confirm this

the game does use ENGLISH US (QWERTY) to show the keys in the Settings > Controls and in the Macro Manager

but when typing text it does show the correct character (according to your set keyboard layout) in the chat or other textinput fields

So the only fix we can provide is that we show the correct key for the currently used keyboard layout in the Settings > Controls and in the Macro Manager

**Comment by Th3Dilli** [comment] 2023-09-15 10:44
I also tested on 1.18.5 and it has the same behavior there

**Comment by Th3Dilli** [comment] 2023-09-15 11:29
#356 

is the same issue and describes it as I can confirm

so fixing the settings and macro manager to show the character from your current keyboard layout should take care of this

**Comment by Guimoute** [comment] 2023-09-15 11:32
> I can only partially confirm this
> 
> the game does use ENGLISH US (QWERTY) to show the keys in the Settings > Controls and in the Macro Manager
> 
> but when typing text it does show the correct character (according to your set keyboard layout) in the chat or other textinput fields
> 

Hello,

Sorry I now realise my initial bug report may have contained a confusing phrasing. "_typing "AZER" yields "QWER_" was only meant for the settings > controls. The chat works well.

> So the only fix we can provide is that we show the correct key for the currently used keyboard layout in the Settings > Controls and in the Macro Manager

Anything is good.

> I also tested on 1.18.5 and it has the same behavior there

This is not my experience. I have played with physical AZERTY keyboard + FR keyboard layout setting since the start. **Only the switch from 1.18.7 to 1.18.8** "broke" the keys. By "breaking" I mean that without changing the layout and without changing the hotkeys registered, ZQSD didn't move the character anymore as Z and Q were interpreted as W and A.

**Comment by Th3Dilli** [comment] 2023-09-15 13:10
it may have been broken on the way to 1.18.8 with the rc or pre releases

could you delete those two mappings from settings.json

then it should show the keys as if you had QWERTY, no matter what layout you have set

if it then shows W for forward you should still be able to walk forward using AZERTY and key Z

**Comment by Th3Dilli** [comment] 2023-09-15 13:38
![image](https://github.com/anegostudios/VintageStory-Issues/assets/31390939/38432354-c798-4170-b281-db24594ebca3)
this is what it looks like with the new change
keyboard layout set to FR AZERTY and when I press Z on AZERTY I move forward without making any changes to default

and here I just changed my layout to German QWERTZ with no other changes and when I press W I move forward
![image](https://github.com/anegostudios/VintageStory-Issues/assets/31390939/f5794144-ea0b-429d-8840-a8de79a46eb4)

**Comment by Guimoute** [comment] 2023-09-15 15:41
> it may have been broken on the way to 1.18.8 with the rc or pre releases
> 
> could you delete those two mappings from settings.json
> 
> then it should show the keys as if you had QWERTY, no matter what layout you have set
>
> if it then shows W for forward you should still be able to walk forward using AZERTY and key Z

Is there a specific version in which I have to test this?

In my current installation (1.18.7), deleting those mappings from the file then starting the game does show the controls as WASD, but I cannot move forward or left using Z or Q. This version is the one where the game behaves as expected, showing the right letter in the control settings.

**Comment by Th3Dilli** [comment] 2023-09-15 16:43
Hmm that should work on 1.18.7 i just tested and it seems fine for me
![image](https://github.com/anegostudios/VintageStory-Issues/assets/31390939/7d1fea7a-4b4a-4c64-9848-cf224dd7a513)


maybe can you test with the latest 1.18.10
and or make a backup of your settings and delete the current one and try a fresh one so just start the game?

**Comment by Guimoute** [comment] 2023-09-15 17:28
Ok I'll test again following your steps and make a recording for you so that you can see everything. 

What is the software you are using for the virtual keyboard? I might as well use the same in case it doesn't behave the same way a physical keyboard does.

**Comment by Th3Dilli** [comment] 2023-09-16 19:12
That software is on linux build in, I haven't seen such on windows yet mysqlf

**Comment by Craluminum2413** [comment] 2023-10-04 12:50
Probably it is because for the game your non-QWERTY `Z` is key with the same number as QWERTY `W`

**Comment by Guimoute** [comment] 2023-10-04 13:47
> Probably it is because for the game your non-QWERTY `Z` is key with the same number as QWERTY `W`

Dana the core of the bug is not so much the keyboard layout not being recognised, it's that the behaviour changed during the .NET7 switch.

**Comment by Th3Dilli** [comment] 2023-12-15 08:59
So have you had a chance to test things in 1.19? and does that work well for you?

**Comment by Th3Dilli** [comment] 2023-12-22 15:30
hmm yeah probably not really worth for that one layout I assume

maybe you can set your system keyboard to a numbers by default version


for now I am going to close this then

**Closed by Th3Dilli** 2023-12-22 15:30 UTC
Labels: status: new
