### ISSUE TITLE
No drops on animals-drifters

### ISSUE THREAD

**Issue by MarcosMaurelli** [anegostudios/VintageStory-Issues#3306] opened 2023-12-12 12:18 UTC
### Game Version

v1.19.0-pre.9

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

You get nothing from killing animals-drifters

### How to reproduce

Kill an animal

### Screenshots

![no loot](https://github.com/anegostudios/VintageStory-Issues/assets/63467569/3e6db013-c6aa-4d1c-8fac-de4a0bae9e4f)

### Logs

[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/13647946/client-main.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/13647959/server-main.txt)

**Comment by Craluminum2413** [comment] 2023-12-12 12:39
Duplicate of #3289

**Closed by Craluminum2413** 2023-12-12 12:39 UTC
Labels: status: new
