### ISSUE TITLE
trough  cannot mix "dry grass" and "Hay".

### ISSUE THREAD

**Issue by teknik1** [anegostudios/VintageStory-Issues#2858] opened 2023-06-28 18:57 UTC
Vanilla 1.18.5
You can not merge dry grass and hay in trough.

![image](https://github.com/anegostudios/VintageStory-Issues/assets/9663048/69919a66-7ad3-41da-9c8b-08fc4fe09b60)

**Comment by Craluminum2413** [comment] 2023-06-28 19:18
They are different items

**Comment by Guimoute** [comment] 2023-06-28 21:49
I assume OP expected the trough to uncraft the hay bale and add 8 dry grass accordingly? Not a bad idea honestly.

**Comment by Craluminum2413** [comment] 2023-06-28 21:52
If it is a suggestion then I will close it

**Comment by teknik1** [comment] 2023-06-29 00:04
no  we can feed the trough with  hay bale and 8 dry grass.
That mean if you feed the trough with  one hay bale the trough will have 1 portion and after you cannot feed with dry grass.
Its not a huge bug but i have noticed

**Comment by teknik1** [comment] 2023-07-05 01:19
https://gifyu.com/image/SQXy6

**Comment by RedramVS** [comment] 2023-12-13 15:17
This is not a bug, this is simply how troughs function.  Grass and bales are different items, and the trough cannot accept more than one type of item.  hay bales are free to craft and un-craft, so it's at best a very, very minor qol issue.

**Closed by RedramVS** 2023-12-13 15:17 UTC
Labels: status: incomplete
