### ISSUE TITLE
Crash with german language // not with english   

### ISSUE THREAD

**Issue by SlrHui** [anegostudios/VintageStory-Issues#2093] opened 2022-08-07 05:49 UTC
**Game Version:v1.17.0-rc.3 (Unstable
**Platform:** Windows  
**Modded:** No
**SP/MP:** Singleplayer

### Description
Crash with german language (Feuerton)

### How to reproduce
1. when i move the mouse over the fire tone in the inventory the game crashes
(but only in german not in english language)

### Logs
Running on 64 bit Windows with 64 GB RAM 
Game Version: v1.17.0-rc.3 (Unstable)
Loaded Mods: game@1.17.0-rc.3, creative@1.17.0-rc.3, survival@1.17.0-rc.3
07.08.2022 07:39:02: Critical error occurred
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.API.Client.HotkeyComponent.GenHotkeyTexture() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\HotkeyComponent.cs:Zeile 49.
   bei Vintagestory.API.Client.GuiElementRichtext.ComposeFor(ElementBounds bounds, Context ctx, ImageSurface surface) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementRichtext.cs:Zeile 418.
   bei Vintagestory.API.Client.GuiElementRichtext.Compose(Boolean genTextureLater) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementRichtext.cs:Zeile 118.
   bei Vintagestory.API.Client.GuiElementItemstackInfo.<>c__DisplayClass20_1.<AsyncRecompose>b__1() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementItemstackInfo.cs:Zeile 178.
   bei Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientMain.cs:Zeile 1138.
   bei Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:Zeile 123.
   bei Vintagestory.Client.ScreenManager.Render(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:Zeile 664.
   bei Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ScreenManager.cs:Zeile 608.
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\GameWindow.cs:Zeile 125.
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 476.
   bei OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 452.
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:Zeile 375.
   bei Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   bei Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:Zeile 87.
-------------------------------

Paste crash between the triple backticks.

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.
```

**Comment by Craluminum2413** [comment] 2022-08-07 05:53
Duplicate of #2055

**Closed by Craluminum2413** 2022-08-07 05:53 UTC
Labels: status: new
