### ISSUE TITLE
crash while exploring the map

### ISSUE THREAD

**Issue by HanDrauid** [anegostudios/VintageStory-Issues#3231] opened 2023-11-15 18:22 UTC
### Game Version

V1.19.0-pre.5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I didn't do anything special, I explored the map and ran and jumped when necessary.

### Logs

```Log```
Running on 64 bit Windows with 16276 MB RAM
Game Version: v1.19.0-pre.5 (Unstable)
15/11/2023 19:14:23: Critical error occurred
Loaded Mods: game@1.19.0-pre.5, creative@1.19.0-pre.5, survival@1.19.0-pre.5
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Vintagestory.GameContent.MicroBlockSounds.get_block() in VSSurvivalMod\Systems\Microblock\BlockMicroBlock.cs:line 45
   at Vintagestory.GameContent.MicroBlockSounds.get_Walk() in VSSurvivalMod\Systems\Microblock\BlockMicroBlock.cs:line 23
   at Vintagestory.API.Common.EntityPlayer.PlayWalkSound(IPlayer player) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 538
   at Vintagestory.API.Common.EntityPlayer.updateEyeHeight(Single dt) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 398
   at Vintagestory.Client.NoObf.PlayerCamera.OnBeforeRenderFrame3D(Single dt) in VintagestoryLib\Client\Render\PlayerCamera.cs:line 58
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 796
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 718
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 322
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Craluminum2413** [comment] 2023-11-15 18:25
Duplicate of #3205

**Closed by Craluminum2413** 2023-11-15 18:25 UTC
Labels: status: new
