### ISSUE TITLE
Unusable clutter 

### ISSUE THREAD

**Issue by Lokiver** [anegostudios/VintageStory-Issues#3321] opened 2023-12-20 01:28 UTC
### Game Version

v1.18.15

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Found in ruins an invicible block named "stone rubble" without model. Also in description tells that it Unusable clutter.

### Screenshots

![image](https://github.com/anegostudios/VintageStory-Issues/assets/114997702/7dd0c0ac-5e7c-4e57-bdaf-21f79805ec7b)

### Logs

```Log```
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/13721831/client-main.txt)
[server-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/13721832/server-main.txt)

**Comment by Craluminum2413** [comment] 2023-12-20 01:35
Duplicate of #2900

**Closed by Craluminum2413** 2023-12-20 01:35 UTC
Labels: status: new

**Comment by pingouyn** [comment] 2024-01-11 19:57
Still a bug in 1.19.0.rc6
