### ISSUE TITLE
Placed food (pumpkin/pineapple) doesn't spoil.

### ISSUE THREAD

**Issue by Ragolution** [anegostudios/VintageStory-Issues#1233] opened 2021-07-30 18:55 UTC
**Game Version:** 1.15.2
**Platform:** Win10
**Modded:** No

### Description
Pumpkins and pineapples, when placed on the ground, will not expire. They essentially outlast even flour, and can be picked up with their full duration of freshness. This, in essence, can provide immortal pumpkins.

### How to reproduce
1. Grow pumpkin
2. Place on ground
3. fresh forever

**Comment by Craluminum2413** [comment] 2021-07-30 19:31
Duplicate of #980

**Closed** 2021-07-30 20:14 UTC
Labels: status: duplicate
