### ISSUE TITLE
1.18.6 boots bug

### ISSUE THREAD

**Issue by Prinzip** [anegostudios/VintageStory-Issues#2865] opened 2023-06-29 15:58 UTC
### Game Version

1.18.6

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

all boots on ground show a figuremodel

https://cdn.discordapp.com/attachments/1124004863886512229/1124004864196874260/image.png

u can watch the bug in video:

https://cdn.discordapp.com/attachments/334233095374897152/1124005190996066335/2023-06-29_17-53-54.mp4

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2023-06-29 15:59
Duplicate of #2862

**Closed by Craluminum2413** 2023-06-29 15:59 UTC
Labels: status: new
