### ISSUE TITLE
Sometimes crashes when mod loader tries to report dependancy issues

### ISSUE THREAD

**Issue by keinkaihere** [anegostudios/VintageStory-Issues#3644] opened 2024-02-27 17:01 UTC
### Game Version

1.19.4rc3

### Platform

Windows

### Modded

Modded

### SP/MP

None

### How to reproduce

Seems to happen when a mod has multiple dependencies and one of them is out of date. Found with Maltiez's mods because they have a lot of dependencies.

### Logs

```
Running on 64 bit Windows 10.0.22621.0 with 15711 MB RAM
Game Version: v1.19.4-rc.3 (Unstable)
2024-02-27 11:47:32: Critical error occurred
Loaded Mods: buzzwords@1.6.0, game@1.19.4-rc.3, animationmanagerlib@0.6.3, betterfirepit@1.1.4, carryon@1.7.4, commonlib@2.3.4, hudclock@3.4.0, creative@1.19.4-rc.3, vsimgui@0.3.5, survival@1.19.4-rc.3, bullseye-continued@2.5.5, configlib@0.5.4, playercorpse@1.9.0, stonequarry@3.2.1
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.GuiScreenMods.LoadModCells() in VintagestoryLib\Client\MainMenu\Screens\GuiScreenMods.cs:line 93
   at Vintagestory.Client.GuiScreenMods.InitGui() in VintagestoryLib\Client\MainMenu\Screens\GuiScreenMods.cs:line 151
   at Vintagestory.Client.GuiScreenMods..ctor(ScreenManager screenManager, GuiScreen parentScreen) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenMods.cs:line 28
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Vintagestory.Client.ScreenManager.LoadAndCacheScreen(Type screenType) in VintagestoryLib\Client\ScreenManager.cs:line 924
   at Vintagestory.Client.GuiCompositeMainMenuLeft.OnMods() in VintagestoryLib\Client\MainMenu\Composite\GuiCompositeMainMenuLeft.cs:line 302
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 317
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\GuiElement.cs:line 719
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Controls\GuiElementTextButton.cs:line 307
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 445
   at Vintagestory.Client.GuiCompositeMainMenuLeft.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\MainMenu\Composite\GuiCompositeMainMenuLeft.cs:line 361
   at GuiScreen.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\MainMenu\Screens\Special\GuiScreen.cs:line 198
   at Vintagestory.Client.ScreenManager.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\ScreenManager.cs:line 890
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 211
   at OpenTK.Windowing.Desktop.NativeWindow.OnMouseUp(MouseButtonEventArgs e)
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.NativeWindow.ProcessWindowEvents(Boolean waitForEvents)
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.GuiScreenMods.LoadModCells() in VintagestoryLib\Client\MainMenu\Screens\GuiScreenMods.cs:line 93
   at Vintagestory.Client.GuiScreenMods.InitGui() in VintagestoryLib\Client\MainMenu\Screens\GuiScreenMods.cs:line 151
   at Vintagestory.Client.GuiScreenMods..ctor(ScreenManager screenManager, GuiScreen parentScreen) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenMods.cs:line 28
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by radfast** [comment] 2024-02-27 17:45
Thanks for reporting, this will be fixed in 1.19.4-stable coming shortly.

Meanwhile if you want to play today with these mods, check each mod's dependencies carefully: the cause of the error is one of the mods has a dependency (for example a Library) and that dependency **itself** could not be loaded due to an error - for example a version mismatch.

**Closed** 2024-02-27 17:52 UTC
Labels: status: resolved, department: code, version: 1.19
