### ISSUE TITLE
seraph glow at night even though i did not respawn 

### ISSUE THREAD

**Issue by OrphanWaffle** [anegostudios/VintageStory-Issues#1331] opened 2021-09-26 09:07 UTC
i was just fighting some drifters and i started glowing, one time i was in the house at night, clay molding and started glowing for no reason

**Comment by Ragolution** [comment] 2021-10-01 11:17
Have been able to reproduce this a number of times. My best guess is it has something to do with updates to body temperature dealing 0 damage, since it seems to only happen in winter.

**Comment by tyronx** [comment] 2021-11-03 13:16
this should be fixed in 1.15.7, if not, please reopen

**Closed by tyronx** 2021-11-03 13:16 UTC
Labels: status: new
