### ISSUE TITLE
Crash, no idea why

### ISSUE THREAD

**Issue by Heptagon-ru** [anegostudios/VintageStory-Issues#1075] opened 2021-06-26 22:51 UTC
**Game Version:** 1.15 pre8, TOPTS
**Platform:** Windows 10
**Modded:** Yes, Zoom Button (played for few hours exploring new 1,15 lands, no issues)

### Description
Was chatting and alt tabbing to Discord to report strange disconnnect of 4 people simultaneously happened just 5 mins before.
Then crashed, idk why, was just standing at my base. Maybe a tree grew? No idea.
Oh, just a possibility: I use a RAM disk for ShadowPlay temporary files, so I have 2 GB of my 16 GB mem taken. Maybe VS grows too big in memory? It seems it sometimes grows quite big. But most likely it is unrelated.
Copy of bug report of 4 people disconnecting, from Discord:
```
Had a strange disconnect on TOPTS just now.
6 people online. 4 people left the server simultaneously.
Two (me and skol) remained fine.
Those 4 people returned one by one.
One, Zooloo75, said they were walking up a stairs and pressed F5 and game disconnected them from server.
Other three just said some standard disconnect, like no response in expected time or sometrhing.
Lol, 5 minutes after that when I was writing this and alt tabbing to and fro, i crashed. Made a proper bug report to insert the crash log.
```

### How to reproduce
no idea

### Expected behavior
o,O

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.0-pre.8 (Unstable)27.06.2021 1:46:31: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Common.BlockAccessorBase.SetDecorsBulk(Int64 chunkIndex, Dictionary`2 newDecors)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _VQ30Ln02gyvoATEl8PlfeLVSgEr._B7JNvwI3nx9QEdgkJkgLg21lvde(Single )
   at _IJG2v0zGeUDfPbxVmwnXgzVbdHp._pSnRqX9ORNtB1LvHF1vzxnB3jpe(Single )
   at _IJG2v0zGeUDfPbxVmwnXgzVbdHp._g3nxKDmkyYJ7Dq7TaDsdBSLVw0A(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _yLUmmGhRYnnQv7zul2v0crZd2Tp._PwL995m4VTOZDErzGUzsRHij9rh(_rhrdlgKC766AwXQivHTdHkcGzAjb , String[] )
   at _EDKdxfQFQqcYQ64nBo1IPHJ5Kw9._PwL995m4VTOZDErzGUzsRHij9rh(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 05.06.2021 14:13:01, Site = , Source = Windows Error Reporting, Message = Fault bucket 1837167348359640725, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 6079b344
P4: mscorlib
P5: 4.8.4341.0
P6: 60230124
P7: 1694
P8: 1d8
P9: System.IO.IOException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER172B.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER19EC.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER19FC.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1A00.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1A20.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_1764dc927acd2b13639dda21195759d282faf2c_5674d60d_0fcf2832-d818-4b44-a64f-c26f9c92ab2a

Analysis symbol: 
Rechecking for solution: 0
Report Id: c7ac46fd-186b-4ebe-aaab-631ffac22dab
Report Status: 268435456
Hashed bucket: bad632bcf34946f3c97eedf837ec3695
Cab Guid: 0 }
--------------
{ TimeGenerated = 05.06.2021 14:12:59, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.14.10.0, time stamp: 0x6079b344
Faulting module name: KERNELBASE.dll, version: 10.0.18362.1474, time stamp: 0x5ae7af90
Exception code: 0xe0434352
Fault offset: 0x0000000000043b19
Faulting process id: 0x4758
Faulting application start time: 0x01d759fba6f30476
Faulting application path: D:\Games\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: c7ac46fd-186b-4ebe-aaab-631ffac22dab
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 05.06.2021 14:12:58, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32, System.IO.FileOptions, System.String, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode)
   at Hjg.Pngcs.FileHelper.OpenFileForWriting(System.String, Boolean)
   at Hjg.Pngcs.FileHelper.CreatePngWriter(System.String, Hjg.Pngcs.ImageInfo, Boolean)
   at Automap.Snapshotter+<Take>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
```

**Comment by copygirl** [comment] 2021-06-26 22:58
Duplicate of your issue #1072, which should be fixed in the next pre-release.

**Closed by copygirl** 2021-06-26 22:58 UTC
Labels: status: duplicate
