### ISSUE TITLE
Character don't make sound when getting hurt

### ISSUE THREAD

**Issue by Sparx300** [anegostudios/VintageStory-Issues#3057] opened 2023-08-28 18:41 UTC
### Game Version

v1.18.7 stable

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

My character and people i am playing with don't make sound when getting hurt, when i get to create my character i can select a voice and in this menu when i select one i can hear it properly but as soon as i start to play, no matter what, the character will stay silent. In the character creation menu there is a "*" on the voice list and it say this is an experimental feature and it won't work without being activate in the sound menu but there isn't such a feature in it. I tried to switch in 1.18.8 but the problem is still there and i can't find anything on the internet about it, nobody seem to have this problem.

### Logs

```Log```

**Comment by Th3Dilli** [comment] 2023-09-21 09:37
Duplicate of #2667

make sure to set `"newSeraphVoices": false` in your clientsettings.json

You can find that file by opening your Mods or Saves folder and then go one folder up there you should see that file.

**Closed by Th3Dilli** 2023-09-21 09:37 UTC
Labels: status: duplicate
