### ISSUE TITLE
Crash while looking at recipe

### ISSUE THREAD

**Issue by Frothgar** [anegostudios/VintageStory-Issues#290] opened 2019-05-12 17:34 UTC
I was trying to look at the recipe for a vine basket. Soon as I clicked on it, crashed. Report follows. No mods, new to the game.

Running on 64 bit Windows with 16 GB RAM 
Version: v1.9.3 (Stable)5/12/2019 1:30:34 PM: Critical error occurred
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at Newtonsoft.Json.Linq.JObject.get_Item(Object key)
   at Vintagestory.API.JsonObject.get_Item(String key)
   at Vintagestory.GameContent.BlockGenericTypedContainer.GetHeldItemInfo(ItemStack stack, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo)
   at Vintagestory.API.Common.ItemStack.GetDescription(IWorldAccessor world, Boolean debug)
   at Vintagestory.API.Client.GuiElementItemstackInfo.Recompose()
   at Vintagestory.API.Client.GuiElementItemstackInfo.SetSourceSlot(ItemSlot nowSlot)
   at Vintagestory.API.Client.ItemstackComponentBase.RenderItemstackTooltip(ItemStack stack, Double renderX, Double renderY, Single dt)
   at Vintagestory.API.Client.SlideshowItemstackTextComponent.RenderInteractiveElements(Single deltaTime, Double renderX, Double renderY)
   at Vintagestory.API.Client.GuiElementRichtext.RenderInteractiveElements(Single deltaTime)
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime)
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime)
   at _YrPLgRNoKqLkIJjZXGQBQZfF0ss._6WZTNVfTa7rWSKqb82sMCqgCFyP(Single )
   at _GUwD6VYkgVQ73AlLfKTdTWGrvUH._NqNCafwIuVnrN0APAIQT44l6CVR(EnumRenderStage , Single )
   at _PndAABz6mbLrIVY3bGkjFENAKYE._NqNCafwIuVnrN0APAIQT44l6CVR(EnumRenderStage , Single )
   at _PndAABz6mbLrIVY3bGkjFENAKYE._8Q0lcHKBmMsrZdVz5CTBHXVZQIW(Single )
   at _NkoWRZbO8vbo2P0bHOmeWW5HFZm._8Q0lcHKBmMsrZdVz5CTBHXVZQIW(Single )
   at _ClwmnLe1V7vR8n56XkbHz2NmshG._v6KGki9QaYXffAVL8MxroiYvLHZ(Single )
   at _ClwmnLe1V7vR8n56XkbHz2NmshG._bWLdqbxl84dj0WzW4hexmUSwPWP(Single )
   at _mEhEzZ8DmIQe7K9d4tBswO1fhgX._0oOO2PQajHpBpSzMJCyLMiw7tG(Object , FrameEventArgs )
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _3vfvgrHj6ymQxm8FJtx4Ruzypih._Z3lNUjeecYm8PMLFsAqAg3ack5w(_mmIyrGEQIkHEG3raFL54FrKNncQ , String[] )
   at _VPmpDmTQc9Jyy6X2oS97VHCLE8A._Z3lNUjeecYm8PMLFsAqAg3ack5w(ThreadStart )
-------------------------------

**Comment by siasur** [comment] 2019-05-12 18:03
This is known and will be fixed in the next version. See bug report #287

**Comment by Frothgar** [comment] 2019-05-12 19:06
Good to know, Thanks! Fun game.

**Comment by tyronx** [comment] 2019-05-12 19:11
indeed, duplicate of #287

**Closed by tyronx** 2019-05-12 19:11 UTC
