### ISSUE TITLE
Creatures killed by rock sling not counted as player kill

### ISSUE THREAD

**Issue by SunnyOpossum** [anegostudios/VintageStory-Issues#2647] opened 2023-04-22 19:45 UTC
### Game Version

v1.18.1

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Killing a creature by using a rock sling to shoot rocks at it will cause the corpse to display "Killed by another creature".
Causes the normal "killed by another creature" loot reduction.

### How to reproduce

1.Kill a sheep or something with rocks shot from a sling
2.Observe corpse and reduced loot

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2023-04-22 19:49
Duplicate of #2583

**Closed by Craluminum2413** 2023-04-22 19:49 UTC
Labels: status: new
