### ISSUE TITLE
Crash while running over cobblestone? (I think)

### ISSUE THREAD

**Issue by SakurraKoi** [anegostudios/VintageStory-Issues#4293] opened 2024-10-12 20:11 UTC
### Game Version

1.20.pre5

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

Honestly I am not 100% sure what caused the crash, I was breaking cobblestone blocks so they were lying on the ground and I was walking/running around picking them up and then crashed.

### Logs
```
Running on 64 bit Windows 10.0.22631.0 with 32694 MB RAM
Game Version: v1.20.0-pre.5 (Unstable)
10/12/2024 4:02:55 PM: Critical error occurred
Loaded Mods: juicyores@1.0.0, primitivesurvival@3.6.7, game@1.20.0-pre.5, vtr@4.0.4, alchemy@1.6.36, egocaribautomapmarkers@4.0.0, carryon@1.8.0-pre.1, nemi@1.1.0, stepupcontinued@0.0.1, vtpp@1.1.1, creative@1.20.0-pre.5, survival@1.20.0-pre.5
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.ClientAnimator.calculateMatrices(Single dt) in VintagestoryApi\Common\Model\Animation\ClientAnimator.cs:line 294
   at Vintagestory.API.Common.AnimatorBase.OnFrame(Dictionary`2 activeAnimationsByAnimCode, Single dt) in VintagestoryApi\Common\Model\Animation\AnimatorBase.cs:line 109
   at Vintagestory.API.Common.AnimationManager.OnClientFrame(Single dt) in VintagestoryApi\Common\Model\Animation\AnimationManager.cs:line 430
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 74
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 818
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 824
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 740
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 207
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
``

**Comment by Craluminum2413** [comment] 2024-10-12 20:17
Does it happen without any mods?

**Comment by Craluminum2413** [comment] 2024-10-12 20:18
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4243

**Closed by Craluminum2413** 2024-10-12 20:18 UTC
Labels: status: incomplete
