### ISSUE TITLE
Game repeatedly crashing trying to load or create new world.

### ISSUE THREAD

**Issue by thebongmaster** [anegostudios/VintageStory-Issues#3524] opened 2024-01-27 18:47 UTC
### Game Version

Latest

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Game crashing since last update when trying to open world, modded or not. all mods have been disabled with same effect. last crash happened trying to create new world and failed to create logs. logs supplied are from an attempt to open saved world with no mods enabled.

### How to reproduce

run game, try and play it. that is all i did

### Logs

```Running on 64 bit Windows 10.0.19045.0 with 65318 MB RAM
Game Version: v1.19.3 (Stable)
27/01/2024 19:42:13: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Common.WorldConfig.loadWorldConfigValuesFromPlaystyle() in VintagestoryLib\Common\Config\WorldConfig.cs:line 107
   at Vintagestory.Common.WorldConfig.selectPlayStyle(String playstylecode) in VintagestoryLib\Common\Config\WorldConfig.cs:line 98
   at Vintagestory.Common.WorldConfig.loadFromSavegame(SaveGame savegame) in VintagestoryLib\Common\Config\WorldConfig.cs:line 56
   at Vintagestory.Client.GuiScreenSingleplayerModify.initGui(SaveGame savegame) in VintagestoryLib\Client\MainMenu\Screens\Singleplayer\GuiScreenSingleplayerModify.cs:line 44
   at Vintagestory.Client.GuiScreenSingleplayerModify.OnScreenLoaded() in VintagestoryLib\Client\MainMenu\Screens\Singleplayer\GuiScreenSingleplayerModify.cs:line 168
   at Vintagestory.Client.ScreenManager.LoadScreen(GuiScreen screen) in VintagestoryLib\Client\ScreenManager.cs:line 944
   at Vintagestory.Client.GuiScreenSingleplayer.OnClickCellRight(Int32 cellIndex) in VintagestoryLib\Client\MainMenu\Screens\Singleplayer\GuiScreenSingleplayer.cs:line 154
   at Vintagestory.API.Client.GuiElementMainMenuCell.OnMouseUpOnElement(MouseEvent args, Int32 elementIndex) in VintagestoryApi\Client\UI\Elements\Impl\Misc\GuiElementMainMenuCell.cs:line 319
   at Vintagestory.API.Client.GuiElementCellList`1.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementCellList.cs:line 240
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\GuiElement.cs:line 719
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 445
   at GuiScreen.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\MainMenu\Screens\Special\GuiScreen.cs:line 204
   at Vintagestory.Client.ScreenManager.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\ScreenManager.cs:line 889
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 211
   at OpenTK.Windowing.Desktop.NativeWindow.OnMouseUp(MouseButtonEventArgs e)
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.NativeWindow.ProcessWindowEvents(Boolean waitForEvents)
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 27/01/2024 19:41:38, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.3.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process ID: 0x6c8c
Faulting application start time: 0x01da51503fec6c5f
Faulting application path: H:\Vintagestory\Vintagestory.exe
Faulting module path: H:\Vintagestory\Lib\openal32.dll
Report ID: 78bb13b2-8d03-4f2d-a3a5-19bc1849c7fc
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 27/01/2024 19:40:07, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.3.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process ID: 0x7b7c
Faulting application start time: 0x01da51502773c0ef
Faulting application path: H:\Vintagestory\Vintagestory.exe
Faulting module path: H:\Vintagestory\Lib\openal32.dll
Report ID: 099bfc56-5e62-4167-93aa-c159254f6e32
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 27/01/2024 19:39:26, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.3.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process ID: 0x9ac
Faulting application start time: 0x01da514fe47fa648
Faulting application path: H:\Vintagestory\Vintagestory.exe
Faulting module path: H:\Vintagestory\Lib\openal32.dll
Report ID: 53145159-a869-4300-86ee-c1a825f794a5
Faulting package full name: 
Faulting package-relative application ID:  }```

**Comment by thebongmaster** [comment] 2024-01-27 18:51
this log is from clicking the edit button for a world:
`Running on 64 bit Windows 10.0.19045.0 with 65318 MB RAM
Game Version: v1.19.3 (Stable)
27/01/2024 19:50:01: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Common.WorldConfig.loadWorldConfigValuesFromPlaystyle() in VintagestoryLib\Common\Config\WorldConfig.cs:line 107
   at Vintagestory.Common.WorldConfig.selectPlayStyle(String playstylecode) in VintagestoryLib\Common\Config\WorldConfig.cs:line 98
   at Vintagestory.Common.WorldConfig.loadFromSavegame(SaveGame savegame) in VintagestoryLib\Common\Config\WorldConfig.cs:line 56
   at Vintagestory.Client.GuiScreenSingleplayerModify.initGui(SaveGame savegame) in VintagestoryLib\Client\MainMenu\Screens\Singleplayer\GuiScreenSingleplayerModify.cs:line 44
   at Vintagestory.Client.GuiScreenSingleplayerModify.OnScreenLoaded() in VintagestoryLib\Client\MainMenu\Screens\Singleplayer\GuiScreenSingleplayerModify.cs:line 168
   at Vintagestory.Client.ScreenManager.LoadScreen(GuiScreen screen) in VintagestoryLib\Client\ScreenManager.cs:line 944
   at Vintagestory.Client.GuiScreenSingleplayer.OnClickCellRight(Int32 cellIndex) in VintagestoryLib\Client\MainMenu\Screens\Singleplayer\GuiScreenSingleplayer.cs:line 154
   at Vintagestory.API.Client.GuiElementMainMenuCell.OnMouseUpOnElement(MouseEvent args, Int32 elementIndex) in VintagestoryApi\Client\UI\Elements\Impl\Misc\GuiElementMainMenuCell.cs:line 319
   at Vintagestory.API.Client.GuiElementCellList`1.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\GuiElementCellList.cs:line 240
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 445
   at GuiScreen.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\MainMenu\Screens\Special\GuiScreen.cs:line 204
   at Vintagestory.Client.ScreenManager.OnMouseUp(MouseEvent e) in VintagestoryLib\Client\ScreenManager.cs:line 889
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 211
   at OpenTK.Windowing.Desktop.NativeWindow.OnMouseUp(MouseButtonEventArgs e)
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.NativeWindow.ProcessWindowEvents(Boolean waitForEvents)
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 27/01/2024 19:43:23, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.3.0, time stamp: 0x65310000
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc00000fd
Fault offset: 0x00007ff8625f9be3
Faulting process ID: 0x7768
Faulting application start time: 0x01da51509c5885ee
Faulting application path: H:\Vintagestory\Vintagestory.exe
Faulting module path: unknown
Report ID: 7cb5e61d-4478-4643-bd3d-0e2cf7af84e2
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 27/01/2024 19:41:38, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.3.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process ID: 0x6c8c
Faulting application start time: 0x01da51503fec6c5f
Faulting application path: H:\Vintagestory\Vintagestory.exe
Faulting module path: H:\Vintagestory\Lib\openal32.dll
Report ID: 78bb13b2-8d03-4f2d-a3a5-19bc1849c7fc
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 27/01/2024 19:40:07, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.3.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process ID: 0x7b7c
Faulting application start time: 0x01da51502773c0ef
Faulting application path: H:\Vintagestory\Vintagestory.exe
Faulting module path: H:\Vintagestory\Lib\openal32.dll
Report ID: 099bfc56-5e62-4167-93aa-c159254f6e32
Faulting package full name: 
Faulting package-relative application ID:  }`

**Comment by thebongmaster** [comment] 2024-01-28 15:36
i tried rolling back to previous versions and am still getting CTDs game will not run now past the menus

**Comment by thebongmaster** [comment] 2024-01-28 18:33
It seems the update broke it, installing from the full installer made it work again, and after doing an update from the update alert ingame it broke it again. so ran the full installer for latest ver and its working. so i think the updater is breaking something

**Comment by Craluminum2413** [comment] 2024-02-05 10:30
Duplicate of #2692

**Closed by Craluminum2413** 2024-02-05 10:30 UTC
Labels: status: new
