### ISSUE TITLE
Vintage Story Crah 

### ISSUE THREAD

**Issue by CombatBrutus** [anegostudios/VintageStory-Issues#434] opened 2020-03-05 19:23 UTC
Vintage Story
Windows 10
No

### Description
When trying to run the game it crash
-------------------------------

### How to reproduce
Start the game up

### Expected behavior
If not obvious, what did you expect to happen?

### Screenshots
Attach a screenshot if it helps explain the issue / shows a visual bug.

### Logs
```
Running on 64 bit Windows with 8 GB RAM 
Version: v1.12.5 (Stable)3/5/2020 2:18:03 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.NoObf.ClientPlatformWindows.LoadTexture(IBitmap bmp, Boolean linearMag, Int32 clampMode, Boolean generateMipmaps)
   at _mKeEWUbBZsjLS6VlGWgOoYQFk2K._KNs6g2GMtsTu5gnL4MXdRgZVlLh()
   at _lt8TgSVuBImgzFgAFlSeVzSFsSy._HdDsdRJDH8nMF88r278C4eqdINGA()
   at _lt8TgSVuBImgzFgAFlSeVzSFsSy._gjiBClIE7Yspuz65gCqPGSAnUYeb()
   at _lt8TgSVuBImgzFgAFlSeVzSFsSy._NbPATb9BXlxRc4ZhH2GgyFCUInp(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _hCuHXesCXlp0LGSdrsPFpw4up5n._mOm8EuKIvHpaJoztxNWRpAoOpbM(_55ISULxdcpPfF8D2JP831aWhOBe , String[] )
   at _iCfIbY24GyBXP5lAwqsSlD9COxC._mOm8EuKIvHpaJoztxNWRpAoOpbM(ThreadStart )
-------------------------------

In the game's Logs folder you may be able to find more information
inside client-main.txt and server-main.txt. Alternatively, you may use
gist.github.com to upload logs, linking them here, if they're too large.

Note that the crash log contains all crashes that have happened so far.
You likely only want to report the latest one.
```

**Comment by lambertschulz** [comment] 2020-03-05 19:30
I have the same issue:
I try to start the game and  while loading it crashes.



Logs: (in german)
[client-debug.txt](https://github.com/anegostudios/VintageStory-Issues/files/4294796/client-debug.txt)
[client-main.txt](https://github.com/anegostudios/VintageStory-Issues/files/4294797/client-main.txt)
[client-crash.txt](https://github.com/anegostudios/VintageStory-Issues/files/4294798/client-crash.txt)

Error: (in german)

Running on 64 bit Windows with 16 GB RAM 
Version: v1.12.4 (Stable)05.03.2020 20:25:27: Critical error occurred
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.LoadTexture(IBitmap bmp, Boolean linearMag, Int32 clampMode, Boolean generateMipmaps)
   bei _Nm2Dey99KsdwIYLpu4GOdoFloZP._qP4paZogWeAkBAdIetsRHNRsPeR()
   bei _EQxWmablZ9e1a2ttf5sknNEhthE._ryUq828Jdon4eHk5toV3WI6D1nH()
   bei _EQxWmablZ9e1a2ttf5sknNEhthE._TNhCFDnDMOpUfVxHZgPyWvoTAtF()
   bei _EQxWmablZ9e1a2ttf5sknNEhthE._wVES3I4AcneyUTHpdRuLu6EHvCH(Single )
   bei Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   bei System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   bei OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   bei OpenTK.GameWindow.DispatchRenderFrame()
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei _KgkCdVM1WnzOB8EQZYjMqMgiQif._FmdhOaaNJf4xNNi98fb5q9puBYb(_vzXUYcAd8hQnBWAaPoIw4RI2yoU , String[] )
   bei _RenJRmDtixD6Tekd8S9clc9cPZV._FmdhOaaNJf4xNNi98fb5q9puBYb(ThreadStart )
-------------------------------

**Comment by copygirl** [comment] 2020-03-05 19:36
Update the game to 1.¹2.6 please. The bug is already fixed.
Closing as duplicate of #407.

**Closed by copygirl** 2020-03-05 19:36 UTC
Labels: status: duplicate
