### ISSUE TITLE
Crash when tool is used and another prepared

### ISSUE THREAD

**Issue by konradszkudlarczyk** [anegostudios/VintageStory-Issues#3089] opened 2023-09-10 09:50 UTC
### Game Version

18.10

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

When tool (e.g. shovel) is almost fully used and new tool is prepared in crafting grid (but not created), when old tool is destroyed, game crashes.

### How to reproduce

1 Have almost completely used shovel in hand
2 Press 'e' and prepare new shovel in crafting grid - but don't create it and leave this window open
3 Use old shovel

### Logs

Running on 64 bit Windows with 32699 MB RAM
Game Version: v1.18.10 (Stable)
10/09/2023 11:23:40: Critical error occurred
Loaded Mods: game@1.18.10, creative@1.18.10, survival@1.18.10
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Common.ItemSlotCraftingOutput.triggerEvent(ItemStack craftedStack, Int32 moved, IPlayer actingPlayer) in VintagestoryLib\Common\GameContent\Inventory\ItemSlotCraftingOutput.cs:line 72
   at Vintagestory.Common.ItemSlotCraftingOutput.TryPutInto(ItemSlot sinkSlot, ItemStackMoveOperation& op) in VintagestoryLib\Common\GameContent\Inventory\ItemSlotCraftingOutput.cs:line 63
   at Vintagestory.API.Common.ItemSlot.TryPutInto(IWorldAccessor world, ItemSlot sinkSlot, Int32 quantity) in VintagestoryApi\Common\Inventory\ItemSlot.cs:line 176
   at Vintagestory.API.Common.CollectibleObject.<>c__DisplayClass79_0.<RefillSlotIfEmpty>b__0(ItemSlot invslot) in VintagestoryApi\Common\Collectible\Collectible.cs:line 843
   at Vintagestory.API.Common.EntityPlayer.WalkInventory(OnInventorySlot handler) in VintagestoryApi\Common\Entity\EntityPlayer.cs:line 1203
   at Vintagestory.API.Common.CollectibleObject.RefillSlotIfEmpty(ItemSlot slot, EntityAgent byEntity, ActionConsumable`1 matcher) in VintagestoryApi\Common\Collectible\Collectible.cs:line 834
   at Vintagestory.API.Common.CollectibleObject.DamageItem(IWorldAccessor world, Entity byEntity, ItemSlot itemslot, Int32 amount) in VintagestoryApi\Common\Collectible\Collectible.cs:line 825
   at Vintagestory.API.Common.CollectibleObject.OnBlockBrokenWith(IWorldAccessor world, Entity byEntity, ItemSlot itemslot, BlockSelection blockSel, Single dropQuantityMultiplier) in VintagestoryApi\Common\Collectible\Collectible.cs:line 555
   at Vintagestory.Client.NoObf.ClientMain.OnPlayerTryDestroyBlock(BlockSelection blockSelection) in VintagestoryLib\Client\ClientMain.cs:line 1678
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.ContinueBreakSurvival(BlockSelection blockSelection, Block block, Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 798
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 447
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 92
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 790
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 983
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 76
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 312
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 10/09/2023 11:18:05, Site = , Source = Windows Error Reporting, Message = Fault bucket 2214170192790503688, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.10.0
P3: 64b07659
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4763.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER49D5.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER49D6.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER49E4.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER49F5.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_38893ed42eb8d1a668828edf5bed1a44a4c7eb_93d687c4_31a2b46d-4954-4ca1-8d7b-82a085c7daa8

Analysis symbol: 
Rechecking for solution: 0
Report Id: ea24487d-917c-4fc4-9cb1-631db28dbfce
Report Status: 268566528
Hashed bucket: e045985d4f8a18ca4eba500f25894108
Cab Guid: 0 }
--------------
{ TimeGenerated = 10/09/2023 11:18:04, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.10.0, time stamp: 0x64b07659
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process ID: 0x1a44
Faulting application start time: 0x01d9e3c746d89dea
Faulting application path: C:\Program Files (x86)\Vintagestory\Vintagestory.exe
Faulting module path: C:\Program Files (x86)\Vintagestory\Lib\openal32.dll
Report ID: ea24487d-917c-4fc4-9cb1-631db28dbfce
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 10/09/2023 11:15:01, Site = , Source = Windows Error Reporting, Message = Fault bucket 2214170192790503688, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.10.0
P3: 64b07659
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER76AF.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER78F2.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7903.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7907.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7918.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_38893ed42eb8d1a668828edf5bed1a44a4c7eb_93d687c4_165e5f5c-66ff-4362-b619-5e96c668c5b1

Analysis symbol: 
Rechecking for solution: 0
Report Id: 2ea88c7c-03a5-40b3-82ab-fdf2e463710c
Report Status: 268566528
Hashed bucket: e045985d4f8a18ca4eba500f25894108
Cab Guid: 0 }

**Comment by Th3Dilli** [comment] 2023-09-12 17:15
Duplicate of #2741

**Closed by Th3Dilli** 2023-09-12 17:15 UTC
Labels: target: survival, status: new
