### ISSUE TITLE
Ульевая печь не принимает огнеупорные кирпичи

### ISSUE THREAD

**Issue by tehtelev** [anegostudios/VintageStory-Issues#4761] opened 2024-12-21 09:35 UTC
### Game Version

v1.20-rc.5

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

I built a beehive furnace back on the "pre" version of the game. On the latest version, I threw in fuel and ceramics for firing and set them on fire. I am informed that the building is not completed, as the wrong blocks are being used. I use fire-resistant bricks of the 1st and 2nd level. Demolished it and rebuilt it - no result. Fire-resistant grilles are considered correctly

### How to reproduce

1. Start building a beehive furnace.
2. Press Shift+Right click on the fireproof door

### Screenshots

![2024-12-21_12-27-28](https://github.com/user-attachments/assets/04cd4ba7-b20e-434f-b6fb-2788adc22421)
![2024-12-21_12-27-58](https://github.com/user-attachments/assets/f8681aa2-6076-4932-897d-f5188ce9dccd)

### Logs

```Log```

**Comment by Craluminum2413** [comment] 2024-12-21 11:39
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4721

**Closed by Craluminum2413** 2024-12-21 11:39 UTC
Labels: status: new
