### ISSUE TITLE
Attempting to re-use a seed crashes the game

### ISSUE THREAD

**Issue by Machaeus** [anegostudios/VintageStory-Issues#1084] opened 2021-07-01 02:06 UTC
**Game Version:** 1.14.10 (stable)  
**Platform:** Windows 10 
**Modded:** No

### Description
Clicked "make a new world with this seed," crashed the game instantly.

### How to reproduce
1. Log in
2. Choose a world's pencil
3. Click "Create a new world with this world seed"
4. It crashes.

### Logs
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.14.10 (Stable)6/30/2021 6:41:35 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at _XdIuBv24vQ1JZohJexy6wrKepcG._plbbXOc9b5uBS8CNUoxbNm2MgS7()
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   at _tQNG2d15aM4IHF2517OUDULPBHL._TqANHNj1JY1XBE9yPv18vWLJBlG(MouseEvent )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _ISiSTzGmXXpAqo3PzdxdVD1bClZ._ofvn0Tr1zNGCbNV3SxvKs2MXNP(_C7CLMRbe3BejVtaARYCgl7Bg1vl , String[] )
   at _0Y0SN1uu1V65pRLxvnN2xsIjXAg._ofvn0Tr1zNGCbNV3SxvKs2MXNP(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 6/25/2021 2:07:25 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2274906873183596421, type 5
Event Name: BEX64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 6079b344
P4: atio6axx.dll
P5: 27.20.12031.1000
P6: 5f6acb67
P7: 0000000001b09809
P8: c0000409
P9: 0000000000000007
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREFD6.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF296.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF2A7.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF2A5.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF2B5.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_cd6541a4d93fa8b11f81ea63ce12cbf3613692_5674d60d_ef73b1e2-dbe4-4b76-a283-a810056aca78

Analysis symbol: 
Rechecking for solution: 0
Report Id: 5871b2a2-5731-4e79-a85c-bc13bb784554
Report Status: 268566528
Hashed bucket: f7070d254d17a2029f9217bf8933ef85
Cab Guid: 0 }
--------------
{ TimeGenerated = 6/25/2021 2:07:23 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.14.10.0, time stamp: 0x6079b344
Faulting module name: atio6axx.dll, version: 27.20.12031.1000, time stamp: 0x5f6acb67
Exception code: 0xc0000409
Fault offset: 0x0000000001b09809
Faulting process id: 0x45f8
Faulting application start time: 0x01d769fabdb8b5aa
Faulting application path: C:\Users\Machaeus\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\System32\DriverStore\FileRepository\u0359518.inf_amd64_ddc5c961c2795261\B359297\atio6axx.dll
Report Id: 5871b2a2-5731-4e79-a85c-bc13bb784554
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 6/25/2021 1:12:23 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1617108784218071861, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 10.0.19041.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Machaeus\AppData\Local\Temp\RDR8EDD.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8EED.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8EFE.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8F1B.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8F4B.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: a771cbbc-4765-43f0-a57e-4f3cb4c23449
Report Status: 268435456
Hashed bucket: 53ec02d71894ee5b26711fdf167b6335
Cab Guid: 0 }
```

**Comment by copygirl** [comment] 2021-07-01 04:21
Duplicate of #795. Thanks for reporting!

**Closed by copygirl** 2021-07-01 04:21 UTC
Labels: status: duplicate
