### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Setimu** [anegostudios/VintageStory-Issues#812] opened 2021-03-13 04:13 UTC
**Game Version:** 1.14.8
**Platform:** Windows
**Modded:** No

### Description
Crash

### How to reproduce
Crashed upon selecting "Create a new world with this seed" option in single player.

### Logs
```
Running on 64 bit Windows with 8 GB RAM 
Version: v1.14.8 (Stable)3/12/2021 23:07:44: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at _PW8NVVq6wBR9krMQ9GulRnv6PMD._h9K0G4wbrt2CCpt5A92lCnKV2gP()
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   at _oDnqPT3M9pq9hNGZM4RDtA6RTnG._TE0ypoo5kb57Ue2gLv7daIuY6VD(MouseEvent )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _YrS2W1MoaeqC4xqH8ItdZB6vADN._8t1BmEWVlCT9mjx5M0vFIzU9tif(_7T00Rjby4si0wyEBez5dXNqLm7h , String[] )
   at _ejKuc6cg0k8V39o8jDIzquyczbO._8t1BmEWVlCT9mjx5M0vFIzU9tif(ThreadStart )
-------------------------------
```

**Comment by Setimu** [comment] 2021-03-13 04:13
Immediately repeated upon trying again.

Running on 64 bit Windows with 8 GB RAM 
Version: v1.14.8 (Stable)3/12/2021 23:13:29: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at _PW8NVVq6wBR9krMQ9GulRnv6PMD._h9K0G4wbrt2CCpt5A92lCnKV2gP()
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   at _oDnqPT3M9pq9hNGZM4RDtA6RTnG._TE0ypoo5kb57Ue2gLv7daIuY6VD(MouseEvent )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _YrS2W1MoaeqC4xqH8ItdZB6vADN._8t1BmEWVlCT9mjx5M0vFIzU9tif(_7T00Rjby4si0wyEBez5dXNqLm7h , String[] )
   at _ejKuc6cg0k8V39o8jDIzquyczbO._8t1BmEWVlCT9mjx5M0vFIzU9tif(ThreadStart )
-------------------------------

**Comment by copygirl** [comment] 2021-03-13 07:56
Duplicate of #795.

**Closed by copygirl** 2021-03-13 07:56 UTC
Labels: status: duplicate
