### ISSUE TITLE
Error while tryng to put the ratlines

### ISSUE THREAD

**Issue by Resserfis** [anegostudios/VintageStory-Issues#4300] opened 2024-10-13 16:31 UTC
### Game Version

v1.20-pre.6

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

Well i just tried to put a rat line in the thing that changes the wind of the sail and my game crashed

(use traductor for the final part of the crash txt)

### How to reproduce

1 make a sailboat 2 get a ratline 3 put the rat line in the sail thing that has string 4 boom it crashes

### Screenshots

Nothing

### Logs

Running on 64 bit Windows 10.0.19045.0 with 16307 MB RAM
Game Version: v1.20.0-pre.6 (Unstable)
13/10/2024 18:23:43: Critical error occurred
Loaded Mods: game@1.20.0-pre.6, creative@1.20.0-pre.6, survival@1.20.0-pre.6
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.EntityBehaviorAttachable.TryAttach(ItemSlot itemslot, Int32 slotIndex, EntityAgent byEntity) in VSSurvivalMod\Entity\Behavior\BehaviorAttachable.cs:line 298
   at Vintagestory.GameContent.EntityBehaviorAttachable.OnInteract(EntityAgent byEntity, ItemSlot itemslot, Vec3d hitPosition, EnumInteractMode mode, EnumHandling& handled) in VSSurvivalMod\Entity\Behavior\BehaviorAttachable.cs:line 185
   at Vintagestory.GameContent.EntityBoat.OnInteract(EntityAgent byEntity, ItemSlot itemslot, Vec3d hitPosition, EnumInteractMode mode) in VSSurvivalMod\Systems\Boats\EntityBoat.cs:line 479
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsNoBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 394
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 819
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1023
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 13/10/2024 11:58:49, Site = , Source = Application Error, Message = Nombre de la aplicación con errores: Vintagestory.exe, versión: 1.20.0.0, marca de tiempo: 0x66470000
Nombre del módulo con errores: KERNELBASE.dll, versión: 10.0.19041.4842, marca de tiempo: 0xe6d00f33
Código de excepción: 0xe0434352
Desplazamiento de errores: 0x000000000003b699
Identificador del proceso con errores: 0x4be0
Hora de inicio de la aplicación con errores: 0x01db1ccd97ed8313
Ruta de acceso de la aplicación con errores: D:\Vintagestory\Vintagestory.exe
Ruta de acceso del módulo con errores: C:\WINDOWS\System32\KERNELBASE.dll
Identificador del informe: 24e2a75a-20fd-4f95-93eb-166199461d39
Nombre completo del paquete con errores: 
Identificador de aplicación relativa del paquete con errores:  }

**Comment by Craluminum2413** [comment] 2024-10-13 16:35
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4093

**Closed by Craluminum2413** 2024-10-13 16:35 UTC
Labels: status: new
