### ISSUE TITLE
Handbook search treats similar letters the same (with undesired results)

### ISSUE THREAD

**Issue by MyraMidnight** [anegostudios/VintageStory-Issues#4711] opened 2024-12-16 10:22 UTC
### Game Version

v1.20.0-rc.4

### Platform

Windows

### Modded

Vanilla

### SP/MP

Singleplayer

### Description

It seems that just adding a space to the search is giving me unrelated items, and that space is needed to add the `or` keyword for more advanced search (since I have to go through all the `handbooksearch` links while translating, it can't find things when names have changed due to translation). Trying to write `grófur bogi or gróf ör`

Makes me wonder if it treats `ör` same as `or` in this context, which would be weird.

I have discovered that it does indeed treat `ó` and `ö` same as an `o`, so I do get the crude arrow when writing `gróf or`, `gróf ör` and `gróf ór`, so that might indeed be the issue with the search. So I essentially cannot search for singular arrows with the current search.

### How to reproduce

1. set game language to Icelandic
2. open handbook
3. search for `gróf ör`
4. add a space to the search `gróf ör `

### Screenshots

![search-issue](https://github.com/user-attachments/assets/c05d50c3-ef79-4336-9d39-3390ad3728a4)
![search-issue-2](https://github.com/user-attachments/assets/2d267685-6a61-4e1d-ab10-508e787cbfd7)

### Logs

```Log```

**Comment by MyraMidnight** [comment] 2024-12-16 10:44
It almost seems like the search needs a "specific" search ability, like google search, that I want that specific query in my results, not all variations of it. 

Sure I have since discovered I can slightly hack it by putting the `gróf ör` last in the search query so it won't be treated as an `or`, but that does not take away from the fact that it is blind to variations of letters.

**Comment by Craluminum2413** [comment] 2024-12-16 11:13
rc.4?

**Comment by MyraMidnight** [comment] 2024-12-16 11:17
Yes, sorry about that @Craluminum2413

**Comment by radfast** [comment] 2024-12-16 11:40
I believe this is intended behaviour, as with other languages which are perhaps not so precise as Icelandic, many players will run searches without typing the accents.   I guess if it was really smart it could interpret any search term with an accent as an explicit search for that....

But can you not workaround the issue, while improving localizations, by looking at the language file directly, in a text editor?  In the game's installation folder, file `/assets/game/lang/is.json`.  Then you can search as needed, in a good text editor (I use EditPad Lite 8 myself) you can even do a Regex search.

(In case you ask this, I do not think there is any automated way to simply edit the `is.json` file directly and have that edited version then officially in the game, it has to be done via CrowdIn.  It is maybe possible that tyron can manually update what's on CrowdIn on a one-off basis for one language only, but I don't know if he would have time or whether it's technically possible even - one other issue with that is it would wipe any other translations which are recently added to CrowdIn.  I'm afraid in general the best way to localize is always to update through the CrowdIn platform - and that also has the great advantage that any other community member interested in helping with the localization can immediately see what is going on, for almost all our languages more than one person is involved, as it's obviously a huge amount of work for one person.)

**Comment by radfast** [comment] 2024-12-16 11:44
Great job in it being already 86% translated, btw

**Comment by MyraMidnight** [comment] 2024-12-16 11:45
@radfast this issue came up when I was translating the `handbooksearch` links, I did find a workaround by simply putting the `gróf ör` last in the query (so it won't end up with a space behind it, triggering the 'or' keyword). I doubt I will run into this issue again, with words overlapping with an actual keyword, but still felt I should mention the issue.

I have been using the crowdin platform for translating

**Comment by radfast** [comment] 2024-12-16 11:48
OK we can at least mitigate this a bit for the future by treating "or" as a logical keyword, only if it is unaccented.

Can I then treat this as "Resolved"?   I would see a call to add a Google-type explicit search mode as more of a suggestion than a bug with what is currently offered.

**Comment by MyraMidnight** [comment] 2024-12-16 11:50
@radfast sounds good and solved then

**Comment by radfast** [comment] 2024-12-16 11:54
In general with any links in the translation e.g. `<a href=\"handbook:\/\/gamemechanicinfo-stonelayers\">setbergi<\/a>` the text inside the `<>` pairs should be left exactly as is.  It's possible, however, that some of the links are bugged or at least outdated (VS does very occasionally change the internal names for items, that is what the remapping files are for), you'd need to compare the current `en.json` to be sure, and even then the `en.json` might have a typo or might have become outdated without us noticing....    As with most things, the community will put us right in the end, but please do feel free to open an issue for any incorrect links you discover in `en.json`.

We probably also have discussions of things in the handbook where there _could be_ more links, but none is currently included.

**Comment by MyraMidnight** [comment] 2024-12-16 11:56
It is the `handbooksearch` links specifically that break during translation, and need to be translated to work again. 
![image](https://github.com/user-attachments/assets/03804a1c-6211-4608-af4e-665de721b980)
Since it just pastes the query into the search, and wont find things if they currently aren't named the same

**Comment by radfast** [comment] 2024-12-16 11:58
oh I see!  Sorry for being slow, I see the problem

**Comment by MyraMidnight** [comment] 2024-12-16 12:01
those handbook search links are the most painful thing about translating, easy to break

**Comment by radfast** [comment] 2024-12-16 14:17
OK the fix is in place for 1.20-rc.5, any search for "grófur bogi or gróf ör" will work correctly after that version is out.  You can also use uppercase `OR` if you prefer, to make things more obvious.  And while doing this I have added the ability to use 'AND' in searches.

**Closed by radfast** 2024-12-16 14:17 UTC
Labels: status: new, department: code
