### ISSUE TITLE
Held glass blocks are transparent through the player

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#2872] opened 2023-07-01 00:40 UTC
### Game Version

1.18.6

### Platform

Windows

### Modded

None

### SP/MP

Multiplayer

### Description

The image says it all. I'm looking at another player holding glass.
![image](https://github.com/anegostudios/VintageStory-Issues/assets/13642054/ab032571-9298-458a-ae22-e6eced5a9d74)

**Comment by Craluminum2413** [comment] 2023-07-01 01:04
Duplicate of #1850

**Closed by Craluminum2413** 2023-07-01 01:04 UTC
Labels: status: new
