### ISSUE TITLE
ClientAnimator crash

### ISSUE THREAD

**Issue by WickedSchnitzel** [anegostudios/VintageStory-Issues#4786] opened 2024-12-24 19:42 UTC
### Game Version

1.20.0-rc.6

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

People are frequently crashing.
I think i have posted this before, but was not able to find it again.

### Logs

Running on 64 bit Windows 10.0.22631.0 with 16088 MB RAM
Game Version: v1.20.0-rc.6 (Unstable)
12/24/2024 2:37:48 PM: Critical error occurred
Loaded Mods: ancientarmory@1.0.6, bettercrates@1.8.0-rc.4, canoemod@1.0.2, chiseltools@1.14.4, decor@1.2.0, extrachests@1.8.0, fantasycreatures@0.7.1, fixedpaths@1.0.1, pantherinae@1.1.14, foundrymod@1.0.0, moreicons_cs@1.1.0, primitivesurvival@3.7.4, nvscaffolding@1.0.1, translocatorengineeringredux@1.5.4, game@1.20.0-rc.6, weaponpackalphaunoff@1.5.1, animalcages@3.0.3, apegrapes@1.1.3, betterruins@0.4.2, butterflycases@1.0.1, carryon@1.8.0-pre.1, commonlib@2.6.1, decayingcreatures@0.1.1, fairplayguardian@1.1.7, furniturelibrary@1.0.14, gourmand@1.2.7, heatretention@1.0.2, playerlist@2.1.5, rifteye@0.4.0, simplefootstepsredux@1.0.1, sleepvote@1.0.7, tentbag@2.2.0, th3dungeon@0.3.1, thecritterpack@0.9.1, vanity@2.2.1, vinconomy@0.4.0-rc.4, creative@1.20.0-rc.6, vsquest@1.2.0, vsserverpanel@0.1.5, survival@1.20.0-rc.6, wildgrass@1.1.3, youvegotmail@1.0.8, cob2@1.6.9, em@3.0.0-pre.3, outerspacetunesvolume1@1.0.2, outerspacetunesvolume2@1.0.2, playercorpse@1.11.0, stonequarry@3.4.2, cob@2.0.0, outerspacetunesmaster@1.0.2
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.ClientAnimator.calculateMatrices(Single dt) in VintagestoryApi\Common\Model\Animation\ClientAnimator.cs:line 294
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 49
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 188
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 825
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 161
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 334
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 12/24/2024 1:59:52 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0xa40
Faulting application start time: 0x0x1db5635e517a765
Faulting application path: C:\Users\cjohn\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\cjohn\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 687dfdd4-af13-4304-b4c2-7bb3c0f82cba
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 12/24/2024 1:23:47 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0xf20
Faulting application start time: 0x0x1db5630dc877902
Faulting application path: C:\Users\cjohn\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\cjohn\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 62e1ab7a-d1f6-45bf-ace1-fb63f5a63848
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 12/24/2024 12:14:08 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.0.0, time stamp: 0x66470000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x410c
Faulting application start time: 0x0x1db5626ebda077d
Faulting application path: C:\Users\cjohn\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\cjohn\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: d9245a14-7f7a-436d-8a1e-b030a81ab69c
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Craluminum2413** [comment] 2024-12-24 19:44
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4243

**Closed by Craluminum2413** 2024-12-24 19:44 UTC
Labels: status: new
