### ISSUE TITLE
Game crashes while using books to write

### ISSUE THREAD

**Issue by rileynr** [anegostudios/VintageStory-Issues#2776] opened 2023-05-24 02:25 UTC
### Game Version

v1.18.5

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

The game crashes while using a book and quill to write,

### How to reproduce

1. Write to the end of a page in a book
2. Flip to the next page
3. Backspace
4. The game crashes

### Logs

```Log```Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.5 (Stable)
5/23/2023 10:23:53 PM: Critical error occurred
Loaded Mods: game@1.18.5, creative@1.18.5, survival@1.18.5
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Vintagestory.GameContent.GuiDialogEditableBook.onTryTextChange(List`1 lines) in VSSurvivalMod\Systems\WritingSystem\GuiDialogEditableBook.cs:line 78
   at Vintagestory.API.Client.GuiElementEditableTextBase.LoadValue(List`1 newLines) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 281
   at Vintagestory.API.Client.GuiElementEditableTextBase.SetValue(String text, Boolean setCaretPosToEnd) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 266
   at Vintagestory.GameContent.GuiDialogReadonlyBook.updatePage(Boolean setCaretPosToEnd) in VSSurvivalMod\Systems\WritingSystem\GuiDialogReadonlyBook.cs:line 174
   at Vintagestory.GameContent.GuiDialogEditableBook.onTextChanged(String text) in VSSurvivalMod\Systems\WritingSystem\GuiDialogEditableBook.cs:line 130
   at Vintagestory.API.Client.GuiElementEditableTextBase.TextChanged() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 329
   at Vintagestory.API.Client.GuiElementEditableTextBase.OnKeyBackSpace() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 563
   at Vintagestory.API.Client.GuiElementEditableTextBase.OnKeyDown(ICoreClientAPI api, KeyEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementEditableTextBase.cs:line 429
   at Vintagestory.API.Client.GuiComposer.OnKeyDown(KeyEvent args, Boolean haveFocus) in VintagestoryApi\Client\UI\GuiComposer.cs:line 564
   at Vintagestory.API.Client.GuiDialog.OnKeyDown(KeyEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 416
   at Vintagestory.GameContent.GuiDialogReadonlyBook.OnKeyDown(KeyEvent args) in VSSurvivalMod\Systems\WritingSystem\GuiDialogReadonlyBook.cs:line 192
   at Vintagestory.Client.NoObf.GuiManager.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 361
   at Vintagestory.Client.NoObf.ClientMain.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1738
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(Object sender, KeyboardKeyEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 250
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.NativeWindowBase.OnKeyDown(Key key, Boolean repeat) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\NativeWindowBase.cs:line 130
   at OpenTK.Platform.Windows.WinGLNative.HandleKeyboard(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 646
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 828
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1551
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 369
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 5/22/2023 4:46:05 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1240568917199403651, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.5.0
P3: 64668a12
P4: KERNELBASE.dll
P5: 10.0.22621.1635
P6: 61869dd2
P7: c0020001
P8: 000000000006536c
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.49cbae09-0826-493b-854f-ea649ca130d0.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.7b7e6a5d-82bc-432f-b0ad-2f92c0c77984.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.0e98dee7-7866-47f2-8916-ee6a0c885571.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.0089df86-270c-4c54-a287-f1f0c71651ad.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.8e157392-9c20-42a4-b088-26706f9f9230.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_beeb7cca4f398a7ca68e1092eb6c1be9c55e78be_099fad0f_445358dd-3e4d-459a-bcba-34ee22ac5522

Analysis symbol: 
Rechecking for solution: 0
Report Id: bb300367-1308-4278-9215-ad8dbc981b08
Report Status: 268566528
Hashed bucket: fe47733119a2ea5b513762db7d0fba83
Cab Guid: 0 }
--------------
{ TimeGenerated = 5/22/2023 4:45:53 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.5.0, time stamp: 0x64668a12
Faulting module name: KERNELBASE.dll, version: 10.0.22621.1635, time stamp: 0x61869dd2
Exception code: 0xc0020001
Fault offset: 0x000000000006536c
Faulting process id: 0x0x1d70
Faulting application start time: 0x0x1d98ceb17da296d
Faulting application path: C:\Users\rhawk\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: bb300367-1308-4278-9215-ad8dbc981b08
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 5/22/2023 4:45:48 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FFBD0F8536C
Stack:
   at System.Environment._Exit(Int32)
   at System.Environment._Exit(Int32)
   at System.Environment.Exit(Int32)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.NativeWindow.OnClosedInternal(System.Object, System.EventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.Platform.Windows.WinGLNative.HandleDestroy(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   at OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.DestroyWindow()
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DefWindowProc(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(OpenTK.Platform.Windows.MSG ByRef)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(OpenTK.Platform.Windows.MSG ByRef)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double, Double)
   at Vintagestory.Client.ClientProgram.Start(Vintagestory.Client.ClientProgramArgs, System.String[])
   at Vintagestory.ClientNative.CrashReporter.Start(System.Threading.ThreadStart)
   at Vintagestory.Client.ClientProgram.Main(System.String[])
 }

**Comment by Craluminum2413** [comment] 2023-05-24 05:32
Duplicate of #2740

**Closed by Craluminum2413** 2023-05-24 05:32 UTC
Labels: status: new
