### ISSUE TITLE
Game crash, smelting guide, wooden tongs

### ISSUE THREAD

**Issue by VangardV** [anegostudios/VintageStory-Issues#3497] opened 2024-01-21 18:43 UTC
Game version - v1.19.1

Platform - Windows

Modded - Vanilla

SP/MP - Singleplayer

Description - Smelting guide crash 

How to reproduce - 1.  just play in world 2. open handbook  3.open guide with smelting 4. click on first wooden tongs  5. Crash 

Logs - 

 Running on 64 bit Windows 10.0.19045.0 with 16348 MB RAM
Game Version: v1.19.1 (Stable)
21.01.2024 19:25:16: Critical error occurred
Loaded Mods: game@1.19.1, creative@1.19.1, survival@1.19.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Client.LinkTextComponent.HandleLink() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\TextLinkComponent.cs:line 208
   at Vintagestory.API.Client.LinkTextComponent.Trigger() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\TextLinkComponent.cs:line 197
   at Vintagestory.API.Client.LinkTextComponent.OnMouseUp(MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\TextLinkComponent.cs:line 182
   at Vintagestory.API.Client.GuiElementRichtext.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementRichtext.cs:line 524
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 449
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 583
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 412
   at Vintagestory.Client.NoObf.ClientMain.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1874
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 208
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by radfast** [comment] 2024-01-22 13:42
Duplicate of #3496

**Closed by radfast** 2024-01-22 13:42 UTC
Labels: status: incomplete, status: can't reproduce, version: 1.19

**Comment by radfast** [comment] 2024-01-22 13:43
Although marked as a duplicate, if you can comment on which language you are using that could help track this down :)

**Comment by radfast** [comment] 2024-01-23 00:53
Please talk to the Polish translators in the Discord channel, #wiki-and-translations.   They translated the links in this guide, they should not have.   
 For example `<a href=\"handbooksearch://drewniane szczypce>` should be `<a href=\"handbooksearch://tongs\">`  Note, they also missed off this at the end `\"` which is important in formatting!
Other links in the smelting / Metallurgy 101 guide have the same problem, maybe other guides also, it's worth checking

**Comment by VangardV** [comment] 2024-01-23 17:05
Okay i will let them know, about this issue, anyway thanks for help
