### ISSUE TITLE
Vertical Racks will not place on top of blocks

### ISSUE THREAD

**Issue by VallenFrostweaver** [anegostudios/VintageStory-Issues#2841] opened 2023-06-22 12:35 UTC
### Game Version

1.18.5

### Platform

Windows

### Modded

None

### SP/MP

None

### Description

You cannot place Vertical Racks on top of any blocks (solid or otherwise). You can only place these on the side of blocks. I guess I missed this in the past due to always placing the rack in a corner.
![image](https://github.com/anegostudios/VintageStory-Issues/assets/13642054/46084854-2904-49b0-b513-7e868004d378)
I'm currently verifying if this is intended bevavior.

**Comment by Craluminum2413** [comment] 2023-06-22 12:37
It is intended

**Comment by Craluminum2413** [comment] 2023-06-22 12:38
Duplicate of #1280

**Closed by Craluminum2413** 2023-06-22 12:38 UTC
Labels: status: new

**Comment by VallenFrostweaver** [comment] 2023-06-22 13:29
Please re-open until I can confirm with the rest of the team. Thank you.
