### ISSUE TITLE
The VS server reaches 100% load

### ISSUE THREAD

**Issue by iForged** [anegostudios/VintageStory-Issues#4648] opened 2024-12-10 00:42 UTC
### Game Version

1.20.0-pre13

### Platform

Linux

### Modded

Modded

### SP/MP

Multiplayer

### Description

The issue has been persisting for over 4 weeks.
I saw Tyron's message about the memory leak in version 1.20 rc.1.

For me, it started with version 1.20 pre13. At certain moments, the server reaches 100% CPU and RAM usage (VM on Ubuntu 24.04). Interestingly, restarting the game server, the VM, or even the physical server doesn’t resolve the problem. It doesn’t depend on how many resources I allocate to the VM. I’ve allocated the maximum my server can currently provide: 24 threads and 64 GB of DDR4 RAM.

During the last such failure, to rule out potential hardware issues, I ran the server on my PC instead. As a result, the VM hit 100% load, and Windows simply killed the VM process.

The issue occurs when starting the game server, specifically at the world generation stage, although earlier stages also proceed more slowly than usual.

The only effective way to restore the server's functionality is to keep restarting it until it works properly, which takes anywhere from 3 to approximately 10 restarts.

I don’t recall this issue happening in version pre7. However, since then, server activity has grown, and peak player count is now 25.

### How to reproduce

The issue is too random; it doesn’t depend on the number of players on the server and has occurred even when there were only 3 players online. I couldn’t identify any pattern to its occurrence, and the logs didn’t provide any useful information either.

### Screenshots

![image](https://github.com/user-attachments/assets/ffa904ab-0e94-493c-9f25-46ea51df0de7)

### Logs

```Log```

**Comment by iForged** [comment] 2024-12-10 00:44
upd. I’m using only one mod on the server:
https://mods.vintagestory.at/betterruins

**Comment by radfast** [comment] 2024-12-10 01:18
It's not necessary to contact tyron on Discord to report issues! Github is the best place.

BetterRuins may be the cause: even though it only adds content not code, it adds a **lot** of content including some schematics much larger than anything in vanilla.  Any chance you can try running a multiplayer server on either your Linux hardware or your Windows VM (or both) **without** BetterRuins active, and have a few players connect to it, see what the CPU and RAM usage looks like.

The memory leak reported on Discord Status is _not_ connected with this, that was a memory leak when servers have no players on them, servers with no players are supposed to go into a dormant state but it seems that was sometimes not working, which was a big problem for servers managed in the cloud like VintageHosting but should not be a problem at all for a one-off 25 player server like yours - you don't mind if it doesn't go into a dormant sate.

1. Please post your `servermagicnumbers.json` file.  It might be an idea to turn down some of the numbers in that.
2. For a game startup when the issue occurs, please post your full `server-debug.log` file

I can locally run a 1.20-rc.1 server on half the hardware (12 threads, 32GB RAM) and it seems stable, so I'm wondering what is different on yours apart from BetterRuins.

Note that it is intended behavior that during server startup, the code might **briefly** (for around 1-2 seconds) peak at or near 100% CPU.  It does this simply because some part of startup are heavily multithreaded, to get the game started more quickly. Similar to a modern audio or video encoding package or similar app. It's not a sign of an error, and your OS should not shutdown the server just for this.

**Comment by iForged** [comment] 2024-12-10 01:46
As I mentioned earlier, this issue is too random. It used to occur twice a week. For the past four days, it hasn’t appeared. However, a new issue has emerged, where one player causes all other players on the server to crash.

When players try to reconnect to the server, they crash again. This issue resolves itself after 5-10 minutes. I’m currently in touch with the player causing the problem. Previously, I simply restarted the game server to restore functionality. Frequent restarts might be the reason why the server no longer reaches 100% load.

I’m now considering using another server for these purposes to definitively rule out a hardware-related issue.

The current failure is caused by:

ClothSystem: Calling the UpdateMesh method, which exceeds the valid list index range.
openal32.dll: The OpenAL sound module, which also triggers crashes.

**Comment by iForged** [comment] 2024-12-10 01:47
Important clarification: this issue didn’t appear immediately after launching the server. I started it in early November, but the problem only became apparent after 2-3 weeks. Before that, the server was running without any issues.

Previously, this same server hosted the pre-7 version, and then, as far as I remember, I upgraded to version 11. The server ran without any problems for about a month. Then, with the release of pre.13, the world was generated from scratch. Initially, block physics was enabled on the server, but shortly after, following an incident where a player dug down to the Earth's mantle and then caused a massive collapse that crashed the server, I believe that’s when the problems with the server began. After the second such collapse, I disabled block physics, but in the long run, this solution didn’t help.

**Comment by iForged** [comment] 2024-12-10 01:56
I’m currently discussing with the players the possibility of upgrading to version rc.1 while preserving the current world, but I strongly doubt that this will magically resolve the server’s issues. Therefore, I’m hoping for the release version and the regeneration of the world, with the transfer of player builds and loot from the current server.

I forgot to mention that my server is based on a socket 2011 platform. It has a 2 x E5-2680V4 processor and 128GB of ECC Reg DDR4 RAM.
This server also hosts other virtual machines, one of which runs Docker containers with GitLab and other microservices, and there are no performance issues there. I even tried turning off all the VMs except for the VM running the VS game server for a few days, but that didn’t resolve the problem either.

**Comment by radfast** [comment] 2024-12-10 15:06
If you are experiencing crashes on unmodded 1.20-rc.1, please post the crash report or the relevant server/client log, as a new issue on Github.  It may be we are not aware of it.  Crashes are essentially either caused by bugs in the code, or by other causes such as mods or damaged / duplicated assets (including improper installations of the game or bad updates on Linux boxes).  During the -pre release and -rc phases, there _may_ be crashes caused by bugs in the code.

The sooner the team is aware of any such issues, the sooner they will be fixed and the fixes incorporated into the next update such as -rc.2

We have already moved on some way since the pre-7 version, there is no point in trouble-shooting issues in that specific version as they may already have been fixed by updates.  In addition, worldgen in -rc.1 - especially but not only for the Story locations - will have features not seen in pre-7.  If you proceed to run a server on pre-7, your players will be missing out on the full intended generation of the new Story locations.  I don't really understand why you would want that ...

**Comment by radfast** [comment] 2024-12-10 15:11
The game is designed to support multiplayer, possibly with a few tweaks to `servermagicnumbers` to optimise things.  TOPS is a server running the vanilla game at standard settings, on ordinary commercially available server hardware (OK quite good these days), and it supports up to 70 players with consistent tick rate of around 8-10tps. 

Full block physics (topsoil collapsing), which is off by default in a standard Survival world, will increase server load at the times when larger physics events are occurring, like landslides.   But it won't produce the type of 100% CPU, 64GB RAM issues you are writing about.

I want to help you to investigate the 100% CPU, 64GB RAM issue which you first wrote about, but you need to help me to help you ... use the latest version, with no mods, and provide the servermagicnumbers as requested

**Comment by iForged** [comment] 2024-12-14 05:56
A few days have passed since the transition to rc.1, and now that rc.2 has been released, I think we'll switch to it today or tomorrow. The previously mentioned issues seem to have stopped appearing, which is great news for me! 😊
However, new problems have emerged:

1. The most pressing issue right now involves UDP and affects about 10% of players. The problem is well-documented here: https://github.com/anegostudios/VintageStory-Issues/issues/4552
2. This issue only occurred today when the server shut itself down (Server shutting down - Too many errors detected. See server-main.log file).
In the logs, these errors have been appearing for several hours:
`14.12.2024 01:31:31 [Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockToolMold.GetTraversalCost(BlockPos pos, EnumAICreatureType creatureType) in VSSurvivalMod\Block\BlockToolMold.cs:line 144
   at Vintagestory.Essentials.AStar.traversable(PathNode node, Single stepHeight, Int32 maxFallHeight, Cuboidf entityCollBox, Cardinal fromDir, Single& extraCost) in VSEssentials\Entity\Pathfinding\Astar\AStar.cs:line 141
   at Vintagestory.Essentials.WaypointsTraverser.FindPath(BlockPos startBlockPos, BlockPos targetBlockPos, Int32 searchDepth, Int32 mhdistanceTolerance) in VSEssentials\Entity\Pathfinding\Astar\WaypointsTraverser.cs:line 130
   at Vintagestory.Essentials.WaypointsTraverser.NavigateTo(Vec3d target, Single movingSpeed, Single targetDistance, Action OnGoalReached, Action OnStuck, Action onNoPath, Boolean giveUpWhenNoPath, Int32 searchDepth, Int32 mhdistanceTolerance, Nullable`1 creatureType) in VSEssentials\Entity\Pathfinding\Astar\WaypointsTraverser.cs:line 97
   at Vintagestory.GameContent.AiTaskSeekFoodAndEat.ContinueExecute(Single dt) in VSEssentials\Entity\AI\Task\TasksImpl\AiTaskSeekFoodAndEat.cs:line 194
   at Vintagestory.GameContent.AiTaskManager.OnGameTick(Single dt) in VSEssentials\Entity\AI\Task\AiTaskManager.cs:line 214
   at Vintagestory.GameContent.EntityBehaviorTaskAI.OnGameTick(Single deltaTime) in VSEssentials\Entity\AI\Task\BehaviorTaskAI.cs:line 125
   at Vintagestory.API.Common.Entities.Entity.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\Entity.cs:line 911
   at Vintagestory.API.Common.EntityAgent.OnGameTick(Single dt) in VintagestoryApi\Common\Entity\EntityAgent.cs:line 589
   at Vintagestory.Server.ServerSystemEntitySimulation.TickEntities(Single dt) in VintagestoryLib\Server\Systems\World\EntitySimulation.cs:line 332
   at Vintagestory.Server.ServerSystemEntitySimulation.OnServerTick(Single dt) in VintagestoryLib\Server\Systems\World\EntitySimulation.cs:line 144
   at Vintagestory.Server.ServerMain.Process() in VintagestoryLib\Server\ServerMain.cs:line 904`

**Comment by radfast** [comment] 2024-12-15 03:04
Please go for -rc.4 not -rc.2.  (-rc.2 had some issues as documented in the patch notes in the News area of the Vintage Story website)

**Comment by radfast** [comment] 2024-12-19 12:55
> The previously mentioned issues seem to have stopped appearing,

I'm going to close this as resolved in that case.  If the same issues as mentioned above re-appear (persistent >50% CPU load or >16GB RAM use on a server) please re-open or comment here and I will see it and re-open.

If the mentioned client-side issue about "_ClothSystem: Calling the UpdateMesh method, which exceeds the valid list index range._" recurs, please have the affected player open a new issue here and post the actual crash report or better the `client-main.log`, it is a great help to us to see the full log and stacktrace with line numbers etc.  Or you can get the info off the player and post their log on their behalf, that's up to you and them.

The same for the OpenAL errors though those are very low priority.  There are sometimes one or two OpenAL errors logged on a client which have no actual effect on gameplay (sometimes only occur during client forced shutdown due to some earlier error).

**Comment by radfast** [comment] 2024-12-19 12:59
For info:

- You should update to 1.20.0-rc.5 if you have not done so already. It fixes things without breaking anything new, so is overall good
- The UDP issue is now fixed for most people, probably around 99%. But even so in a future version we are considering dropping UDP completely as there are still some routers and ISPs which don't handle it well in ways outside our control.

**Comment by iForged** [comment] 2024-12-22 21:32
I updated to rc.5 after your message. After testing for a few days, I can provide some feedback. There are no major issues. Users occasionally experience crashes, even when simply eating a berry. With 28+ players on the server, there are noticeable delays when dropping items, but the VM load is around 12GB RAM, with 2-3 cores at 90+% usage, while the remaining 11-12 cores are at about 10%.

That the server doesn’t crash is already a success.

**Comment by radfast** [comment] 2024-12-23 02:49
If the affected users (or you) can please report the actual crashes to us here on Github, with the relevant crash report or log, there's a good chance they can be fixed in a near-future version.   Assuming they are vanilla crashes, not caused by a mod.  If it's a mod crashing (often indicated within the crash report itself) then we don't want to know about it, but you should instead report it to the mod author.

Your performance issues, when you have lots of players online, please run command `/debug logticks 80` for a minute or so, and then paste up here the corresponding extract from the log file `server-main.log` - you should be able to get readonly access to that log file in a text editor even while the server is running.   Run the exact same command again when the minute is up, to stop the logging.   This will give the coding team detailed info about how _your server_ is handling the code and what are the main causes of any delay or lag - it won't mean much to you but it will mean a lot to us.

I've chosen the `logticks 80` number intentionally to pick up anything that I would see as a slow ticks (tick rate drops to less than 12.5 tps). If that gives log spam you can pick out the even slower ticks with a higher number like `logticks 150`.

At the same time it would be helpful to see your `servermagicnumbers.json`, maybe there are things that can be improved there.

**Comment by iForged** [comment] 2024-12-25 19:18
Unfortunately, the issue with 100% CPU and RAM usage occurred again today...
![image](https://github.com/user-attachments/assets/d5dcba83-0893-4c82-873d-3322b02d0910)

I conducted a test on different hardware, and the result was the same. The logs contain a lot of messages about server overload:
`[Warning] Server overloaded. A tick took 1753ms to complete.`

There is only one error:
```
[Error] Exception: Object reference not set to an instance of an object.  
   at Vintagestory.GameContent.StoryStructuresSpawnConditions.GetStoryStructureAt(BlockPos pos) in VSSurvivalMod\Lore\StoryStructuresSpawnConditions.cs:line 132  
   at Vintagestory.GameContent.StoryStructureProtection.Event_OnTestBlockAccess(IPlayer player, BlockSelection blockSel, EnumBlockAccessFlags accessType, String& claimant, EnumWorldAccessResponse response) in VSSurvivalMod\Lore\StoryStructureProtection.cs:line 60  
   at Vintagestory.Server.ServerSystemBlockSimulation.HandleBlockInteract(Packet_Client packet, ConnectedClient client) in VintagestoryLib\Server\Systems\World\BlockSimulation.cs:line 429  
   at Vintagestory.Server.ServerSystemInventory.HandleHandInteraction(Packet_Client packet, ConnectedClient client) in VintagestoryLib\Server\Systems\Inventory.cs:line 255  
   at Vintagestory.Server.ServerMain.ProcessNetMessage(NetIncomingMessage msg, NetServer mainSocket) in VintagestoryLib\Server\ServerMainNetworking.cs:line 141
```  

After that, I restarted the server several times, but it didn’t resolve the issue, so I decided to update the server to rc.6.
After the update, the server started without any problems.

**Comment by iForged** [comment] 2024-12-25 19:19
servermagicnumbers.json
```
  "DefaultEntityTrackingRange": 4,
  "DefaultSimulationRange": 128,
  "RequestChunkColumnsQueueSize": 2000,
  "ReadyChunksQueueSize": 200,
  "ChunksColumnsToRequestPerTick": 4,
  "ChunksToSendPerTick": 192,
  "ChunkRequestTickTime": 20,
  "ChunkColumnsToGeneratePerThreadTick": 15,
  "ServerAutoSave": 300,
  "SpawnChunksWidth": 7,
  "TrackedEntitiesPerClient": 3000,
  "CalendarPacketSecondInterval": 60,
  "ChunkUnloadInterval": 4000,
  "UncompressedChunkTTL": 15000,
  "CompressedChunkTTL": 45000,
  "PlayerDesyncTolerance": 0.02,
  "PlayerDesyncMaxIntervalls": 20.0,
  "ChunkThreadTickTime": 5,
  "AntiAbuseMaxWalkBlocksPer200ms": 3,
  "AntiAbuseMaxFlySuspicions": 3,
  "AntiAbuseMaxTeleSuspicions": 8,
  "MaxPhysicsThreads": 1,
  "MaxWorldgenThreads": 1,
  "MaxEntitySpawnsPerTick": 8,
  "ServerMagicNumVersion": "1.3"
}
```

**Comment by iForged** [comment] 2024-12-25 19:26
Players started complaining about issues about 5 minutes before the server crashed.
When I connected, the load on all 14 CPU threads was already near 100%, but the RAM usage was at 9GB. Within a minute, it spiked to 28GB, after which I shut down the server.

Essentially, I’m still playing with the BetterRuins mod, which I’ve updated to version 0.4.2.
I’m hesitant to disable the mod completely because I’m concerned it might cause errors in the game related to the mod’s content.

**Comment by radfast** [comment] 2024-12-26 13:10
> Your performance issues, when you have lots of players online, please run command `/debug logticks 80` for a minute or so, and then paste up here the corresponding extract from the log file server-main.log 

This, @iForged .  I can't do any more without this.   In fact given what you have reported, I recommend running `/debug logticks 250` permanently.  That will essentially log any cause which brings the server's tick rate below 4 tps, which is about the limit of what is playable.

Please also provide your full `server-main.log` file from the server run when the issues happened yesterday, better to let the dev team have the full log, we can pick out what is relevant in your log.

**Comment by iForged** [comment] 2024-12-29 13:48
I reached out to other administrators of large servers and managed to find a possible cause of this issue. It is not related to the game or the game engine itself.
It turns out I'm not the first one to encounter this problem. This issue is caused by DDoS attacks. My server is hosted at home, and I had never used a firewall for the VS server, as I didn't expect anyone would want to target my server with DDoS attacks... How wrong I was. This issue has been confirmed by at least two other large server owners, after which I began analyzing the traffic during the last outage and found that the channel was literally overloaded with traffic from the USA and Kenya. I completely blocked the IP addresses at the 16 subnet level, and this worked...
I don't think this will be of much interest to you, but I will continue to monitor this problem.

**Comment by radfast** [comment] 2024-12-29 16:13
OK thanks for the update and info.  If you have the chance to pass this on to other server owners ever - for example on Discord - please do so.

**Closed by radfast** 2024-12-29 16:13 UTC
Labels: target: multiplayer, status: incomplete, target: performance

**Comment by iForged** [comment] 2024-12-29 21:31
The most interesting part is that all these DDoS attacks were exclusively targeted at my VintageStory server. They showed no interest in other infrastructure with open ports. Even now, they continue the attack, despite the firewall blocking them. The firewall registers approximately 270 malicious packets per second directed at the VS server port.

**Comment by radfast** [comment] 2025-03-02 23:50
For info, please try game version 1.20.5-rc.1 released today, this has some server-side mitigation of certain types of DDoS attack (disabled by default, you need to use configs to enable it).  The intention is to keep the server running through the attack, although tick rate may drop, or players may become disconnected if the server networking connection cannot support the load well enough to allow the player's playing packets through  (ie. if the network starts hard filtering traffic or dropping packets, then people won't be able to play either)
