### ISSUE TITLE
MacOS version has switched color channels and scuffed GUI

### ISSUE THREAD

**Issue by Wh4tdoes1tM4tter** [anegostudios/VintageStory-Issues#4606] opened 2024-12-05 19:26 UTC
### Game Version

v1.20

### Platform

Mac

### Modded

Vanilla

### SP/MP

None

### Description

I'm on MacOS Sequoia 15.1.1 and VS 1.20rc1, and, apparently, the color channels have swapped since 1.19 and the game now looks very blue/green and other-worldish. Also most GUI elements are not visible at all, sometimes they appear for a split second and then disappear again and even if you ever get to click the invisible Quit button or the one visible in the main menu the game instantly crashes.

### How to reproduce

Just start up or the game or quit.

### Screenshots

![Screenshot 2024-12-05 at 20 14 02](https://github.com/user-attachments/assets/d3e0a4b9-1b52-453d-aea8-e2d983520ce7)
![Screenshot 2024-12-05 at 20 13 32](https://github.com/user-attachments/assets/12d937b9-afaf-42ca-877f-b22e89cbee2a)

### Logs

```Log```
[client-main.log](https://github.com/user-attachments/files/18028603/client-main.log)

**Comment by Craluminum2413** [comment] 2024-12-05 19:54
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4327

**Closed by Craluminum2413** 2024-12-05 19:54 UTC
Labels: status: new
