### ISSUE TITLE
Crash on throwing spear

### ISSUE THREAD

**Issue by LottieVixen** [anegostudios/VintageStory-Issues#361] opened 2020-01-15 12:08 UTC
**Game Version:** 1.11.11
**Platform:** windows 10
**Modded:** Yes
**mod:** https://github.com/copygirl/CarryCapacity

### Description
throwing a spear caused a crash

### How to reproduce
not sure on steps, just tried to throw a spear

### Expected behavior
throwing the spear successfully, not causing a crash

### Logs
latest and only crash
```
Running on 64 bit Windows with 8 GB RAM 
Version: v1.11.11 (Stable)15/01/2020 11:07:27: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.ItemSpear.OnHeldInteractStop(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   at _axV7D9tLYXopUhk2HxGdemG2KbH._EWeOV4tCqqvxnHLBYDDLhaRlFTF()
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at _NG0ZnXmTtmPezIn9LSDyNwn1qcA._J9HjWf5oBFWBMSE9T0rzaB12uzM(Single )
   at _NG0ZnXmTtmPezIn9LSDyNwn1qcA._GfoBSdM3Y0SqlEpD5woPKY7P1uA(Single )
   at _UugBRzab4cvS4gP9FU16U1nCEkv._FSwYayGiaiyft0co3hAAEsCvntwA(Single )
   at _EV8yMnhtAV8IVAlRniUfLnu7sZp._maGDsIZvsWOnOdmbpKZafq8JKxcA(Single )
   at _EV8yMnhtAV8IVAlRniUfLnu7sZp._ryTdv9qG5dhCjbW6tjKjdNvxYhY(Single )
   at _k603ozcgxEWfTany0f4BuFkKaTO._cofRcWkjdUpiHnZj5DznYMVdHcb(Object , FrameEventArgs )
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _KhnygRKbChlhNVZ6NoTIj4AppFv._CZt1ULfHsOfvWyybAWFzfZAPlmN(_v0QfrgDod6R3FrQXNUcbGgdKeRI , String[] )
   at _Vfez4jOq8l9qPflsxomPO9fBnuB._CZt1ULfHsOfvWyybAWFzfZAPlmN(ThreadStart )
-------------------------------
```

**Comment by LottieVixen** [comment] 2020-01-15 12:16
Note, I have not been able to reproduce this.

**Comment by tyronx** [comment] 2020-01-17 07:19
I'm also not able to reproduce this :<

**Comment by Aledark789** [comment] 2020-04-16 21:27
Same deal: i aim my spear and once it goes off...poof crash

Running on 64 bit Windows with 16 GB RAM 
Version: v1.12.14 (Stable)2020-04-16 5:20:08 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Common.ClassRegistryAPI.CreateEntity(EntityProperties entityType)
   at Vintagestory.GameContent.ItemSpear.OnHeldInteractStop(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   at _AwTvpwXV1bHGBB8plvoGTYT5ihD._aXg8ff7JchZYkTRDnSjo139TZJH()
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at _hLaepLRCOckdCEvZTPp1GxfgrdT._gvVdZYlJjMijmkAmKtFDCvJNXax(Single )
   at _hLaepLRCOckdCEvZTPp1GxfgrdT._nu0syyqM6QcVDRvU3XOrq03zfUh(Single )
   at _wbw3WsD1ic8cZIS5Ql2MkIqPWmb._ibkrrJqCs89QNSe99xnFzRxp3sL(Single )
   at _s54YxMQ8l5DBeihbmw81nJkPTSU._RT1lBvzfhVzcDZ6jmYewDTkUdvx(Single )
   at _s54YxMQ8l5DBeihbmw81nJkPTSU._EZIJU8BLizIQdIOGgxu5BrkHzpV(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _gilSYm6aSzOct8TKUm64HAM8OHp._tyidesQGCE1oKHv8YEo8HwYCSty(_RxGTCHor7fqeGRNMEH5pZVfBHHK , String[] )
   at _xmrDk9pogtvR6xvbzmBc2dtFsbu._tyidesQGCE1oKHv8YEo8HwYCSty(ThreadStart )
-------------------------------

**Comment by copygirl** [comment] 2020-04-16 21:29
@Aledark789 I'm assuming you're using a more recent game version. Can you tell us which?

**Comment by Aledark789** [comment] 2020-04-16 21:32
> 
> 
> @Aledark789 I'm assuming you're using a more recent game version. Can you tell us which?
v1.12.14

**Comment by tyronx** [comment] 2020-04-17 09:18
@Aledark789 any mods installed, beyond the vanilla ones?

**Comment by Aledark789** [comment] 2020-04-17 10:21
> 
> 
> @tyronx  any mods installed, beyond the vanilla ones?
Sorry first time i do bug report on game and github. Learning curve :)

1_12.14-VSHUD-1.4.2
599465123_PrinzipsOreThemepack
1432606610_lazytweaksv1.8.1
btaquivers_v0.1.0
CarryCapacity-0.4.9
NoNegativeArmor-1.0.0
orecrystals_v1.1.3
VS-1.12.14-Immersion-1.2.3
xleveling_v0.1.4
xskills_v0.1.4

**Comment by tyronx** [comment] 2020-04-19 12:21
I've heard reports that the immersion mod has crashing issues with spears. I'd try to disable that one.

**Comment by Aledark789** [comment] 2020-04-19 12:23
> 
> 
> I've heard reports that the immersion mod has crashing issues with spears. I'd try to disable that one and/or all of them to verify its a mod that causes it.

Alright i'll create a game just to verify this.

Thanks @tyronx

**Comment by Aledark789** [comment] 2020-04-21 19:54
> 
> 
> > I've heard reports that the immersion mod has crashing issues with spears. I'd try to disable that one and/or all of them to verify its a mod that causes it.
> 
> Alright i'll create a game just to verify this.
> 
@tyronx you are right tyron when i turn off immersion, it no longer crashes however i enjoy all their add-ons. I went and posted on their github and in the forum thread.

**Comment by copygirl** [comment] 2021-05-29 18:27
Something in 1.15.0-pre.2 release notes mentions spear crash having been fixed so I will close this issue for now.

**Closed by copygirl** 2021-05-29 18:27 UTC
Labels: status: resolved, target: survival, type: crash
