### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by Thief2122** [anegostudios/VintageStory-Issues#2385] opened 2023-02-17 20:32 UTC
### Game Version

v1.17.11

### Platform

Windows

### Modded

Vanilla

### SP/MP

Multiplayer

### Description

try to join friends server but it just crashes while joining

### Logs

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.11 (Stable)
2/17/2023 12:27:41 PM: Critical error occurred
Loaded Mods: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line 407
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 718
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 622
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 124
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2/17/2023 12:20:26 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2102517163793815581, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.11.0
P3: 10.0.22000.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\MLGPR\AppData\Local\Temp\RDR7527.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.67b39427-cc91-42e7-9f3a-4e309d89a3ab.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.85812674-8882-435d-bdea-60ed6b3288c0.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.d43f3a50-e0f9-4119-99e6-07119fdb76e9.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.5506ed8c-0031-43cc-80ed-2fb2f14dfec1.tmp.txt

**Comment by Craluminum2413** [comment] 2023-02-17 20:58
Duplicate of #2380

**Closed by Craluminum2413** 2023-02-17 20:58 UTC
Labels: status: new
