### ISSUE TITLE
Harvesting resin from trees with a knife does crash players

### ISSUE THREAD

**Issue by WickedSchnitzel** [anegostudios/VintageStory-Issues#2681] opened 2023-04-29 15:54 UTC
### Game Version

1.18.1

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Logs

```Running on 64 bit Windows with 8 GB RAM 
Game Version: v1.18.1 (Stable)
29.04.2023 16:13:26: Critical error occurred
Loaded Mods: 
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'The ThreadLocal object has been disposed.'.
   at System.Threading.ThreadLocal`1.GetValueSlow()
   at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionStatesNative(IWorldAccessor world, ItemSlot inslot) in VintagestoryApi\Common\Collectible\Collectible.cs:line 2283
   at Vintagestory.API.Common.CollectibleObject.AppendPerishableInfoText(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1650
   at Vintagestory.API.Common.CollectibleObject.GetHeldItemInfo_Patch0(CollectibleObject this, ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo)
   at Vintagestory.API.Common.Block.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 2173
   at Vintagestory.API.Common.ItemStack.GetDescription(IWorldAccessor world, ItemSlot inSlot, Boolean debug) in VintagestoryApi\Common\Collectible\ItemStack.cs:line 403
   at Vintagestory.GameContent.GuiHandbookItemStackPage..ctor(ICoreClientAPI capi, ItemStack stack) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 42
   at Vintagestory.GameContent.ModSystemHandbook.onCreatePagesAsync() in VSSurvivalMod\Systems\Handbook\Handbook.cs:line 79
   at Vintagestory.GameContent.GuiDialogHandbook.LoadPages_Async() in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 489
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 29.04.2023 7:52:34, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Vintagestory.Common.BlockTypeNet.ReadBlockTypePacket(Packet_BlockType, Vintagestory.API.Common.IWorldAccessor, Vintagestory.Common.ClassRegistry)
   at Vintagestory.Client.NoObf.ClientSystemStartup.PopulateBlocks(Vintagestory.API.Common.Block[], Int32, Int32)
   at Vintagestory.Client.NoObf.ClientSystemStartup.LoadBlockTypes()
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step1()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }
--------------
{ TimeGenerated = 02.04.2023 17:12:36, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.17.11.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 38ac

Start Time: 01d96541602656fe

Termination Time: 36

Application Path: D:\Users\Grigoriewich\AppData\Roaming\Vintagestory165\Vintagestory.exe

Report Id: e8d1cdc0-510f-450f-aed4-5766f0a586d0

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
--------------
{ TimeGenerated = 02.04.2023 11:48:25, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException
   at System.Threading.ThreadLocal`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetValueSlow()
   at Vintagestory.API.Common.CollectibleObject.UpdateAndGetTransitionStatesNative(Vintagestory.API.Common.IWorldAccessor, Vintagestory.API.Common.ItemSlot)
   at Vintagestory.API.Common.CollectibleObject.AppendPerishableInfoText(Vintagestory.API.Common.ItemSlot, System.Text.StringBuilder, Vintagestory.API.Common.IWorldAccessor)
   at DynamicClass.Vintagestory.API.Common.CollectibleObject.GetHeldItemInfo_Patch0(Vintagestory.API.Common.CollectibleObject, Vintagestory.API.Common.ItemSlot, System.Text.StringBuilder, Vintagestory.API.Common.IWorldAccessor, Boolean)
   at Vintagestory.API.Common.ItemStack.GetDescription(Vintagestory.API.Common.IWorldAccessor, Vintagestory.API.Common.ItemSlot, Boolean)
   at Vintagestory.GameContent.GuiHandbookItemStackPage..ctor(Vintagestory.API.Client.ICoreClientAPI, Vintagestory.API.Common.ItemStack)
   at Vintagestory.GameContent.GuiDialogHandbook.BuildPages_Async(System.Collections.Generic.List`1<Vintagestory.API.Common.ItemStack>)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 }```

**Comment by Craluminum2413** [comment] 2023-04-29 16:45
Probably related to some mod

**Comment by radfast** [comment] 2023-04-29 17:31
Believed to be an **Ancient Tools** issue.  Do you have Ancient Tools, @WickedSchnitzel ?

**Comment by WickedSchnitzel** [comment] 2023-04-29 18:05
> Believed to be an **Ancient Tools** issue. Do you have Ancient Tools, @WickedSchnitzel ?

Yes, we do

**Comment by radfast** [comment] 2023-04-29 18:26
If possible, disable Ancient Tools, and then try harvesting resin with a knife, let us know if the game still crashes.

If there is no crash with Ancient Tools disabled, please close this issue and report to the mod author instead.  (The mod author can contact me or tyron if they believe code in the game engine or API is causing the crash.)

**Comment by noelle-lavenza** [comment] 2023-04-29 23:59
This crash is actually different than the one that seems to be associated with Ancient Tools, I think. The one we've been seeing is on BehaviorHarvestable.cs line 100, in BlockBehaviorHarvestable.OnBlockInteractStop. https://github.com/anegostudios/vssurvivalmod/blob/6eaaaedf85fb26cee94f2af35e2907ec7f5da8af/BlockBehavior/BehaviorHarvestable.cs#L100
This crashlog seems to be either from a different crash, or is unrelated to harvesting resin.

**Comment by radfast** [comment] 2023-04-30 05:49
I have assumed that this issue is actually reporting the `BlockBehaviorHarvestable.OnBlockInteractStop` crash but the wrong crashlog has been provided ...

**Comment by noelle-lavenza** [comment] 2023-05-10 15:16
Figured it out. https://github.com/anegostudios/vssurvivalmod/blob/1d2bfd39003969ca91da8183b98985a06c54ded8/BlockBehavior/BehaviorHarvestable.cs#L112-L113C47
```cs
                ItemStack stack = harvestedStack.GetNextItemStack(dropRate);
                var origStack = stack.Clone();
```
if your drop rate is <100%, like if you're a tailor or blackguard, stack can be null, so stack.Clone causes a null reference exception.

**Comment by radfast** [comment] 2023-05-11 13:52
Fixed in next release.  It appears the issue occurs only with Tailor or Blackguard classes which have a chance of no item drop. 
 Thank you for reporting @WickedSchnitzel and your patience.  Big thanks to @noelle-lavenza for finding the cause.

**Closed by radfast** 2023-05-11 13:52 UTC
Labels: status: incomplete
