### ISSUE TITLE
Client crash when in cave ruin during removal of metal rubble on the floor

### ISSUE THREAD

**Issue by ncottrill** [anegostudios/VintageStory-Issues#2542] opened 2023-04-05 21:15 UTC
### Game Version

v1.18.0-rc.2

### Platform

Windows

### Modded

Modded

### SP/MP

Multiplayer

### Description

When clearing out a pile of metal rubble next to a translocator in a ruin, the client crashes.

### How to reproduce

Go to a cave ruin with a translocator in it and a bunch of rubble and clutter around. Clear everything out except the metal rubble on the floor near the translocator. This should all work fine.

But, when you go to try to mine the metal rubble away from the translocator (see yellow rectangle in the image), my client crashes.

### Screenshots

![image](https://user-images.githubusercontent.com/14022160/230212829-c8cd18ad-f045-46e0-b3fb-6e9af30fd96c.png)

### Logs

```Log```
[crash-removing-rubble.txt](https://github.com/anegostudios/VintageStory-Issues/files/11163166/crash-removing-rubble.txt)

**Comment by Craluminum2413** [comment] 2023-04-05 21:17
Duplicate of #2527

**Closed by Craluminum2413** 2023-04-05 21:17 UTC
Labels: status: new
