### ISSUE TITLE
Falling snow onto undug charcoal causes items to be unable to be picked up

### ISSUE THREAD

**Issue by causticjay** [anegostudios/VintageStory-Issues#4825] opened 2024-12-29 03:16 UTC
### Game Version

1.20.0-rc.6

### Platform

Windows

### Modded

None

### SP/MP

Singleplayer

### Description

Today I updated to the latest 1.20.0-rc.6 version. I was playing for hours with no issues. When I went to destroy undug charcoal stacks that were covered in snow to harvest charcoal the game stopped letting me pick up any blocks or items. I have exited and reloaded the world, restarted Vintage Story and reloaded the world, and restarted my PC then reloaded the world and I still can not pick up any items. 

Based off two other bugs reported in the VS discord, I think if a block falls due to gravity (gravel or snow) on to a not-full stack of undug charcoal the game breaks. 

### How to reproduce

1. Create charcoal.
2. Have a gravity-affected block above the undug charcoal (I believe both snow and gravel have caused this).
3. Cause the gravity-affected block to fall onto a stack of undug charcoal. 

### Logs

[client-main.log](https://github.com/user-attachments/files/18268332/client-main.log)
[server-main.log](https://github.com/user-attachments/files/18268333/server-main.log)

**Comment by pizza2004** [comment] 2024-12-29 05:36
Duplicate of #4815.

**Closed by pizza2004** 2024-12-29 05:36 UTC
Labels: status: new
