### ISSUE TITLE
Beehive kiln cannot be completed.

### ISSUE THREAD

**Issue by shasdhhs** [anegostudios/VintageStory-Issues#4782] opened 2024-12-24 04:44 UTC
### Game Version

1.20.rc5

### Platform

PC

### Modded

Vanilla

### SP/MP

SP

### Description

While building the beehive kiln, refractory bricks of any tier are counted as invalid blocks in the structure. Iron hatch doors and gratings are okay though.

### How to reproduce

Place down a kiln door, shift click it to create the hologram,place refractory bricks, then shift click the door again. The outlines of the refractory bricks will be red, showing that they are not valid ( even though they should be ).

### Screenshots

![2024-12-23_23-44-02](https://github.com/user-attachments/assets/eac6d7e9-3efb-4d87-ae81-92fb5a6f1883)

### Logs

```Crash```

**Comment by pizza2004** [comment] 2024-12-24 04:57
Duplicate of https://github.com/anegostudios/VintageStory-Issues/issues/4721

**Closed by pizza2004** 2024-12-24 04:57 UTC
Labels: status: new

**Comment by radfast** [comment] 2024-12-24 17:39
@shasdhhs you should find this issue is fixed in latest build 1.20.0-rc.6 made available today
