### ISSUE TITLE
Long ladder issues

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#1053] opened 2021-06-25 07:36 UTC
**Game Version:** 1.15 pre 6
**Platform:** Windows 
**Modded:** No 

### Description
Breaking a ladder only breaks ~15ish ladders on top of it.
Similarly, after a certain distance (I think ~15ish again), right-clicking bottom ladders consumes the item but doesn't put a ladder on top.

### How to reproduce
1. Make a ladder that's 16+ long
2. break the bottom

### Expected behavior
All ladders to fall

### Screenshots
![image](https://user-images.githubusercontent.com/12073699/123388109-4c0c3a80-d54d-11eb-9552-22af3e445a89.png)

**Comment by Craluminum2413** [comment] 2021-06-25 08:30
Duplicate of #828

**Comment by sirStroam** [comment] 2021-06-25 08:44
Thanks
Closing

**Closed** 2021-06-25 08:43 UTC
Labels: status: new, type: bug
