### ISSUE TITLE
Trying to pick up aged armor stand caused crash

### ISSUE THREAD

**Issue by Thor8472** [anegostudios/VintageStory-Issues#4240] opened 2024-10-06 07:55 UTC
### Game Version

1.20 pre 5

### Platform

Windows

### Modded

Modded

### SP/MP

Singleplayer

### Description

see title

### How to reproduce

try to pick it up

### Screenshots

![2024-10-06_09-55-05](https://github.com/user-attachments/assets/94a5eb9c-e513-405a-bd9a-d4c7f2de18cc)

### Logs

Running on 64 bit Windows 10.0.19045.0 with 32540 MB RAM
Game Version: v1.20.0-pre.5 (Unstable)
06.10.2024 09:52:48: Critical error occurred
Loaded Mods: chiseltools@1.11.5, game@1.20.0-pre.5, vtr@4.0.4, egocaribautomapmarkers@3.1.0, betterfirepit@1.1.4, betterruins@0.3.7, commonlib@2.4.0, heatretention@1.0.2, hudclock@3.4.0, prospecttogether@1.3.0, creative@1.20.0-pre.5, vsimgui@1.1.3, survival@1.20.0-pre.5, configlib@1.3.11, playercorpse@1.9.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.EntityArmorStand.OnInteract(EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode) in VSSurvivalMod\Entities\EntityArmorStand.cs:line 59
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsNoBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 394
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 818
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1022
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 05.10.2024 09:20:47, Site = , Source = Application Error, Message = Name der fehlerhaften Anwendung: Vintagestory.exe, Version: 1.20.0.0, Zeitstempel: 0x66470000
Name des fehlerhaften Moduls: coreclr.dll, Version: 7.0.1023.36312, Zeitstempel: 0x64b06d6c
Ausnahmecode: 0xc0000005
Fehleroffset: 0x00000000001c98a6
ID des fehlerhaften Prozesses: 0x78a8
Startzeit der fehlerhaften Anwendung: 0x01db16f2eacc391a
Pfad der fehlerhaften Anwendung: C:\Users\Thor\AppData\Roaming\Vintagestory1.20pre\Vintagestory.exe
Pfad des fehlerhaften Moduls: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.10\coreclr.dll
Berichtskennung: ccd8116c-a608-41a6-982c-c6630db2925c
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:  }

**Comment by Craluminum2413** [comment] 2024-10-06 09:21
Duplicate of #4183

**Closed by Craluminum2413** 2024-10-06 09:21 UTC
Labels: status: new
