### ISSUE TITLE
Tree artifact

### ISSUE THREAD

**Issue by sirStroam** [anegostudios/VintageStory-Issues#1051] opened 2021-06-24 07:46 UTC
**Game Version:** 1.15 pre 3
**Platform:** Windows 
**Modded:** No

### Description
Cutting down trees sometimes leaves artifacts that remain until chunk is reloaded

### How to reproduce
1. Cut down a bunch of trees. Works best with taller trees.

### Expected behavior
No artifacts

### Screenshots
![image](https://user-images.githubusercontent.com/12073699/123223239-932ef880-d485-11eb-8385-6ac802d1a863.png)

**Comment by Craluminum2413** [comment] 2021-06-24 08:15
Duplicate of #828

**Closed** 2021-06-24 09:40 UTC
Labels: status: duplicate
