### ISSUE TITLE
Crash when creating new game 1.15.0-pre

### ISSUE THREAD

**Issue by jamiroph** [anegostudios/VintageStory-Issues#901] opened 2021-05-25 18:02 UTC
**Game Version:** 1.15.0-pre
**Platform:** Windows
**Modded:** No

### Description
Updated game using exe from account download page. Emptied mods directory and tried to create new world in single player, world fails to load with included crash report

### How to reproduce
1. Update from 1.14.10 to 1.15.0-pre (choose upgrade in wizard)
2. Disable all mods and create new world in single player
3. It crashes

### Expected behavior
World generation/load to complete without crash

### Logs
```
Crash Report Exception:
Running on 64 bit Windows with 32 GB RAM 
Version: v1.15.0-pre.1 (Unstable)25/05/2021 18:57:08: Critical error occurred
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at _hbUyCC3cATVAykxaAlEBjKdgWtnA._SouwGBCwt3vt19dhJpiDcgkZ21N(Boolean )
   at _gZDhzP3Tg63cu5tNZrkD3Dahswb._cyQdbN4D1GDMZDxelJi2miAKq5RA()
   at _gZDhzP3Tg63cu5tNZrkD3Dahswb..ctor(_s8KgWeJlIYNXma8EsZDJOscF1VA , _llHcxa89DarSoaUgdS8JwCmrYpv )
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at _s8KgWeJlIYNXma8EsZDJOscF1VA._YClF0gBClh2j6z6wTMzohhllQRO(Type )
   at _A8WotwW2tf2CQ2lXhVedUYnpcxT._dX4cYtH4rtqfp8qkFQZRALmAGiO()
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElement.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiElementTextButton.OnMouseUp(ICoreClientAPI api, MouseEvent args)
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse)
   at _llHcxa89DarSoaUgdS8JwCmrYpv._7FWcaHQOPkJazhbD1ceYYZm7C1H(MouseEvent )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _Sfca4roOb4ikuKbMulRniUxARF4._0ytRimz1XDNkGpyxJcZbGf9Oxbd(_YzYAgXNLrh0iXJRtlZnQ7TqOSZX , String[] )
   at _hNqfhVOk3ksmv0cZQgnBG2cCt6o._0ytRimz1XDNkGpyxJcZbGf9Oxbd(ThreadStart )
-------------------------------
System.NullReferenceException: Object reference not set to an instance of an object.
   at _hbUyCC3cATVAykxaAlEBjKdgWtnA._SouwGBCwt3vt19dhJpiDcgkZ21N(Boolean )
   at _gZDhzP3Tg63cu5tNZrkD3Dahswb._cyQdbN4D1GDMZDxelJi2miAKq5RA()
   at _gZDhzP3Tg63cu5tNZrkD3Dahswb..ctor(_s8KgWeJlIYNXma8EsZDJOscF1VA , _llHcxa89DarSoaUgdS8JwCmrYpv )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 25/05/2021 18:56:55, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.15.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 1014

Start Time: 01d7518f2ee271ab

Termination Time: 12

Application Path: I:\Games\Vintagestory\Vintagestory\Vintagestory.exe

Report Id: 7dffa379-d160-4c24-a8de-e30624e05b67

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
--------------
{ TimeGenerated = 25/05/2021 18:56:55, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.0.0
P3: 60aa9427
P4: 86d0
P5: 134217728
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC587.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC588.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC597.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC5A7.tmp.txt
\\?\C:\Users\James\AppData\Local\Temp\WERCC11.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_Vintagestory.exe_2ed958da1011a864ebfb3f2b93c160ccb59183_cdf018de_9bea6c44-c289-46bd-a1e2-4855853cb35e

Analysis symbol: 
Rechecking for solution: 0
Report Id: 7dffa379-d160-4c24-a8de-e30624e05b67
Report Status: 97
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 07/05/2021 17:27:26, Site = , Source = Windows Error Reporting, Message = Fault bucket 1999085723610005733, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.14.10.0
P3: 10.0.19042.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\James\AppData\Local\Temp\RDRD49D.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD49E.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD4AF.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD4BC.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD4CD.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: caf3b246-b646-4ba3-851f-c015a3c9acfc
Report Status: 268435456
Hashed bucket: ee3def5252484136fbbe2ddfbf5440e5
Cab Guid: 0 }

```

**Comment by Craluminum2413** [comment] 2021-05-25 18:12
duplicate of #888 ?

**Comment by jamiroph** [comment] 2021-05-25 18:27
Yes! I believe so, I removed the mods from the folder eventually but I now have the same issue in that clicking create world will crash the game.

**Comment by jamiroph** [comment] 2021-05-25 18:46
I can confirm after renaming AppData directory (thanks to comment from CopyGirl in other issue thread) I was able to create a world and have it load without issue

**Comment by copygirl** [comment] 2021-05-25 19:11
Will close as duplicate for now.

**Closed by copygirl** 2021-05-25 19:11 UTC
Labels: status: duplicate
