### ISSUE TITLE
Undesired items can take place in "liquid slot" of barrel crafting

### ISSUE THREAD

**Issue by darnuria** [anegostudios/VintageStory-Issues#531] opened 2020-05-16 18:47 UTC
**Game Version:** v1.12.14 (Stable)
**Platform:** Linux, Ubuntu 18.04.4 LTS
**Modded:** Yes only VSHUD Novocain mod
**Processor:** Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
**MonoVersion:** C# Framework: Mono 6.8.0.105 (tarball Tue Feb 4 21:20:20 UTC 2020)
**Gamemode**: Survival solo/ multiplayer

### Description

While barrel crafting cured meat, meat can take the place of salf in the recipe.
Can lead to the problem where meat is lost because it's impossible to get a good ratio with salt.

The "stucked" meat can decay but it's really slow got 125*4 hours to decay.

It's possible to reproduce the bug with rot instead of salt.

### How to reproduce

The key point is to swap quickly the window of time is not so small, and can happens while normal play through.

0.0 (not sure if account) Be in a cellar
0. Place a barrel
1. Open GUI barrel
2. Place meat before salt 32 or 64
3. Place salt BUT quickly replace with meat
4. Get meat in the "buffer" slot of the salt
5.a you are lucky you placed 32 meat it's OK you can get the recipe by adding salt
5.b you placed 64 meat it's stuck.

Happened in multiplayer on chrometech, reproducible on creative and gamemode set to survival.

### Screenshot
Before
![Screenshot from 2020-05-16 20-38-45](https://user-images.githubusercontent.com/2827553/82127732-2ba07700-97b6-11ea-8e79-c61c33caaed8.png)

After
![Screenshot from 2020-05-16 20-38-49](https://user-images.githubusercontent.com/2827553/82127736-33601b80-97b6-11ea-88fa-678975727e63.png)
![Screenshot from 2020-05-16 20-38-53](https://user-images.githubusercontent.com/2827553/82127787-7e7a2e80-97b6-11ea-9bd8-08156ba153fa.png)

Whops
![Screenshot from 2020-05-16 20-50-33](https://user-images.githubusercontent.com/2827553/82127888-1a0b9f00-97b7-11ea-91f3-da6ee7ecd824.png)

Other exemple with 32 meat
![Screenshot from 2020-05-16 20-39-36](https://user-images.githubusercontent.com/2827553/82127757-4d016300-97b6-11ea-8f4a-227c17807b1c.png)

Hopefully it rot and it's possible to process it in compost:
![Screenshot from 2020-05-16 20-54-54](https://user-images.githubusercontent.com/2827553/82127979-a4ec9980-97b7-11ea-8098-e92cd438d844.png)

Can trigger it with salt + rot.
![Screenshot from 2020-05-16 20-56-36](https://user-images.githubusercontent.com/2827553/82128003-d6fdfb80-97b7-11ea-8c17-bb09ea3ecddf.png)

**Comment by tyronx** [comment] 2020-07-29 12:22
thanks for the thorough report! I currently cannot reproduce this in v1.13-pre.10. I do remember fixing some things related to the barrel in v1.13 so please let me know if this is still happening in 1.13

**Comment by Craluminum2413** [comment] 2021-06-17 10:54
Can't reproduce in 1.15.0-pre.3 (I think this was fixed in 1.13 version)

**Closed** 2021-06-17 11:53 UTC
Labels: status: incomplete, type: bug
